import {lazy,Suspense,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {BookOpen,Play,Search,Clock3,ArrowRight,Plus,Settings2,Users,Award,ShieldCheck,MoreHorizontal,Pencil,GraduationCap} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {QueryError} from '@/components/hr/Operations';
import {Input,Note,Pager,Toggle,text,today,useSave,type Directory} from '@/components/hr/EmployeeServiceUI';
import {useDebounced} from '@/components/communications/HubControls';
import type {CourseDefinition} from '@shared/employee-services';
import type {InductionBrand,InductionSettings} from '@shared/induction';
import {CourseCover,LearningProgress,durationLabel} from './LearningVisuals';
import MyLearning from './MyLearning';
import type {Records} from './InductionReports';
const InductionAuthor=lazy(()=>import('./InductionAuthor'));
const InductionBrandEditor=lazy(()=>import('./InductionAuthor').then(m=>({default:m.InductionBrandEditor})));
const InductionPlayer=lazy(()=>import('./InductionPlayer'));
const InductionReports=lazy(()=>import('./InductionReports'));
const InductionSafetyLibrary=lazy(()=>import('./InductionSafetyLibrary'));
const base='/api/learning/induction';
type Context={brand:{version:number;config:InductionBrand};canManage:boolean;canReport:boolean;canConfigure:boolean;storage:boolean;limits:Record<string,number>};
type Course={id:number;version:number;definition:CourseDefinition;publishedRelease:{id:number;releaseNumber:number;lessonCount:number;questionCount:number;settings:InductionSettings}|null;hasDraft:boolean;canSelfEnroll?:boolean;selfEnrollmentNote?:string|null;ownEnrollment?:{id:number;status:string;progress:number}|null};
type Courses={items:Course[];total:number};
type SelectedEmployee={id:number;name:string;code:string};
const enrollmentFromLocation=()=>{const value=Number(new URLSearchParams(window.location.search).get('enrollment'));return Number.isSafeInteger(value)&&value>0?value:null;};
const enrollmentLabel=(row:NonNullable<Course['ownEnrollment']>)=>row.status==='completed'?'Review course':row.status==='requested'?'Awaiting approval':row.status==='completion_submitted'?'Awaiting review':row.status==='failed'?'View next steps':row.progress?'Continue learning':'Start learning';

export default function InductionAcademy(){
  const [tab,setTab]=useState('catalogue'),[q,setQ]=useState(''),[page,setPage]=useState(1),[editor,setEditor]=useState<number|null|undefined>(),[selected,setSelected]=useState<number|null>(enrollmentFromLocation),[assignment,setAssignment]=useState<Course|null>(null),[preview,setPreview]=useState<Course|null>(null),[filter,setFilter]=useState('all');
  const search=useDebounced(q);
  const context=useQuery<Context>({queryKey:[base+'/context']}),courses=useQuery<Courses>({queryKey:[base+'/courses',{q:search,offset:(page-1)*25,filter}],enabled:tab==='catalogue'&&editor===undefined&&!selected});
  const mine=useQuery<Records>({queryKey:[base+'/records',{mine:'true',q:'',status:'',offset:0}],enabled:!selected&&editor===undefined});
  if(!context.data)return <div className="space-y-3"><QueryError error={context.error}/>{context.isLoading?<p role="status">Loading your academy…</p>:<Button variant="outline" onClick={()=>context.refetch()}>Reload academy</Button>}</div>;
  const {brand,canManage,canReport,canConfigure}=context.data;
  const openEnrollment=(id:number|null)=>{setSelected(id);setPreview(null);const url=new URL(window.location.href);if(id)url.searchParams.set('enrollment',String(id));else url.searchParams.delete('enrollment');window.history.replaceState(window.history.state,'',url.pathname+url.search+url.hash);};
  const loading=<p role="status" className="p-6">Opening learning workspace…</p>;
  if(selected)return <Suspense fallback={loading}><InductionPlayer key={selected} id={selected} onBack={()=>openEnrollment(null)}/></Suspense>;
  if(editor!==undefined)return <Suspense fallback={loading}><InductionAuthor courseId={editor||undefined} onClose={()=>{setEditor(undefined);setTab('catalogue');}} onSaved={()=>setTab('catalogue')}/></Suspense>;
  const next=mine.error?undefined:mine.data?.items.find(row=>row.status==='in_progress')||mine.data?.items.find(row=>row.status==='approved');
  const visible=courses.data?.items||[];
  const tabs=[{id:'catalogue',label:'Explore',Icon:BookOpen},{id:'mine',label:'My learning',Icon:Play},...(canReport?[{id:'records',label:'Team progress',Icon:Users}]:[])];
  return <div className="learning-academy space-y-6">
    <header className="learning-hero"><div className="learning-hero-copy"><span className="learning-eyebrow"><GraduationCap className="h-4 w-4"/>{brand.config.organizationName}</span><h1>{brand.config.academyTitle}</h1><p>{brand.config.welcomeText}</p><div className="learning-hero-actions"><Button onClick={()=>{setTab('catalogue');document.getElementById('academy-catalog')?.scrollIntoView({behavior:'smooth',block:'start'});}} className="gap-2">Explore courses<ArrowRight className="h-4 w-4"/></Button><Button variant="outline" className="gap-2" onClick={()=>setTab('mine')}><Play className="h-4 w-4"/>My learning</Button></div></div><div className="learning-hero-image"><CourseCover course={{title:'Welcome',coverImage:'welcome'}} eager/></div></header>
    {next&&<button className="learning-resume" onClick={()=>openEnrollment(next.id)}><span className="learning-resume-icon"><Play/></span><span className="min-w-0 flex-1 text-left"><small>CONTINUE LEARNING</small><strong>{next.title}</strong><span>{next.progress}% complete{next.dueDate?` · Due ${next.dueDate}`:''}</span></span><ArrowRight className="h-5 w-5 shrink-0"/></button>}
    <Tabs value={tab} onValueChange={setTab} id="academy-catalog">
      <div className="learning-navigation"><TabsList aria-label="Learning sections">{tabs.map(item=><TabsTrigger key={item.id} value={item.id} className="gap-2"><item.Icon className="h-4 w-4"/>{item.label}</TabsTrigger>)}{['library','branding'].includes(tab)&&<TabsTrigger value={tab}>{tab==='library'?'Safety library':'Branding'}</TabsTrigger>}</TabsList>{(canManage||canConfigure)&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className="gap-2" aria-label="Manage academy"><Settings2 className="h-4 w-4"/><span className="hidden sm:inline">Manage</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{canManage&&<><DropdownMenuItem onSelect={()=>setEditor(null)}><Plus/>Create course</DropdownMenuItem><DropdownMenuItem onSelect={()=>setTab('library')}><ShieldCheck/>Safety course library</DropdownMenuItem></>}{canConfigure&&<DropdownMenuItem onSelect={()=>setTab('branding')}><Settings2/>Academy branding</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>}</div>
      <TabsContent value="mine" className="pt-5"><MyLearning onOpen={openEnrollment} onBrowse={()=>setTab('catalogue')}/></TabsContent>
      <TabsContent value="records" className="pt-5">{canReport&&<Suspense fallback={loading}><InductionReports onOpen={openEnrollment}/></Suspense>}</TabsContent>
      <TabsContent value="library" className="pt-5">{canManage&&<Suspense fallback={loading}><InductionSafetyLibrary onEdit={setEditor} onCatalogue={()=>setTab('catalogue')}/></Suspense>}</TabsContent>
      <TabsContent value="branding" className="pt-5">{canConfigure&&<Suspense fallback={loading}><InductionBrandEditor onClose={()=>setTab('catalogue')}/></Suspense>}</TabsContent>
      <TabsContent value="catalogue" className="space-y-5 pt-5">
        <div className="learning-section-heading"><div><h2>Find your next course</h2><p>Build confidence, one lesson at a time.</p></div>{canManage&&<Button variant="outline" size="sm" onClick={()=>setEditor(null)} className="gap-2"><Plus className="h-4 w-4"/>Create course</Button>}</div>
        <div className="learning-catalog-toolbar"><label className="learning-search"><Search/><input aria-label="Search courses" placeholder="What would you like to learn?" value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setPage(1);}}/></label><div className="learning-filter-pills" role="group" aria-label="Course filters">{[{id:'all',label:'All courses'},{id:'required',label:'Required induction'},{id:'self',label:'Self-enrollment'},...(canManage?[{id:'draft',label:'Drafts'}]:[])].map(item=><button key={item.id} aria-pressed={filter===item.id} onClick={()=>{setFilter(item.id);setPage(1);}}>{item.label}</button>)}</div></div>
        <QueryError error={courses.error}/>{courses.error&&<Button variant="outline" onClick={()=>courses.refetch()}>Reload courses</Button>}
        {courses.isLoading&&<div className="learning-course-grid" role="status" aria-label="Loading courses">{[1,2,3].map(key=><div key={key} className="course-skeleton"><div/><span/><span/></div>)}</div>}
        <div className="learning-course-grid">{!courses.error&&visible.map(course=>{
          const release=course.publishedRelease,settings=release?.settings,available=!!release&&course.definition.status!=='archived',own=course.ownEnrollment;
          return <article key={course.id} className="learning-course-card"><button className="course-cover-button" onClick={()=>setPreview(course)} aria-label={`Preview ${course.definition.title}`}><CourseCover course={course.definition}/><span className="course-image-tag">{course.definition.status==='archived'?'Archived':!release?'Draft':settings?.mandatoryForOnboarding?'Required induction':'Self-paced'}</span><span className="course-preview-icon"><ArrowRight/></span></button>
            <div className="course-card-body"><span className="course-provider">{course.definition.provider}</span><h3><button onClick={()=>setPreview(course)}>{course.definition.title}</button></h3><p className="course-description">{course.definition.description}</p><div className="course-meta"><span><Clock3/>{durationLabel(course.definition.durationMinutes)}</span>{release&&<span><BookOpen/>{release.lessonCount} lessons</span>}</div>{own&&<LearningProgress value={own.progress} label="Your progress"/>}
              <div className="course-card-actions flex gap-2"><Button className="min-w-0 flex-1 gap-2" variant={own?.status==='completed'?'outline':'default'} onClick={()=>own?openEnrollment(own.id):setPreview(course)}>{own?<Play className="h-4 w-4"/>:<ArrowRight className="h-4 w-4"/>}{own?enrollmentLabel(own):available&&settings?.allowSelfEnrollment&&course.canSelfEnroll?'Enroll now':'View course'}</Button>{canManage&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="icon" aria-label={`Manage ${course.definition.title}`}><MoreHorizontal className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>setEditor(course.id)}><Pencil/>Edit course</DropdownMenuItem>{available&&<DropdownMenuItem onSelect={()=>setAssignment(course)}><Users/>Assign employees</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>}</div>
            </div>
          </article>;
        })}</div>
        {!courses.isLoading&&!courses.error&&!visible.length&&<div className="learning-empty"><BookOpen/><h3>No courses found</h3><p>Try another search or filter.</p><Button variant="outline" onClick={()=>{setQ('');setFilter('all');setPage(1);}}>Show all courses</Button></div>}
        {(courses.data?.total||0)>25&&<><Pager page={page} total={courses.data?.total||0} onChange={setPage}/></>}
      </TabsContent>
    </Tabs>
    <Dialog open={!!preview} onOpenChange={open=>{if(!open)setPreview(null);}}><DialogContent className="course-preview-dialog sm:max-w-2xl">{preview&&<CoursePreview key={preview.id} course={preview} onOpen={openEnrollment} onAssign={canManage?()=>{setAssignment(preview);setPreview(null);}:undefined}/>}</DialogContent></Dialog>
    <Dialog open={!!assignment} onOpenChange={open=>{if(!open)setAssignment(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Assign training</DialogTitle><DialogDescription>{assignment?.definition.title}</DialogDescription></DialogHeader>{assignment&&<AssignmentForm key={assignment.id} course={assignment} onClose={()=>setAssignment(null)} onOpen={openEnrollment}/>}</DialogContent></Dialog>
  </div>;
}
function CoursePreview({course,onOpen,onAssign}:{course:Course;onOpen:(id:number)=>void;onAssign?:()=>void}){
  const save=useSave<{enrollmentId:number}>(value=>onOpen(value.enrollmentId)),release=course.publishedRelease,settings=release?.settings,own=course.ownEnrollment,available=!!release&&course.definition.status!=='archived';
  return <><CourseCover course={course.definition} eager/><DialogHeader><span className="course-provider">{course.definition.provider}</span><DialogTitle className="text-xl">{course.definition.title}</DialogTitle><DialogDescription className="whitespace-pre-wrap">{course.definition.description}</DialogDescription></DialogHeader><div className="course-preview-facts"><span><Clock3/>{durationLabel(course.definition.durationMinutes)}<small>At your pace</small></span>{release&&<><span><BookOpen/>{release.lessonCount} lessons<small>Learn step by step</small></span><span><Award/>{settings?.passScore}% to pass<small>{release.questionCount} quiz questions</small></span></>}</div>
    {settings&&<p className="text-xs text-muted-foreground">{settings.mandatoryForOnboarding?'Required induction. ':''}{settings.enrollmentApprovalRequired?'Approval is needed before starting.':'Lessons open after enrollment.'}{settings.reviewRequired?' A reviewer confirms completion.':''}</p>}
    <QueryError error={save.error}/>
    {own?<Button className="gap-2" onClick={()=>onOpen(own.id)}><Play className="h-4 w-4"/>{enrollmentLabel(own)}</Button>:available&&settings?.allowSelfEnrollment&&course.canSelfEnroll?<Button className="gap-2" disabled={save.isPending} onClick={()=>save.mutate({url:`${base}/courses/${course.id}/enroll`,body:{releaseId:release!.id,reason:'Employee requested enrollment from the learning course catalog.'}})}><Play className="h-4 w-4"/>{save.isPending?'Opening enrollment…':settings.enrollmentApprovalRequired?'Request enrollment':'Enroll & start'}</Button>:<p className="rounded-xl bg-muted p-3 text-sm">{!available?'This course is not open for new enrollments.':!settings?.allowSelfEnrollment?'Your HR team assigns this training.':course.selfEnrollmentNote||'Contact HR to enroll in this course.'}</p>}
    {onAssign&&available&&<Button variant="outline" className="gap-2" onClick={onAssign}><Users className="h-4 w-4"/>Assign to employees</Button>}
  </>;
}
function AssignmentForm({course,onClose,onOpen}:{course:Course;onClose:()=>void;onOpen:(id:number)=>void}){
  const [q,setQ]=useState(''),[selected,setSelected]=useState<SelectedEmployee[]>([]),[saved,setSaved]=useState<{id:number;enrollmentId:number;employeeId:number}[]|null>(null);
  const directory=useQuery<Directory>({queryKey:['/api/learning/directory',{q}]}),save=useSave<{items:{id:number;enrollmentId:number;employeeId:number}[]}>(value=>setSaved(value.items));
  const toggle=(employee:SelectedEmployee,checked:boolean)=>setSelected(old=>checked?(old.some(e=>e.id===employee.id)?old:[...old,employee]):old.filter(e=>e.id!==employee.id));
  if(saved)return <div className="space-y-4"><p role="status" className="font-medium">Training assignment saved for {saved.length} {saved.length===1?'employee':'employees'}.</p><p className="text-sm text-muted-foreground">Each assignment retains its course release, quiz rules and due date. Existing assignments returned by the server remain unchanged.</p><ul className="space-y-2">{saved.map(record=><li key={record.enrollmentId} className="flex flex-wrap items-center justify-between gap-3 rounded border p-3 text-sm"><span>{selected.find(e=>e.id===record.employeeId)?.name||'Assigned employee'}</span><Button variant="outline" onClick={()=>onOpen(record.enrollmentId)}>Open training record</Button></li>)}</ul><Button variant="outline" onClick={onClose}>Done</Button></div>;
  return <form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/courses/${course.id}/assign`,body:{employeeIds:selected.map(employee=>employee.id),releaseId:course.publishedRelease!.id,dueDate:text(f,'dueDate')||null,required:f.has('required'),reason:text(f,'reason')}});}}>
    <p className="text-sm text-muted-foreground">Select up to 100 employees within your access scope. The server checks eligibility for this course’s employee types and departments before assigning release {course.publishedRelease?.releaseNumber}.</p>
    <Input label="Find employees to assign" value={q} maxLength={100} placeholder="Name or employee code" onChange={e=>setQ(e.target.value)}/><QueryError error={directory.error}/>{directory.isLoading&&<p role="status" className="text-sm">Loading employees…</p>}
    <fieldset className="max-h-72 space-y-2 overflow-y-auto rounded border p-3"><legend className="px-1 text-sm font-medium">Matching employees</legend>{directory.data?.employees.map(employee=><label className="flex items-center gap-3 rounded p-2 text-sm hover:bg-muted" key={employee.id}><input type="checkbox" checked={selected.some(e=>e.id===employee.id)} disabled={save.isPending||selected.length>=100&&!selected.some(e=>e.id===employee.id)} onChange={e=>toggle(employee,e.target.checked)}/><span>{employee.name} <span className="text-muted-foreground">· {employee.code}{employee.own?' · You':''}</span></span></label>)}{directory.data&&!directory.data.employees.length&&<p className="text-sm text-muted-foreground">No employees match this search.</p>}</fieldset><p className="text-xs text-muted-foreground">Up to 50 search results are shown. Search again to add more people; your selection is retained.</p>
    <div className="space-y-2"><p className="text-sm font-medium">{selected.length} / 100 selected</p><div className="flex flex-wrap gap-2">{selected.map(employee=><button type="button" className="rounded-full border px-3 py-1 text-xs" key={employee.id} onClick={()=>toggle(employee,false)} disabled={save.isPending} aria-label={`Remove ${employee.name} from this assignment`}>{employee.name} · Remove</button>)}</div>{!!selected.length&&<Button type="button" variant="ghost" onClick={()=>setSelected([])} disabled={save.isPending}>Clear selection</Button>}</div>
    <Input label="Due date (blank uses the course default)" name="dueDate" type="date" min={today()}/><Toggle label="Required training assignment" name="required" checked={true}/><Note label="Assignment reason" value="Employee induction and role training assignment."/><QueryError error={save.error}/><div className="flex flex-wrap gap-2"><Button disabled={save.isPending||!selected.length}>Assign to {selected.length} {selected.length===1?'employee':'employees'}</Button><Button type="button" variant="outline" disabled={save.isPending} onClick={onClose}>Cancel</Button></div>
  </form>;
}
