import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {QueryError,Section} from '@/components/hr/Operations';
import {Note,text,useSave} from '@/components/hr/EmployeeServiceUI';

type LibraryItem={key:string;title:string;description:string;audience:string;durationMinutes:number;lessonCount:number;questionCount:number;reviewedOn:string;libraryVersion:number;sources:{title:string;url:string}[];courseId:number|null;status:string;currentTitle:string|null;installedVersion:number|null};
export default function InductionSafetyLibrary({onEdit,onCatalogue}:{onEdit:(id:number)=>void;onCatalogue:()=>void}){
 const query=useQuery<{items:LibraryItem[]}>({queryKey:['/api/learning/induction/library']}),install=useSave<{created:number[];existing:number[]}>();
 const missing=query.data?.items.filter(item=>!item.courseId).length||0;
 return <div className="space-y-5"><Section title="Editable safety course library"><p className="text-sm text-muted-foreground">Practical awareness courses for office, event, mall activation and FEC teams. Each contains lessons and an automatically scored quiz. Your administrators can revise the content, questions, pass mark, attempts and assignment rules in the course editor.</p><p className="text-sm">These are internal awareness courses. Completion does not award an accredited qualification or prove practical first-aid, firefighting or equipment-operating competence.</p><div className="flex flex-wrap gap-3"><Button variant="outline" onClick={onCatalogue}>Open course catalogue</Button></div><QueryError error={query.error}/>{query.error&&<Button variant="outline" onClick={()=>query.refetch()}>Reload library</Button>}{query.isLoading&&<p role="status">Loading safety courses…</p>}
 {missing>0&&<form className="space-y-3 rounded border p-4" onSubmit={e=>{e.preventDefault();install.mutate({url:'/api/learning/induction/library/install',body:{reason:text(new FormData(e.currentTarget),'reason')}});}}><p className="text-sm">{missing} starter {missing===1?'course is':'courses are'} not yet installed. Add and publish them to the catalogue under your administrator account. Existing course edits and archives are preserved; no employee is enrolled automatically.</p><Note label="Reason for adding the courses" value="Add the requested internal safety awareness course library."/><QueryError error={install.error}/><Button disabled={install.isPending}>Add missing safety courses</Button></form>}
 {install.data&&<p role="status" className="text-sm">Added {install.data.created.length} courses. {install.data.existing.length} existing courses were preserved.</p>}
 </Section><div className="grid gap-4 xl:grid-cols-2">{query.data?.items.map(item=><article key={item.key} className="space-y-3 rounded-lg border bg-card p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-semibold">{item.currentTitle||item.title}</h3><span className="rounded bg-muted px-2 py-1 text-xs">{item.status.replaceAll('_',' ')}</span></div><p className="text-sm">{item.description}</p><p className="text-xs text-muted-foreground">Starter edition: {item.lessonCount} lessons · {item.questionCount} questions · {item.durationMinutes} minutes</p><p className="text-sm">Designed for: {item.audience}</p><details className="rounded border p-3"><summary className="cursor-pointer text-sm font-medium">Source guidance and local customisation</summary><div className="mt-3 space-y-3 text-sm"><p>Reference guidance checked {item.reviewedOn}. Content is written for internal awareness and is not endorsed by the source organisations. Add your venue’s approved contacts, evacuation arrangements, emergency numbers and role-specific instructions before making it mandatory.</p><ul className="space-y-2">{item.sources.map(source=><li key={source.url}><a className="text-primary underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a></li>)}</ul><p className="text-xs text-muted-foreground">Reference links are optional reading. Course lessons and quizzes are hosted inside your HR system and do not require a paid learning service.</p></div></details>{item.courseId&&<Button variant="outline" onClick={()=>onEdit(item.courseId!)}>Edit course & quiz</Button>}</article>)}</div></div>;
}
