import {useEffect,useRef,useState,type ReactNode} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Field,QueryError,Section,Table,fieldClass} from '@/components/hr/Operations';
import {Input,type Directory} from '@/components/hr/EmployeeServiceUI';
import {apiJson} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {defaultInductionSettings,inductionBrand,inductionCreate,inductionRevision,type InductionBrand,type InductionContent,type InductionLesson,type InductionQuestion,type InductionSettings} from '@shared/induction';
import type {CourseDefinition} from '@shared/employee-services';

const base='/api/learning/induction';
const starterBody='DRAFT AUTHORING INSTRUCTIONS: Replace this text with your approved induction content before publishing. Add lessons, upload company resources, and write the assessment questions that employees must complete.';
const starterPrompt='DRAFT QUESTION: Replace this question with an assessment of your approved lesson content.';
type Asset={id:number;filename:string;mime:string;size:number};
type Context={brand:{version:number;config:InductionBrand};canManage:boolean;canConfigure:boolean;storage:boolean;limits?:{maxAssetBytes:number;mediaBudgetBytes?:number;mediaUsedBytes?:number}};
type CourseDraft={course:{id:number;version:number;definition:CourseDefinition};draft:{version:number;definition:CourseDefinition;content:InductionContent};publishedRelease:{id:number;releaseNumber:number}|null;assets:Asset[];history:unknown[]};
type AuthorTab='course'|'lessons'|'quiz'|'rules'|'assets'|'history';
const uuid=()=>crypto.randomUUID();
const copy=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));
const move=<T,>(rows:T[],index:number,direction:-1|1)=>{const result=[...rows],target=index+direction;if(target<0||target>=rows.length)return result;[result[index],result[target]]=[result[target],result[index]];return result;};
const newLesson=():InductionLesson=>({id:uuid(),title:'',kind:'text',body:'',assetId:null,required:true,estimatedMinutes:5});
const newQuestion=():InductionQuestion=>({id:uuid(),prompt:'',kind:'single',options:[{id:uuid(),text:''},{id:uuid(),text:''}],correctOptionIds:[],points:1,explanation:''});
function initialContent():InductionContent{
  const question=newQuestion();question.prompt=starterPrompt;question.options[0].text='Replace this option with the correct answer';question.options[1].text='Replace this option with an incorrect answer';question.correctOptionIds=[question.options[0].id];
  return {lessons:[{...newLesson(),title:'Draft lesson — replace before publishing',body:starterBody}],questions:[question],settings:copy(defaultInductionSettings)};
}
const initialDefinition=(organizationName:string):CourseDefinition=>({title:'',description:'',provider:organizationName||'',format:'self_paced',url:'',durationMinutes:30,capacity:null,passScore:80,requiresEvidence:false,validMonths:null,approverId:0,status:'draft',delivery:'internal'});
function Check({label,checked,onChange,disabled=false}: {label:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
function Textarea({label,value,onChange,maxLength=5000,rows=4}: {label:string;value:string;onChange:(value:string)=>void;maxLength?:number;rows?:number}){return <Field label={label}><textarea className={fieldClass} value={value} onChange={e=>onChange(e.target.value)} maxLength={maxLength} rows={rows}/></Field>;}
function NumberField({label,value,onChange,min,max,nullable=false}: {label:string;value:number|null;onChange:(value:number|null)=>void;min:number;max:number;nullable?:boolean}){return <Input label={label} type="number" min={min} max={max} step={1} required={!nullable} value={value??''} onChange={e=>onChange(e.target.value===''&&nullable?null:Number(e.target.value))}/>;}
function Card({title,children}: {title:string;children:ReactNode}){return <div className="rounded-lg border p-4 space-y-4"><h3 className="font-semibold">{title}</h3>{children}</div>;}
const validationMessages=(issues:{path:(string|number)[];message:string}[])=>issues.map(i=>`${i.path.join(' › ')||'Course'}: ${i.message}`);

/** Internal course authoring uses its own draft; published enrollments retain their release. */
export default function InductionAuthor({courseId,onClose,onSaved}: {courseId?:number;onClose:()=>void;onSaved?:(id:number)=>void}){
  const [activeId,setActiveId]=useState(courseId),[tab,setTab]=useState<AuthorTab>('course');
  const context=useQuery<Context>({queryKey:[base+'/context']});
  const draft=useQuery<CourseDraft>({queryKey:[`${base}/courses/${activeId}/draft`],enabled:!!activeId});
  const directory=useQuery<Directory>({queryKey:['/api/learning/directory']});
  const [definition,setDefinition]=useState<CourseDefinition>(()=>initialDefinition('')),[content,setContent]=useState<InductionContent>(initialContent);
  const [versions,setVersions]=useState<{course:number;draft:number}|null>(null),[assets,setAssets]=useState<Asset[]>([]),[dirty,setDirty]=useState(false),[note,setNote]=useState(''),[errors,setErrors]=useState<string[]>([]),[publishConfirmed,setPublishConfirmed]=useState(false),[statusMessage,setStatusMessage]=useState('');
  const initialized=useRef<number|null>(null),brandApplied=useRef(false),cache=useQueryClient(),{toast}=useToast();
  const applyDraft=(data:CourseDraft)=>{setDefinition(copy(data.draft.definition));setContent(copy(data.draft.content));setVersions({course:data.course.version,draft:data.draft.version});setAssets(data.assets||[]);setDirty(false);setNote('');setErrors([]);setPublishConfirmed(false);initialized.current=data.course.id;};
  useEffect(()=>{if(courseId!==activeId){setActiveId(courseId);initialized.current=null;setVersions(null);setDirty(false);setAssets([]);setDefinition(initialDefinition(context.data?.brand.config.organizationName||''));setContent(initialContent());setNote('');setErrors([]);setPublishConfirmed(false);}},[courseId]);
  useEffect(()=>{if(draft.data&&initialized.current!==activeId)applyDraft(draft.data);},[draft.data,activeId]);
  useEffect(()=>{if(!activeId&&!brandApplied.current&&context.data){setDefinition(d=>({...d,provider:d.provider||context.data!.brand.config.organizationName}));brandApplied.current=true;}},[context.data,activeId]);
  useEffect(()=>{if(!dirty)return;const listener=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[dirty]);
  const changed=()=>{setDirty(true);setErrors([]);setStatusMessage('');setPublishConfirmed(false);};
  const updateDefinition=(patch:Partial<CourseDefinition>)=>{setDefinition(value=>({...value,...patch}));changed();};
  const updateContent=(patch:Partial<InductionContent>)=>{setContent(value=>({...value,...patch}));changed();};
  const updateSettings=(patch:Partial<InductionSettings>)=>{setContent(value=>({...value,settings:{...value.settings,...patch}}));changed();};
  const close=()=>{if(!dirty||window.confirm('Discard the unsaved changes to this course draft?'))onClose();};
  const mutation=useMutation({mutationFn:async({kind,body}: {kind:'save'|'publish'|'archive';body:unknown})=>{
    const url=kind==='save'?`${base}/courses${activeId?`/${activeId}/draft`:''}`:`${base}/courses/${activeId}/${kind}`;
    return apiJson<{id?:number;course?:{id:number}}>(url,{method:kind==='save'&&activeId?'PUT':'POST',body});
  },onSuccess:async(result,variables)=>{
    const id=activeId||result.id||result.course?.id;
    if(!id){setErrors(['The server saved the request but did not return a course ID. Close and reopen the course catalogue to load it.']);return;}
    setActiveId(id);initialized.current=null;setDirty(false);setNote('');setPublishConfirmed(false);await cache.invalidateQueries();
    const refreshed=await apiJson<CourseDraft>(`${base}/courses/${id}/draft`);cache.setQueryData([`${base}/courses/${id}/draft`],refreshed);applyDraft(refreshed);
    setStatusMessage(variables.kind==='save'?'Draft saved. Publish it when the content is ready.':variables.kind==='publish'?'Course release published. New enrollments use this release.':'Course archived. Existing learning records are retained.');
    toast({title:variables.kind==='save'?'Draft saved':variables.kind==='publish'?'Course published':'Course archived'});onSaved?.(id);
  },onError:error=>{setErrors([error.message]);toast({title:'Unable to save course',description:error.message,variant:'destructive'});}});
  const save=()=>{
    const normalized:CourseDefinition={...definition,delivery:'internal',format:'self_paced',url:'',passScore:content.settings.passScore,validMonths:content.settings.validMonths,requiresEvidence:false};
    const body={definition:normalized,content,reason:note,...(activeId&&versions?{version:versions.course,draftVersion:versions.draft}:{})};
    const parsed=activeId?inductionRevision.safeParse(body):inductionCreate.safeParse(body);
    if(!parsed.success){setErrors(validationMessages(parsed.error.issues));return;}
    mutation.mutate({kind:'save',body:parsed.data});
  };
  const publish=()=>{
    if(!activeId||!versions)return;
    if(dirty){setErrors(['Save your draft changes before publishing.']);return;}
    if(content.lessons.some(l=>l.body.includes('DRAFT AUTHORING INSTRUCTIONS')||l.title==='Draft lesson — replace before publishing')||content.questions.some(q=>q.prompt===starterPrompt||q.options.some(o=>o.text.startsWith('Replace this option with')))){setErrors(['Replace all starter lesson and quiz instructions with approved course content before publishing.']);return;}
    if(!publishConfirmed){setErrors(['Confirm that the lessons, answers and employee requirements are ready for publication.']);return;}
    if(note.trim().length<5){setErrors(['Add a publication reason of at least five characters.']);return;}
    mutation.mutate({kind:'publish',body:{version:versions.course,draftVersion:versions.draft,reason:note.trim()}});
  };
  const archive=()=>{if(!activeId||!versions)return;if(dirty){setErrors(['Save or discard unsaved draft changes before archiving.']);return;}if(note.trim().length<5){setErrors(['Add a reason for archiving of at least five characters.']);return;}if(window.confirm('Archive this course and stop new enrollments? Existing learning records will be retained.'))mutation.mutate({kind:'archive',body:{version:versions.course,reason:note.trim()}});};
  if(context.isLoading)return <p role="status">Loading course authoring…</p>;
  if(context.error)return <QueryError error={context.error}/>;
  if(!context.data?.canManage)return <p role="alert">You do not have permission to manage internal courses.</p>;
  if(activeId&&(!versions||initialized.current!==activeId))return <div className="space-y-3"><QueryError error={draft.error}/>{draft.isLoading&&<p role="status">Loading course draft…</p>}<Button variant="outline" onClick={onClose}>Back to academy</Button></div>;
  const stale=!!(draft.data&&versions&&(draft.data.course.version!==versions.course||draft.data.draft.version!==versions.draft));
  const busy=mutation.isPending;
  return <div className="space-y-5">
    <Section title={activeId?'Edit internal course':'Create internal course'}>
      <div className="flex flex-wrap justify-between gap-3"><p className="text-sm text-muted-foreground">{activeId?`Draft ${versions?.draft} · ${draft.data?.publishedRelease?`Published release ${draft.data.publishedRelease.releaseNumber}`:'Not published'}${dirty?' · Unsaved changes':''}`:'Draft lessons and assessments stay private until you publish a release.'}</p><Button variant="outline" onClick={close} disabled={busy}>Close editor</Button></div>
      <p className="text-sm">Employees learn and take quizzes inside your HR system. Text lessons, private files, scoring and certificates use the existing application.</p>
      {!activeId&&<p className="rounded-md bg-muted p-3 text-sm">The starter lesson and question contain authoring instructions only. Replace them with your approved content before publication. Save a first draft to enable private file uploads.</p>}
      {stale&&<div className="rounded-md border border-amber-500 p-3 space-y-2"><p role="alert" className="text-sm">A newer version is available. Your local edits have been kept. Reload the saved version before making further changes.</p><Button variant="outline" disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard your unsaved edits and load the latest saved draft?')){if(draft.data)applyDraft(draft.data);}}}>Load latest saved draft</Button></div>}
      <QueryError error={draft.error}/>
      <div className="flex flex-wrap gap-2" role="group" aria-label="Course authoring sections">{([['course','Course details'],['lessons',`Lessons (${content.lessons.length})`],['quiz',`Question bank (${content.questions.length})`],['rules','Completion rules'],['assets','Private resources'],['history','History']] as [AuthorTab,string][]).map(([key,label])=><Button key={key} variant={tab===key?'default':'outline'} onClick={()=>setTab(key)} aria-pressed={tab===key}>{label}</Button>)}</div>
    </Section>
    <fieldset disabled={busy} className="space-y-5 min-w-0">
    {tab==='course'&&<Section title="Course details">
      <Input label="Course title" value={definition.title} minLength={3} maxLength={200} required onChange={e=>updateDefinition({title:e.target.value})}/>
      <Textarea label="Course description" value={definition.description} onChange={description=>updateDefinition({description})}/>
      <div className="grid gap-4 md:grid-cols-2"><Input label="Organization / internal provider" value={definition.provider} minLength={2} maxLength={150} required onChange={e=>updateDefinition({provider:e.target.value})}/><NumberField label="Estimated course duration (minutes)" min={1} max={100000} value={definition.durationMinutes} onChange={v=>updateDefinition({durationMinutes:v||0})}/><NumberField label="Active enrollment capacity (blank = unlimited)" min={1} max={100000} nullable value={definition.capacity} onChange={capacity=>updateDefinition({capacity})}/><Field label="Assigned enrollment and completion reviewer"><select className={fieldClass} value={definition.approverId||''} required onChange={e=>updateDefinition({approverId:Number(e.target.value)})}><option value="">Select an eligible reviewer</option>{!!definition.approverId&&!directory.data?.approvers.some(a=>a.id===definition.approverId)&&<option value={definition.approverId}>Assigned reviewer #{definition.approverId}</option>}{directory.data?.approvers.map(a=><option value={a.id} key={a.id}>{a.name} · {a.role.replaceAll('_',' ')}</option>)}</select></Field></div>
      <QueryError error={directory.error}/><p className="text-sm text-muted-foreground">Delivery: internal, self paced. The reviewer is used whenever enrollment approval or completion review is enabled. Uploaded completion evidence is replaced by lesson progress and a server-scored assessment.</p>
    </Section>}
    {tab==='lessons'&&<LessonEditor lessons={content.lessons} assets={assets} onChange={lessons=>updateContent({lessons})} hasCourse={!!activeId}/>}
    {tab==='quiz'&&<QuizEditor questions={content.questions} onChange={questions=>updateContent({questions})}/>}
    {tab==='rules'&&<RuleEditor settings={content.settings} questionCount={content.questions.length} onChange={updateSettings}/>}
    {tab==='assets'&&<AssetLibrary courseId={activeId} assets={assets} storage={context.data.storage} maxBytes={context.data.limits?.maxAssetBytes||41943040} budgetBytes={context.data.limits?.mediaBudgetBytes} usedBytes={context.data.limits?.mediaUsedBytes} hasUnsavedChanges={dirty} referencedAssetIds={content.lessons.map(l=>l.assetId).filter((id):id is number=>id!==null)} onUploaded={asset=>setAssets(old=>[...old.filter(a=>a.id!==asset.id),asset])} onRemoved={id=>setAssets(old=>old.filter(a=>a.id!==id))}/>}
    {tab==='history'&&<Section title="Course revision history"><p className="text-sm text-muted-foreground">Saving updates the working draft. Publishing creates an immutable release for new enrollments.</p><CourseHistory rows={draft.data?.history||[]}/></Section>}
    <Section title="Save and publish">
      <Textarea label="Reason for this change or publication" value={note} onChange={setNote} maxLength={2000} rows={3}/>
      {errors.length>0&&<div role="alert" className="rounded-md border border-destructive p-3 text-sm text-destructive"><p className="font-semibold">Please address the following:</p><ul className="mt-2 list-disc pl-5 space-y-1">{errors.map((error,i)=><li key={i}>{error}</li>)}</ul></div>}
      {statusMessage&&<p role="status" className="text-sm">{statusMessage}</p>}
      <div className="flex flex-wrap gap-3"><Button onClick={save} disabled={busy||stale}>{busy?'Saving…':activeId?'Save draft':'Create draft'}</Button>{activeId&&<Button variant="outline" onClick={()=>{if(!dirty||window.confirm('Discard your unsaved edits and reload the saved draft?')){if(draft.data)applyDraft(draft.data);}}} disabled={busy||!draft.data}>Reload saved draft</Button>}</div>
      {activeId&&<div className="border-t pt-4 space-y-3"><Check label="I have reviewed the lesson content, correct answers and employee requirements for this release." checked={publishConfirmed} onChange={setPublishConfirmed}/><div className="flex flex-wrap gap-3"><Button onClick={publish} disabled={busy||dirty||stale||!publishConfirmed}>Publish new release</Button>{definition.status!=='archived'&&<Button variant="outline" onClick={archive} disabled={busy||dirty||stale}>Archive course</Button>}</div><p className="text-sm text-muted-foreground">Existing enrollments retain their saved release and rules. Publishing updates the catalogue for new enrollments.</p></div>}
    </Section>
    </fieldset>
  </div>;
}

function LessonEditor({lessons,assets,onChange,hasCourse}: {lessons:InductionLesson[];assets:Asset[];onChange:(rows:InductionLesson[])=>void;hasCourse:boolean}){
  const update=(id:string,patch:Partial<InductionLesson>)=>onChange(lessons.map(l=>l.id===id?{...l,...patch}:l));
  return <Section title="Lessons"><p className="text-sm text-muted-foreground">Order the material employees work through. Text is displayed as plain text, with line breaks preserved. PDF, image and video resources are private course uploads.</p>
    {lessons.map((lesson,index)=><Card title={`Lesson ${index+1}`} key={lesson.id}>
      <div className="grid gap-4 md:grid-cols-2"><Input label={`Lesson ${index+1} title`} value={lesson.title} maxLength={180} required onChange={e=>update(lesson.id,{title:e.target.value})}/><Field label="Lesson format"><select className={fieldClass} value={lesson.kind} onChange={e=>update(lesson.id,{kind:e.target.value as InductionLesson['kind'],assetId:null})}><option value="text">Text lesson</option><option value="document">Private PDF or image</option><option value="video">Private video</option></select></Field></div>
      <Textarea label={lesson.kind==='text'?'Lesson content':'Introduction / instructions (optional)'} value={lesson.body} onChange={body=>update(lesson.id,{body})} maxLength={40000} rows={lesson.kind==='text'?10:4}/>
      {lesson.kind!=='text'&&<><Field label={lesson.kind==='video'?'Course video':'Course PDF or image'}><select className={fieldClass} value={lesson.assetId??''} onChange={e=>update(lesson.id,{assetId:e.target.value?Number(e.target.value):null})}><option value="">Choose an uploaded resource</option>{assets.filter(a=>lesson.kind==='video'?a.mime.startsWith('video/'):a.mime==='application/pdf'||a.mime.startsWith('image/')).map(a=><option value={a.id} key={a.id}>{a.filename}</option>)}</select></Field><p className="text-sm text-muted-foreground">{hasCourse?'Add files in Private resources, then choose the resource here.':'Save your initial text draft to enable private resource uploads.'}</p></>}
      <div className="flex flex-wrap gap-4 items-center"><div className="w-56"><NumberField label="Estimated lesson time (minutes)" min={0} max={600} value={lesson.estimatedMinutes} onChange={v=>update(lesson.id,{estimatedMinutes:v||0})}/></div><Check label="Required before the final quiz" checked={lesson.required} onChange={required=>update(lesson.id,{required})}/></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={index===0} onClick={()=>onChange(move(lessons,index,-1))} aria-label={`Move lesson ${index+1} up`}>Move up</Button><Button variant="outline" disabled={index===lessons.length-1} onClick={()=>onChange(move(lessons,index,1))} aria-label={`Move lesson ${index+1} down`}>Move down</Button><Button variant="outline" disabled={lessons.length===1} onClick={()=>{if(window.confirm(`Remove lesson ${index+1} from this draft?`))onChange(lessons.filter(l=>l.id!==lesson.id));}}>Remove lesson</Button></div>
    </Card>)}
    <Button variant="outline" disabled={lessons.length>=60} onClick={()=>onChange([...lessons,newLesson()])}>Add lesson</Button><p className="text-sm text-muted-foreground">At least one lesson must be required. Maximum 60 lessons per course.</p>
  </Section>;
}

function QuizEditor({questions,onChange}: {questions:InductionQuestion[];onChange:(rows:InductionQuestion[])=>void}){
  const update=(id:string,patch:Partial<InductionQuestion>)=>onChange(questions.map(q=>q.id===id?{...q,...patch}:q));
  const changeKind=(q:InductionQuestion,kind:InductionQuestion['kind'])=>{
    if(kind==='true_false'){const options=[{id:uuid(),text:'True'},{id:uuid(),text:'False'}];update(q.id,{kind,options,correctOptionIds:[]});}
    else update(q.id,{kind,correctOptionIds:kind==='single'?q.correctOptionIds.slice(0,1):q.correctOptionIds});
  };
  return <Section title="Assessment question bank"><p className="text-sm text-muted-foreground">Choose the correct answers and assign points. Multiple-answer questions require every correct option and no incorrect options to earn their points. The server records scores; learners cannot edit them.</p>
    {questions.map((question,index)=><Card key={question.id} title={`Question ${index+1}`}>
      <Textarea label={`Question ${index+1} prompt`} value={question.prompt} onChange={prompt=>update(question.id,{prompt})} maxLength={3000} rows={3}/>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Question type"><select className={fieldClass} value={question.kind} onChange={e=>changeKind(question,e.target.value as InductionQuestion['kind'])}><option value="single">Single correct answer</option><option value="multiple">Multiple correct answers</option><option value="true_false">True / false</option></select></Field><NumberField label="Points" min={1} max={20} value={question.points} onChange={v=>update(question.id,{points:v||0})}/></div>
      <fieldset className="rounded-md border p-3 space-y-3"><legend className="px-2 text-sm font-medium">Answer options — mark {question.kind==='multiple'?'all correct answers':'the correct answer'}</legend>{question.options.map((option,optionIndex)=><div key={option.id} className="grid gap-2 sm:grid-cols-[auto_1fr_auto] items-end"><label className="inline-flex items-center gap-2 text-sm pb-2"><input type={question.kind==='multiple'?'checkbox':'radio'} name={`correct-${question.id}`} checked={question.correctOptionIds.includes(option.id)} onChange={e=>update(question.id,{correctOptionIds:question.kind==='multiple'?(e.target.checked?[...question.correctOptionIds,option.id]:question.correctOptionIds.filter(id=>id!==option.id)):[option.id]})}/><span>Correct {String.fromCharCode(65+optionIndex)}</span></label><Input label={`Option ${String.fromCharCode(65+optionIndex)}`} value={option.text} maxLength={1000} required readOnly={question.kind==='true_false'} onChange={e=>update(question.id,{options:question.options.map(o=>o.id===option.id?{...o,text:e.target.value}:o)})}/>{question.kind!=='true_false'&&<Button variant="outline" disabled={question.options.length<=2} onClick={()=>update(question.id,{options:question.options.filter(o=>o.id!==option.id),correctOptionIds:question.correctOptionIds.filter(id=>id!==option.id)})} aria-label={`Remove option ${String.fromCharCode(65+optionIndex)} from question ${index+1}`}>Remove</Button>}</div>)}{question.kind!=='true_false'&&<Button variant="outline" disabled={question.options.length>=8} onClick={()=>update(question.id,{options:[...question.options,{id:uuid(),text:''}]})}>Add answer option</Button>}</fieldset>
      <Textarea label="Answer explanation (optional)" value={question.explanation} onChange={explanation=>update(question.id,{explanation})} maxLength={3000} rows={3}/>
      <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={index===0} onClick={()=>onChange(move(questions,index,-1))} aria-label={`Move question ${index+1} up`}>Move up</Button><Button variant="outline" disabled={index===questions.length-1} onClick={()=>onChange(move(questions,index,1))} aria-label={`Move question ${index+1} down`}>Move down</Button><Button variant="outline" disabled={questions.length===1} onClick={()=>{if(window.confirm(`Remove question ${index+1} from the draft question bank?`))onChange(questions.filter(q=>q.id!==question.id));}}>Remove question</Button></div>
    </Card>)}
    <Button variant="outline" disabled={questions.length>=100} onClick={()=>onChange([...questions,newQuestion()])}>Add question</Button><p className="text-sm text-muted-foreground">Up to 100 questions, with 2–8 answer options each.</p>
  </Section>;
}

function RuleEditor({settings,questionCount,onChange}: {settings:InductionSettings;questionCount:number;onChange:(patch:Partial<InductionSettings>)=>void}){
  const [departments,setDepartments]=useState(settings.departments.join(', '));
  useEffect(()=>{setDepartments(settings.departments.join(', '));},[settings.departments]);
  const numbers: {key:'passScore'|'maxAttempts'|'retryDelayMinutes'|'attemptMinutes'|'questionCount'|'defaultDueDays';label:string;min:number;max:number}[]=[{key:'passScore',label:'Passing score (%)',min:0,max:100},{key:'maxAttempts',label:'Maximum quiz attempts',min:1,max:20},{key:'attemptMinutes',label:'Quiz time limit (minutes)',min:1,max:180},{key:'retryDelayMinutes',label:'Delay between attempts (minutes)',min:0,max:10080},{key:'questionCount',label:'Questions per attempt (0 = entire bank)',min:0,max:Math.min(100,questionCount)},{key:'defaultDueDays',label:'Default due date (days after enrollment)',min:0,max:365}];
  return <Section title="Completion and assignment rules">
    <div className="grid gap-4 md:grid-cols-2">{numbers.map(n=><NumberField key={n.key} label={n.label} min={n.min} max={n.max} value={settings[n.key]} onChange={v=>onChange({[n.key]:v||0})}/>)}<NumberField label="Certificate validity (months; blank = no expiry)" min={1} max={120} nullable value={settings.validMonths} onChange={validMonths=>onChange({validMonths})}/></div>
    <Card title="Learning and quiz behavior"><Check label="Complete required lessons in order" checked={settings.sequentialLessons} onChange={sequentialLessons=>onChange({sequentialLessons})}/><Check label="Shuffle the question order per attempt" checked={settings.shuffleQuestions} onChange={shuffleQuestions=>onChange({shuffleQuestions})}/><Check label="Shuffle answer options per attempt" checked={settings.shuffleOptions} onChange={shuffleOptions=>onChange({shuffleOptions})}/><Check label="Require reviewer approval after the employee passes the quiz" checked={settings.reviewRequired} onChange={reviewRequired=>onChange({reviewRequired})}/></Card>
    <Card title="Enrollment and onboarding"><Check label="Allow eligible employees to enroll themselves" checked={settings.allowSelfEnrollment} onChange={allowSelfEnrollment=>onChange({allowSelfEnrollment})}/><Check label="Require approval before an enrollment can start" checked={settings.enrollmentApprovalRequired} onChange={enrollmentApprovalRequired=>onChange({enrollmentApprovalRequired})}/><Check label="Mandatory for eligible employees during onboarding" checked={settings.mandatoryForOnboarding} onChange={mandatoryForOnboarding=>onChange({mandatoryForOnboarding})}/><p className="text-sm text-muted-foreground">Onboarding requirements use published releases and apply to the employee types and departments below.</p></Card>
    <Card title="Employee eligibility"><fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Eligible employee types</legend>{(['permanent','temporary','contract'] as const).map(type=><Check key={type} label={type==='temporary'?'Temporary / event employees':type==='contract'?'Contract employees':'Permanent employees'} checked={settings.employeeTypes.includes(type)} onChange={checked=>onChange({employeeTypes:checked?[...settings.employeeTypes,type]:settings.employeeTypes.filter(v=>v!==type)})}/>)}</fieldset><Input label="Departments (comma separated; blank = all departments)" value={departments} maxLength={15000} onChange={e=>setDepartments(e.target.value)} onBlur={()=>{const values=[...new Set(departments.split(',').map(v=>v.trim()).filter(Boolean))];onChange({departments:values});}}/><p className="text-sm text-muted-foreground">Use the exact department names from employee records. Eligibility applies equally to permanent, temporary, event and contract staff through their employee type.</p></Card>
  </Section>;
}

function AssetLibrary({courseId,assets,storage,maxBytes,budgetBytes,usedBytes,hasUnsavedChanges,referencedAssetIds,onUploaded,onRemoved}: {courseId?:number;assets:Asset[];storage:boolean;maxBytes:number;budgetBytes?:number;usedBytes?:number;hasUnsavedChanges:boolean;referencedAssetIds:number[];onUploaded:(asset:Asset)=>void;onRemoved:(id:number)=>void}){
  const [file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[removeAsset,setRemoveAsset]=useState<Asset|null>(null),[removeReason,setRemoveReason]=useState(''),[removeError,setRemoveError]=useState(''),inputRef=useRef<HTMLInputElement>(null),cache=useQueryClient(),{toast}=useToast();
  const upload=useMutation({mutationFn:async()=>{if(!courseId||!file)throw new Error('Choose a file for a saved course');if(file.size>maxBytes)throw new Error(`The file must be no larger than ${Math.floor(maxBytes/1024/1024)} MB`);if(budgetBytes!==undefined&&file.size+(usedBytes||0)>budgetBytes)throw new Error('This upload exceeds the academy media budget. An administrator can edit the budget within academy settings.');if(!['application/pdf','image/png','image/jpeg','video/mp4','video/webm'].includes(file.type))throw new Error('Choose a PDF, PNG, JPEG, MP4 or WebM file');const body=new FormData();body.set('file',file);return apiJson<Asset|{asset:Asset}>(`${base}/courses/${courseId}/assets`,{method:'POST',body});},onSuccess:result=>{const asset='asset' in result?result.asset:result;onUploaded(asset);setFile(null);if(inputRef.current)inputRef.current.value='';setError('');cache.invalidateQueries({queryKey:[`${base}/courses/${courseId}/draft`]});cache.invalidateQueries({queryKey:[base+'/context']});toast({title:'Private course resource uploaded'});},onError:e=>setError(e.message)});
  const remove=useMutation({mutationFn:async()=>{if(!removeAsset)throw new Error('Choose a resource to remove');if(hasUnsavedChanges)throw new Error('Save your draft changes before removing resources');if(referencedAssetIds.includes(removeAsset.id))throw new Error('Remove the lesson reference and save the draft before removing this resource');if(removeReason.trim().length<5)throw new Error('Enter a removal reason of at least five characters');await apiJson<{removed:true}>(`${base}/assets/${removeAsset.id}`,{method:'DELETE',body:{reason:removeReason.trim()}});return removeAsset.id;},onSuccess:id=>{onRemoved(id);setRemoveAsset(null);setRemoveReason('');setRemoveError('');cache.invalidateQueries({queryKey:[`${base}/courses/${courseId}/draft`]});cache.invalidateQueries({queryKey:[base+'/context']});toast({title:'Unused course resource removed'});},onError:e=>setRemoveError(e.message)});
  return <Section title="Private course resources"><p className="text-sm text-muted-foreground">Upload your organization’s files to the configured private storage. Videos play inside the course; no public video embeds or external learning providers are used.</p>
    {budgetBytes!==undefined&&<p className="text-sm">Academy media: {((usedBytes||0)/1024/1024).toFixed(1)} MB used of {(budgetBytes/1024/1024).toFixed(0)} MB configured.</p>}
    <Table headers={['Resource','Type','Size','']} rows={assets.map(asset=>[asset.filename,asset.mime,`${(asset.size/1024/1024).toFixed(2)} MB`,courseId?<div className="space-y-2"><a className="text-primary underline" href={`${base}/assets/${asset.id}/download?courseId=${courseId}`} target="_blank" rel="noopener noreferrer">Open private resource</a><div><Button variant="outline" size="sm" disabled={hasUnsavedChanges||referencedAssetIds.includes(asset.id)||remove.isPending||upload.isPending} onClick={()=>{setRemoveAsset(asset);setRemoveReason('');setRemoveError('');}}>Remove unused resource</Button></div>{referencedAssetIds.includes(asset.id)&&<p className="text-xs text-muted-foreground">Used in the current draft</p>}</div>:null])}/>
    {!!assets.length&&<p className="text-sm text-muted-foreground">To reclaim media space, remove the resource from any lessons and save the draft before deleting it. Resources referenced by a published release, another draft or a certificate are retained. {hasUnsavedChanges?'Save your draft changes to enable removal.':''}</p>}
    {removeAsset&&<div className="rounded-md border p-4 space-y-3"><h3 className="font-semibold">Remove unused resource</h3><p className="text-sm">Permanently remove <strong>{removeAsset.filename}</strong> ({(removeAsset.size/1024/1024).toFixed(2)} MB) from private storage. The server will prevent removal if a saved record still uses this resource.</p><Textarea label="Reason for removing this resource" value={removeReason} onChange={value=>{setRemoveReason(value);setRemoveError('');}} maxLength={2000} rows={3}/>{removeError&&<p role="alert" className="text-sm text-destructive">{removeError}</p>}<div className="flex flex-wrap gap-2"><Button variant="destructive" disabled={remove.isPending||upload.isPending||hasUnsavedChanges||referencedAssetIds.includes(removeAsset.id)||removeReason.trim().length<5} onClick={()=>remove.mutate()}>{remove.isPending?'Removing…':'Permanently remove resource'}</Button><Button variant="outline" disabled={remove.isPending} onClick={()=>{setRemoveAsset(null);setRemoveReason('');setRemoveError('');}}>Cancel removal</Button></div></div>}
    {!courseId?<p className="text-sm">Create the draft first, then upload resources here.</p>:!storage?<p role="status" className="text-sm">Private storage is not configured. Text lessons and quizzes can still be authored. An administrator must configure the application’s existing storage to enable file uploads.</p>:budgetBytes===0?<p role="status" className="text-sm">Course file uploads are disabled by the academy media budget. Text lessons and quizzes remain available.</p>:<div className="space-y-3"><Field label={`Course file — PDF, PNG, JPEG, MP4 or WebM; maximum ${Math.floor(maxBytes/1024/1024)} MB`}><input ref={inputRef} className={fieldClass} type="file" accept=".pdf,.png,.jpg,.jpeg,.mp4,.webm" disabled={upload.isPending||remove.isPending} onChange={e=>{setFile(e.target.files?.[0]||null);setError('');}}/></Field>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button variant="outline" disabled={!file||upload.isPending||remove.isPending} onClick={()=>upload.mutate()}>{upload.isPending?'Uploading…':'Upload private resource'}</Button><p className="text-sm text-muted-foreground">Choose the uploaded file in a lesson to include it in the course. Keep videos short and compressed to stay within your existing free storage allowance.</p></div>}
  </Section>;
}

function CourseHistory({rows}: {rows:unknown[]}){
  return <ol className="space-y-3">{!rows.length&&<li className="text-sm text-muted-foreground">No saved changes yet.</li>}{rows.map((raw,index)=>{const row=raw as {id?:number;action?:string;kind?:string;version?:number;releaseNumber?:number;actorId?:number;actor_id?:number;reason?:string;at?:string;createdAt?:string;created_at?:string};const date=row.at||row.createdAt||row.created_at;return <li key={row.id||index} className="rounded-md border p-3 text-sm space-y-1"><p className="font-medium">{(row.action||row.kind||'Course update').replaceAll('_',' ')}{row.version?` · Version ${row.version}`:''}{row.releaseNumber?` · Release ${row.releaseNumber}`:''}</p>{date&&<p className="text-muted-foreground">{new Date(date).toLocaleString()}</p>}<p className="whitespace-pre-wrap">{row.reason||'Saved course revision'}</p>{(row.actorId||row.actor_id)&&<p className="text-muted-foreground">Recorded by user #{row.actorId||row.actor_id}</p>}</li>;})}</ol>;
}

export function InductionBrandEditor({onClose}: {onClose?:()=>void}={}){
  const context=useQuery<Context>({queryKey:[base+'/context']}),query=useQuery<{version:number;config:InductionBrand}>({queryKey:[base+'/branding'],enabled:!!context.data?.canConfigure});
  const history=useQuery<{version:number;reason:string;created_at:string;config:InductionBrand}[]>({queryKey:[base+'/branding/history'],enabled:!!context.data?.canConfigure});
  const [config,setConfig]=useState<InductionBrand|null>(null),[version,setVersion]=useState<number|null>(null),[reason,setReason]=useState(''),[dirty,setDirty]=useState(false),[errors,setErrors]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[pendingLogo,setPendingLogo]=useState(false);
  const initialized=useRef(false),logoRef=useRef<HTMLInputElement>(null),cache=useQueryClient(),{toast}=useToast();
  const apply=(value:{version:number;config:InductionBrand})=>{setConfig(copy(value.config));setVersion(value.version);setDirty(false);setReason('');setErrors([]);setPendingLogo(false);initialized.current=true;};
  useEffect(()=>{if(!initialized.current&&query.data)apply(query.data);},[query.data]);
  useEffect(()=>{if(!dirty)return;const listener=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',listener);return()=>window.removeEventListener('beforeunload',listener);},[dirty]);
  const update=(patch:Partial<InductionBrand>)=>{setConfig(old=>old?{...old,...patch}:old);setDirty(true);setErrors([]);};
  const save=useMutation({mutationFn:(body:unknown)=>apiJson<{version:number;config:InductionBrand}>(base+'/branding',{method:'POST',body}),onSuccess:async()=>{await cache.invalidateQueries();const next=await apiJson<{version:number;config:InductionBrand}>(base+'/branding');cache.setQueryData([base+'/branding'],next);apply(next);toast({title:'Academy branding saved'});},onError:e=>setErrors([e.message])});
  const upload=useMutation({mutationFn:async()=>{if(!file)throw new Error('Choose a logo image');if(file.size>2097152)throw new Error('The logo must be no larger than 2 MB');if(!['image/png','image/jpeg'].includes(file.type))throw new Error('Choose a PNG or JPEG logo');const body=new FormData();body.set('file',file);return apiJson<{id?:number;asset?:{id:number};assetId?:number}>(base+'/branding/assets',{method:'POST',body});},onSuccess:result=>{const id=result.id||result.asset?.id||result.assetId;if(!id){setErrors(['The server did not return the uploaded logo identifier.']);return;}update({logoAssetId:id});setFile(null);setPendingLogo(true);if(logoRef.current)logoRef.current.value='';toast({title:'Logo uploaded',description:'Save branding to apply this logo.'});},onError:e=>setErrors([e.message])});
  if(context.isLoading)return <p role="status">Loading academy settings…</p>;
  if(context.error)return <QueryError error={context.error}/>;
  if(!context.data?.canConfigure)return <p role="alert">Only administrators and super administrators can change academy branding.</p>;
  if(!config)return <><QueryError error={query.error}/>{query.isLoading&&<p role="status">Loading academy branding…</p>}</>;
  const stale=query.data?.version!==version,busy=save.isPending||upload.isPending;
  return <Section title="Academy branding"><div className="flex flex-wrap justify-between gap-3"><p className="text-sm text-muted-foreground">Your organization’s identity is used throughout the internal academy and its completion certificates.</p>{onClose&&<Button variant="outline" disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved branding changes?'))onClose();}}>Close settings</Button>}</div><QueryError error={query.error}/>
    {stale&&<div className="rounded-md border p-3 space-y-2"><p role="alert" className="text-sm">Branding has changed since you opened this form. Your edits have been kept.</p><Button variant="outline" onClick={()=>{if(!dirty||window.confirm('Discard your edits and load the latest branding?')){if(query.data)apply(query.data);}}}>Load latest branding</Button></div>}
    <form className="space-y-4" onSubmit={e=>{e.preventDefault();const parsed=inductionBrand.safeParse(config);if(!parsed.success){setErrors(validationMessages(parsed.error.issues));return;}if(reason.trim().length<5){setErrors(['Add a change reason of at least five characters.']);return;}save.mutate({version,config:parsed.data,reason:reason.trim()});}}>
      <fieldset disabled={busy} className="space-y-4 min-w-0"><div className="grid gap-4 md:grid-cols-2"><Input label="Organization name" value={config.organizationName} maxLength={160} required onChange={e=>update({organizationName:e.target.value})}/><Input label="Academy title" value={config.academyTitle} maxLength={160} required onChange={e=>update({academyTitle:e.target.value})}/></div><Textarea label="Welcome message" value={config.welcomeText} onChange={welcomeText=>update({welcomeText})} maxLength={1000}/>
      <div className="grid gap-4 md:grid-cols-2"><Input label="Accent color" type="color" value={config.accentColor} onChange={e=>update({accentColor:e.target.value})}/><Input label="Certificate heading" value={config.certificateTitle} maxLength={160} required onChange={e=>update({certificateTitle:e.target.value})}/><Input label="Certificate number prefix (2–20 uppercase letters, numbers or hyphens)" value={config.certificatePrefix} minLength={2} maxLength={20} pattern="[A-Z0-9-]{2,20}" required onChange={e=>update({certificatePrefix:e.target.value.toUpperCase()})}/><Input label="Certificate signatory title (optional)" value={config.signatoryTitle} maxLength={160} onChange={e=>update({signatoryTitle:e.target.value})}/></div>
      <Card title="Media limits"><div className="grid gap-4 md:grid-cols-2"><NumberField label="Maximum course file size (MB)" min={1} max={40} value={config.maxUploadMb} onChange={v=>update({maxUploadMb:v||1})}/><NumberField label="Academy media budget (MB; 0 disables course uploads)" min={0} max={512} value={config.mediaBudgetMb} onChange={v=>update({mediaBudgetMb:v||0})}/></div><p className="text-sm text-muted-foreground">These limits control academy uploads within existing storage. Lowering the budget preserves stored files and blocks new uploads above the budget. Text courses and quizzes do not require uploaded media.</p></Card>
      <Card title="Organization logo">{config.logoAssetId&&!pendingLogo&&<img className="max-h-24 max-w-64 object-contain" alt={`${config.organizationName} logo`} src={`${base}/branding/logo?v=${version}`}/>}<p className="text-sm">{pendingLogo?'A new private logo is uploaded. Save branding to apply it.':config.logoAssetId?'A private organization logo is configured.':'No logo selected.'}</p>{context.data.storage?<><Field label="Upload logo (PNG or JPEG, maximum 2 MB)"><input ref={logoRef} className={fieldClass} type="file" accept=".png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><div className="flex gap-2 flex-wrap"><Button type="button" variant="outline" disabled={!file||busy} onClick={()=>upload.mutate()}>Upload logo</Button>{config.logoAssetId&&<Button type="button" variant="outline" onClick={()=>{update({logoAssetId:null});setPendingLogo(false);}}>Remove logo from branding</Button>}</div></>:<p className="text-sm text-muted-foreground">Logo uploads need the application’s private file storage. Text branding works without storage.</p>}</Card>
      <div className="rounded-lg border p-5 space-y-2" style={{borderTop:`4px solid ${config.accentColor}`}}><p className="text-sm text-muted-foreground">Brand preview</p><h3 className="text-xl font-semibold">{config.academyTitle}</h3><p className="text-sm">{config.organizationName}</p><p className="text-sm whitespace-pre-wrap">{config.welcomeText}</p><p className="font-medium pt-2">{config.certificateTitle}</p><p className="text-sm text-muted-foreground">{config.signatoryTitle}</p></div>
      <Textarea label="Reason for branding change" value={reason} onChange={setReason} maxLength={2000} rows={3}/>{errors.length>0&&<div role="alert" className="text-sm text-destructive"><ul className="list-disc pl-5">{errors.map((error,i)=><li key={i}>{error}</li>)}</ul></div>}<Button type="submit" disabled={busy||stale}>{save.isPending?'Saving…':'Save academy branding'}</Button>
      </fieldset>
    </form>
    <details className="rounded-md border p-4"><summary className="cursor-pointer text-sm font-semibold">Branding and media policy history</summary><div className="mt-4 space-y-3"><QueryError error={history.error}/>{history.isLoading?<p role="status" className="text-sm">Loading branding history…</p>:<CourseHistory rows={(history.data||[]).map(row=>({...row,action:'branding_update'}))}/>}</div></details>
  </Section>;
}
