import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'wouter';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,useOperation,today} from './Common';
export function AttendanceOperations(){
 const [from,setFrom]=useState(()=>new Date(Date.now()-14*86400000).toISOString().slice(0,10)),[to,setTo]=useState(today()),[reconcile,setReconcile]=useState(false),[selected,setSelected]=useState<any>(null),[decision,setDecision]=useState<any>(null),[history,setHistory]=useState<number|null>(null),[reason,setReason]=useState('');
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[breaks,setBreaks]=useState('0'),op=useOperation();const valid=!!from&&!!to&&from<=to&&Date.parse(to)-Date.parse(from)<90*86400000,range={from,to};
 const records=useQuery<any[]>({queryKey:['/api/attendance/records',range],enabled:valid}),requests=useQuery<any[]>({queryKey:['/api/attendance/corrections',range],enabled:valid}),roster=useQuery<any[]>({queryKey:['/api/attendance/roster-reconciliation',range],enabled:valid&&reconcile}),versions=useQuery<any[]>({queryKey:[`/api/attendance/records/${history}/history`],enabled:!!history});
 const stamp=(v:string)=>v?new Date(v).toISOString().replace('T',' ').slice(0,16)+' UTC':'Not recorded';
 return <Card><CardHeader><CardTitle>Corrections & roster reconciliation</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-3"><Field label="From (UTC)"><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></Field><Field label="Through (UTC)"><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></Field></div><p className="text-sm">Employees propose corrections to their records; an independent attendance approver decides. Changes retain the original calculation rules and history. Up to 300 records per window; narrow the dates for larger teams.</p>{!valid?<p role="alert">Choose up to 90 days.</p>:<>{records.isLoading?<p>Loading records…</p>:records.error?<p role="alert">Unable to load attendance.</p>:records.data?.map(({record:r,name,own})=><div key={r.id} className="flex flex-wrap items-center justify-between gap-2 border-t py-2 text-sm"><span>{name} · {r.date} · {stamp(r.checkIn)} → {stamp(r.checkOut)} · {r.totalBreakMinutes} break minutes</span><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setHistory(r.id)}>History</Button>{own&&<Button size="sm" onClick={()=>{setSelected(r);setReason('');setStart(r.checkIn?new Date(r.checkIn).toISOString().slice(0,16):r.date+'T09:00');setEnd(r.checkOut?new Date(r.checkOut).toISOString().slice(0,16):r.date+'T17:00');setBreaks(String(r.totalBreakMinutes));}}>Request correction</Button>}</div></div>)}{records.data?.length===0&&<p>No records in this window.</p>}<h3 className="font-medium">Correction requests</h3>{requests.isLoading?<p>Loading corrections…</p>:requests.error?<p role="alert">Unable to load correction requests.</p>:requests.data?.map(r=><div key={r.id} className="space-y-2 border-t py-3 text-sm"><p>{r.employee_name} · {r.status} · {r.reason}</p><p>Original: {stamp(r.original.checkIn)} → {stamp(r.original.checkOut)} · {r.original.totalBreakMinutes} break minutes</p><p>Proposed: {stamp(r.proposed.checkIn)} → {stamp(r.proposed.checkOut)} · {r.proposed.totalBreakMinutes} break minutes</p>{r.status==='pending'&&<div className="flex gap-2">{(r.own?['withdrawn']:['approved','rejected']).map(action=><Button variant="outline" size="sm" key={action} onClick={()=>{setDecision({id:r.id,action});setReason('');}}>{action==='withdrawn'?'Withdraw':action==='approved'?'Approve':'Reject'}</Button>)}</div>}{r.decision_reason&&<p>Decision: {r.decision_reason}</p>}</div>)}{!requests.data?.length&&!requests.isLoading&&!requests.error&&<p>No corrections in this window.</p>}
 <Button variant="outline" onClick={()=>setReconcile(!reconcile)}>{reconcile?'Hide':'Load'} roster reconciliation</Button>{reconcile&&<><p className="text-sm">Completed accepted assignments only. Clock records are evidence, not automatic payable time. A daily clock record spanning multiple assignments needs manual review.</p>{roster.isLoading?<p>Reconciling…</p>:roster.error?<p role="alert">Unable to reconcile roster.</p>:roster.data?.map(r=><div key={r.assignmentId} className="border-t py-3 text-sm"><p>{r.name} · {r.team} · {r.role} · {stamp(r.startAt)}</p><p>{r.issue} · {r.timeStatus||'No timesheet'}</p>{r.sheetId&&<Link className="text-primary" href={`/timesheets/${r.sheetId}`}>Review timesheet #{r.sheetId}</Link>}</div>)}{roster.data?.length===0&&<p>No completed assignments in this window.</p>}</>}</>}
 <Dialog open={!!selected||!!decision} onOpenChange={v=>{if(!v&&!op.isPending){setSelected(null);setDecision(null);}}}><DialogContent><DialogHeader><DialogTitle>{selected?'Request attendance correction':'Decide correction'}</DialogTitle><DialogDescription>{selected?'Enter the completed check-in and checkout in UTC. Your reviewer will see the original and proposed values.':'The server rechecks permissions and the current attendance version before applying the decision.'}</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await op.mutateAsync(selected?{url:`/api/attendance/records/${selected.id}/corrections`,body:{version:selected.version,reason,proposed:{checkIn:new Date(start+'Z').toISOString(),checkOut:new Date(end+'Z').toISOString(),totalBreakMinutes:Number(breaks)}}}:{url:`/api/attendance/corrections/${decision.id}/decide`,body:{decision:decision.action,reason}});setSelected(null);setDecision(null);}catch{}}}>{selected&&<><Field label="Check-in (UTC)"><Input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Check-out (UTC)"><Input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Break minutes"><Input type="number" required min={0} max={1439} value={breaks} onChange={e=>setBreaks(e.target.value)}/></Field></>}<Field label="Reason"><Input minLength={5} maxLength={500} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={op.isPending}>{selected?'Submit correction':'Confirm '+decision?.action}</Button></form></DialogContent></Dialog>
 <Dialog open={!!history} onOpenChange={v=>{if(!v)setHistory(null);}}><DialogContent><DialogHeader><DialogTitle>Attendance history</DialogTitle><DialogDescription>Versions recorded since history tracking was introduced.</DialogDescription></DialogHeader><div className="max-h-[60vh] overflow-auto">{versions.isLoading?<p>Loading…</p>:versions.error?<p role="alert">Unable to load history.</p>:versions.data?.map(h=><p key={h.version} className="border-t py-2 text-sm">Version {h.version} · {stamp(h.snapshot.check_in)} → {stamp(h.snapshot.check_out)} · {h.snapshot.total_break_minutes} break minutes · Actor {h.actor_id||'Not recorded'}</p>)}{versions.data?.length===0&&<p>No recorded versions yet.</p>}</div></DialogContent></Dialog></CardContent></Card>;
}
