import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Field,useOperation,selectStyle} from './Common';
export function LeaveRuns({employeeId,account}:{employeeId:number;account:{leaveType:string;year:number;version:number;managed:boolean}}){
 const [kind,setKind]=useState(account.managed?'accrual':'opening'),[month,setMonth]=useState('1'),[available,setAvailable]=useState('0'),[reason,setReason]=useState(''),[preview,setPreview]=useState<any>(null),op=useOperation();
 const payload={employeeId,leaveType:account.leaveType,year:account.year,kind,month:Number(month),verifiedAvailable:Number(available),expectedVersion:account.version,reason};
 return <details className="border-t pt-3"><summary>Accrual, carryover & opening reconciliation</summary><form className="space-y-3 pt-3" onChange={()=>setPreview(null)} onSubmit={async e=>{e.preventDefault();try{setPreview(await op.mutateAsync({url:'/api/leaves/ledger-run',body:{...payload,preview:true}}));}catch{setPreview(null);}}}><Field label="Operation"><select className={selectStyle} value={kind} onChange={e=>setKind(e.target.value)}>{!account.managed&&<option value="opening">Reconcile opening balance</option>}<option value="accrual">Completed-month accrual</option><option value="carryover">Carry from previous year</option></select></Field>{kind==='opening'?<><Field label="Verified available days after pending reservations"><Input required type="number" min={0} max={3660} step="0.01" value={available} onChange={e=>setAvailable(e.target.value)}/></Field><p className="text-sm">Verify against your legacy records. The opening allocation also covers existing approved and pending leave; it does not copy the legacy balance automatically.</p></>:kind==='accrual'?<Field label="Month in selected year"><Input required type="number" min={1} max={12} value={month} onChange={e=>setMonth(e.target.value)}/></Field>:<p className="text-sm">Carryover deducts transferred days from the prior year. Decide all pending source-year leave first.</p>}<Field label="Reason / verification source"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button variant="outline" disabled={op.isPending}>Preview calculation</Button></form>{preview&&<div className="space-y-2 rounded bg-muted p-3 mt-3"><p>{preview.posted?'Already posted':'Proposed credit'}: {preview.days} days</p>{preview.basis.policy&&<p className="text-sm">Policy version {preview.basis.policy.id} · Effective {String(preview.basis.policy.effective_from).slice(0,10)}</p>}{preview.basis.eligibleDays!==undefined&&<p className="text-sm">Eligible calendar days {preview.basis.eligibleDays} / {preview.basis.calendarDays}</p>}{preview.basis.sourceAvailable!==undefined&&<p className="text-sm">Source available: {preview.basis.sourceAvailable} days</p>}{!preview.posted&&<Button disabled={op.isPending} onClick={async()=>{try{await op.mutateAsync({url:'/api/leaves/ledger-run',body:{...payload,preview:false,expectedPolicyId:preview.basis.policy?.id,expectedQuote:preview.quote}});setPreview(null);}catch{setPreview(null);}}}>Post reviewed calculation</Button>}</div>}</details>;
}
export function LegacyLeave({employeeId}:{employeeId:number}){
 const q=useQuery<{legacyBalances:any[];unresolved:any[]}>({queryKey:[`/api/leaves/ledger-reconciliation/${employeeId}`]}),op=useOperation();const [selected,setSelected]=useState<any>(null),[splits,setSplits]=useState<Record<string,string>>({}),[reason,setReason]=useState('');
 return <details><summary>Legacy balance evidence & cross-year requests</summary>{q.isLoading?<p>Loading…</p>:q.error?<p role="alert">Unable to load legacy reconciliation.</p>:<><div className="space-y-2 py-3 text-sm">{q.data?.legacyBalances.map(b=><p key={b.id}>Leave type #{b.leaveTypeId}, {b.year}: opening {b.openingBalance}, accrued {b.accrued}, used {b.used}, pending {b.pending}, adjusted {b.adjusted}. Verify these values before opening reconciliation.</p>)}{!q.data?.legacyBalances.length&&<p>No legacy balance rows.</p>}</div>{q.data?.unresolved.map(l=><p key={l.id} className="text-sm py-2">#{l.id} · {l.leaveType} · {l.startDate} → {l.endDate} · {l.totalDays} days <Button size="sm" variant="outline" onClick={()=>{setSelected(l);setReason('');setSplits(Object.fromEntries(Array.from({length:Number(l.endDate.slice(0,4))-Number(l.startDate.slice(0,4))+1},(_,i)=>[String(Number(l.startDate.slice(0,4))+i),'0'])));}}>Allocate years</Button></p>)}{!q.data?.unresolved.length&&<p className="text-sm">No unresolved cross-year requests.</p>}{selected&&<form className="space-y-3 p-3 border" onSubmit={async e=>{e.preventDefault();try{await op.mutateAsync({url:`/api/leaves/ledger-reconciliation/${employeeId}/split`,body:{leaveId:selected.id,splits:Object.entries(splits).map(([year,days])=>({year:Number(year),days:Number(days)})),reason}});setSelected(null);}catch{}}}><p>Preserve the original total of {selected.totalDays} days. Each affected year needs an allocation.</p>{Object.entries(splits).map(([year,days])=><Field key={year} label={year+' days'}><Input required type="number" min={0} max={367} step="0.01" value={days} onChange={e=>setSplits({...splits,[year]:e.target.value})}/></Field>)}<Field label="Reconciliation evidence"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={op.isPending}>Save verified year split</Button></form>}</>}</details>;
}
