import {useEffect,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Field,useOperation,selectStyle,today} from './Common';
import {ruleScopeLabels,ruleScopes} from '@shared/calculation-rules';
export function OperationalPolicies(){
 const [kind,setKind]=useState('leave'),[scope,setScope]=useState('');const types=useQuery<{name:string;active:boolean}[]>({queryKey:['/api/leave-types']});
 return <Card><CardHeader><CardTitle>Leave accrual & time-to-pay policies</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm">Admin/Super Admin publishes dated versions. Existing accrual runs and payroll imports retain their saved policy. Backdated versions affect only new calculations; review the effective date carefully.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="Policy"><select className={selectStyle} value={kind} onChange={e=>{setKind(e.target.value);setScope('');}}><option value="leave">Leave accrual and carryover</option><option value="timepay">Approved time earnings</option></select></Field><Field label={kind==='leave'?'Leave type':'Employee policy group'}><select className={selectStyle} value={scope} onChange={e=>setScope(e.target.value)}><option value="">Select…</option>{kind==='leave'?types.data?.filter(t=>t.active).map(t=><option key={t.name}>{t.name}</option>):ruleScopes.map(s=><option key={s} value={s}>{ruleScopeLabels[s]}</option>)}</select></Field></div>{types.error&&kind==='leave'&&<p role="alert">Unable to load leave types.</p>}{scope&&<Editor key={kind+scope} kind={kind} scope={scope}/>}</CardContent></Card>;
}
const leaveDefaults={enabled:false,monthlyDays:0,annualCap:0,prorate:true,minServiceDays:0,carryoverCap:0},payDefaults={enabled:false,hourlyRateCents:0,overtimeAfterMinutes:480,overtimeMultiplierHundredths:100,roundingMode:'nearest'};
const labels:Record<string,string>={enabled:'Enable calculations',monthlyDays:'Days accrued per completed month',annualCap:'Maximum accrual days per year',prorate:'Prorate for eligible calendar days',minServiceDays:'Service days before accrual eligibility',carryoverCap:'Maximum days carried into the next year',hourlyRateCents:'Hourly rate (QAR)',overtimeAfterMinutes:'Overtime threshold per timesheet (minutes)',overtimeMultiplierHundredths:'Overtime multiplier',roundingMode:'Earning rounding to cents'};
function Editor({kind,scope}:{kind:string;scope:string}){
 const q=useQuery<any[]>({queryKey:['/api/attendance/policies',{kind,scope}]}),op=useOperation();const [rules,setRules]=useState<Record<string,any>>({...kind==='leave'?leaveDefaults:payDefaults}),[version,setVersion]=useState<number|null>(null),[date,setDate]=useState(today()),[reason,setReason]=useState('');
 useEffect(()=>{if(q.data&&version===null){setRules(q.data[0]?.rules||{...kind==='leave'?leaveDefaults:payDefaults});setVersion(q.data[0]?.id||0);}},[q.data,version,kind]);
 if(q.isLoading)return <p>Loading policies…</p>;if(q.error)return <p role="alert">Policy administration is unavailable for this account.</p>;
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await op.mutateAsync({url:'/api/attendance/policies',body:{kind,scope,rules,effectiveFrom:date,reason,expectedVersion:version}});setVersion(null);setReason('');}catch{}}}><p className="text-sm">Editing from published version {version||'none'}. {kind==='timepay'?'Rates use the shift start date and policy group; overtime is per approved timesheet, not a daily or weekly aggregate. No rates are enabled by default.':'Accrual runs use the first day of the month; carryover uses January 1. They are previewed and posted by an administrator from the leave ledger.'}</p><div className="grid gap-3 sm:grid-cols-2">{Object.keys(kind==='leave'?leaveDefaults:payDefaults).map(k=>[k,rules[k]] as const).map(([k,v])=><Field key={k} label={labels[k]}>{typeof v==='boolean'?<input type="checkbox" checked={v} onChange={e=>setRules({...rules,[k]:e.target.checked})}/>:k==='roundingMode'?<select className={selectStyle} value={v} onChange={e=>setRules({...rules,[k]:e.target.value})}>{['nearest','down','up'].map(m=><option key={m}>{m}</option>)}</select>:<Input required type="number" min={0} step={['monthlyDays','annualCap','carryoverCap','hourlyRateCents','overtimeMultiplierHundredths'].includes(k)?'0.01':'1'} value={['hourlyRateCents','overtimeMultiplierHundredths'].includes(k)?v/100:v} onChange={e=>setRules({...rules,[k]:['hourlyRateCents','overtimeMultiplierHundredths'].includes(k)?Math.round(Number(e.target.value)*100):Number(e.target.value)})}/>}</Field>)}</div><Field label="Effective date"><Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Change reason"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={op.isPending||version===null}>Publish version</Button><details><summary>Version history</summary>{q.data?.map(v=><p key={v.id} className="text-sm py-2">Version {v.id} · Effective {String(v.effective_from).slice(0,10)} · {v.reason}</p>)}</details></form>;
}
