import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Field,useOperation,selectStyle} from './Common';
export function TimePay({records,canUpdate}:{records:{id:number;employeeName:string;status:string}[];canUpdate:boolean}){
 const [id,setId]=useState('');return <details className="border rounded p-3"><summary>Approved time → payroll earnings</summary><p className="text-sm my-3">Preview the saved hourly/overtime policy for each approved timesheet. Earnings are added as a separate allowance; ensure basic salary does not already include the same hours. Importing reserves those timesheets. Recording payment locks them permanently.</p><Field label="Payroll record"><select className={selectStyle} value={id} onChange={e=>setId(e.target.value)}><option value="">Select…</option>{records.map(r=><option key={r.id} value={r.id}>#{r.id} · {r.employeeName} · {r.status}</option>)}</select></Field>{id&&records.some(r=>String(r.id)===id)&&<Import key={id} id={id} editable={canUpdate&&records.find(r=>String(r.id)===id)?.status==='pending'}/>}</details>;
}
function Import({id,editable}:{id:string;editable:boolean}){
 const [reason,setReason]=useState(''),[adjustment,setAdjustment]=useState('0'),[adjustmentReason,setAdjustmentReason]=useState(''),[preview,setPreview]=useState<any>(null),[release,setRelease]=useState(false),op=useOperation();const q=useQuery<any[]>({queryKey:[`/api/payroll/${id}/time-import`]}),active=q.data?.some(e=>!e.released_at),payload={reason,adjustmentCents:Math.round(Number(adjustment)*100),adjustmentReason};
 return <div className="space-y-3 pt-3">{q.isLoading?<p>Loading imported earnings…</p>:q.error?<p role="alert">Unable to load imported earnings.</p>:<>{q.data?.map(e=><p key={e.id} className="border-t py-2 text-sm">{e.timesheet_id?'Timesheet #'+e.timesheet_id:'Adjustment'} · QAR {(e.amount_cents/100).toFixed(2)} · {e.released_at?'Released':'Included'}{e.basis.policy?` · Rate policy v${e.basis.policy.id} · ${e.basis.payableMinutes} payable minutes`:''} · {e.basis.reason}</p>)}{editable&&!active&&<form className="space-y-3" onChange={()=>setPreview(null)} onSubmit={async e=>{e.preventDefault();try{setPreview(await op.mutateAsync({url:`/api/payroll/${id}/time-import`,body:{...payload,preview:true}}));}catch{setPreview(null);}}}><Field label="Import reason / hours verification"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Field label="Earning adjustment (+/− QAR)"><Input required type="number" step="0.01" value={adjustment} onChange={e=>setAdjustment(e.target.value)}/></Field><Field label="Adjustment reason (required if nonzero)"><Input required={Number(adjustment)!==0} minLength={Number(adjustment)!==0?5:0} value={adjustmentReason} onChange={e=>setAdjustmentReason(e.target.value)}/></Field><Button variant="outline" disabled={op.isPending}>Preview approved time</Button></form>}{preview&&<div className="rounded bg-muted p-3 space-y-2">{preview.lines.map((l:any)=><p key={l.timesheetId} className="text-sm">#{l.timesheetId}: {l.regularMinutes} regular + {l.overtimeMinutes} overtime minutes · QAR {(l.amountCents/100).toFixed(2)} · policy v{l.policy.id}</p>)}<p>Time earnings including adjustment: QAR {(preview.totalCents/100).toFixed(2)}. New net salary: QAR {preview.netSalary}.</p><Button disabled={op.isPending} onClick={async()=>{try{await op.mutateAsync({url:`/api/payroll/${id}/time-import`,body:{...payload,preview:false,quote:preview.quote}});setPreview(null);}catch{setPreview(null);}}}>Import reviewed earnings</Button></div>}{editable&&active&&<><Button variant="outline" onClick={()=>setRelease(!release)}>Release time import</Button>{release&&<form className="space-y-2" onSubmit={async e=>{e.preventDefault();try{await op.mutateAsync({url:`/api/payroll/${id}/time-release`,body:{reason}});setRelease(false);setPreview(null);}catch{}}}><p className="text-sm">Removes the imported allowance and releases the timesheets for correction. The import history is retained.</p><Field label="Release reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={op.isPending}>Confirm release</Button></form>}</>}</>}</div>;
}
