import {useState,type FormEvent,type InputHTMLAttributes} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Field,Section,Table,QueryError,fieldClass} from './Operations';
import type {WorkflowEvent} from '@shared/employee-services';
export type Directory={employees:{id:number;name:string;code:string;own:boolean}[];approvers:{id:number;name:string;role:string}[];canConfigure?:boolean};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const text=(f:FormData,key:string)=>String(f.get(key)||'').trim();
export const number=(f:FormData,key:string)=>Number(f.get(key));
export function Input({label,...props}:InputHTMLAttributes<HTMLInputElement>&{label:string}){return <Field label={label}><input className={fieldClass} {...props}/></Field>;}
export function Note({label='Reason / evidence',name='reason',value=''}:{label?:string;name?:string;value?:string}){return <Field label={label}><textarea className={fieldClass} rows={3} name={name} defaultValue={value} minLength={5} maxLength={2000} required/></Field>;}
export function Toggle({label,name,checked=false}:{label:string;name:string;checked?:boolean}){return <label className="flex items-center gap-2 text-sm"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>;}
export function useSave<T=unknown>(done?:(value:T)=>void){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({url,body,method='POST'}:{url:string;body:unknown;method?:string})=>apiJson<T>(url,{method,body}),onSuccess:value=>{cache.invalidateQueries();toast({title:'Saved successfully'});done?.(value);},onError:e=>toast({title:'Unable to save',description:e.message,variant:'destructive'})});}
export function Pager({page,total,size=25,onChange}:{page:number;total:number;size?:number;onChange:(p:number)=>void}){return <div className="flex items-center gap-3 text-sm"><Button variant="outline" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</Button><span>{total} records · Page {page}</span><Button variant="outline" disabled={page*size>=total} onClick={()=>onChange(page+1)}>Next</Button></div>;}
export function EmployeePicker({base,value,onChange,optional=false}:{base:string;value:string;onChange:(s:string)=>void;optional?:boolean}){
  const [search,setSearch]=useState('');const query=useQuery<Directory>({queryKey:[base+'/directory',{q:search}]});return <div className="space-y-3"><Input label="Find employee" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or employee ID"/><Field label={optional?'Applies to':'Employee'}><select className={fieldClass} required={!optional} value={value} onChange={e=>onChange(e.target.value)}><option value="">{optional?'Company default':'Select employee'}</option>{value&&!query.data?.employees.some(e=>String(e.id)===value)&&<option value={value}>Selected employee #{value}</option>}{query.data?.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.code}{e.own?' (you)':''}</option>)}</select></Field><QueryError error={query.error}/></div>;
}
export function ApproverPicker({base,value,name='approverId'}:{base:string;value?:number;name?:string}){const query=useQuery<Directory>({queryKey:[base+'/directory']});return <Field label="Independent approver"><select className={fieldClass} name={name} defaultValue={value||''} required><option value="">Select an approver</option>{query.data?.approvers.map(u=><option key={u.id} value={u.id}>{u.name} · {u.role.replaceAll('_',' ')}</option>)}</select><QueryError error={query.error}/></Field>;}
export function History({events}:{events:WorkflowEvent[]}){return <details className="rounded-lg border p-4"><summary className="cursor-pointer font-semibold">Activity & decision history</summary><ol className="mt-4 space-y-4">{[...events].reverse().map((e,i)=><li key={i} className="border-b pb-3 text-sm"><div className="font-medium">{e.action.replaceAll('_',' ')} · Version {e.version}</div><p className="text-muted-foreground">{new Date(e.at).toLocaleString()} · User #{e.actorId}</p><p className="whitespace-pre-wrap mt-1">{e.reason}</p></li>)}</ol></details>;}
export type FileInfo={id:number;filename:string;size:number;createdAt:string};
export function Files({base,id,version,files,editable,storage}:{base:string;id:number;version:number;files:FileInfo[];editable:boolean;storage:boolean}){
  const mutation=useSave(),{toast}=useToast(),[file,setFile]=useState<File|null>(null);return <Section title="Private evidence"><Table headers={['File','Size','']} rows={files.map(f=>[f.filename,`${Math.ceil(f.size/1024)} KB`,<Button variant="outline" onClick={async()=>{try{const r=await apiJson<{url:string}>(`${base}/${id}/files/${f.id}/download`);const a=document.createElement('a');a.href=r.url;a.target='_blank';a.rel='noopener noreferrer';a.click();}catch(e){toast({title:'Unable to download',description:e instanceof Error?e.message:'Try again',variant:'destructive'});}}}>Download</Button>])}/>{editable&&<form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();if(!file)return;const body=new FormData();body.set('file',file);body.set('version',String(version));mutation.mutate({url:`${base}/${id}/files`,body});}}><Input label="Attach PDF, PNG or JPEG (up to 10 MB)" type="file" accept=".pdf,.png,.jpg,.jpeg" required disabled={!storage} onChange={e=>setFile(e.target.files?.[0]||null)}/><Button disabled={!file||mutation.isPending||!storage}>Attach evidence</Button></form>}{editable&&!storage&&<p className="text-sm text-muted-foreground">An administrator must configure private file storage before attachments can be added.</p>}</Section>;
}
export function ActionForm({base,id,version,actions,score=false,progress=false,fulfill=false}:{base:string;id:number;version:number;actions:{key:string;label:string}[];score?:boolean;progress?:boolean;fulfill?:boolean}){
  const mutation=useSave();if(!actions.length)return null;return <form className="space-y-3 rounded-lg border p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),action=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value');if(!action)return;mutation.mutate({url:`${base}/${id}/actions`,body:{version,action,reason:text(f,'reason'),...(action==='verify'?{score:number(f,'score')}:{}),...(action==='progress'?{progress:number(f,'progress')}:{}),...(action==='fulfill'?{reference:text(f,'reference'),confirmed:f.has('confirmed')}:{})}});}}><Note/>{progress&&<Input label="Progress (%)" name="progress" type="number" min={0} max={99} defaultValue={0}/>} {score&&<Input label="Verified score (%)" name="score" type="number" min={0} max={100}/>} {fulfill&&<><Input label="Activation or reimbursement reference" name="reference" minLength={3} maxLength={150}/><Toggle name="confirmed" label="I confirm the benefit was activated or reimbursement was completed externally"/></>}<div className="flex flex-wrap gap-2">{actions.map(a=><Button key={a.key} name="action" value={a.key} disabled={mutation.isPending} variant={['reject','cancel','withdraw'].includes(a.key)?'outline':'default'}>{a.label}</Button>)}</div></form>;
}
export function Reassign({base,directoryBase,id,version}:{base:string;directoryBase:string;id:number;version:number}){const mutation=useSave();return <details className="rounded border p-4"><summary className="cursor-pointer text-sm font-medium">Change assigned reviewer</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({url:`${base}/${id}/actions`,body:{version,action:'reassign',approverId:number(f,'approverId'),reason:text(f,'reason')}});}}><ApproverPicker base={directoryBase}/><Note/><Button disabled={mutation.isPending}>Assign reviewer</Button></form></details>;}
