import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'wouter';
import { BookOpen, CircleCheck, Clock3, Inbox, LifeBuoy, LockKeyhole, Plus, RefreshCw, Settings2, AlertCircle, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Field, QueryError, fieldClass } from './Operations';
import { HelpdeskKnowledge, HelpdeskPolicies } from './HelpdeskOperations';
import { HelpdeskAutomationAccess } from './HelpdeskAutomation';
import { HelpdeskSettings } from './HelpdeskSettings';
import { caseStatuses, statusLabels, type CaseList, type HelpdeskConfig } from '@shared/helpdesk';
import { categoryName, type HelpdeskOverview } from '@shared/helpdesk-workspace';

const stamp=(value:string)=>new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
const colors=['bg-blue-500','bg-violet-500','bg-amber-500','bg-emerald-500','bg-slate-400'];
export function HelpdeskWorkspace({config,create}:{config:HelpdeskConfig;create:(category?:string)=>void}) {
  const [tab,setTab]=useState('requests');
  return <div className="space-y-6">
    <nav aria-label="Helpdesk sections" className="flex flex-wrap gap-2 rounded-xl border bg-card p-2">{[{id:'requests',label:'Requests',icon:Inbox},{id:'knowledge',label:'Knowledge base',icon:BookOpen},...(config.canManagePolicies?[{id:'admin',label:'Administration',icon:Settings2}]:[])].map(t=><Button key={t.id} aria-current={tab===t.id?'page':undefined} variant={tab===t.id?'default':'ghost'} onClick={()=>setTab(t.id)}><t.icon className="mr-2 h-4 w-4"/>{t.label}</Button>)}</nav>
    {tab==='requests'&&<Requests config={config} create={create}/>}
    {tab==='knowledge'&&<HelpdeskKnowledge config={config}/>}
    {tab==='admin'&&config.canManagePolicies&&<div className="space-y-5"><HelpdeskSettings config={config}/><HelpdeskPolicies config={config}/><HelpdeskAutomationAccess/></div>}
  </div>;
}
function Requests({config,create}:{config:HelpdeskConfig;create:(category?:string)=>void}) {
  const [view,setView]=useState('mine'),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[assignment,setAssignment]=useState('all'),[overdue,setOverdue]=useState(false),[search,setSearch]=useState(''),[term,setTerm]=useState(''),[page,setPage]=useState(1);
  useEffect(()=>{const timer=setTimeout(()=>{setTerm(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search]);
  const list=useQuery<CaseList>({queryKey:['/api/helpdesk/cases',{view,status,category,assignment,overdue,q:term,page,limit:20}],refetchInterval:30000,refetchIntervalInBackground:false});
  const overview=useQuery<HelpdeskOverview>({queryKey:['/api/helpdesk/overview',{view}],refetchInterval:30000,refetchIntervalInBackground:false});
  const totals=overview.data;
  const filtered=Boolean(status||category||assignment!=='all'||overdue||search);
  function clear(){setStatus('');setCategory('');setAssignment('all');setOverdue(false);setSearch('');setTerm('');setPage(1);}
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button aria-pressed={view==='mine'} variant={view==='mine'?'default':'outline'} onClick={()=>{setView('mine');clear();}}>My requests</Button>{config.canWorkQueue&&<Button aria-pressed={view==='queue'} variant={view==='queue'?'default':'outline'} onClick={()=>{setView('queue');clear();}}>HR queue</Button>}</div><Button variant="outline" disabled={list.isFetching||overview.isFetching} onClick={()=>{list.refetch();overview.refetch();}}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    <QueryError error={overview.error}/>
    {overview.isLoading?<div role="status" className="rounded-xl border p-5 text-muted-foreground">Loading request overview…</div>:!overview.error&&totals&&<>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'Total requests',value:totals.total,icon:Inbox,color:'text-primary'},{label:'Active requests',value:totals.active,icon:Clock3,color:'text-blue-600 dark:text-blue-400'},{label:'Overdue',value:totals.overdue,icon:AlertCircle,color:'text-amber-600 dark:text-amber-400'},{label:'Completed',value:totals.completed,icon:CircleCheck,color:'text-emerald-600 dark:text-emerald-400'}].map(metric=><div key={metric.label} className="rounded-2xl border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><p className="text-xs sm:text-sm text-muted-foreground">{metric.label}</p><metric.icon className={`h-5 w-5 shrink-0 ${metric.color}`}/></div><p className="mt-3 text-3xl font-semibold tabular-nums">{metric.value}</p></div>)}</div>
      <div className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Request progress</h2><span className="text-xs text-muted-foreground">{view==='mine'?'All your requests':'All requests you can handle'} · Independent of filters</span></div>{totals.total>0?<><div className="my-4 flex h-3 overflow-hidden rounded-full bg-muted" aria-hidden="true">{caseStatuses.map((s,i)=>{const count=totals.statuses.find(row=>row.status===s)?.count||0;return count>0?<div key={s} className={colors[i]} style={{width:`${count/totals.total*100}%`}}/>:null;})}</div><div className="flex flex-wrap gap-x-5 gap-y-2">{caseStatuses.map((s,i)=><button type="button" key={s} className="flex items-center gap-2 rounded text-sm hover:underline focus-visible:outline-primary" aria-pressed={status===s} onClick={()=>{clear();setStatus(s);}}><span className={`h-2.5 w-2.5 rounded-full ${colors[i]}`} aria-hidden="true"/>{statusLabels[s]} <strong>{totals.statuses.find(row=>row.status===s)?.count||0}</strong></button>)}</div></>:<p className="mt-3 text-sm text-muted-foreground">Progress will appear when requests are created.</p>}{view==='queue'&&<p className="mt-4 text-xs text-muted-foreground">{totals.unassigned} active requests awaiting assignment · {totals.waiting} waiting for an employee reply</p>}</div>
    </>}
    <section className="overflow-hidden rounded-2xl border bg-card">
      <div className="space-y-4 border-b p-4 sm:p-5"><h2 className="font-semibold">{view==='mine'?'Your requests':'Team support queue'}</h2><div className={`grid items-end gap-3 sm:grid-cols-2 ${view==='queue'?'xl:grid-cols-4':'xl:grid-cols-3'}`}><Field label="Search subject"><Input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="Search requests…"/></Field><Field label="Status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{caseStatuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field><Field label="Category"><select className={fieldClass} value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option>{config.workspace.categories.map(c=><option key={c.id} value={c.id}>{c.label}{c.enabled?'':' (inactive)'}</option>)}</select></Field>{view==='queue'&&<Field label="Assignment"><select className={fieldClass} value={assignment} onChange={e=>{setAssignment(e.target.value);setPage(1);}}><option value="all">All handlers</option><option value="mine">Assigned to me</option><option value="unassigned">Unassigned</option></select></Field>}</div><div className="flex items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={overdue} onChange={e=>{setOverdue(e.target.checked);setPage(1);}}/>Overdue only</label>{filtered&&<Button size="sm" variant="ghost" onClick={clear}>Clear filters</Button>}</div></div>
      {list.isLoading?<p role="status" className="p-8">Loading requests…</p>:list.error?<div className="p-5"><QueryError error={list.error}/><Button variant="outline" className="mt-3" onClick={()=>list.refetch()}>Try again</Button></div>:!list.data?.items.length?<div className="flex flex-col items-center gap-3 p-10 text-center"><LifeBuoy className="h-10 w-10 text-primary"/><h3 className="font-semibold">{filtered?'No matching requests':'No requests yet'}</h3><p className="text-sm text-muted-foreground">{filtered?'Adjust your filters to find a request.':'Create a request when you need support.'}</p><Button variant="outline" onClick={()=>filtered?clear():create()}>{filtered?'Clear filters':'New request'}</Button></div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr>{['Request','Status','People','Response targets','Updated'].map(h=><th scope="col" key={h} className={`p-4 ${h==='People'||h==='Updated'?'hidden lg:table-cell':''}`}>{h}</th>)}</tr></thead><tbody className="divide-y">{list.data.items.map(row=>{const responseLate=!['resolved','closed'].includes(row.status)&&!row.firstRespondedAt&&row.firstResponseDueAt&&Date.parse(row.firstResponseDueAt)<Date.now();const late=!['resolved','closed'].includes(row.status)&&row.resolutionDueAt&&Date.parse(row.resolutionDueAt)<Date.now();return <tr key={row.id} className="hover:bg-muted/30"><td className="min-w-[210px] max-w-sm p-4"><Link href={`/helpdesk/${row.id}`} className="flex items-start gap-2 font-medium text-primary hover:underline"><span className="break-words">#{row.id} · {row.title}</span><ArrowUpRight className="mt-0.5 h-4 w-4 shrink-0"/></Link><p className="mt-1 text-xs text-muted-foreground">{categoryName(config.workspace,row.category)}</p>{row.confidential&&<span className="mt-2 inline-flex items-center gap-1 text-xs"><LockKeyhole className="h-3 w-3"/>Confidential</span>}<p className="mt-2 text-xs text-muted-foreground lg:hidden">{row.assigneeName||'Awaiting assignment'}</p></td><td className="p-4"><Badge variant={['resolved','closed'].includes(row.status)?'secondary':'outline'}>{statusLabels[row.status]}</Badge></td><td className="hidden p-4 lg:table-cell"><p>{row.requesterName}</p><p className="mt-1 text-xs text-muted-foreground">Handler: {row.assigneeName||'Unassigned'}</p></td><td className={`p-4 text-xs ${late?'text-destructive':'text-muted-foreground'}`}>{row.firstResponseDueAt&&!row.firstRespondedAt&&<p className={`mb-2 ${responseLate?'text-destructive':''}`}>Reply: {stamp(row.firstResponseDueAt)}{responseLate?' (overdue)':''}</p>}{row.resolutionDueAt?<><span>Resolution: </span><time>{stamp(row.resolutionDueAt)}</time>{late&&<p className="mt-1 font-medium">Overdue</p>}</>:'No target configured'}</td><td className="hidden whitespace-nowrap p-4 text-xs text-muted-foreground lg:table-cell">{stamp(row.updatedAt)}</td></tr>;})}</tbody></table></div>}
      {!list.error&&list.data&&<div className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-sm"><p>{list.data.total} requests · Page {page} of {Math.max(1,Math.ceil(list.data.total/20))}</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={page===1||list.isFetching} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" size="sm" disabled={page*20>=list.data.total||list.isFetching} onClick={()=>setPage(page+1)}>Next</Button></div></div>}
    </section>
    <section className="space-y-3"><h2 className="font-semibold">Start a request</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{config.workspace.categories.filter(c=>c.enabled).map(c=><button type="button" key={c.id} onClick={()=>create(c.id)} className="group flex gap-3 rounded-xl border bg-card p-4 text-left transition-colors hover:border-primary/50 hover:bg-primary/5 focus-visible:outline-primary"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">{c.confidential?<LockKeyhole className="h-4 w-4"/>:<Plus className="h-4 w-4"/>}</span><span><span className="font-medium">{c.label}</span>{c.description&&<span className="mt-1 block text-xs leading-relaxed text-muted-foreground">{c.description}</span>}{c.confidential&&<span className="mt-1 block text-xs text-muted-foreground">Confidential</span>}</span></button>)}</div></section>
    {config.workspace.contactInstructions&&<aside className="rounded-xl border bg-muted/30 p-5"><h2 className="font-medium">Support information</h2><p className="mt-2 whitespace-pre-wrap break-words text-sm text-muted-foreground">{config.workspace.contactInstructions}</p></aside>}
  </div>;
}
