import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Section, Field, Table, QueryError, fieldClass } from './Operations';
import { Input, Note, text, useSave } from './EmployeeServiceUI';
import { helpdeskAutomationInput, type HelpdeskAutomationConfig, type HelpdeskAutomationPolicy } from '@shared/helpdesk-automation';

const base='/api/helpdesk/automation';
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const stamp=(value:string|null)=>value?new Date(value).toLocaleString():'Not yet run';
type Runtime={last_started_at:string|null;last_finished_at:string|null;cases_checked:number;notifications_created:number;cases_escalated:number;enabled:boolean};
export function HelpdeskAutomationAccess(){
  const query=useQuery<{canConfigure:boolean}>({queryKey:[base+'/config']}),[open,setOpen]=useState(false);
  if(!query.data?.canConfigure)return null;
  return <div className="space-y-4"><Button variant="outline" onClick={()=>setOpen(!open)}>{open?'Close calendar & automation':'Business hours & automated reminders'}</Button>{open&&<HelpdeskAutomation/>}</div>;
}
export default function HelpdeskAutomation(){
  const query=useQuery<{policy:HelpdeskAutomationPolicy;runtime:Runtime}>({queryKey:[base+'/policy']}),[offset,setOffset]=useState(0),history=useQuery<{version:number;config:HelpdeskAutomationConfig;reason:string;created_at:string}[]>({queryKey:[base+'/policy/history',{offset}]}),mutation=useSave();
  return <div className="space-y-5"><Section title="Helpdesk business hours & automation"><QueryError error={query.error}/>{query.isLoading&&<p>Loading automation rules…</p>}{query.data&&<><AutomationForm key={query.data.policy.version} policy={query.data.policy}/><div className="rounded border p-4 space-y-2 text-sm"><h3 className="font-semibold">Processing status</h3><p>Last finished: {stamp(query.data.runtime.last_finished_at)}</p><p>{query.data.runtime.cases_checked} cases checked · {query.data.runtime.notifications_created} in-app reminders created · {query.data.runtime.cases_escalated} cases escalated</p><p className="text-muted-foreground">Processing runs while the application is awake. A sleeping free hosting service catches up after it starts. Notifications remain inside E3 HR.</p><Button variant="outline" disabled={mutation.isPending||!query.data.policy.config.enabled} onClick={()=>mutation.mutate({url:base+'/run',body:{}})}>Process due reminders now</Button></div></>}</Section><Section title="Calendar & automation rule history"><QueryError error={history.error}/><Table headers={['Version','Changed','Clock','Automation','Reason','']} rows={(history.data||[]).map(row=>[row.version,stamp(row.created_at),row.config.clockMode==='business'?row.config.calendar.timezone+' business hours':'Elapsed hours',row.config.enabled?'Enabled':'Disabled',row.reason,<details><summary className="cursor-pointer">Saved rules</summary><CalendarSummary config={row.config}/><p className="mt-2 text-sm">Reminders: {row.config.remindersEnabled?'enabled':'disabled'} · Escalation: {row.config.autoEscalate?'enabled':'disabled'} · Escalation delay {row.config.escalationDelayMinutes} minutes</p></details>])}/><div className="flex items-center gap-3"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</Button><span className="text-sm">Page {offset/25+1}</span><Button variant="outline" disabled={history.data?.length!==25} onClick={()=>setOffset(offset+25)}>Next</Button></div></Section></div>;
}
function Toggle({label,value,change}:{label:string;value:boolean;change:(value:boolean)=>void}){return <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={value} onChange={event=>change(event.target.checked)} className="mt-1"/><span>{label}</span></label>;}
function AutomationForm({policy}:{policy:HelpdeskAutomationPolicy}){
  const [config,setConfig]=useState<HelpdeskAutomationConfig>(()=>structuredClone(policy.config)),[error,setError]=useState(''),mutation=useSave();
  const update=<K extends keyof HelpdeskAutomationConfig>(key:K,value:HelpdeskAutomationConfig[K])=>setConfig(current=>({...current,[key]:value}));
  const changeWindows=(day:number,windows:{start:string;end:string}[])=>setConfig(current=>({...current,calendar:{...current.calendar,week:current.calendar.week.map(item=>item.day===day?{...item,windows}:item)}}));
  return <form className="space-y-5" onSubmit={event=>{event.preventDefault();setError('');const input=helpdeskAutomationInput.safeParse({version:policy.version,config,reason:text(new FormData(event.currentTarget),'reason')});if(!input.success){setError(input.error.issues.map(issue=>issue.message).join('; '));return;}mutation.mutate({url:base+'/policy',body:input.data});}}>
    <p className="text-sm text-muted-foreground">New cases preserve the calendar and automation version in force when they open. Existing deadlines stay unchanged. Turning automation off here also pauses processing for cases created under earlier versions.</p><Field label="How response targets count hours"><select className={fieldClass} value={config.clockMode} onChange={event=>update('clockMode',event.target.value as HelpdeskAutomationConfig['clockMode'])}><option value="business">Count configured business opening hours</option><option value="elapsed">Count all elapsed hours, including weekends</option></select></Field><Input label="Calendar timezone" value={config.calendar.timezone} onChange={event=>setConfig(current=>({...current,calendar:{...current.calendar,timezone:event.target.value}}))} placeholder="Asia/Qatar" required/>
    <div className="space-y-3"><h3 className="font-semibold">Weekly opening windows</h3><p className="text-sm text-muted-foreground">Use separate windows for breaks. Leave a day empty when the helpdesk is closed. Windows must be ordered and end on the same day.</p>{[...config.calendar.week].sort((a,b)=>a.day-b.day).map(day=><div key={day.day} className="rounded border p-3 space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><strong className="text-sm">{weekdays[day.day]}{!day.windows.length?' · Closed':''}</strong><Button type="button" size="sm" variant="outline" disabled={day.windows.length>=4} onClick={()=>changeWindows(day.day,[...day.windows,{start:day.windows.length?day.windows[day.windows.length-1].end:'',end:''}])}>Add opening window</Button></div>{day.windows.map((window,index)=><div key={index} className="flex flex-wrap items-end gap-3"><Input label="Opens" type="time" value={window.start} required onChange={event=>changeWindows(day.day,day.windows.map((value,position)=>position===index?{...value,start:event.target.value}:value))}/><Input label="Closes" type="time" value={window.end} required onChange={event=>changeWindows(day.day,day.windows.map((value,position)=>position===index?{...value,end:event.target.value}:value))}/><Button type="button" variant="ghost" onClick={()=>changeWindows(day.day,day.windows.filter((_,position)=>position!==index))}>Remove window</Button></div>)}</div>)}</div>
    <div className="space-y-3"><h3 className="font-semibold">Holidays and closure dates</h3>{config.calendar.holidays.map((holiday,index)=><div key={index} className="grid items-end gap-3 sm:grid-cols-[1fr_2fr_auto]"><Input label="Date" type="date" value={holiday.date} required onChange={event=>setConfig(current=>({...current,calendar:{...current.calendar,holidays:current.calendar.holidays.map((value,position)=>position===index?{...value,date:event.target.value}:value)}}))}/><Input label="Closure name" value={holiday.name} maxLength={120} required onChange={event=>setConfig(current=>({...current,calendar:{...current.calendar,holidays:current.calendar.holidays.map((value,position)=>position===index?{...value,name:event.target.value}:value)}}))}/><Button type="button" variant="ghost" onClick={()=>setConfig(current=>({...current,calendar:{...current.calendar,holidays:current.calendar.holidays.filter((_,position)=>position!==index)}}))}>Remove</Button></div>)}<Button type="button" variant="outline" disabled={config.calendar.holidays.length>=500} onClick={()=>setConfig(current=>({...current,calendar:{...current.calendar,holidays:[...current.calendar.holidays,{date:'',name:''}]}}))}>Add closure date</Button></div>
    <div className="space-y-4 rounded border p-4"><h3 className="font-semibold">In-app reminders & escalation</h3><Toggle label="Enable automatic processing for new cases and allow processing of existing enrolled cases" value={config.enabled} change={value=>update('enabled',value)}/><Toggle label="Send in-app response and resolution reminders" value={config.remindersEnabled} change={value=>update('remindersEnabled',value)}/><div className="grid gap-3 md:grid-cols-3"><Input label="Reminder before deadline (elapsed minutes)" type="number" value={config.reminderLeadMinutes} min={0} max={10080} required onChange={event=>update('reminderLeadMinutes',Number(event.target.value))}/><Input label="Minimum time between overdue reminders (elapsed minutes)" type="number" value={config.reminderRepeatMinutes} min={15} max={43200} required onChange={event=>update('reminderRepeatMinutes',Number(event.target.value))}/><Input label="Maximum overdue reminders per target and recipient" type="number" value={config.maxOverdueReminders} min={1} max={20} required onChange={event=>update('maxOverdueReminders',Number(event.target.value))}/></div><Toggle label="Automatically escalate an overdue case to its saved escalation handler" value={config.autoEscalate} change={value=>update('autoEscalate',value)}/><Input label={'Escalation delay after deadline ('+(config.clockMode==='business'?'business':'elapsed')+' minutes)'} type="number" value={config.escalationDelayMinutes} min={0} max={43200} required onChange={event=>update('escalationDelayMinutes',Number(event.target.value))}/><Toggle label="Notify the requester when their case is automatically escalated" value={config.notifyRequesterOnEscalation} change={value=>update('notifyRequesterOnEscalation',value)}/><p className="text-sm text-muted-foreground">Business-hour rules send reminders and perform escalation during opening windows. Waiting for an employee continues to count towards the saved target. Confidential cases use their assigned responder or authorized confidential triage team.</p></div><Note label="Reason for this rule revision"/>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={mutation.isPending}>Save calendar & automation rules</Button>
  </form>;
}
function CalendarSummary({config}:{config:HelpdeskAutomationConfig}){return <div className="space-y-1 mt-3 text-sm"><p>{config.calendar.timezone}</p>{[...config.calendar.week].sort((a,b)=>a.day-b.day).map(day=><p key={day.day}>{weekdays[day.day]}: {day.windows.map(window=>window.start+'–'+window.end).join(', ')||'Closed'}</p>)}{config.calendar.holidays.map(holiday=><p key={holiday.date}>Closed {holiday.date}: {holiday.name}</p>)}</div>;}
export function CaseAutomationInfo({id}:{id:number}){
  const query=useQuery<{clockMode:string;timezone:string|null;calendar:HelpdeskAutomationConfig['calendar']|null;policyVersion:number|null;enabled:boolean;canEnroll:boolean;version:number;events:{id:number;kind:string;details:string;created_at:string}[]}>({queryKey:[`${base}/cases/${id}`]}),mutation=useSave();
  if(!query.data)return <QueryError error={query.error}/>;const detail=query.data;
  return <div className="space-y-3 border-t pt-3 text-sm"><p className="text-muted-foreground">{detail.clockMode==='business'?`Targets count saved opening hours in ${detail.timezone}.`:'Targets count elapsed hours, including weekends.'} Waiting for an employee continues to count. Reopening starts a new resolution target using the saved calendar.</p>{detail.calendar&&<details><summary className="cursor-pointer">Saved business calendar</summary><div className="mt-2 space-y-1">{[...detail.calendar.week].sort((a,b)=>a.day-b.day).map(day=><p key={day.day}>{weekdays[day.day]}: {day.windows.map(window=>window.start+'–'+window.end).join(', ')||'Closed'}</p>)}{detail.calendar.holidays.map(holiday=><p key={holiday.date}>Closed {holiday.date}: {holiday.name}</p>)}</div></details>}<p>Saved automation rule: {detail.policyVersion??'None'} · {detail.enabled?'Enrolled; subject to the global processing switch':'Not enabled for this case'}</p>{detail.events.length>0&&<details><summary className="cursor-pointer">Automatic processing history</summary><ol className="mt-3 space-y-3">{detail.events.map(event=><li key={event.id}><p className="text-muted-foreground">{stamp(event.created_at)}</p><p>{event.details}</p></li>)}</ol></details>}{detail.canEnroll&&<details><summary className="cursor-pointer">Apply current automation rules to this case</summary><form className="space-y-3 mt-3" onSubmit={event=>{event.preventDefault();mutation.mutate({url:`${base}/cases/${id}/enroll`,body:{version:detail.version,reason:text(new FormData(event.currentTarget),'reason')}});}}><p className="text-muted-foreground">Existing deadlines are retained. Future processing uses the current rules, and reminder counters restart for this case.</p><Note label="Reason for applying the current rules"/><Button variant="outline" disabled={mutation.isPending}>Apply current rules</Button></form></details>}</div>;
}
