import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Section,Field,Table,QueryError,fieldClass,useAction } from './Operations';
import { caseCategories,categoryLabels,type CaseDetail,type HelpdeskConfig } from '@shared/helpdesk';
type Category=typeof caseCategories[number];
type Article={id:number;title:string;body:string;category:Category;audience:'all'|'hr';status:'draft'|'published'|'archived';version:number;updatedAt:string};
type Policy={id:number;category:Category;confidential:boolean;employeeId:number|null;enabled:boolean;effectiveAt:string;firstResponseHours:number;resolutionHours:number;defaultAssigneeId:number|null;escalationAssigneeId:number|null;reason:string};
const localNow=()=>{const date=new Date();date.setMinutes(date.getMinutes()-date.getTimezoneOffset());return date.toISOString().slice(0,16);};
const stamp=(value:string|null)=>value?new Date(value).toLocaleString():'Not set';
function CategorySelect({value,onChange}:{value:Category;onChange:(v:Category)=>void}){return <Field label="Category"><select className={fieldClass} value={value} onChange={e=>onChange(e.target.value as Category)}>{caseCategories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select></Field>;}
export function HelpdeskResources({config}:{config:HelpdeskConfig}){
  const [panel,setPanel]=useState('');return <div className="space-y-4"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setPanel(panel==='knowledge'?'':'knowledge')}>Knowledge articles</Button>{config.canManagePolicies&&<Button variant="outline" onClick={()=>setPanel(panel==='rules'?'':'rules')}>Routing & response rules</Button>}</div>{panel==='knowledge'&&<Knowledge manage={config.canManagePolicies}/>} {panel==='rules'&&<Policies config={config}/>}</div>;
}
export function CaseTargets({detail}:{detail:CaseDetail}){
  const row=detail.case,[reason,setReason]=useState('');const mutation=useAction();const active=!['resolved','closed'].includes(row.status),now=Date.now();
  const responseLate=!row.firstRespondedAt&&row.firstResponseDueAt&&Date.parse(row.firstResponseDueAt)<now,resolutionLate=active&&row.resolutionDueAt&&Date.parse(row.resolutionDueAt)<now;
  return <Section title="Response targets"><dl className="space-y-3 text-sm"><div><dt className="font-medium">First response due</dt><dd>{stamp(row.firstResponseDueAt)} {responseLate&&active&&<span className="text-destructive">· Overdue</span>}</dd></div><div><dt className="font-medium">First public HR reply</dt><dd>{row.firstRespondedAt?stamp(row.firstRespondedAt):'Awaiting reply'}</dd></div><div><dt className="font-medium">Resolution due</dt><dd>{stamp(row.resolutionDueAt)} {resolutionLate&&<span className="text-destructive">· Overdue</span>}</dd></div>{row.resolvedAt&&<div><dt>Resolved</dt><dd>{stamp(row.resolvedAt)}</dd></div>}{row.escalatedAt&&<div><dt>Escalated</dt><dd>{stamp(row.escalatedAt)}</dd></div>}</dl><p className="text-xs text-muted-foreground">Targets use elapsed hours, including weekends and time waiting for an employee. Reopening starts a new resolution target from the original policy.</p>
    {detail.canEscalate&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`/api/helpdesk/cases/${row.id}/escalate`,body:{version:row.version,reason}});}}><Field label="Escalation reason"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000} required/></Field><Button disabled={mutation.isPending}>Escalate to configured handler</Button></form>}
  </Section>;
}
function Policies({config}:{config:HelpdeskConfig}){
  const [page,setPage]=useState(1),[template,setTemplate]=useState<Policy|undefined>();const query=useQuery<{items:{policy:Policy;employeeName:string|null}[];total:number}>({queryKey:['/api/helpdesk/policies',{page}]});
  return <Section title="Routing & response rules"><p className="text-sm text-muted-foreground">Rules apply to new cases from their effective date. Employee overrides take priority over company rules. Existing cases keep their saved deadlines and escalation handler.</p><PolicyForm key={template?.id||0} config={config} template={template}/><QueryError error={query.error}/><Table headers={['Category','Applies to','Effective','Targets','State','']} rows={(query.data?.items||[]).map(({policy:p,employeeName})=>[categoryLabels[p.category]+(p.confidential?' · Confidential':''),employeeName||'Company default',stamp(p.effectiveAt),`${p.firstResponseHours}h reply / ${p.resolutionHours}h resolution`,p.enabled?'Enabled':'Disabled',<Button variant="outline" onClick={()=>setTemplate(p)}>Create revision</Button>])}/><div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={!query.data||page*25>=query.data.total} onClick={()=>setPage(page+1)}>Next</Button></div></Section>;
}
function PolicyForm({config,template:p}:{config:HelpdeskConfig;template?:Policy}){
  const [category,setCategory]=useState<Category>(p?.category||'payroll'),[confidential,setConfidential]=useState(p?.confidential||false),[employee,setEmployee]=useState(p?.employeeId?String(p.employeeId):''),[enabled,setEnabled]=useState(p?.enabled??true),[effective,setEffective]=useState(localNow());
  const [reply,setReply]=useState(p?.firstResponseHours||24),[resolution,setResolution]=useState(p?.resolutionHours||72),[handler,setHandler]=useState(p?.defaultAssigneeId?String(p.defaultAssigneeId):''),[escalation,setEscalation]=useState(p?.escalationAssigneeId?String(p.escalationAssigneeId):''),[reason,setReason]=useState(''),[search,setSearch]=useState('');
  const people=useQuery<{employees:{id:number;name:string;employeeId:string}[];handlers:{id:number;name:string;role:string}[]}>({queryKey:['/api/helpdesk/policies/directory',{q:search}]});const mutation=useAction(()=>setReason(''));
  const restricted=confidential||category==='employee_relations',handlers=people.data?.handlers.filter(h=>!restricted||['super_admin','hr_director'].includes(h.role));
  return <details className="rounded border p-4" open={Boolean(p)||undefined}><summary className="cursor-pointer font-medium">{p?`New revision of rule #${p.id}`:'Add a routing rule'}</summary><form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({url:'/api/helpdesk/policies',body:{category,confidential:restricted,employeeId:employee?Number(employee):null,enabled,effectiveAt:new Date(effective).toISOString(),firstResponseHours:reply,resolutionHours:resolution,defaultAssigneeId:handler?Number(handler):null,escalationAssigneeId:escalation?Number(escalation):null,reason}});}}>
    <CategorySelect value={category} onChange={setCategory}/><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={restricted} disabled={!config.confidentialTriage||category==='employee_relations'} onChange={e=>{setConfidential(e.target.checked);setHandler('');setEscalation('');}}/>Confidential cases</label>{restricted&&!config.confidentialTriage&&<p role="alert" className="text-sm text-destructive">An HR director or system owner must configure confidential routing.</p>}
    <Field label="Find employee for an override"><input className={fieldClass} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search names or employee ID"/></Field><Field label="Applies to"><select className={fieldClass} value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">Company default</option>{employee&&!people.data?.employees.some(p=>String(p.id)===employee)&&<option value={employee}>Employee #{employee}</option>}{people.data?.employees.map(p=><option key={p.id} value={p.id}>{p.name} · {p.employeeId}</option>)}</select></Field>
    <div className="grid gap-3 sm:grid-cols-3"><Field label="Effective from (your local time)"><input className={fieldClass} type="datetime-local" required value={effective} onChange={e=>setEffective(e.target.value)}/></Field><Field label="First response, elapsed hours"><input className={fieldClass} type="number" min={1} max={8760} value={reply} required onChange={e=>setReply(Number(e.target.value))}/></Field><Field label="Resolution, elapsed hours"><input className={fieldClass} type="number" min={reply} max={8760} value={resolution} required onChange={e=>setResolution(Number(e.target.value))}/></Field></div>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Default handler"><select className={fieldClass} value={handler} onChange={e=>setHandler(e.target.value)}><option value="">Leave for triage</option>{handlers?.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></Field><Field label="Escalation handler"><select className={fieldClass} value={escalation} onChange={e=>setEscalation(e.target.value)}><option value="">Manual assignment only</option>{handlers?.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></Field></div>
    <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable routing and targets for matching new cases</label><p className="text-xs text-muted-foreground">A disabled employee override suppresses the company rule. Confidential automatic routing is limited to HR directors and system owners.</p><Field label="Reason for this rule revision"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} required minLength={5} maxLength={1000}/></Field><QueryError error={people.error}/><Button disabled={mutation.isPending||restricted&&!config.confidentialTriage}>Save rule revision</Button>
  </form></details>;
}
function Knowledge({manage}:{manage:boolean}){
  const [q,setQ]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<number|null>(null),[create,setCreate]=useState(false);
  const query=useQuery<{items:Article[];total:number}>({queryKey:['/api/helpdesk/articles',{q,category,page}]});
  return <Section title="Knowledge articles">{selected?<><Button variant="outline" onClick={()=>setSelected(null)}>Back to articles</Button><ArticleDetail key={selected} id={selected} manage={manage}/></>:<><div className="flex flex-wrap gap-3"><Field label="Search knowledge"><input className={fieldClass} value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Search titles and content"/></Field><Field label="Article category"><select className={fieldClass} value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option>{caseCategories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select></Field>{manage&&<Button variant="outline" onClick={()=>setCreate(!create)}>{create?'Close form':'Create article'}</Button>}</div>{create&&<ArticleForm done={()=>setCreate(false)}/>}<QueryError error={query.error}/><Table headers={['Article','Category','Visibility','']} rows={(query.data?.items||[]).map(a=>[a.title,categoryLabels[a.category],`${a.audience==='all'?'All employees':'HR only'} · ${a.status}`,<Button variant="outline" onClick={()=>setSelected(a.id)}>Read article</Button>])}/><div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={!query.data||page*20>=query.data.total} onClick={()=>setPage(page+1)}>Next</Button></div></>}</Section>;
}
function ArticleDetail({id,manage}:{id:number;manage:boolean}){
  const query=useQuery<{article:Article;history:{id:number;version:number;reason:string;createdAt:string;snapshot:Article}[]}>({queryKey:[`/api/helpdesk/articles/${id}`]});const [edit,setEdit]=useState(false);
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading article…</p>}</>;
  const a=query.data.article;return <article className="space-y-4"><h3 className="text-xl font-semibold">{a.title}</h3><p className="text-xs text-muted-foreground">{categoryLabels[a.category]} · Updated {stamp(a.updatedAt)} · Version {a.version}</p><div className="whitespace-pre-wrap break-words leading-relaxed text-sm">{a.body}</div>{manage&&<><Button variant="outline" onClick={()=>setEdit(!edit)}>Edit / publish / archive</Button>{edit&&<ArticleForm key={a.version} article={a} done={()=>setEdit(false)}/>}<details><summary className="cursor-pointer text-sm font-medium">Version history</summary><div className="space-y-3 mt-3">{query.data.history.map(h=><details key={h.id} className="rounded border p-3"><summary className="cursor-pointer text-sm">Version {h.version} · {stamp(h.createdAt)} · {h.reason}</summary><h4 className="font-medium mt-3">{h.snapshot.title}</h4><p className="whitespace-pre-wrap text-sm mt-2">{h.snapshot.body}</p></details>)}</div></details></>}</article>;
}
function ArticleForm({article:a,done}:{article?:Article;done:()=>void}){
  const [title,setTitle]=useState(a?.title||''),[body,setBody]=useState(a?.body||''),[category,setCategory]=useState<Category>(a?.category||'other'),[audience,setAudience]=useState(a?.audience||'all'),[status,setStatus]=useState(a?.status||'draft'),[reason,setReason]=useState('');const mutation=useAction(done);
  return <form className="rounded border p-4 space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:a?`/api/helpdesk/articles/${a.id}`:'/api/helpdesk/articles',method:a?'PATCH':'POST',body:{title,body,category,audience,status,...(a?{version:a.version,reason}:{})}});}}><Field label="Article title"><input className={fieldClass} value={title} minLength={4} maxLength={200} required onChange={e=>setTitle(e.target.value)}/></Field><CategorySelect value={category} onChange={setCategory}/><Field label="Article content"><textarea className={fieldClass} rows={10} value={body} minLength={10} maxLength={30000} required onChange={e=>setBody(e.target.value)}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Audience"><select className={fieldClass} value={audience} onChange={e=>setAudience(e.target.value as typeof audience)}><option value="all">All employees</option><option value="hr">HR responders only</option></select></Field><Field label="Publication status"><select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Field></div><p className="text-xs text-muted-foreground">Only published articles appear to readers. Saving as draft or archived removes the article from their knowledge search.</p>{a&&<Field label="Revision reason"><textarea className={fieldClass} value={reason} minLength={5} maxLength={1000} required onChange={e=>setReason(e.target.value)}/></Field>}<Button disabled={mutation.isPending}>Save article</Button></form>;
}
