import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, fieldClass, useAction, QueryError } from './Operations';
export default function Interviews({ applications }: {
    applications: any[];
}) {
    const data = useQuery<any>({ queryKey: ['/api/hiring/interviews'] });
    const [appId, setApp] = useState(''), [owner, setOwner] = useState(''), [date, setDate] = useState(''), [type, setType] = useState('video'), [round, setRound] = useState('first'), [note, setNote] = useState(''), [result, setResult] = useState<any>(null);
    const action = useAction(() => { setResult(null); setNote(''); setDate(''); });
    const selected = applications.find(a => a.application.id === Number(appId));
    return <Section title="Interviews"><QueryError error={data.error}/>{data.data?.canManage && <details><summary className="cursor-pointer">Schedule interview</summary><form className="mt-4 space-y-3" onSubmit={e => { e.preventDefault(); if (!selected)
        return; action.mutate({ url: '/api/hiring/interviews', body: { applicationId: selected.application.id, version: selected.application.version, interviewerId: Number(owner), interviewDate: new Date(date).toISOString(), interviewType: type, interviewRound: round, reason: note } }); }}><div className="grid gap-3 md:grid-cols-3"><Field label="Shortlisted candidate"><select className={fieldClass} required value={appId} onChange={e => setApp(e.target.value)}><option value="">Select candidate</option>{applications.filter(a => ['shortlisted', 'interview'].includes(a.application.status)).map(a => <option key={a.application.id} value={a.application.id}>{a.candidate.fullNameEn} · {a.jobTitle}</option>)}</select></Field><Field label="Interviewer"><select className={fieldClass} required value={owner} onChange={e => setOwner(e.target.value)}><option value="">Select interviewer</option>{data.data.interviewers.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label={`Interview time (${Intl.DateTimeFormat().resolvedOptions().timeZone})`}><input className={fieldClass} required type="datetime-local" value={date} onChange={e => setDate(e.target.value)}/></Field><Field label="Format"><select className={fieldClass} value={type} onChange={e => setType(e.target.value)}>{['phone', 'video', 'in-person'].map(v => <option key={v}>{v}</option>)}</select></Field><Field label="Round"><select className={fieldClass} value={round} onChange={e => setRound(e.target.value)}>{['first', 'second', 'final', 'technical', 'hr'].map(v => <option key={v}>{v}</option>)}</select></Field></div><Field label="Meeting details and scheduling note"><textarea className={fieldClass} required minLength={5} value={note} onChange={e => setNote(e.target.value)}/></Field><Button disabled={action.isPending || !selected}>Schedule interview</Button></form></details>}
 <Table headers={['Candidate / job', 'Interviewer', 'Time / round', 'Status', 'Feedback', 'Action']} rows={(data.data?.rows || []).map((r: any) => [r.candidate + ' · ' + r.jobTitle, r.interviewer, new Date(r.interview.interviewDate).toLocaleString() + ' · ' + r.interview.interviewRound, r.interview.status, r.interview.feedback || '—', data.data.canManage && r.interview.status === 'scheduled' ? <Button variant="outline" onClick={() => setResult({ id: r.interview.id, version: r.interview.version, status: 'completed', rating: 3, recommendation: 'hold', feedback: '' })}>Record result</Button> : null])}/>
 {result && <form className="space-y-3 border rounded p-4" onSubmit={e => { e.preventDefault(); const { id, ...body } = result; action.mutate({ url: `/api/hiring/interviews/${id}/result`, body }); }}><div className="grid gap-3 md:grid-cols-3"><Field label="Interview outcome"><select className={fieldClass} value={result.status} onChange={e => setResult({ ...result, status: e.target.value })}>{['completed', 'cancelled', 'no-show'].map(v => <option key={v}>{v}</option>)}</select></Field>{result.status === 'completed' && <><Field label="Rating (1–5)"><input className={fieldClass} required type="number" min={1} max={5} value={result.rating} onChange={e => setResult({ ...result, rating: Number(e.target.value) })}/></Field><Field label="Recommendation"><select className={fieldClass} value={result.recommendation} onChange={e => setResult({ ...result, recommendation: e.target.value })}>{['hire', 'reject', 'hold'].map(v => <option key={v}>{v}</option>)}</select></Field></>}</div><Field label="Interview feedback or cancellation reason"><textarea className={fieldClass} required minLength={5} value={result.feedback} onChange={e => setResult({ ...result, feedback: e.target.value })}/></Field><Button disabled={action.isPending}>Save result</Button> <Button type="button" variant="outline" onClick={() => setResult(null)}>Close</Button></form>}</Section>;
}
