import { useState } from 'react';
import { Eye, Plus, Search, Trash2, UserPlus, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Field, fieldClass } from './Operations';
import { OrgChartCanvas, initials } from './OrgChartCanvas';
import { orgChartInput, type ChartPerson, type OrgNode, type OrgPerson } from '@shared/org-chart';

export type ChartDraft={version:number;effectiveFrom:string;effectiveTo:string;nodes:OrgNode[];reason:string};
export function OrgChartEditor({initial,people,savedPeople,pending,error,onSave,onCancel}:{initial:ChartDraft;people:OrgPerson[];savedPeople:ChartPerson[];pending:boolean;error:string;onSave:(draft:ChartDraft)=>void;onCancel:()=>void}) {
  const [draft,setDraft]=useState(initial),[search,setSearch]=useState(''),[personId,setPersonId]=useState(''),[managerId,setManagerId]=useState(''),[preview,setPreview]=useState(false),[validation,setValidation]=useState('');
  const directory=new Map<number,Pick<OrgPerson,'name'|'position'|'department'>>([...savedPeople.map(p=>[p.employeeId,p] as const),...people.map(p=>[p.id,p] as const)]);
  const activeIds=new Set(people.map(p=>p.id));
  const label=(id:number)=>directory.get(id)?.name||`Employee #${id}`;
  const inactive=draft.nodes.filter(n=>!activeIds.has(n.employeeId));
  function setNode(id:number,patch:Partial<OrgNode>){setDraft(d=>({...d,nodes:d.nodes.map(n=>n.employeeId===id?{...n,...patch}:n)}));setValidation('');}
  function descendants(id:number){const result=new Set<number>([id]);let changed=true;while(changed){changed=false;draft.nodes.forEach(n=>{if(n.parentEmployeeId!==null&&result.has(n.parentEmployeeId)&&!result.has(n.employeeId)){result.add(n.employeeId);changed=true;}});}return result;}
  const available=people.filter(p=>!draft.nodes.some(n=>n.employeeId===p.id)&&`${p.name} ${p.position} ${p.department}`.toLowerCase().includes(search.toLowerCase()));
  const previewNodes=draft.nodes.map(n=>({...n,name:label(n.employeeId),position:directory.get(n.employeeId)?.position||'',department:directory.get(n.employeeId)?.department||''}));
  return <div className="space-y-5"><form className="overflow-hidden rounded-2xl border border-primary/30 bg-card" onSubmit={e=>{e.preventDefault();const parsed=orgChartInput.safeParse({...draft,effectiveTo:draft.effectiveTo||null});if(!parsed.success){setValidation(parsed.error.issues[0].message);return;}if(inactive.length){setValidation('Remove inactive employees before saving this revision.');return;}setValidation('');onSave(draft);}}>
    <div className="flex flex-wrap items-center justify-between gap-3 border-b bg-primary/5 p-5"><div><h2 className="font-semibold">Edit team hierarchy</h2><p className="mt-1 text-sm text-muted-foreground">Add people, choose their team roles, and connect reporting lines.</p></div><Button type="button" variant="outline" onClick={()=>setPreview(!preview)} aria-pressed={preview}><Eye className="mr-2 h-4 w-4"/>{preview?'Hide preview':'Live preview'}</Button></div>
    <fieldset disabled={pending} className="space-y-6 p-5">
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Effective from"><Input type="date" required value={draft.effectiveFrom} onChange={e=>setDraft({...draft,effectiveFrom:e.target.value})}/></Field><Field label="Effective through (optional)"><Input type="date" min={draft.effectiveFrom} value={draft.effectiveTo} onChange={e=>setDraft({...draft,effectiveTo:e.target.value})}/></Field></div>
      <section className="space-y-3 rounded-xl bg-muted/30 p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><UserPlus className="h-4 w-4"/>Add someone to this chart</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="Find employee"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>{setSearch(e.target.value);setPersonId('');}} placeholder="Search name, position or department"/></div></Field><Field label="Employee"><select className={fieldClass} value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">{available.length?'Choose an employee':'No employees match'}</option>{available.map(p=><option key={p.id} value={p.id}>{p.name} · {p.position}</option>)}</select></Field><Field label="Reports to"><select className={fieldClass} value={managerId} onChange={e=>setManagerId(e.target.value)}><option value="">Top level / team head</option>{draft.nodes.map(n=><option key={n.employeeId} value={n.employeeId}>{label(n.employeeId)} · {n.role}</option>)}</select></Field><Button type="button" className="self-end" variant="outline" disabled={!personId||draft.nodes.length>=500} onClick={()=>{const p=people.find(p=>p.id===Number(personId));if(!p)return;setDraft({...draft,nodes:[...draft.nodes,{employeeId:p.id,parentEmployeeId:managerId?Number(managerId):null,role:p.position||''}]});setPersonId('');setSearch('');setValidation('');}}><Plus className="mr-2 h-4 w-4"/>Add to chart</Button></div></section>
      {inactive.length>0&&<p role="alert" className="rounded-lg bg-destructive/5 p-3 text-sm text-destructive">Inactive or unavailable employees: {inactive.map(n=>label(n.employeeId)).join(', ')}. Remove them from this revision before saving.</p>}
      <div><div className="mb-3 flex flex-wrap justify-between gap-2"><h3 className="text-sm font-semibold">Reporting lines · {draft.nodes.length} people</h3><span className="text-xs text-muted-foreground">Subordinates are excluded from their manager’s reporting choices.</span></div>{draft.nodes.length?<div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/50"><tr>{['Person','Role in this team','Reports to',''].map((h,i)=><th key={i} scope="col" className="p-3 text-xs font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody className="divide-y">{draft.nodes.map(n=>{const blocked=descendants(n.employeeId);return <tr key={n.employeeId}><td className="min-w-44 p-3"><div className="flex items-center gap-2"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-xs font-medium text-primary">{initials(label(n.employeeId))}</span><span className="font-medium">{label(n.employeeId)}</span></div></td><td className="min-w-44 p-3"><Input aria-label={`Team role for ${label(n.employeeId)}`} required maxLength={100} value={n.role} onChange={e=>setNode(n.employeeId,{role:e.target.value})}/></td><td className="min-w-52 p-3"><select className={fieldClass} aria-label={`Reporting manager for ${label(n.employeeId)}`} value={n.parentEmployeeId??''} onChange={e=>setNode(n.employeeId,{parentEmployeeId:e.target.value?Number(e.target.value):null})}><option value="">Top level / team head</option>{draft.nodes.filter(p=>!blocked.has(p.employeeId)).map(p=><option key={p.employeeId} value={p.employeeId}>{label(p.employeeId)} · {p.role}</option>)}</select></td><td className="p-3"><Button type="button" size="icon" variant="ghost" aria-label={`Remove ${label(n.employeeId)} from chart`} onClick={()=>{setDraft({...draft,nodes:draft.nodes.filter(p=>p.employeeId!==n.employeeId).map(p=>p.parentEmployeeId===n.employeeId?{...p,parentEmployeeId:n.parentEmployeeId}:p)});if(managerId===String(n.employeeId))setManagerId(n.parentEmployeeId?String(n.parentEmployeeId):'');}}><Trash2 className="h-4 w-4 text-destructive"/></Button></td></tr>;})}</tbody></table></div>:<div className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">Add the team head first, then add their team members.</div>}<p className="mt-3 text-xs text-muted-foreground">Removing a manager moves their direct reports to that manager’s parent. Review the reporting lines before saving.</p></div>
      <Field label="Reason for revision"><textarea className={fieldClass} required minLength={5} maxLength={2000} rows={3} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})} placeholder="Describe the staffing or reporting change"/></Field>
      <p className="text-xs text-muted-foreground">Saving creates a dated revision. The latest saved revision applies where dates overlap. Chart positions do not assign roster membership, leave approval or account access.</p>
      {(validation||error)&&<p role="alert" className="text-sm text-destructive">{validation||error}</p>}
      <div className="flex flex-wrap gap-3"><Button type="submit"><Save className="mr-2 h-4 w-4"/>{pending?'Saving…':'Save hierarchy revision'}</Button><Button type="button" variant="outline" onClick={onCancel}>Cancel changes</Button></div>
    </fieldset>
  </form>{preview&&<OrgChartCanvas nodes={previewNodes} preview/>}</div>;
}
