import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { ChevronDown, ChevronRight, Focus, GitBranch, List, Network, Search, Users, ZoomIn, ZoomOut, ArrowUpRight, Building2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import type { ChartPerson } from '@shared/org-chart';
import './OrgChartCanvas.css';

export const initials=(name:string)=>name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(n=>n[0]).join('').toUpperCase();
export function chartStructure(nodes:ChartPerson[]) {
  const byId=new Map(nodes.map(n=>[n.employeeId,n])),children=new Map<number,ChartPerson[]>();
  const roots=nodes.filter(n=>n.parentEmployeeId===null||!byId.has(n.parentEmployeeId));
  nodes.forEach(n=>{if(n.parentEmployeeId!==null&&byId.has(n.parentEmployeeId))children.set(n.parentEmployeeId,[...(children.get(n.parentEmployeeId)||[]),n]);});
  const reached=new Set<number>();let levels=0;
  function visit(id:number,depth:number){if(reached.has(id))return;reached.add(id);levels=Math.max(levels,depth);(children.get(id)||[]).forEach(c=>visit(c.employeeId,depth+1));}
  roots.forEach(n=>visit(n.employeeId,1));
  return {byId,children,roots,levels,disconnected:nodes.filter(n=>!reached.has(n.employeeId))};
}
export function OrgChartCanvas({nodes,preview=false}:{nodes:ChartPerson[];preview?:boolean}) {
  const [search,setSearch]=useState(''),[mode,setMode]=useState('chart'),[collapsed,setCollapsed]=useState<Set<number>>(new Set()),[selected,setSelected]=useState<number|null>(null),[focus,setFocus]=useState<number|null>(null),[zoom,setZoom]=useState(1);
  const viewport=useRef<HTMLDivElement>(null),drawing=useRef<HTMLDivElement>(null);
  const graph=useMemo(()=>chartStructure(nodes),[nodes]);
  const query=search.trim().toLowerCase();
  const subtree=new Set<number>();
  function collect(id:number){if(subtree.has(id))return;subtree.add(id);(graph.children.get(id)||[]).forEach(n=>collect(n.employeeId));}
  if(focus!==null&&graph.byId.has(focus))collect(focus);else nodes.forEach(n=>subtree.add(n.employeeId));
  const matches=nodes.filter(n=>subtree.has(n.employeeId)&&(!query||`${n.name} ${n.role} ${n.position} ${n.department}`.toLowerCase().includes(query)));
  const matchIds=new Set(matches.map(n=>n.employeeId)),visible=new Set<number>();
  matches.forEach(n=>{let current:ChartPerson|undefined=n;const seen=new Set<number>();while(current&&!seen.has(current.employeeId)&&subtree.has(current.employeeId)){seen.add(current.employeeId);visible.add(current.employeeId);current=current.parentEmployeeId===null?undefined:graph.byId.get(current.parentEmployeeId);}});
  const roots=focus!==null&&graph.byId.has(focus)?[graph.byId.get(focus)!]:graph.roots;
  const person=selected===null?undefined:graph.byId.get(selected);
  const manager=person?.parentEmployeeId?graph.byId.get(person.parentEmployeeId):undefined;
  const reports=person?graph.children.get(person.employeeId)||[]:[];
  function fit(){if(viewport.current&&drawing.current){setZoom(Math.max(.25,Math.min(1,(viewport.current.clientWidth-48)/drawing.current.scrollWidth)));viewport.current.scrollTo({left:0,top:0});}}
  useEffect(()=>{if(selected!==null&&!graph.byId.has(selected))setSelected(null);if(focus!==null&&!graph.byId.has(focus))setFocus(null);},[graph,selected,focus]);
  function branch(node:ChartPerson,path:number[]=[]) : ReactNode {
    if(path.includes(node.employeeId)||path.length>=20||!visible.has(node.employeeId))return null;
    const children=graph.children.get(node.employeeId)||[],shown=children.filter(c=>visible.has(c.employeeId));
    const closed=!query&&collapsed.has(node.employeeId),head=node.parentEmployeeId===null||node.employeeId===focus||!graph.byId.has(node.parentEmployeeId);
    return <li key={node.employeeId}><article className={`w-60 overflow-hidden rounded-2xl border bg-card text-left shadow-sm transition-shadow hover:shadow-md ${query&&matchIds.has(node.employeeId)?'ring-2 ring-primary':head?'border-primary/40':''}`}>
      <div className={`h-1.5 ${head?'bg-primary':children.length?'bg-violet-400':'bg-slate-300 dark:bg-slate-600'}`}/>
      <button type="button" className="w-full p-4 text-left focus-visible:outline-primary" onClick={()=>setSelected(node.employeeId)} aria-label={`View ${node.name}, ${node.role}`}><div className="flex items-start gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-sm font-semibold ${head?'bg-primary/10 text-primary':'bg-muted text-muted-foreground'}`}>{initials(node.name)}</span><div className="min-w-0"><h3 className="break-words text-sm font-semibold leading-5">{node.name}</h3><p className="mt-1 break-words text-xs font-medium text-primary">{node.role}</p></div></div><p className="mt-3 truncate text-xs text-muted-foreground" title={node.department}>{node.department||'Department not set'}</p></button>
      {children.length>0?<button type="button" disabled={!!query} aria-expanded={!closed} className="flex w-full items-center justify-between gap-2 border-t bg-muted/30 px-4 py-2.5 text-xs font-medium hover:bg-muted/60 disabled:opacity-70" onClick={()=>setCollapsed(current=>{const next=new Set(current);next.has(node.employeeId)?next.delete(node.employeeId):next.add(node.employeeId);return next;})}><span className="flex items-center gap-1.5"><Users className="h-3.5 w-3.5"/>{children.length} direct reports</span>{closed?<ChevronRight className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>:<div className="border-t px-4 py-2.5 text-xs text-muted-foreground">Individual contributor</div>}
    </article>{!closed&&shown.length>0&&<ul>{shown.map(c=>branch(c,[...path,node.employeeId]))}</ul>}</li>;
  }
  return <section className="overflow-hidden rounded-2xl border bg-card">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="relative min-w-52 flex-1 sm:max-w-sm"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Find a person, role or department" className="pl-9" placeholder="Find a person, role or department" value={search} onChange={e=>setSearch(e.target.value)} maxLength={100}/></div><div className="flex flex-wrap items-center gap-2"><div className="flex rounded-lg border p-1"><Button size="sm" variant={mode==='chart'?'secondary':'ghost'} aria-pressed={mode==='chart'} onClick={()=>setMode('chart')}><Network className="mr-2 h-4 w-4"/>Chart</Button><Button size="sm" variant={mode==='list'?'secondary':'ghost'} aria-pressed={mode==='list'} onClick={()=>setMode('list')}><List className="mr-2 h-4 w-4"/>List</Button></div>{preview&&<Badge variant="outline">Unsaved preview</Badge>}</div></div>
    <div className="flex flex-wrap items-center justify-between gap-3 border-b bg-muted/20 px-4 py-3"><div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">{query?<><span>{matches.length} matching people · reporting paths included</span><Button size="sm" variant="ghost" onClick={()=>setSearch('')}>Clear search</Button></>:<span>Select a person to view their manager and direct reports.</span>}{focus!==null&&<Button size="sm" variant="outline" onClick={()=>{setFocus(null);setSearch('');}}>Show full chart</Button>}</div>{mode==='chart'&&<div className="flex flex-wrap items-center gap-1"><Button size="sm" variant="ghost" disabled={!!query} onClick={()=>setCollapsed(new Set())}>Expand all</Button><Button size="sm" variant="ghost" disabled={!!query} onClick={()=>setCollapsed(new Set(nodes.filter(n=>graph.children.has(n.employeeId)).map(n=>n.employeeId)))}>Collapse all</Button><Button size="icon" variant="ghost" aria-label="Zoom out" disabled={zoom<=.25} onClick={()=>setZoom(z=>Math.max(.25,z-.15))}><ZoomOut className="h-4 w-4"/></Button><span className="w-10 text-center text-xs tabular-nums">{Math.round(zoom*100)}%</span><Button size="icon" variant="ghost" aria-label="Zoom in" disabled={zoom>=1.6} onClick={()=>setZoom(z=>Math.min(1.6,z+.15))}><ZoomIn className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={fit}><Focus className="mr-1.5 h-4 w-4"/>Fit</Button><Button size="sm" variant="ghost" onClick={()=>setZoom(1)}>100%</Button></div>}</div>
    {query&&!matches.length?<div className="p-12 text-center"><Search className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><h3 className="font-medium">No matching people</h3><p className="mt-2 text-sm text-muted-foreground">Try another name, role or department.</p></div>:mode==='chart'?<div ref={viewport} tabIndex={0} aria-label="Scrollable organization chart" className="org-canvas max-h-[680px] min-h-80 overflow-auto p-6 sm:p-10"><div style={{zoom}} className="mx-auto w-max min-w-min"><div ref={drawing} className="w-max"><ul className="org-tree" aria-label="Organization hierarchy">{roots.map(n=>branch(n))}</ul></div></div></div>:<div className="max-h-[680px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-muted"><tr>{['Person','Role / department','Reports to','Direct reports'].map(h=><th key={h} scope="col" className="p-4 text-xs font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody className="divide-y">{matches.map(n=><tr key={n.employeeId} className="hover:bg-muted/30"><td className="p-4"><button type="button" className="flex items-center gap-3 text-left font-medium text-primary hover:underline" onClick={()=>setSelected(n.employeeId)}><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs">{initials(n.name)}</span>{n.name}</button></td><td className="p-4"><p>{n.role}</p><p className="mt-1 text-xs text-muted-foreground">{n.department}</p></td><td className="p-4">{graph.byId.get(n.parentEmployeeId!)?.name||(n.parentEmployeeId?'Manager outside this view':'Top level')}</td><td className="p-4 tabular-nums">{graph.children.get(n.employeeId)?.length||0}</td></tr>)}</tbody></table></div>}
    {graph.disconnected.length>0&&<div role="alert" className="border-t bg-destructive/5 p-4 text-sm text-destructive">Reporting loops need attention: {graph.disconnected.map(n=>n.name).join(', ')}. These people remain available in List view.</div>}
    <div className="flex flex-wrap items-center gap-4 border-t px-4 py-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-primary"/>Top level</span><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-violet-400"/>Manages people</span><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-slate-400"/>Individual contributor</span><span className="ml-auto">{nodes.length} people in this chart</span></div>
    <Sheet open={!!person} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="overflow-y-auto sm:max-w-md"><SheetHeader><div className="mb-3 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 text-xl font-semibold text-primary">{person&&initials(person.name)}</div><SheetTitle>{person?.name}</SheetTitle><SheetDescription>{person?.role}</SheetDescription></SheetHeader>{person&&<div className="mt-6 space-y-6"><div className="rounded-xl bg-muted/40 p-4 text-sm"><p className="flex items-center gap-2 font-medium"><Building2 className="h-4 w-4"/>{person.department||'Department not set'}</p>{person.position&&person.position!==person.role&&<p className="mt-2 text-muted-foreground">Company position: {person.position}</p>}</div><div><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Reports to</h3>{manager?<button type="button" className="flex w-full items-center justify-between rounded-xl border p-3 text-left hover:bg-muted/40" onClick={()=>setSelected(manager.employeeId)}><span><span className="block text-sm font-medium">{manager.name}</span><span className="text-xs text-muted-foreground">{manager.role}</span></span><ArrowUpRight className="h-4 w-4"/></button>:<p className="text-sm">{person.parentEmployeeId?'Manager outside this view':'Top-level position in this chart'}</p>}</div><div><h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Direct reports · {reports.length}</h3>{reports.length?<div className="divide-y rounded-xl border">{reports.map(n=><button type="button" key={n.employeeId} className="flex w-full items-center gap-3 p-3 text-left hover:bg-muted/40" onClick={()=>setSelected(n.employeeId)}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-muted text-xs font-medium">{initials(n.name)}</span><span><span className="block text-sm font-medium">{n.name}</span><span className="text-xs text-muted-foreground">{n.role}</span></span></button>)}</div>:<p className="text-sm text-muted-foreground">No direct reports in this chart.</p>}</div>{reports.length>0&&<Button className="w-full" onClick={()=>{setFocus(person.employeeId);setSearch('');setCollapsed(new Set());setSelected(null);setZoom(1);}}><GitBranch className="mr-2 h-4 w-4"/>Focus on this team</Button>}</div>}</SheetContent></Sheet>
  </section>;
}
