import EarlierPerformanceRecords from '../performance/PerformanceOverview';
import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, QueryError, fieldClass, useAction } from './Operations';
import type { Rubric, Scores } from '@shared/performance-cycles';
import { BulkParticipants, ParticipationControls } from './PerformanceParticipants';

type Cycle={id:number;name:string;periodStart:string;periodEnd:string;dueDate:string;selfRequired:boolean;rubric:Rubric;ratingLabels:string[];status:string;version:number};
type Review={id:number;employeeId:number;employeeName:string;reviewerName:string;reviewerId:number;dueDate:string;selfRequired:boolean;status:string;participationStatus:'active'|'withdrawn';version:number;selfScores:Scores|null;selfSummary:string|null;managerScores:Scores|null;managerSummary:string|null;finalScores:Scores|null;finalSummary:string|null;finalRating:string|null;publishedAt:string|null;acknowledgedAt:string|null};
type Objective={id:number;kind:string;title:string;measure:string;dueDate:string;progress:number;status:string;version:number};
type ReviewDetail={cycle:Cycle;review:Review;participation:{status:'active'|'withdrawn';reason:string|null};employee:{id:number;name:string};objectives:Objective[];history:{id:number;action:string;reason:string|null;actorName:string;createdAt:string}[];access:{own:boolean;reviewer:boolean;calibrate:boolean;manage:boolean;editObjectives:boolean;manageParticipation:boolean}};
const endpoint='/api/review-cycles';
const title=(s:string)=>s.replaceAll('_',' ');
export default function PerformanceCycles({embedded=false}:{embedded?:boolean}={}){
  const [cycleId,setCycleId]=useState<number|null>(null),[reviewId,setReviewId]=useState<number|null>(null),[earlier,setEarlier]=useState(false),[create,setCreate]=useState(false),[page,setPage]=useState(1);
  const config=useQuery<{canManage:boolean;userId:number}>({queryKey:[endpoint+'/config']});
  const list=useQuery<{items:Cycle[];total:number}>({queryKey:[endpoint,{page}],enabled:!cycleId});
  return <div className="space-y-6">{!embedded&&<div><h1 className="text-3xl font-bold">Performance & development</h1><p className="mt-2 text-muted-foreground">Set objectives, reflect on progress and complete a structured review together.</p></div>}<QueryError error={config.error}/>
    {reviewId?<><Button variant="outline" onClick={()=>setReviewId(null)}>Back to cycle</Button><ReviewPanel key={reviewId} id={reviewId}/></>:cycleId?<><Button variant="outline" onClick={()=>setCycleId(null)}>All review cycles</Button><CyclePanel id={cycleId} manage={Boolean(config.data?.canManage)} openReview={setReviewId}/></>:<>
      {config.data?.canManage&&<Button onClick={()=>setCreate(!create)}>{create?'Close form':'Create review cycle'}</Button>}
      {create&&<CycleForm done={()=>setCreate(false)}/>}
      <Section title="Review cycles"><QueryError error={list.error}/>{list.isLoading?<p>Loading cycles…</p>:<Table headers={['Cycle','Review period','Deadline','Status','']} rows={(list.data?.items||[]).map(c=>[c.name,`${c.periodStart} to ${c.periodEnd}`,c.dueDate,title(c.status),<Button variant="outline" onClick={()=>setCycleId(c.id)}>Open cycle</Button>])}/>}
        {list.data&&<div className="flex gap-3 items-center"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>{list.data.total} cycles · Page {page}</span><Button variant="outline" disabled={page*20>=list.data.total} onClick={()=>setPage(page+1)}>Next</Button></div>}
      </Section><p className="text-sm text-muted-foreground">Ratings support a review conversation. They do not automatically change pay or employment status.</p>{config.data?.canManage&&<><Button variant="outline" onClick={()=>setEarlier(!earlier)}>Earlier reviews, goals & feedback</Button>{earlier&&<EarlierPerformanceRecords/>}</>}
    </>}
  </div>;
}
function CycleForm({cycle,done}:{cycle?:Cycle;done:()=>void}){
  const [name,setName]=useState(cycle?.name||''),[start,setStart]=useState(cycle?.periodStart||''),[end,setEnd]=useState(cycle?.periodEnd||''),[due,setDue]=useState(cycle?.dueDate||''),[self,setSelf]=useState(cycle?.selfRequired??true);
  const [rubric,setRubric]=useState<Rubric>(cycle?.rubric||[{key:'results',label:'Results and objectives',weight:50},{key:'development',label:'Skills and collaboration',weight:50}]);
  const [labels,setLabels]=useState(cycle?.ratingLabels||['Needs significant support','Developing','Meets expectations','Exceeds expectations','Exceptional']);const mutation=useAction(done);
  function save(e:FormEvent){e.preventDefault();const data={name,periodStart:start,periodEnd:end,dueDate:due,selfRequired:self,rubric,ratingLabels:labels};mutation.mutate({url:cycle?endpoint+'/'+cycle.id:endpoint,method:cycle?'PATCH':'POST',body:cycle?{version:cycle.version,cycle:data}:data});}
  return <Section title={cycle?'Edit draft cycle':'New review cycle'}><form className="space-y-4" onSubmit={save}><Field label="Cycle name"><input className={fieldClass} value={name} onChange={e=>setName(e.target.value)} maxLength={160} required/></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Period start"><input type="date" className={fieldClass} value={start} onChange={e=>setStart(e.target.value)} required/></Field><Field label="Period end"><input type="date" className={fieldClass} value={end} onChange={e=>setEnd(e.target.value)} min={start} required/></Field><Field label="Default employee deadline"><input type="date" className={fieldClass} value={due} onChange={e=>setDue(e.target.value)} min={end} required/></Field></div>
    <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={self} onChange={e=>setSelf(e.target.checked)}/>Require self-assessment by default</label><p className="text-sm text-muted-foreground">Employee deadlines and self-assessment requirements can differ. Criteria and rating labels are fixed when the cycle opens.</p>
    <h3 className="font-medium">Assessment criteria · weights total {rubric.reduce((n,r)=>n+r.weight,0)}%</h3>{rubric.map((r,i)=><div key={r.key} className="grid gap-3 sm:grid-cols-[1fr_110px_auto]"><Field label={`Criterion ${i+1}`}><input className={fieldClass} value={r.label} onChange={e=>setRubric(rubric.map((x,j)=>i===j?{...x,label:e.target.value}:x))} maxLength={120} required/></Field><Field label="Weight %"><input type="number" min={1} max={100} className={fieldClass} value={r.weight} onChange={e=>setRubric(rubric.map((x,j)=>i===j?{...x,weight:Number(e.target.value)}:x))} required/></Field><Button type="button" variant="outline" disabled={rubric.length===1} onClick={()=>setRubric(rubric.filter((_,j)=>i!==j))}>Remove</Button></div>)}<Button type="button" variant="outline" disabled={rubric.length>=12} onClick={()=>setRubric([...rubric,{key:'criterion_'+Date.now(),label:'',weight:1}])}>Add criterion</Button>
    <div className="grid gap-3 sm:grid-cols-2">{labels.map((label,i)=><Field key={i} label={`Rating ${i+1} label`}><input className={fieldClass} value={label} maxLength={80} required onChange={e=>setLabels(labels.map((v,j)=>j===i?e.target.value:v))}/></Field>)}</div><Button disabled={mutation.isPending||rubric.reduce((n,r)=>n+r.weight,0)!==100} type="submit">Save cycle</Button>
  </form></Section>;
}
function PersonSelect({kind,value,onChange}:{kind:'employees'|'reviewers';value:string;onChange:(value:string)=>void}){
  const [search,setSearch]=useState('');const query=useQuery<{employees:{id:number;name:string;employeeId:string}[];reviewers:{id:number;name:string;role:string}[]}>({queryKey:[endpoint+'/directory',{q:search}]});
  return <div className="space-y-2"><Field label={kind==='employees'?'Find employee':'Find reviewer'}><input className={fieldClass} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name"/></Field><Field label={kind==='employees'?'Employee':'Reviewer'}><select className={fieldClass} value={value} onChange={e=>onChange(e.target.value)} required><option value="">Choose…</option>{query.data?.[kind].map(p=><option value={p.id} key={p.id}>{p.name} · #{p.id}</option>)}</select></Field><QueryError error={query.error}/></div>;
}
function CyclePanel({id,manage,openReview}:{id:number;manage:boolean;openReview:(id:number)=>void}){
  const query=useQuery<{cycle:Cycle;reviews:Review[];report:{total:number;withdrawn:number;published:number;acknowledged:number;averageRating:number|null;sampleCount:number}}>({queryKey:[endpoint+'/'+id]});
  const [edit,setEdit]=useState(false),[reason,setReason]=useState('');const mutation=useAction();
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading cycle…</p>}</>;
  const {cycle,report,reviews}=query.data;
  return <div className="space-y-5"><Section title={cycle.name}><p>{cycle.periodStart} to {cycle.periodEnd} · {title(cycle.status)}</p><p className="text-sm">{report.total} active reviews · {report.published} published · {report.acknowledged} acknowledged · {report.withdrawn} withdrawn</p><p className="text-sm">Average published rating: {report.averageRating===null?'No published ratings':report.averageRating+' / 5'} · Sample: {report.sampleCount} reviews in your view</p>
    {manage&&<div className="space-y-3"><div className="flex flex-wrap gap-2">{cycle.status==='draft'&&<><Button variant="outline" onClick={()=>setEdit(!edit)}>Edit settings</Button><Button disabled={mutation.isPending||!report.total} onClick={()=>mutation.mutate({url:`${endpoint}/${id}/actions`,body:{version:cycle.version,action:'open'}})}>Open cycle</Button></>}{cycle.status==='open'&&<Button disabled={mutation.isPending||reviews.some(r=>r.participationStatus==='active'&&r.status!=='acknowledged')} onClick={()=>mutation.mutate({url:`${endpoint}/${id}/actions`,body:{version:cycle.version,action:'close'}})}>Close completed cycle</Button>}</div>
      {['draft','open'].includes(cycle.status)&&!reviews.some(r=>['published','acknowledged'].includes(r.status))&&<details><summary className="cursor-pointer text-sm">Cancel cycle</summary><form className="mt-3 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`${endpoint}/${id}/actions`,body:{version:cycle.version,action:'cancel',reason}});}}><Field label="Cancellation reason"><input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} required/></Field><Button variant="outline" disabled={mutation.isPending}>Cancel cycle</Button></form></details>}
    </div>}
  </Section>{manage&&edit&&cycle.status==='draft'&&<CycleForm key={cycle.version} cycle={cycle} done={()=>setEdit(false)}/>}{manage&&cycle.status==='draft'&&<><AddParticipant key={cycle.version} cycle={cycle}/><BulkParticipants cycle={cycle}/></>}
  <Section title="Employee reviews"><Table headers={['Employee','Reviewer','Deadline','Stage','Rating','']} rows={reviews.map(r=>[r.employeeName,r.reviewerName,r.dueDate,r.participationStatus==='withdrawn'?'Withdrawn · '+title(r.status):title(r.status),r.finalRating||'—',<Button variant="outline" onClick={()=>openReview(r.id)}>Open review</Button>])}/></Section></div>;
}
function AddParticipant({cycle}:{cycle:Cycle}){
  const [employee,setEmployee]=useState(''),[reviewer,setReviewer]=useState(''),[due,setDue]=useState(cycle.dueDate),[self,setSelf]=useState(cycle.selfRequired);const mutation=useAction();
  return <Section title="Assign an employee"><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`${endpoint}/${cycle.id}/participants`,body:{version:cycle.version,employeeId:Number(employee),reviewerId:Number(reviewer),dueDate:due,selfRequired:self}});}}><div className="grid gap-4 sm:grid-cols-2"><PersonSelect kind="employees" value={employee} onChange={setEmployee}/><PersonSelect kind="reviewers" value={reviewer} onChange={setReviewer}/></div><Field label="Employee review deadline"><input className={fieldClass} type="date" value={due} min={cycle.periodEnd} onChange={e=>setDue(e.target.value)} required/></Field><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={self} onChange={e=>setSelf(e.target.checked)}/>Require this employee's self-assessment</label><p className="text-sm text-muted-foreground">The reviewer needs permission to manage this employee. HR calibration will require a different administrator.</p><Button disabled={mutation.isPending||!employee||!reviewer}>Assign employee</Button></form></Section>;
}
function ReviewPanel({id}:{id:number}){
  const query=useQuery<ReviewDetail>({queryKey:[`${endpoint}/assessments/${id}`]});const mutation=useAction();const [reason,setReason]=useState(''),[reviewer,setReviewer]=useState('');
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading review…</p>}</>;
  const data=query.data,{review:r,cycle,access}=data,open=cycle.status==='open'&&r.participationStatus==='active';
  const stage=open&&access.own&&r.status==='self_review'?'self':open&&access.reviewer&&r.status==='manager_review'?'manager':open&&access.calibrate&&r.status==='calibration'?'calibration':null;
  return <div className="space-y-5"><Section title={data.employee.name}><p>{cycle.name} · {title(r.status)} · Due {r.dueDate}</p>{r.finalRating&&<p className="text-xl font-semibold">Final rating {r.finalRating} / 5</p>}{r.finalSummary&&<p className="whitespace-pre-wrap">{r.finalSummary}</p>}{open&&access.own&&r.status==='published'&&<><p className="text-sm text-muted-foreground">Acknowledgement records that you have read this review. You can record a response below.</p><Field label="Employee response (optional)"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} maxLength={3000}/></Field><Button disabled={mutation.isPending} onClick={()=>mutation.mutate({url:`${endpoint}/assessments/${id}/actions`,body:{version:r.version,action:'acknowledge',reason}})}>Acknowledge review</Button></>}</Section>
    {r.participationStatus==='withdrawn'&&<p className="rounded border p-4 text-sm">This participant is withdrawn. Their earlier assessment and objective history is retained, and further submissions are paused.</p>}
    {cycle.status==='draft'&&access.manage&&r.participationStatus==='active'&&<ParticipantSettings key={r.version} review={r} cycle={cycle}/>}
    {access.manageParticipation&&['draft','open'].includes(cycle.status)&&!['published','acknowledged'].includes(r.status)&&<ParticipationControls key={r.version} cycle={cycle} review={r} withdrawn={r.participationStatus==='withdrawn'} reason={data.participation.reason}/>}
    {stage&&<AssessmentForm key={`${r.id}-${r.version}-${stage}`} data={data} stage={stage}/>}
    {r.selfScores&&<ScoreView title="Self-assessment" rubric={cycle.rubric} labels={cycle.ratingLabels} scores={r.selfScores} summary={r.selfSummary}/>}
    {r.managerScores&&<ScoreView title="Manager assessment" rubric={cycle.rubric} labels={cycle.ratingLabels} scores={r.managerScores} summary={r.managerSummary}/>}
    {r.finalScores&&<ScoreView title="Calibrated assessment" rubric={cycle.rubric} labels={cycle.ratingLabels} scores={r.finalScores} summary={r.finalSummary}/>}
    {open&&access.manage&&!['published','acknowledged'].includes(r.status)&&<Section title="Change reviewer"><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`${endpoint}/assessments/${id}/actions`,body:{version:r.version,action:'reassign',reviewerId:Number(reviewer),reason}});}}><PersonSelect kind="reviewers" value={reviewer} onChange={setReviewer}/><Field label="Reason"><input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} required/></Field><p className="text-sm text-muted-foreground">The new reviewer must submit a fresh assessment. Earlier submissions remain in the recorded history.</p><Button disabled={!reviewer||mutation.isPending}>Reassign review</Button></form></Section>}
    <Section title="Objectives & development plan">{data.objectives.map(o=><ObjectiveCard key={o.id+'-'+o.version} objective={o} editable={access.editObjectives&&cycle.status!=='cancelled'}/>)}{!data.objectives.length&&<p className="text-sm text-muted-foreground">No objectives yet.</p>}{access.editObjectives&&cycle.status!=='cancelled'&&<NewObjective id={id}/>}</Section>
    <Section title="Review history"><div className="space-y-3">{data.history.map(h=><div key={h.id} className="border-l-2 pl-3"><p className="text-sm font-medium">{title(h.action)} · {h.actorName}</p>{h.reason&&<p className="whitespace-pre-wrap text-sm">{h.reason}</p>}<p className="text-xs text-muted-foreground">{new Date(h.createdAt).toLocaleString()}</p></div>)}</div></Section>
  </div>;
}
function ScoreView({title:heading,rubric,labels,scores,summary}:{title:string;rubric:Rubric;labels:string[];scores:Scores;summary:string|null}){
  return <Section title={heading}><Table headers={['Criterion','Weight','Rating','Evidence / comment']} rows={rubric.map(r=>{const s=scores.find(s=>s.key===r.key);return [r.label,r.weight+'%',s?`${s.score} · ${labels[s.score-1]}`:'—',s?.comment||'—'];})}/>{summary&&<p className="whitespace-pre-wrap text-sm">{summary}</p>}</Section>;
}
function AssessmentForm({data,stage}:{data:ReviewDetail;stage:'self'|'manager'|'calibration'}){
  const r=data.review,initial=stage==='self'?r.selfScores:r.managerScores;
  const [scores,setScores]=useState<Scores>(data.cycle.rubric.map(r=>initial?.find(s=>s.key===r.key)||{key:r.key,score:0,comment:''})),[summary,setSummary]=useState((stage==='self'?r.selfSummary:r.managerSummary)||''),[reason,setReason]=useState('');const mutation=useAction();
  function send(action:string){mutation.mutate({url:`${endpoint}/assessments/${r.id}/actions`,body:{version:r.version,action,scores,summary,...(stage==='calibration'?{reason}:{})}});}
  return <Section title={stage==='calibration'?'HR calibration & publication':stage==='self'?'Your self-assessment':'Manager review'}><form className="space-y-4" onSubmit={e=>{e.preventDefault();send(stage==='calibration'?'publish':stage==='self'?'submit_self':'submit_manager');}}>{data.cycle.rubric.map((criterion,i)=><div className="rounded border p-3 space-y-3" key={criterion.key}><Field label={`${criterion.label} (${criterion.weight}%)`}><select className={fieldClass} value={scores[i].score||''} required onChange={e=>setScores(scores.map((s,j)=>i===j?{...s,score:Number(e.target.value)}:s))}><option value="">Choose rating…</option>{data.cycle.ratingLabels.map((label,n)=><option value={n+1} key={n}>{n+1} · {label}</option>)}</select></Field><Field label="Evidence and comments"><textarea className={fieldClass} value={scores[i].comment} maxLength={2000} onChange={e=>setScores(scores.map((s,j)=>i===j?{...s,comment:e.target.value}:s))}/></Field></div>)}
    <Field label="Assessment summary"><textarea className={fieldClass} value={summary} rows={4} minLength={10} maxLength={10000} required onChange={e=>setSummary(e.target.value)}/></Field>{stage==='calibration'&&<Field label="Calibration or return reason"><textarea className={fieldClass} value={reason} minLength={5} maxLength={3000} required onChange={e=>setReason(e.target.value)}/></Field>}
    <div className="flex flex-wrap gap-2"><Button disabled={mutation.isPending} type="submit">{stage==='calibration'?'Publish calibrated review':'Submit assessment'}</Button>{stage!=='calibration'?<Button type="button" variant="outline" disabled={mutation.isPending} onClick={()=>send(stage==='self'?'save_self':'save_manager')}>Save assessment</Button>:<Button type="button" variant="outline" disabled={mutation.isPending||reason.trim().length<5} onClick={()=>send('return_manager')}>Return to reviewer</Button>}</div>
  </form></Section>;
}
function NewObjective({id}:{id:number}){
  const [kind,setKind]=useState('objective'),[title,setTitle]=useState(''),[measure,setMeasure]=useState(''),[due,setDue]=useState('');const mutation=useAction(()=>{setTitle('');setMeasure('');setDue('');});
  return <details className="rounded border p-4"><summary className="cursor-pointer font-medium">Add objective or development action</summary><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`${endpoint}/assessments/${id}/objectives`,body:{kind,title,measure,dueDate:due}});}}><Field label="Type"><select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="objective">Objective</option><option value="development">Development action</option></select></Field><Field label="Title"><input className={fieldClass} value={title} maxLength={200} required onChange={e=>setTitle(e.target.value)}/></Field><Field label="Success measure / planned action"><textarea className={fieldClass} value={measure} required maxLength={3000} onChange={e=>setMeasure(e.target.value)}/></Field><Field label="Due date"><input className={fieldClass} type="date" value={due} required onChange={e=>setDue(e.target.value)}/></Field><Button disabled={mutation.isPending}>Add to plan</Button></form></details>;
}
function ObjectiveCard({objective:o,editable}:{objective:Objective;editable:boolean}){
  const [progress,setProgress]=useState(o.progress),[status,setStatus]=useState(o.status),[note,setNote]=useState('');const mutation=useAction(()=>setNote(''));
  return <article className="rounded border p-4 space-y-2"><h3 className="font-semibold">{o.title}</h3><p className="whitespace-pre-wrap text-sm">{o.measure}</p><p className="text-sm text-muted-foreground">{title(o.kind)} · Due {o.dueDate} · {o.progress}% · {title(o.status)}</p>{editable&&<details><summary className="cursor-pointer text-sm text-primary">Update progress</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`${endpoint}/objectives/${o.id}/progress`,body:{version:o.version,progress,status,note}});}}><div className="grid gap-3 sm:grid-cols-2"><Field label="Progress %"><input type="number" className={fieldClass} min={0} max={100} value={progress} onChange={e=>setProgress(Number(e.target.value))} required/></Field><Field label="Status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);if(e.target.value==='completed')setProgress(100);}}>{['active','completed','cancelled'].map(s=><option key={s} value={s}>{title(s)}</option>)}</select></Field></div><Field label="Progress evidence / reason"><textarea className={fieldClass} value={note} maxLength={3000} required onChange={e=>setNote(e.target.value)}/></Field><Button disabled={mutation.isPending}>Save progress</Button></form></details>}</article>;
}

function ParticipantSettings({review:r,cycle}:{review:Review;cycle:Cycle}){
  const [reviewer,setReviewer]=useState(String(r.reviewerId)),[due,setDue]=useState(r.dueDate),[self,setSelf]=useState(r.selfRequired);const mutation=useAction();
  return <Section title="Employee review settings"><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate({url:endpoint+'/assessments/'+r.id,method:'PATCH',body:{version:r.version,reviewerId:Number(reviewer),dueDate:due,selfRequired:self}});}}><PersonSelect kind="reviewers" value={reviewer} onChange={setReviewer}/><Field label="Employee deadline"><input type="date" className={fieldClass} value={due} min={cycle.periodEnd} required onChange={e=>setDue(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={self} onChange={e=>setSelf(e.target.checked)}/>Require self-assessment</label><Button disabled={mutation.isPending}>Save employee settings</Button></form></Section>;
}
