import {useEffect,useState,type FormEvent} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Field,Section,Table,QueryError,fieldClass,useAction} from './Operations';
import {siteTimeToIso,type WorkforceDashboard} from '@shared/workforce';
import {defaultArrivalRules,type ArrivalRules,type MyPresence,type PresenceView,type ShiftOperations,type IncidentView} from '@shared/workforce-operations';
import {readAttendancePosition} from '@/lib/attendance-location';

const display=(value:string,zone:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:zone,dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
function wall(value:string,zone:string){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;}
type Member=WorkforceDashboard['members'][number];
export function MembershipEndButton({member,zone}:{member:Member;zone:string}){
  const [open,setOpen]=useState(false),[end,setEnd]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<unknown>(null);
  const history=useQuery<{id:number;version:number;previousEndAt:string;endAt:string;reason:string;createdAt:string}[]>({queryKey:[`/api/workforce/members/${member.id}/history`],enabled:open});
  const save=useAction(()=>setOpen(false));
  async function submit(e:FormEvent){e.preventDefault();setError(null);try{await save.mutateAsync({url:`/api/workforce/members/${member.id}/end-date`,body:{version:member.version,endAt:siteTimeToIso(end,zone),reason}});}catch(e){setError(e);}}
  return <><Button size="sm" variant="outline" onClick={()=>{setEnd(wall(member.endAt,zone));setReason('');setError(null);setOpen(true);}}>Dates & history</Button><Dialog open={open} onOpenChange={v=>{if(!save.isPending)setOpen(v);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{member.name}: membership dates</DialogTitle><DialogDescription>Times use {zone}. The original start stays in history. End or extend this period, then add a new membership period when needed.</DialogDescription></DialogHeader>
    <p className="text-sm">Starts {display(member.startAt,zone)} · Version {member.version}</p>
    {new Date(member.endAt)>new Date()&&<form onSubmit={submit} className="space-y-3"><fieldset disabled={save.isPending} className="space-y-3"><Field label="New membership end"><input className={fieldClass} type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} required/></Field><Field label="Reason for date change"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000} required/></Field><p className="text-xs text-muted-foreground">Affected offers and accepted shifts must be released or replaced before shortening membership.</p><QueryError error={error}/><Button type="submit">Save end date</Button></fieldset></form>}
    <h3 className="font-medium">Change history</h3><QueryError error={history.error}/>{history.isLoading?<p>Loading history…</p>:<Table headers={['Changed','Previous end','New end','Reason']} rows={(history.data||[]).map(h=>[display(h.createdAt,zone),display(h.previousEndAt,zone),display(h.endAt,zone),h.reason])}/>}
  </DialogContent></Dialog></>;
}

type RuleHistory={id:number;employeeId:number|null;employeeName:string|null;effectiveAt:string;rules:ArrivalRules;reason:string};
export function ArrivalRulesPanel({teamId,zone,members}:{teamId:number;zone:string;members:Member[]}){
  const [expanded,setExpanded]=useState(false),[employeeId,setEmployeeId]=useState(''),[rules,setRules]=useState(defaultArrivalRules),[effective,setEffective]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<unknown>(null);
  const query=useQuery<{defaults:ArrivalRules;history:RuleHistory[]}>({queryKey:[`/api/workforce/teams/${teamId}/arrival-rules`],enabled:expanded});
  const save=useAction(()=>{setReason('');setEffective('');});
  useEffect(()=>{const rows=query.data?.history||[];const applicable=rows.find(r=>String(r.employeeId||'')===employeeId&&new Date(r.effectiveAt)<=new Date())||rows.find(r=>r.employeeId===null&&new Date(r.effectiveAt)<=new Date());setRules(applicable?.rules||defaultArrivalRules);},[query.data,employeeId]);
  async function submit(e:FormEvent){e.preventDefault();setError(null);try{await save.mutateAsync({url:`/api/workforce/teams/${teamId}/arrival-rules`,body:{employeeId:employeeId?Number(employeeId):null,effectiveAt:effective?siteTimeToIso(effective,zone):null,rules,reason}});}catch(e){setError(e);}}
  const people=[...new Map(members.map(m=>[m.employeeId,m])).values()];
  return <Section title="Arrival rules"><Button variant="outline" onClick={()=>setExpanded(v=>!v)}>{expanded?'Hide arrival rules':'Configure arrival rules'}</Button>{expanded&&<><p className="text-sm text-muted-foreground">Set team defaults or an employee override. Revisions take effect at the chosen time and are saved with each arrival. Employee overrides take priority until replaced. Times use {zone}.</p><QueryError error={query.error}/>
    <form onSubmit={submit}><fieldset disabled={save.isPending||query.isLoading||!!query.error} className="space-y-3"><Field label="Arrival rule applies to"><select className={fieldClass} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All team members</option>{people.map(m=><option key={m.employeeId} value={m.employeeId}>{m.name}</option>)}</select></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={rules.enabled} onChange={e=>setRules({...rules,enabled:e.target.checked})}/>Enable mobile arrival</label>
      <div className="grid gap-3 sm:grid-cols-3">{([['earlyMinutes','Minutes before shift to open arrival'],['lateMinutes','Minutes after start to close arrival'],['departureGraceMinutes','Departure grace after shift (minutes)']] as const).map(([key,label])=><Field key={key} label={label}><input className={fieldClass} type="number" min={0} max={1440} value={rules[key]} onChange={e=>setRules({...rules,[key]:Number(e.target.value)})} required/></Field>)}</div>
      <Field label="Effective time (blank means now)"><input className={fieldClass} type="datetime-local" value={effective} onChange={e=>setEffective(e.target.value)}/></Field><Field label="Reason for rule revision"><textarea className={fieldClass} minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} required/></Field><QueryError error={error}/><Button type="submit">Save arrival rule revision</Button></fieldset></form>
    <p className="text-xs text-muted-foreground">Initial settings: arrival opens 60 minutes before the shift and closes 240 minutes after its start, capped at shift end. Departure is always available after arrival; early or overdue departures are flagged for review.</p>
    <Table headers={['Scope','Effective','Arrival window','Departure grace','Reason']} rows={(query.data?.history||[]).map(r=>[r.employeeName||'All team members',display(r.effectiveAt,zone),r.rules.enabled?`${r.rules.earlyMinutes} min before / ${r.rules.lateMinutes} min after start`:'Disabled',`${r.rules.departureGraceMinutes} min`,r.reason])}/>
  </>}</Section>;
}

export function MyArrival({assignmentId,zone}:{assignmentId:number;zone:string}){
  const query=useQuery<MyPresence>({queryKey:[`/api/workforce/assignments/${assignmentId}/presence`],refetchInterval:30000});
  const save=useAction(),p=query.data?.presence,now=Date.now(),canArrive=query.data?.rules.enabled&&now>=Date.parse(query.data.opensAt)&&now<=Date.parse(query.data.closesAt);
  const [locating,setLocating]=useState(false),[error,setError]=useState<unknown>(null);
  async function record(action:'arrival'|'departure'){setLocating(true);setError(null);try{const position=query.data?.locationRequired?await readAttendancePosition():undefined;await save.mutateAsync({url:`/api/workforce/assignments/${assignmentId}/${action}`,body:position?{position}:{}});}catch(e){setError(e);}finally{setLocating(false);}}
  return <div className="w-full space-y-2 border-t pt-3"><h3 className="font-medium">Arrival & departure</h3><QueryError error={query.error||error}/>{query.isLoading?<p>Loading arrival status…</p>:query.data&&<>
    {p?<><p className="text-sm">Arrived {display(p.arrivedAt,zone)}{p.departedAt?` · Departed ${display(p.departedAt,zone)}`:' · Visit open'} · Supervisor: {p.approvalStatus||'pending'}</p>{p.flags.length>0&&<p className="text-sm">Review flags: {p.flags.join('; ')}</p>}{p.reviewedAt&&<p className="text-sm">Reviewed: {p.reviewNote}</p>}{!p.departedAt&&<Button disabled={save.isPending||locating} onClick={()=>record('departure')}>Record departure</Button>}</>:
      <><p className="text-sm">{query.data.rules.enabled?`Arrival window: ${display(query.data.opensAt,zone)} → ${display(query.data.closesAt,zone)}`:'Mobile arrival is disabled by your current rules.'}</p><Button disabled={save.isPending||locating||!canArrive} onClick={()=>record('arrival')}>Record arrival</Button>{!canArrive&&query.data.rules.enabled&&<p className="text-xs text-muted-foreground">Outside the window, contact your lead to report the exception.</p>}</>}
    <p className="text-xs text-muted-foreground">{locating?'Reading current location… ':query.data.locationRequired?'Allow GPS access; your arrival and departure must be inside an assigned site location. ':''}Supervisor attendance approval is required before Timesheets can approve this assignment for payroll.</p><QueryError error={save.error}/>
  </>}</div>;
}

function PresenceReview({row,zone}:{row:PresenceView&{name:string;canReview?:boolean};zone:string}){
  const [reason,setReason]=useState(''),[decision,setDecision]=useState('approve');const save=useAction(()=>setReason(''));
  return <div className="space-y-2 rounded-md border p-3"><p className="font-medium">{row.name}</p><p className="text-sm">{display(row.arrivedAt,zone)} → {row.departedAt?display(row.departedAt,zone):'Visit open'}</p>{row.flags.length>0&&<p className="text-sm">{row.flags.join('; ')}</p>}{row.departureReason&&<p className="text-sm">Closure: {row.departureReason}</p>}
    <p className="text-sm">Supervisor approval: {row.approvalStatus||'pending'} · Location: {row.locationIn?.fence?.name||row.locationIn?.status||'Legacy'} → {row.locationOut?.fence?.name||row.locationOut?.status||'—'}</p>
    {row.reviewedAt?<p className="text-sm">Reviewed: {row.reviewNote}</p>:row.canReview&&<form onSubmit={e=>{e.preventDefault();save.mutate({url:`/api/workforce/presence/${row.id}/review`,body:{version:row.version,action:row.departedAt?decision:'close',reason}});}} className="space-y-2">{row.departedAt&&<Field label="Attendance decision"><select className={fieldClass} value={decision} onChange={e=>setDecision(e.target.value)}><option value="approve">Approve attendance</option><option value="reject">Reject attendance</option></select></Field>}<Field label={row.departedAt?'Supervisor review reason':'Reason to close open visit'}><textarea className={fieldClass} minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} required/></Field><Button size="sm" variant="outline" disabled={save.isPending}>{row.departedAt?'Save attendance decision':'Close visit at current time'}</Button><QueryError error={save.error}/></form>}
  </div>;
}
function IncidentCard({row,canManage,zone}:{row:IncidentView;canManage:boolean;zone:string}){
  const [status,setStatus]=useState<string>(row.status==='resolved'?'open':'in_progress'),[note,setNote]=useState('');const save=useAction(()=>setNote(''));
  useEffect(()=>setStatus(row.status==='resolved'?'open':'in_progress'),[row.status]);
  return <article className="space-y-3 rounded-md border p-4"><div><h3 className="font-semibold">#{row.id} · {row.title}</h3><p className="text-sm">{row.severity} priority · {row.status.replace('_',' ')} · {display(row.occurredAt,zone)}</p><p className="text-xs text-muted-foreground">Reported by {row.reporterName} · Owner: {row.ownerName||'Unassigned'}</p></div><p className="whitespace-pre-wrap break-words text-sm">{row.details}</p>
    {row.history.length>0&&<details><summary className="cursor-pointer text-sm font-medium">Update history ({row.history.length})</summary>{row.history.map(h=><div className="mt-2 border-l-2 pl-3 text-sm" key={h.id}><p>{h.status.replace('_',' ')} · {h.actorName} · {display(h.createdAt,zone)}</p><p className="whitespace-pre-wrap break-words">{h.note}</p></div>)}</details>}
    {canManage&&<form onSubmit={e=>{e.preventDefault();save.mutate({url:`/api/workforce/incidents/${row.id}/status`,body:{version:row.version,status,note}});}} className="space-y-2"><fieldset disabled={save.isPending} className="space-y-2"><Field label={`Update incident #${row.id}`}><select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value)}>{row.status==='resolved'?<option value="open">Reopen</option>:<><option value="in_progress">Take ownership / add progress</option><option value="resolved">Resolve</option>{row.status==='in_progress'&&<option value="open">Return to unassigned queue</option>}</>}</select></Field><Field label="Incident update note"><textarea className={fieldClass} minLength={5} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} required/></Field><Button size="sm" type="submit">Save incident update</Button></fieldset><QueryError error={save.error}/></form>}
  </article>;
}
export function ShiftOperationsButton({shiftId,zone,startAt,endAt}:{shiftId:number;zone:string;startAt:string;endAt:string}){
  const [open,setOpen]=useState(false),[form,setForm]=useState({title:'',details:'',severity:'medium',occurredAt:'',requestKey:''}),[error,setError]=useState<unknown>(null);
  const query=useQuery<ShiftOperations>({queryKey:[`/api/workforce/shifts/${shiftId}/operations`],enabled:open,refetchInterval:open?30000:false});
  const save=useAction(()=>setForm(f=>({...f,title:'',details:'',requestKey:crypto.randomUUID()})));
  function begin(){setError(null);setForm({title:'',details:'',severity:'medium',occurredAt:wall(new Date(Math.min(Date.now(),Date.parse(endAt))).toISOString(),zone),requestKey:crypto.randomUUID()});setOpen(true);}
  async function submit(e:FormEvent){e.preventDefault();setError(null);try{await save.mutateAsync({url:`/api/workforce/shifts/${shiftId}/incidents`,body:{...form,occurredAt:siteTimeToIso(form.occurredAt,zone)}});}catch(e){setError(e);}}
  return <><Button size="sm" variant="outline" onClick={begin}>Operations log</Button><Dialog open={open} onOpenChange={v=>{if(!save.isPending)setOpen(v);}}><DialogContent className="max-h-[90vh] max-w-3xl overflow-auto"><DialogHeader><DialogTitle>Shift #{shiftId}: operations log</DialogTitle><DialogDescription>Arrival records and operational incidents. Times use {zone}. Reports are visible to their reporter and authorized scheduling leads. Use Helpdesk for confidential HR matters.</DialogDescription></DialogHeader><QueryError error={query.error}/>{query.isLoading?<p>Loading operations…</p>:query.data&&<>
    <h2 className="text-lg font-semibold">Recorded visits</h2><p className="text-xs text-muted-foreground">A visit records arrival and departure. Independent supervisor approval is required before the assignment timesheet can be approved. Payable hours still receive a separate Timesheet review.</p>{query.data.presence.length?query.data.presence.map(p=><PresenceReview key={p.id} row={p} zone={zone}/>):<p className="text-sm text-muted-foreground">No arrivals recorded.</p>}
    <h2 className="text-lg font-semibold">{query.data.canManage?'Incident log':'Your incident reports'}</h2>{query.data.incidents.length?query.data.incidents.map(i=><IncidentCard key={i.id} row={i} canManage={query.data!.canManage} zone={zone}/>):<p className="text-sm text-muted-foreground">No reports to show.</p>}
    {Date.parse(startAt)<=Date.now()?<form onSubmit={submit} className="space-y-3 border-t pt-4"><h3 className="font-semibold">Report an operational incident</h3><fieldset disabled={save.isPending} className="space-y-3"><Field label="Incident title"><input className={fieldClass} minLength={5} maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Incident time"><input className={fieldClass} type="datetime-local" value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})} required/></Field><Field label="Incident priority"><select className={fieldClass} value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></Field></div><Field label="What happened and immediate action taken"><textarea className={fieldClass} rows={4} minLength={10} maxLength={4000} value={form.details} onChange={e=>setForm({...form,details:e.target.value})} required/></Field><QueryError error={error}/><Button type="submit">Submit incident report</Button></fieldset></form>:<p className="text-sm text-muted-foreground">Incident reporting opens when the shift starts.</p>}
  </>}</DialogContent></Dialog></>;
}
