import {useState,type FormEvent} from 'react';
import {useMutation,useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {apiJson} from '@/lib/queryClient';
import {Field,Section,Table,QueryError,fieldClass,useAction} from './Operations';
import type {AvailabilityPattern,AvailabilitySeries} from '@shared/workforce-renewals';
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const format=(value:string,zone:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:zone,dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
type Occurrence={id:number;startAt:string;endAt:string;cancelledAt:string|null;cancellationReason:string|null};
function PatternDetail({id,onClose}:{id:number;onClose:()=>void}){
  const query=useQuery<{series:AvailabilitySeries;occurrences:Occurrence[]}>({queryKey:[`/api/workforce/staffing/availability-series/${id}`]});
  const [action,setAction]=useState<{url:string;label:string}|null>(null),[reason,setReason]=useState('');const save=useAction(()=>{setAction(null);setReason('');});
  const series=query.data?.series,zone=series?.pattern.timezone||'UTC';
  return <Dialog open onOpenChange={v=>{if(!v&&!save.isPending)onClose();}}><DialogContent className="max-h-[90vh] max-w-3xl overflow-auto"><DialogHeader><DialogTitle>Recurring unavailable dates #{id}</DialogTitle><DialogDescription>Skip a future occurrence or stop all future dates. Started and past occurrences remain in history. Times use {zone}.</DialogDescription></DialogHeader><QueryError error={query.error}/>{series&&<>
    <p className="text-sm">{series.pattern.startDate} → {series.pattern.endDate} · {series.pattern.weekdays.map(d=>days[d]).join(', ')} · {series.pattern.startTime}–{series.pattern.endTime}{series.pattern.endDayOffset?' next day':''}</p>{series.pattern.note&&<p className="text-sm">Private note: {series.pattern.note}</p>}{series.stoppedAt?<p className="text-sm">Stopped: {series.stopReason}</p>:query.data!.occurrences.some(o=>!o.cancelledAt&&Date.parse(o.startAt)>Date.now())&&<Button variant="outline" disabled={save.isPending} onClick={()=>{setAction({url:`/api/workforce/staffing/availability-series/${id}/stop`,label:'Stop future occurrences'});setReason('');}}>Stop future occurrences</Button>}
    {action&&<form onSubmit={e=>{e.preventDefault();save.mutate({url:action.url,body:{reason}});}} className="space-y-3 rounded border p-3"><Field label={`Reason: ${action.label}`}><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} required/></Field><QueryError error={save.error}/><Button disabled={save.isPending}>{action.label}</Button><Button type="button" variant="ghost" onClick={()=>setAction(null)}>Keep dates</Button></form>}
    <Table headers={['Occurrence','Status','Action']} rows={query.data!.occurrences.map(o=>[`${format(o.startAt,zone)} → ${format(o.endAt,zone)}`,o.cancelledAt?`Cancelled: ${o.cancellationReason}`:Date.parse(o.endAt)<=Date.now()?'Past':'Unavailable',!o.cancelledAt&&Date.parse(o.startAt)>Date.now()?<Button size="sm" variant="outline" disabled={save.isPending} onClick={()=>{setAction({url:`/api/workforce/staffing/unavailable/${o.id}/cancel`,label:'Skip selected date'});setReason('');}}>Skip this date</Button>:null])}/>
  </>}</DialogContent></Dialog>;
}
export function RecurringAvailability({employeeId}:{employeeId:number}){
  const [open,setOpen]=useState(false),[page,setPage]=useState(1),[detail,setDetail]=useState<number|null>(null);
  const [pattern,setPattern]=useState<AvailabilityPattern>({timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,startDate:'',endDate:'',weekdays:[1],startTime:'09:00',endTime:'17:00',endDayOffset:0,note:''});
  const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
  const list=useQuery<{series:AvailabilitySeries[];hasMore:boolean}>({queryKey:[`/api/workforce/staffing/employees/${employeeId}/availability-series`,{page}]});
  const preview=useMutation({mutationFn:()=>apiJson<{occurrences:{startAt:string;endAt:string;issue:string|null}[]}>(`/api/workforce/staffing/employees/${employeeId}/availability-series/preview`,{method:'POST',body:pattern})});
  const save=useAction(()=>{setOpen(false);preview.reset();setRequestKey(crypto.randomUUID());setPage(1);});
  function change(patch:Partial<AvailabilityPattern>){setPattern(p=>({...p,...patch}));preview.reset();save.reset();setRequestKey(crypto.randomUUID());}
  function submit(e:FormEvent){e.preventDefault();preview.mutate();}
  return <Section title="Recurring unavailability"><p className="text-sm text-muted-foreground">Repeat unavailable hours on selected weekdays for up to one year. Preview every date before saving. Existing accepted work must be released or replaced first. Notes remain private to you and HR.</p><Button variant="outline" onClick={()=>setOpen(v=>!v)}>{open?'Close weekly pattern':'Add weekly pattern'}</Button>
    {open&&<form className="space-y-3" onSubmit={submit}><fieldset disabled={preview.isPending||save.isPending} className="space-y-3"><Field label="Pattern time zone"><input className={fieldClass} value={pattern.timezone} onChange={e=>change({timezone:e.target.value})} required/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="First pattern date"><input className={fieldClass} type="date" value={pattern.startDate} onChange={e=>change({startDate:e.target.value})} required/></Field><Field label="Last pattern date"><input className={fieldClass} type="date" value={pattern.endDate} onChange={e=>change({endDate:e.target.value})} required/></Field></div>
      <fieldset><legend className="text-sm font-medium">Unavailable weekdays</legend><div className="mt-2 flex flex-wrap gap-4">{days.map((day,i)=><label key={day} className="flex items-center gap-1 text-sm"><input type="checkbox" checked={pattern.weekdays.includes(i)} onChange={e=>change({weekdays:e.target.checked?[...pattern.weekdays,i]:pattern.weekdays.filter(d=>d!==i)})}/>{day}</label>)}</div></fieldset>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Unavailable start time"><input className={fieldClass} type="time" value={pattern.startTime} onChange={e=>change({startTime:e.target.value})} required/></Field><Field label="Unavailable end time"><input className={fieldClass} type="time" value={pattern.endTime} onChange={e=>change({endTime:e.target.value})} required/></Field><Field label="End on"><select className={fieldClass} value={pattern.endDayOffset} onChange={e=>change({endDayOffset:Number(e.target.value)})}><option value={0}>Same day</option><option value={1}>Next day</option></select></Field></div>
      <Field label="Pattern private note (optional)"><textarea className={fieldClass} value={pattern.note} onChange={e=>change({note:e.target.value})} maxLength={500}/></Field><Button type="submit">Preview weekly dates</Button></fieldset><QueryError error={preview.error||save.error}/>
      {preview.data&&<><p className="font-medium">{preview.data.occurrences.length} occurrences · {preview.data.occurrences.filter(o=>o.issue).length} conflicts</p><div className="max-h-64 overflow-auto"><Table headers={['Date and time','Check']} rows={preview.data.occurrences.map(o=>[`${format(o.startAt,pattern.timezone)} → ${format(o.endAt,pattern.timezone)}`,o.issue||'Ready'])}/></div><Button type="button" disabled={save.isPending||preview.data.occurrences.some(o=>o.issue)} onClick={()=>save.mutate({url:`/api/workforce/staffing/employees/${employeeId}/availability-series`,body:{requestKey,pattern}})}>Save weekly unavailability</Button></>}
    </form>}
    <QueryError error={list.error}/>{list.isLoading?<p>Loading patterns…</p>:<Table headers={['Pattern','Remaining dates','Action']} rows={(list.data?.series||[]).map(s=>[`${s.pattern.startDate} → ${s.pattern.endDate} · ${s.pattern.weekdays.map(d=>days[d]).join(', ')} · ${s.pattern.startTime}–${s.pattern.endTime} · ${s.pattern.timezone}`,s.stoppedAt?'Stopped':s.futureCount,<Button size="sm" variant="outline" onClick={()=>setDetail(s.id)}>Dates & exceptions</Button>])}/>}
    {(page>1||list.data?.hasMore)&&<div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous patterns</Button><span>Page {page}</span><Button size="sm" variant="outline" disabled={!list.data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next patterns</Button></div>}{detail&&<PatternDetail id={detail} onClose={()=>setDetail(null)}/>}
  </Section>;
}
