import {useEffect,useState,type FormEvent} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Field,Section,Table,QueryError,fieldClass,useAction} from './Operations';
import {siteTimeToIso,type WorkforcePerson} from '@shared/workforce';
import type {Qualification} from '@shared/workforce-staffing';
import {defaultRenewalPolicy,type RenewalPolicy,type RenewalDue,type RenewalView} from '@shared/workforce-renewals';

function CertificatePicker({credentialId,renewalId,value,onChange}:{credentialId:number;renewalId?:number;value:string;onChange:(s:string)=>void}){
  const [page,setPage]=useState(1),query=useQuery<{items:{id:number;documentType:string;issueDate:string;expiryDate:string;version:number}[];hasMore:boolean;policy:RenewalPolicy}>({queryKey:[`/api/workforce/staffing/qualifications/${credentialId}/evidence`,{page,...(renewalId?{renewalId}:{})}]});
  return <div className="space-y-2"><Field label={query.data?.policy.evidenceRequired?'Private certificate document (required)':'Private certificate document (optional)'}><select className={fieldClass} value={value} onChange={e=>onChange(e.target.value)} required={query.data?.policy.evidenceRequired} disabled={query.isLoading||!!query.error}><option value="">Select uploaded certificate…</option>{value&&!query.data?.items.some(d=>String(d.id)===value)&&<option value={value}>Selected document #{value}</option>}{query.data?.items.map(d=><option key={d.id} value={d.id}>#{d.id} · {d.documentType} · Expires {d.expiryDate} · Version {d.version}</option>)}</select></Field><QueryError error={query.error}/><p className="text-xs text-muted-foreground">Upload certificates under <a href="/documents" className="text-primary underline" target="_blank" rel="noopener noreferrer">Documents</a>, then refresh this list. {query.data?.policy.documentType?`Required type: ${query.data.policy.documentType}. `:''}The submitted document version is retained for independent HR verification.</p><div className="flex gap-2"><Button variant="ghost" size="sm" type="button" onClick={()=>void query.refetch()}>Refresh documents</Button>{page>1&&<Button variant="ghost" size="sm" type="button" onClick={()=>setPage(page-1)}>Previous</Button>}{query.data?.hasMore&&<Button variant="ghost" size="sm" type="button" onClick={()=>setPage(page+1)}>More documents</Button>}</div></div>;
}

export function RenewalRequestButton({credentialId,label='Submit renewal'}:{credentialId:number;label?:string}){
  const [open,setOpen]=useState(false),[reference,setReference]=useState(''),[note,setNote]=useState(''),[requestKey,setRequestKey]=useState(''),[documentId,setDocumentId]=useState('');const save=useAction(()=>setOpen(false));
  return <><Button size="sm" variant="outline" onClick={()=>{setReference('');setNote('');setDocumentId('');setRequestKey(crypto.randomUUID());save.reset();setOpen(true);}}>{label}</Button><Dialog open={open} onOpenChange={v=>{if(!save.isPending)setOpen(v);}}><DialogContent><DialogHeader><DialogTitle>Submit qualification renewal</DialogTitle><DialogDescription>Provide a certificate reference or the location of evidence already shared with HR. HR must verify the renewal and dates before it counts toward shift eligibility.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();save.mutate({url:`/api/workforce/staffing/qualifications/${credentialId}/renew`,body:{requestKey,reference,note,documentId:documentId?Number(documentId):null}});}} className="space-y-3"><fieldset disabled={save.isPending} className="space-y-3"><Field label="Renewal evidence reference"><textarea className={fieldClass} value={reference} onChange={e=>setReference(e.target.value)} minLength={5} maxLength={500} required/></Field><CertificatePicker credentialId={credentialId} value={documentId} onChange={setDocumentId}/><Field label="Renewal note (optional)"><textarea className={fieldClass} value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></Field><QueryError error={save.error}/><Button type="submit">Send for HR verification</Button></fieldset></form></DialogContent></Dialog></>;
}
type PolicyRow={id:number;qualificationId:number;qualificationName:string;employeeId:number|null;employeeName:string|null;effectiveAt:string;config:RenewalPolicy;reason:string};
function RenewalRules(){
  const [open,setOpen]=useState(false),[qualificationId,setQualificationId]=useState(''),[employeeId,setEmployeeId]=useState(''),[search,setSearch]=useState(''),[q,setQ]=useState('');
  const [config,setConfig]=useState(defaultRenewalPolicy),[effective,setEffective]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<unknown>(null);
  useEffect(()=>{const timer=setTimeout(()=>setQ(search.trim()),300);return()=>clearTimeout(timer);},[search]);
  const catalog=useQuery<Qualification[]>({queryKey:['/api/workforce/staffing/catalog'],enabled:open}),people=useQuery<WorkforcePerson[]>({queryKey:['/api/workforce/directory',{kind:'employees',q}],enabled:open&&q.length>=2});
  const rules=useQuery<{defaults:RenewalPolicy;history:PolicyRow[]}>({queryKey:['/api/workforce/renewal-policies'],enabled:open});
  useEffect(()=>{const rows=(rules.data?.history||[]).filter(r=>String(r.qualificationId)===qualificationId&&Date.parse(r.effectiveAt)<=Date.now());const selected=rows.find(r=>String(r.employeeId||'')===employeeId)||rows.find(r=>r.employeeId===null);setConfig({...defaultRenewalPolicy,...selected?.config});},[rules.data,qualificationId,employeeId]);
  const save=useAction(()=>{setReason('');setEffective('');});
  async function submit(e:FormEvent){e.preventDefault();setError(null);try{await save.mutateAsync({url:'/api/workforce/renewal-policies',body:{qualificationId:Number(qualificationId),employeeId:employeeId?Number(employeeId):null,effectiveAt:effective?siteTimeToIso(effective,config.timezone):null,config,reason}});}catch(e){setError(e);}}
  return <Section title="Renewal & certificate rules"><Button variant="outline" onClick={()=>setOpen(v=>!v)}>{open?'Hide reminder rules':'Configure reminder rules'}</Button>{open&&<><p className="text-sm text-muted-foreground">Set reminder windows per qualification, with optional employee overrides and effective dates. The due list updates when opened or refreshed. The initial window is 30 days in UTC.</p><QueryError error={catalog.error||rules.error||people.error}/><form onSubmit={submit}><fieldset disabled={save.isPending||rules.isLoading||!!rules.error} className="space-y-3"><Field label="Reminder qualification"><select className={fieldClass} value={qualificationId} onChange={e=>setQualificationId(e.target.value)} required><option value="">Choose qualification…</option>{catalog.data?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><Field label="Find employee override (optional)"><input className={fieldClass} value={search} onChange={e=>{setSearch(e.target.value);setEmployeeId('');}} placeholder="At least 2 characters"/></Field><Field label="Reminder applies to"><select className={fieldClass} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All employees</option>{people.data?.map(p=><option key={p.id} value={p.id}>{p.name} · {p.label}</option>)}</select></Field>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Days before expiry to remind"><input className={fieldClass} type="number" min={0} max={365} value={config.reminderDays} onChange={e=>setConfig({...config,reminderDays:Number(e.target.value)})} required/></Field><Field label="Reminder time zone"><input className={fieldClass} value={config.timezone} onChange={e=>setConfig({...config,timezone:e.target.value})} required/></Field></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.evidenceRequired} onChange={e=>setConfig({...config,evidenceRequired:e.target.checked})}/>Require a private certificate document for renewal verification</label><Field label="Certificate document type (blank allows any uploaded type)"><input className={fieldClass} value={config.documentType} maxLength={100} onChange={e=>setConfig({...config,documentType:e.target.value})} placeholder="professional_certification"/></Field><Field label="Reminder rule effective time (blank means now)"><input className={fieldClass} type="datetime-local" value={effective} onChange={e=>setEffective(e.target.value)}/></Field><Field label="Reason for reminder rule"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} required/></Field><QueryError error={error}/><Button type="submit">Save reminder rule</Button></fieldset></form>
      <Table headers={['Qualification / scope','Effective','Window','Reason']} rows={(rules.data?.history||[]).map(r=>[`${r.qualificationName} · ${r.employeeName||'All employees'}`,new Date(r.effectiveAt).toLocaleString(),`${r.config.reminderDays} days · ${r.config.timezone}`,r.reason])}/>
    </>}</Section>;
}
function RenewalHistory({id}:{id:number}){
  const [open,setOpen]=useState(false);const query=useQuery<{id:number;version:number;actorId:number;action:string;reason:string;createdAt:string;snapshot:{reference:string;note:string;newCredentialId:number|null}}[]>({queryKey:[`/api/workforce/renewals/${id}/history`],enabled:open});
  return <div><Button size="sm" variant="ghost" onClick={()=>setOpen(v=>!v)}>{open?'Hide renewal history':'Renewal history'}</Button>{open&&<><QueryError error={query.error}/>{query.data?.map(h=><div key={h.id} className="my-2 border-l-2 pl-3 text-sm"><p>Version {h.version} · {h.action} · {new Date(h.createdAt).toLocaleString()} · User #{h.actorId}</p><p>{h.reason}</p><p className="break-words">Evidence: {h.snapshot.reference}</p>{h.snapshot.note&&<p className="break-words">{h.snapshot.note}</p>}</div>)}</>}</div>;
}
function RenewalCard({row}:{row:RenewalView}){
  const [mode,setMode]=useState<'verify'|'return'|'resubmit'|'cancel'|null>(null),[reason,setReason]=useState(''),[reference,setReference]=useState(row.reference),[note,setNote]=useState(row.note),[documentId,setDocumentId]=useState(String(row.documentEvidence?.id||''));
  const [from,setFrom]=useState(''),[through,setThrough]=useState(''),[noExpiry,setNoExpiry]=useState(false);const save=useAction(()=>setMode(null));
  function begin(action:NonNullable<typeof mode>){setMode(action);setReason('');setReference(row.reference);setNote(row.note);setDocumentId(String(row.documentEvidence?.id||''));setThrough('');setNoExpiry(false);setFrom(row.previousValidThrough?new Date(Date.parse(row.previousValidThrough)+86400000).toISOString().slice(0,10):'');save.reset();}
  function submit(e:FormEvent){e.preventDefault();const common={version:row.version};
    if(mode==='resubmit')save.mutate({url:`/api/workforce/renewals/${row.id}/resubmit`,body:{...common,reference,note,documentId:documentId?Number(documentId):null}});
    else if(mode==='cancel')save.mutate({url:`/api/workforce/renewals/${row.id}/cancel`,body:{...common,reason}});
    else save.mutate({url:`/api/workforce/renewals/${row.id}/review`,body:mode==='verify'?{...common,decision:'verify',reason,validFrom:from,validThrough:noExpiry?null:through,verificationReference:reference}:{...common,decision:'return',reason}});
  }
  return <article className="space-y-3 rounded-lg border bg-card p-4"><div><h3 className="font-semibold">#{row.id} · {row.qualificationName} · {row.employeeName}</h3><p className="text-sm">{row.status} · Previous expiry: {row.previousValidThrough||'None'}{row.newCredentialId?` · New verification #${row.newCredentialId}`:''}</p></div><p className="break-words text-sm">Evidence: {row.reference}</p>{row.documentEvidence&&<div className="rounded bg-muted p-3 text-sm"><p>Certificate #{row.documentEvidence.id} · {row.documentEvidence.documentType} · Version {row.documentEvidence.version}</p><p>Valid {row.documentEvidence.issueDate} through {row.documentEvidence.expiryDate}</p><a className="text-primary underline" href={`/api/workforce/renewals/${row.id}/evidence/download`} target="_blank" rel="noopener noreferrer">Download submitted certificate</a></div>}{row.note&&<p className="break-words text-sm">{row.note}</p>}{row.reviewNote&&<p className="text-sm">HR response: {row.reviewNote}</p>}
    <div className="flex flex-wrap gap-2">{row.status==='submitted'&&row.canReview&&<><Button size="sm" onClick={()=>begin('verify')}>Verify renewal</Button><Button size="sm" variant="outline" onClick={()=>begin('return')}>Return for changes</Button></>}{row.status==='returned'&&<Button size="sm" onClick={()=>begin('resubmit')}>Update & resubmit</Button>}{['submitted','returned'].includes(row.status)&&<Button size="sm" variant="outline" onClick={()=>begin('cancel')}>Cancel request</Button>}</div><RenewalHistory id={row.id}/>
    <Dialog open={!!mode} onOpenChange={v=>{if(!v&&!save.isPending)setMode(null);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>{mode==='verify'?'Verify qualification renewal':mode==='return'?'Return renewal for changes':mode==='resubmit'?'Resubmit renewal':'Cancel renewal request'}</DialogTitle><DialogDescription>{row.employeeName} · {row.qualificationName}. Verification creates a new linked record and preserves the original. A different HR administrator must verify a request you submitted or your own qualification.</DialogDescription></DialogHeader><form onSubmit={submit}><fieldset disabled={save.isPending} className="space-y-3">
      {mode==='verify'&&<><Field label="Renewal valid from"><input className={fieldClass} type="date" value={from} onChange={e=>setFrom(e.target.value)} required/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={noExpiry} disabled={!!row.documentEvidence} onChange={e=>setNoExpiry(e.target.checked)}/>Verified certificate has no expiry</label>{!noExpiry&&<Field label="Renewal valid through"><input className={fieldClass} type="date" value={through} onChange={e=>setThrough(e.target.value)} required/></Field>}<p className="text-xs text-muted-foreground">Use the dates on the verified certificate. Overlap with the original is allowed. A gap in dates does not qualify the employee during that gap.</p></>}
      {(mode==='verify'||mode==='resubmit')&&<Field label={mode==='verify'?'HR verification reference':'Updated renewal evidence reference'}><textarea className={fieldClass} value={reference} onChange={e=>setReference(e.target.value)} minLength={5} maxLength={500} required/></Field>}
      {mode==='resubmit'&&<CertificatePicker credentialId={row.previousCredentialId} renewalId={row.id} value={documentId} onChange={setDocumentId}/>}{mode==='resubmit'?<Field label="Updated renewal note"><textarea className={fieldClass} value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></Field>:<Field label="Renewal decision reason"><textarea className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000} required/></Field>}
      <QueryError error={save.error}/><Button type="submit">{mode==='verify'?'Confirm HR verification':mode==='resubmit'?'Resubmit to HR':mode==='return'?'Return request':'Confirm cancellation'}</Button>
    </fieldset></form></DialogContent></Dialog>
  </article>;
}
export function QualificationRenewals({isAdmin}:{isAdmin:boolean}){
  const [duePage,setDuePage]=useState(1),[page,setPage]=useState(1),[status,setStatus]=useState('submitted');
  const due=useQuery<{total:number;rows:RenewalDue[];hasMore:boolean}>({queryKey:['/api/workforce/renewals/due',{page:duePage}],refetchInterval:60000});
  const requests=useQuery<{rows:RenewalView[];hasMore:boolean}>({queryKey:['/api/workforce/renewals',{page,status}],refetchInterval:60000});
  return <div className="space-y-5">{isAdmin&&<RenewalRules/>}<Section title={isAdmin?'Qualification renewal due list':'Your qualification renewals'}><p className="text-sm text-muted-foreground">{isAdmin?'Active employees with expiring or expired qualifications.':'Your expiring or expired qualifications.'} Only verified coverage clears an expiry reminder. Pending requests do not qualify an employee for work.</p><QueryError error={due.error}/>{due.isLoading?<p>Checking renewal dates…</p>:<><p className="font-medium">{due.data?.total||0} due</p><Table headers={['Employee / qualification','Expiry','Reminder','Action']} rows={(due.data?.rows||[]).map(r=>[`${r.employeeName} · ${r.qualificationName}`,r.validThrough,r.daysLeft<0?`Expired ${-r.daysLeft} days ago`:r.daysLeft===0?'Expires today':`${r.daysLeft} days left`,r.requestId?<span className="text-sm">Request #{r.requestId} · {r.requestStatus}</span>:r.renewedFrom?<span className="text-sm">Renewed from {r.renewedFrom}; check the coverage gap with HR</span>:<RenewalRequestButton credentialId={r.credentialId}/>])}/></>}
    {(duePage>1||due.data?.hasMore)&&<div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={duePage===1} onClick={()=>setDuePage(p=>p-1)}>Previous due</Button><span>Page {duePage}</span><Button size="sm" variant="outline" disabled={!due.data?.hasMore} onClick={()=>setDuePage(p=>p+1)}>Next due</Button></div>}</Section>
    <Section title="Renewal requests"><Field label="Renewal request status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="submitted">Awaiting HR verification</option><option value="returned">Returned for changes</option><option value="verified">Verified</option><option value="cancelled">Cancelled</option><option value="all">All requests</option></select></Field><QueryError error={requests.error}/>{requests.isLoading?<p>Loading requests…</p>:!requests.data?.rows.length?<p className="text-sm text-muted-foreground">No requests in this view.</p>:requests.data.rows.map(row=><RenewalCard key={`${row.id}-${row.version}`} row={row}/>)}{(page>1||requests.data?.hasMore)&&<div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous requests</Button><span>Page {page}</span><Button size="sm" variant="outline" disabled={!requests.data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next requests</Button></div>}</Section>
  </div>;
}
