import type { ReactNode } from 'react';
import type { LucideIcon } from 'lucide-react';
import { ArrowUpRight, Inbox } from 'lucide-react';
import { Link } from 'wouter';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, PieChart, Pie, Cell } from 'recharts';
import type { DashboardBreakdown } from '@shared/dashboard';

export const palette = ['#14b8a6', '#8b5cf6', '#f59e0b', '#f43f5e', '#38bdf8', '#a3a3a3'];
export const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
export const number = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 1 });
export const day = (value: string) => new Date(value.slice(0, 10) + 'T12:00:00Z').toLocaleDateString(undefined, { month: 'short', day: 'numeric', timeZone: 'UTC' });
export const moment = (value: string, timezone: string) => new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit', timeZone: timezone });
export const tooltipStyle = { background: 'hsl(var(--popover))', color: 'hsl(var(--popover-foreground))', border: '1px solid hsl(var(--border))', borderRadius: 12, fontSize: 12 };
export function Panel({ title, subtitle, icon: Icon, href, children, className = '', action }: { title: string; subtitle?: string; icon: LucideIcon; href?: string; children: ReactNode; className?: string; action?: ReactNode }) {
  return <section className={'min-w-0 rounded-2xl border bg-card shadow-sm ' + className}><header className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div className="flex min-w-0 items-center gap-3"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="h-4 w-4"/></span><div><h2 className="font-semibold">{title}</h2>{subtitle && <p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}</div></div>{action || (href && <Link href={href} className="inline-flex items-center gap-1 text-xs font-medium text-primary">Open<ArrowUpRight className="h-3.5 w-3.5"/><span className="sr-only"> {title}</span></Link>)}</header><div className="p-5">{children}</div></section>;
}
export function Empty({ text }: { text: string }) { return <div className="flex min-h-32 flex-col items-center justify-center gap-3 rounded-xl bg-muted/25 p-5 text-center"><Inbox className="h-7 w-7 text-muted-foreground/50"/><p className="max-w-sm text-sm text-muted-foreground">{text}</p></div>; }
export function Metric({ title, value, note, icon: Icon, href, tone = 'teal' }: { title: string; value: string | number; note: string; icon: LucideIcon; href: string; tone?: 'teal' | 'violet' | 'amber' | 'rose' }) {
  const tones = { teal: 'bg-teal-500/10 text-teal-600 dark:text-teal-300', violet: 'bg-violet-500/10 text-violet-600 dark:text-violet-300', amber: 'bg-amber-500/10 text-amber-700 dark:text-amber-300', rose: 'bg-rose-500/10 text-rose-600 dark:text-rose-300' };
  return <Link href={href} className="group min-w-0 rounded-2xl border bg-card p-4 shadow-sm transition-colors hover:border-primary/50"><div className="flex items-center justify-between gap-2"><span className={'rounded-xl p-2.5 ' + tones[tone]}><Icon className="h-5 w-5"/></span><ArrowUpRight className="h-4 w-4 text-muted-foreground transition-transform motion-safe:group-hover:-translate-y-0.5 motion-safe:group-hover:translate-x-0.5"/></div><strong className="mt-4 block truncate text-3xl font-semibold tracking-tight tabular-nums">{typeof value === 'number' ? number(value) : value}</strong><h2 className="mt-1 text-sm font-medium">{title}</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">{note}</p></Link>;
}
export function Progress({ value, total, text, color = palette[0] }: { value: number; total: number; text: string; color?: string }) { return <div><div className="mb-2 flex items-center justify-between gap-2 text-xs"><span>{text}</span><strong className="tabular-nums">{number(value)} / {number(total)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted" role="progressbar" aria-label={text} aria-valuemin={0} aria-valuemax={Math.max(total, 1)} aria-valuenow={Math.min(value, Math.max(total, 1))}><div className="h-full rounded-full" style={{ width: `${total ? Math.min(100, value / total * 100) : 0}%`, background: color }}/></div></div>; }
export function Pill({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <span className={'inline-flex rounded-full px-2.5 py-1 text-[11px] font-medium ' + (warning ? 'bg-amber-500/10 text-amber-700 dark:text-amber-300' : 'bg-primary/10 text-primary')}>{children}</span>; }
export function Distribution({ rows, empty = 'No records available yet.' }: { rows: DashboardBreakdown[]; empty?: string }) {
  const total = rows.reduce((sum, row) => sum + row.count, 0);
  if (!total) return <Empty text={empty}/>;
  return <div className="grid items-center gap-3 sm:grid-cols-[140px_1fr]"><div className="relative h-36" role="img" aria-label={rows.map(r => `${label(r.name)}: ${r.count}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={rows} dataKey="count" nameKey="name" innerRadius={43} outerRadius={63} paddingAngle={3} stroke="none" isAnimationActive={false}>{rows.map((r, i) => <Cell key={r.name} fill={palette[i % palette.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex items-center justify-center text-xl font-semibold">{number(total)}</div></div><div className="space-y-3">{rows.map((row, i) => <div key={row.name} className="flex items-center gap-2 text-xs"><span className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ background: palette[i % palette.length] }}/><span className="min-w-0 flex-1 truncate" title={label(row.name)}>{label(row.name)}</span><strong>{number(row.count)}</strong><span className="w-9 text-right text-muted-foreground">{Math.round(row.count / total * 100)}%</span></div>)}</div></div>;
}
export function AttendanceChart({ data }: { data: { date: string; present: number; late: number; absent: number; onLeave: number }[] }) {
  if (!data.some(row => row.present + row.late + row.absent + row.onLeave)) return <Empty text="Attendance trends will appear when time records are added for this period."/>;
  return <><div className="h-64 w-full" role="img" aria-label="Daily recorded attendance, stacked by present, late, absent and leave"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} accessibilityLayer margin={{ top: 10, right: 0, left: -25, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="date" tickFormatter={day} tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} axisLine={false} tickLine={false} minTickGap={28}/><YAxis allowDecimals={false} tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} labelFormatter={v => day(String(v))}/><Legend iconType="circle" wrapperStyle={{ fontSize: 11, paddingTop: 12 }}/>{[{ key: 'present', name: 'Present', color: palette[0] }, { key: 'late', name: 'Late', color: palette[2] }, { key: 'absent', name: 'Recorded absent', color: palette[3] }, { key: 'onLeave', name: 'Leave', color: palette[1] }].map(s => <Bar key={s.key} dataKey={s.key} name={s.name} fill={s.color} stackId="attendance" maxBarSize={28} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></div><details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">View daily figures</summary><div className="mt-3 max-h-48 overflow-auto"><table className="w-full text-left"><thead><tr><th className="p-2">Day</th><th>Present</th><th>Late</th><th>Absent</th><th>Leave</th></tr></thead><tbody>{data.map(row => <tr key={row.date} className="border-t"><td className="p-2">{day(row.date)}</td><td>{row.present}</td><td>{row.late}</td><td>{row.absent}</td><td>{row.onLeave}</td></tr>)}</tbody></table></div></details></>;
}
