import { useQuery } from '@tanstack/react-query';
import { MessageCircle, Megaphone, ArrowUpRight, Pin } from 'lucide-react';
import { Link } from 'wouter';
import type { BulletinView, HubSummary } from '@shared/communications';
import { Panel, Empty, day, Pill } from './DashboardParts';

export default function DashboardCommunication({ autoRefresh = true }: { autoRefresh?: boolean }) {
  const summary = useQuery<HubSummary>({ queryKey: ['/api/communications/summary'], refetchInterval: autoRefresh ? 30000 : false, refetchIntervalInBackground: false });
  const notices = useQuery<{ items: BulletinView[] }>({ queryKey: ['/api/communications/bulletins?managed=false&filter=all&offset=0'], refetchInterval: autoRefresh ? 60000 : false, refetchIntervalInBackground: false });
  return <Panel title="Team updates" subtitle="Your conversations and published notices" icon={Megaphone} href="/communications"><div className="mb-4 grid grid-cols-3 gap-2">{[{ title: 'Unread chats', value: summary.data?.unreadConversations }, { title: 'Mentions', value: summary.data?.mentions }, { title: 'To acknowledge', value: summary.data?.pendingAcknowledgements }].map(item => <Link href="/communications" key={item.title} className="rounded-xl bg-muted/40 p-3"><strong className="block text-xl">{summary.error ? '—' : item.value ?? '…'}</strong><span className="text-[11px] text-muted-foreground">{item.title}</span></Link>)}</div>{summary.error && <p className="mb-3 text-xs text-muted-foreground">Communication counts are unavailable. Open the Hub to reconnect.</p>}{notices.error ? <Empty text="Notices are unavailable right now. Open the Communication Hub to try again."/> : notices.isLoading ? <p className="text-sm text-muted-foreground">Loading notices…</p> : !notices.data?.items.length ? <Empty text="Published notices addressed to you will appear here."/> : <div className="divide-y">{notices.data.items.slice(0, 4).map(b => <Link key={b.id} href="/communications" className="block py-3 first:pt-0"><div className="mb-1 flex items-center gap-2 text-[11px] text-muted-foreground">{b.pinned && <Pin className="h-3 w-3 text-primary"/>}<span className="truncate">{b.audience_label}</span><span className="ml-auto shrink-0">{day(b.publish_at)}</span></div><h3 className="text-sm font-semibold">{b.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{b.body}</p>{b.requires_acknowledgement && !b.acknowledged_at && <div className="mt-2"><Pill warning>Acknowledgement needed</Pill></div>}</Link>)}</div>}<Link href="/communications" className="mt-4 flex items-center justify-between rounded-xl bg-primary/10 p-3 text-xs font-medium text-primary"><span className="flex items-center gap-2"><MessageCircle className="h-4 w-4"/>Open team chat & action inbox</span><ArrowUpRight className="h-4 w-4"/></Link></Panel>;
}
