import {ExperienceHero,AnimatedIcon,MiniTrend} from '@/components/ux/ExperienceUI';
import {HelpDisclosure} from '@/components/ux/WorkspaceUI';
import { useState, useId } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'wouter';
import { Users, Clock3, CalendarDays, FileCheck2, GraduationCap, Wallet, MapPin, RefreshCw, SlidersHorizontal, ArrowUpRight, AlertCircle, CheckCircle2, Building2, LayoutGrid, Megaphone, BriefcaseBusiness, TrendingUp, CalendarClock } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import { useAuth } from '@/contexts/AuthContext';
import { usePageAccess } from '@/hooks/usePageAccess';
import { Button } from '@/components/ui/button';
import { getAccessScope, canAccessModule } from '@shared/permissions';
import { roleLabel } from '@shared/navigation';
import type { DashboardOverview } from '@shared/dashboard';
import { Panel, Metric, Empty, Progress, Distribution, AttendanceChart, Pill, palette, number, label, day, moment, tooltipStyle } from './DashboardParts';
import DashboardCommunication from './DashboardCommunication';

const sections = [{ id: 'attendance', name: 'Attendance trends' }, { id: 'people', name: 'People & departments' }, { id: 'workforce', name: 'Teams & shift coverage' }, { id: 'leave', name: 'Leave calendar' }, { id: 'documents', name: 'Document deadlines' }, { id: 'learning', name: 'Learning & training' }, { id: 'payroll', name: 'Payroll overview' }, { id: 'updates', name: 'Team updates' }];
const money = (value: string | number) => Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function WorkspaceDashboard() {
  const { user } = useAuth(), { pages } = usePageAccess(), cache = useQueryClient();
  const [days, setDays] = useState('30'), [auto, setAuto] = useState(true), [customize, setCustomize] = useState(false), [hidden, setHidden] = useState<string[]>([]);
  const self = !!user && ['employee', 'permanent_employee', 'temporary_staff', 'contract_employee'].includes(user.role);
  const query = useQuery<DashboardOverview>({ queryKey: [`/api/dashboard/overview?days=${days}`], staleTime: 30000, refetchInterval: auto ? 60000 : false, refetchIntervalInBackground: false });
  const data = query.error ? undefined : query.data;
  const hasHub = !!user && canAccessModule(user.role, 'communication_hub');
  const shown = (id: string) => !hidden.includes(id);
  const scope = user ? getAccessScope(user.role, 'employee_database') : 'none';
  const scopeLabel = self ? 'Your personal workspace' : scope === 'all' ? 'Organization overview' : scope === 'department' ? `${user?.department || 'Your department'} overview` : scope === 'team' ? 'Your team overview' : 'Your role overview';
  const refresh = () => { void query.refetch(); void cache.invalidateQueries({ predicate: q => ['/api/employee/dashboard', '/api/communications/summary', '/api/communications/bulletins?managed=false&filter=all&offset=0'].includes(String(q.queryKey[0])) }); };
  const attention = data ? [
    ...(data.leave ? [{ title: 'Leave requests', value: data.leave.pending, note: 'Pending in your scope', href: '/leave', Icon: CalendarDays }] : []),
    ...(data.documents ? [{ title: 'Document deadlines', value: data.documents.expired + data.documents.expiring, note: `${data.documents.expired} expired · ${data.documents.expiring} expiring`, href: '/documents', Icon: FileCheck2 }] : []),
    ...(data.learning ? [{ title: 'Overdue learning', value: data.learning.overdue, note: 'Active enrollments past their due date', href: '/learning', Icon: GraduationCap }] : []),
    ...(data.workforce?.teams ? [{ title: 'Open shift places', value: data.workforce.gaps, note: 'Upcoming shifts · next 7 days', href: '/workforce', Icon: MapPin }] : []),
    ...(data.attendance ? [{ title: 'Attendance reviews', value: data.attendance.pending, note: `Pending records · last ${data.days * 2} days`, href: '/attendance', Icon: Clock3 }] : []),
    ...(data.payroll ? [{ title: 'Payroll in review', value: data.payroll.statuses.find(r => r.name === 'submitted')?.count || 0, note: 'Current payroll month', href: '/payroll', Icon: Wallet }] : []),
  ].filter(item => item.value > 0) : [];
  const availableSections = sections.filter(s => s.id === 'updates' ? hasHub : s.id === 'people' ? !!data?.people && !self : !!data?.[s.id as keyof DashboardOverview]);
  return <div className="space-y-6 pb-10">
    <ExperienceHero eyebrow={scopeLabel} title={`Your day${user?.firstName ? `, ${user.firstName}` : ''}.`} description={data ? new Date(data.today+'T12:00:00Z').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',timeZone:'UTC'}) : 'Everything you need, together.'} actions={<>{pages.some(p=>p.href==='/workforce')&&<Button asChild><Link href="/workforce"><CalendarClock className="h-4 w-4"/>Plan the day</Link></Button>}{hasHub&&<Button asChild variant="outline"><Link href="/communications"><Megaphone className="h-4 w-4"/>Team hub</Link></Button>}</>}>{data&&<div className="hero-dashboard-aside">{data.attendance&&<MiniTrend values={data.attendance.trend.map(row=>row.present+row.late+row.absent+row.onLeave)} label="Attendance activity"/>}<a href="#dashboard-priorities" className="hero-focus"><span className="hero-focus-icon"><AnimatedIcon icon={attention.length?AlertCircle:CheckCircle2}/></span><strong>{attention.length}</strong><span>{attention.length?'areas need attention':'priority flags'}</span><small>View priorities <ArrowUpRight className="h-3.5 w-3.5"/></small></a></div>}</ExperienceHero>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap items-center gap-3"><div className="flex rounded-xl border bg-card p-1" role="group" aria-label="Dashboard trend period">{['7', '30', '90'].map(value => <button key={value} aria-pressed={days === value} onClick={() => setDays(value)} className={'rounded-lg px-3 py-2 text-xs font-medium ' + (days === value ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted')}>{value} days</button>)}</div><span className="text-xs text-muted-foreground">Trend period{data ? `: ${day(data.from)} – ${day(data.today)}` : ''}</span></div><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={auto} onChange={e => setAuto(e.target.checked)}/>Auto-refresh</label><Button size="sm" variant="outline" aria-expanded={customize} onClick={() => setCustomize(!customize)}><SlidersHorizontal className="mr-2 h-4 w-4"/>Sections</Button><Button size="icon" variant="outline" aria-label="Refresh dashboard" disabled={query.isFetching} onClick={refresh}><RefreshCw className={'h-4 w-4 ' + (query.isFetching ? 'animate-spin' : '')}/></Button></div></div>
    {customize && <section className="rounded-2xl border bg-card p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Choose what you see</h2><p className="mt-1 text-xs text-muted-foreground">Adjust this view for your current session. Summary cards and priorities stay visible.</p></div><Button size="sm" variant="ghost" onClick={() => setHidden([])}>Show all</Button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{availableSections.map(s => <label key={s.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={shown(s.id)} onChange={e => setHidden(e.target.checked ? hidden.filter(id => id !== s.id) : [...hidden, s.id])}/>{s.name}</label>)}</div></section>}
    {query.isLoading && <div role="status" aria-label="Loading dashboard" className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Array.from({ length: 8 }, (_, i) => <div key={i} className="h-40 animate-pulse rounded-2xl border bg-muted/40"/>)}</div>}
    {query.error && <div role="alert" className="flex flex-wrap items-center gap-3 rounded-2xl border border-destructive/30 bg-destructive/5 p-5"><AlertCircle className="h-5 w-5 text-destructive"/><p className="flex-1 text-sm">The dashboard could not refresh. Please try again.</p><Button variant="outline" onClick={refresh}>Retry</Button></div>}
    {data && <>
      {!!data.unavailable.length && <p role="status" className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-sm">Some sections are temporarily unavailable: {data.unavailable.map(label).join(', ')}. Other sections remain available; refresh to try again.</p>}
      <div className="dashboard-metrics grid grid-cols-2 gap-3 xl:grid-cols-4">
        {data.people && !self && <Metric title="People" value={data.people.active} note={`${data.people.total} employee records · ${data.people.joined} joined in period`} icon={Users} href="/employees"/>}
        {data.attendance && <Metric title={self ? 'Recorded work hours' : 'At work today'} value={self ? number(data.attendance.minutes / 60) : data.attendance.today} note={self ? `Last ${days} days · ${number(data.attendance.overtime / 60)} overtime hours` : `${data.attendance.working} still clocked in today`} icon={Clock3} href="/attendance"/>}
        {data.leave && <Metric title={self ? 'Pending leave requests' : 'On leave'} value={self ? data.leave.pending : data.leave.away} note={self ? 'Awaiting the leave workflow' : `${data.leave.pending} pending requests · today's date ranges`} icon={CalendarDays} href="/leave" tone="violet"/>}
        {data.workforce && !self && <Metric title="Teams & venues" value={data.workforce.teams} note={`${data.workforce.shifts} shifts start in the next 7 days`} icon={Building2} href="/workforce" tone="violet"/>}
        {data.documents && <Metric title="Documents due" value={data.documents.expired + data.documents.expiring} note={`${data.documents.expired} expired · next ${data.expiryDays} days for expiry`} icon={FileCheck2} href="/documents" tone="amber"/>}
        {data.learning && <Metric title="Learning" value={data.learning.active} note={`${data.learning.overdue} overdue · ${data.learning.completed} completed in period`} icon={GraduationCap} href="/learning" tone="violet"/>}
        {data.workforce && (data.workforce.teams > 0 || self) && <Metric title={self ? 'Upcoming shift offers' : 'Open shift places'} value={self ? data.workforce.own.filter(s => s.status === 'offered').length : data.workforce.gaps} note={self ? 'Among your next 6 assignments · 30 days' : 'Required places without an accepted assignment · 7 days'} icon={MapPin} href="/workforce" tone="amber"/>}
        {data.payroll && <Metric title="Payroll recorded" value={data.payroll.statuses.find(s => s.name === 'processed')?.count || 0} note={`Payroll month ${data.today.slice(0, 7)} · within your access`} icon={Wallet} href="/payroll"/>}
      </div>
      {self && <PersonalOverview autoRefresh={auto}/>}
      <div id="dashboard-priorities" className="scroll-mt-5"><Panel title="Your next moves" subtitle="Priorities in your scope" icon={AlertCircle}><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{attention.length ? attention.map(item => <Link key={item.title} href={item.href} className="flex items-center gap-3 rounded-xl border p-3 hover:bg-muted/40"><span className="rounded-lg bg-amber-500/10 p-2 text-amber-600 dark:text-amber-300"><item.Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1"><strong className="block text-sm">{item.title}</strong><span className="text-xs text-muted-foreground">{item.note}</span></span><strong className="text-lg tabular-nums">{number(item.value)}</strong><ArrowUpRight className="h-4 w-4 text-muted-foreground"/></Link>) : <div className="flex items-center gap-3 rounded-xl bg-primary/5 p-4 sm:col-span-2 xl:col-span-3"><CheckCircle2 className="h-6 w-6 text-primary"/><div><p className="text-sm font-medium">No flags in the loaded summaries</p><p className="mt-1 text-xs text-muted-foreground">Check your team hub and individual modules for assigned tasks.</p></div></div>}</div></Panel></div>
      <div className="grid items-start gap-5 xl:grid-cols-3">
        {data.attendance && shown('attendance') && <Panel title="Attendance trends" subtitle={`Recorded attendance · last ${days} days`} icon={TrendingUp} href="/attendance" className="xl:col-span-2"><div className="mb-5 grid grid-cols-3 gap-3">{[{ title: 'Recorded hours', value: number(data.attendance.minutes / 60) }, { title: 'Overtime hours', value: number(data.attendance.overtime / 60) }, { title: `Previous ${days} days · hours`, value: number(data.attendance.previousMinutes / 60) }].map(item => <div key={item.title} className="rounded-xl bg-muted/40 p-3"><strong className="block text-xl tabular-nums">{item.value}</strong><span className="text-[11px] text-muted-foreground">{item.title}</span></div>)}</div><AttendanceChart data={data.attendance.trend}/><HelpDisclosure title="About these figures"><p>Shows saved attendance records, including records pending review. A missing record is not counted as an absence. Payroll uses its own approved calculations.</p></HelpDisclosure></Panel>}
        {hasHub && shown('updates') && <DashboardCommunication autoRefresh={auto}/>}
        {data.people && !self && shown('people') && <Panel title="People at a glance" subtitle="Currently active employees in your scope" icon={Users} href="/employees"><Distribution rows={data.people.types}/><h3 className="mb-3 mt-5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Department distribution</h3><div className="max-h-64 space-y-4 overflow-y-auto pr-1">{data.people.departments.map(row => <Progress key={row.name} text={row.name} value={row.count} total={data.people!.active}/>)}{!data.people.departments.length && <p className="text-sm text-muted-foreground">No active department records.</p>}</div></Panel>}
        {data.workforce && shown('workforce') && (data.workforce.teams > 0 || !self) && <Panel title="FEC, mall & event operations" subtitle="Managed teams · shifts starting in the next 7 days" icon={Building2} href="/workforce" className="xl:col-span-2"><div className="mb-5 grid gap-5 sm:grid-cols-2"><div className="space-y-4"><Progress text="Accepted staffing places" value={data.workforce.accepted} total={data.workforce.required}/><div className="flex flex-wrap gap-2"><Pill>{data.workforce.shifts} shifts</Pill><Pill warning={data.workforce.gaps > 0}>{data.workforce.gaps} open places</Pill></div></div><div className="grid grid-cols-2 gap-2">{data.workforce.breakdown.map(row => <div className="rounded-lg bg-muted/40 p-2.5 text-xs" key={row.name}><strong className="mr-2 text-base">{row.count}</strong>{label(row.name)}</div>)}</div></div>{data.workforce.upcoming.length ? <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-muted-foreground"><tr><th className="pb-3 pr-3 font-medium">Team / shift</th><th className="pb-3 pr-3 font-medium">Starts at site</th><th className="pb-3 font-medium">Coverage</th></tr></thead><tbody>{data.workforce.upcoming.map(s => <tr key={s.id} className="border-t"><td className="py-3 pr-3"><Link href="/workforce" className="font-semibold hover:text-primary">{s.team}</Link><p className="mt-1 text-muted-foreground">{s.role} · {s.site}</p></td><td className="py-3 pr-3"><p>{moment(s.start, s.timezone)}</p><span className="text-[10px] text-muted-foreground">{s.timezone}</span></td><td className="min-w-24 py-3"><Pill warning={s.accepted < s.required}>{s.accepted} / {s.required} filled</Pill></td></tr>)}</tbody></table></div> : <Empty text="No scheduled shifts start within the next 7 days. Open Workforce to plan the next roster."/>}{pages.some(p => p.href === '/org-charts') && <Link href="/org-charts" className="mt-4 inline-flex items-center gap-2 text-xs font-medium text-primary">Manage team hierarchy<ArrowUpRight className="h-3.5 w-3.5"/></Link>}</Panel>}
        {data.workforce && shown('workforce') && (self || data.workforce.own.length > 0) && <Panel title="Your upcoming shifts" subtitle="Next 6 assignments within 30 days" icon={BriefcaseBusiness} href="/workforce">{data.workforce.own.length ? <div className="divide-y">{data.workforce.own.map(s => <Link href="/workforce" key={s.id} className="block py-3 first:pt-0"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold">{s.team}</h3><Pill warning={s.status === 'offered'}>{label(s.status)}</Pill></div><p className="mt-1 text-xs text-muted-foreground">{s.role} · {s.site}</p><p className="mt-2 text-xs">{moment(s.start, s.timezone)} · {s.timezone}</p></Link>)}</div> : <Empty text="Your offered and accepted shifts will appear here."/>}</Panel>}
        {data.leave && shown('leave') && <Panel title={self ? 'Your leave' : 'Leave overview'} subtitle={`Requests overlapping ${day(data.from)} – ${day(data.today)}`} icon={CalendarDays} href="/leave"><Distribution rows={data.leave.statuses}/><h3 className="mb-2 mt-5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Current & upcoming approved leave</h3>{data.leave.upcoming.length ? <div className="divide-y">{data.leave.upcoming.map(r => <Link key={r.id} href="/leave" className="flex items-start gap-3 py-3"><span className="min-w-0 flex-1"><strong className="text-sm">{r.name}</strong><span className="mt-1 block text-xs text-muted-foreground">{day(r.start)} – {day(r.end)} · {label(r.type)}</span></span><Pill>{number(r.days)} days</Pill></Link>)}</div> : <p className="py-4 text-sm text-muted-foreground">No upcoming approved leave.</p>}<HelpDisclosure title="About these figures"><p>Half days keep their recorded units. Date-range counts do not imply a full day away.</p></HelpDisclosure></Panel>}
        {data.documents && shown('documents') && <Panel title="Document readiness" subtitle={`Active records · expiry window ${data.expiryDays} days`} icon={FileCheck2} href="/documents"><Distribution rows={[{ name: 'Beyond expiry window', count: data.documents.healthy }, { name: 'Expiring soon', count: data.documents.expiring }, { name: 'Expired', count: data.documents.expired }]}/><h3 className="mb-2 mt-5 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Earliest deadlines</h3>{data.documents.upcoming.length ? <div className="divide-y">{data.documents.upcoming.map(r => <Link href="/documents" key={r.id} className="flex items-center gap-3 py-3"><span className="min-w-0 flex-1"><strong className="block text-sm">{r.name}</strong><span className="text-xs text-muted-foreground">{label(r.type)}</span></span><span className="text-right"><span className="block text-xs">{day(r.date)}</span><span className={'text-[11px] ' + (r.date < data.today ? 'text-rose-600 dark:text-rose-300' : 'text-amber-700 dark:text-amber-300')}>{r.date < data.today ? 'Expired' : 'Due soon'}</span></span></Link>)}</div> : <p className="py-4 text-sm text-muted-foreground">No document deadlines within the configured window.</p>}<HelpDisclosure title="About these figures"><p>Archived documents are excluded. Expiry dates alone do not confirm overall compliance.</p></HelpDisclosure></Panel>}
        {data.learning && shown('learning') && <Panel title="Learning & development" subtitle={`${data.learning.completed} completions during the selected period`} icon={GraduationCap} href="/learning"><div className="mb-5 grid grid-cols-3 gap-2">{[{ text: 'Active', count: data.learning.active }, { text: 'Overdue', count: data.learning.overdue }, { text: 'Awaiting review', count: data.learning.awaiting }].map(s => <div key={s.text} className="rounded-xl bg-muted/40 p-3"><strong className="block text-xl">{s.count}</strong><span className="text-[11px] text-muted-foreground">{s.text}</span></div>)}</div>{data.learning.upcoming.length ? <div className="space-y-5">{data.learning.upcoming.map(r => <div key={r.id}><Link href="/learning" className="text-sm font-semibold hover:text-primary">{r.title}</Link><p className="mb-2 mt-1 text-xs text-muted-foreground">{r.name} · {r.date ? `Due ${day(r.date)}` : 'No due date set'}</p><Progress text="Course progress" value={r.progress} total={100} color={r.date && r.date < data.today ? palette[2] : palette[1]}/></div>)}</div> : <Empty text="No active learning enrollments in your scope."/>}</Panel>}
        {data.payroll && shown('payroll') && <PayrollPanel payroll={data.payroll} today={data.today}/>}
        {data.people && !self && shown('people') && <Panel title="New team members" subtitle={`Joined during the last ${days} days`} icon={Users} href="/employees">{data.people.recent.length ? <div className="divide-y">{data.people.recent.map(r => <Link href="/employees" key={r.id} className="flex items-center gap-3 py-3 first:pt-0"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-semibold text-primary">{r.name.split(' ').filter(Boolean).slice(0, 2).map(n => n[0]).join('')}</span><span className="min-w-0 flex-1"><strong className="block text-sm">{r.name}</strong><span className="text-xs text-muted-foreground">{r.position} · {r.department}</span></span><span className="text-xs text-muted-foreground">{day(r.date)}</span></Link>)}</div> : <Empty text="No joining dates fall within the selected period."/>}</Panel>}
      </div>
      <Panel title="Your modules" subtitle="Jump directly into the work you need" icon={LayoutGrid}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{pages.filter(p => !['/', '/account'].includes(p.href)).map(p => <Link key={p.href} href={p.href} className="flex items-center justify-between gap-2 rounded-lg border px-3 py-2.5 text-xs hover:border-primary/40 hover:bg-primary/5"><span>{p.label}</span><ArrowUpRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground"/></Link>)}</div></Panel>
      <footer className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>Updated {new Date(data.generatedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}{auto ? ' · Refreshes every minute while this page is active' : ' · Automatic dashboard refresh paused'}</span><span>Each module uses its own role and team access scope.</span></footer>
    </>}
  </div>;
}

function PayrollPanel({ payroll, today }: { payroll: NonNullable<DashboardOverview['payroll']>; today: string }) {
  const chartId = 'payroll-'+useId().replaceAll(':','');
  const currencies = [...new Set([...payroll.totals.map(r => r.currency), ...payroll.trend.map(r => r.currency)])];
  const [chosen, setChosen] = useState('');
  const currency = currencies.includes(chosen) ? chosen : currencies[0] || '';
  const current = payroll.totals.find(row => row.currency === currency);
  const trend = Array.from({ length: 6 }, (_, i) => { const month = new Date(Date.UTC(Number(today.slice(0, 4)), Number(today.slice(5, 7)) - 6 + i, 1)).toISOString().slice(0, 7); return { month, total: Number(payroll.trend.find(r => r.month === month && r.currency === currency)?.total || 0) }; });
  return <Panel title="Payroll overview" subtitle={`Current payroll month ${today.slice(0, 7)} · processed trend over 6 months`} icon={Wallet} href="/payroll" className="xl:col-span-2">{!currencies.length ? <Empty text="Payroll figures appear once records have been generated within your access scope."/> : <><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-5"><div><p className="text-xs text-muted-foreground">Processed · {currency}</p><strong className="text-2xl">{money(current?.processed || '0')}</strong></div><div><p className="text-xs text-muted-foreground">Awaiting processing · {currency}</p><strong className="text-2xl">{money(current?.awaiting || '0')}</strong></div></div><label className="text-xs text-muted-foreground">Currency<select aria-label="Payroll chart currency" className="ml-2 rounded-lg border bg-background px-3 py-2 text-foreground" value={currency} onChange={e => setChosen(e.target.value)}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label></div><div className="h-52" role="img" aria-label={`Processed net payroll per month in ${currency}`}><ResponsiveContainer width="100%" height="100%"><BarChart data={trend} accessibilityLayer margin={{ top: 10, left: 0, right: 5, bottom: 0 }}><defs><linearGradient id={chartId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a87aff"/><stop offset="100%" stopColor="#6634ca" stopOpacity={0.65}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="month" tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} axisLine={false} tickLine={false}/><YAxis tickFormatter={n => Number(n).toLocaleString(undefined, { notation: 'compact' })} tick={{ fontSize: 10, fill: 'hsl(var(--muted-foreground))' }} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v => [money(Number(v)), currency]}/><Bar dataKey="total" name="Processed net pay" fill={`url(#${chartId})`} radius={[5, 5, 0, 0]} maxBarSize={40} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><details className="mt-3 text-xs text-muted-foreground"><summary className="cursor-pointer">View monthly figures</summary><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{trend.map(row => <div key={row.month} className="rounded-lg bg-muted/40 p-2">{row.month}<strong className="mt-1 block text-foreground">{money(row.total)} {currency}</strong></div>)}</div></details></>}<div className="mt-4 flex flex-wrap gap-2">{payroll.statuses.map(row => <Pill key={row.name} warning={['failed', 'submitted'].includes(row.name)}>{label(row.name)}: {row.count}</Pill>)}</div><HelpDisclosure title="About these figures"><p>Currencies remain separate. Figures use each record's payroll month, not the trend-period selector. Pay dates and salary periods follow the saved payroll rules.</p></HelpDisclosure></Panel>;
}

function PersonalOverview({ autoRefresh }: { autoRefresh: boolean }) {
  const { pages } = usePageAccess();
  const query = useQuery<{ attendance: { checkIn: string | null; checkOut: string | null } | null; leaves: { available: number | null; used: number; pending: number }; payroll: { month: number; year: number; netSalary: string; currency: string | null } | null }>({ queryKey: ['/api/employee/dashboard'], refetchInterval: autoRefresh ? 60000 : false, refetchIntervalInBackground: false });
  if (query.error) return <p className="rounded-xl border bg-card p-4 text-sm text-muted-foreground">Your personal summary is unavailable. HR may need to link your account to an employee record.</p>;
  if (!query.data) return <p className="text-sm text-muted-foreground">Loading your personal summary…</p>;
  const d = query.data, allowed = (href: string) => pages.some(p => p.href === href);
  return <div className="grid gap-3 md:grid-cols-3">{allowed('/attendance') && <Metric title="Today's time clock" value={d.attendance?.checkOut ? 'Clocked out' : d.attendance?.checkIn ? 'Clocked in' : 'Not clocked in'} note={d.attendance?.checkIn ? `Started ${new Date(d.attendance.checkIn).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` : 'Open Attendance to record your work'} icon={Clock3} href="/attendance"/>}{allowed('/leave') && <Metric title="Available leave days" value={d.leaves.available === null ? 'Not configured' : number(d.leaves.available)} note={`${number(d.leaves.used)} approved days this year · ${d.leaves.pending} pending`} icon={CalendarDays} href="/leave" tone="violet"/>}{allowed('/payroll') && <Metric title="Latest recorded payment" value={d.payroll ? money(d.payroll.netSalary) : 'No payment yet'} note={d.payroll ? `${d.payroll.currency || 'Currency unspecified'} · ${d.payroll.month}/${d.payroll.year}` : 'Your recorded payroll will appear here'} icon={Wallet} href="/payroll"/>}</div>;
}
