import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, CheckCheck, Eye, Users, CalendarClock, FileEdit, Send, Archive, Pin, ShieldCheck, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Field, QueryError, fieldClass } from '@/components/hr/Operations';
import type { BulletinView, BulletinRecipient, HubContext } from '@shared/communications';
import { hub, useHubAction, useDebounced, Pager, dateLabel, type Page } from './HubControls';
import { FilterPills, NoticeStage } from './NoticeVisuals';
import AnnouncementEditor from './AnnouncementEditor';

export default function AnnouncementDetail({ id, context, onClose }: { id: number; context: HubContext; onClose: () => void }) {
  const [edit, setEdit] = useState(false), [tab, setTab] = useState('notice');
  const [confirm, setConfirm] = useState<'publish' | 'archive' | 'pin' | null>(null), [why, setWhy] = useState(''), [reviewed, setReviewed] = useState(false);
  const query = useQuery<BulletinView>({ queryKey: [`${hub}/bulletins/${id}`], refetchInterval: 30000, refetchIntervalInBackground: false });
  const b = query.data;
  const action = useHubAction(() => { setConfirm(null); setWhy(''); setReviewed(false); });
  const estimate = useQuery<{ eligible: number }>({ queryKey: [`${hub}/bulletins/audience-preview?audience=${b?.audience}&target=${encodeURIComponent(b?.target || '')}`], enabled: confirm === 'publish' && !!b?.can_manage, staleTime: 0 });
  if (query.error || !b) return <div className="space-y-4"><Button variant="outline" onClick={onClose}><ArrowLeft className="mr-2 h-4 w-4"/>Back to announcements</Button><QueryError error={query.error}/>{query.isLoading && <p role="status">Opening announcement…</p>}</div>;
  if (edit && b.can_manage && b.status === 'draft') return <AnnouncementEditor value={b} context={context} onCancel={() => setEdit(false)} onDone={() => setEdit(false)}/>;
  const openConfirmation = (kind: typeof confirm) => { setConfirm(kind); setWhy(''); setReviewed(false); action.reset(); };
  const scheduled = new Date(b.publish_at) > new Date();
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><Button variant="outline" onClick={onClose}><ArrowLeft className="mr-2 h-4 w-4"/>Back to announcements</Button><div className="flex gap-2"><NoticeStage stage={b.stage}/>{b.pinned && <Badge variant="secondary"><Pin className="mr-1 h-3 w-3"/>Pinned</Badge>}</div></div>
    <div className="rounded-2xl border bg-card p-5 sm:p-6"><h2 className="break-words text-2xl font-semibold">{b.title}</h2><p className="mt-2 text-sm text-muted-foreground">{b.author_name} · Version {b.version}</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-primary"/>{b.audience_label}</span><span className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-primary"/>{dateLabel(b.publish_at)}</span>{b.expires_at && <span className="text-muted-foreground">Expires {dateLabel(b.expires_at)}</span>}</div></div>
    {b.can_manage && <FilterPills label="Announcement view" value={tab} onChange={setTab} items={[{ value: 'notice', label: 'Notice & publishing' }, { value: 'recipients', label: 'Recipient tracker' }]}/>}
    <QueryError error={action.error}/>
    {tab === 'recipients' && b.can_manage ? <Recipients bulletin={b}/> : <div className={`grid gap-5 ${b.can_manage ? 'xl:grid-cols-[minmax(0,1fr)_300px]' : ''}`}>
      <div className="space-y-4"><article className="whitespace-pre-wrap break-words rounded-2xl border bg-card p-5 text-sm leading-7 [overflow-wrap:anywhere] sm:p-6">{b.body}</article>
        {b.addressed_to_me && <section className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex gap-3"><ShieldCheck className="mt-1 h-6 w-6 shrink-0 text-primary"/><div><h3 className="font-semibold">{b.acknowledged_at ? 'Your acknowledgement is recorded' : b.requires_acknowledgement ? 'Please read and acknowledge' : b.read_at ? 'Marked as read' : 'Have you read this notice?'}</h3><p className="mt-1 text-sm text-muted-foreground">{b.requires_acknowledgement ? 'First mark the notice read, then confirm that you received it.' : 'Keep your announcement list up to date when you finish reading.'}</p></div></div>
          <div className="flex flex-wrap gap-3"><Button variant="outline" disabled={!!b.read_at || action.isPending} onClick={() => action.mutate({ path: `/bulletins/${id}/read`, body: {} })}><Eye className="mr-2 h-4 w-4"/>{b.read_at ? 'Read ✓' : 'Mark as read'}</Button>{b.requires_acknowledgement && <Button disabled={!b.read_at || !!b.acknowledged_at || action.isPending} onClick={() => action.mutate({ path: `/bulletins/${id}/acknowledge`, body: {} })}><CheckCheck className="mr-2 h-4 w-4"/>{b.acknowledged_at ? 'Acknowledged ✓' : 'I acknowledge this notice'}</Button>}</div>
          {b.acknowledged_at && <p className="text-xs text-muted-foreground">Recorded {dateLabel(b.acknowledged_at)}</p>}{b.requires_acknowledgement && <p className="text-xs text-muted-foreground">Acknowledgement confirms receipt of this exact notice. It does not approve an HR request or agreement.</p>}
        </section>}
      </div>
      {b.can_manage && <aside className="h-fit space-y-4 rounded-2xl border bg-card p-5"><h3 className="font-semibold">Publishing controls</h3><p className="text-sm text-muted-foreground">{b.status === 'draft' ? 'Review the wording, recipients and timing before publishing.' : 'Published wording is preserved. Create a new notice for corrections.'}</p>
        {b.status === 'draft' && <><Button className="w-full justify-start gap-2" variant="outline" onClick={() => setEdit(true)}><FileEdit className="h-4 w-4"/>Edit draft</Button><Button className="w-full justify-start gap-2" onClick={() => openConfirmation('publish')}><Send className="h-4 w-4"/>{scheduled ? 'Schedule publication' : 'Publish notice'}</Button></>}
        {b.status !== 'archived' && <><Button variant="outline" className="w-full justify-start gap-2" onClick={() => openConfirmation('pin')}><Pin className="h-4 w-4"/>{b.pinned ? 'Unpin notice' : 'Pin notice'}</Button><Button variant="outline" className="w-full justify-start gap-2" onClick={() => openConfirmation('archive')}><Archive className="h-4 w-4"/>{b.stage === 'scheduled' ? 'Cancel scheduled publication' : 'Archive notice'}</Button></>}
        <p className="text-xs text-muted-foreground">{b.stage === 'scheduled' ? 'This notice will appear at the scheduled time while the service is available.' : b.stage === 'archived' ? 'Archived notices and recorded receipts are retained.' : 'Publication appears inside the Hub.'}</p>
      </aside>}
    </div>}
    <Dialog open={!!confirm} onOpenChange={open => { if (!open && !action.isPending) setConfirm(null); }}><DialogContent><DialogHeader><DialogTitle>{confirm === 'publish' ? scheduled ? 'Schedule this notice' : 'Publish this notice' : confirm === 'archive' ? 'Archive this notice' : b.pinned ? 'Unpin this notice' : 'Pin this notice'}</DialogTitle><DialogDescription>{confirm === 'publish' ? 'Confirm the final wording and audience before making this notice available.' : confirm === 'archive' ? 'The notice will leave recipient lists. Its content and receipts remain stored.' : 'Change how prominently this notice appears in the announcement list.'}</DialogDescription></DialogHeader>
      <div className="space-y-2 rounded-xl bg-muted/40 p-4 text-sm"><p className="font-semibold">{b.title}</p><p>{b.audience_label}</p>{confirm === 'publish' && <><p>{estimate.error ? 'Audience check failed' : estimate.data ? `${estimate.data.eligible} eligible accounts now` : 'Checking audience…'}</p><p>{scheduled ? `Visible from ${dateLabel(b.publish_at)}` : 'Visible after publishing'}</p>{estimate.data?.eligible === 0 && <p className="text-amber-700 dark:text-amber-300">No eligible accounts currently match. Access and membership can change later.</p>}<QueryError error={estimate.error}/></>}</div>
      {confirm === 'publish' && <label className="flex items-start gap-3 text-sm"><input type="checkbox" className="mt-1" checked={reviewed} onChange={e => setReviewed(e.target.checked)}/>I have reviewed the saved wording, audience and timing.</label>}
      <Field label="Reason for this change"><input className={fieldClass} minLength={5} maxLength={2000} value={why} onChange={e => setWhy(e.target.value)} placeholder="Explain the publication or change"/></Field><QueryError error={action.error}/>
      <Button disabled={why.trim().length < 5 || action.isPending || confirm === 'publish' && (!reviewed || estimate.isPending || !!estimate.error)} onClick={() => action.mutate({ path: `/bulletins/${id}/${confirm}`, body: { version: b.version, reason: why } })}>{action.isPending ? 'Saving…' : confirm === 'publish' ? scheduled ? 'Confirm schedule' : 'Confirm publication' : 'Confirm change'}</Button>
    </DialogContent></Dialog>
  </div>;
}

function Recipients({ bulletin: b }: { bulletin: BulletinView }) {
  const [filter, setFilter] = useState('all'), [q, setQ] = useState(''), [offset, setOffset] = useState(0), [history, setHistory] = useState(false);
  const search = useDebounced(q);
  const result = useQuery<Page<BulletinRecipient> & { totals: { eligible: number; read: number; acknowledged: number } }>({ queryKey: [`${hub}/bulletins/${b.id}/recipients?filter=${filter}&q=${encodeURIComponent(search)}&offset=${offset}`], refetchInterval: 30000, refetchIntervalInBackground: false, enabled: !history });
  const receipts = useQuery<Page<BulletinRecipient>>({ queryKey: [`${hub}/bulletins/${b.id}/receipts?offset=${offset}`], enabled: history, refetchInterval: history ? 30000 : false });
  const query = history ? receipts : result, totals = result.error ? undefined : result.data?.totals;
  return <section className="space-y-5 rounded-2xl border bg-card p-4 sm:p-6"><div><h3 className="text-lg font-semibold">Recipient tracker</h3><p className="mt-1 text-sm text-muted-foreground">Current eligible audience, recalculated as accounts and team access change. This is not a fixed delivery list.</p>{b.stage !== 'live' && <p className="mt-2 text-sm text-muted-foreground">This notice is {b.stage}; current recipients cannot read or acknowledge it now.</p>}</div>
    {!history && <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-muted/40 p-4"><Users className="mb-2 h-5 w-5 text-primary"/><strong className="text-2xl">{totals?.eligible ?? '—'}</strong><p className="text-xs text-muted-foreground">Eligible accounts now</p></div>{[{ label: 'Read', value: totals?.read }, ...(b.requires_acknowledgement ? [{ label: 'Acknowledged', value: totals?.acknowledged }] : [])].map(item => <div key={item.label} className="rounded-xl bg-muted/40 p-4"><p className="text-sm font-medium">{item.label}</p><p className="my-2 text-2xl font-semibold">{item.value ?? '—'} <span className="text-sm font-normal text-muted-foreground">/ {totals?.eligible ?? '—'}</span></p><div role="progressbar" aria-label={item.label} aria-valuenow={item.value || 0} aria-valuemin={0} aria-valuemax={totals?.eligible || 1} className="h-2 overflow-hidden rounded-full bg-primary/10"><div className="h-full bg-primary" style={{ width: `${totals?.eligible ? (item.value || 0) / totals.eligible * 100 : 0}%` }}/></div></div>)}</div>}
    <div className="flex flex-wrap items-center justify-between gap-3"><FilterPills label="Recipient tracking view" value={history ? 'history' : 'current'} onChange={v => { setHistory(v === 'history'); setOffset(0); }} items={[{ value: 'current', label: 'Current audience' }, { value: 'history', label: 'Receipt history' }]}/>{!history && <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><input className={fieldClass + ' pl-9'} aria-label="Find recipient" placeholder="Find a recipient…" value={q} maxLength={100} onChange={e => { setQ(e.target.value); setOffset(0); }}/></div>}</div>
    {!history && <FilterPills label="Recipient status" value={filter} onChange={v => { setFilter(v); setOffset(0); }} items={[{ value: 'all', label: 'All' }, { value: 'unread', label: 'Not read' }, { value: 'read', label: 'Read' }, ...(b.requires_acknowledgement ? [{ value: 'pending', label: 'Awaiting acknowledgement' }, { value: 'acknowledged', label: 'Acknowledged' }] : [])]}/>}
    {history && <p className="text-xs text-muted-foreground">Historical receipts are retained even when a person is no longer in the current audience.</p>}
    <QueryError error={query.error}/>{query.isLoading && <p role="status">Loading recipients…</p>}
    {!query.error && query.data && <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted/40"><tr><th className="p-3 font-medium">Team member</th><th className="p-3 font-medium">Read</th>{b.requires_acknowledgement && <th className="p-3 font-medium">Acknowledged</th>}</tr></thead><tbody>{query.data.items.map((person, i) => <tr className="border-t" key={person.id || i}><td className="p-3"><strong className="font-medium">{person.name}</strong>{person.department && <p className="text-xs text-muted-foreground">{person.department}</p>}</td><td className="p-3 text-xs">{person.read_at ? dateLabel(person.read_at) : 'Not yet read'}</td>{b.requires_acknowledgement && <td className="p-3 text-xs">{person.acknowledged_at ? dateLabel(person.acknowledged_at) : 'Pending'}</td>}</tr>)}</tbody></table>{!query.data.items.length && <p className="p-8 text-center text-sm text-muted-foreground">No recipients match this view.</p>}</div>}
    <Pager offset={offset} hasMore={!query.error && query.data?.hasMore} onChange={setOffset}/>
  </section>;
}
