import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {hub,useHubAction,PersonPicker,Pager,localDate,dateLabel,type Page,type Person} from './HubControls';
import type {Channel} from '@shared/communications';
export function ChannelManagement({id,channel}:{id:number;channel:Channel}) {
  const [person,setPerson]=useState(''),[start,setStart]=useState(localDate()),[end,setEnd]=useState(''),[why,setWhy]=useState(''),[offset,setOffset]=useState(0),[q,setQ]=useState('');
  const action=useHubAction();
  const members=useQuery<Page<Person>>({queryKey:[`${hub}/channels/${id}/members?q=${encodeURIComponent(q)}&offset=${offset}`]});
  const history=useQuery<Page<any>>({queryKey:[`${hub}/channels/${id}/history?offset=0`]});
  return <div className="space-y-3 rounded-lg border p-4"><Field label="Reason for channel change"><input className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/settings`,body:{version:channel.version,reason:why,archived:!!channel.archived_at,managersOnly:!channel.managers_only}})}>{channel.managers_only?'Allow members to post':'Restrict posting to managers'}</Button><Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/settings`,body:{version:channel.version,reason:why,archived:!channel.archived_at,managersOnly:channel.managers_only}})}>{channel.archived_at?'Reopen channel':'Archive channel'}</Button></div><QueryError error={action.error}/>
    {channel.kind==='group'&&!channel.archived_at&&<><h3 className="font-medium">Add or update membership</h3><PersonPicker value={person} onChange={setPerson}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Member access starts (device timezone)"><input type="datetime-local" className={fieldClass} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Member access ends (required for temporary staff)"><input type="datetime-local" className={fieldClass} value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Button size="sm" disabled={!person||!start||why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/members`,body:{version:channel.version,member:{userId:Number(person),startsAt:new Date(start).toISOString(),endsAt:end?new Date(end).toISOString():null,reason:why}}})}>Save membership</Button></>}
    {channel.kind==='workforce'&&<p className="text-sm">Members follow the workforce team, accepted shifts starting within 24 hours and active supervisor grants. Manage assignments in <a href="/workforce" className="underline">Workforce</a>.</p>}
    <input className={fieldClass} aria-label="Find channel members" placeholder="Find channel members" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><QueryError error={members.error}/>{members.data?.items.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 text-sm"><span>{p.name} · {p.current?'Current':p.removed_at?'Removed':'Outside access dates'}{p.ends_at?' · Until '+dateLabel(p.ends_at):''}</span>{channel.kind==='group'&&!p.removed_at&&<Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/members/${p.id}/remove`,body:{version:channel.version,reason:why}})}>Remove access</Button>}</div>)}<Pager offset={offset} hasMore={members.data?.hasMore} onChange={setOffset}/><details><summary>Recent channel history (latest 25)</summary>{history.data?.items.map(h=><p className="text-xs my-2" key={h.version}>Version {h.version} · {dateLabel(h.created_at)} · {h.reason}</p>)}<QueryError error={history.error}/></details></div>;
}
