import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Search,Bookmark,Files,ArrowUpRight,Paperclip} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {QueryError,fieldClass} from '@/components/hr/Operations';
import type {ChatMessage} from '@shared/communications';
import {hub,Pager,dateLabel,type Page,useDebounced} from './HubControls';
export default function ChatSearch({mode,onOpen}:{mode:'all'|'saved'|'files';onOpen:(channel:number,message:number)=>void}){
 const [q,setQ]=useState(''),[offset,setOffset]=useState(0),search=useDebounced(q);
 const result=useQuery<Page<ChatMessage>>({queryKey:[`${hub}/search?mode=${mode}&q=${encodeURIComponent(search)}&offset=${offset}`],enabled:mode!=='all'||search.trim().length>=2,refetchInterval:10000,refetchIntervalInBackground:false});
 const Icon=mode==='saved'?Bookmark:mode==='files'?Files:Search;
 return <section className="rounded-2xl border bg-card p-4 sm:p-6 space-y-4"><header className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><Icon className="h-5 w-5"/></span><div><h2 className="font-semibold">{mode==='saved'?'Saved for later':mode==='files'?'Shared files':'Search conversations'}</h2><p className="text-sm text-muted-foreground">{mode==='saved'?'Your private list of messages to come back to.':'Find messages and files in conversations you can currently access.'}</p></div></header><input className={fieldClass} aria-label="Search across conversations" placeholder={mode==='all'?'Search at least two characters…':'Filter by message or file name…'} value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><QueryError error={result.error}/>{result.isFetching&&<p role="status" className="text-sm text-muted-foreground">Searching…</p>}{mode==='all'&&search.trim().length<2&&<p className="py-10 text-center text-muted-foreground">Search by a phrase, instruction or file name.</p>}{!result.error&&result.data&&!result.data.items.length&&<div className="py-10 text-center"><Icon className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><p className="font-medium">{mode==='saved'?'Nothing saved yet':'No matches found'}</p><p className="mt-1 text-sm text-muted-foreground">{mode==='saved'?'Choose “Save for later” from a message’s menu.':'Try a different search or check your conversation access.'}</p></div>}
 <div className="grid gap-3 md:grid-cols-2">{!result.error&&result.data?.items.map(m=><article key={m.id} className="rounded-xl border p-4"><p className="text-xs font-medium text-primary">{m.channel_name}</p><p className="mt-2 line-clamp-3 whitespace-pre-wrap break-words text-sm">{m.body}</p>{m.attachment_name&&<p className="mt-2 flex items-center gap-2 text-xs"><Paperclip className="h-3.5 w-3.5 shrink-0"/><span className="truncate">{m.attachment_name}</span></p>}<p className="mt-3 text-xs text-muted-foreground">{m.author_name} · {dateLabel(m.created_at)}</p><Button variant="ghost" size="sm" className="mt-2 gap-2" onClick={()=>onOpen(m.channel_id,m.id)}>Open conversation<ArrowUpRight className="h-4 w-4"/></Button></article>)}</div><Pager offset={offset} hasMore={!result.error&&result.data?.hasMore} onChange={setOffset}/></section>;
}
