import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,ArrowDown,Send,Paperclip,AtSign,Star,BellOff,Bell,Pin,Files,MessageCircle,Settings2,X,Search,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {QueryError,fieldClass} from '@/components/hr/Operations';
import {apiJson} from '@/lib/queryClient';
import type {Channel,ChatMessage,CommunicationPolicy} from '@shared/communications';
import {hub,useHubAction,Pager,type Page,type Person,useDebounced} from './HubControls';
import {ChannelManagement} from './ChannelManagement';
import {MessageCard} from './ChatMessageCard';

export type ChatDraft={body:string;file:File|null;reply:ChatMessage|null;mentions:number[]};
const emptyDraft=():ChatDraft=>({body:'',file:null,reply:null,mentions:[]});
export default function Conversation({id,userId,displayName,focusMessage,onBack,drafts}:{id:number;userId:number;displayName?:string;focusMessage:number|null;onBack:()=>void;drafts:Map<number,ChatDraft>}){
 const [draft,setDraft]=useState(()=>drafts.get(id)||emptyDraft()),[q,setQ]=useState(''),[before,setBefore]=useState<number>(),[view,setView]=useState('all'),[manage,setManage]=useState(false),[thread,setThread]=useState<number|null>(focusMessage),[threadOffset,setThreadOffset]=useState(0),[mentionOpen,setMentionOpen]=useState(false),[memberQ,setMemberQ]=useState(''),[memberOffset,setMemberOffset]=useState(0),[retract,setRetract]=useState<ChatMessage|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[newMessages,setNewMessages]=useState(false),[fileKey,setFileKey]=useState(0);
 const search=useDebounced(q),memberSearch=useDebounced(memberQ),pending=useRef({signature:'',key:''}),scroll=useRef<HTMLDivElement>(null),textarea=useRef<HTMLTextAreaElement>(null),stick=useRef(true),forceScroll=useRef(true),lastRead=useRef(0),cache=useQueryClient();
 const update=(next:ChatDraft)=>{setDraft(next);drafts.set(id,next);};
 useEffect(()=>{setThread(focusMessage);setThreadOffset(0);},[focusMessage]);
 const channel=useQuery<Channel&{policy:CommunicationPolicy;muted:boolean;favorite:boolean}>({queryKey:[`${hub}/channels/${id}`],refetchInterval:10000,refetchIntervalInBackground:false});
 const messages=useQuery<Page<ChatMessage>>({queryKey:[`${hub}/channels/${id}/messages?q=${encodeURIComponent(search)}&view=${view}${before?'&before='+before:''}`],refetchInterval:before?false:5000,refetchIntervalInBackground:false,enabled:!!channel.data&&!channel.error});
 const replies=useQuery<Page<ChatMessage>&{root:ChatMessage}>({queryKey:[`${hub}/channels/${id}/messages/${thread}/replies?offset=${threadOffset}`],enabled:!!thread&&!!channel.data&&!channel.error,refetchInterval:thread?5000:false,refetchIntervalInBackground:false});
 const members=useQuery<Page<Person>>({queryKey:[`${hub}/channels/${id}/members?q=${encodeURIComponent(memberSearch)}&offset=${memberOffset}`],enabled:mentionOpen});
 const send=useHubAction(()=>{update(emptyDraft());setFileKey(v=>v+1);pending.current={signature:'',key:''};forceScroll.current=true;setBefore(undefined);setThreadOffset(0);setError('');textarea.current?.focus();});
 const action=useHubAction(()=>{setRetract(null);setReason('');});
 const read=useMutation({mutationFn:(lastReadId:number)=>apiJson(`${hub}/channels/${id}/state`,{method:'POST',body:{lastReadId}}),onSuccess:()=>{cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith(hub+'/channels?')||q.queryKey[0]===hub+'/summary'});},onError:()=>{lastRead.current=0;}});
 const c=channel.data,shown=messages.error?[]:messages.data?.items||[],latest=shown[0]?.id;
 function markShown(){if(latest&&!messages.error&&!channel.error&&!thread&&!before&&!search&&view==='all'&&stick.current&&document.visibilityState==='visible'&&latest>lastRead.current&&!read.isPending){lastRead.current=latest;read.mutate(latest);}}
 useLayoutEffect(()=>{if(!scroll.current)return;if(stick.current||forceScroll.current){scroll.current.scrollTop=scroll.current.scrollHeight;forceScroll.current=false;setNewMessages(false);}else setNewMessages(true);},[latest,thread,replies.data?.items.length]);
 useEffect(()=>{markShown();const visible=()=>markShown();document.addEventListener('visibilitychange',visible);return()=>document.removeEventListener('visibilitychange',visible);},[latest,thread,before,search,view,channel.error,messages.error]);
 function openThread(mid:number){setThread(mid);setThreadOffset(0);forceScroll.current=true;}
 function replyTo(m:ChatMessage){update({...draft,reply:m});setThread(m.id);setThreadOffset(0);textarea.current?.focus();}
 const messageAction=(m:ChatMessage,actionName:string,body:unknown)=>action.mutate({path:`/channels/${id}/messages/${m.id}/${actionName}`,body});
 function submit(){
  if(!c||send.isPending||!draft.body.trim())return;
  if(draft.file&&draft.file.size>c.policy.attachmentMegabytes*1024*1024){setError(`Choose an attachment under ${c.policy.attachmentMegabytes} MB.`);return;}
  const signature=JSON.stringify([draft.body,draft.reply?.id??thread,draft.mentions,draft.file?.name,draft.file?.size,draft.file?.lastModified]);if(pending.current.signature!==signature)pending.current={signature,key:crypto.randomUUID()};
  const input={body:draft.body,replyTo:draft.reply?.id??thread??null,mentions:draft.mentions,requestKey:pending.current.key};let body:any=input;if(draft.file){body=new FormData();body.append('message',JSON.stringify(input));body.append('file',draft.file);}setError('');send.mutate({path:`/channels/${id}/messages`,body});
 }
 if(channel.error||!c)return <div className="p-6 space-y-4"><Button variant="outline" onClick={onBack}>Back to conversations</Button><QueryError error={channel.error}/>{channel.error?<Button onClick={()=>void channel.refetch()}>Try again</Button>:<p role="status">Opening conversation…</p>}</div>;
 const card=(m:ChatMessage)=><MessageCard key={m.id} message={m} userId={userId} canPost={c.can_post} canManage={c.can_manage} busy={action.isPending} onReply={replyTo} onThread={openThread} onAction={messageAction} onWithdraw={m=>{setRetract(m);setReason('');}}/>;
 return <section className="flex min-h-0 min-w-0 flex-col bg-background" aria-label="Open conversation">
  <header className="border-b p-4"><div className="flex items-center gap-2"><Button size="icon" variant="ghost" aria-label="Back to conversations" className="h-8 w-8 lg:hidden" onClick={onBack}><ArrowLeft className="h-4 w-4"/></Button><div className="min-w-0 flex-1"><h2 className="truncate font-semibold" title={displayName||c.name}>{displayName||c.name}</h2><p className="mt-0.5 text-xs text-muted-foreground">{c.kind==='direct'?'Private conversation':c.kind==='workforce'?'Event / FEC team':'Private group'} · {c.archived_at?'Archived':!c.can_post?'Read only':'Updates every 5s'}</p></div><Button variant="ghost" size="icon" className="h-8 w-8" disabled={action.isPending} aria-label={c.favorite?'Remove favorite':'Favorite conversation'} aria-pressed={c.favorite} onClick={()=>action.mutate({path:`/channels/${id}/state`,body:{favorite:!c.favorite}})}><Star className={`h-4 w-4 ${c.favorite?'fill-amber-400 text-amber-600':''}`}/></Button><Button variant="ghost" size="icon" className="h-8 w-8" disabled={action.isPending} aria-label={c.muted?'Unmute conversation':'Mute conversation'} onClick={()=>action.mutate({path:`/channels/${id}/state`,body:{muted:!c.muted}})}>{c.muted?<BellOff className="h-4 w-4"/>:<Bell className="h-4 w-4"/>}</Button>{c.can_manage&&<Button variant="ghost" size="icon" className="h-8 w-8" aria-label="Manage conversation" onClick={()=>setManage(true)}><Settings2 className="h-4 w-4"/></Button>}</div>
   {c.description&&<p className="mt-2 line-clamp-1 sm:line-clamp-2 text-xs text-muted-foreground" title={c.description}>{c.description}</p>}
   <div className="mt-3 flex flex-wrap gap-1">{[{id:'all',label:'Messages',Icon:MessageCircle},{id:'pinned',label:'Pinned',Icon:Pin},{id:'files',label:'Files',Icon:Files}].map(item=><Button key={item.id} size="sm" variant={view===item.id&&!thread?'secondary':'ghost'} className="h-8 gap-1.5 text-xs" onClick={()=>{setView(item.id);setBefore(undefined);setThread(null);forceScroll.current=true;}}><item.Icon className="h-3.5 w-3.5"/>{item.label}</Button>)}<Button size="sm" variant="ghost" className="ml-auto h-8 px-2" aria-label="Refresh conversation" onClick={()=>{void channel.refetch();void messages.refetch();if(thread)void replies.refetch();}}><RefreshCw className={`h-3.5 w-3.5 ${messages.isFetching?'animate-spin':''}`}/></Button></div>
  </header>
  {thread?<div className="flex items-center justify-between gap-2 border-b bg-primary/5 px-4 py-2 text-sm"><span className="font-medium">Message & replies</span><Button size="sm" variant="ghost" onClick={()=>{setThread(null);setThreadOffset(0);update({...draft,reply:null});forceScroll.current=true;}}><X className="mr-1 h-3 w-3"/>Close replies</Button></div>:<div className="flex items-center gap-2 border-b px-4 py-2"><Search className="h-4 w-4 shrink-0 text-muted-foreground"/><input className="w-full bg-transparent py-1 text-xs outline-none" aria-label="Search messages in conversation" placeholder="Find a message in this conversation…" maxLength={100} value={q} onChange={e=>{setQ(e.target.value);setBefore(undefined);forceScroll.current=true;}}/></div>}
  <div ref={scroll} onScroll={()=>{const area=scroll.current!;stick.current=area.scrollHeight-area.scrollTop-area.clientHeight<70;if(stick.current){setNewMessages(false);markShown();}}} tabIndex={0} aria-label="Conversation messages" className="min-h-[120px] flex-1 space-y-4 overflow-y-auto bg-muted/20 p-3 sm:p-4">
   <QueryError error={messages.error||replies.error||action.error||read.error}/>
   {thread?<>{replies.isLoading&&<p role="status">Loading replies…</p>}{replies.data&&!replies.error&&<>{card(replies.data.root)}<div className="border-t pt-3 text-xs font-medium text-muted-foreground">Replies</div>{replies.data.items.length?[...replies.data.items].reverse().map(card):<p className="py-6 text-center text-sm text-muted-foreground">No replies yet. Reply to this message to keep the conversation together.</p>}<Pager offset={threadOffset} hasMore={replies.data.hasMore} onChange={setThreadOffset}/></>}</>:<>{messages.isLoading&&<p role="status" className="text-sm text-muted-foreground">Loading messages…</p>}{messages.data?.hasMore&&<div className="text-center"><Button variant="outline" size="sm" onClick={()=>{setBefore(shown[shown.length-1]?.id);forceScroll.current=true;}}>Older messages</Button></div>}{!shown.length&&!messages.isLoading&&!messages.error&&<div className="py-12 text-center"><MessageCircle className="mx-auto mb-3 h-9 w-9 text-primary/50"/><h3 className="text-sm font-semibold">{search?'No matching messages':view==='pinned'?'No pinned messages':view==='files'?'No files shared yet':'Start the conversation'}</h3><p className="mt-1 text-xs text-muted-foreground">{view==='pinned'?'Channel managers can pin instructions from a message’s menu.':'Share an update, ask a question or coordinate the next shift.'}</p></div>}{[...shown].reverse().map((m,i,array)=><div key={m.id} className="space-y-4">{(i===0||new Date(array[i-1].created_at).toDateString()!==new Date(m.created_at).toDateString())&&<p className="text-center text-[11px] text-muted-foreground">{new Date(m.created_at).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</p>}{card(m)}</div>)}</>}
  </div>
  {(before||newMessages)&&<Button size="sm" variant="secondary" className="mx-auto my-1 gap-2" onClick={()=>{setBefore(undefined);forceScroll.current=true;if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;stick.current=true;setNewMessages(false);markShown();}}><ArrowDown className="h-4 w-4"/>{before?'Back to latest messages':'New messages'}</Button>}
  {c.can_post&&(!thread||replies.data&&!replies.error&&!replies.data.root.retracted_at)?<form className="border-t bg-card p-3" onSubmit={e=>{e.preventDefault();submit();}}><fieldset disabled={send.isPending}>
   {draft.reply&&<div className="mb-2 flex gap-2 rounded-lg border-l-2 border-primary bg-muted/50 p-2 text-xs"><div className="min-w-0 flex-1"><strong>Replying to {draft.reply.author_name}</strong><p className="truncate">{draft.reply.body}</p></div><button type="button" aria-label="Cancel reply" onClick={()=>{update({...draft,reply:null});setThread(null);}}><X className="h-4 w-4"/></button></div>}
   <textarea ref={textarea} aria-label="Message" placeholder={draft.reply||thread?'Write your reply…':'Write a message…'} required rows={2} maxLength={c.policy.maxMessageLength} className="w-full resize-none rounded-lg border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary" value={draft.body} onChange={e=>update({...draft,body:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.nativeEvent.isComposing){e.preventDefault();submit();}}}/>
   {draft.file&&<div className="mt-2 flex items-center gap-2 text-xs"><Paperclip className="h-3 w-3"/><span className="min-w-0 flex-1 truncate">{draft.file.name} · {Math.ceil(draft.file.size/1024)} KB</span><button type="button" aria-label="Remove attachment" onClick={()=>{update({...draft,file:null});setFileKey(v=>v+1);}}><X className="h-4 w-4"/></button></div>}
   {draft.mentions.length>0&&<p className="mt-1 text-xs text-primary">{draft.mentions.length} member{draft.mentions.length===1?'':'s'} mentioned <button type="button" className="ml-2 underline" onClick={()=>update({...draft,mentions:[]})}>Clear</button></p>}
   <div className="mt-2 flex flex-wrap items-center gap-2"><label className="relative inline-flex cursor-pointer items-center gap-1 overflow-hidden rounded-md border p-2 text-xs hover:bg-accent"><Paperclip className="h-4 w-4"/><span>Attach</span><input key={fileKey} aria-label="Attach private file" type="file" accept=".pdf,.png,.jpg,.jpeg" className="absolute inset-0 cursor-pointer opacity-0" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>c.policy.attachmentMegabytes*1024*1024){setError(`Attachment must be under ${c.policy.attachmentMegabytes} MB.`);e.target.value='';return;}update({...draft,file});setError('');}}/></label><Button variant="ghost" type="button" size="sm" className="px-2" aria-label="Mention a member" onClick={()=>setMentionOpen(true)}><AtSign className="h-4 w-4"/></Button><span className="ml-auto text-[10px] text-muted-foreground">{draft.body.length}/{c.policy.maxMessageLength}</span><Button size="sm" type="submit" disabled={send.isPending||!draft.body.trim()||draft.mentions.length>10} className="gap-2"><Send className="h-4 w-4"/>{send.isPending?'Sending…':'Send message'}</Button></div><p className="mt-1 text-[10px] text-muted-foreground">Ctrl / ⌘ + Enter to send · PDF, PNG, JPEG up to {c.policy.attachmentMegabytes} MB</p>
  </fieldset><QueryError error={send.error||error}/></form>:<p className="border-t bg-muted/30 p-4 text-sm text-muted-foreground">{thread?'Close replies to return to the conversation. This message is unavailable for new replies.':'Posting is closed or restricted to channel managers.'}</p>}
  <Dialog open={manage} onOpenChange={setManage}><DialogContent><DialogHeader><DialogTitle>Manage conversation</DialogTitle></DialogHeader><ChannelManagement id={id} channel={c}/></DialogContent></Dialog>
  <Dialog open={mentionOpen} onOpenChange={setMentionOpen}><DialogContent><DialogHeader><DialogTitle>Mention current members</DialogTitle></DialogHeader><input aria-label="Find a member to mention" className={fieldClass} placeholder="Search names…" value={memberQ} onChange={e=>{setMemberQ(e.target.value);setMemberOffset(0);}}/><QueryError error={members.error}/><div className="space-y-2">{!members.error&&members.data?.items.filter(p=>p.current!==false&&p.id!==userId).map(p=><label className="flex items-center gap-3 rounded-lg border p-3 text-sm" key={p.id}><input type="checkbox" checked={draft.mentions.includes(p.id)} disabled={!draft.mentions.includes(p.id)&&draft.mentions.length>=10} onChange={e=>update({...draft,mentions:e.target.checked?[...draft.mentions,p.id]:draft.mentions.filter(n=>n!==p.id)})}/>{p.name}</label>)}</div><Pager offset={memberOffset} hasMore={members.data?.hasMore} onChange={setMemberOffset}/><Button onClick={()=>setMentionOpen(false)}>Done · {draft.mentions.length} selected</Button></DialogContent></Dialog>
  <Dialog open={!!retract} onOpenChange={open=>{if(!open)setRetract(null);}}><DialogContent><DialogHeader><DialogTitle>Withdraw message</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">The message becomes a withdrawal marker. Its stored history is retained.</p><label className="space-y-2 text-sm">Reason<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5}/></label><QueryError error={action.error}/><Button variant="destructive" disabled={reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/messages/${retract!.id}/retract`,body:{reason}})}>Withdraw message</Button></DialogContent></Dialog>
 </section>;
}
