import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,ArrowDown,Send,Paperclip,AtSign,Star,BellOff,Bell,Pin,Files,MessageCircle,Settings2,X,Search,RefreshCw,MoreVertical,Users,Info,Smile} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {QueryError,fieldClass} from '@/components/hr/Operations';
import {apiJson} from '@/lib/queryClient';
import type {Channel,ChatMessage,CommunicationPolicy} from '@shared/communications';
import {hub,useHubAction,Pager,type Page,type Person,useDebounced} from './HubControls';
import {ChannelManagement} from './ChannelManagement';
import {MessageCard,initials} from './ChatMessageCard';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';

export type ChatDraft={body:string;file:File|null;reply:ChatMessage|null;mentions:number[]};
const emptyDraft=():ChatDraft=>({body:'',file:null,reply:null,mentions:[]});
export default function Conversation({id,userId,displayName,focusMessage,onBack,drafts}:{id:number;userId:number;displayName?:string;focusMessage:number|null;onBack:()=>void;drafts:Map<number,ChatDraft>}){
 const [draft,setDraft]=useState(()=>drafts.get(id)||emptyDraft()),[q,setQ]=useState(''),[before,setBefore]=useState<number>(),[view,setView]=useState('all'),[manage,setManage]=useState(false),[thread,setThread]=useState<number|null>(focusMessage),[threadOffset,setThreadOffset]=useState(0),[mentionOpen,setMentionOpen]=useState(false),[memberQ,setMemberQ]=useState(''),[memberOffset,setMemberOffset]=useState(0),[retract,setRetract]=useState<ChatMessage|null>(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[newMessages,setNewMessages]=useState(false),[fileKey,setFileKey]=useState(0),[searchOpen,setSearchOpen]=useState(false),[info,setInfo]=useState(false);
 const search=useDebounced(q),memberSearch=useDebounced(memberQ),pending=useRef({signature:'',key:''}),scroll=useRef<HTMLDivElement>(null),textarea=useRef<HTMLTextAreaElement>(null),stick=useRef(true),forceScroll=useRef(true),lastRead=useRef(0),cache=useQueryClient();
 const update=(next:ChatDraft)=>{setDraft(next);drafts.set(id,next);};
 useEffect(()=>{setThread(focusMessage);setThreadOffset(0);},[focusMessage]);
 const channel=useQuery<Channel&{policy:CommunicationPolicy;muted:boolean;favorite:boolean}>({queryKey:[`${hub}/channels/${id}`],refetchInterval:10000,refetchIntervalInBackground:false});
 const messages=useQuery<Page<ChatMessage>>({queryKey:[`${hub}/channels/${id}/messages?q=${encodeURIComponent(search)}&view=${view}${before?'&before='+before:''}`],refetchInterval:before?false:5000,refetchIntervalInBackground:false,enabled:!!channel.data&&!channel.error});
 const replies=useQuery<Page<ChatMessage>&{root:ChatMessage}>({queryKey:[`${hub}/channels/${id}/messages/${thread}/replies?offset=${threadOffset}`],enabled:!!thread&&!!channel.data&&!channel.error,refetchInterval:thread?5000:false,refetchIntervalInBackground:false});
 const members=useQuery<Page<Person>>({queryKey:[`${hub}/channels/${id}/members?q=${encodeURIComponent(memberSearch)}&offset=${memberOffset}`],enabled:mentionOpen});
 const send=useHubAction(()=>{update(emptyDraft());setFileKey(v=>v+1);pending.current={signature:'',key:''};forceScroll.current=true;setBefore(undefined);setThreadOffset(0);setError('');textarea.current?.focus();});
 const action=useHubAction(()=>{setRetract(null);setReason('');});
 const read=useMutation({mutationFn:(lastReadId:number)=>apiJson(`${hub}/channels/${id}/state`,{method:'POST',body:{lastReadId}}),onSuccess:()=>{cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith(hub+'/channels?')||q.queryKey[0]===hub+'/summary'});},onError:()=>{lastRead.current=0;}});
 const c=channel.data,shown=messages.error?[]:messages.data?.items||[],latest=shown[0]?.id;
 useLayoutEffect(()=>{const input=textarea.current;if(input){input.style.height='auto';input.style.height=Math.min(input.scrollHeight,120)+'px';}},[draft.body,c?.can_post,thread,replies.data?.root?.id]);
 function markShown(){if(latest&&!messages.error&&!channel.error&&!thread&&!before&&!search&&view==='all'&&stick.current&&document.visibilityState==='visible'&&latest>lastRead.current&&!read.isPending){lastRead.current=latest;read.mutate(latest);}}
 useLayoutEffect(()=>{if(!scroll.current)return;if(stick.current||forceScroll.current){scroll.current.scrollTop=scroll.current.scrollHeight;forceScroll.current=false;setNewMessages(false);}else setNewMessages(true);},[latest,thread,replies.data?.items.length]);
 useEffect(()=>{markShown();const visible=()=>markShown();document.addEventListener('visibilitychange',visible);return()=>document.removeEventListener('visibilitychange',visible);},[latest,thread,before,search,view,channel.error,messages.error]);
 function openThread(mid:number){setThread(mid);setThreadOffset(0);forceScroll.current=true;}
 function replyTo(m:ChatMessage){update({...draft,reply:m});setThread(m.id);setThreadOffset(0);textarea.current?.focus();}
 const messageAction=(m:ChatMessage,actionName:string,body:unknown)=>action.mutate({path:`/channels/${id}/messages/${m.id}/${actionName}`,body});
 function submit(){
  if(!c||send.isPending||!draft.body.trim())return;
  if(draft.file&&draft.file.size>c.policy.attachmentMegabytes*1024*1024){setError(`Choose an attachment under ${c.policy.attachmentMegabytes} MB.`);return;}
  const signature=JSON.stringify([draft.body,draft.reply?.id??thread,draft.mentions,draft.file?.name,draft.file?.size,draft.file?.lastModified]);if(pending.current.signature!==signature)pending.current={signature,key:crypto.randomUUID()};
  const input={body:draft.body,replyTo:draft.reply?.id??thread??null,mentions:draft.mentions,requestKey:pending.current.key};let body:any=input;if(draft.file){body=new FormData();body.append('message',JSON.stringify(input));body.append('file',draft.file);}setError('');send.mutate({path:`/channels/${id}/messages`,body});
 }
 if(channel.error||!c)return <div className="p-6 space-y-4"><Button variant="outline" onClick={onBack}>Back to conversations</Button><QueryError error={channel.error}/>{channel.error?<Button onClick={()=>void channel.refetch()}>Try again</Button>:<p role="status">Opening conversation…</p>}</div>;
 const card=(m:ChatMessage)=><MessageCard key={m.id} message={m} userId={userId} canPost={c.can_post} canManage={c.can_manage} busy={action.isPending} onReply={replyTo} onThread={openThread} onAction={messageAction} onWithdraw={m=>{setRetract(m);setReason('');}}/>;
 return <section className="messenger-conversation" aria-label="Open conversation">
  <header className="messenger-conversation-header">
   <Button size="icon" variant="ghost" aria-label="Back to conversations" className="chat-back shrink-0" onClick={onBack}><ArrowLeft className="h-5 w-5"/></Button>
   <button className="chat-contact" onClick={()=>setInfo(true)} aria-label={`About ${displayName||c.name}`}>
    <span className={`chat-avatar ${c.kind==='direct'?'chat-avatar-person':''}`} aria-hidden="true">{c.kind==='direct'?initials(displayName||c.name):<Users className="h-5 w-5"/>}</span>
    <span className="min-w-0"><h2 className="truncate text-sm font-semibold" title={displayName||c.name}>{displayName||c.name}</h2><span className="mt-1 block truncate text-xs text-muted-foreground">{c.archived_at?'Archived':!c.can_post?'Read only':c.kind==='direct'?'Direct message':c.kind==='workforce'?'Team chat':'Group chat'}{c.muted?' · Muted':''}</span></span>
   </button>
   <Button variant="ghost" size="icon" className="shrink-0" aria-label="Search this chat" title="Search this chat" aria-pressed={searchOpen} onClick={()=>{setSearchOpen(v=>!v);setQ('');setBefore(undefined);setThread(null);}}><Search className="h-5 w-5"/></Button>
   <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="shrink-0" aria-label="Conversation options"><MoreVertical className="h-5 w-5"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">
    <DropdownMenuItem onSelect={()=>setInfo(true)}><Info/>Chat info</DropdownMenuItem>
    <DropdownMenuItem disabled={action.isPending} onSelect={()=>action.mutate({path:`/channels/${id}/state`,body:{favorite:!c.favorite}})}><Star/>{c.favorite?'Remove favorite':'Favorite chat'}</DropdownMenuItem>
    <DropdownMenuItem disabled={action.isPending} onSelect={()=>action.mutate({path:`/channels/${id}/state`,body:{muted:!c.muted}})}>{c.muted?<Bell/>:<BellOff/>}{c.muted?'Unmute chat':'Mute chat'}</DropdownMenuItem>
    <DropdownMenuSeparator/>
    <DropdownMenuItem onSelect={()=>{setView('pinned');setBefore(undefined);setThread(null);forceScroll.current=true;}}><Pin/>Pinned messages</DropdownMenuItem>
    <DropdownMenuItem onSelect={()=>{setView('files');setBefore(undefined);setThread(null);forceScroll.current=true;}}><Files/>Shared files</DropdownMenuItem>
    <DropdownMenuItem onSelect={()=>{void channel.refetch();void messages.refetch();if(thread)void replies.refetch();}}><RefreshCw/>Refresh chat</DropdownMenuItem>
    {c.can_manage&&<><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>setManage(true)}><Settings2/>Manage group</DropdownMenuItem></>}
   </DropdownMenuContent></DropdownMenu>
  </header>
  {searchOpen&&!thread&&<div className="chat-search-bar"><Search className="h-4 w-4 shrink-0 text-muted-foreground"/><input autoFocus aria-label="Search messages in conversation" placeholder="Search in this chat" maxLength={100} value={q} onChange={e=>{setQ(e.target.value);setBefore(undefined);forceScroll.current=true;}}/><Button size="icon" variant="ghost" aria-label="Close message search" onClick={()=>{setSearchOpen(false);setQ('');setBefore(undefined);}}><X className="h-4 w-4"/></Button></div>}
  {(thread||view!=='all')&&<div className="chat-context-bar"><span className="flex items-center gap-2">{thread?<MessageCircle className="h-4 w-4"/>:view==='pinned'?<Pin className="h-4 w-4"/>:<Files className="h-4 w-4"/>}{thread?'Replies':view==='pinned'?'Pinned messages':'Shared files'}</span><Button size="sm" variant="ghost" className="gap-1 text-xs" onClick={()=>{setThread(null);setThreadOffset(0);setView('all');setBefore(undefined);update({...draft,reply:null});forceScroll.current=true;}}><X className="h-3 w-3"/>Back to chat</Button></div>}
  <div ref={scroll} onScroll={()=>{const area=scroll.current!;stick.current=area.scrollHeight-area.scrollTop-area.clientHeight<70;if(stick.current){setNewMessages(false);markShown();}}} tabIndex={0} aria-label="Conversation messages" className="messenger-messages">
   <QueryError error={messages.error||replies.error||action.error||read.error}/>
   {thread?<>{replies.isLoading&&<p role="status">Loading replies…</p>}{replies.data&&!replies.error&&<>{card(replies.data.root)}<div className="border-t pt-3 text-xs font-medium text-muted-foreground">Replies</div>{replies.data.items.length?[...replies.data.items].reverse().map(card):<p className="py-6 text-center text-sm text-muted-foreground">No replies yet. Reply to this message to keep the conversation together.</p>}<Pager offset={threadOffset} hasMore={replies.data.hasMore} onChange={setThreadOffset}/></>}</>:<>{messages.isLoading&&<p role="status" className="text-sm text-muted-foreground">Loading messages…</p>}{messages.data?.hasMore&&<div className="text-center"><Button variant="outline" size="sm" onClick={()=>{setBefore(shown[shown.length-1]?.id);forceScroll.current=true;}}>Older messages</Button></div>}{!shown.length&&!messages.isLoading&&!messages.error&&<div className="py-12 text-center"><MessageCircle className="mx-auto mb-3 h-9 w-9 text-primary/50"/><h3 className="text-sm font-semibold">{search?'No matching messages':view==='pinned'?'No pinned messages':view==='files'?'No files shared yet':'Start the conversation'}</h3><p className="mt-1 text-xs text-muted-foreground">{view==='pinned'?'Channel managers can pin instructions from a message’s menu.':'Share an update, ask a question or coordinate the next shift.'}</p></div>}{[...shown].reverse().map((m,i,array)=><div key={m.id} className="chat-message-block">{(i===0||new Date(array[i-1].created_at).toDateString()!==new Date(m.created_at).toDateString())&&<div className="chat-date"><span>{new Date(m.created_at).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}</span></div>}{card(m)}</div>)}</>}
  </div>
  {(before||newMessages)&&<Button size="sm" variant="secondary" className="mx-auto my-1 gap-2" onClick={()=>{setBefore(undefined);forceScroll.current=true;if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;stick.current=true;setNewMessages(false);markShown();}}><ArrowDown className="h-4 w-4"/>{before?'Back to latest messages':'New messages'}</Button>}
  {c.can_post&&(!thread||replies.data&&!replies.error&&!replies.data.root.retracted_at)?<form className="messenger-composer" onSubmit={e=>{e.preventDefault();submit();}}><fieldset disabled={send.isPending} className="min-w-0">
   {draft.reply&&<div className="mb-2 flex gap-2 rounded-lg border-l-2 border-primary bg-muted/50 p-3 text-xs"><div className="min-w-0 flex-1"><strong>Replying to {draft.reply.author_name}</strong><p className="truncate">{draft.reply.body}</p></div><Button size="icon" variant="ghost" type="button" aria-label="Cancel reply" onClick={()=>{update({...draft,reply:null});setThread(null);}}><X className="h-4 w-4"/></Button></div>}
   {draft.file&&<div className="mb-2 flex items-center gap-2 rounded-xl bg-muted px-3 py-1 text-xs"><Paperclip className="h-4 w-4"/><span className="min-w-0 flex-1 truncate">{draft.file.name} · {Math.ceil(draft.file.size/1024)} KB</span><Button size="icon" variant="ghost" type="button" aria-label="Remove attachment" onClick={()=>{update({...draft,file:null});setFileKey(v=>v+1);}}><X className="h-4 w-4"/></Button></div>}
   {draft.mentions.length>0&&<div className="mb-2 flex items-center justify-between rounded-xl bg-primary/5 px-3 text-xs text-primary"><span>@ {draft.mentions.length} mentioned</span><Button type="button" size="sm" variant="ghost" onClick={()=>update({...draft,mentions:[]})}>Clear</Button></div>}
   <div className="chat-compose-row">
    <label className="chat-attach" title={`Attach PDF, PNG or JPEG · up to ${c.policy.attachmentMegabytes} MB`}><Paperclip className="h-5 w-5"/><input key={fileKey} aria-label="Attach private file" type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>c.policy.attachmentMegabytes*1024*1024){setError(`Attachment must be under ${c.policy.attachmentMegabytes} MB.`);e.target.value='';return;}update({...draft,file});setError('');}}/></label>
    <div className="chat-input-wrap"><textarea ref={textarea} aria-label="Message" placeholder={draft.reply||thread?'Reply…':'Message…'} required rows={1} maxLength={c.policy.maxMessageLength} value={draft.body} onChange={e=>update({...draft,body:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'&&!e.nativeEvent.isComposing&&((e.ctrlKey||e.metaKey)||(!e.shiftKey&&window.matchMedia('(pointer: fine)').matches))){e.preventDefault();submit();}}}/>
     <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" type="button" aria-label="Emoji and mentions" title="Emoji and mentions"><Smile className="h-5 w-5"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>setMentionOpen(true)}><AtSign/>Mention someone</DropdownMenuItem><DropdownMenuSeparator/><div className="grid grid-cols-5 gap-1 p-1" role="group" aria-label="Add emoji">{['😀','👍','❤️','🎉','😊','👋','✅','🙏','💪','📌'].map(emoji=><button key={emoji} type="button" className="rounded-lg p-2 text-lg hover:bg-accent focus-visible:ring-2 focus-visible:ring-primary" aria-label={`Add ${emoji}`} onClick={()=>{update({...draft,body:draft.body.length+emoji.length<=c.policy.maxMessageLength?draft.body+emoji:draft.body});textarea.current?.focus();}}>{emoji}</button>)}</div></DropdownMenuContent></DropdownMenu>
    </div>
    <Button type="submit" size="icon" disabled={send.isPending||!draft.body.trim()||draft.mentions.length>10} className="chat-send" aria-label={send.isPending?'Sending message':'Send message'} title="Send message"><Send className="h-5 w-5"/></Button>
   </div>
   {draft.body.length>c.policy.maxMessageLength-100&&<p className="mt-1 text-right text-[10px] text-muted-foreground">{draft.body.length}/{c.policy.maxMessageLength}</p>}
   <p className="chat-keyboard-hint">Enter to send · Shift + Enter for a new line</p>
  </fieldset><QueryError error={send.error||error}/></form>:<p className="border-t bg-muted/30 p-4 text-sm text-muted-foreground">{thread?'Close replies to return to the conversation. This message is unavailable for new replies.':'Posting is closed or restricted to channel managers.'}</p>}
  <Dialog open={info} onOpenChange={setInfo}><DialogContent><DialogHeader><DialogTitle>{displayName||c.name}</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{c.description||'No description added.'}</p><p className="text-xs text-muted-foreground">{c.kind==='direct'?'Direct message':c.kind==='workforce'?'Event / FEC team':'Private group'}{c.archived_at?' · Archived':''}</p>{c.can_manage&&<Button onClick={()=>{setInfo(false);setManage(true);}}><Settings2 className="mr-2 h-4 w-4"/>Manage group</Button>}</DialogContent></Dialog>
  <Dialog open={manage} onOpenChange={setManage}><DialogContent><DialogHeader><DialogTitle>Manage conversation</DialogTitle></DialogHeader><ChannelManagement id={id} channel={c}/></DialogContent></Dialog>
  <Dialog open={mentionOpen} onOpenChange={setMentionOpen}><DialogContent><DialogHeader><DialogTitle>Mention current members</DialogTitle></DialogHeader><input aria-label="Find a member to mention" className={fieldClass} placeholder="Search names…" value={memberQ} onChange={e=>{setMemberQ(e.target.value);setMemberOffset(0);}}/><QueryError error={members.error}/><div className="space-y-2">{!members.error&&members.data?.items.filter(p=>p.current!==false&&p.id!==userId).map(p=><label className="flex items-center gap-3 rounded-lg border p-3 text-sm" key={p.id}><input type="checkbox" checked={draft.mentions.includes(p.id)} disabled={!draft.mentions.includes(p.id)&&draft.mentions.length>=10} onChange={e=>update({...draft,mentions:e.target.checked?[...draft.mentions,p.id]:draft.mentions.filter(n=>n!==p.id)})}/>{p.name}</label>)}</div><Pager offset={memberOffset} hasMore={members.data?.hasMore} onChange={setMemberOffset}/><Button onClick={()=>setMentionOpen(false)}>Done · {draft.mentions.length} selected</Button></DialogContent></Dialog>
  <Dialog open={!!retract} onOpenChange={open=>{if(!open)setRetract(null);}}><DialogContent><DialogHeader><DialogTitle>Withdraw message</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">The message becomes a withdrawal marker. Its stored history is retained.</p><label className="space-y-2 text-sm">Reason<input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)} minLength={5}/></label><QueryError error={action.error}/><Button variant="destructive" disabled={reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/messages/${retract!.id}/retract`,body:{reason}})}>Withdraw message</Button></DialogContent></Dialog>
 </section>;
}
