import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {hub,useHubAction,PersonPicker,Pager,localDate,dateLabel,type Page,type Person} from './HubControls';
import type {Channel} from '@shared/communications';
export default function CreateChannel({mode,onDone}:{mode:string;onDone:(id:number)=>void}) {
  const [person,setPerson]=useState(''),[kind,setKind]=useState('group'),[team,setTeam]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[end,setEnd]=useState(''),[why,setWhy]=useState(''),[restricted,setRestricted]=useState(false);
  const save=useHubAction(r=>onDone(r.id));
  return <Section title={mode==='direct'?'Start a private conversation':'Create a team channel'}><form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:mode==='direct'?'/direct':'/channels',body:mode==='direct'?{userId:Number(person)}:{name,description,kind,teamId:kind==='workforce'?Number(team):null,startsAt:new Date().toISOString(),endsAt:end?new Date(end).toISOString():null,managersOnly:restricted,reason:why}});}}>{mode==='direct'?<PersonPicker value={person} onChange={setPerson}/>:<><Field label="Channel kind"><select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="group">Private group (invite members)</option><option value="workforce">Event / FEC / mall team (automatic access)</option></select></Field>{kind==='workforce'&&<PersonPicker value={team} onChange={setTeam} teams/>}<Field label="Channel name"><input className={fieldClass} required minLength={3} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Purpose and instructions"><textarea className={fieldClass} maxLength={1500} value={description} onChange={e=>setDescription(e.target.value)}/></Field><Field label="Access ends (your device timezone)"><input type="datetime-local" className={fieldClass} required={kind==='workforce'} value={end} onChange={e=>setEnd(e.target.value)}/></Field><label className="flex gap-2"><input type="checkbox" checked={restricted} onChange={e=>setRestricted(e.target.checked)}/>Only channel managers can post</label><Field label="Reason for creating channel"><input className={fieldClass} required minLength={5} value={why} onChange={e=>setWhy(e.target.value)}/></Field></>}<QueryError error={save.error}/><Button disabled={save.isPending||(mode==='direct'&&!person)||(kind==='workforce'&&!team)}>Create</Button></form></Section>;
}
