import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Field, Section, QueryError, fieldClass } from '@/components/hr/Operations';
import { hub, Pager, useHubAction, localDate, dateLabel, type Page } from './HubControls';
import { bulletinInput, type Bulletin, type Channel } from '@shared/communications';

export default function HubAnnouncements({context}:{context:any}) {
  const [managed,setManaged]=useState(false),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<number|null>(null),[create,setCreate]=useState(false);
  const items=useQuery<Page<Bulletin>>({queryKey:[`${hub}/bulletins?managed=${managed}&q=${encodeURIComponent(q)}&offset=${offset}`],refetchInterval:30000,refetchIntervalInBackground:false});
  return <div className="space-y-5"><div className="flex flex-wrap items-center gap-3"><input className={fieldClass+' max-w-sm'} aria-label="Search announcements" placeholder="Search announcements and briefings" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/>{context.canManage&&<><label className="text-sm"><input type="checkbox" checked={managed} onChange={e=>{setManaged(e.target.checked);setOffset(0);}}/> Manage drafts and publications</label><Button onClick={()=>{setCreate(!create);setSelected(null);}}>New announcement</Button></>}<Button variant="outline" onClick={()=>items.refetch()}>Refresh</Button></div><QueryError error={items.error}/>{create&&<Editor context={context} onDone={id=>{setCreate(false);setSelected(id);setManaged(true);}}/>}{selected&&<BulletinDetail key={selected} id={selected} context={context} onClose={()=>setSelected(null)}/>}
    {items.isLoading&&<p>Loading announcements…</p>}{items.data&&!items.data.items.length&&<Section title="No announcements to show"><p>{managed?'Create a draft, review the audience and publish it when ready.':'Published notices and event briefings addressed to you will appear here.'}</p></Section>}
    <div className="grid gap-4 md:grid-cols-2">{items.data?.items.map(b=><article key={b.id} className="space-y-3 rounded-xl border bg-card p-5"><div className="flex flex-wrap gap-2">{b.pinned&&<Badge>Pinned</Badge>}<Badge variant="outline">{b.status==='published'&&new Date(b.publish_at)>new Date()?'Scheduled':b.status}</Badge>{b.requires_acknowledgement&&<Badge variant="outline">{b.acknowledged_at?'Acknowledged':'Acknowledgement required'}</Badge>}</div><h2 className="text-lg font-semibold">{b.title}</h2><p className="whitespace-pre-wrap break-words text-sm">{b.body.slice(0,200)}{b.body.length>200?'…':''}</p><p className="text-xs text-muted-foreground">{b.author_name} · {dateLabel(b.publish_at)} · {b.audience}{b.target?' / '+b.target:''}</p><Button variant="outline" onClick={()=>{setSelected(b.id);setCreate(false);}}>Open announcement</Button></article>)}</div><Pager offset={offset} hasMore={items.data?.hasMore} onChange={setOffset}/></div>;
}
function Editor({context,value,onDone}:{context:any;value?:Bulletin;onDone:(id:number)=>void}) {
  const [title,setTitle]=useState(value?.title||''),[body,setBody]=useState(value?.body||''),[audience,setAudience]=useState(value?.audience||(context.canPublishCompany?'all':context.canPublishDepartment?'department':'channel')),[target,setTarget]=useState(value?.target||(!context.canPublishCompany&&context.canPublishDepartment?context.department||'':'')),[publish,setPublish]=useState(localDate(value?.publish_at)),[expiry,setExpiry]=useState(value?.expires_at?localDate(value.expires_at):''),[ack,setAck]=useState(value?.requires_acknowledgement||false),[pin,setPin]=useState(value?.pinned||false),[why,setWhy]=useState(''),[error,setError]=useState('');
  const [channelQ,setChannelQ]=useState(''),[channelOffset,setChannelOffset]=useState(0);
  const channels=useQuery<Page<Channel>>({queryKey:[`${hub}/channels?q=${encodeURIComponent(channelQ)}&offset=${channelOffset}`],enabled:audience==='channel'});
  const save=useHubAction(r=>onDone(r.id));
  return <Section title={value?'Edit announcement draft':'Draft an announcement or event briefing'}><form className="space-y-3" onSubmit={e=>{e.preventDefault();const v={title,body,audience,target,publishAt:publish?new Date(publish).toISOString():'',expiresAt:expiry?new Date(expiry).toISOString():null,requiresAcknowledgement:ack,pinned:pin,reason:why};const parsed=bulletinInput.safeParse(v);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join('; '));return;}setError('');save.mutate({path:value?`/bulletins/${value.id}`:'/bulletins',method:value?'PATCH':'POST',body:value?{version:value.version,definition:parsed.data}:parsed.data});}}><Field label="Title"><input required minLength={3} maxLength={180} className={fieldClass} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Announcement text"><textarea required rows={6} maxLength={20000} className={fieldClass} value={body} onChange={e=>setBody(e.target.value)}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Audience"><select className={fieldClass} value={audience} onChange={e=>{setAudience(e.target.value);setTarget(e.target.value==='department'&&!context.canPublishCompany&&context.canPublishDepartment?context.department||'':'');}}>{context.canPublishCompany&&<option value="all">Whole company</option>}{context.canPublishDepartment&&<option value="department">Department</option>}{context.canPublishCompany&&<option value="role">Role</option>}<option value="channel">Team / event channel</option></select></Field>{audience==='department'&&<Field label="Department (exact name)"><input required className={fieldClass} value={target} onChange={e=>setTarget(e.target.value)}/></Field>}{audience==='role'&&<Field label="Recipient role"><select required className={fieldClass} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose role…</option>{(context.roles as string[]).map(r=><option key={r}>{r}</option>)}</select></Field>}</div>
    {audience==='channel'&&<><input className={fieldClass} aria-label="Find briefing channel" placeholder="Find a channel you manage" value={channelQ} onChange={e=>{setChannelQ(e.target.value);setChannelOffset(0);}}/><Field label="Channel"><select required className={fieldClass} value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose managed channel…</option>{target&&!channels.data?.items.some(c=>String(c.id)===target)&&<option value={target}>Selected #{target}</option>}{channels.data?.items.filter(c=>c.can_manage&&!c.archived_at).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Pager offset={channelOffset} hasMore={channels.data?.hasMore} onChange={setChannelOffset}/><QueryError error={channels.error}/></>}
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Publish from (device timezone)"><input required type="datetime-local" className={fieldClass} value={publish} onChange={e=>setPublish(e.target.value)}/></Field><Field label="Expires at (optional)"><input type="datetime-local" className={fieldClass} value={expiry} onChange={e=>setExpiry(e.target.value)}/></Field></div><div className="flex flex-wrap gap-5"><label className="text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> Require explicit acknowledgement</label><label className="text-sm"><input type="checkbox" checked={pin} onChange={e=>setPin(e.target.checked)}/> Pin announcement</label></div><Field label="Reason for this draft"><input required minLength={5} className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><QueryError error={save.error||error}/><Button disabled={save.isPending}>Save draft for review</Button><p className="text-sm text-muted-foreground">Review the saved text and audience before publishing. Publication becomes visible at its scheduled time when the application is available.</p></form></Section>;
}
function BulletinDetail({id,context,onClose}:{id:number;context:any;onClose:()=>void}) {
  const [edit,setEdit]=useState(false),[why,setWhy]=useState(''),[receiptOffset,setReceiptOffset]=useState(0);
  const query=useQuery<Bulletin>({queryKey:[`${hub}/bulletins/${id}`]});
  const b=query.data;
  const receipts=useQuery<Page<any>>({queryKey:[`${hub}/bulletins/${id}/receipts?offset=${receiptOffset}`],enabled:!!b?.can_manage});
  const action=useHubAction();
  if(edit&&b)return <Editor context={context} value={b} onDone={()=>setEdit(false)}/>;
  return <Section title={b?.title||'Announcement'}><Button size="sm" variant="outline" onClick={onClose}>Close announcement</Button><QueryError error={query.error||action.error}/>{b&&<><p className="text-sm text-muted-foreground">{b.author_name} · Audience: {b.audience}{b.target?' / '+b.target:''} · {b.status} · Version {b.version}</p><p className="text-xs">Visible from {dateLabel(b.publish_at)}{b.expires_at?' until '+dateLabel(b.expires_at):''}</p><div className="whitespace-pre-wrap break-words rounded border p-4">{b.body}</div>{b.status==='published'&&new Date(b.publish_at)<=new Date()&&(!b.expires_at||new Date(b.expires_at)>new Date())&&<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!!b.read_at||action.isPending} onClick={()=>action.mutate({path:`/bulletins/${id}/read`,body:{}})}>{b.read_at?'Read '+dateLabel(b.read_at):'Mark as read'}</Button>{b.requires_acknowledgement&&<Button disabled={!b.read_at||!!b.acknowledged_at||action.isPending} onClick={()=>action.mutate({path:`/bulletins/${id}/acknowledge`,body:{}})}>{b.acknowledged_at?'Acknowledged':'I acknowledge this announcement'}</Button>}</div>}{b.requires_acknowledgement&&<p className="text-xs text-muted-foreground">Acknowledgement records that you received this exact notice. It does not approve leave, payroll or a contract.</p>}
    {b.can_manage&&<div className="space-y-3 border-t pt-4"><Field label="Reason for publication or change"><input className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><div className="flex flex-wrap gap-2">{b.status==='draft'&&<><Button variant="outline" onClick={()=>setEdit(true)}>Edit draft</Button><Button disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/bulletins/${id}/publish`,body:{version:b.version,reason:why}})}>Publish to selected audience</Button></>}{b.status!=='archived'&&<><Button variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/bulletins/${id}/pin`,body:{version:b.version,reason:why}})}>{b.pinned?'Unpin':'Pin'}</Button><Button variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/bulletins/${id}/archive`,body:{version:b.version,reason:why}})}>Archive</Button></>}</div><p className="text-xs text-muted-foreground">Published wording is preserved. Publish a new announcement for corrections.</p><details><summary className="cursor-pointer">Read and acknowledgement receipts</summary><QueryError error={receipts.error}/>{receipts.data?.items.map((r,i)=><p key={i} className="text-sm my-2">{r.name} · Read {dateLabel(r.read_at)} · Acknowledged {dateLabel(r.acknowledged_at)}</p>)}{receipts.data&&!receipts.data.items.length&&<p className="text-sm">No receipts recorded.</p>}<Pager offset={receiptOffset} hasMore={receipts.data?.hasMore} onChange={setReceiptOffset}/></details></div>}</>}</Section>;
}
