import { useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Field, Section, QueryError, fieldClass } from '@/components/hr/Operations';
import { hub, useHubAction, PersonPicker, Pager, localDate, dateLabel, type Page, type Person } from './HubControls';
import type { Channel, CommMessage, CommunicationPolicy } from '@shared/communications';

export default function HubChannels({ context }: { context: any }) {
  const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState<number|null>(null),[create,setCreate]=useState('');
  const channels=useQuery<Page<Channel>>({queryKey:[`${hub}/channels?q=${encodeURIComponent(q)}&offset=${offset}`],refetchInterval:20000,refetchIntervalInBackground:false});
  return <div className="space-y-4"><div className="flex flex-wrap gap-2">{context?.policy.definition.directMessages&&<Button variant="outline" onClick={()=>setCreate(create==='direct'?'':'direct')}>New direct message</Button>}{context?.canManage&&<Button onClick={()=>setCreate(create==='group'?'':'group')}>Create channel</Button>}<Button variant="outline" onClick={()=>channels.refetch()}>Refresh</Button></div>
    {create&&<CreateChannel mode={create} onDone={id=>{setCreate('');setSelected(id);}}/>}
    <div className="grid gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><Section title="Conversations"><input className={fieldClass} aria-label="Find conversations" placeholder="Search conversation names" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><QueryError error={channels.error}/>{channels.isLoading&&<p>Loading conversations…</p>}{channels.data?.items.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={'block w-full rounded-lg border p-3 text-left '+(selected===c.id?'border-primary bg-primary/5':'')}><strong className="block break-words">{c.name}</strong><span className="text-xs text-muted-foreground">{c.kind==='workforce'?'Event / FEC team':c.kind==='direct'?'Direct message':'Private group'}{c.archived_at?' · Archived':''}{c.muted?' · Muted':''}</span><div className="flex gap-1 mt-1">{!c.muted&&Number(c.unread)>0&&<Badge>{c.unread} unread</Badge>}{Number(c.mentions)>0&&<Badge variant="outline">{c.mentions} mentions</Badge>}</div></button>)}{channels.data&&!channels.data.items.length&&<p className="text-sm text-muted-foreground">No conversations yet. Workforce channels appear when you have current access.</p>}<Pager offset={offset} hasMore={channels.data?.hasMore} onChange={setOffset}/></Section>
    {selected?<Conversation key={selected} id={selected} userId={context.userId} muted={channels.data?.items.find(c=>c.id===selected)?.muted||false}/>:<Section title="Your workspace"><p>Select a conversation or start one with an available colleague.</p><p className="text-sm text-muted-foreground">Messages refresh while this tab is open. Event and FEC access follows dated team memberships, accepted shifts and supervisor grants. Confidential HR cases belong in the HR Helpdesk.</p><a className="underline" href="/helpdesk">Open HR Helpdesk</a></Section>}</div></div>;
}
function CreateChannel({mode,onDone}:{mode:string;onDone:(id:number)=>void}) {
  const [person,setPerson]=useState(''),[kind,setKind]=useState('group'),[team,setTeam]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[end,setEnd]=useState(''),[why,setWhy]=useState(''),[restricted,setRestricted]=useState(false);
  const save=useHubAction(r=>onDone(r.id));
  return <Section title={mode==='direct'?'Start a private conversation':'Create a team channel'}><form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:mode==='direct'?'/direct':'/channels',body:mode==='direct'?{userId:Number(person)}:{name,description,kind,teamId:kind==='workforce'?Number(team):null,startsAt:new Date().toISOString(),endsAt:end?new Date(end).toISOString():null,managersOnly:restricted,reason:why}});}}>{mode==='direct'?<PersonPicker value={person} onChange={setPerson}/>:<><Field label="Channel kind"><select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="group">Private group (invite members)</option><option value="workforce">Event / FEC / mall team (automatic access)</option></select></Field>{kind==='workforce'&&<PersonPicker value={team} onChange={setTeam} teams/>}<Field label="Channel name"><input className={fieldClass} required minLength={3} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Purpose and instructions"><textarea className={fieldClass} maxLength={1500} value={description} onChange={e=>setDescription(e.target.value)}/></Field><Field label="Access ends (your device timezone)"><input type="datetime-local" className={fieldClass} required={kind==='workforce'} value={end} onChange={e=>setEnd(e.target.value)}/></Field><label className="flex gap-2"><input type="checkbox" checked={restricted} onChange={e=>setRestricted(e.target.checked)}/>Only channel managers can post</label><Field label="Reason for creating channel"><input className={fieldClass} required minLength={5} value={why} onChange={e=>setWhy(e.target.value)}/></Field></>}<QueryError error={save.error}/><Button disabled={save.isPending||(mode==='direct'&&!person)||(kind==='workforce'&&!team)}>Create</Button></form></Section>;
}
function Conversation({id,userId,muted}:{id:number;userId:number;muted:boolean}) {
  const [q,setQ]=useState(''),[before,setBefore]=useState<number|undefined>(),[manage,setManage]=useState(false),[body,setBody]=useState(''),[file,setFile]=useState<File|null>(null),[reply,setReply]=useState<number|null>(null),[mentions,setMentions]=useState<number[]>([]),[retract,setRetract]=useState<number|null>(null),[reason,setReason]=useState('');
  const [fileKey,setFileKey]=useState(0),pending=useRef({signature:'',key:''});
  const channel=useQuery<Channel&{policy:CommunicationPolicy}>({queryKey:[`${hub}/channels/${id}`],refetchInterval:20000,refetchIntervalInBackground:false});
  const messages=useQuery<Page<CommMessage>>({queryKey:[`${hub}/channels/${id}/messages?q=${encodeURIComponent(q)}${before?'&before='+before:''}`],refetchInterval:before?false:20000,refetchIntervalInBackground:false});
  const [memberQ,setMemberQ]=useState('');
  const members=useQuery<Page<Person>>({queryKey:[`${hub}/channels/${id}/members?q=${encodeURIComponent(memberQ)}`]});
  const send=useHubAction(()=>{setBody('');setFile(null);setFileKey(v=>v+1);setReply(null);setMentions([]);setBefore(undefined);pending.current={signature:'',key:''};});
  const action=useHubAction(()=>{setRetract(null);setReason('');});
  const c=channel.data;
  if(channel.error||!c)return <Section title="Conversation"><QueryError error={channel.error}/>{!channel.error&&<p>Loading conversation…</p>}</Section>;
  const shown=messages.data?.items||[],latest=shown[0]?.id;
  return <Section title={c.name}><p className="whitespace-pre-wrap text-sm">{c.description}</p><p className="text-xs text-muted-foreground">{c.ends_at?'Access window ends '+dateLabel(c.ends_at)+'. ':''}Visible message history: {c.policy.historyDays} days. {c.archived_at?'Archived; messages are read-only.':''}</p><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>action.mutate({path:`/channels/${id}/state`,body:{muted:!muted}})}>{muted?'Unmute':'Mute unread badge'}</Button><Button variant="outline" size="sm" disabled={!latest||action.isPending||!!q||!!before} onClick={()=>action.mutate({path:`/channels/${id}/state`,body:{lastReadId:latest}})}>Mark displayed messages read</Button>{c.can_manage&&<Button variant="outline" size="sm" onClick={()=>setManage(!manage)}>{manage?'Close management':'Manage channel'}</Button>}</div>
    {manage&&<ChannelManagement id={id} channel={c}/>}
    <input className={fieldClass} aria-label="Search messages in conversation" placeholder="Search messages in this conversation" value={q} onChange={e=>{setQ(e.target.value);setBefore(undefined);}}/>
    <QueryError error={messages.error||action.error}/><div className="max-h-[520px] space-y-3 overflow-y-auto rounded-lg bg-muted/30 p-3" aria-label="Conversation messages">{messages.isLoading&&<p>Loading messages…</p>}{!shown.length&&!messages.isLoading&&<p>No messages to show.</p>}{[...shown].reverse().map(m=><article key={m.id} className={'rounded-lg border bg-background p-3 '+(m.author_id===userId?'ml-5':'mr-5')}><div className="flex flex-wrap justify-between gap-2 text-xs"><strong>{m.author_name}</strong><time>{dateLabel(m.created_at)}</time></div>{m.reply_to&&<p className="text-xs text-muted-foreground">Reply to message #{m.reply_to}</p>}<p className="my-2 whitespace-pre-wrap break-words">{m.body}</p>{m.mentions.includes(userId)&&<Badge variant="outline">You were mentioned</Badge>}{m.attachment_name&&<a className="block text-sm underline" href={`${hub}/channels/${id}/messages/${m.id}/file`} target="_blank" rel="noreferrer">Download {m.attachment_name} ({Math.ceil((m.attachment_size||0)/1024)} KB)</a>}<div className="mt-2 flex gap-3">{!m.retracted_at&&c.can_post&&<button className="text-xs underline" onClick={()=>setReply(m.id)}>Reply</button>}{!m.retracted_at&&(m.author_id===userId||c.can_manage)&&<button className="text-xs underline" onClick={()=>setRetract(m.id)}>Withdraw</button>}</div></article>)}</div><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!messages.data?.hasMore} onClick={()=>setBefore(shown[shown.length-1]?.id)}>Older messages</Button><Button size="sm" variant="outline" disabled={!before} onClick={()=>setBefore(undefined)}>Latest messages</Button></div>
    {retract&&<div className="space-y-2 rounded border p-3"><Field label="Reason for withdrawing message"><input className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="text-xs">The conversation will show a withdrawal marker. Stored history is retained.</p><Button variant="destructive" disabled={reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/messages/${retract}/retract`,body:{reason}})}>Withdraw message #{retract}</Button> <Button variant="outline" onClick={()=>setRetract(null)}>Cancel</Button></div>}
    {c.can_post?<form className="space-y-3 border-t pt-4" onSubmit={e=>{e.preventDefault();const signature=JSON.stringify([body,reply,mentions,file?.name,file?.size,file?.lastModified]);if(pending.current.signature!==signature)pending.current={signature,key:crypto.randomUUID()};const input={body,replyTo:reply,mentions,requestKey:pending.current.key};let data:any=input;if(file){data=new FormData();data.append('message',JSON.stringify(input));data.append('file',file);}send.mutate({path:`/channels/${id}/messages`,body:data});}}>{reply&&<p className="text-sm">Replying to #{reply} <button type="button" className="underline" onClick={()=>setReply(null)}>Cancel reply</button></p>}<Field label="Message"><textarea className={fieldClass} rows={3} required maxLength={c.policy.maxMessageLength} value={body} onChange={e=>setBody(e.target.value)}/></Field><details><summary className="cursor-pointer text-sm">Mention a current member</summary><input className={fieldClass} aria-label="Find a member to mention" placeholder="Find member" value={memberQ} onChange={e=>setMemberQ(e.target.value)}/><div className="flex flex-wrap gap-3 p-2">{members.data?.items.filter(p=>p.current!==false).map(p=><label className="text-sm" key={p.id}><input type="checkbox" checked={mentions.includes(p.id)} onChange={e=>setMentions(e.target.checked?[...mentions,p.id]:mentions.filter(n=>n!==p.id))}/>{p.name}</label>)}</div><QueryError error={members.error}/></details><Field label={`Private attachment — PDF, PNG or JPEG up to ${c.policy.attachmentMegabytes} MB`}><input key={fileKey} type="file" accept=".pdf,.png,.jpg,.jpeg" className={fieldClass} onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><QueryError error={send.error}/><Button disabled={send.isPending||!body.trim()||mentions.length>10}>{send.isPending?'Saving message…':'Send message'}</Button><p className="text-xs text-muted-foreground">Sent messages keep their original wording. Post a reply for corrections. A sent message is not an HR approval.</p></form>:<p className="text-sm text-muted-foreground">Posting is closed or restricted to channel managers.</p>}</Section>;
}
function ChannelManagement({id,channel}:{id:number;channel:Channel}) {
  const [person,setPerson]=useState(''),[start,setStart]=useState(localDate()),[end,setEnd]=useState(''),[why,setWhy]=useState(''),[offset,setOffset]=useState(0),[q,setQ]=useState('');
  const action=useHubAction();
  const members=useQuery<Page<Person>>({queryKey:[`${hub}/channels/${id}/members?q=${encodeURIComponent(q)}&offset=${offset}`]});
  const history=useQuery<Page<any>>({queryKey:[`${hub}/channels/${id}/history?offset=0`]});
  return <div className="space-y-3 rounded-lg border p-4"><Field label="Reason for channel change"><input className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/settings`,body:{version:channel.version,reason:why,archived:!!channel.archived_at,managersOnly:!channel.managers_only}})}>{channel.managers_only?'Allow members to post':'Restrict posting to managers'}</Button><Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/settings`,body:{version:channel.version,reason:why,archived:!channel.archived_at,managersOnly:channel.managers_only}})}>{channel.archived_at?'Reopen channel':'Archive channel'}</Button></div><QueryError error={action.error}/>
    {channel.kind==='group'&&!channel.archived_at&&<><h3 className="font-medium">Add or update membership</h3><PersonPicker value={person} onChange={setPerson}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Member access starts (device timezone)"><input type="datetime-local" className={fieldClass} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Member access ends (required for temporary staff)"><input type="datetime-local" className={fieldClass} value={end} onChange={e=>setEnd(e.target.value)}/></Field></div><Button size="sm" disabled={!person||!start||why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/members`,body:{version:channel.version,member:{userId:Number(person),startsAt:new Date(start).toISOString(),endsAt:end?new Date(end).toISOString():null,reason:why}}})}>Save membership</Button></>}
    {channel.kind==='workforce'&&<p className="text-sm">Members follow the workforce team, accepted shifts starting within 24 hours and active supervisor grants. Manage assignments in <a href="/workforce" className="underline">Workforce</a>.</p>}
    <input className={fieldClass} aria-label="Find channel members" placeholder="Find channel members" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><QueryError error={members.error}/>{members.data?.items.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 text-sm"><span>{p.name} · {p.current?'Current':p.removed_at?'Removed':'Outside access dates'}{p.ends_at?' · Until '+dateLabel(p.ends_at):''}</span>{channel.kind==='group'&&!p.removed_at&&<Button size="sm" variant="outline" disabled={why.trim().length<5||action.isPending} onClick={()=>action.mutate({path:`/channels/${id}/members/${p.id}/remove`,body:{version:channel.version,reason:why}})}>Remove access</Button>}</div>)}<Pager offset={offset} hasMore={members.data?.hasMore} onChange={setOffset}/><details><summary>Recent channel history (latest 25)</summary>{history.data?.items.map(h=><p className="text-xs my-2" key={h.version}>Version {h.version} · {dateLabel(h.created_at)} · {h.reason}</p>)}<QueryError error={history.error}/></details></div>;
}
