import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { MessageCircle, Users, Paperclip, History, Save, ShieldCheck, TextCursorInput } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Switch } from '@/components/ui/switch';
import { Field, QueryError, fieldClass } from '@/components/hr/Operations';
import { useToast } from '@/hooks/use-toast';
import { communicationPolicy, type CommunicationPolicy } from '@shared/communications';
import { hub, useHubAction, Pager, dateLabel, type Page } from './HubControls';

export default function HubPolicy({ current }: { current: { version: number; definition: CommunicationPolicy } }) {
  const [definition, setDefinition] = useState(current.definition), [why, setWhy] = useState(''), [error, setError] = useState(''), [offset, setOffset] = useState(0), [showHistory, setShowHistory] = useState(false);
  const { toast } = useToast(), action = useHubAction(() => toast({ title: 'Communication rules saved' }));
  const history = useQuery<Page<{ version: number; created_at: string; reason: string; snapshot: { definition: CommunicationPolicy } }>>({ queryKey: [`${hub}/policy/history?offset=${offset}`], enabled: showHistory });
  const changed = JSON.stringify(definition) !== JSON.stringify(current.definition);
  return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Communication rules</h2><p className="mt-1 text-sm text-muted-foreground">Set the team’s communication options and limits.</p></div><Badge variant="outline">{current.version ? `Version ${current.version}` : 'Default policy'}</Badge></header>
    <form className="space-y-5" onSubmit={e => { e.preventDefault(); const parsed = communicationPolicy.safeParse(definition); if (!parsed.success) { setError(parsed.error.issues.map(issue => issue.message).join('; ')); return; } setError(''); action.mutate({ path: '/policy', method: 'PUT', body: { version: current.version, definition: parsed.data, reason: why } }); }}>
      <fieldset disabled={action.isPending} className="space-y-5"><div className="grid gap-4 md:grid-cols-2">{[
        { key: 'directMessages' as const, label: 'Direct messages', text: 'Let eligible colleagues start private conversations.', Icon: MessageCircle },
        { key: 'groupCreation' as const, label: 'Private team groups', text: 'Let authorized managers create private groups.', Icon: Users },
      ].map(item => <div key={item.key} className="flex items-start gap-4 rounded-2xl border bg-card p-5"><item.Icon className="mt-1 h-6 w-6 shrink-0 text-primary"/><div className="flex-1"><label htmlFor={item.key} className="font-semibold">{item.label}</label><p className="mt-1 text-sm text-muted-foreground">{item.text}</p></div><Switch id={item.key} checked={definition[item.key]} onCheckedChange={value => setDefinition({ ...definition, [item.key]: value })}/></div>)}</div>
      <div className="grid gap-4 lg:grid-cols-3">{[
        { key: 'maxMessageLength' as const, label: 'Message character limit', min: 200, max: 12000, unit: 'characters', text: 'Maximum length of each chat message.', Icon: TextCursorInput },
        { key: 'attachmentMegabytes' as const, label: 'Attachment size limit', min: 1, max: 10, unit: 'MB', text: 'One PDF, PNG or JPEG per message.', Icon: Paperclip },
        { key: 'historyDays' as const, label: 'Visible message history', min: 30, max: 3650, unit: 'days', text: 'How far back messages and files can be accessed.', Icon: History },
      ].map(item => <div key={item.key} className="space-y-3 rounded-2xl border bg-card p-5"><item.Icon className="h-6 w-6 text-primary"/><Field label={item.label}><input required type="number" min={item.min} max={item.max} className={fieldClass + ' text-lg font-semibold'} value={definition[item.key]} onChange={e => setDefinition({ ...definition, [item.key]: Number(e.target.value) })}/></Field><p className="text-xs text-muted-foreground">{item.min.toLocaleString()}–{item.max.toLocaleString()} {item.unit}</p><p className="text-sm text-muted-foreground">{item.text}</p></div>)}</div>
      <div className="flex gap-3 rounded-xl bg-primary/5 p-4"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-primary"/><p className="text-sm text-muted-foreground">Private chats remain limited to their participants. History limits hide older records; they do not delete stored messages or files. Team access dates still apply.</p></div>
      <div className="space-y-4 rounded-2xl border bg-card p-5"><Field label="Reason for policy change"><input required minLength={5} maxLength={2000} className={fieldClass} placeholder="Explain why these rules are changing" value={why} onChange={e => setWhy(e.target.value)}/></Field><QueryError error={action.error || error}/><div className="flex flex-wrap items-center gap-3"><Button disabled={!changed || why.trim().length < 5 || action.isPending}><Save className="mr-2 h-4 w-4"/>{action.isPending ? 'Saving…' : 'Save communication rules'}</Button><Button type="button" variant="outline" disabled={!changed || action.isPending} onClick={() => { setDefinition(current.definition); setWhy(''); setError(''); }}>Reset changes</Button>{changed && <Badge variant="secondary">Unsaved changes</Badge>}</div></div></fieldset>
    </form>
    <section className="space-y-4 rounded-2xl border bg-card p-5"><Button variant="ghost" className="gap-2" aria-expanded={showHistory} onClick={() => setShowHistory(!showHistory)}><History className="h-4 w-4"/>{showHistory ? 'Hide policy history' : 'View policy history'}</Button>{showHistory && <><QueryError error={history.error}/>{history.isLoading && <p role="status">Loading policy history…</p>}{!history.error && history.data && <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Version</th><th className="p-3">Message / file / history limits</th><th className="p-3">Change reason</th></tr></thead><tbody>{history.data.items.map(row => <tr key={row.version} className="border-b"><td className="p-3">{row.version}<p className="text-xs text-muted-foreground">{dateLabel(row.created_at)}</p></td><td className="p-3">{row.snapshot.definition.maxMessageLength.toLocaleString()} chars · {row.snapshot.definition.attachmentMegabytes} MB · {row.snapshot.definition.historyDays} days<p className="mt-1 text-xs text-muted-foreground">Direct messages {row.snapshot.definition.directMessages ? 'on' : 'off'} · Group creation {row.snapshot.definition.groupCreation ? 'on' : 'off'}</p></td><td className="p-3">{row.reason}</td></tr>)}</tbody></table>{!history.data.items.length && <p className="py-6 text-sm text-muted-foreground">Using the default policy. No saved changes yet.</p>}</div>}<Pager offset={offset} hasMore={!history.error && history.data?.hasMore} onChange={setOffset}/></>}</section>
  </div>;
}
