import {readFileSync} from 'node:fs';
import {beforeAll,afterAll,beforeEach,test,expect,vi} from 'vitest';
import {PGlite} from '@electric-sql/pglite';
import {drizzle} from 'drizzle-orm/pglite';
import express from 'express';
const ctx=vi.hoisted(()=>({db:null as any,helpdesk:vi.fn(),reminders:vi.fn(),reports:vi.fn()}));
vi.mock('../server/db',()=>({get db(){return ctx.db}}));
vi.mock('../server/services/helpdesk-automation',()=>({runHelpdeskAutomation:ctx.helpdesk}));
vi.mock('../server/services/operational-reminders',()=>({runOperationalReminders:ctx.reminders}));
vi.mock('../server/services/reportWorkspace',()=>({runReportSchedules:ctx.reports}));
import {runScheduledJobs} from '../server/services/scheduled-jobs';
import router from '../server/routes/scheduled-jobs';
let pg:PGlite,server:any,url:string;
beforeAll(async()=>{pg=new PGlite();await pg.exec(readFileSync(new URL('../migrations/0054_scheduled_jobs.sql',import.meta.url),'utf8'));ctx.db=drizzle(pg);const app=express();app.use('/internal/scheduled-jobs',router);server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));url='http://127.0.0.1:'+server.address().port+'/internal/scheduled-jobs';});
beforeEach(async()=>{vi.resetAllMocks();for(const fn of [ctx.helpdesk,ctx.reminders,ctx.reports])fn.mockResolvedValue({skipped:false});await pg.exec("UPDATE scheduled_job_runtime SET next_run_at=now()-interval '1 minute',lease_id=NULL,lease_until=NULL,last_status=NULL,consecutive_failures=0");});
afterAll(async()=>{vi.unstubAllEnvs();await new Promise<void>(r=>server.close(()=>r()));await pg.close();});
test('successful jobs are durable and repeat triggers cannot execute them early',async()=>{expect((await runScheduledJobs()).every(j=>j.status==='succeeded')).toBe(true);expect((await runScheduledJobs()).every(j=>j.status==='not_due_or_running')).toBe(true);expect(ctx.helpdesk).toHaveBeenCalledTimes(1);expect((await pg.query("SELECT * FROM scheduled_job_runtime WHERE last_status='succeeded'")).rows).toHaveLength(3);});
test('disabled reports are healthy while partial report failures are visible',async()=>{ctx.reports.mockResolvedValueOnce({skipped:true,reason:'disabled',failed:0});expect((await runScheduledJobs())[2].status).toBe('succeeded');await pg.exec("UPDATE scheduled_job_runtime SET next_run_at=now()-interval '1 minute' WHERE name='reports'");ctx.reports.mockResolvedValueOnce({created:1,failed:1});expect((await runScheduledJobs())[2].status).toBe('failed');});
test('failure schedules a retry while other jobs still run; expired crash leases are reclaimed',async()=>{ctx.helpdesk.mockRejectedValueOnce(new Error('private details'));expect((await runScheduledJobs())[0].status).toBe('failed');const failed=(await pg.query("SELECT * FROM scheduled_job_runtime WHERE name='helpdesk'")).rows[0] as any;expect(failed.consecutive_failures).toBe(1);expect(failed.lease_id).toBeNull();await pg.exec("UPDATE scheduled_job_runtime SET next_run_at=now()-interval '1 minute',lease_until=now()-interval '1 minute',last_status='running' WHERE name='helpdesk'");expect((await runScheduledJobs())[0].status).toBe('succeeded');});
test('a current lease prevents execution and unauthorized triggers cannot run jobs',async()=>{await pg.exec("UPDATE scheduled_job_runtime SET lease_until=now()+interval '30 minutes' WHERE name='helpdesk'");expect((await runScheduledJobs())[0].status).toBe('not_due_or_running');expect(ctx.helpdesk).not.toHaveBeenCalled();vi.stubEnv('SCHEDULER_SECRET','');expect((await fetch(url,{method:'POST'})).status).toBe(503);vi.stubEnv('SCHEDULER_SECRET','s'.repeat(48));expect((await fetch(url,{method:'POST',headers:{Authorization:'Bearer wrong'}})).status).toBe(401);expect((await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+'s'.repeat(48)}})).status).toBe(200);});
