import {useState,type ReactNode} from 'react';
import {Link,useLocation,useRoute} from 'wouter';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,Star,Plus,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {apiJson} from '@/lib/queryClient';
import {reviewRubric,reviewStatuses,reviewStatusLabels,criterionKeys,type Criterion,type RatingValues,type ReviewAssignment,type ReviewConfig,type AssignmentReviewList,type AssignmentReviewDetail,type AssignmentReviewRow} from '@shared/assignmentReviews';

const selectClass='w-full rounded-md border border-input bg-background px-3 py-2 text-sm';
const stamp=(v:string,zone:string)=>new Date(v).toLocaleString([],{timeZone:zone,dateStyle:'medium',timeStyle:'short'});
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>;}
const emptyRatings=():RatingValues=>({punctuality:null,service:null,teamwork:null,roleSkill:null,evidence:{punctuality:'',service:'',teamwork:'',roleSkill:''},roleExpectation:'',summary:'',improvementActions:''});
const valuesFrom=(row:RatingValues):RatingValues=>({punctuality:row.punctuality,service:row.service,teamwork:row.teamwork,roleSkill:row.roleSkill,evidence:{...row.evidence},roleExpectation:row.roleExpectation,summary:row.summary,improvementActions:row.improvementActions});
function useReviewMutation(){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({url,body}:{url:string;body:unknown})=>apiJson<{id:number;version:number}>(url,{method:'POST',body}),onSuccess:async()=>{await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/assignment-reviews')||String(q.queryKey[0]).startsWith('/api/team-overview')});toast({title:'Review saved'});},onError:async(error)=>{toast({title:'Unable to save',description:error.message,variant:'destructive'});if(error.message.startsWith('409:'))await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/assignment-reviews')});}});}
function RatingFields({value,change}:{value:RatingValues;change:(value:RatingValues)=>void}){
  const set=(key:Criterion,score:string)=>change({...value,[key]:score===''?null:Number(score)});
  return <div className="space-y-4"><Field label="Role expectations for this assignment"><Textarea value={value.roleExpectation} onChange={e=>change({...value,roleExpectation:e.target.value})} minLength={10} maxLength={1000} required placeholder="Describe the agreed duties, quality and safety expectations."/></Field>
    {reviewRubric.criteria.map(c=><div key={c.key} className="space-y-3 rounded-md border p-4"><Field label={c.label}><select className={selectClass} value={value[c.key]??''} onChange={e=>set(c.key,e.target.value)}><option value="">Not observed (N/A)</option>{reviewRubric.anchors.map((label,i)=><option key={label} value={i+1}>{i+1} — {label}</option>)}</select></Field><p className="text-sm text-muted-foreground">{c.guidance}</p><Field label={`${c.label} evidence`}><Textarea value={value.evidence[c.key]} onChange={e=>change({...value,evidence:{...value.evidence,[c.key]:e.target.value}})} minLength={10} maxLength={1500} required placeholder="Give a concrete example, or explain why this was not observed."/></Field></div>)}
    <Field label="Review summary"><Textarea value={value.summary} onChange={e=>change({...value,summary:e.target.value})} minLength={10} maxLength={2000} required/></Field><Field label="Improvement actions"><Textarea value={value.improvementActions} onChange={e=>change({...value,improvementActions:e.target.value})} minLength={criterionKeys.some(k=>value[k]!==null&&value[k]!<=2)?10:undefined} maxLength={2000} required={criterionKeys.some(k=>value[k]!==null&&value[k]!<=2)} placeholder="Agree practical next steps and follow-up dates. Required for any score of 1 or 2."/></Field>
  </div>;
}
function RatingsRead({value,rubric=reviewRubric}:{value:RatingValues;rubric?:typeof reviewRubric}){return <div className="space-y-4"><div><p className="text-xs font-medium uppercase text-muted-foreground">Role expectations</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{value.roleExpectation}</p></div><div className="grid gap-3 md:grid-cols-2">{rubric.criteria.map(c=><div className="rounded-md border p-4" key={c.key}><p className="font-semibold">{c.label} <span className="float-right">{value[c.key]===null?'N/A':`${value[c.key]}/5`}</span></p><p className="mt-1 text-xs text-muted-foreground">{value[c.key]===null?'Not observed':rubric.anchors[value[c.key]!-1]}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm">{value.evidence[c.key]}</p></div>)}</div><p className="whitespace-pre-wrap break-words text-sm">{value.summary}</p>{value.improvementActions&&<div className="rounded-md bg-muted p-4"><h3 className="text-sm font-semibold">Improvement actions</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm">{value.improvementActions}</p></div>}</div>;}
export default function AssignmentReviews(){
  const [,params]=useRoute('/assignment-reviews/:id'),id=params?Number(params.id):null;
  const initialAssignment=Number(new URLSearchParams(window.location.search).get('assignmentId'))||null;
  const config=useQuery<ReviewConfig>({queryKey:['/api/assignment-reviews/config']}),[view,setView]=useState('mine'),[status,setStatus]=useState(''),[page,setPage]=useState(1),[open,setOpen]=useState(!!initialAssignment);
  const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const valid=!!from&&!!to&&to>=from&&Date.parse(to)-Date.parse(from)<90*86400000,range={from:from+'T00:00:00Z',to:to?new Date(Date.parse(to)+86400000).toISOString():''};
  const list=useQuery<AssignmentReviewList>({queryKey:['/api/assignment-reviews/',{...range,view,status,page}],enabled:!id&&valid,refetchInterval:30000});
  if(config.isLoading)return <p>Loading review access…</p>;
  if(config.error||!config.data)return <p role="alert">Unable to load assignment reviews. Please refresh.</p>;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Feedback & development</p><h1 className="mt-2 text-3xl font-semibold">Assignment reviews</h1><p className="mt-2 text-muted-foreground">Specific feedback on completed work, with space for employee responses.</p></div>{config.data.canReview&&<Button onClick={()=>setOpen(true)} disabled={!valid}><Plus className="mr-2 h-4 w-4"/>New review</Button>}</div>
    {id?<ReviewDetail key={id} id={id}/>:<><div className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-5"><Field label="View"><select className={selectClass} value={view} onChange={e=>{setView(e.target.value);setPage(1);setStatus('');}}><option value="mine">My reviews</option>{config.data.canReview&&<option value="team">Team reviews</option>}{config.data.canResolve&&<option value="disputes">HR dispute queue</option>}</select></Field><Field label="Status"><select className={selectClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}} disabled={view==='disputes'}><option value="">All statuses</option>{reviewStatuses.map(s=><option key={s} value={s}>{reviewStatusLabels[s]}</option>)}</select></Field><Field label="Work date from (UTC)"><Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></Field><Field label="Through (UTC)"><Input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></Field><Button variant="outline" disabled={!valid} onClick={()=>list.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
      {view==='disputes'&&<p className="text-sm text-muted-foreground">Disputes within these work dates that you can decide independently. Reviews you authored and your own employee reviews require another HR administrator.</p>}
      {!valid?<p role="alert">Choose a date range of up to 90 days.</p>:list.isLoading?<p>Loading reviews…</p>:list.error?<p role="alert">Unable to load reviews. Please refresh.</p>:<Card><CardContent className="py-2">{!list.data?.items.length?<div className="py-10"><Star className="mb-3 h-8 w-8 text-primary"/><h2 className="font-semibold">No reviews in this view</h2><p className="mt-2 text-muted-foreground">Choose another view or work date. Leads can review completed assignments once their time is approved.</p></div>:<div className="divide-y">{list.data.items.map(row=><Link key={row.id} href={`/assignment-reviews/${row.id}`} className="block rounded-md py-4 hover:bg-muted/40"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{row.employeeName} · {row.role}</p><p className="mt-1 text-sm text-muted-foreground">{row.teamName} · {row.siteName}</p></div><Badge className="self-start" variant={row.status==='disputed'?'destructive':'secondary'}>{reviewStatusLabels[row.status]}</Badge></div><p className="mt-3 text-sm">{stamp(row.startAt,row.timezone)} · Reviewer: {row.authorName}</p><p className="mt-1 text-xs text-muted-foreground">{row.responseKind?`Employee response: ${row.responseKind}`:row.status==='withdrawn'?'Review withdrawn':'Awaiting employee response'} · Version {row.version}</p></Link>)}</div>}</CardContent></Card>}
      {valid&&list.data&&<div className="flex flex-wrap justify-between gap-3 text-sm"><p>{list.data.total} reviews · Page {page}</p><div className="flex gap-2"><Button variant="outline" disabled={page===1||list.isFetching} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page*25>=list.data.total||list.isFetching} onClick={()=>setPage(page+1)}>Next</Button></div></div>}
    </>}
    <CreateReview open={open} close={()=>setOpen(false)} range={range} initialAssignment={initialAssignment}/>
  </div>;
}
function CreateReview({open,close,range,initialAssignment}:{open:boolean;close:()=>void;range:{from:string;to:string};initialAssignment:number|null}){
  const [,navigate]=useLocation(),[page,setPage]=useState(1),[selected,setSelected]=useState<ReviewAssignment|null>(null),[ignoreInitial,setIgnoreInitial]=useState(false),[values,setValues]=useState(emptyRatings),[confirmed,setConfirmed]=useState(false),mutation=useReviewMutation();
  const direct=useQuery<ReviewAssignment>({queryKey:[`/api/assignment-reviews/assignments/${initialAssignment}`],enabled:open&&!!initialAssignment&&!ignoreInitial});
  const assignment=selected||(!ignoreInitial?direct.data:undefined);
  const candidates=useQuery<{items:ReviewAssignment[];hasMore:boolean}>({queryKey:['/api/assignment-reviews/assignments',{...range,page}],enabled:open&&!assignment&&(!initialAssignment||ignoreInitial)});
  const reset=()=>{setSelected(null);setIgnoreInitial(true);setValues(emptyRatings());setConfirmed(false);setPage(1);};
  return <Dialog open={open} onOpenChange={value=>{if(!value&&!mutation.isPending){close();reset();}}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Review completed work</DialogTitle><DialogDescription>One published review per assignment. Ratings, examples and actions are visible to the employee and authorized HR/team reviewers.</DialogDescription></DialogHeader>
    {assignment?<form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{const saved=await mutation.mutateAsync({url:'/api/assignment-reviews/',body:{assignmentId:assignment.assignmentId,confirmed,ratings:values}});close();reset();navigate(`/assignment-reviews/${saved.id}`);}catch{}}}><fieldset disabled={mutation.isPending} className="space-y-4"><div className="rounded-md bg-muted p-3 text-sm"><p className="font-semibold">{assignment.employeeName} · {assignment.role}</p><p className="mt-1">{assignment.teamName} · {stamp(assignment.startAt,assignment.timezone)} · {assignment.timezone}</p><p className="mt-1">Approved worked time: {Math.floor(assignment.workedMinutes/60)}h {assignment.workedMinutes%60}m</p></div><RatingFields value={values} change={setValues}/><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>I observed this work and checked these ratings against the agreed expectations and examples.</label><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={reset}>Choose another assignment</Button><Button disabled={!confirmed||mutation.isPending}>Publish to employee</Button></div></fieldset></form>:<div className="space-y-3">{initialAssignment&&!ignoreInitial?(direct.error?<><p role="alert">This assignment is unavailable, already reviewed or its time is not approved.</p><Button variant="outline" onClick={reset}>Choose an available assignment</Button></>:<p>Loading assignment…</p>):candidates.isLoading?<p>Loading assignments…</p>:candidates.error?<p role="alert">Unable to load review assignments.</p>:!candidates.data?.items.length?<p>No completed assignments with approved time need a review in this date range.</p>:candidates.data.items.map(a=><button className="block w-full rounded-md border p-4 text-left hover:bg-muted" key={a.assignmentId} onClick={()=>setSelected(a)}><p className="font-medium">{a.employeeName} · {a.role}</p><p className="mt-1 text-sm text-muted-foreground">{a.teamName} · {stamp(a.startAt,a.timezone)}</p></button>)}{(!initialAssignment||ignoreInitial)&&<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={!candidates.data?.hasMore} onClick={()=>setPage(page+1)}>More assignments</Button></div>}</div>}
  </DialogContent></Dialog>;
}
function ReviewDetail({id}:{id:number}){
  const query=useQuery<AssignmentReviewDetail>({queryKey:[`/api/assignment-reviews/${id}`]});
  if(query.isLoading)return <p>Loading review…</p>;
  if(query.error||!query.data)return <div role="alert"><p>This review is unavailable or outside your current access.</p><Link href="/assignment-reviews" className="text-primary">Back to reviews</Link></div>;
  const {review:row,capabilities:access,history}=query.data;
  return <div className="space-y-5"><Link href="/assignment-reviews" className="inline-flex items-center text-sm text-primary"><ArrowLeft className="mr-2 h-4 w-4"/>Back to reviews</Link><Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-muted-foreground">Review #{row.id} · Version {row.version} · Rubric {row.rubricVersion}</p><CardTitle className="mt-2">{row.employeeName} · {row.role}</CardTitle><p className="mt-2 text-sm text-muted-foreground">{row.teamName} · {row.siteName} · {stamp(row.startAt,row.timezone)}</p><p className="mt-1 text-sm text-muted-foreground">Published by {row.authorName} · {stamp(row.createdAt,row.timezone)}</p></div><Badge className="self-start" variant={row.status==='disputed'?'destructive':'secondary'}>{reviewStatusLabels[row.status]}</Badge></div></CardHeader><CardContent><RatingsRead value={row} rubric={row.rubric}/>{!['approved','payroll_locked'].includes(row.timeStatus)&&<p className="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-950">The time approval for this assignment has changed. This review is excluded from performance trends until time is approved again.</p>}</CardContent></Card>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><div className="space-y-5">{row.responseKind&&<Card><CardHeader><CardTitle>Employee response · {row.responseKind}</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm">{row.employeeResponse||'Acknowledged receipt. This does not imply agreement with the ratings.'}</p></CardContent></Card>}{row.resolutionReason&&<Card><CardHeader><CardTitle>HR decision · {row.resolution}</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap break-words text-sm">{row.resolutionReason}</p><p className="mt-2 text-xs text-muted-foreground">Earlier ratings and employee responses remain in the revision history.</p></CardContent></Card>}
      {(access.respond||access.dispute)&&<ResponsePanel row={row} canRespond={access.respond}/>}{access.resolve&&<ResolutionPanel row={row}/>}
      <p className="text-sm text-muted-foreground">Review responses are visible to the employee, authorized team reviewers and HR. For confidential concerns, use <Link href="/helpdesk" className="text-primary underline">HR Helpdesk</Link>.</p>
    </div><Card><CardHeader><CardTitle>Revision history</CardTitle></CardHeader><CardContent className="space-y-3">{history.map(h=><details className="rounded-md border p-3" key={h.id}><summary className="cursor-pointer text-sm font-medium">v{h.version} · {h.action} · {h.actorName}</summary><p className="mt-2 text-xs text-muted-foreground">{stamp(h.createdAt,row.timezone)}</p><p className="my-3 whitespace-pre-wrap break-words text-sm">{h.reason}</p><RatingsRead value={h.snapshot} rubric={row.rubric}/>{h.snapshot.employeeResponse&&<p className="mt-3 whitespace-pre-wrap break-words text-sm">Employee response: {h.snapshot.employeeResponse}</p>}</details>)}</CardContent></Card></div>
  </div>;
}
function ResponsePanel({row,canRespond}:{row:AssignmentReviewRow;canRespond:boolean}){
  const [kind,setKind]=useState(canRespond?'acknowledge':'dispute'),[message,setMessage]=useState(''),mutation=useReviewMutation();
  return <Card><CardHeader><CardTitle>Your response</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/assignment-reviews/${row.id}/respond`,body:{version:row.version,kind:canRespond?kind:'dispute',message}});setMessage('');setKind('dispute');}catch{}}}><Field label="Response"><select className={selectClass} value={canRespond?kind:'dispute'} onChange={e=>setKind(e.target.value)}>{canRespond&&<><option value="acknowledge">Acknowledge receipt</option><option value="comment">Add my perspective</option></>}<option value="dispute">Dispute and request HR review</option></select></Field><p className="text-sm text-muted-foreground">Acknowledging confirms you received the review, without requiring agreement. You can still raise a dispute afterwards. A dispute excludes this review from trends until HR records a decision.</p><Field label="Your comments"><Textarea value={message} onChange={e=>setMessage(e.target.value)} required={!canRespond||kind!=='acknowledge'} minLength={!canRespond||kind!=='acknowledge'?10:undefined} maxLength={3000}/></Field><Button disabled={mutation.isPending}>Save response</Button></form></CardContent></Card>;
}
function ResolutionPanel({row}:{row:AssignmentReviewRow}){
  const [outcome,setOutcome]=useState(row.status==='disputed'?'uphold':'amend'),[reason,setReason]=useState(''),[values,setValues]=useState(()=>valuesFrom(row)),mutation=useReviewMutation();
  return <Card><CardHeader><CardTitle>Independent HR decision</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/assignment-reviews/${row.id}/resolve`,body:{version:row.version,outcome,reason,...(outcome==='amend'?{ratings:values}:{})}});setReason('');setOutcome('amend');}catch{}}}><Field label="HR outcome"><select className={selectClass} value={outcome} onChange={e=>setOutcome(e.target.value)}>{row.status==='disputed'&&<option value="uphold">Uphold existing ratings</option>}<option value="amend">Amend ratings or evidence</option><option value="withdraw">Withdraw review</option></select></Field><p className="text-sm text-muted-foreground">Record an evidence-based decision visible to the employee. Changes preserve earlier versions and allow a new employee response. Withdrawal is final and removes the review from trends.</p>{outcome==='amend'&&<RatingFields value={values} change={setValues}/>}<Field label="HR decision reason"><Textarea value={reason} onChange={e=>setReason(e.target.value)} required minLength={10} maxLength={3000}/></Field><Button disabled={mutation.isPending}>Record HR decision</Button></form></CardContent></Card>;
}
