import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {PageHeading,HelpDisclosure} from '@/components/ux/WorkspaceUI';
import {MetricCard,StatusPill,EmptyState,FlowSteps} from '@/components/ux/ModuleVisuals';
import {Upload,FileSpreadsheet,Download} from 'lucide-react';
import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {useAuth} from '@/contexts/AuthContext';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {employeeImportColumns,type ImportJob,type ImportRow,type ImportPayload} from '@shared/employee-import';

export default function BulkImport(){
 const {user}=useAuth(),allowed=!!user&&['admin','super_admin'].includes(user.role);const cache=useQueryClient(),{toast}=useToast();
 const [view,setView]=useState('upload');
 const [file,setFile]=useState<File|null>(null),[submissionKey,setSubmissionKey]=useState(''),[selected,setSelected]=useState<number|null>(null),[page,setPage]=useState(1);
 const jobs=useQuery<{items:ImportJob[];hasMore:boolean}>({queryKey:['/api/bulk-import/jobs',{page}],enabled:allowed});
 const upload=useMutation({mutationFn:async()=>{if(!file)throw new Error('Choose a CSV file');if(file.size>2*1024*1024)throw new Error('The file must be 2 MB or smaller');const data=new FormData();data.append('file',file);data.append('submissionKey',submissionKey);return apiJson<{jobId:number}>('/api/bulk-import/upload',{method:'POST',body:data});},onSuccess:async r=>{setSelected(r.jobId);setView('review');await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/bulk-import')});toast({title:'Draft ready for review',description:'No employee records have been created yet.'});},onError:e=>toast({title:'Unable to stage file',description:e.message,variant:'destructive'})});
 if(!allowed)return <div className="rounded border p-5"><h1 className="text-xl font-semibold">Bulk employee import</h1><p>Admin or Super Admin access is required.</p></div>;
 return <div className="space-y-5"><PageHeading title="Employee import" description="Upload a file, review the records, then import." icon={Upload}/>
 <Tabs value={view} onValueChange={setView}><TabsList aria-label="Import workspace"><TabsTrigger value="upload">New import</TabsTrigger><TabsTrigger value="history">Import history</TabsTrigger>{selected&&<TabsTrigger value="review">Review #{selected}</TabsTrigger>}<TabsTrigger value="guide">Field guide</TabsTrigger></TabsList>
 <TabsContent value="upload" className="space-y-5"><FlowSteps steps={['Upload CSV','Review & correct','Confirm import']}/><div className="grid gap-5 lg:grid-cols-[minmax(0,2fr)_minmax(240px,1fr)]"><section className="module-card border bg-card p-5 sm:p-7"><h2 className="font-semibold">Upload employee records</h2><label className="mt-5 flex cursor-pointer flex-col items-center gap-3 rounded-xl border-2 border-dashed bg-muted/20 px-5 py-8 text-center hover:border-primary/40"><span className="rounded-xl bg-primary/10 p-3"><FileSpreadsheet aria-hidden="true" className="h-7 w-7 text-primary"/></span><span className="font-medium">{file?file.name:'Choose a CSV file'}</span><span className="text-xs text-muted-foreground">UTF-8 · Up to 500 employees · 2 MB maximum</span><Input className="max-w-sm" aria-label="Employee CSV file" type="file" accept=".csv,text/csv" disabled={upload.isPending} onChange={e=>{setFile(e.target.files?.[0]??null);setSubmissionKey(crypto.randomUUID());}}/></label><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-muted-foreground">Uploading creates a draft for review.</span><Button disabled={!file||upload.isPending} onClick={()=>upload.mutate()}>{upload.isPending?'Validating…':'Preview import'}</Button></div></section><aside className="space-y-4"><section className="module-card border bg-card p-5"><Download aria-hidden="true" className="mb-3 h-5 w-5 text-primary"/><h2 className="font-semibold">Start with the template</h2><p className="mt-2 text-sm text-muted-foreground">Use the supplied columns for a smoother import.</p><Button className="mt-4 w-full" variant="outline" asChild><a href="/api/bulk-import/template" download>Download template</a></Button></section><HelpDisclosure title="Before you upload"><p>Only new employee records are created. Existing employees are preserved. Login accounts are managed in User Management.</p><p>Use YYYY-MM-DD dates. Keep IDs and phone numbers as text to preserve leading zeros. Choose work schedules and event eligibility explicitly.</p></HelpDisclosure></aside></div></TabsContent>
 <TabsContent value="review">{selected&&<ImportReview key={selected} id={selected}/>}</TabsContent>
 <TabsContent value="history"><section className="module-card border bg-card p-5 space-y-4"><h2 className="font-semibold">Your imports</h2><p className="text-xs text-muted-foreground">Only imports uploaded by your account appear here.</p>{jobs.isLoading?<p role="status">Loading imports…</p>:jobs.isError?<p role="alert">Unable to load jobs. <Button onClick={()=>jobs.refetch()}>Retry</Button></p>:<>{!jobs.data?.items.length&&<EmptyState title="No imports yet" description="Start with a CSV file in New import."/>}{jobs.data?.items.map(j=><article className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4" key={j.id}><div className="flex min-w-0 items-center gap-3"><FileSpreadsheet aria-hidden="true" className="h-5 w-5 shrink-0 text-primary"/><div className="min-w-0"><h3 className="break-all text-sm font-medium">{j.fileName}</h3><p className="mt-1 text-xs text-muted-foreground">#{j.id} · {j.successfulRows} / {j.totalRows} imported · {new Date(j.createdAt).toLocaleDateString()}</p></div></div><div className="flex items-center gap-3"><StatusPill value={j.status}/><Button variant="outline" size="sm" onClick={()=>{setSelected(j.id);setView('review');}}>Open import #{j.id}</Button></div></article>)}<div className="flex justify-end gap-2"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Newer</Button><Button size="sm" variant="outline" disabled={!jobs.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Older</Button></div></>}</section></TabsContent>
 <TabsContent value="guide"><section className="module-card border bg-card p-5 space-y-4"><h2 className="font-semibold">CSV field guide</h2><p className="text-sm text-muted-foreground">Record numbering starts at 2, after the header. Quoted line breaks stay within a single record.</p><div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Column','Required','Format / meaning'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{employeeImportColumns.map(c=><tr key={c.key}><td className="p-3 font-mono">{c.key}</td><td className="p-3">{c.required?'Required':'Optional'}</td><td className="p-3">{c.options?.join(' / ')||(c.kind==='date'?'YYYY-MM-DD':c.kind==='integer'?'Whole number':c.kind==='boolean'?'true / false':'Text')}{c.help?' · '+c.help:''}</td></tr>)}</tbody></table></div></section></TabsContent>
 </Tabs></div>;
}

function ImportReview({id}:{id:number}){
 const base='/api/bulk-import/job/'+id;const cache=useQueryClient(),{toast}=useToast();const [page,setPage]=useState(1),[filter,setFilter]=useState('all'),[editor,setEditor]=useState<ImportRow|null>(null),[reason,setReason]=useState(''),[confirmedVersion,setConfirmedVersion]=useState<number|null>(null);
 const job=useQuery<ImportJob>({queryKey:[base]});const records=useQuery<{items:ImportRow[];hasMore:boolean;version:number}>({queryKey:[base+'/rows',{page,filter},job.data?.version],queryFn:()=>apiJson(base+'/rows?page='+page+'&filter='+filter),enabled:!!job.data?.staged});
 const refresh=()=>cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/bulk-import')||String(q.queryKey[0]).startsWith('/api/employees')||String(q.queryKey[0]).startsWith('/api/dashboard')});
 const action=useMutation({mutationFn:({path,body,method='POST'}:{path:string;body:object;method?:string})=>apiJson(base+path,{method,body}),onSuccess:async()=>{setEditor(null);setReason('');setConfirmedVersion(null);await refresh();toast({title:'Import job updated'});},onError:async e=>{await refresh();toast({title:'Import needs attention',description:e.message,variant:'destructive'});}});
 if(job.isLoading)return <p>Loading import review…</p>;if(job.isError||!job.data)return <p role="alert">Unable to load this import. <Button onClick={()=>job.refetch()}>Retry</Button></p>;
 const j=job.data,draft=j.staged&&j.status==='draft';
 return <section className="rounded-lg border bg-card p-4 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">Import #{j.id} · {j.fileName}</h2><p>Status: {j.status} · Version {j.version}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>refresh()}>Refresh import</Button>{j.staged&&<Button variant="outline" asChild><a href={base+'/report'} download>Download results CSV</a></Button>}</div></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Included" value={j.includedRows}/><MetricCard label="Needs correction" value={j.failedRows} tone="attention"/><MetricCard label="Excluded" value={j.excludedRows}/><MetricCard label="Imported" value={j.successfulRows} tone="positive"/></div>
 {j.status==='completed'&&<p role="status" className="rounded bg-green-50 text-green-900 p-3">Import complete. {j.successfulRows} employee records created{j.staged?' together':''}.</p>}
 {!j.staged?<p>This is a historical import. Its totals are retained; staged corrections and detailed CSV reports apply to new imports.</p>:<>
 <div className="flex flex-wrap gap-3 items-end"><label>Show records<select className="block rounded border p-2" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);setEditor(null);}}>{[['all','All records'],['errors','Included with errors'],['included','Included'],['excluded','Excluded'],['imported','Imported']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{draft&&<Button variant="outline" disabled={action.isPending} onClick={()=>action.mutate({path:'/revalidate',body:{version:j.version}})}>Revalidate against current employees</Button>}</div>
 {records.isLoading?<p>Loading records…</p>:records.isError?<p role="alert">Records unavailable. <Button onClick={()=>records.refetch()}>Retry</Button></p>:<><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b">{['CSV record','Employee ID','Name','Employment','Review','Action'].map(s=><th className="p-2" key={s}>{s}</th>)}</tr></thead><tbody>{!records.data?.items.length?<tr><td colSpan={6} className="p-3">No matching records.</td></tr>:records.data.items.map(r=><tr key={r.id} className="border-b align-top"><td className="p-2">{r.rowNumber}</td><td className="p-2">{r.payload.employeeId||'Missing'}</td><td className="p-2">{r.payload.firstName} {r.payload.lastName}</td><td className="p-2">{r.payload.type} · {r.payload.department}<br/>{r.payload.workSchedule||'unassigned'}</td><td className="p-2">{r.employeeId?'Imported':!r.included?'Excluded':r.errors.length?'Needs correction':'Valid'}{r.included&&r.errors.length>0&&<ul className="list-disc pl-4">{r.errors.map((e,i)=><li key={i}>{e.field}: {e.message}</li>)}</ul>}</td><td className="p-2"><Button variant="outline" size="sm" disabled={action.isPending} onClick={()=>setEditor(r)}>{draft?'Review / correct':'View record'}</Button>{r.employeeId&&<a className="block underline mt-2" href="/employees">Employee directory</a>}</td></tr>)}</tbody></table></div><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Previous records</Button><span>Page {page}</span><Button variant="outline" disabled={!records.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Next records</Button></div></>}
 {editor&&<RowEditor key={editor.id+':'+j.version} row={editor} editable={draft} pending={action.isPending} onClose={()=>setEditor(null)} onSave={(payload,included,reason)=>action.mutate({path:'/rows/'+editor.id,method:'PATCH',body:{version:j.version,payload,included,reason}})}/>}
 {draft&&<fieldset disabled={action.isPending} className="border rounded p-4 space-y-3"><legend className="font-medium">Finish review</legend><p className="text-sm">Included records import together only when all are valid. Excluded records stay in this job and are not created. Duplicate checks and manager validation run again at commit.</p><label className="block">Import or cancellation reason<Input value={reason} minLength={5} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2 items-center"><input type="checkbox" checked={confirmedVersion===j.version} onChange={e=>setConfirmedVersion(e.target.checked?j.version:null)}/>I reviewed the {j.includedRows} included employee records in version {j.version}.</label><div className="flex gap-2"><Button disabled={j.failedRows>0||!j.includedRows||confirmedVersion!==j.version||reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:'/commit',body:{version:j.version,reason,confirmedRows:j.includedRows}})}>Import {j.includedRows} employees</Button><Button variant="outline" disabled={reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:'/cancel',body:{version:j.version,reason}})}>Cancel draft</Button></div></fieldset>}
 <ImportHistory key={j.version} base={base}/></>}
 </section>;
}
function RowEditor({row,editable,pending,onClose,onSave}:{row:ImportRow;editable:boolean;pending:boolean;onClose:()=>void;onSave:(payload:ImportPayload,included:boolean,reason:string)=>void}){
 const [data,setData]=useState(row.payload),[included,setIncluded]=useState(row.included),[reason,setReason]=useState('');
 return <form className="rounded border p-4 space-y-3" onSubmit={e=>{e.preventDefault();onSave(data,included,reason);}}><div className="flex justify-between gap-2"><h3 className="font-semibold">CSV record {row.rowNumber}</h3><Button type="button" variant="outline" onClick={onClose}>Close record</Button></div><fieldset disabled={!editable||pending} className="space-y-3"><label className="flex gap-2 items-center"><input type="checkbox" checked={included} onChange={e=>setIncluded(e.target.checked)}/>Include this employee in the import</label><div className="grid md:grid-cols-3 gap-3">{employeeImportColumns.map(col=><label key={col.key} className="text-sm">{col.label}{col.required?' *':''}<Input aria-label={col.label} maxLength={2000} value={data[col.key]??''} placeholder={col.kind==='date'?'YYYY-MM-DD':col.options?.join(' / ')||col.kind==='boolean'&&'true / false'||''} onChange={e=>setData({...data,[col.key]:e.target.value})}/>{col.help&&<span className="text-xs text-muted-foreground">{col.help}</span>}</label>)}</div>{editable&&<><label className="block">Correction / exclusion reason<Input value={reason} minLength={5} maxLength={1000} onChange={e=>setReason(e.target.value)} required/></label><Button type="submit" disabled={reason.trim().length<5||pending}>Save and revalidate draft</Button></>}</fieldset></form>;
}
function ImportHistory({base}:{base:string}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1);const q=useQuery<{items:{version:number;reason:string;created_at:string;snapshot:{action:string;rowNumber?:number}}[];hasMore:boolean}>({queryKey:[base+'/history',{page}],enabled:open});
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer font-medium">Import history</summary>{open&&<div className="space-y-2 p-2">{q.isLoading?<p>Loading history…</p>:q.isError?<p role="alert">History unavailable. <Button onClick={()=>q.refetch()}>Retry</Button></p>:<>{!q.data?.items.length&&<p>No history recorded.</p>}{q.data?.items.map(h=><div className="border-b py-2 text-sm" key={h.version}><p>Version {h.version} · {h.snapshot.action}{h.snapshot.rowNumber?' · CSV record '+h.snapshot.rowNumber:''} · {new Date(h.created_at).toLocaleString()}</p><p>{h.reason}</p></div>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Newer history</Button><Button variant="outline" disabled={!q.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Older history</Button></div></>}</div>}</details>;
}
