import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {useAuth} from '@/contexts/AuthContext';
import {useToast} from '@/hooks/use-toast';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {employeeImportColumns,type ImportJob,type ImportRow,type ImportPayload} from '@shared/employee-import';

export default function BulkImport(){
 const {user}=useAuth(),allowed=!!user&&['admin','super_admin'].includes(user.role);const cache=useQueryClient(),{toast}=useToast();
 const [file,setFile]=useState<File|null>(null),[submissionKey,setSubmissionKey]=useState(''),[selected,setSelected]=useState<number|null>(null),[page,setPage]=useState(1);
 const jobs=useQuery<{items:ImportJob[];hasMore:boolean}>({queryKey:['/api/bulk-import/jobs',{page}],enabled:allowed});
 const upload=useMutation({mutationFn:async()=>{if(!file)throw new Error('Choose a CSV file');if(file.size>2*1024*1024)throw new Error('The file must be 2 MB or smaller');const data=new FormData();data.append('file',file);data.append('submissionKey',submissionKey);return apiJson<{jobId:number}>('/api/bulk-import/upload',{method:'POST',body:data});},onSuccess:async r=>{setSelected(r.jobId);await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/bulk-import')});toast({title:'Draft ready for review',description:'No employee records have been created yet.'});},onError:e=>toast({title:'Unable to stage file',description:e.message,variant:'destructive'})});
 if(!allowed)return <div className="rounded border p-5"><h1 className="text-xl font-semibold">Bulk employee import</h1><p>Admin or Super Admin access is required.</p></div>;
 return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Bulk employee import</h1><p className="text-muted-foreground">Upload → correct and review → import included employees together.</p></div>
 <section className="rounded-lg border bg-card p-4 space-y-3"><h2 className="text-lg font-semibold">Create an import draft</h2><p className="text-sm">Creates new active employee records for permanent, temporary and contract staff. Existing employees are never overwritten. Set event eligibility and work schedules explicitly. Manage login accounts separately in User Management.</p>
 <div className="flex flex-wrap gap-3 items-end"><Button variant="outline" asChild><a href="/api/bulk-import/template" download>Download CSV template</a></Button><label className="grid gap-1">UTF-8 CSV file · up to 500 records / 2 MB<Input type="file" accept=".csv,text/csv" disabled={upload.isPending} onChange={e=>{setFile(e.target.files?.[0]??null);setSubmissionKey(crypto.randomUUID());}}/></label><Button disabled={!file||upload.isPending} onClick={()=>upload.mutate()}>{upload.isPending?'Validating file…':'Validate and preview'}</Button></div>
 <p className="text-sm text-muted-foreground">Use YYYY-MM-DD dates. Keep employee IDs, identity references and telephone numbers as text to preserve leading zeros. Uploading creates a draft only. CSV record numbers start at 2 after the header; quoted line breaks remain within one record.</p>
 <details><summary className="cursor-pointer font-medium">CSV field guide</summary><div className="max-h-80 overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Column</th><th className="p-2">Required</th><th className="p-2">Format / meaning</th></tr></thead><tbody>{employeeImportColumns.map(c=><tr key={c.key} className="border-t"><td className="p-2 font-mono">{c.key}</td><td className="p-2">{c.required?'Yes':'No'}</td><td className="p-2">{c.options?.join(' / ')|| (c.kind==='date'?'YYYY-MM-DD':c.kind==='integer'?'Whole number':c.kind==='boolean'?'true / false':'Text')}{c.help?' · '+c.help:''}</td></tr>)}</tbody></table></div></details></section>
 {selected&&<ImportReview key={selected} id={selected}/>}
 <section className="rounded-lg border bg-card p-4 space-y-3"><h2 className="text-lg font-semibold">Your import jobs</h2><p className="text-sm text-muted-foreground">Drafts, results and reports are private to the administrator who uploaded them.</p>{jobs.isLoading?<p>Loading imports…</p>:jobs.isError?<p role="alert">Unable to load jobs. <Button onClick={()=>jobs.refetch()}>Retry</Button></p>:<>{!jobs.data?.items.length&&<p>No import jobs yet.</p>}{jobs.data?.items.map(j=><div className="flex flex-wrap justify-between gap-3 border rounded p-3" key={j.id}><div><p className="font-medium">#{j.id} · {j.fileName} · {j.status}</p><p className="text-sm">{j.totalRows} records · {j.successfulRows} imported · {new Date(j.createdAt).toLocaleString()}</p></div><Button variant="outline" onClick={()=>setSelected(j.id)}>Open import #{j.id}</Button></div>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Newer imports</Button><Button variant="outline" disabled={!jobs.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Older imports</Button></div></>}</section></div>;
}
function ImportReview({id}:{id:number}){
 const base='/api/bulk-import/job/'+id;const cache=useQueryClient(),{toast}=useToast();const [page,setPage]=useState(1),[filter,setFilter]=useState('all'),[editor,setEditor]=useState<ImportRow|null>(null),[reason,setReason]=useState(''),[confirmedVersion,setConfirmedVersion]=useState<number|null>(null);
 const job=useQuery<ImportJob>({queryKey:[base]});const records=useQuery<{items:ImportRow[];hasMore:boolean;version:number}>({queryKey:[base+'/rows',{page,filter},job.data?.version],queryFn:()=>apiJson(base+'/rows?page='+page+'&filter='+filter),enabled:!!job.data?.staged});
 const refresh=()=>cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/bulk-import')||String(q.queryKey[0]).startsWith('/api/employees')||String(q.queryKey[0]).startsWith('/api/dashboard')});
 const action=useMutation({mutationFn:({path,body,method='POST'}:{path:string;body:object;method?:string})=>apiJson(base+path,{method,body}),onSuccess:async()=>{setEditor(null);setReason('');setConfirmedVersion(null);await refresh();toast({title:'Import job updated'});},onError:async e=>{await refresh();toast({title:'Import needs attention',description:e.message,variant:'destructive'});}});
 if(job.isLoading)return <p>Loading import review…</p>;if(job.isError||!job.data)return <p role="alert">Unable to load this import. <Button onClick={()=>job.refetch()}>Retry</Button></p>;
 const j=job.data,draft=j.staged&&j.status==='draft';
 return <section className="rounded-lg border bg-card p-4 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">Import #{j.id} · {j.fileName}</h2><p>Status: {j.status} · Version {j.version}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>refresh()}>Refresh import</Button>{j.staged&&<Button variant="outline" asChild><a href={base+'/report'} download>Download results CSV</a></Button>}</div></div>
 <p>{j.totalRows} total · {j.includedRows} included · {j.excludedRows} excluded · {j.failedRows} included records with errors · {j.successfulRows} imported</p>
 {j.status==='completed'&&<p role="status" className="rounded bg-green-50 text-green-900 p-3">Import complete. {j.successfulRows} employee records created{j.staged?' together':''}.</p>}
 {!j.staged?<p>This is a historical import. Its totals are retained; staged corrections and detailed CSV reports apply to new imports.</p>:<>
 <div className="flex flex-wrap gap-3 items-end"><label>Show records<select className="block rounded border p-2" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);setEditor(null);}}>{[['all','All records'],['errors','Included with errors'],['included','Included'],['excluded','Excluded'],['imported','Imported']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{draft&&<Button variant="outline" disabled={action.isPending} onClick={()=>action.mutate({path:'/revalidate',body:{version:j.version}})}>Revalidate against current employees</Button>}</div>
 {records.isLoading?<p>Loading records…</p>:records.isError?<p role="alert">Records unavailable. <Button onClick={()=>records.refetch()}>Retry</Button></p>:<><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b">{['CSV record','Employee ID','Name','Employment','Review','Action'].map(s=><th className="p-2" key={s}>{s}</th>)}</tr></thead><tbody>{!records.data?.items.length?<tr><td colSpan={6} className="p-3">No matching records.</td></tr>:records.data.items.map(r=><tr key={r.id} className="border-b align-top"><td className="p-2">{r.rowNumber}</td><td className="p-2">{r.payload.employeeId||'Missing'}</td><td className="p-2">{r.payload.firstName} {r.payload.lastName}</td><td className="p-2">{r.payload.type} · {r.payload.department}<br/>{r.payload.workSchedule||'unassigned'}</td><td className="p-2">{r.employeeId?'Imported':!r.included?'Excluded':r.errors.length?'Needs correction':'Valid'}{r.included&&r.errors.length>0&&<ul className="list-disc pl-4">{r.errors.map((e,i)=><li key={i}>{e.field}: {e.message}</li>)}</ul>}</td><td className="p-2"><Button variant="outline" size="sm" disabled={action.isPending} onClick={()=>setEditor(r)}>{draft?'Review / correct':'View record'}</Button>{r.employeeId&&<a className="block underline mt-2" href="/employees">Employee directory</a>}</td></tr>)}</tbody></table></div><div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Previous records</Button><span>Page {page}</span><Button variant="outline" disabled={!records.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Next records</Button></div></>}
 {editor&&<RowEditor key={editor.id+':'+j.version} row={editor} editable={draft} pending={action.isPending} onClose={()=>setEditor(null)} onSave={(payload,included,reason)=>action.mutate({path:'/rows/'+editor.id,method:'PATCH',body:{version:j.version,payload,included,reason}})}/>}
 {draft&&<fieldset disabled={action.isPending} className="border rounded p-4 space-y-3"><legend className="font-medium">Finish review</legend><p className="text-sm">Included records import together only when all are valid. Excluded records stay in this job and are not created. Duplicate checks and manager validation run again at commit.</p><label className="block">Import or cancellation reason<Input value={reason} minLength={5} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><label className="flex gap-2 items-center"><input type="checkbox" checked={confirmedVersion===j.version} onChange={e=>setConfirmedVersion(e.target.checked?j.version:null)}/>I reviewed the {j.includedRows} included employee records in version {j.version}.</label><div className="flex gap-2"><Button disabled={j.failedRows>0||!j.includedRows||confirmedVersion!==j.version||reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:'/commit',body:{version:j.version,reason,confirmedRows:j.includedRows}})}>Import {j.includedRows} employees</Button><Button variant="outline" disabled={reason.trim().length<5||action.isPending} onClick={()=>action.mutate({path:'/cancel',body:{version:j.version,reason}})}>Cancel draft</Button></div></fieldset>}
 <ImportHistory key={j.version} base={base}/></>}
 </section>;
}
function RowEditor({row,editable,pending,onClose,onSave}:{row:ImportRow;editable:boolean;pending:boolean;onClose:()=>void;onSave:(payload:ImportPayload,included:boolean,reason:string)=>void}){
 const [data,setData]=useState(row.payload),[included,setIncluded]=useState(row.included),[reason,setReason]=useState('');
 return <form className="rounded border p-4 space-y-3" onSubmit={e=>{e.preventDefault();onSave(data,included,reason);}}><div className="flex justify-between gap-2"><h3 className="font-semibold">CSV record {row.rowNumber}</h3><Button type="button" variant="outline" onClick={onClose}>Close record</Button></div><fieldset disabled={!editable||pending} className="space-y-3"><label className="flex gap-2 items-center"><input type="checkbox" checked={included} onChange={e=>setIncluded(e.target.checked)}/>Include this employee in the import</label><div className="grid md:grid-cols-3 gap-3">{employeeImportColumns.map(col=><label key={col.key} className="text-sm">{col.label}{col.required?' *':''}<Input aria-label={col.label} maxLength={2000} value={data[col.key]??''} placeholder={col.kind==='date'?'YYYY-MM-DD':col.options?.join(' / ')||col.kind==='boolean'&&'true / false'||''} onChange={e=>setData({...data,[col.key]:e.target.value})}/>{col.help&&<span className="text-xs text-muted-foreground">{col.help}</span>}</label>)}</div>{editable&&<><label className="block">Correction / exclusion reason<Input value={reason} minLength={5} maxLength={1000} onChange={e=>setReason(e.target.value)} required/></label><Button type="submit" disabled={reason.trim().length<5||pending}>Save and revalidate draft</Button></>}</fieldset></form>;
}
function ImportHistory({base}:{base:string}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1);const q=useQuery<{items:{version:number;reason:string;created_at:string;snapshot:{action:string;rowNumber?:number}}[];hasMore:boolean}>({queryKey:[base+'/history',{page}],enabled:open});
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer font-medium">Import history</summary>{open&&<div className="space-y-2 p-2">{q.isLoading?<p>Loading history…</p>:q.isError?<p role="alert">History unavailable. <Button onClick={()=>q.refetch()}>Retry</Button></p>:<>{!q.data?.items.length&&<p>No history recorded.</p>}{q.data?.items.map(h=><div className="border-b py-2 text-sm" key={h.version}><p>Version {h.version} · {h.snapshot.action}{h.snapshot.rowNumber?' · CSV record '+h.snapshot.rowNumber:''} · {new Date(h.created_at).toLocaleString()}</p><p>{h.reason}</p></div>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Newer history</Button><Button variant="outline" disabled={!q.data?.hasMore} onClick={()=>setPage(n=>n+1)}>Older history</Button></div></>}</div>}</details>;
}
