import {MessageCircle,AtSign,Megaphone,Inbox as InboxIcon,ArrowUpRight} from 'lucide-react';
import {useHubSummary} from '@/components/communications/HubIndicator';
import {usePageAccess} from '@/hooks/usePageAccess';
import { useState,useRef,useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Field,Section,QueryError,fieldClass } from '@/components/hr/Operations';
import HubAnnouncements from '@/components/communications/HubAnnouncements';
import type {ChatDraft} from '@/components/communications/Conversation';
import HubChannels from '@/components/communications/HubChannels';
import { hub,useHubAction,Pager,dateLabel,type Page } from '@/components/communications/HubControls';
import { communicationPolicy,type CommunicationPolicy } from '@shared/communications';
export default function Communications(){
  const [tab,setTab]=useState('channels'),[chatFilter,setChatFilter]=useState({value:'all',revision:0}),[focused,setFocused]=useState(false);
  const top=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(focused)top.current?.closest('main')?.scrollTo({top:0});},[focused]);
  const drafts=useRef(new Map<number,ChatDraft>());
  const summary=useHubSummary();
  const context=useQuery<any>({queryKey:[hub+'/context']});
  return <div ref={top} className={focused?"space-y-0":"space-y-6"}>{!focused&&<header><h1 className="text-3xl font-bold">Communication Hub</h1><p className="mt-2 text-muted-foreground">Connect with your team. Keep every shift, update and conversation in sync.</p></header>}<QueryError error={context.error}/>{!context.data&&!context.error&&<p>Loading your workspace…</p>}{context.data&&!context.error&&<>{!focused&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{key:'unreadConversations',label:'Unread chats',target:'channels',Icon:MessageCircle},{key:'mentions',label:'Mentions',target:'channels',Icon:AtSign},{key:'pendingAcknowledgements',label:'Notices to acknowledge',target:'announcements',Icon:Megaphone},{key:'unreadActions',label:'Action inbox',target:'inbox',Icon:InboxIcon}].map(item=><button key={item.key} onClick={()=>{if(item.target==='channels')setChatFilter(value=>({value:item.key==='mentions'?'mentions':'unread',revision:value.revision+1}));setTab(item.target);}} className="flex items-center gap-3 rounded-xl border bg-card p-3 text-left hover:bg-accent"><span className="rounded-lg bg-primary/10 p-2 text-primary"><item.Icon className="h-4 w-4"/></span><span><strong className="block text-lg">{summary.error?'—':summary.data?.[item.key as keyof typeof summary.data]??'…'}</strong><span className="text-xs text-muted-foreground">{item.label}</span></span></button>)}</div>}<Tabs value={tab} onValueChange={setTab}>{!focused&&<TabsList className="flex h-auto w-fit max-w-full flex-wrap"><TabsTrigger value="channels">Team chat</TabsTrigger><TabsTrigger value="announcements">Announcements & briefings</TabsTrigger><TabsTrigger value="inbox">Action inbox</TabsTrigger>{context.data.canConfigure&&<TabsTrigger value="settings">Administration</TabsTrigger>}</TabsList>}<TabsContent value="announcements"><HubAnnouncements context={context.data}/></TabsContent><TabsContent value="channels"><HubChannels context={context.data} filterRequest={chatFilter} drafts={drafts.current} focused={focused} onFocus={()=>setFocused(value=>!value)}/></TabsContent><TabsContent value="inbox"><Inbox onAnnouncements={()=>setTab('announcements')}/></TabsContent>{context.data.canConfigure&&<TabsContent value="settings"><Policy key={context.data.policy.version} current={context.data.policy}/></TabsContent>}</Tabs></>}</div>;
}
function Inbox({onAnnouncements}:{onAnnouncements:()=>void}){
  const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[unread,setUnread]=useState(true);
  const items=useQuery<Page<any>>({queryKey:[`${hub}/inbox?q=${encodeURIComponent(q)}&offset=${offset}&unread=${unread}`],refetchInterval:30000,refetchIntervalInBackground:false});
  const action=useHubAction();const {pages}=usePageAccess();
  return <div className="space-y-4"><Section title="Actions and reminders"><p className="text-sm">Open the original HR record to take action. Reading a reminder does not complete or approve its task.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{href:'/team-overview',label:'Team approvals'},{href:'/helpdesk',label:'My HR cases'},{href:'/learning',label:'My training'}].filter(item=>pages.some(page=>page.href===item.href)).map(item=><a key={item.href} className="flex items-center justify-between rounded-xl border bg-background p-4 text-sm font-medium hover:bg-accent" href={item.href}>{item.label}<ArrowUpRight className="h-4 w-4"/></a>)}<button className="flex items-center justify-between rounded-xl border bg-background p-4 text-left text-sm font-medium hover:bg-accent" onClick={onAnnouncements}>Company notices<Megaphone className="h-4 w-4"/></button></div></Section><div className="flex flex-wrap gap-3 items-center"><input className={fieldClass+' max-w-sm'} aria-label="Search action inbox" placeholder="Search your reminders" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/><label className="text-sm"><input type="checkbox" checked={unread} onChange={e=>{setUnread(e.target.checked);setOffset(0);}}/> Unread only</label><Button variant="outline" onClick={()=>items.refetch()}>Refresh</Button></div><QueryError error={items.error||action.error}/>{items.isLoading&&<p>Loading inbox…</p>}{items.data&&!items.data.items.length&&<p>No reminders to show.</p>}{items.data?.items.map(n=><article className="space-y-2 rounded-lg border bg-card p-4" key={n.id}><p className="whitespace-pre-wrap break-words">{n.message}</p><p className="text-xs text-muted-foreground">{dateLabel(n.timestamp)} · {n.read_at?'Read '+dateLabel(n.read_at):'Unread'}{n.channel!=='push'?' · Historical external notification':''}</p><div className="flex gap-3">{n.url&&<a className="text-sm underline" href={n.url}>Open related record</a>}{!n.read_at&&<Button size="sm" variant="outline" disabled={action.isPending} onClick={()=>action.mutate({path:`/inbox/${n.id}/read`,body:{}})}>Mark read</Button>}</div></article>)}<Pager offset={offset} hasMore={items.data?.hasMore} onChange={setOffset}/></div>;
}
function Policy({current}:{current:{version:number;definition:CommunicationPolicy}}){
  const [definition,setDefinition]=useState(current.definition),[why,setWhy]=useState(''),[error,setError]=useState(''),[offset,setOffset]=useState(0);
  const action=useHubAction();const history=useQuery<Page<any>>({queryKey:[`${hub}/policy/history?offset=${offset}`]});
  return <Section title="Communication rules"><form className="space-y-4" onSubmit={e=>{e.preventDefault();const result=communicationPolicy.safeParse(definition);if(!result.success){setError(result.error.issues.map(i=>i.message).join('; '));return;}setError('');action.mutate({path:'/policy',method:'PUT',body:{version:current.version,definition:result.data,reason:why}});}}><p className="text-sm text-muted-foreground">Current policy version {current.version}. Administrators configure limits; private conversations remain restricted to their participants.</p><label className="block text-sm"><input type="checkbox" checked={definition.directMessages} onChange={e=>setDefinition({...definition,directMessages:e.target.checked})}/> Allow direct messaging</label><label className="block text-sm"><input type="checkbox" checked={definition.groupCreation} onChange={e=>setDefinition({...definition,groupCreation:e.target.checked})}/> Allow authorized managers to create private groups</label><div className="grid gap-3 md:grid-cols-3"><Field label="Message character limit (200–12,000)"><input required type="number" min={200} max={12000} className={fieldClass} value={definition.maxMessageLength} onChange={e=>setDefinition({...definition,maxMessageLength:Number(e.target.value)})}/></Field><Field label="Maximum attachment MB (1–10)"><input required type="number" min={1} max={10} className={fieldClass} value={definition.attachmentMegabytes} onChange={e=>setDefinition({...definition,attachmentMegabytes:Number(e.target.value)})}/></Field><Field label="Visible message history days (30–3,650)"><input required type="number" min={30} max={3650} className={fieldClass} value={definition.historyDays} onChange={e=>setDefinition({...definition,historyDays:Number(e.target.value)})}/></Field></div><p className="text-xs text-muted-foreground">History limits affect message search and attachment access. Older stored records are retained; this setting does not permanently delete them. Group membership and event access dates are enforced separately.</p><Field label="Reason for policy change"><input required minLength={5} className={fieldClass} value={why} onChange={e=>setWhy(e.target.value)}/></Field><QueryError error={action.error||error}/><Button disabled={action.isPending||why.trim().length<5}>Save communication policy</Button></form><details><summary className="cursor-pointer">Policy history</summary><QueryError error={history.error}/>{history.data?.items.map(h=><div key={h.version} className="my-3 rounded border p-3 text-sm"><p>Version {h.version} · {dateLabel(h.created_at)} · {h.reason}</p><p>{h.snapshot.definition.maxMessageLength} characters · {h.snapshot.definition.attachmentMegabytes} MB · {h.snapshot.definition.historyDays} days</p></div>)}<Pager offset={offset} hasMore={history.data?.hasMore} onChange={setOffset}/></details></Section>;
}
