import {useRef,useState,type PointerEvent} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,BookOpen,CheckCircle2,Download,Eye,FileSignature,FileStack,Plus,Send} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {PageHeading} from '@/components/ux/WorkspaceUI';
import {apiJson} from '@/lib/queryClient';
import {contractDraftSchema,contractStatuses,blankDraft,contentOf,editableDraft,fillContractContent,bilingualIssues,agreementEnglish,agreementArabic,type ContractTemplate,type ContractClause,type ContractDraft,type ContractDocument,type ContractRecord,type ContractSignature} from '@shared/contracts';

import {ContentFields,ClauseEditor,DocumentPreview,Readiness,LanguageField} from '@/components/contracts/ContractComposer';
import TemplateLibrary from '@/components/contracts/TemplateLibrary';

const base='/api/contracts';
type Person={id:number;reference:string;name:string;position:string;department:string;location:string;startDate:string;endDate:string|null};
type Context={canManage:boolean;employees:Person[];company?:{name:string;address:string}|null};
type Summary=Pick<ContractRecord,'id'|'reference'|'employee_name'|'status'|'created_at'> & {title:string};
function useSave(done?:(value:{id:number})=>void){
  const cache=useQueryClient();
  return useMutation({mutationFn:({url,body,method='POST'}:{url:string;body:unknown;method?:string})=>apiJson<{id:number}>(url,{method,body}),
    onSuccess:data=>{void cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith(base)});done?.(data);}});
}
const statusLabel=(value:string)=>value==='sent'?'Awaiting signature':value.charAt(0).toUpperCase()+value.slice(1);
const when=(value:string)=>new Date(value).toLocaleString();
export default function Contracts(){
  const [selected,setSelected]=useState<number|null>(()=>{const value=Number(new URLSearchParams(location.search).get('contract'));return Number.isSafeInteger(value)&&value>0?value:null;});
  const [creating,setCreating]=useState(false),[tab,setTab]=useState('contracts');
  const [preset,setPreset]=useState<ContractTemplate|undefined>();
  const context=useQuery<Context>({queryKey:[base+'/context']});
  const open=(id:number)=>{setSelected(id);setCreating(false);};
  return <div className="space-y-6"><PageHeading icon={FileSignature} title="Contracts" description="English + العربية. One agreed version." actions={context.data?.canManage&&!creating&&<Button onClick={()=>{setPreset(undefined);setCreating(true);setSelected(null);setTab('contracts');}}><Plus className="mr-2 h-4 w-4"/>Create contract</Button>}/>
    <QueryError error={context.error}/>{context.isLoading&&<p role="status">Loading your contract access…</p>}
    {creating&&context.data?.canManage?<ContractEditor preset={preset} close={()=>setCreating(false)} done={open}/>:
    selected?<ContractDetail key={selected} id={selected} close={()=>setSelected(null)} open={open}/>:
    <Tabs value={tab} onValueChange={setTab}><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="contracts"><FileSignature className="mr-2 h-4 w-4"/>Contracts</TabsTrigger>{context.data?.canManage&&<><TabsTrigger value="templates"><FileStack className="mr-2 h-4 w-4"/>Templates</TabsTrigger><TabsTrigger value="library"><BookOpen className="mr-2 h-4 w-4"/>Clause library</TabsTrigger></>}</TabsList>
      <TabsContent value="contracts" className="pt-4"><ContractList open={open}/></TabsContent>
      {context.data?.canManage&&<><TabsContent value="templates" className="pt-4"><TemplateLibrary onUse={template=>{setPreset(template);setCreating(true);setSelected(null);}}/></TabsContent><TabsContent value="library" className="pt-4"><ClauseLibrary/></TabsContent></>}
    </Tabs>}
  </div>;
}
function ContractList({open}:{open:(id:number)=>void}){
  const [status,setStatus]=useState(''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(1);
  const query=useQuery<{items:Summary[];hasMore:boolean}>({queryKey:[base,{status,q:search,page}]});
  return <div className="space-y-4"><form className="flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setSearch(q);setPage(1);}}><input aria-label="Find a contract" className={fieldClass+' min-w-0 sm:max-w-sm'} placeholder="Find employee or contract reference" value={q} onChange={e=>setQ(e.target.value)} maxLength={100}/><select aria-label="Contract status" className={fieldClass+' sm:w-auto'} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{contractStatuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select><Button variant="outline">Search</Button></form>
    <QueryError error={query.error}/>{query.isLoading&&<p role="status">Loading contracts…</p>}
    {query.data&&!query.data.items.length&&<Section title="No contracts here yet"><p className="text-sm text-muted-foreground">HR creates and sends contracts. Employees can review, sign and download their own copies here.</p></Section>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{query.data?.items.map(row=><button key={row.id} onClick={()=>open(row.id)} className="module-card rounded-2xl border bg-card p-5 text-left transition-transform motion-safe:hover:-translate-y-1 focus-visible:ring-2 focus-visible:ring-primary"><div className="flex items-center justify-between gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><FileSignature className="h-5 w-5"/></span><Badge variant={row.status==='signed'?'default':'secondary'}>{statusLabel(row.status)}</Badge></div><h2 className="mt-4 font-semibold">{row.employee_name}</h2><p className="mt-1 text-sm text-muted-foreground">{row.title}</p><div className="mt-5 flex justify-between gap-3 border-t pt-3 text-xs text-muted-foreground"><span>{row.reference}</span><span>Open contract →</span></div></button>)}</div>
    <div className="flex items-center gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span className="text-sm">Page {page}</span><Button variant="outline" disabled={!query.data?.hasMore} onClick={()=>setPage(page+1)}>Next</Button></div>
  </div>;
}
function ContractEditor({row,preset,done,close}:{row?:ContractRecord;preset?:ContractTemplate;done:(id:number)=>void;close:()=>void}){
  const [draft,setDraft]=useState<ContractDraft>(()=>row?editableDraft(row.document):{...blankDraft(),...(preset?contentOf(preset.document):{})});
  const [employeeId,setEmployeeId]=useState(row?.employee_id||0),[search,setSearch]=useState(''),[searchTerm,setSearchTerm]=useState(''),[step,setStep]=useState('details');
  const [submissionKey]=useState(()=>crypto.randomUUID()),[picked,setPicked]=useState<Person|null>(null);
  const [source,setSource]=useState(preset?{id:preset.id,version:preset.version,name:preset.name}:null),[choosing,setChoosing]=useState(false);
  const context=useQuery<Context>({queryKey:[base+'/context',{q:searchTerm}]});
  const library=useQuery<ContractClause[]>({queryKey:[base+'/clauses']});
  const save=useSave(value=>done(value.id)),[formError,setFormError]=useState('');
  const person=picked||context.data?.employees.find(e=>e.id===employeeId),people=context.data?.employees||[];
  const choices=picked&&!people.some(p=>p.id===picked.id)?[picked,...people]:people;
  const values={employee_name:row?.document.employeeName||person?.name||'',position:draft.position,department:draft.department,location:draft.location,
    employee_name_ar:draft.employeeNameAr,position_ar:draft.arabic.position,department_ar:draft.arabic.department,location_ar:draft.arabic.location};
  const resolved={...draft,...fillContractContent(contentOf(draft),values)};
  const preview:ContractDocument={...resolved,companyName:row?.document.companyName||context.data?.company?.name||'Company details from Settings',companyAddress:row?.document.companyAddress||context.data?.company?.address||'',employeeName:row?.document.employeeName||person?.name||'Select employee',employeeReference:row?.document.employeeReference||person?.reference||''};
  const selectPerson=(value:string)=>{const next=choices.find(e=>e.id===Number(value)),switching=!!employeeId&&employeeId!==Number(value);setEmployeeId(Number(value));setPicked(next||null);if(next)setDraft(d=>({...d,position:switching?next.position:d.position||next.position,department:switching?next.department:d.department||next.department,location:switching?next.location:d.location||next.location,startDate:next.startDate,endDate:next.endDate||'',employeeNameAr:switching?'':d.employeeNameAr,arabic:switching?{...d.arabic,position:'',department:'',location:''}:d.arabic}));};
  const apply=(template:ContractTemplate)=>{setDraft(d=>({...d,...contentOf(template.document),position:template.document.position||person?.position||d.position,department:template.document.department||person?.department||d.department,location:template.document.location||person?.location||d.location}));setSource({id:template.id,version:template.version,name:template.name});setChoosing(false);};
  const submit=()=>{const parsed=contractDraftSchema.safeParse(resolved);if(!parsed.success){setFormError(parsed.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; '));return;}if(!employeeId){setFormError('Select an employee.');return;}setFormError('');save.mutate({url:row?base+'/'+row.id:base,method:row?'PATCH':'POST',body:row?{version:row.version,document:parsed.data}:{employeeId,document:parsed.data,submissionKey,...(source?{template:{id:source.id,version:source.version}}:{})}});};
  if(choosing)return <div className="space-y-4"><Button variant="ghost" onClick={()=>setChoosing(false)}><ArrowLeft className="mr-2 h-4 w-4"/>Back to draft</Button><p className="rounded-xl bg-muted/50 p-4 text-sm">Applying a template replaces this draft’s title, terms and default arrangements. Employee and dates stay selected.</p><TemplateLibrary onUse={apply}/></div>;
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" onClick={close}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button><Badge variant="outline">Draft · English + العربية</Badge></div>
    {!row&&<div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-primary/5 p-4"><div><p className="font-medium">{source?source.name:'Start with a ready-made template'}</p><p className="mt-1 text-xs text-muted-foreground">{source?'Template v'+source.version+' · This copy stays editable.':'Or build a contract from scratch below.'}</p></div><Button variant="outline" disabled={save.isPending} onClick={()=>setChoosing(true)}><FileStack className="mr-2 h-4 w-4"/>{source?'Change template':'Choose template'}</Button></div>}
    <fieldset className="min-w-0" disabled={save.isPending}><Tabs value={step} onValueChange={setStep}><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="details">1 · Details</TabsTrigger><TabsTrigger value="terms">2 · Terms</TabsTrigger><TabsTrigger value="preview">3 · Review</TabsTrigger></TabsList>
      <TabsContent value="details"><Section title={row?row.employee_name:'Who is this contract for?'}>
        {!row&&<><div className="flex gap-2"><input aria-label="Find employee" className={fieldClass} placeholder="Search employee name or ID" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/><Button type="button" variant="outline" onClick={()=>setSearchTerm(search)}>Find</Button></div><Field label="Employee"><select className={fieldClass} value={employeeId||''} onChange={e=>selectPerson(e.target.value)}><option value="">Select an employee</option>{choices.map(e=><option key={e.id} value={e.id}>{e.name} · {e.reference}</option>)}</select></Field><QueryError error={context.error}/></>}
        <LanguageField label="اسم الموظف · Arabic employee name" arabic max={200} value={draft.employeeNameAr} onChange={employeeNameAr=>setDraft(d=>({...d,employeeNameAr}))}/>
        <div className="grid gap-4 sm:grid-cols-2"><Field label="Start date · تاريخ البدء"><input className={fieldClass} type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></Field><Field label="End date (optional) · تاريخ الانتهاء"><input className={fieldClass} type="date" value={draft.endDate} onChange={e=>setDraft({...draft,endDate:e.target.value})}/></Field></div>
        <ContentFields value={draft} onChange={content=>setDraft(d=>({...d,...content}))}/><Button type="button" onClick={()=>setStep('terms')}>Continue to terms →</Button>
      </Section></TabsContent>
      <TabsContent value="terms"><Section title="Edit both versions together"><p className="text-sm text-muted-foreground">Placeholders fill from the selected employee and Arabic fields in the preview. Edit any term for this employee.</p><QueryError error={library.error}/><ClauseEditor clauses={draft.clauses} onChange={clauses=>setDraft(d=>({...d,clauses}))} library={library.data}/><Button type="button" onClick={()=>setStep('preview')}><Eye className="mr-2 h-4 w-4"/>Review both languages</Button></Section></TabsContent>
      <TabsContent value="preview" className="space-y-4"><Readiness document={preview}/><DocumentPreview document={preview}/></TabsContent>
    </Tabs></fieldset>
    {formError&&<p role="alert" className="text-sm text-destructive">{formError}</p>}<QueryError error={save.error}/><div className="sticky bottom-20 flex items-center justify-between gap-3 rounded-xl border bg-card p-4 shadow-lg md:bottom-4"><span className="text-xs text-muted-foreground">Save your progress. Complete both languages before sending.</span><Button disabled={save.isPending} onClick={submit}>{save.isPending?'Saving…':'Save draft'}</Button></div>
  </div>;
}
function ContractDetail({id,close,open}:{id:number;close:()=>void;open:(id:number)=>void}){
  const query=useQuery<ContractRecord>({queryKey:[base+'/'+id]});const [edit,setEdit]=useState(false);
  return <div className="space-y-4"><Button variant="ghost" onClick={close}><ArrowLeft className="mr-2 h-4 w-4"/>All contracts</Button><QueryError error={query.error}/>{query.isLoading&&<p role="status">Opening contract…</p>}{query.data&&(edit?<ContractEditor key={query.data.version} row={query.data} close={()=>setEdit(false)} done={()=>setEdit(false)}/>:<ContractContents key={id+':'+query.data.version} row={query.data} edit={()=>setEdit(true)} open={open}/>)}</div>;
}
function ContractContents({row,edit,open}:{row:ContractRecord;edit:()=>void;open:(id:number)=>void}){
  const [confirmed,setConfirmed]=useState(false),[note,setNote]=useState(''),[mode,setMode]=useState('');
  const [submissionKey]=useState(()=>crypto.randomUUID());const save=useSave(data=>{setMode('');if(data.id!==row.id)open(data.id);});
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{row.reference}</h2><Badge className="mt-2" variant={row.status==='signed'?'default':'secondary'}>{statusLabel(row.status)}</Badge></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><a href={`${base}/${row.id}/download?download=true`}><Download className="mr-2 h-4 w-4"/>Download HTML</a></Button><Button asChild variant="outline"><a href={`${base}/${row.id}/download`} target="_blank" rel="noreferrer">Print / Save PDF</a></Button>{row.canManage&&row.status==='draft'&&<Button onClick={edit}>Edit draft</Button>}</div></div>
    <DocumentPreview document={row.document}/>{row.status==='draft'&&row.canManage&&<Readiness document={row.document}/>}
    {row.response_note&&<Section title="Response note"><p className="whitespace-pre-wrap text-sm">{row.response_note}</p></Section>}
    {row.signature&&<Section title="Signed by employee"><CheckCircle2 className="h-7 w-7 text-emerald-500"/><p className="font-semibold">{row.signature.name}</p><SignatureDrawing strokes={row.signature.strokes}/><p className="text-sm text-muted-foreground">{when(row.signature.recordedAt)} · Account #{row.signature.userId}</p><p className="text-sm">{row.signature.statement}</p>{row.signature.statementAr&&<p lang="ar" dir="rtl" className="text-right text-sm leading-8">{row.signature.statementAr}</p>}</Section>}
    {row.canSign&&<SignContract row={row}/>}
    {row.canManage&&row.status==='draft'&&<Section title="Ready for employee review?"><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-1"/>I have reviewed the English and Arabic text and approve this exact version for the employee to sign.</label><Button disabled={!confirmed||save.isPending||bilingualIssues(row.document).length>0} onClick={()=>save.mutate({url:`${base}/${row.id}/send`,body:{version:row.version,confirmed:true}})}><Send className="mr-2 h-4 w-4"/>Send for signature</Button></Section>}
    <div className="flex flex-wrap gap-2">{row.canSign&&<Button variant="outline" onClick={()=>setMode('decline')}>Request changes / decline</Button>}{row.canManage&&row.status==='sent'&&<Button variant="outline" onClick={()=>setMode('withdraw')}>Withdraw unsigned copy</Button>}{row.canManage&&row.status!=='draft'&&<Button variant="outline" onClick={()=>setMode('revise')}><Plus className="mr-2 h-4 w-4"/>Create revised draft</Button>}</div>
    {mode&&<Section title={mode==='revise'?'Create a separate draft':mode==='withdraw'?'Withdraw this unsigned copy':'Tell HR what needs to change'}><Field label="Reason"><textarea className={fieldClass} maxLength={2000} minLength={3} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="flex gap-2"><Button disabled={note.trim().length<3||save.isPending} onClick={()=>save.mutate({url:`${base}/${row.id}/${mode}`,body:{version:row.version,note,...(mode==='revise'?{submissionKey}:{})}})}>Confirm</Button><Button variant="ghost" onClick={()=>setMode('')}>Cancel</Button></div></Section>}
    <QueryError error={save.error}/><details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Version and activity</summary><p className="mt-3 break-all text-xs text-muted-foreground">Content fingerprint: {row.content_hash||'Assigned when sent'}</p><ol className="mt-4 space-y-3">{row.history.map((event,index)=><li key={index} className="border-l-2 border-primary/30 pl-3 text-sm"><strong>{event.action}</strong> · {event.actor_name}<p className="text-xs text-muted-foreground">{when(event.created_at)}</p><p>{event.note}</p></li>)}</ol></details>
  </div>;
}
type Strokes=ContractSignature['strokes'];
function SignatureDrawing({strokes}:{strokes:Strokes}){return strokes.length?<svg viewBox="0 0 600 180" role="img" aria-label="Employee signature" className="max-h-36 w-full text-foreground">{strokes.map((line,i)=><polyline key={i} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" points={line.map(([x,y])=>`${x*600},${y*180}`).join(' ')}/>)}</svg>:null;}
function SignContract({row}:{row:ContractRecord}){
  const [name,setName]=useState(''),[password,setPassword]=useState(''),[consent,setConsent]=useState(false),[strokes,setStrokes]=useState<Strokes>([]);
  const drawing=useRef<number|null>(null),save=useSave();
  const point=(e:PointerEvent<SVGSVGElement>):[number,number]=>{const r=e.currentTarget.getBoundingClientRect();return [Math.round(Math.max(0,Math.min(1,(e.clientX-r.left)/r.width))*1000)/1000,Math.round(Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))*1000)/1000];};
  return <Section title="Your agreement · موافقتك"><form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate({url:`${base}/${row.id}/sign`,body:{version:row.version,contentHash:row.content_hash,currentPassword:password,signature:{name,consent,strokes:strokes.filter(line=>line.length>1)}}},{onSettled:()=>setPassword('')});}}><Field label="Your full name"><input className={fieldClass} value={name} minLength={2} maxLength={200} required autoComplete="name" onChange={e=>setName(e.target.value)}/></Field><div><p className="mb-2 text-sm font-medium">Draw your signature (optional)</p><svg preserveAspectRatio="none" viewBox="0 0 600 180" aria-label="Signature drawing area; typing your name above is also accepted" className="h-40 w-full touch-none rounded-xl border bg-background text-foreground" onPointerDown={e=>{if(save.isPending||strokes.length>=20)return;drawing.current=strokes.length;e.currentTarget.setPointerCapture(e.pointerId);setStrokes([...strokes,[point(e)]]);}} onPointerMove={e=>{if(drawing.current===null)return;const p=point(e),at=drawing.current;setStrokes(current=>current.reduce((n,line)=>n+line.length,0)>=1500?current:current.map((line,i)=>i===at&&line.length<400?[...line,p]:line));}} onPointerUp={()=>{drawing.current=null;}} onPointerCancel={()=>{drawing.current=null;}}>{strokes.map((line,i)=><polyline key={i} fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" points={line.map(([x,y])=>`${x*600},${y*180}`).join(' ')}/>)}</svg><Button type="button" variant="ghost" size="sm" onClick={()=>{drawing.current=null;setStrokes([]);}}>Clear drawing</Button></div><Field label="Confirm with your account password"><input className={fieldClass} type="password" autoComplete="current-password" required maxLength={1024} value={password} onChange={e=>setPassword(e.target.value)}/></Field><label className="flex items-start gap-3 text-sm"><input className="mt-1" type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{row.document.languageMode==='en-ar'?agreementEnglish:'I have reviewed this exact contract and agree to its terms. I intend my signature to confirm my agreement.'}{row.document.languageMode==='en-ar'&&<span lang="ar" dir="rtl" className="mt-2 block text-right leading-8">{agreementArabic}</span>}</span></label><p className="text-xs text-muted-foreground">Your account, signature, contract version and signing time will be recorded.</p><QueryError error={save.error}/><Button disabled={save.isPending||!consent||!name.trim()||!password}><FileSignature className="mr-2 h-4 w-4"/>{save.isPending?'Recording signature…':'Sign this contract · توقيع العقد'}</Button></form></Section>;
}
export function ClauseLibrary(){
  const query=useQuery<ContractClause[]>({queryKey:[base+'/clauses']});
  const [editing,setEditing]=useState<ContractClause|null>(null),[creating,setCreating]=useState(false);
  const empty=()=>({title:'',category:'Employment',body:'',titleAr:'',bodyAr:'',active:true});
  const [form,setForm]=useState(empty);const save=useSave(()=>{setEditing(null);setCreating(false);});
  const start=(row?:ContractClause)=>{setEditing(row||null);setCreating(true);setForm(row?{title:row.title,category:row.category,body:row.body,titleAr:row.titleAr||'',bodyAr:row.bodyAr||'',active:row.active}:empty());save.reset();};
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Reusable English–Arabic clauses for templates and employee contracts.</p><Button onClick={()=>start()}><Plus className="mr-2 h-4 w-4"/>Add clause</Button></div><QueryError error={query.error}/>
    {creating&&<Section title={editing?'Edit library clause':'New library clause'}><form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate({url:base+'/clauses'+(editing?'/'+editing.id:''),method:editing?'PATCH':'POST',body:{...form,...(editing?{version:editing.version}:{})}});}}><fieldset disabled={save.isPending} className="space-y-4">
      <Field label="Category"><input className={fieldClass} value={form.category} minLength={2} maxLength={80} required onChange={e=>setForm({...form,category:e.target.value})}/></Field>
      <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-3"><LanguageField label="Clause title · English" max={160} value={form.title} onChange={title=>setForm({...form,title})}/><LanguageField label="Clause text · English" rows={6} value={form.body} onChange={body=>setForm({...form,body})}/></div><div className="space-y-3"><LanguageField label="عنوان البند · Arabic" max={160} value={form.titleAr} arabic onChange={titleAr=>setForm({...form,titleAr})}/><LanguageField label="نص البند · Arabic" rows={6} value={form.bodyAr} arabic onChange={bodyAr=>setForm({...form,bodyAr})}/></div></div>
      <details className="rounded-xl bg-muted/50 p-3 text-xs"><summary className="cursor-pointer">Reusable employee fields</summary><p className="mt-2">{'{{employee_name}}, {{position}}, {{department}}, {{location}}'}</p><p className="mt-2">{'{{employee_name_ar}}, {{position_ar}}, {{department_ar}}, {{location_ar}}'}</p></details>
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Available in the builder</label>
      <QueryError error={save.error}/><div className="flex gap-2"><Button disabled={save.isPending}>{save.isPending?'Saving…':'Save clause'}</Button><Button type="button" variant="ghost" onClick={()=>setCreating(false)}>Cancel</Button></div>
    </fieldset></form></Section>}
    <div className="grid gap-4 md:grid-cols-2">{query.data?.map(row=><Section key={row.id} title={row.title}><Badge variant="outline">{row.category}{!row.active?' · Archived':''}</Badge><p className="line-clamp-3 whitespace-pre-wrap text-sm text-muted-foreground">{row.body}</p><div lang="ar" dir="rtl" className="border-t pt-3 text-right"><h3 className="text-sm font-medium">{row.titleAr||'أضف العنوان العربي'}</h3><p className="mt-2 line-clamp-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{row.bodyAr||'أضف النص العربي قبل استخدام هذا البند.'}</p></div><Button variant="outline" onClick={()=>start(row)}>Edit clause</Button></Section>)}</div>
  </div>;
}
