import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Panel,Field,Paging,LoadState,selectStyle} from '@/components/lifecycle/Common';
import {useServiceSave} from '@/components/lifecycle/EmployeeServices';

const root='employment-continuity';
const human=(s:string)=>s.replaceAll('_',' ');
const offsetDate=(date:string,days:number)=>date?new Date(Date.parse(date)+days*86400000).toISOString().slice(0,10):'Choose exit date';
export function EmploymentHistory({kind,id}:{kind:string;id?:number}){
 const [open,setOpen]=useState(false),q=useQuery<any[]>({queryKey:[`/api/${root}/${kind==='policy'?'policy-history':`${kind}/${id}/history`}`],enabled:open});
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer">History</summary>{q.isLoading&&<p>Loading history…</p>}{q.error&&<p role="alert">Unable to load history.</p>}{q.data?.map(h=><details key={h.version} className="rounded border p-2"><summary>v{h.version} · {h.reason}</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(h.snapshot,null,2)}</pre></details>)}</details>;
}
function EmployeeFinder({label,onSelect,activeOnly=false}:{label:string;onSelect:(person:any)=>void;activeOnly?:boolean}){
 const [search,setSearch]=useState(''),[selected,setSelected]=useState(''),q=useQuery<any[]>({queryKey:[`/api/${root}/people`,{q:search}],enabled:search.trim().length>=2});
 return <div className="space-y-2"><Field label={`Find ${label}`}><Input value={search} placeholder="Name or employee number" onChange={e=>{setSearch(e.target.value);setSelected('');onSelect(null);}}/></Field>{q.error&&<p role="alert">Unable to find employees.</p>}<Field label={label}><select className={selectStyle} required value={selected} onChange={e=>{setSelected(e.target.value);onSelect(q.data?.find(p=>String(p.id)===e.target.value)||null);}}><option value="">Choose employee</option>{q.data?.filter(p=>!activeOnly||p.status==='active').map(p=><option value={p.id} key={p.id}>{p.name} · {p.employee_id}</option>)}</select></Field></div>;
}
export function Contracts(){
 const config=useQuery<any>({queryKey:[`/api/${root}/config`]});
 return <div><h1 className="text-2xl font-bold">Contract renewals</h1><p>Track contract expiry, record verified renewal terms and apply an independently approved extension when effective.</p>{config.error&&<p role="alert">Unable to load permissions.</p>}{config.data?.canConfigure&&<WatchPolicy key={config.data.policy.version} policy={config.data.policy}/>}{config.data?.canManage&&<><ExpiryQueue/><Panel title="Propose a renewal"><Proposal kind="renewals"/></Panel></>}<RecordQueue kind="renewals" manage={!!config.data?.canManage}/></div>;
}
function WatchPolicy({policy:p}:{policy:any}){
 const [days,setDays]=useState(String(p.watch_days)),[reason,setReason]=useState(''),save=useServiceSave();
 return <Panel title="Admin expiry watch rules"><details><summary>Configure expiry watch · version {p.version}</summary><form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:root+'/policy',body:{version:p.version,watchDays:Number(days),reason}});}}><Field label="Days ahead to show in expiry queue"><Input type="number" min={1} max={365} required value={days} onChange={e=>setDays(e.target.value)}/></Field><Field label="Change reason"><Input required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Save rule</Button></form></details><EmploymentHistory kind="policy"/></Panel>;
}
function ExpiryQueue(){
 const [page,setPage]=useState(1),q=useQuery<any>({queryKey:[`/api/${root}/expiring`,{page}]});
 return <Panel title="Contract expiry queue"><p className="text-sm">Expired contracts and contracts ending within {q.data?.watchDays??'…'} days. No automatic renewal or termination occurs.</p><LoadState query={q}/>{q.data?.items.map((e:any)=><article key={e.id} className="rounded border p-3"><strong>{e.name} · {e.employee_id}</strong><p>{e.type} · End date {e.contract_end_date} · {e.days_remaining<0?`${Math.abs(e.days_remaining)} days overdue`:`${e.days_remaining} days remaining`} · {e.renewal_status?`Renewal ${e.renewal_status}`:'No pending renewal'}</p></article>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel>;
}
export function ReturnToWork(){
 const config=useQuery<any>({queryKey:[`/api/${root}/config`]});
 return <div><h1 className="text-2xl font-bold">Return-to-work equipment clearance</h1><p>After HR verifies and restores current employment, independently clear specified completed exit cases so equipment can be issued again. This clearance does not activate an account, change employment status or reset service dates.</p>{config.isLoading?<p>Loading permissions…</p>:config.error?<p role="alert">Unable to load permissions.</p>:config.data?.canManage?<><Panel title="Request clearance"><Proposal kind="clearances"/></Panel><RecordQueue kind="clearances" manage/></>:<p>Organization-wide HR management access is required.</p>}</div>;
}
function Proposal({kind}:{kind:'renewals'|'clearances'}){
 const [person,setPerson]=useState<any>(null),[date,setDate]=useState(''),[end,setEnd]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),save=useServiceSave();
 const exits=useQuery<any[]>({queryKey:[`/api/${root}/clearance-exits/${person?.id}`],enabled:kind==='clearances'&&!!person});
 return <form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();if(!person)return;save.mutate({path:root+'/'+kind,body:{employeeId:person.id,employeeVersion:person.record_version,reason,...(kind==='renewals'?{newEndDate:end,effectiveDate:date,agreementReference:reference}:{returnDate:date,reference})}},{onSuccess:()=>setReason('')});}}><EmployeeFinder label="Employee" activeOnly={kind==='clearances'} onSelect={setPerson}/>{person&&<p>{person.name} · {person.type} · Current contract end: {person.contract_end_date||'Not recorded'}{kind==='renewals'&&!person.contract_end_date&&' — set and verify the original contract in the employee profile first.'}</p>}<Field label={kind==='renewals'?'Renewal effective date':'Verified return-to-work date'}><Input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field>{kind==='renewals'&&<Field label="New contract end date"><Input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></Field>}<Field label={kind==='renewals'?'Verified signed agreement reference':'Verified employment / return approval reference'}><Input required minLength={2} maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field label="Review evidence and reason"><Textarea minLength={5} maxLength={2000} required value={reason} onChange={e=>setReason(e.target.value)}/></Field>{kind==='clearances'&&person&&<div className="md:col-span-2">{exits.isLoading?<p>Checking exit records…</p>:exits.error?<p role="alert">Unable to check exit records.</p>:exits.data?.length?exits.data.map(o=><p key={o.id}>Exit #{o.id} · {o.status}{o.completed_date&&` · Completed ${o.completed_date}`}</p>):<p>No exit case currently needs equipment clearance.</p>}</div>}<Button disabled={save.isPending||!person||(kind==='renewals'&&!person.contract_end_date)||(kind==='clearances'&&(!exits.data?.length||exits.data.some(o=>o.status==='open')))}>Submit for independent review</Button></form>;
}
function RecordQueue({kind,manage}:{kind:'renewals'|'clearances';manage:boolean}){
 const [page,setPage]=useState(1),[status,setStatus]=useState(''),q=useQuery<any>({queryKey:[`/api/${root}/${kind}`,{page,status}]});
 const statuses=kind==='renewals'?['submitted','approved','rejected','cancelled','applied']:['submitted','approved','rejected','cancelled','revoked'];
 return <Panel title={manage?'Requests and decisions':'My approved renewals'}><Field label="Status"><select className={selectStyle} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{statuses.map(s=><option value={s} key={s}>{human(s)}</option>)}</select></Field><LoadState query={q}/>{q.data?.items.map((r:any)=><Request key={r.id+':'+r.version} row={r} kind={kind} showHistory={manage}/>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel>;
}
function Request({row:r,kind,showHistory}:{row:any;kind:'renewals'|'clearances';showHistory:boolean}){
 const [reason,setReason]=useState(''),save=useServiceSave();const act=(action:string)=>save.mutate({path:`${root}/${kind}/${r.id}/actions`,body:{version:r.version,action,reason}});
 const actions=kind==='renewals'?[[r.canReview&&r.status==='submitted','approve','Approve renewal'],[r.canReview&&r.status==='submitted','reject','Reject'],[r.canManage&&r.status==='approved','apply','Apply approved renewal'],[r.canManage&&['submitted','approved'].includes(r.status),'cancel','Cancel']]:[[r.canReview&&r.status==='submitted','approve','Approve equipment clearance'],[r.canReview&&r.status==='submitted','reject','Reject'],[r.canManage&&r.status==='submitted','cancel','Cancel'],[r.canManage&&r.status==='approved','revoke','Revoke future equipment clearance']];
 return <article className="space-y-3 rounded border p-4"><h3 className="font-semibold">{r.employee_name} · {r.status}</h3>{kind==='renewals'?<><p>Contract end {r.previous_end_date} → {r.new_end_date} · Effective {r.effective_date}</p><p>Agreement: {r.agreement_reference}</p>{r.status==='approved'&&<p>Awaiting HR application on or after the effective date.</p>}{r.applied_at&&<p>Applied {new Date(r.applied_at).toLocaleString()}</p>}</>:<><p>Return date {r.return_date} · Exit cases {r.exit_ids.join(', ')}</p><p>Employment reference: {r.reference}</p><p className="text-sm">Clearance covers these exit cases only. Revocation blocks future issuance; existing custody remains recorded.</p></>}<p>{r.proposal_reason}</p>{r.decision_reason&&<p>Decision: {r.decision_reason}</p>}{actions.some(a=>a[0])&&<><Field label="Decision evidence / reason"><Textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000}/></Field><div className="flex flex-wrap gap-2">{actions.filter(a=>a[0]).map(a=><Button key={String(a[1])} variant="outline" disabled={save.isPending||reason.trim().length<5} onClick={()=>act(String(a[1]))}>{String(a[2])}</Button>)}</div></>}{showHistory&&<EmploymentHistory kind={kind} id={r.id}/>}</article>;
}

export function ExitTemplates(){
 const config=useQuery<any>({queryKey:[`/api/${root}/config`]}),[page,setPage]=useState(1),q=useQuery<any>({queryKey:[`/api/${root}/exit-templates`,{page}],enabled:!!config.data?.canManage});
 return <div><h1 className="text-2xl font-bold">Exit checklist templates</h1><p>Prepare repeatable clearance tasks for permanent, temporary and contract employees. Each exit case retains the template version and deadlines used when it started.</p>{config.isLoading?<p>Loading permissions…</p>:config.error?<p role="alert">Unable to load permissions.</p>:!config.data?.canManage?<p>Organization-wide HR management access is required.</p>:<>{config.data?.canConfigure&&<Panel title="Create a reusable exit checklist"><details><summary>Create template</summary><TemplateEditor/></details></Panel>}<Panel title="Templates"><LoadState query={q}/>{q.data?.items.map((r:any)=><article key={r.id+':'+r.version} className="space-y-3 rounded border p-4"><h3 className="font-semibold">{r.name} · v{r.version} · {r.enabled?'Enabled':'Disabled'}</h3><p>For {r.employee_types.join(', ')}</p><ul className="list-disc pl-5">{r.tasks.map((t:any)=><li key={t.key}>{t.title} · {t.kind==='asset'?'Asset return':'Checklist'} · {t.daysFromExit===0?'On exit date':`${Math.abs(t.daysFromExit)} days ${t.daysFromExit<0?'before':'after'} exit`}</li>)}</ul>{r.enabled&&<details><summary>Start an exit case using this version</summary><StartExit row={r}/></details>}{config.data.canConfigure&&<details><summary>Edit / disable template</summary><TemplateEditor row={r}/></details>}<EmploymentHistory kind="exit-templates" id={r.id}/></article>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel></>}<p><a href="/onboarding" className="text-primary underline">Manage offboarding tasks and completion</a></p></div>;
}
type TemplateTask={key:string;title:string;kind:'checklist'|'asset';daysFromExit:number};
function TemplateEditor({row:r}:{row?:any}){
 const [name,setName]=useState(r?.name||''),[enabled,setEnabled]=useState(r?.enabled??true),[types,setTypes]=useState<string[]>(r?.employee_types||['permanent','temporary','contract']),[tasks,setTasks]=useState<TemplateTask[]>(r?.tasks||[]),[reason,setReason]=useState(''),save=useServiceSave();
 return <form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:root+'/exit-templates'+(r?'/'+r.id:''),body:{name,enabled,employeeTypes:types,tasks,reason,...(r?{version:r.version}:{})}},{onSuccess:()=>{if(!r){setName('');setTasks([]);setReason('');}}});}}><Field label="Template name"><Input required minLength={2} maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="flex flex-wrap gap-4">{['permanent','temporary','contract'].map(t=><label key={t}><input type="checkbox" checked={types.includes(t)} onChange={e=>setTypes(e.target.checked?[...types,t]:types.filter(v=>v!==t))}/> {t}</label>)}</div><label className="block"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Allow new exit cases</label>{tasks.map((t,i)=><div className="grid gap-2 rounded border p-3 md:grid-cols-4" key={t.key}><Field label={`Task ${i+1} title`}><Input required minLength={2} maxLength={160} value={t.title} onChange={e=>setTasks(tasks.map(x=>x.key===t.key?{...x,title:e.target.value}:x))}/></Field><Field label="Task type"><select className={selectStyle} value={t.kind} onChange={e=>setTasks(tasks.map(x=>x.key===t.key?{...x,kind:e.target.value as TemplateTask['kind']}:x))}><option value="checklist">Checklist</option><option value="asset">Asset return</option></select></Field><Field label="Days from exit (negative = before)"><Input type="number" min={-365} max={365} required value={t.daysFromExit} onChange={e=>setTasks(tasks.map(x=>x.key===t.key?{...x,daysFromExit:Number(e.target.value)}:x))}/></Field><Button type="button" variant="ghost" onClick={()=>setTasks(tasks.filter(x=>x.key!==t.key))}>Remove draft task</Button></div>)}<Button type="button" variant="outline" disabled={tasks.length>=100} onClick={()=>setTasks([...tasks,{key:crypto.randomUUID(),title:'',kind:'checklist',daysFromExit:0}])}>Add template task</Button><Field label="Template change reason"><Textarea minLength={5} maxLength={2000} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending||!tasks.length||!types.length}>Save template version</Button></form>;
}
function StartExit({row:r}:{row:any}){
 const [employee,setEmployee]=useState<any>(null),[date,setDate]=useState(''),[owners,setOwners]=useState<Record<string,number>>({}),[reason,setReason]=useState(''),[saved,setSaved]=useState<number|null>(null),save=useServiceSave();
 return <form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:'offboarding',body:{employeeId:employee.id,reason,templateId:r.id,templateVersion:r.version,targetExitDate:date,owners:r.tasks.map((t:any)=>({key:t.key,ownerId:owners[t.key]}))}},{onSuccess:result=>setSaved(result.id)});}}><EmployeeFinder label="Departing employee" onSelect={setEmployee}/>{employee&&!r.employee_types.includes(employee.type)&&<p role="alert">This template does not support the selected employment type.</p>}<Field label="Target exit date"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field>{r.tasks.map((t:any)=><div className="rounded border p-3" key={t.key}><strong>{t.title}</strong><p>Due {offsetDate(date,t.daysFromExit)}</p><EmployeeFinder activeOnly label={`Owner for ${t.title}`} onSelect={p=>setOwners({...owners,[t.key]:p?.id||0})}/></div>)}<Field label="Exit case reason"><Textarea required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending||!!saved||!employee||!r.employee_types.includes(employee.type)||r.tasks.some((t:any)=>!owners[t.key]||owners[t.key]===employee?.id)}>Start offboarding from template</Button>{saved&&<p role="status">Exit case #{saved} created. <a href="/onboarding" className="text-primary underline">Continue with task clearance</a></p>}</form>;
}
