import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Helmet} from 'react-helmet';
import {Button} from '@/components/ui/button';
import {Field,Section,Table,QueryError,fieldClass,downloadCsv} from '@/components/hr/Operations';
import {ActionForm,ApproverPicker,EmployeePicker,Files,History,Input,Note,Pager,Reassign,Toggle,number,text,today,useSave,type Directory,type FileInfo} from '@/components/hr/EmployeeServiceUI';
import type {EligibilityRule,ServiceKind} from '@shared/employee-services';
import type {servicePolicies,serviceRequests} from '@shared/schema';
type Policy=typeof servicePolicies.$inferSelect;
type ServiceRequest=typeof serviceRequests.$inferSelect;
type Entitlement={key:string;name:string;policyId:number;config:EligibilityRule;eligible:boolean;message:string;reserved:string;remaining:string;year:number};
const endpoint=(kind:ServiceKind)=>kind==='benefit'?'/api/benefits':'/api/expenses';
const statusLabel=(s:string,kind:ServiceKind)=>s==='fulfilled'?(kind==='expense'?'Reimbursed':'Fulfilled'):s.replaceAll('_',' ');
export function Benefits(){return <EmployeeServices kind="benefit"/>;}
export function Expenses(){return <EmployeeServices kind="expense"/>;}
function EmployeeServices({kind}:{kind:ServiceKind}){
  const base=endpoint(kind),title=kind==='benefit'?'Benefits & entitlements':'Expenses & reimbursements';
  const [tab,setTab]=useState('requests'),[page,setPage]=useState(1),[status,setStatus]=useState(''),[selected,setSelected]=useState<number|null>(null),[create,setCreate]=useState(false),[policy,setPolicy]=useState<Policy|null|undefined>();
  const directory=useQuery<Directory>({queryKey:[base+'/directory']});
  const query=useQuery<{items:{id:number;employeeName:string;title:string;policyKey:string;requestDate:string;amount:string;unit:string|null;status:string}[];total:number}>({queryKey:[base+'/requests',{page,status}],enabled:tab==='requests'});
  const policies=useQuery<{items:{policy:Policy;employeeName:string|null}[];total:number}>({queryKey:[base+'/policies',{page}],enabled:tab==='rules'&&!!directory.data?.canConfigure});
  return <div className="space-y-6"><Helmet><title>{title} | E3 HR</title></Helmet><header className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">{title}</h1><p className="text-muted-foreground mt-1">{kind==='benefit'?'Understand your eligibility, request benefits and track activation.':'Prepare a claim, attach receipts and track approval and reimbursement.'}</p></div><Button onClick={()=>{setCreate(true);setSelected(null);}}>New {kind==='benefit'?'benefit request':'expense claim'}</Button></header><QueryError error={directory.error}/>
  {selected?<><Button variant="outline" onClick={()=>setSelected(null)}>Back to requests</Button><RequestDetail kind={kind} id={selected}/></>:<>
    <div className="flex flex-wrap gap-2">{[['requests','Requests & approvals'],['entitlements','Eligibility & balances'],...(directory.data?.canConfigure?[['rules','Admin rules']]:[])].map(([key,label])=><Button key={key} variant={tab===key?'default':'outline'} onClick={()=>{setTab(key);setPage(1);}}>{label}</Button>)}</div>
    {create&&<Section title={kind==='benefit'?'Prepare benefit request':'Prepare expense claim'}><RequestForm kind={kind} done={id=>{setCreate(false);setSelected(id);}}/><Button variant="ghost" onClick={()=>setCreate(false)}>Cancel</Button></Section>}
    {tab==='requests'&&<Section title="Requests & approvals"><div className="flex flex-wrap items-end gap-3"><Field label="Status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['draft','submitted','approved','returned','rejected','cancelled','fulfilled'].map(s=><option value={s} key={s}>{statusLabel(s,kind)}</option>)}</select></Field><Button variant="outline" onClick={()=>downloadCsv(kind+'-requests-page-'+page+'.csv',[['ID','Employee','Title','Program','Date','Amount','Unit','Status'],...(query.data?.items||[]).map(r=>[r.id,r.employeeName,r.title,r.policyKey,r.requestDate,r.amount,r.unit,r.status])])}>Export this page</Button></div><QueryError error={query.error}/>{query.isLoading&&<p>Loading requests…</p>}<Table headers={['Employee','Request','Date','Amount / units','Status','']} rows={(query.data?.items||[]).map(r=>[r.employeeName,r.title,r.requestDate,`${r.amount} ${r.unit||''}`,statusLabel(r.status,kind),<Button variant="outline" onClick={()=>setSelected(r.id)}>Open</Button>])}/><Pager page={page} total={query.data?.total||0} onChange={setPage}/></Section>}
    {tab==='entitlements'&&<Entitlements kind={kind}/>}
    {tab==='rules'&&directory.data?.canConfigure&&<Section title="Effective company & employee rules"><p className="text-sm text-muted-foreground">Employee overrides take priority over company rules. New submissions keep a saved policy version. Pending, approved and fulfilled requests count toward the annual limit.</p><Button onClick={()=>setPolicy(null)}>Add policy revision</Button>{policy!==undefined&&<><PolicyForm key={policy?.id||0} kind={kind} policy={policy||undefined} done={()=>setPolicy(undefined)}/><Button variant="ghost" onClick={()=>setPolicy(undefined)}>Close rule editor</Button></>}<QueryError error={policies.error}/><Table headers={['Program','Applies to','Effective from','Limits','State','']} rows={(policies.data?.items||[]).map(({policy:p,employeeName})=>[`${p.name} (${p.key})`,employeeName||'Company default',p.effectiveFrom,`${p.config.perRequestLimit} per request / ${p.config.annualLimit} ${p.config.unit} per year`,p.config.enabled?'Enabled':'Disabled',<Button variant="outline" onClick={()=>setPolicy(p)}>Create revision</Button>])}/><Pager page={page} total={policies.data?.total||0} onChange={setPage}/></Section>}
  </>}</div>;
}
function Entitlements({kind}:{kind:ServiceKind}){
  const base=endpoint(kind),[employee,setEmployee]=useState(''),[date,setDate]=useState(today());const query=useQuery<Entitlement[]>({queryKey:[base+'/entitlements',{employeeId:employee,date}],enabled:!!employee&&!!date});
  return <Section title="Eligibility & annual balances"><EmployeePicker base={base} value={employee} onChange={setEmployee}/><Input label="Policy date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><QueryError error={query.error}/><Table headers={['Program','Eligibility','Annual limit','Reserved / used','Available','Per request']} rows={(query.data||[]).map(p=>[p.name,p.eligible?'Eligible':p.message,`${p.config.annualLimit} ${p.config.unit}`,p.reserved,p.remaining,p.config.perRequestLimit])}/><p className="text-sm text-muted-foreground">Balances use the request year and include submitted, approved and fulfilled requests. Drafts and returned, rejected or cancelled requests do not reserve entitlement. Limits do not accrue or carry forward automatically.</p></Section>;
}
function PolicyForm({kind,policy,done}:{kind:ServiceKind;policy?:Policy;done:()=>void}){
  const base=endpoint(kind),c=policy?.config,[employee,setEmployee]=useState(policy?.employeeId?String(policy.employeeId):''),mutation=useSave(done);
  return <form className="space-y-4 rounded border p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({url:base+'/policies',body:{kind,key:text(f,'key'),name:text(f,'name'),employeeId:employee?Number(employee):null,effectiveFrom:text(f,'effectiveFrom'),reason:text(f,'reason'),config:{enabled:f.has('enabled'),employeeTypes:f.getAll('employeeTypes'),departments:text(f,'departments').split(',').map(s=>s.trim()).filter(Boolean),minServiceDays:number(f,'minServiceDays'),annualLimit:text(f,'annualLimit'),perRequestLimit:text(f,'perRequestLimit'),unit:text(f,'unit'),receiptRequired:f.has('receiptRequired'),submissionDays:number(f,'submissionDays'),approverId:number(f,'approverId')}}});}}>
    <div className="grid gap-3 md:grid-cols-2"><Input label="Stable program code" name="key" pattern="[a-z][a-z0-9_-]{1,59}" defaultValue={policy?.key} required placeholder={kind==='expense'?'business-travel':'annual-wellbeing'}/><Input label="Program name" name="name" defaultValue={policy?.name} minLength={3} maxLength={150} required/></div><EmployeePicker base={base} value={employee} onChange={setEmployee} optional/><Input label="Effective from" name="effectiveFrom" type="date" defaultValue={today()} required/><Toggle name="enabled" label="Enable eligibility under this rule" checked={c?.enabled??true}/><fieldset className="space-y-2"><legend className="text-sm font-medium">Eligible employment types</legend><div className="flex flex-wrap gap-4">{['permanent','temporary','contract'].map(type=><label className="text-sm flex gap-2" key={type}><input name="employeeTypes" type="checkbox" value={type} defaultChecked={c?.employeeTypes.includes(type as any)??type==='permanent'}/>{type}</label>)}</div></fieldset><Input label="Eligible departments (comma separated; blank = all)" name="departments" defaultValue={c?.departments.join(', ')}/><div className="grid gap-3 md:grid-cols-3"><Input label="Minimum service (days)" name="minServiceDays" type="number" min={0} max={3650} defaultValue={c?.minServiceDays??0} required/><Input label="Annual entitlement limit" name="annualLimit" inputMode="decimal" pattern="\d{1,8}(\.\d{1,2})?" defaultValue={c?.annualLimit} required/><Input label="Limit per request" name="perRequestLimit" inputMode="decimal" pattern="\d{1,8}(\.\d{1,2})?" defaultValue={c?.perRequestLimit} required/></div><div className="grid gap-3 md:grid-cols-2"><Input label={kind==='expense'?'Currency code (for example QAR)':'Entitlement unit (for example visits, days or QAR)'} name="unit" defaultValue={c?.unit||(kind==='expense'?'QAR':'')} required maxLength={20} pattern={kind==='expense'?'[A-Z]{3}':undefined}/><Input label="Submission window after request date (days)" name="submissionDays" type="number" min={1} max={366} defaultValue={c?.submissionDays??30} required/></div><Toggle name="receiptRequired" label={kind==='expense'?'Require uploaded receipts':'Require supporting evidence'} checked={c?.receiptRequired??kind==='expense'}/><ApproverPicker base={base} value={c?.approverId}/><Note label="Reason for policy revision"/><p className="text-sm text-muted-foreground">Use the same program code for revisions. Use a separate code when changing units or currency within a year that already has reserved or used entitlement.</p><Button disabled={mutation.isPending}>Publish policy revision</Button>
  </form>;
}
function RequestForm({kind,row,done}:{kind:ServiceKind;row?:ServiceRequest;done:(id:number)=>void}){
  const base=endpoint(kind),[employee,setEmployee]=useState(row?String(row.employeeId):''),[date,setDate]=useState(row?.requestDate||today()),[key,setKey]=useState(row?.policyKey||''),[items,setItems]=useState(row?.items.length?row.items:[{description:'',amount:''}]),mutation=useSave<{id:number}>(r=>done(r.id));
  const policies=useQuery<Entitlement[]>({queryKey:[base+'/entitlements',{employeeId:employee,date}],enabled:!!employee&&!!date}),selected=policies.data?.find(p=>p.key===key);
  return <form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({url:base+'/requests'+(row?'/'+row.id:''),method:row?'PATCH':'POST',body:{employeeId:Number(employee),policyKey:key,requestDate:date,title:text(f,'title'),details:text(f,'details'),...(kind==='benefit'?{quantity:text(f,'quantity')}:{items}),...(row?{version:row.version}:{})}});}}>
    {row?<p className="text-sm">Employee #{row.employeeId}</p>:<EmployeePicker base={base} value={employee} onChange={v=>{setEmployee(v);setKey('');}}/>}<Input label={kind==='expense'?'Expense date':'Benefit request date'} type="date" value={date} max={today()} required onChange={e=>setDate(e.target.value)}/><Field label="Program / category"><select className={fieldClass} value={key} required onChange={e=>setKey(e.target.value)}><option value="">Select a program</option>{policies.data?.map(p=><option value={p.key} key={p.key} disabled={!p.eligible}>{p.name} · {p.eligible?p.remaining+' '+p.config.unit+' available':'Not eligible'}</option>)}</select></Field><QueryError error={policies.error}/>{employee&&policies.data&&!policies.data.length&&<p className="text-sm text-muted-foreground">An administrator must configure a matching policy before you can prepare this request.</p>}{selected&&<p className="rounded bg-muted p-3 text-sm">{selected.remaining} {selected.config.unit} available for {selected.year} · {selected.config.perRequestLimit} per request · Submit within {selected.config.submissionDays} days · {selected.config.receiptRequired?'Evidence required':'Evidence optional'}</p>}<Input label="Request title" name="title" defaultValue={row?.title} required minLength={3} maxLength={200}/><Note label="Business purpose / request details" name="details" value={row?.details}/>
    {kind==='benefit'?<Input label={'Requested units'+(selected?' ('+selected.config.unit+')':'')} name="quantity" inputMode="decimal" pattern="\d{1,8}(\.\d{1,2})?" defaultValue={row?.amount} required/>:<Section title="Itemized expenses">{items.map((item,i)=><div key={i} className="grid gap-3 md:grid-cols-[1fr_160px_auto] items-end"><Input label={'Item '+(i+1)} value={item.description} required minLength={3} maxLength={200} onChange={e=>setItems(items.map((v,n)=>n===i?{...v,description:e.target.value}:v))}/><Input label={selected?.config.unit||'Amount'} value={item.amount} required inputMode="decimal" pattern="\d{1,8}(\.\d{1,2})?" onChange={e=>setItems(items.map((v,n)=>n===i?{...v,amount:e.target.value}:v))}/><Button type="button" variant="outline" disabled={items.length===1} onClick={()=>setItems(items.filter((_,n)=>n!==i))}>Remove</Button></div>)}<div className="flex flex-wrap gap-4 items-center"><Button type="button" variant="outline" disabled={items.length>=50} onClick={()=>setItems([...items,{description:'',amount:''}])}>Add item</Button><strong className="text-sm">Total: {items.reduce((sum,i)=>sum+(Number(i.amount)||0),0).toFixed(2)} {selected?.config.unit}</strong></div></Section>}
    <p className="text-sm text-muted-foreground">Save a draft, attach the required evidence, then submit it for approval.</p><Button disabled={mutation.isPending||!selected?.eligible}>Save draft</Button>
  </form>;
}
function RequestDetail({kind,id}:{kind:ServiceKind;id:number}){
  const base=endpoint(kind),[edit,setEdit]=useState(false);const query=useQuery<{row:ServiceRequest;employeeName:string;files:FileInfo[];canPrepare:boolean;canReview:boolean;canFulfill:boolean;canReassign:boolean;storage:boolean}>({queryKey:[base+'/requests/'+id]});
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading request…</p>}</>;const d=query.data,r=d.row,actions:{key:string;label:string}[]=[];
  if(d.canPrepare&&['draft','returned'].includes(r.status))actions.push({key:'submit',label:'Submit for approval'});
  if(d.canPrepare&&['draft','returned','submitted'].includes(r.status)||d.canReview&&r.status==='approved')actions.push({key:'cancel',label:'Cancel request'});
  if(d.canReview&&r.status==='submitted')actions.push({key:'approve',label:'Approve'},{key:'return',label:'Return for correction'},{key:'reject',label:'Reject'});
  if(d.canFulfill&&r.status==='approved')actions.push({key:'fulfill',label:kind==='expense'?'Record reimbursement':'Record benefit activation'});
  return <div className="space-y-5"><Section title={r.title}><div className="grid gap-3 sm:grid-cols-2 text-sm"><p>Employee: <strong>{d.employeeName}</strong></p><p>Status: <strong>{statusLabel(r.status,kind)}</strong></p><p>Program: {r.policySnapshot?.name||r.policyKey}</p><p>Request date: {r.requestDate}</p><p>Requested: <strong>{r.amount} {r.policySnapshot?.config.unit}</strong></p><p>Assigned reviewer: {r.approverId?'User #'+r.approverId:'Assigned when submitted'}</p></div><p className="whitespace-pre-wrap text-sm">{r.details}</p>{r.items.length>0&&<Table headers={['Expense item','Amount']} rows={r.items.map(i=>[i.description,i.amount])}/>} {r.fulfillmentReference&&<p className="rounded bg-muted p-3 text-sm">{kind==='expense'?'Reimbursement':'Activation'} reference: {r.fulfillmentReference} · {new Date(r.fulfilledAt!).toLocaleString()}</p>}{d.canPrepare&&['draft','returned'].includes(r.status)&&<Button variant="outline" onClick={()=>setEdit(!edit)}>{edit?'Close editor':'Edit draft'}</Button>}{edit&&<RequestForm key={r.version} kind={kind} row={r} done={()=>setEdit(false)}/>}</Section>
    {r.policySnapshot&&<details className="rounded border p-4 text-sm"><summary className="cursor-pointer font-medium">Saved policy requirements</summary><div className="space-y-2 mt-3"><p>Policy #{r.policySnapshot.id} · {r.policySnapshot.name}</p><p>Annual limit: {r.policySnapshot.config.annualLimit} {r.policySnapshot.config.unit} · Per request: {r.policySnapshot.config.perRequestLimit}</p><p>Submission window: {r.policySnapshot.config.submissionDays} days · {r.policySnapshot.config.receiptRequired?'Evidence required':'Evidence optional'}</p></div></details>}
    <ActionForm key={r.version} base={base+'/requests'} id={id} version={r.version} actions={actions} fulfill={d.canFulfill&&r.status==='approved'}/><Files base={base+'/requests'} id={id} version={r.version} files={d.files} editable={d.canPrepare&&['draft','returned'].includes(r.status)} storage={d.storage}/>{d.canReassign&&['submitted','approved'].includes(r.status)&&<Reassign base={base+'/requests'} directoryBase={base} id={id} version={r.version}/>}<History events={r.history}/><p className="text-sm text-muted-foreground">{kind==='expense'?'Reimbursement references record payments made outside the app.':'Activation records confirm benefits provided outside the app.'}</p>
  </div>;
}
