import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, QueryError, fieldClass } from '@/components/hr/Operations';
import { EmployeePicker, Input, Note, Pager, Toggle, text, number, today, useSave } from '@/components/hr/EmployeeServiceUI';
import type { EquipmentAsset, EquipmentAssignment, EquipmentHistory, EquipmentPolicy } from '@shared/equipment';

const base='/api/equipment';
type Context={canManage:boolean;canPolicy:boolean;ownEmployeeId:number|null;today:string;policy:EquipmentPolicy&{version:number}};
const label=(s:string)=>s.replaceAll('_',' ');
const open=(status:string)=>['issued','return_requested'].includes(status);
const conditions=['new','good','fair','damaged','lost'];
export default function Equipment(){
  const context=useQuery<Context>({queryKey:[base+'/context']});
  const [tab,setTab]=useState('assignments'),[selected,setSelected]=useState<{kind:'asset'|'assignment';id:number}|null>(null),[creating,setCreating]=useState(false);
  const c=context.data;
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">Equipment & custody</h1><p className="text-muted-foreground mt-1">Track company equipment from issue and employee receipt through return inspection.</p></div>{c?.canManage&&<Button onClick={()=>{setCreating(true);setSelected(null);setTab('inventory');}}>Register equipment</Button>}</header>
    <QueryError error={context.error}/>{context.isLoading&&<p>Loading equipment workspace…</p>}
    {c&&<><nav className="flex flex-wrap gap-2" aria-label="Equipment views"><Button variant={tab==='assignments'?'default':'outline'} onClick={()=>{setTab('assignments');setSelected(null);setCreating(false);}}>Employee custody</Button>{c.canManage&&<Button variant={tab==='inventory'?'default':'outline'} onClick={()=>{setTab('inventory');setSelected(null);setCreating(false);}}>Inventory register</Button>}{c.canPolicy&&<Button variant={tab==='policy'?'default':'outline'} onClick={()=>{setTab('policy');setSelected(null);setCreating(false);}}>Equipment rules</Button>}</nav>
      {selected?<><Button variant="outline" onClick={()=>setSelected(null)}>Back to {tab==='inventory'?'inventory':'custody records'}</Button>{selected.kind==='asset'?<AssetDetail id={selected.id} context={c} issued={id=>{setTab('assignments');setSelected({kind:'assignment',id});}}/>:<AssignmentDetail id={selected.id}/>}</>:
      creating?<Section title="Register equipment"><AssetForm done={row=>{setCreating(false);setSelected({kind:'asset',id:row.id});}}/><Button variant="ghost" onClick={()=>setCreating(false)}>Cancel</Button></Section>:
      tab==='inventory'&&c.canManage?<Inventory select={id=>setSelected({kind:'asset',id})}/>:
      tab==='policy'&&c.canPolicy?<PolicyEditor policy={c.policy}/>:<Assignments select={id=>setSelected({kind:'assignment',id})} context={c}/>}</>}
  </div>;
}
function Inventory({select}:{select:(id:number)=>void}){
  const [q,setQ]=useState(''),[state,setState]=useState(''),[page,setPage]=useState(1);
  const query=useQuery<{items:EquipmentAsset[];total:number;counts:{state:string;count:number}[]}>({queryKey:[base+'/assets',{q,state,offset:(page-1)*25}]});
  return <Section title="Inventory register"><div className="grid gap-3 md:grid-cols-2"><Input label="Find tag, name, serial number or category" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><Field label="Inventory state"><select className={fieldClass} value={state} onChange={e=>{setState(e.target.value);setPage(1);}}><option value="">All inventory</option>{['available','issued','maintenance','retired','lost'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></Field></div>
    <div className="flex flex-wrap gap-2">{query.data?.counts.map(c=><span key={c.state} className="rounded bg-muted px-3 py-2 text-sm">{label(c.state)}: <strong>{c.count}</strong></span>)}</div><QueryError error={query.error}/>{query.isLoading&&<p>Loading inventory…</p>}
    <Table headers={['Asset','Category / serial','Location','Condition / state','']} rows={(query.data?.items||[]).map(a=>[<><strong>{a.asset_tag}</strong><br/>{a.name}</>,<>{a.category}<br/><span className="text-muted-foreground">{a.serial_number||'No serial number'}</span></>,a.location||'Not set',<>{a.condition}<br/>{label(a.state)}</>,<Button variant="outline" onClick={()=>select(a.id)}>Open</Button>])}/><Pager page={page} total={query.data?.total||0} onChange={setPage}/>
  </Section>;
}
function Assignments({select,context}:{select:(id:number)=>void;context:Context}){
  const [q,setQ]=useState(''),[status,setStatus]=useState('open'),[page,setPage]=useState(1),[mine,setMine]=useState(false);
  const query=useQuery<{items:EquipmentAssignment[];total:number}>({queryKey:[base+'/assignments',{q,status,offset:(page-1)*25,...(mine&&context.ownEmployeeId?{employeeId:context.ownEmployeeId}:{})}]});
  return <Section title="Employee custody"><div className="grid gap-3 md:grid-cols-2"><Input label="Search equipment or employee" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><Field label="Custody status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{[['open','Open custody'],['issued','Issued'],['return_requested','Returns awaiting inspection'],['overdue','Overdue return'],['unacknowledged','Unacknowledged / disputed receipt'],['returned','Returned'],['written_off','Written off'],['','All records']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field></div>
    {context.ownEmployeeId&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={mine} onChange={e=>{setMine(e.target.checked);setPage(1);}}/>Only equipment assigned to me</label>}<p className="text-sm text-muted-foreground">Returns stay in the employee’s custody until HR records the inspection. {context.policy.blockOffboarding?'Open custody records prevent final offboarding under the current rule.':'Current equipment rules allow offboarding with open custody.'}</p>
    <QueryError error={query.error}/>{query.isLoading&&<p>Loading custody records…</p>}<Table headers={['Equipment','Employee','Issued / due','Receipt','Custody','']} rows={(query.data?.items||[]).map(r=>[<><strong>{r.asset_tag}</strong><br/>{r.asset_name}</>,<>{r.employee_name}<br/><span className="text-muted-foreground">{r.employee_code}</span></>,<>{r.issued_on}<br/><span className={r.due_on&&r.due_on<context.today&&open(r.status)?'text-destructive':''}>{r.due_on?'Due '+r.due_on:'No return deadline'}</span></>,<>{label(r.acknowledgement)}{r.acknowledgement==='pending'&&r.acknowledgement_due_on&&<p className="text-muted-foreground text-xs">Due {r.acknowledgement_due_on}</p>}</>,label(r.status),<Button variant="outline" onClick={()=>select(r.id)}>Open</Button>])}/><Pager page={page} total={query.data?.total||0} onChange={setPage}/>
  </Section>;
}
function AssetForm({asset,done}:{asset?:EquipmentAsset;done:(row:EquipmentAsset)=>void}){
  const save=useSave<EquipmentAsset>(done);
  return <form key={asset?.version||0} className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),input={assetTag:text(f,'assetTag'),name:text(f,'name'),category:text(f,'category'),serialNumber:text(f,'serialNumber'),location:text(f,'location'),purchaseDate:text(f,'purchaseDate')||null,warrantyUntil:text(f,'warrantyUntil')||null,condition:text(f,'condition'),notes:text(f,'notes')};save.mutate({url:base+'/assets'+(asset?'/'+asset.id:''),method:asset?'PATCH':'POST',body:asset?{version:asset.version,asset:input,state:text(f,'state'),reason:text(f,'reason')}:input});}}>
    <div className="grid gap-3 md:grid-cols-2"><Input label="Asset tag" name="assetTag" required minLength={2} maxLength={100} defaultValue={asset?.asset_tag}/><Input label="Equipment name" name="name" required minLength={2} maxLength={200} defaultValue={asset?.name}/><Input label="Category" name="category" required minLength={2} maxLength={100} defaultValue={asset?.category} placeholder="Laptop, radio, uniform, event kit…"/><Input label="Serial number (optional)" name="serialNumber" maxLength={150} defaultValue={asset?.serial_number}/><Input label="Inventory location" name="location" maxLength={200} defaultValue={asset?.location}/><Condition label="Recorded condition" name="condition" value={asset?.condition||'good'} lost={!!asset&&asset.condition==='lost'}/><Input label="Purchase date (optional)" name="purchaseDate" type="date" max={today()} defaultValue={asset?.purchase_date||''}/><Input label="Warranty expiry (optional)" name="warrantyUntil" type="date" defaultValue={asset?.warranty_until||''}/></div>
    {asset&&<Field label="Inventory state"><select className={fieldClass} name="state" defaultValue={asset.state}>{(asset.state==='issued'?['issued']:['available','maintenance','retired',...(asset.state==='lost'?['lost']:[])]).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></Field>}
    <Field label="Inventory notes (optional)"><textarea className={fieldClass} name="notes" rows={3} maxLength={2000} defaultValue={asset?.notes}/></Field>{asset&&<Note label="Reason for inventory revision"/>}<Button disabled={save.isPending}>{asset?'Save inventory revision':'Register equipment'}</Button>
  </form>;
}
function AssetDetail({id,context,issued}:{id:number;context:Context;issued:(id:number)=>void}){
  const query=useQuery<EquipmentAsset>({queryKey:[base+'/assets/'+id]}),[edit,setEdit]=useState(false),[issue,setIssue]=useState(false),a=query.data;
  if(!a)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading equipment…</p>}</>;
  return <div className="space-y-5"><Section title={`${a.asset_tag} · ${a.name}`}><div className="grid gap-3 md:grid-cols-2 text-sm"><p>Category: <strong>{a.category}</strong></p><p>State: <strong>{label(a.state)}</strong> · Condition: {a.condition}</p><p>Serial number: {a.serial_number||'Not recorded'}</p><p>Location: {a.location||'Not recorded'}</p><p>Purchased: {a.purchase_date||'Not recorded'}</p><p>Warranty expiry: {a.warranty_until||'Not recorded'}</p></div>{a.notes&&<p className="whitespace-pre-wrap text-sm">{a.notes}</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>setEdit(!edit)}>{edit?'Close editor':'Edit inventory record'}</Button>{a.state==='available'&&<Button onClick={()=>setIssue(!issue)}>{issue?'Cancel issue':'Issue to employee'}</Button>}</div></Section>
    {edit&&<Section title="Revise inventory"><AssetForm key={a.version} asset={a} done={()=>setEdit(false)}/></Section>}
    {issue&&a.state==='available'&&<Section title="Issue equipment"><IssueForm key={a.version} asset={a} policy={context.policy} done={issued}/></Section>}
    <RecordHistory kind="assets" id={id}/>
  </div>;
}
function IssueForm({asset,policy,done}:{asset:EquipmentAsset;policy:Context['policy'];done:(id:number)=>void}){
  const [employee,setEmployee]=useState(''),save=useSave<EquipmentAssignment>(row=>done(row.id));
  return <form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:base+'/assignments',body:{assetId:asset.id,assetVersion:asset.version,employeeId:Number(employee),issuedOn:text(f,'issuedOn'),dueOn:text(f,'dueOn')||null,condition:text(f,'condition'),note:text(f,'reason')}});}}>
    <EmployeePicker base={base} value={employee} onChange={setEmployee}/><div className="grid gap-3 md:grid-cols-2"><Input label="Issue date" name="issuedOn" type="date" defaultValue={today()} max={today()} required/><Input label={policy.maxLoanDays?`Return due date (within ${policy.maxLoanDays} days of issue)`:'Return due date (optional)'} name="dueOn" type="date" required={policy.maxLoanDays!==null}/></div><Condition name="condition" label="Condition at handover" value={asset.condition==='lost'?'good':asset.condition}/><Note label="Handover evidence / issue note"/><p className="text-sm text-muted-foreground">{policy.acknowledgementRequired?`The employee must acknowledge receipt within ${policy.acknowledgementDays} days.`:'Receipt acknowledgement is optional under the current equipment rule.'} This custody record keeps the rules and equipment details from the issue date.</p><Button disabled={save.isPending||!employee}>Record issue</Button>
  </form>;
}
type AssignmentDetailData={row:EquipmentAssignment;employeeName:string;employeeCode:string;assetVersion:number;canAcknowledge:boolean;canRequestReturn:boolean;canManage:boolean;canWriteOff:boolean;canReview:boolean};
function AssignmentDetail({id}:{id:number}){
  const query=useQuery<AssignmentDetailData>({queryKey:[base+'/assignments/'+id]}),d=query.data;
  if(!d)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading equipment custody…</p>}</>;
  const r=d.row;
  return <div className="space-y-5"><Section title={`${r.asset_snapshot.asset_tag} · ${r.asset_snapshot.name}`}><div className="grid gap-3 md:grid-cols-2 text-sm"><p>Employee: <strong>{d.employeeName}</strong> · {d.employeeCode}</p><p>Status: <strong>{label(r.status)}</strong></p><p>Issued: {r.issued_on} · Condition: {r.issued_condition}</p><p>Return deadline: {r.due_on||'Not set'}</p><p>Serial: {r.asset_snapshot.serial_number||'Not recorded'}</p><p>Receipt: <strong>{label(r.acknowledgement)}</strong>{r.acknowledgement_due_on?' · Due '+r.acknowledgement_due_on:''}</p></div><p className="whitespace-pre-wrap text-sm"><strong>Handover note: </strong>{r.issue_note}</p>{r.acknowledgement_note&&<p className="whitespace-pre-wrap text-sm"><strong>Employee receipt response: </strong>{r.acknowledgement_note}</p>}
      {r.return_request_note&&<div className="rounded bg-muted p-4 text-sm"><p><strong>Reported condition: </strong>{r.requested_condition}</p><p className="whitespace-pre-wrap mt-1">{r.return_request_note}</p></div>}
      {r.return_note&&<p className="whitespace-pre-wrap text-sm"><strong>HR inspection / decision: </strong>{r.return_note}</p>}{!open(r.status)&&<p className="text-sm">Closed {r.returned_on} · Final condition: {r.returned_condition} · User #{r.closed_by}</p>}{r.return_evidence&&<p className="whitespace-pre-wrap text-sm"><strong>Evidence / receipt: </strong>{r.return_evidence}</p>}
    </Section>
    {d.canAcknowledge&&<Acknowledgement key={'ack'+r.version} row={r}/>}{d.canRequestReturn&&<ReturnRequest key={'request'+r.version} row={r}/>}
    {d.canReview&&open(r.status)&&<ReturnInspection key={'review'+r.version+':'+d.assetVersion} data={d}/>}
    {d.canManage&&open(r.status)&&<DueDateEditor key={'due'+r.version} row={r}/>}
    {d.canWriteOff&&open(r.status)&&<WriteOff key={'writeoff'+r.version+':'+d.assetVersion} data={d}/>}
    <details className="rounded border p-4"><summary className="cursor-pointer text-sm font-medium">Saved equipment rules · Version {r.policy_snapshot.version}</summary><div className="space-y-1 mt-3 text-sm"><p>Receipt acknowledgement: {r.policy_snapshot.acknowledgementRequired?'Required':'Optional'}</p><p>Maximum loan: {r.policy_snapshot.maxLoanDays?r.policy_snapshot.maxLoanDays+' days':'No configured maximum'}</p><p>Employee return request: {r.policy_snapshot.requireReturnRequest?'Required before inspection':'Optional before inspection'}</p><p>Return evidence: {r.policy_snapshot.returnEvidenceRequired?'Required':'Optional'}</p><p>Independent return review: {r.policy_snapshot.independentReturnReview?'Required':'Standard HR review'}</p></div></details>
    <RecordHistory kind="assignments" id={id}/>
  </div>;
}
function Acknowledgement({row}:{row:EquipmentAssignment}){
  const save=useSave();return <Section title="Confirm equipment receipt"><form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/assignments/${row.id}/acknowledge`,body:{version:row.version,decision:text(f,'decision'),note:text(f,'reason')}});}}><Field label="Receipt response"><select name="decision" className={fieldClass}><option value="accepted">I received the listed equipment</option><option value="disputed">I need HR to correct this handover</option></select></Field><Note label="Receipt confirmation / discrepancy details"/><Button disabled={save.isPending}>Send receipt response</Button></form></Section>;
}
function ReturnRequest({row}:{row:EquipmentAssignment}){
  const save=useSave();return <details className="rounded border p-4"><summary className="cursor-pointer font-medium">Request equipment return or report loss</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/assignments/${row.id}/request-return`,body:{version:row.version,condition:text(f,'condition'),note:text(f,'reason')}});}}><Condition name="condition" label="Current condition" value="good" lost/><Note label="Return arrangements, condition or loss details"/><p className="text-sm text-muted-foreground">HR must inspect the equipment and close this custody record. Reporting loss does not create a payroll deduction.</p><Button disabled={save.isPending}>Send to HR</Button></form></details>;
}
function ReturnInspection({data}:{data:AssignmentDetailData}){
  const r=data.row,save=useSave(),[action,setAction]=useState('return');
  return <Section title="HR return inspection"><form className="space-y-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/assignments/${r.id}/${action}`,body:action==='reject-return'?{version:r.version,note:text(f,'reason')}:{version:r.version,assetVersion:data.assetVersion,returnedOn:text(f,'returnedOn'),condition:text(f,'condition'),disposition:text(f,'disposition'),note:text(f,'reason'),evidence:text(f,'evidence')}});}}>
    {r.status==='return_requested'&&<Field label="Review decision"><select className={fieldClass} value={action} onChange={e=>setAction(e.target.value)}><option value="return">Confirm received and inspected</option><option value="reject-return">Send request back to employee</option></select></Field>}
    {action==='return'&&<><div className="grid gap-3 md:grid-cols-2"><Input label="Actual return date" name="returnedOn" type="date" min={r.issued_on} max={today()} defaultValue={today()} required/><Condition name="condition" label="Inspected condition" value={r.requested_condition&&r.requested_condition!=='lost'?r.requested_condition:'good'}/></div><Field label="Inventory destination"><select className={fieldClass} name="disposition"><option value="available">Available for another issue</option><option value="maintenance">Hold for maintenance</option><option value="retired">Retire from service</option></select></Field><Field label="Return evidence / signed receipt reference"><textarea className={fieldClass} name="evidence" rows={2} maxLength={2000} minLength={r.policy_snapshot.returnEvidenceRequired?5:undefined} required={r.policy_snapshot.returnEvidenceRequired}/></Field>{r.policy_snapshot.requireReturnRequest&&r.status!=='return_requested'&&<p className="text-sm text-muted-foreground">The saved rule requires the employee to request return first.</p>}</>}
    <Note label={action==='return'?'Inspection note':'Reason for returning the request'}/><Button disabled={save.isPending||(action==='return'&&r.policy_snapshot.requireReturnRequest&&r.status!=='return_requested')}>{action==='return'?'Confirm return & close custody':'Return request to employee'}</Button>
  </form></Section>;
}
function DueDateEditor({row}:{row:EquipmentAssignment}){
  const save=useSave();return <details className="rounded border p-4"><summary className="cursor-pointer text-sm font-medium">Change return deadline</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/assignments/${row.id}/due-date`,body:{version:row.version,dueOn:text(f,'dueOn')||null,note:text(f,'reason')}});}}><Input label="Return deadline" name="dueOn" type="date" min={row.issued_on} defaultValue={row.due_on||''} required={row.policy_snapshot.maxLoanDays!==null}/><Note label="Reason for changing the deadline"/><Button disabled={save.isPending}>Save return deadline</Button></form></details>;
}
function WriteOff({data}:{data:AssignmentDetailData}){
  const save=useSave(),r=data.row;return <details className="rounded border p-4"><summary className="cursor-pointer text-sm font-medium">Administrator equipment write-off</summary><form className="space-y-3 mt-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:`${base}/assignments/${r.id}/write-off`,body:{version:r.version,assetVersion:data.assetVersion,closedOn:text(f,'closedOn'),condition:text(f,'condition'),note:text(f,'reason'),evidence:text(f,'evidence')}});}}><p className="text-sm text-muted-foreground">Close custody for confirmed lost or damaged equipment. This records the inventory decision and does not make an employee payroll deduction.</p><Input label="Write-off date" name="closedOn" type="date" min={r.issued_on} max={today()} defaultValue={today()} required/><Field label="Write-off condition"><select className={fieldClass} name="condition"><option value="lost">Lost</option><option value="damaged">Damaged beyond continued use</option></select></Field><Field label="Reason for write-off"><textarea className={fieldClass} name="reason" required minLength={10} maxLength={2000} rows={3}/></Field><Note label="Decision evidence / approval reference" name="evidence"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" required/>I confirm this equipment custody should be closed as a write-off.</label><Button disabled={save.isPending} variant="outline">Record write-off</Button></form></details>;
}
function Condition({name,label:caption,value='good',lost=false}:{name:string;label:string;value?:string;lost?:boolean}){
  return <Field label={caption}><select className={fieldClass} name={name} defaultValue={value}>{conditions.filter(c=>lost||c!=='lost').map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field>;
}
function RecordHistory({kind,id}:{kind:'assets'|'assignments';id:number}){
  const [page,setPage]=useState(1),query=useQuery<{items:EquipmentHistory[];total:number}>({queryKey:[`${base}/${kind}/${id}/history`,{offset:(page-1)*25}]});
  return <Section title="Record history"><QueryError error={query.error}/>{query.isLoading&&<p>Loading history…</p>}<ol className="space-y-4">{query.data?.items.map(h=><li key={h.id} className="border-b pb-3 text-sm"><p className="font-medium">Version {h.version} · User #{h.actor_id} · {new Date(h.created_at).toLocaleString()}</p><p className="whitespace-pre-wrap mt-1">{h.reason}</p><details className="mt-2"><summary className="cursor-pointer text-muted-foreground">Saved record</summary><pre className="overflow-auto rounded bg-muted p-3 text-xs mt-2">{JSON.stringify(h.snapshot,null,2)}</pre></details></li>)}</ol><Pager page={page} total={query.data?.total||0} onChange={setPage}/></Section>;
}
function PolicyEditor({policy}:{policy:Context['policy']}){
  const save=useSave(),[page,setPage]=useState(1),history=useQuery<{items:{id:number;version:number;definition:EquipmentPolicy;reason:string;created_at:string}[];total:number}>({queryKey:[base+'/policy/history',{offset:(page-1)*25}]});
  return <div className="space-y-5"><Section title={`Equipment rules · Version ${policy.version}`}><form key={policy.version} className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save.mutate({url:base+'/policy',body:{version:policy.version,definition:{acknowledgementRequired:f.has('acknowledgementRequired'),acknowledgementDays:number(f,'acknowledgementDays'),maxLoanDays:text(f,'maxLoanDays')?number(f,'maxLoanDays'):null,requireReturnRequest:f.has('requireReturnRequest'),independentReturnReview:f.has('independentReturnReview'),returnEvidenceRequired:f.has('returnEvidenceRequired'),blockOffboarding:f.has('blockOffboarding')},reason:text(f,'reason')}});}}>
    <Toggle label="Require employee receipt acknowledgement" name="acknowledgementRequired" checked={policy.acknowledgementRequired}/><div className="grid gap-3 md:grid-cols-2"><Input label="Receipt acknowledgement deadline (calendar days)" name="acknowledgementDays" type="number" min={1} max={365} defaultValue={policy.acknowledgementDays} required/><Input label="Maximum loan duration (calendar days; blank = no maximum)" name="maxLoanDays" type="number" min={1} max={3650} defaultValue={policy.maxLoanDays??''}/></div><Toggle label="Require an employee return request before HR inspection" name="requireReturnRequest" checked={policy.requireReturnRequest}/><Toggle label="Require independent return review" name="independentReturnReview" checked={policy.independentReturnReview}/><Toggle label="Require return evidence or signed receipt reference" name="returnEvidenceRequired" checked={policy.returnEvidenceRequired}/><Toggle label="Prevent final offboarding while employee equipment custody is open" name="blockOffboarding" checked={policy.blockOffboarding}/><p className="text-sm text-muted-foreground">Receipt, loan and return rules apply to newly issued equipment. Existing custody keeps its saved rules. The offboarding clearance rule applies immediately to every final offboarding decision.</p><Note label="Reason for equipment policy revision"/><Button disabled={save.isPending}>Publish equipment rules</Button>
    </form></Section><Section title="Policy versions"><QueryError error={history.error}/>{history.data?.items.map(h=><details className="rounded border p-3 text-sm" key={h.id}><summary className="cursor-pointer">Version {h.version} · {new Date(h.created_at).toLocaleString()}</summary><p className="whitespace-pre-wrap mt-2">{h.reason}</p><pre className="overflow-auto bg-muted rounded p-3 mt-2 text-xs">{JSON.stringify(h.definition,null,2)}</pre></details>)}<Pager page={page} total={history.data?.total||0} onChange={setPage}/></Section></div>;
}
