import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link} from 'wouter';
import type {Event,EventStaffAssignment,EventRole} from '@shared/schema';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Button} from '@/components/ui/button';
export default function EventArchive(){
 const [search,setSearch]=useState(''),[page,setPage]=useState(1);
 const events=useQuery<Event[]>({queryKey:['/api/events']}),roles=useQuery<EventRole[]>({queryKey:['/api/event-roles']}),assignments=useQuery<EventStaffAssignment[]>({queryKey:['/api/event-staff-assignments']});
 const matching=(events.data||[]).filter(e=>e.name.toLowerCase().includes(search.toLowerCase()));
 return <div className="space-y-4"><h2 className="text-2xl font-semibold">Earlier event records</h2><p>These records remain available for reference. Schedule new event, FEC and mall activation shifts in Workforce. Earlier assignments continue to participate in conflict checks; they are not copied into new teams.</p><Link href="/event-staff" className="underline text-primary">Open event and FEC operations</Link><div><Label htmlFor="archive-search">Find an earlier event</Label><Input id="archive-search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div>{[events,roles,assignments].some(q=>q.isPending)&&<p role="status">Loading earlier records…</p>}{[events,roles,assignments].some(q=>q.error)&&<p role="alert">Unable to load all earlier records. Refresh to retry.</p>}{matching.slice((page-1)*20,page*20).map(event=><section className="border rounded p-4 space-y-2" key={event.id}><h3 className="font-semibold">{event.name}</h3><p>{String(event.startDate).slice(0,10)} – {String(event.endDate).slice(0,10)} · {event.location} · {event.status}</p><details><summary>Roles and assignments</summary>{roles.data?.filter(r=>r.eventId===event.id).map(r=><p key={r.id}>{r.roleName} · {r.numberOfStaff} positions</p>)}<div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr><th>Employee reference</th><th>Role</th><th>Status</th><th>Assignment dates</th></tr></thead><tbody>{assignments.data?.filter(a=>a.eventId===event.id).map(a=><tr className="border-t" key={a.id}><td className="py-2">Employee #{a.employeeId}</td><td>{a.role}</td><td>{a.status}</td><td>{String(a.startTime).slice(0,10)} – {String(a.endTime).slice(0,10)}</td></tr>)}</tbody></table></div></details></section>)}{events.isSuccess&&matching.length===0&&<p>No earlier events match.</p>}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous events</Button><Button variant="outline" disabled={page*20>=matching.length} onClick={()=>setPage(p=>p+1)}>Next events</Button></div></div>;
}
