import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, QueryError, fieldClass } from '@/components/hr/Operations';
import { Input, Note, Toggle, text, number, today, useSave } from '@/components/hr/EmployeeServiceUI';
import type { HandbookAssignment, HandbookBook, HandbookEdition, HandbookPolicy } from '@shared/handbook';

const base='/api/handbook';
type Overview={canManage:boolean;canPublish:boolean;canSetRules:boolean;policy:HandbookPolicy};
type Edition=HandbookEdition&{active:boolean;category:string;handbook_version:number};
type EditionDetail={row:Edition;editions:{id:number;edition_number:number;status:string;effective_on:string}[]};
type HistoryItem={version:number;reason:string;actor_id:number;created_at:string;status?:string;due_date?:string;read_at?:string;acknowledged_at?:string;snapshot?:HandbookEdition};
const pretty=(value:string|null|undefined)=>value?new Date(value).toLocaleString():'—';
function nextDate(days:number){const value=new Date(today()+'T12:00:00Z');value.setUTCDate(value.getUTCDate()+days);return value.toISOString().slice(0,10);}
function PageControls({offset,hasMore,change}:{offset:number;hasMore:boolean;change:(value:number)=>void}){return <div className="flex items-center gap-3"><Button variant="outline" disabled={!offset} onClick={()=>change(Math.max(0,offset-25))}>Previous</Button><span className="text-sm">Page {offset/25+1}</span><Button variant="outline" disabled={!hasMore} onClick={()=>change(offset+25)}>Next</Button></div>;}

export default function Handbook(){
  const [tab,setTab]=useState('mine'),[editionId,setEditionId]=useState<number|null>(null),[assignmentId,setAssignmentId]=useState<number|null>(null),[create,setCreate]=useState(false);
  const overview=useQuery<Overview>({queryKey:[base+'/overview']});
  const selectTab=(value:string)=>{setTab(value);setEditionId(null);setAssignmentId(null);setCreate(false);};
  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold">Handbooks & acknowledgements</h1><p className="mt-1 text-muted-foreground">Read company guidance and keep a record of the exact edition you acknowledge.</p></div>{overview.data?.canPublish&&<Button onClick={()=>{selectTab('library');setCreate(true);}}>Create handbook</Button>}</header><QueryError error={overview.error}/>
    <nav className="flex flex-wrap gap-2" aria-label="Handbook sections">{[['mine','My acknowledgements'],['library','Published library'],...(overview.data?.canManage?[['team','Assignment management']]:[]),...(overview.data?.canSetRules?[['rules','Acknowledgement rules']]:[])].map(([value,label])=><Button key={value} variant={tab===value?'default':'outline'} onClick={()=>selectTab(value)}>{label}</Button>)}</nav>
    {overview.isLoading&&<p>Loading handbooks…</p>}{overview.data&&(assignmentId?<><Button variant="outline" onClick={()=>setAssignmentId(null)}>Back to assignments</Button><AssignmentDetail id={assignmentId}/></>:editionId?<><Button variant="outline" onClick={()=>setEditionId(null)}>Back to library</Button><EditionPanel key={editionId} id={editionId} overview={overview.data} select={setEditionId}/></>:create?<Section title="New handbook draft"><ContentForm done={row=>{setCreate(false);setEditionId(row.id);}}/><Button variant="ghost" onClick={()=>setCreate(false)}>Cancel</Button></Section>:tab==='library'?<Library overview={overview.data} select={setEditionId}/>:tab==='rules'?<Rules policy={overview.data.policy}/>:<Assignments key={tab} view={tab==='team'?'team':'mine'} select={setAssignmentId}/>)}
  </div>;
}

function Library({overview,select}:{overview:Overview;select:(id:number)=>void}){
  const [q,setQ]=useState(''),[offset,setOffset]=useState(0),[archived,setArchived]=useState(false);
  const query=useQuery<{items:HandbookBook[];hasMore:boolean}>({queryKey:[base+'/catalogue',{q,offset,archived}]});
  return <Section title={overview.canPublish?'Handbook catalogue':'Published library'}><div className="flex flex-wrap items-end gap-4"><Input label="Search title or category" value={q} onChange={e=>{setQ(e.target.value);setOffset(0);}}/>{overview.canPublish&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setOffset(0);}}/>Include archived handbooks</label>}</div><QueryError error={query.error}/>{query.isLoading&&<p>Loading library…</p>}<div className="grid gap-4 lg:grid-cols-2">{query.data?.items.map(item=><article key={item.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{item.title}</h3><span className="text-sm text-muted-foreground">{item.active?item.edition_status:'Archived'}</span></div><p className="text-sm">{item.category} · Edition {item.edition_number} · Effective {item.effective_on}</p><Button variant="outline" onClick={()=>select(item.edition_id)}>{item.edition_status==='draft'?'Open draft':'Read handbook'}</Button></article>)}</div>{query.data&&!query.data.items.length&&<p className="text-sm text-muted-foreground">No handbooks match this selection.</p>}<PageControls offset={offset} hasMore={!!query.data?.hasMore} change={setOffset}/></Section>;
}

function ContentForm({edition,newEdition=false,done}:{edition?:Edition;newEdition?:boolean;done:(row:HandbookEdition)=>void}){
  const mutation=useSave<HandbookEdition>(done);
  return <form className="space-y-4" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),content={title:text(form,'title'),summary:text(form,'summary'),body:text(form,'body'),effectiveOn:text(form,'effectiveOn'),reason:text(form,'reason')};mutation.mutate({url:edition?newEdition?`${base}/catalogue/${edition.handbook_id}/editions`:`${base}/editions/${edition.id}`:base+'/catalogue',method:edition&&!newEdition?'PATCH':'POST',body:{...content,...(edition?newEdition?{sourceEditionId:edition.id}:{version:edition.version}:{category:text(form,'category')})}});}}>
    <div className="grid gap-4 md:grid-cols-2"><Input label="Title" name="title" defaultValue={edition?.title} minLength={3} maxLength={200} required/>{!edition?<Input label="Category" name="category" placeholder="Workplace policies" minLength={2} maxLength={80} required/>:<Input label="Effective date" type="date" name="effectiveOn" defaultValue={newEdition?today():edition.effective_on} required/>}</div>{!edition&&<Input label="Effective date" type="date" name="effectiveOn" defaultValue={today()} required/>}<Field label="Short description"><textarea className={fieldClass} name="summary" rows={2} maxLength={1000} defaultValue={edition?.summary}/></Field><Field label="Handbook content"><textarea className={fieldClass+' min-h-[22rem]'} name="body" rows={18} minLength={20} maxLength={100000} required defaultValue={edition?.body} placeholder="Enter the complete policy or handbook text. Paragraph breaks will be preserved."/></Field><Note label={edition?'Reason for this edition or revision':'Reason for creating this handbook'}/><p className="text-sm text-muted-foreground">Save a draft first. Publishing preserves this edition permanently, and future changes require a new edition.</p><Button disabled={mutation.isPending}>{mutation.isPending?'Saving…':newEdition?'Create new draft':'Save draft'}</Button>
  </form>;
}

function EditionPanel({id,overview,select}:{id:number;overview:Overview;select:(id:number)=>void}){
  const query=useQuery<EditionDetail>({queryKey:[base+'/editions/'+id]}),[edit,setEdit]=useState(false),[assign,setAssign]=useState(false),mutation=useSave(()=>setEdit(false));
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading edition…</p>}</>;
  const row=query.data.row,latest=query.data.editions[0]?.id===row.id;
  return <div className="space-y-5"><Section title={row.title}><div className="flex flex-wrap justify-between gap-3"><p className="text-sm">{row.category} · Edition {row.edition_number} · {row.status} · Effective {row.effective_on}{!row.active?' · Archived':''}</p><Field label="Edition"><select className={fieldClass} value={row.id} onChange={e=>{setEdit(false);setAssign(false);select(Number(e.target.value));}}>{query.data.editions.map(item=><option key={item.id} value={item.id}>Edition {item.edition_number} · {item.status}</option>)}</select></Field></div>{row.summary&&<p className="text-muted-foreground whitespace-pre-wrap">{row.summary}</p>}{row.status==='published'&&<p className="text-sm text-muted-foreground">Published {pretty(row.published_at)}. Existing employee acknowledgements remain tied to this edition.</p>}<article className="whitespace-pre-wrap break-words rounded border bg-background p-5 text-sm leading-7">{row.body}</article><div className="flex flex-wrap gap-2">{overview.canPublish&&(row.status==='draft'||latest&&row.active)&&<Button variant="outline" onClick={()=>setEdit(!edit)}>{edit?'Close editor':row.status==='draft'?'Edit draft':'Prepare next edition'}</Button>}{overview.canManage&&row.status==='published'&&row.active&&<Button onClick={()=>setAssign(!assign)}>{assign?'Close assignment form':'Assign to employees'}</Button>}</div></Section>
    {edit&&<Section title={row.status==='draft'?'Revise draft':'Prepare next edition'}><ContentForm key={row.id+':'+row.version} edition={row} newEdition={row.status==='published'} done={saved=>{setEdit(false);select(saved.id);}}/></Section>}
    {overview.canPublish&&row.status==='draft'&&row.active&&<Section title="Publish this edition"><form className="space-y-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.mutate({url:`${base}/editions/${row.id}/publish`,body:{version:row.version,reason:text(form,'reason')}});}}><p className="text-sm text-muted-foreground">Publishing makes this edition immutable. Employees will see it in the library from its effective date. Assignment is a separate step.</p><Note label="Publication note"/><Button disabled={mutation.isPending}>Publish edition {row.edition_number}</Button></form></Section>}
    {assign&&<Section title={'Assign edition '+row.edition_number}><AssignForm edition={row} policy={overview.policy} done={()=>setAssign(false)}/></Section>}
    {overview.canPublish&&<><Section title="Catalogue settings"><form key={row.handbook_version} className="space-y-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.mutate({url:`${base}/catalogue/${row.handbook_id}`,method:'PATCH',body:{version:row.handbook_version,category:text(form,'category'),active:form.has('active'),reason:text(form,'reason')}});}}><Input label="Category" name="category" defaultValue={row.category} required minLength={2} maxLength={80}/><Toggle name="active" label="Active handbook: allow publishing and new assignments" checked={row.active}/><p className="text-sm text-muted-foreground">Archiving removes the handbook from the active library. Existing assignments and acknowledgements remain available.</p><Note label="Reason for catalogue change"/><Button variant="outline" disabled={mutation.isPending}>Save catalogue settings</Button></form></Section><RecordHistory kind="editions" id={id}/></>}
  </div>;
}

function AssignForm({edition,policy,done}:{edition:Edition;policy:HandbookPolicy;done:()=>void}){
  const [search,setSearch]=useState(''),[selected,setSelected]=useState<Map<number,string>>(new Map()),mutation=useSave(done);
  const directory=useQuery<{id:number;name:string;department:string;type:string}[]>({queryKey:[base+'/directory',{q:search}]});
  const defaultDue=nextDate(policy.defaultDueDays)>edition.effective_on?nextDate(policy.defaultDueDays):edition.effective_on;
  return <form className="space-y-4" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.mutate({url:base+'/assignments',body:{editionId:edition.id,employeeIds:[...selected.keys()],dueDate:text(form,'dueDate'),required:form.has('required'),supersedePending:form.has('supersedePending'),reason:text(form,'reason')}});}}><Input label="Find employees" value={search} onChange={e=>setSearch(e.target.value)}/><QueryError error={directory.error}/><div className="flex flex-wrap items-center gap-3 text-sm"><strong>{selected.size} selected</strong><Button type="button" variant="outline" onClick={()=>setSelected(new Map((directory.data||[]).map(employee=>[employee.id,employee.name])))}>Select displayed employees</Button><Button type="button" variant="ghost" onClick={()=>setSelected(new Map())}>Clear selection</Button></div><div className="max-h-72 space-y-2 overflow-y-auto rounded border p-3">{directory.data?.map(employee=><label key={employee.id} className="flex items-center gap-3 rounded px-2 py-1 text-sm"><input type="checkbox" checked={selected.has(employee.id)} disabled={!selected.has(employee.id)&&selected.size>=200} onChange={event=>setSelected(current=>{const copy=new Map(current);event.target.checked?copy.set(employee.id,employee.name):copy.delete(employee.id);return copy;})}/><span>{employee.name} <span className="text-muted-foreground">· {employee.department} · {employee.type}</span></span></label>)}{directory.data&&!directory.data.length&&<p className="text-sm text-muted-foreground">No active employees match this search.</p>}</div>{selected.size>0&&<details className="text-sm"><summary className="cursor-pointer">Selected employees across searches</summary><p className="mt-2">{[...selected.values()].join(', ')}</p></details>}<p className="text-sm text-muted-foreground">The search shows up to 200 employees at a time. Reassigning the same edition preserves its existing record; a new edition creates a fresh acknowledgement.</p><Input label="Acknowledgement deadline" name="dueDate" type="date" min={today()>edition.effective_on?today():edition.effective_on} defaultValue={defaultDue} required/><Toggle name="required" label="Required acknowledgement" checked={policy.requiredByDefault}/><Toggle name="supersedePending" label="Supersede pending assignments for older editions of this handbook" checked/><p className="rounded bg-muted p-3 text-sm">Acknowledgement statement: {policy.acknowledgementText}</p><Note label="Reason for assignment"/><Button disabled={!selected.size||mutation.isPending}>Assign to {selected.size||'selected'} employees</Button></form>;
}

function Assignments({view,select}:{view:'mine'|'team';select:(id:number)=>void}){
  const [offset,setOffset]=useState(0),[status,setStatus]=useState(''),[q,setQ]=useState('');
  const query=useQuery<{items:HandbookAssignment[];hasMore:boolean}>({queryKey:[base+'/assignments',{view,status,q,offset}]});
  return <Section title={view==='mine'?'My acknowledgements':'Employee acknowledgement register'}><div className="grid gap-3 md:grid-cols-2"><Input label="Search employee or handbook" value={q} onChange={event=>{setQ(event.target.value);setOffset(0);}}/><Field label="Status"><select className={fieldClass} value={status} onChange={event=>{setStatus(event.target.value);setOffset(0);}}><option value="">All statuses</option>{['pending','overdue','acknowledged','superseded','withdrawn'].map(value=><option value={value} key={value}>{value}</option>)}</select></Field></div><QueryError error={query.error}/>{query.isLoading&&<p>Loading assignments…</p>}<Table headers={['Employee','Handbook','Deadline','Status','Acknowledged','']} rows={(query.data?.items||[]).map(row=>[row.employee_name,row.title+' · Edition '+row.edition_number,<span className={row.status==='pending'&&row.due_date<today()?'text-destructive':''}>{row.due_date}{row.required?' · Required':' · Optional'}</span>,row.status,pretty(row.acknowledged_at),<Button variant="outline" onClick={()=>select(row.id)}>Open</Button>])}/><PageControls offset={offset} hasMore={!!query.data?.hasMore} change={setOffset}/></Section>;
}

function AssignmentDetail({id}:{id:number}){
  const query=useQuery<{row:HandbookAssignment;edition:HandbookEdition;employeeName:string;canAcknowledge:boolean;hasReadReceipt:boolean;canManage:boolean}>({queryKey:[base+'/assignments/'+id]}),mutation=useSave(),[confirmed,setConfirmed]=useState(false);
  if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading assigned handbook…</p>}</>;
  const {row,edition,employeeName,canAcknowledge,hasReadReceipt,canManage}=query.data,effective=edition.effective_on<=today();
  return <div className="space-y-5"><Section title={edition.title}><div className="grid gap-3 text-sm sm:grid-cols-2"><p>Employee: <strong>{employeeName}</strong></p><p>Edition {edition.edition_number} · Effective {edition.effective_on}</p><p>Due {row.due_date} · {row.required?'Required':'Optional'}</p><p>Status: <strong>{row.status}</strong></p></div>{edition.summary&&<p className="whitespace-pre-wrap text-muted-foreground">{edition.summary}</p>}<article className="whitespace-pre-wrap break-words rounded border bg-background p-5 text-sm leading-7">{edition.body}</article>{row.read_at&&<p className="text-sm text-muted-foreground">Reading recorded {pretty(row.read_at)}</p>}{row.acknowledged_at&&<p className="rounded bg-muted p-4 text-sm">Acknowledged {pretty(row.acknowledged_at)} by the assigned employee. Statement: {row.policy_snapshot.acknowledgementText}</p>}{canAcknowledge&&row.status==='pending'&&<div className="space-y-4 rounded border p-4">{!effective?<p>This edition becomes available for acknowledgement on {edition.effective_on}.</p>:!hasReadReceipt?<><p className="text-sm">After reading the complete edition above, record that you have finished reading to continue.</p><Button disabled={mutation.isPending} onClick={()=>mutation.mutate({url:`${base}/assignments/${id}/read`,body:{version:row.version,bodyHash:row.body_hash}})}>I have finished reading this edition</Button></>:<><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)} className="mt-1"/><span>{row.policy_snapshot.acknowledgementText}</span></label><Button disabled={!confirmed||mutation.isPending} onClick={()=>mutation.mutate({url:`${base}/assignments/${id}/acknowledge`,body:{version:row.version,bodyHash:row.body_hash,confirmed:true}})}>Acknowledge edition {edition.edition_number}</Button></>}</div>}</Section>
    {canManage&&row.status==='pending'&&<Section title="Manage assignment"><form key={row.version} className="space-y-3" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value')||'update';mutation.mutate({url:`${base}/assignments/${id}`,method:'PATCH',body:{version:row.version,action,dueDate:text(form,'dueDate'),required:form.has('required'),reason:text(form,'reason')}});}}><Input label="Deadline" name="dueDate" type="date" defaultValue={row.due_date} required/><Toggle name="required" label="Required acknowledgement" checked={row.required}/><Note label="Reason for assignment change"/><div className="flex flex-wrap gap-2"><Button value="update" disabled={mutation.isPending}>Save deadline & requirement</Button><Button value="withdraw" variant="outline" disabled={mutation.isPending}>Withdraw assignment</Button></div></form></Section>}<RecordHistory kind="assignments" id={id}/>
  </div>;
}

function RecordHistory({kind,id}:{kind:'editions'|'assignments';id:number}){
  const [offset,setOffset]=useState(0),query=useQuery<HistoryItem[]>({queryKey:[`${base}/${kind}/${id}/history`,{offset}]});
  return <Section title={kind==='editions'?'Edition revision history':'Assignment history'}><QueryError error={query.error}/><ol className="space-y-4">{query.data?.map(item=><li key={item.version} className="space-y-1 border-b pb-3 text-sm"><p className="font-medium">Revision {item.version}{item.status?' · '+item.status:''}</p><p className="text-muted-foreground">{pretty(item.created_at)} · User #{item.actor_id}</p><p className="whitespace-pre-wrap">{item.reason}</p>{item.due_date&&<p>Deadline {item.due_date}</p>}{item.snapshot&&<details><summary className="cursor-pointer">View preserved content</summary><h3 className="mt-3 font-semibold">{item.snapshot.title}</h3><p className="whitespace-pre-wrap mt-2">{item.snapshot.body}</p></details>}</li>)}</ol><PageControls offset={offset} hasMore={query.data?.length===25} change={setOffset}/></Section>;
}

export function HandbookSettings(){
  const query=useQuery<Overview>({queryKey:[base+'/overview']});
  return <><QueryError error={query.error}/>{query.isLoading&&<p role="status">Loading handbook rules…</p>}{query.data?.canSetRules&&<Rules policy={query.data.policy}/>}</>;
}
function Rules({policy}:{policy:HandbookPolicy}){
  const mutation=useSave(),history=useQuery<{version:number;default_due_days:number;required_by_default:boolean;acknowledgement_text:string;reason:string;created_at:string}[]>({queryKey:[base+'/policy/history']}),[offset,setOffset]=useState(0);
  const historyPage=useQuery<typeof history.data>({queryKey:[base+'/policy/history',{offset}],enabled:offset>0});
  return <div className="space-y-5"><Section title="Acknowledgement rules"><form key={policy.version} className="space-y-4" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.mutate({url:base+'/policy',body:{version:policy.version,defaultDueDays:number(form,'defaultDueDays'),requiredByDefault:form.has('requiredByDefault'),acknowledgementText:text(form,'acknowledgementText'),reason:text(form,'reason')}});}}><Input label="Default acknowledgement period (days)" name="defaultDueDays" type="number" min={1} max={365} defaultValue={policy.defaultDueDays} required/><Toggle name="requiredByDefault" label="Make new assignments required by default" checked={policy.requiredByDefault}/><Field label="Employee acknowledgement statement"><textarea className={fieldClass} rows={3} name="acknowledgementText" defaultValue={policy.acknowledgementText} minLength={10} maxLength={1000} required/></Field><p className="text-sm text-muted-foreground">Assignments preserve their original statement and policy version. Only the assigned employee can acknowledge after recording that they have read that edition.</p><Note label="Reason for rule change"/><Button disabled={mutation.isPending}>Save acknowledgement rules</Button></form></Section><Section title="Rule history"><QueryError error={offset?historyPage.error:history.error}/><Table headers={['Version','Default period','Required by default','Statement','Reason','Changed']} rows={((offset?historyPage.data:history.data)||[]).map(row=>[row.version,row.default_due_days+' days',row.required_by_default?'Yes':'No',row.acknowledgement_text,row.reason,pretty(row.created_at)])}/><PageControls offset={offset} hasMore={((offset?historyPage.data:history.data)||[]).length===25} change={setOffset}/></Section></div>;
}
