import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import {Link,useLocation,useRoute} from 'wouter';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,LifeBuoy,LockKeyhole,MessageSquare,Paperclip,Plus,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardContent,CardTitle} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {apiJson} from '@/lib/queryClient';
import {caseCategories,caseStatuses,categoryLabels,statusLabels,type CaseDetail,type CaseList,type HelpdeskConfig,type CaseStatus} from '@shared/helpdesk';

const selectClass='w-full rounded-md border border-input bg-background px-3 py-2 text-sm';
const stamp=(value:string)=>new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>;}
function useHelpdeskMutation(){
  const cache=useQueryClient(),{toast}=useToast();
  const refresh=()=>cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/helpdesk/')});
  return useMutation({mutationFn:({url,body}:{url:string;body:unknown})=>apiJson<{id?:number}>(url,{method:'POST',body}),
    onSuccess:async()=>{await refresh();toast({title:'Saved'});},onError:async(error)=>{toast({title:'Unable to save',description:error.message,variant:'destructive'});if(error.message.startsWith('409:'))await refresh();}});
}
function FileField({available,onChange,resetKey}:{available:boolean;onChange:(file:File|null)=>void;resetKey:number}){
  return <Field label="Attachment (optional)"><Input key={resetKey} type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={!available} onChange={e=>onChange(e.target.files?.[0]||null)}/><span className="text-xs font-normal text-muted-foreground">{available?'One PDF, PNG or JPEG, up to 10 MB.':'Private file storage is not configured. Text requests and replies are available.'}</span></Field>;
}
export default function Helpdesk(){
  const [,navigate]=useLocation(),[,params]=useRoute('/helpdesk/:caseId');const caseId=params?Number(params.caseId):null;
  const config=useQuery<HelpdeskConfig>({queryKey:['/api/helpdesk/config']});
  const [view,setView]=useState('mine'),[status,setStatus]=useState(''),[search,setSearch]=useState(''),[term,setTerm]=useState(''),[page,setPage]=useState(1),[create,setCreate]=useState(false);
  useEffect(()=>{const timer=setTimeout(()=>{setTerm(search.trim());setPage(1);},300);return()=>clearTimeout(timer);},[search]);
  const list=useQuery<CaseList>({queryKey:['/api/helpdesk/cases',{view,status,q:term,page,limit:25}],enabled:!caseId,refetchInterval:30000});
  if(config.isLoading)return <p>Loading helpdesk…</p>;
  if(config.error||!config.data)return <p role="alert">Unable to load the HR helpdesk. Please try again.</p>;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Employee support</p><h1 className="mt-2 text-3xl font-semibold">HR helpdesk</h1><p className="mt-2 text-muted-foreground">Ask HR, track your requests and keep the conversation in one place.</p></div><Button onClick={()=>setCreate(true)}><Plus className="mr-2 h-4 w-4"/>New request</Button></div>
    {caseId?<CasePanel key={caseId} id={caseId} config={config.data}/>:<>
      <div className="grid items-end gap-3 md:grid-cols-[1fr_1fr_2fr_auto]"><Field label="View"><select className={selectClass} value={view} onChange={e=>{setView(e.target.value);setPage(1);}}><option value="mine">My requests</option>{config.data.canWorkQueue&&<option value="queue">HR queue</option>}</select></Field><Field label="Status"><select className={selectClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{caseStatuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field><Field label="Search subject"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search requests" maxLength={100}/></Field><Button variant="outline" onClick={()=>list.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
      {view==='queue'&&<p className="text-sm text-muted-foreground">This queue contains only requests you can handle. Confidential cases have a separate access check.</p>}
      {list.isLoading?<p>Loading requests…</p>:list.error?<p role="alert">Unable to load requests. Please refresh.</p>:<Card><CardContent className="py-2">{!list.data?.items.length?<div className="py-10"><LifeBuoy className="mb-3 h-8 w-8 text-primary"/><h2 className="font-semibold">No requests in this view</h2><p className="mt-2 text-muted-foreground">Create a request or adjust your filters.</p></div>:<div className="divide-y">{list.data.items.map(row=><Link key={row.id} href={`/helpdesk/${row.id}`} className="block rounded-md py-4 hover:bg-muted/40 focus-visible:outline-primary"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="mr-2 text-sm text-muted-foreground">#{row.id}</span><span className="font-semibold">{row.title}</span>{row.confidential&&<Badge variant="outline" className="ml-3"><LockKeyhole className="mr-1 h-3 w-3"/>Confidential</Badge>}</div><Badge variant={row.status==='closed'||row.status==='resolved'?'secondary':'default'}>{statusLabels[row.status]}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{categoryLabels[row.category]} · {row.requesterName} · {row.assigneeName||'Awaiting assignment'}</p><p className="mt-1 text-xs text-muted-foreground">Updated {stamp(row.updatedAt)}</p></Link>)}</div>}</CardContent></Card>}
      {list.data&&<div className="flex flex-wrap items-center justify-between gap-3 text-sm"><p>{list.data.total} request{list.data.total===1?'':'s'} · Page {page}</p><div className="flex gap-2"><Button variant="outline" disabled={page===1||list.isFetching} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page*25>=list.data.total||list.isFetching} onClick={()=>setPage(page+1)}>Next</Button></div></div>}
    </>}
    <NewCase open={create} close={()=>setCreate(false)} config={config.data} created={id=>{setCreate(false);navigate(`/helpdesk/${id}`);}}/>
  </div>;
}
function NewCase({open,close,config,created}:{open:boolean;close:()=>void;config:HelpdeskConfig;created:(id:number)=>void}){
  const [title,setTitle]=useState(''),[category,setCategory]=useState<typeof caseCategories[number]>('payroll'),[confidential,setConfidential]=useState(false),[body,setBody]=useState(''),[file,setFile]=useState<File|null>(null),[fileKey,setFileKey]=useState(0);
  const mutation=useHelpdeskMutation();
  const restricted=confidential||category==='employee_relations';
  async function submit(event:FormEvent){event.preventDefault();const data=new FormData();data.set('title',title);data.set('category',category);data.set('confidential',String(restricted));data.set('body',body);if(file)data.set('file',file);
    try{const result=await mutation.mutateAsync({url:'/api/helpdesk/cases',body:data});setTitle('');setBody('');setFile(null);setFileKey(k=>k+1);setConfidential(false);setCategory('payroll');created(result.id!);}catch{}}
  return <Dialog open={open} onOpenChange={value=>{if(!value&&!mutation.isPending)close();}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>New HR request</DialogTitle><DialogDescription>Describe what you need and HR will follow up here.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}>
    <Field label="Subject"><Input value={title} onChange={e=>setTitle(e.target.value)} minLength={4} maxLength={160} required autoFocus/></Field><Field label="Category"><select className={selectClass} value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{caseCategories.map(c=><option key={c} value={c}>{categoryLabels[c]}</option>)}</select></Field>
    <label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={restricted} disabled={category==='employee_relations'} onChange={e=>setConfidential(e.target.checked)}/>Confidential request</label>
    <p className="text-sm text-muted-foreground">{restricted?'Visible to you, HR directors/system owners and any specifically assigned HR responder. Employee relations requests are always confidential.':'Visible to you, HR triagers and any assigned HR responder. Team leads do not receive access through team membership.'}</p>
    <Field label="Details"><Textarea value={body} onChange={e=>setBody(e.target.value)} minLength={10} maxLength={10000} rows={5} required placeholder="Explain the issue and the help you need."/></Field><FileField available={config.attachmentsAvailable} onChange={setFile} resetKey={fileKey}/>
    <div className="flex justify-end gap-2"><Button variant="outline" type="button" disabled={mutation.isPending} onClick={close}>Close</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?'Submitting…':'Submit request'}</Button></div>
  </form></DialogContent></Dialog>;
}
function CasePanel({id,config}:{id:number;config:HelpdeskConfig}){
  const query=useQuery<CaseDetail>({queryKey:[`/api/helpdesk/cases/${id}`],refetchInterval:30000});
  const mutation=useHelpdeskMutation();
  const [body,setBody]=useState(''),[internal,setInternal]=useState(false),[file,setFile]=useState<File|null>(null),[fileKey,setFileKey]=useState(0),[nextStatus,setNextStatus]=useState(''),[reason,setReason]=useState('');
  if(query.isLoading)return <p>Loading request…</p>;
  if(query.error||!query.data)return <div role="alert" className="space-y-3"><p>This request is unavailable or you no longer have access.</p><Link href="/helpdesk" className="text-primary">Back to requests</Link></div>;
  const {case:row,capabilities:access,messages,events}=query.data;
  async function reply(event:FormEvent){event.preventDefault();const data=new FormData();data.set('version',String(row.version));data.set('body',body);data.set('internal',String(internal&&access.internal));if(file)data.set('file',file);
    try{await mutation.mutateAsync({url:`/api/helpdesk/cases/${id}/messages`,body:data});setBody('');setFile(null);setFileKey(k=>k+1);}catch{}}
  async function changeStatus(event:FormEvent){event.preventDefault();try{await mutation.mutateAsync({url:`/api/helpdesk/cases/${id}/actions`,body:{action:'status',version:row.version,status:nextStatus,reason}});setNextStatus('');setReason('');}catch{}}
  return <div className="space-y-5"><Link href="/helpdesk" className="inline-flex items-center text-sm text-primary"><ArrowLeft className="mr-2 h-4 w-4"/>Back to requests</Link><Card><CardContent className="pt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">Request #{row.id} · {categoryLabels[row.category]}</p><h2 className="mt-2 break-words text-2xl font-semibold">{row.title}</h2></div><div className="flex gap-2">{row.confidential&&<Badge variant="outline"><LockKeyhole className="mr-1 h-3 w-3"/>Confidential</Badge>}<Badge>{statusLabels[row.status]}</Badge></div></div><p className="mt-3 text-sm text-muted-foreground">Requested by {row.requesterName} · Handler: {row.assigneeName||'Awaiting assignment'}</p></CardContent></Card>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(260px,1fr)]"><div className="space-y-5"><Card><CardHeader><CardTitle>Conversation</CardTitle></CardHeader><CardContent className="space-y-4">{messages.map(message=><article key={message.id} className={`rounded-lg border p-4 ${message.internal?'border-amber-300 bg-amber-50/60 dark:bg-amber-950/20':''}`}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{message.authorName}{message.internal&&<Badge variant="outline" className="ml-2">Internal HR note</Badge>}</p><time className="text-xs text-muted-foreground">{stamp(message.createdAt)}</time></div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed">{message.body}</p>{message.attachments.map(a=><a key={a.id} href={`/api/helpdesk/attachments/${a.id}/download`} target="_blank" rel="noopener noreferrer" className="mt-3 flex items-center gap-2 break-all text-sm text-primary"><Paperclip className="h-4 w-4 shrink-0"/>{a.filename} ({Math.ceil(a.size/1024)} KB)</a>)}</article>)}</CardContent></Card>
      {access.reply?<Card><CardHeader><CardTitle>{internal&&access.internal?'Add internal note':'Reply'}</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={reply}>{access.internal&&<Field label="Message visibility"><select className={selectClass} value={internal?'internal':'reply'} onChange={e=>setInternal(e.target.value==='internal')}><option value="reply">Reply visible to employee</option><option value="internal">Internal HR note</option></select></Field>}<Field label={internal&&access.internal?'Internal note':'Your reply'}><Textarea value={body} onChange={e=>setBody(e.target.value)} rows={4} minLength={1} maxLength={10000} required/></Field><FileField available={config.attachmentsAvailable} onChange={setFile} resetKey={fileKey}/><Button type="submit" disabled={mutation.isPending}><MessageSquare className="mr-2 h-4 w-4"/>{mutation.isPending?'Saving…':internal&&access.internal?'Save internal note':'Send reply'}</Button></form></CardContent></Card>:<p className="rounded-md bg-muted p-4 text-sm">This request is {statusLabels[row.status].toLowerCase()}. Reopen it to continue the conversation.</p>}
    </div><div className="space-y-5">
      {access.assign&&row.status!=='closed'&&<AssignmentPanel id={id} version={row.version} current={row.assigneeId}/>}
      {!!access.statuses.length&&<Card><CardHeader><CardTitle>Update status</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={changeStatus}><Field label="New status"><select className={selectClass} value={access.statuses.includes(nextStatus as CaseStatus)?nextStatus:''} onChange={e=>setNextStatus(e.target.value)} required><option value="">Choose status…</option>{access.statuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></Field><Field label="Reason visible to employee"><Textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={1000} required/></Field><Button type="submit" disabled={mutation.isPending}>Update status</Button></form></CardContent></Card>}
      {access.restrict&&<Card><CardHeader><CardTitle>Privacy</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Restrict this case to you, HR directors/system owners and its assigned HR handler. The existing handler keeps access. This screen cannot make a confidential case public again.</p><Button variant="outline" disabled={mutation.isPending} onClick={()=>mutation.mutate({url:`/api/helpdesk/cases/${id}/actions`,body:{action:'restrict',version:row.version}})}><LockKeyhole className="mr-2 h-4 w-4"/>Make confidential</Button></CardContent></Card>}
      <Card><CardHeader><CardTitle>Case history</CardTitle></CardHeader><CardContent className="space-y-4">{events.map(event=><div key={event.id} className="border-l-2 pl-3"><p className="whitespace-pre-wrap break-words text-sm">{event.details}</p><p className="mt-1 text-xs text-muted-foreground">{event.actorName} · {stamp(event.createdAt)}</p></div>)}</CardContent></Card>
    </div></div>
  </div>;
}
function AssignmentPanel({id,version,current}:{id:number;version:number;current:number|null}){
  const [search,setSearch]=useState(''),[term,setTerm]=useState(''),[assignee,setAssignee]=useState('');const mutation=useHelpdeskMutation();
  useEffect(()=>{const timer=setTimeout(()=>setTerm(search.trim()),300);return()=>clearTimeout(timer);},[search]);
  const people=useQuery<{id:number;name:string;role:string}[]>({queryKey:[`/api/helpdesk/cases/${id}/assignees`,{q:term}],enabled:term.length>=2});
  return <Card><CardHeader><CardTitle>Assign HR handler</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/helpdesk/cases/${id}/actions`,body:{action:'assign',version,assigneeId:Number(assignee)}});setAssignee('');setSearch('');}catch{}}}><Field label="Find HR responder"><Input value={search} onChange={e=>{setSearch(e.target.value);setAssignee('');}} placeholder="Enter at least 2 characters"/></Field>{people.error?<p role="alert" className="text-sm">Unable to search case handlers.</p>:term.length>=2&&<Field label="Select HR handler"><select className={selectClass} value={assignee} onChange={e=>setAssignee(e.target.value)} required><option value="">Choose responder…</option>{people.data?.map(p=><option key={p.id} value={p.id}>{p.name} · {p.role.replaceAll('_',' ')}</option>)}</select></Field>}<div className="flex flex-wrap gap-2"><Button type="submit" disabled={mutation.isPending||!assignee}>Assign</Button>{current&&<Button type="button" variant="outline" disabled={mutation.isPending} onClick={()=>mutation.mutate({url:`/api/helpdesk/cases/${id}/actions`,body:{action:'assign',version,assigneeId:null}})}>Unassign</Button>}</div><p className="text-xs text-muted-foreground">Assignment grants this responder access to the case and its internal HR notes.</p></form></CardContent></Card>;
}
