import {CandidateCorrections} from '@/components/recruitment/CandidateCorrections';
import {useAuth} from '@/contexts/AuthContext';
import {getAccessScope,hasPermission} from '@shared/permissions';
import { useState } from 'react';
import Interviews from '@/components/hr/Interviews';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, fieldClass, useAction, QueryError } from '@/components/hr/Operations';
import EmployeeForm from '@/components/employee/EmployeeForm';
import { apiJson } from '@/lib/queryClient';
const transitionJobs: Record<string, string[]> = { draft: ['pending_approval', 'cancelled'], pending_approval: ['approved', 'cancelled'], approved: ['open', 'cancelled'], open: ['on_hold', 'closed', 'cancelled'], on_hold: ['open', 'closed', 'cancelled'] };
const transitionApps: Record<string, string[]> = { new: ['screening', 'rejected'], screening: ['shortlisted', 'rejected'], shortlisted: ['interview', 'rejected'], interview: ['rejected'] };
export default function Hiring() {
    const [candidateId,setCandidateId]=useState<number|null>(null),{user}=useAuth();const candidateAccess=!!user&&hasPermission(user.role,'recruitment_onboarding','read')&&getAccessScope(user.role,'recruitment_onboarding')==='all';
    const cache = useQueryClient(), [modal, setModal] = useState(''), [form, setForm] = useState<any>({}), [decision, setDecision] = useState<any>(null), [note, setNote] = useState(''), [handoff, setHandoff] = useState<any>(null), [templateId, setTemplate] = useState(''), [ownerId, setOwner] = useState('');
    const data = useQuery<any>({ queryKey: ['/api/hiring'] }), templates = useQuery<any[]>({ queryKey: ['/api/lifecycle/templates'], enabled: !!data.data?.canHandoff }), options = useQuery<any>({ queryKey: ['/api/lifecycle/options'], enabled: !!data.data?.canHandoff });
    const action = useAction(() => { setModal(''); setDecision(null); });
    const input = (key: string, label: string, type = 'text') => <Field key={key} label={label}><input className={fieldClass} type={type} required value={form[key] ?? ''} onChange={e => setForm({ ...form, [key]: type === 'number' ? Number(e.target.value) : e.target.value })}/></Field>;
    const decide = (url: string, version: number, status: string) => { setDecision({ url, version, status }); setNote(''); };
    return <div className="space-y-6"><div className="flex flex-wrap justify-between"><h1 className="text-2xl font-bold">Recruitment</h1><a className="underline text-primary" href="/onboarding">Manage onboarding and offboarding checklists</a></div>{candidateId&&<CandidateCorrections key={candidateId} isOpen onClose={()=>setCandidateId(null)} candidateId={candidateId}/>}<QueryError error={data.error}/>{data.data?.canCreate && <div className="flex gap-3"><Button onClick={() => { setModal('job'); setForm({ positionType: 'permanent', numberOfVacancies: 1 }); }}>New requisition</Button><Button variant="outline" onClick={() => { setModal('application'); setForm({ source: 'other' }); }}>Add candidate application</Button></div>}
 {modal && <Section title={modal === 'job' ? 'New job requisition' : modal === 'application' ? 'Candidate application' : 'Issue offer'}><form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ url: '/api/hiring/' + (modal === 'job' ? 'jobs' : modal === 'application' ? 'applications' : 'offers'), body: form }); }}><div className="grid gap-4 md:grid-cols-2">{modal === 'job' ? <>{input('jobTitle', 'Job title')}{input('department', 'Department')}{input('location', 'Location')}{input('numberOfVacancies', 'Vacancies', 'number')}<Field label="Employment type"><select className={fieldClass} value={form.positionType} onChange={e => setForm({ ...form, positionType: e.target.value })}>{['permanent', 'temporary', 'contract'].map(t => <option key={t}>{t}</option>)}</select></Field>{['jobDescription', 'qualifications', 'responsibilities', 'requiredSkills'].map(k => <Field label={k.replace(/([A-Z])/g, ' $1')} key={k}><textarea className={fieldClass} required minLength={5} value={form[k] || ''} onChange={e => setForm({ ...form, [k]: e.target.value })}/></Field>)}</> : modal === 'application' ? <><Field label="Open requisition"><select className={fieldClass} required value={form.requisitionId || ''} onChange={e => setForm({ ...form, requisitionId: Number(e.target.value) })}><option value="">Select job</option>{data.data?.jobs.filter((j: any) => j.status === 'open').map((j: any) => <option key={j.id} value={j.id}>{j.jobTitle} · {j.department}</option>)}</select></Field>{input('fullNameEn', 'Full name')}{input('email', 'Email', 'email')}{input('phone', 'Phone')}<Field label="Source"><select className={fieldClass} value={form.source} onChange={e => setForm({ ...form, source: e.target.value })}>{['job_board', 'company_website', 'referral', 'internal', 'linkedin', 'social_media', 'other'].map(s => <option key={s}>{s}</option>)}</select></Field></> : <>{input('salary', 'Offered basic salary (whole currency units)', 'number')}{input('currency', 'Currency code')}{input('startDate', 'Joining date', 'date')}{input('expiryDate', 'Acceptance deadline', 'date')}{input('reason', 'Offer approval note')}</>}</div><Button disabled={action.isPending}>Save</Button> <Button type="button" variant="outline" onClick={() => setModal('')}>Close</Button></form></Section>}
 <Section title="Requisitions"><Table headers={['Job', 'Department', 'Vacancies', 'Status', 'Actions']} rows={(data.data?.jobs || []).map((j: any) => [j.jobTitle, j.department, j.numberOfVacancies, j.status, <div className="flex flex-wrap gap-2">{(transitionJobs[j.status] || []).map(s => <Button key={s} variant="outline" onClick={() => decide(`/api/hiring/jobs/${j.id}/action`, j.version, s)}>{s.replaceAll('_', ' ')}</Button>)}</div>])}/></Section>
 <Section title="Candidates and applications"><Table headers={['Candidate', 'Contact', 'Job', 'Stage', 'Notes', 'Actions']} rows={(data.data?.applications || []).map((a: any) => [<div>{a.candidate.fullNameEn}{candidateAccess&&<Button variant="link" onClick={()=>setCandidateId(a.candidate.id)}>View candidate</Button>}</div>, a.candidate.email + ' · ' + a.candidate.phone, a.jobTitle, a.application.status, a.application.screeningNotes || '—', <div className="flex flex-wrap gap-2">{(transitionApps[a.application.status] || []).map(s => <Button key={s} variant="outline" onClick={() => decide(`/api/hiring/applications/${a.application.id}/action`, a.application.version, s)}>{s}</Button>)}{['shortlisted', 'interview'].includes(a.application.status) && data.data?.canApprove && <Button onClick={() => { setModal('offer'); setForm({ applicationId: a.application.id, version: a.application.version, currency: 'QAR' }); }}>Issue offer</Button>}</div>])}/></Section>
 <Interviews applications={data.data?.applications || []}/><Section title="Offers and employee handoff"><Table headers={['Candidate', 'Job', 'Joining', 'Offer', 'Status', 'Actions']} rows={(data.data?.offers || []).map((o: any) => [o.candidateName, o.jobTitle, o.offer.startDate, `${o.offer.currency} ${o.offer.salary}`, o.offer.status, <div className="flex flex-wrap gap-2">{o.offer.status === 'pending' && ['accepted', 'declined', 'expired'].map(s => <Button key={s} variant="outline" onClick={() => decide(`/api/hiring/offers/${o.offer.id}/action`, o.offer.version, s)}>{s}</Button>)}{o.employeeId ? <span>Employee #{o.employeeId}</span> : o.offer.status === 'accepted' && data.data?.canHandoff && <Button onClick={() => { setHandoff(o); setTemplate(''); setOwner(''); setNote(''); }}>Create employee and onboard</Button>}</div>])}/></Section>
 {decision && <Section title="Record decision"><form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ url: decision.url, body: { version: decision.version, status: decision.status, reason: note } }); }}><p>New status: {decision.status.replaceAll('_', ' ')}</p><Field label="Reason or candidate response evidence"><textarea className={fieldClass} minLength={5} required value={note} onChange={e => setNote(e.target.value)}/></Field><Button disabled={action.isPending}>Save decision</Button> <Button variant="outline" type="button" onClick={() => setDecision(null)}>Close</Button></form></Section>}
 {handoff && <Section title={'Create employee for ' + handoff.candidateName}><QueryError error={templates.error || options.error}/><p className="text-sm">Confirm the candidate's legal name and required personal details. Department, employment type and joining date must match the accepted offer. Accounts are linked separately in User Management.</p><div className="grid gap-3 md:grid-cols-3"><Field label="Onboarding template"><select className={fieldClass} required value={templateId} onChange={e => setTemplate(e.target.value)}><option value="">Select checklist</option>{templates.data?.filter(t => t.kind === 'onboarding').map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Initial task owner"><select className={fieldClass} required value={ownerId} onChange={e => setOwner(e.target.value)}><option value="">Select owner</option>{options.data?.owners.map((o: any) => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Handoff reason"><input className={fieldClass} minLength={5} value={note} onChange={e => setNote(e.target.value)}/></Field></div><EmployeeForm key={handoff.offer.id} initialValues={(() => { const a = data.data.applications.find((a: any) => a.application.id === handoff.offer.applicationId), job = data.data.jobs.find((j: any) => j.id === a?.application.requisitionId); return { department: job?.department, position: job?.jobTitle, location: job?.location, type: job?.positionType, joiningDate: handoff.offer.startDate, personalEmail: a?.candidate.email, primaryMobile: a?.candidate.phone }; })()} submit={async (employee) => { await apiJson(`/api/hiring/offers/${handoff.offer.id}/handoff`, { method: 'POST', body: { version: handoff.offer.version, employee, templateId: Number(templateId), ownerId: Number(ownerId), reason: note } }); await cache.invalidateQueries(); }} onSuccess={() => setHandoff(null)} onCancel={() => setHandoff(null)}/></Section>}</div>;
}
