import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Field, Section, Table, QueryError, fieldClass } from '@/components/hr/Operations';
import { apiJson } from '@/lib/queryClient';
import { letterFields, letterStatuses, letterDefinition, type LetterDefinition, type LetterTemplate, type LetterRequest, type LetterDetail } from '@shared/hr-letters';

const base = '/api/hr-letters';
type Employee = { id: number; name: string; reference: string; department: string; type: string };
type TemplateOption = { id: number; name?: string; description?: string; employeeTypes?: string[]; definition?: LetterDefinition; revision: number };
const label = (value: string) => value.replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());
function useSave(done?: (data: any) => void) {
  const cache = useQueryClient();
  return useMutation({ mutationFn: ({ url, body, method = 'POST' }: { url: string; body: unknown; method?: string }) => apiJson(url, { method, body }), onSuccess: data => { void cache.invalidateQueries({ queryKey: [base] }); void cache.invalidateQueries({ predicate: query => String(query.queryKey[0]).startsWith(base) }); done?.(data); } });
}
function Pager({ offset, more, change }: { offset: number; more: boolean; change: (value: number) => void }) {
  return <div className="flex gap-2"><Button type="button" variant="outline" disabled={!offset} onClick={() => change(Math.max(0, offset - 25))}>Previous</Button><Button type="button" variant="outline" disabled={!more} onClick={() => change(offset + 25)}>Next</Button></div>;
}
const starters: { label: string; code: string; definition: LetterDefinition }[] = [
  { label: 'Employment confirmation', code: 'employment-confirmation', definition: { name: 'Employment confirmation', description: 'Confirm the employee’s recorded position and joining date.', title: 'Employment confirmation — {{employee_name}}', body: 'This letter confirms that {{employee_name}} (employee reference {{employee_id}}) is employed by {{company_name}} as {{position}} in {{department}}.\n\nJoining date: {{joining_date}}\nEmployment type: {{employment_type}}\n\nThis letter is addressed to {{recipient}} for the following purpose: {{purpose}}.', signatoryTitle: 'Human Resources', employeeTypes: ['permanent', 'temporary', 'contract'] } },
  { label: 'Compensation statement', code: 'compensation-statement', definition: { name: 'Compensation statement', description: 'Confirm the recorded compensation package and separate payment frequencies.', title: 'Compensation statement — {{employee_name}}', body: '{{employee_name}} ({{employee_id}}) is employed by {{company_name}} as {{position}}.\n\nThe compensation package effective from {{compensation_effective_date}} records:\n{{compensation_breakdown}}\n\nMonthly cash components: {{monthly_cash_total}}. Other payment frequencies and provided benefits are listed separately above.\n\nPurpose: {{purpose}}.', signatoryTitle: 'Human Resources', employeeTypes: ['permanent', 'temporary', 'contract'] } },
  { label: 'General HR letter', code: 'general-hr-letter', definition: { name: 'General HR letter', description: 'Editable starting point for a company-approved HR letter.', title: 'Employee confirmation — {{employee_name}}', body: 'Employee: {{employee_name}}\nEmployee reference: {{employee_id}}\nPosition: {{position}}\nDepartment: {{department}}\n\nPurpose of this letter: {{purpose}}.', signatoryTitle: 'Human Resources', employeeTypes: ['permanent', 'temporary', 'contract'] } },
];

function TemplateEditor({ row, close }: { row?: LetterTemplate; close: () => void }) {
  const [definition, setDefinition] = useState<LetterDefinition>(row?.definition || structuredClone(starters[0].definition));
  const [code, setCode] = useState(row?.code || starters[0].code), [reason, setReason] = useState(''), [error, setError] = useState('');
  const save = useSave(close);
  const readOnly = !!row && row.status !== 'draft';
  function submit(event: React.FormEvent) {
    event.preventDefault(); const parsed = letterDefinition.safeParse(definition);
    if (!parsed.success) { setError(parsed.error.issues.map(issue => issue.message).join('; ')); return; }
    setError(''); save.mutate({ url: base + '/templates' + (row ? '/' + row.id : ''), method: row ? 'PATCH' : 'POST', body: { ...(row ? { version: row.version } : { code }), definition: parsed.data, reason } });
  }
  return <Section title={row ? `${row.definition.name} · Revision ${row.revision}` : 'Create a letter template'}>
    {!row && <Field label="Starting point"><select className={fieldClass} onChange={event => { const starter = starters[Number(event.target.value)]; setDefinition(structuredClone(starter.definition)); setCode(starter.code); }}>{starters.map((starter, i) => <option key={starter.code} value={i}>{starter.label}</option>)}</select></Field>}
    <p className="text-sm text-muted-foreground">These starting points are drafts for your company’s review. Publishing makes a template available for employee requests.</p>
    <form className="space-y-4" onSubmit={submit}>
      <fieldset disabled={readOnly || save.isPending} className="space-y-4">
        <div className="grid gap-4 md:grid-cols-2"><Field label="Stable template code"><input className={fieldClass} value={code} disabled={!!row} required pattern="[a-z][a-z0-9_-]{2,59}" onChange={event => setCode(event.target.value)}/></Field><Field label="Template name"><input className={fieldClass} value={definition.name} required minLength={3} maxLength={150} onChange={event => setDefinition({ ...definition, name: event.target.value })}/></Field></div>
        <Field label="Employee description"><input className={fieldClass} value={definition.description} maxLength={1000} onChange={event => setDefinition({ ...definition, description: event.target.value })}/></Field>
        <Field label="Letter title"><input className={fieldClass} value={definition.title} required minLength={3} maxLength={200} onChange={event => setDefinition({ ...definition, title: event.target.value })}/></Field>
        <Field label="Letter body — plain text with supported placeholders"><textarea className={fieldClass + ' min-h-64 font-mono'} value={definition.body} required minLength={3} maxLength={16000} onChange={event => setDefinition({ ...definition, body: event.target.value })}/></Field>
        <Field label="Printed approval title"><input className={fieldClass} value={definition.signatoryTitle} required minLength={2} maxLength={150} onChange={event => setDefinition({ ...definition, signatoryTitle: event.target.value })}/></Field>
        <fieldset><legend className="mb-2 text-sm font-medium">Eligible employee types</legend><div className="flex flex-wrap gap-4">{(['permanent', 'temporary', 'contract'] as const).map(type => <label className="flex items-center gap-2 text-sm" key={type}><input type="checkbox" checked={definition.employeeTypes.includes(type)} onChange={event => setDefinition({ ...definition, employeeTypes: event.target.checked ? [...definition.employeeTypes, type] : definition.employeeTypes.filter(value => value !== type) })}/>{label(type)}</label>)}</div></fieldset>
      </fieldset>
      <details className="rounded border p-3 text-sm"><summary className="cursor-pointer font-medium">Supported placeholders</summary><div className="mt-3 grid gap-2 md:grid-cols-2">{Object.entries(letterFields).map(([field, name]) => <p key={field}><code>{'{{' + field + '}}'}</code> — {name}</p>)}</div><p className="mt-3">Compensation fields require an effective package. Annual benefits and per-event pay are not converted into monthly salary. Per-event means one assigned shift.</p></details>
      <Field label="Reason for this template action"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={reason} onChange={event => setReason(event.target.value)}/></Field>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<QueryError error={save.error}/>
      <div className="flex flex-wrap gap-2">{!readOnly && <Button disabled={save.isPending || !definition.employeeTypes.length}>Save draft</Button>}
        {row && (row.status === 'draft' ? ['publish', 'archive'] : row.status === 'published' ? ['revise', 'archive'] : ['revise']).map(action => <Button type="button" variant="outline" key={action} disabled={save.isPending || reason.trim().length < 5 || row.status === 'draft' && JSON.stringify(definition) !== JSON.stringify(row.definition)} onClick={() => save.mutate({ url: `${base}/templates/${row.id}/${action}`, body: { version: row.version, reason } })}>{action === 'revise' ? 'Create new draft revision' : action === 'archive' ? 'Archive template and all revisions' : label(action)}</Button>)}
        <Button type="button" variant="outline" disabled={save.isPending} onClick={close}>Close</Button></div>
      {row?.status === 'draft' && <p className="text-xs text-muted-foreground">Save any edits before publishing. A published revision stays unchanged in existing letters.</p>}
      {row && <p className="text-xs text-muted-foreground">Archiving the latest revision retires the entire template. Issued letters stay unchanged; open requests need a published replacement.</p>}
    </form>
  </Section>;
}
function Templates() {
  const [offset, setOffset] = useState(0), [q, setQ] = useState(''), [selected, setSelected] = useState<LetterTemplate | null | undefined>(undefined);
  const query = useQuery<{ items: LetterTemplate[]; hasMore: boolean }>({ queryKey: [base + '/templates', { all: 'true', offset, q }] });
  return <div className="space-y-4"><Section title="Company letter templates"><p className="text-sm">Create, publish, revise or archive company templates. HR prepares and independently reviews each employee letter before it is issued.</p><div className="flex flex-wrap gap-3"><input aria-label="Find letter templates" className={fieldClass + ' max-w-sm'} placeholder="Find templates" value={q} maxLength={100} onChange={event => { setQ(event.target.value); setOffset(0); }}/><Button disabled={selected !== undefined} onClick={() => setSelected(null)}>New template</Button></div><QueryError error={query.error}/>{query.isLoading && <p role="status">Loading templates…</p>}<Table headers={['Template', 'Revision', 'State', 'Action']} rows={(query.data?.items || []).map(row => [<>{row.definition.name}<p className="text-xs text-muted-foreground">{row.code}</p></>, row.revision, <Badge variant="outline">{label(row.status)}</Badge>, <Button variant="outline" onClick={() => setSelected(row)}>Open</Button>])}/><Pager offset={offset} more={!!query.data?.hasMore} change={setOffset}/></Section>{selected !== undefined && <TemplateEditor key={selected ? `${selected.id}-${selected.version}` : 'new'} row={selected || undefined} close={() => setSelected(undefined)}/>}</div>;
}

function RequestEditor({ row, done }: { row?: LetterRequest; done: (id: number) => void }) {
  const [employeeId, setEmployeeId] = useState(row ? String(row.employee_id) : ''), [employeeSearch, setEmployeeSearch] = useState(''), [employeeOffset, setEmployeeOffset] = useState(0);
  const [templateId, setTemplateId] = useState(row ? String(row.template_id) : ''), [templateSearch, setTemplateSearch] = useState(''), [templateOffset, setTemplateOffset] = useState(0);
  const [recipient, setRecipient] = useState(row?.recipient || ''), [purpose, setPurpose] = useState(row?.purpose || ''), [submissionKey] = useState(() => crypto.randomUUID());
  const staff = useQuery<{ items: Employee[]; hasMore: boolean }>({ queryKey: [base + '/employees', { q: employeeSearch, offset: employeeOffset }], enabled: !row });
  const templates = useQuery<{ items: TemplateOption[]; hasMore: boolean }>({ queryKey: [base + '/templates', { q: templateSearch, offset: templateOffset }] });
  const save = useSave(data => done(data.id));
  return <form className="space-y-4 rounded-lg border p-4" onSubmit={event => { event.preventDefault(); save.mutate({ url: base + '/requests' + (row ? '/' + row.id : ''), method: row ? 'PATCH' : 'POST', body: { ...(row ? { version: row.version } : { employeeId: Number(employeeId), submissionKey }), templateId: Number(templateId), recipient, purpose } }); }}>
    <h3 className="font-semibold">{row ? 'Correct and resubmit request' : 'Request an HR letter'}</h3>
    {row ? <p className="text-sm">Employee: {row.employee_name}</p> : <><Field label="Find employee by name or reference"><input className={fieldClass} value={employeeSearch} maxLength={100} onChange={event => { setEmployeeSearch(event.target.value); setEmployeeOffset(0); setEmployeeId(''); }}/></Field><Field label="Employee"><select className={fieldClass} required value={employeeId} onChange={event => setEmployeeId(event.target.value)}><option value="">Select employee</option>{staff.data?.items.map(employee => <option key={employee.id} value={employee.id}>{employee.name} · {employee.reference} · {employee.type}</option>)}</select></Field><QueryError error={staff.error}/>{staff.data?.items.length === 0 && <p className="text-sm text-muted-foreground">No available employee records. HR must create your record and link your account before you can request a letter.</p>}<Pager offset={employeeOffset} more={!!staff.data?.hasMore} change={value => { setEmployeeOffset(value); setEmployeeId(''); }}/></>}
    <Field label="Find published template"><input className={fieldClass} value={templateSearch} maxLength={100} onChange={event => { setTemplateSearch(event.target.value); setTemplateOffset(0); setTemplateId(''); }}/></Field>
    <Field label="Letter template"><select className={fieldClass} required value={templateId} onChange={event => setTemplateId(event.target.value)}><option value="">Select published template</option>{row && !templates.data?.items.some(template => template.id === row.template_id) && <option value={row.template_id}>{row.template_name} · Current request template</option>}{templates.data?.items.map(template => <option key={template.id} value={template.id}>{template.definition?.name || template.name} · Revision {template.revision}</option>)}</select></Field><QueryError error={templates.error}/>{templates.data?.items.length === 0 && <p className="text-sm text-muted-foreground">No matching published templates. An administrator can prepare and publish one in the Templates tab.</p>}<Pager offset={templateOffset} more={!!templates.data?.hasMore} change={value => { setTemplateOffset(value); setTemplateId(''); }}/>
    <Field label="Address the letter to"><input className={fieldClass} value={recipient} required minLength={2} maxLength={250} placeholder="Recipient or organization" onChange={event => setRecipient(event.target.value)}/></Field>
    <Field label="Purpose and instructions"><textarea className={fieldClass} value={purpose} required minLength={5} maxLength={2000} onChange={event => setPurpose(event.target.value)}/></Field>
    <QueryError error={save.error}/><Button disabled={save.isPending || !employeeId || !templateId}>{row ? 'Resubmit corrected request' : 'Submit letter request'}</Button>
  </form>;
}

function RequestDetail({ id, close }: { id: number; close: () => void }) {
  const query = useQuery<LetterDetail>({ queryKey: [base + '/requests/' + id] });
  return <Section title="Letter request"><div className="flex justify-end"><Button variant="outline" onClick={close}>Close request</Button></div><QueryError error={query.error}/>{query.isLoading && <p role="status">Loading request…</p>}{query.data && <RequestContents key={query.data.row.version} detail={query.data}/>}</Section>;
}
function RequestContents({ detail }: { detail: LetterDetail }) {
  const { row, actions, history } = detail, [action, setAction] = useState(''), [reason, setReason] = useState(''), [confirmed, setConfirmed] = useState(false), save = useSave();
  const actionLabels: Record<string, string> = { prepare: row.snapshot ? 'Prepare a fresh review copy' : 'Prepare review copy', issue: 'Approve and issue letter', return: 'Return for correction', reject: 'Reject request', cancel: 'Cancel request', revoke: 'Revoke issued letter' };
  return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{row.reference} · {row.employee_name}</h3><p className="text-sm">{row.template_name}</p></div><Badge variant="outline">{label(row.status)}</Badge></div><p className="text-sm whitespace-pre-wrap">Recipient: {row.recipient}<br/>Purpose: {row.purpose}</p>
    {row.snapshot && <article className="space-y-4 rounded-lg border bg-background p-5"><p className="font-semibold text-sm">{row.status === 'issued' ? 'Issued letter' : row.status === 'revoked' ? 'Revoked letter — no longer valid' : 'Prepared copy — not issued'} · {row.snapshot.date}</p><h3 className="text-xl font-semibold">{row.snapshot.title}</h3><p className="whitespace-pre-wrap text-sm break-words">{row.snapshot.body}</p><p className="text-xs text-muted-foreground">Company: {row.snapshot.companyName}<br/>Approval title: {row.snapshot.signatoryTitle}{row.issued_by_name && <><br/>Issued by {row.issued_by_name}</>}{row.snapshot.compensationVersion !== null && <><br/>Compensation revision {row.snapshot.compensationVersion}</>}</p></article>}
    {row.status === 'issued' && <div className="space-y-2"><a className="inline-flex rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground" href={`${base}/requests/${row.id}/print`} target="_blank" rel="noreferrer">Open printable letter</a><p className="text-xs text-muted-foreground">Use your browser’s Print / Save as PDF. Internal approval is recorded; this does not add an external electronic signature.</p></div>}
    {actions.correct && <RequestEditor row={row} done={() => {}}/>}
    {Object.entries(actions).some(([key, allowed]) => key !== 'correct' && allowed) && <form className="space-y-3 rounded border p-4" onSubmit={event => { event.preventDefault(); save.mutate({ url: `${base}/requests/${row.id}/${action}`, body: { version: row.version, reason, ...(['issue', 'revoke'].includes(action) ? { confirmed } : {}) } }); }}><Field label="Next action"><select className={fieldClass} required value={action} onChange={event => { setAction(event.target.value); setConfirmed(false); }}><option value="">Select an action</option>{Object.entries(actions).filter(([key, allowed]) => key !== 'correct' && allowed).map(([key]) => <option key={key} value={key}>{actionLabels[key]}</option>)}</select></Field><Field label="Reason / reviewer notes"><textarea className={fieldClass} value={reason} required minLength={5} maxLength={2000} onChange={event => setReason(event.target.value)}/></Field>{['issue', 'revoke'].includes(action) && <label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" required checked={confirmed} onChange={event => setConfirmed(event.target.checked)}/>{action === 'issue' ? 'I reviewed the prepared letter above and approve this exact copy for issue.' : 'I confirm revocation. Previously downloaded copies cannot be recalled.'}</label>}<QueryError error={save.error}/><Button disabled={save.isPending || !action}>Save action</Button></form>}
    {row.status === 'prepared' && !actions.issue && <p className="text-sm text-muted-foreground">An independent HR reviewer must issue the letter. The employee, requester and current preparer cannot approve it.</p>}
    <details className="rounded border p-3"><summary className="cursor-pointer font-medium text-sm">Latest history — up to 50 entries</summary><Table headers={['Version', 'State', 'Reason', 'Date']} rows={history.map(event => [event.version, label(event.status), event.reason, new Date(event.created_at).toLocaleString()])}/></details>
  </div>;
}

function Requests({ team = false }: { team?: boolean }) {
  const [q, setQ] = useState(''), [status, setStatus] = useState(''), [offset, setOffset] = useState(0), [selected, setSelected] = useState<number | null>(null), [create, setCreate] = useState(false);
  const query = useQuery<{ items: LetterRequest[]; hasMore: boolean }>({ queryKey: [base + '/requests', { q, status, offset, view: team ? 'team' : 'mine' }] });
  return <div className="space-y-4"><Section title={team ? 'HR preparation & approval queue' : 'My letter requests'}><div className="flex flex-wrap gap-3"><input className={fieldClass + ' max-w-sm'} aria-label="Find letter requests" value={q} maxLength={100} placeholder="Reference or employee name" onChange={event => { setQ(event.target.value); setOffset(0); }}/><select className={fieldClass + ' max-w-xs'} aria-label="Filter letter state" value={status} onChange={event => { setStatus(event.target.value); setOffset(0); }}><option value="">All states</option>{letterStatuses.map(value => <option key={value} value={value}>{label(value)}</option>)}</select><Button onClick={() => { setCreate(!create); setSelected(null); }}>{create ? 'Close form' : 'Request letter'}</Button></div><QueryError error={query.error}/>{query.isLoading && <p role="status">Loading letters…</p>}<Table headers={['Reference / employee', 'Template / recipient', 'State', 'Action']} rows={(query.data?.items || []).map(row => [<>{row.reference}<p>{row.employee_name}</p></>, <>{row.template_name}<p className="text-xs text-muted-foreground">{row.recipient}</p></>, <Badge variant="outline">{label(row.status)}</Badge>, <Button variant="outline" onClick={() => { setSelected(row.id); setCreate(false); }}>Open</Button>])}/><Pager offset={offset} more={!!query.data?.hasMore} change={setOffset}/></Section>{create && <RequestEditor done={id => { setCreate(false); setSelected(id); }}/>} {selected && <RequestDetail key={selected} id={selected} close={() => setSelected(null)}/>}</div>;
}
export default function HrLetters() {
  const context = useQuery<{ canManage: boolean; canPublish: boolean }>({ queryKey: [base + '/context'] });
  return <div className="space-y-5"><header><h1 className="text-2xl font-semibold">HR Letter Centre</h1><p className="mt-2 text-muted-foreground">Request employment and compensation letters, follow HR review, and print issued copies.</p></header><QueryError error={context.error}/>{context.isLoading && <p role="status">Loading letter permissions…</p>}{context.data && <Tabs defaultValue={context.data.canManage ? 'team' : 'mine'}><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="mine">My requests</TabsTrigger>{context.data.canManage && <TabsTrigger value="team">HR queue</TabsTrigger>}{context.data.canPublish && <TabsTrigger value="templates">Templates</TabsTrigger>}</TabsList><TabsContent value="mine"><Requests/></TabsContent>{context.data.canManage && <TabsContent value="team"><Requests team/></TabsContent>}{context.data.canPublish && <TabsContent value="templates"><Templates/></TabsContent>}</Tabs>}</div>;
}
