import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Helmet} from 'react-helmet';
import {Button} from '@/components/ui/button';
import {Field,Section,Table,QueryError,fieldClass} from '@/components/hr/Operations';
import {ActionForm,ApproverPicker,EmployeePicker,Files,History,Input,Note,Pager,Reassign,Toggle,number,text,today,useSave,type FileInfo} from '@/components/hr/EmployeeServiceUI';
import type {CourseDefinition,WorkflowEvent} from '@shared/employee-services';
import type {learningCourses,learningEnrollments} from '@shared/schema';
import InductionAcademy from '@/components/learning/InductionAcademy';
import InductionPlayer from '@/components/learning/InductionPlayer';
type Course=typeof learningCourses.$inferSelect;
type Enrollment=typeof learningEnrollments.$inferSelect;
const base='/api/learning';
export default function Learning(){
  const [section,setSection]=useState<'induction'|'records'>('induction');
  return <div className="space-y-6"><Helmet><title>Learning & Training | E3 HR</title></Helmet><nav aria-label="Learning areas" className="flex flex-wrap gap-2"><Button variant={section==='induction'?'default':'outline'} onClick={()=>setSection('induction')}>Induction & training</Button><Button variant={section==='records'?'default':'outline'} onClick={()=>setSection('records')}>Other training & approvals</Button></nav>{section==='induction'?<InductionAcademy/>:<RecordedLearning onInduction={()=>setSection('induction')}/>}</div>;
}
function RecordedLearning({onInduction}:{onInduction:()=>void}){
  const [tab,setTab]=useState('catalogue'),[page,setPage]=useState(1),[q,setQ]=useState(''),[edit,setEdit]=useState<Course|null|undefined>(),[enroll,setEnroll]=useState<Course|null>(null),[selected,setSelected]=useState<number|null>(null),[status,setStatus]=useState('');
  const courses=useQuery<{items:Course[];total:number;canManage:boolean;canOverride:boolean}>({queryKey:[base+'/courses',{page,q}]}),requests=useQuery<{items:{id:number;employeeName:string;title:string;status:string;progress:number;dueDate:string|null;expiresOn:string|null}[];total:number}>({queryKey:[base+'/enrollments',{page,status}],enabled:tab==='records'});
  return <div className="space-y-6"><Helmet><title>Learning & Training | E3 HR</title></Helmet><header className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-semibold">Learning & training</h1><p className="text-muted-foreground mt-1">Build skills, track progress and retain verified completion records.</p></div>{courses.data?.canManage&&<Button onClick={()=>setEdit(null)}>Create course</Button>}</header>
    {selected?<><Button variant="outline" onClick={()=>setSelected(null)}>Back to learning</Button><EnrollmentDetail id={selected}/></>:<><div className="flex gap-2"><Button variant={tab==='catalogue'?'default':'outline'} onClick={()=>{setTab('catalogue');setPage(1);}}>Course catalogue</Button><Button variant={tab==='records'?'default':'outline'} onClick={()=>{setTab('records');setPage(1);}}>Enrollments & approvals</Button></div>
    {edit!==undefined&&<Section title={edit?'Revise course':'New course'}><CourseForm course={edit||undefined} done={()=>setEdit(undefined)}/><Button variant="ghost" onClick={()=>setEdit(undefined)}>Close editor</Button></Section>}
    {enroll&&<Section title={'Request enrollment · '+enroll.definition.title}><EnrollmentForm course={enroll} canOverride={!!courses.data?.canOverride} done={id=>{setEnroll(null);setSelected(id);}}/><Button variant="ghost" onClick={()=>setEnroll(null)}>Cancel</Button></Section>}
    {tab==='catalogue'?<Section title="Course catalogue"><Input label="Search courses" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><QueryError error={courses.error}/>{courses.isLoading&&<p>Loading courses…</p>}<div className="grid gap-4 lg:grid-cols-2">{courses.data?.items.map(c=><article className="rounded-lg border p-5 space-y-3" key={c.id}><div className="flex justify-between gap-3"><h3 className="text-lg font-semibold">{c.definition.title}</h3><span className="text-sm text-muted-foreground">{c.definition.status}</span></div><p className="text-sm whitespace-pre-wrap">{c.definition.description}</p><p className="text-sm text-muted-foreground">{c.definition.provider} · {c.definition.format.replaceAll('_',' ')} · {c.definition.durationMinutes} minutes</p><p className="text-sm">Pass score: {c.definition.passScore}% · {c.definition.requiresEvidence?'Evidence required':'Evidence optional'} · {c.definition.capacity===null?'No place limit':c.definition.capacity+' active places'}</p>{c.definition.url&&<a className="text-primary underline text-sm" target="_blank" rel="noopener noreferrer" href={c.definition.url}>Open course link</a>}<div className="flex gap-2">{c.definition.delivery==='internal'?<Button onClick={onInduction}>Open induction academy</Button>:<>{c.definition.status==='published'&&<Button onClick={()=>setEnroll(c)}>Request enrollment</Button>}{courses.data?.canManage&&<Button variant="outline" onClick={()=>setEdit(c)}>Edit course</Button>}</>}</div></article>)}</div>{courses.data&&!courses.data.items.length&&<p className="text-sm text-muted-foreground">No courses yet. Published courses will appear here.</p>}<Pager page={page} total={courses.data?.total||0} size={20} onChange={setPage}/></Section>:<Section title="Enrollments & approvals"><Field label="Status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['requested','approved','in_progress','completion_submitted','completed','failed','withdrawn','rejected'].map(s=><option value={s} key={s}>{s.replaceAll('_',' ')}</option>)}</select></Field><QueryError error={requests.error}/>{requests.isLoading&&<p>Loading enrollments…</p>}<Table headers={['Employee','Course','Progress','Status','Due / expiry','']} rows={(requests.data?.items||[]).map(r=>[r.employeeName,r.title,`${r.progress}%`,r.status.replaceAll('_',' '),`${r.dueDate||'No deadline'}${r.expiresOn?' · Expires '+r.expiresOn:''}`,<Button variant="outline" onClick={()=>setSelected(r.id)}>Open</Button>])}/><Pager page={page} total={requests.data?.total||0} onChange={setPage}/></Section>}</>}
  </div>;
}
function CourseForm({course,done}:{course?:Course;done:()=>void}){
  const d=course?.definition,mutation=useSave(done);return <form key={course?.id||0} className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const definition:CourseDefinition={delivery:d?.delivery||'record',title:text(f,'title'),description:text(f,'description'),provider:text(f,'provider'),format:text(f,'format') as CourseDefinition['format'],url:text(f,'url'),durationMinutes:number(f,'durationMinutes'),capacity:text(f,'capacity')?number(f,'capacity'):null,passScore:number(f,'passScore'),requiresEvidence:f.has('requiresEvidence'),validMonths:text(f,'validMonths')?number(f,'validMonths'):null,approverId:number(f,'approverId'),status:text(f,'status') as CourseDefinition['status']};mutation.mutate({url:base+'/courses'+(course?'/'+course.id:''),method:course?'PATCH':'POST',body:course?{version:course.version,definition,reason:text(f,'reason')}:definition});}}>
    <div className="grid gap-3 md:grid-cols-2"><Input label="Course title" name="title" defaultValue={d?.title} required minLength={3} maxLength={200}/><Input label="Provider" name="provider" defaultValue={d?.provider} required minLength={2} maxLength={150}/></div><Note label="Description" name="description" value={d?.description}/><div className="grid gap-3 md:grid-cols-3"><Field label="Format"><select className={fieldClass} name="format" defaultValue={d?.format||'online'}>{['online','in_person','hybrid','self_paced'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></Field><Input label="Duration (minutes)" name="durationMinutes" type="number" min={1} max={100000} defaultValue={d?.durationMinutes||60} required/><Input label="Active enrollment capacity (blank = unlimited)" name="capacity" type="number" min={1} max={100000} defaultValue={d?.capacity??''}/></div><Input label="HTTPS course link (optional)" name="url" type="url" defaultValue={d?.url}/><div className="grid gap-3 md:grid-cols-2"><Input label="Passing score (%)" name="passScore" type="number" min={0} max={100} defaultValue={d?.passScore??70} required/><Input label="Certificate validity in months (blank = no expiry)" name="validMonths" type="number" min={1} max={120} defaultValue={d?.validMonths??''}/></div><Toggle name="requiresEvidence" label="Require an uploaded completion document" checked={d?.requiresEvidence??true}/><ApproverPicker base={base} value={d?.approverId}/><Field label="Publication status"><select className={fieldClass} name="status" defaultValue={d?.status||'draft'}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Field><p className="text-sm text-muted-foreground">Existing enrollments retain their saved course requirements. Archiving stops new enrollments.</p>{course&&<><Note label="Reason for revision"/><History events={course.history}/></>}<Button disabled={mutation.isPending}>Save course</Button>
  </form>;
}
function EnrollmentForm({course,canOverride,done}:{course:Course;canOverride:boolean;done:(id:number)=>void}){
  const [employee,setEmployee]=useState(''),[override,setOverride]=useState(false),mutation=useSave<{id:number}>(r=>done(r.id));return <form className="space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({url:base+'/enrollments',body:{employeeId:Number(employee),courseId:course.id,dueDate:text(f,'dueDate')||null,reason:text(f,'reason'),...(override?{override:{passScore:number(f,'passScore'),requiresEvidence:f.has('requiresEvidence'),validMonths:text(f,'validMonths')?number(f,'validMonths'):null,reason:text(f,'overrideReason')}}:{})}});}}><EmployeePicker base={base} value={employee} onChange={setEmployee}/><Input label="Due date (optional)" name="dueDate" type="date" min={today()}/><Note label="Reason for enrollment"/>{canOverride&&<><label className="flex gap-2 text-sm"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>Set employee-specific completion requirements</label>{override&&<div className="rounded border p-4 space-y-3"><Input label="Passing score (%)" name="passScore" type="number" min={0} max={100} required defaultValue={course.definition.passScore}/><Input label="Certificate validity (months; blank = no expiry)" name="validMonths" type="number" min={1} max={120} defaultValue={course.definition.validMonths??''}/><Toggle label="Completion evidence required" name="requiresEvidence" checked={course.definition.requiresEvidence}/><Note name="overrideReason" label="Reason for employee-specific requirements"/></div>}</>}<Button disabled={!employee||mutation.isPending}>Request approval</Button></form>;
}
function certificate(row:Enrollment,name:string){
  const escape=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>Completion record ${escape(row.certificateNumber)}</title><style>body{font:20px Georgia,serif;max-width:850px;margin:80px auto;padding:60px;border:3px solid #174b49;text-align:center;color:#173e3d}h1{font-size:38px}p{line-height:1.7}small{font:14px Arial,sans-serif}</style></head><body><small>E3 HR · VERIFIED LEARNING RECORD</small><h1>Certificate of completion</h1><p>This records that</p><h2>${escape(name)}</h2><p>completed</p><h2>${escape(row.courseSnapshot.title)}</h2><p>Provider: ${escape(row.courseSnapshot.provider)}<br>Verified score: ${escape(row.score)}%<br>Completed: ${escape(String(row.completedAt).slice(0,10))}<br>${row.expiresOn?'Valid until: '+escape(row.expiresOn):'No configured expiry'}</p><small>Record ${escape(row.certificateNumber)} · Verified by user #${escape(row.verifiedBy)}<br>Confirmation is retained in the employee’s private training record.</small></body></html>`;
  const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download=row.certificateNumber+'.html';a.click();URL.revokeObjectURL(url);
}
function EnrollmentDetail({id}:{id:number}){
  const query=useQuery<{row:Enrollment;employeeName:string;files:FileInfo[];canPrepare:boolean;canReview:boolean;canReassign:boolean;storage:boolean}>({queryKey:[base+'/enrollments/'+id]});if(!query.data)return <><QueryError error={query.error}/>{query.isLoading&&<p>Loading enrollment…</p>}</>;const d=query.data,r=d.row,actions:{key:string;label:string}[]=[];
  if(r.courseSnapshot.delivery==='internal')return <InductionPlayer id={id}/>;
  if(d.canPrepare&&['approved','in_progress'].includes(r.status))actions.push({key:'progress',label:'Save progress'},{key:'submit_completion',label:'Submit completion evidence'});
  if(d.canPrepare&&['requested','approved','in_progress','completion_submitted'].includes(r.status))actions.push({key:'withdraw',label:'Withdraw enrollment'});
  if(d.canReview&&r.status==='requested')actions.push({key:'approve',label:'Approve enrollment'},{key:'reject',label:'Reject'});
  if(d.canReview&&r.status==='completion_submitted')actions.push({key:'verify',label:'Verify score & complete'},{key:'return',label:'Return for more evidence'});
  return <div className="space-y-5"><Section title={r.courseSnapshot.title}><div className="grid gap-3 sm:grid-cols-2 text-sm"><p>Employee: <strong>{d.employeeName}</strong></p><p>Status: <strong>{r.status.replaceAll('_',' ')}</strong></p><p>Progress: {r.progress}% · Due: {r.dueDate||'Not set'}</p><p>Reviewer: User #{r.approverId}</p><p>Passing score: {r.courseSnapshot.passScore}% · {r.courseSnapshot.requiresEvidence?'Evidence required':'Evidence optional'}</p><p>Recorded score: {r.score??'Not verified'}</p></div>{r.courseSnapshot.url&&<a className="text-primary underline" href={r.courseSnapshot.url} target="_blank" rel="noopener noreferrer">Open course</a>}{r.status==='completed'&&<div className="rounded bg-muted p-4 space-y-2"><p>Certificate {r.certificateNumber} · {r.expiresOn?'Expires '+r.expiresOn:'No configured expiry'}</p><Button variant="outline" onClick={()=>certificate(r,d.employeeName)}>Download printable completion certificate</Button></div>}{r.completionNote&&<p className="whitespace-pre-wrap text-sm">{r.completionNote}</p>}</Section><ActionForm key={r.version} base={base+'/enrollments'} id={id} version={r.version} actions={actions} progress={d.canPrepare&&['approved','in_progress'].includes(r.status)} score={d.canReview&&r.status==='completion_submitted'}/><Files base={base+'/enrollments'} id={id} version={r.version} files={d.files} editable={d.canPrepare&&['approved','in_progress'].includes(r.status)} storage={d.storage}/>{d.canReassign&&['requested','approved','in_progress','completion_submitted'].includes(r.status)&&<Reassign base={base+'/enrollments'} directoryBase={base} id={id} version={r.version}/>}<History events={r.history}/></div>;
}
