import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Field,Section,Table,fieldClass,useAction,QueryError} from '@/components/hr/Operations';
import {LifecycleTemplates,LifecycleReviewPolicy} from '@/components/onboarding/LifecycleTemplates';
import EmployeeCompensation from '@/components/employees/EmployeeCompensation';

const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export default function Lifecycle(){
  const [selected,setSelected]=useState<number|null>(null),[employeeId,setEmployee]=useState(''),[templateId,setTemplate]=useState(''),[ownerId,setOwner]=useState(''),[startDate,setDate]=useState(today),[startReason,setStartReason]=useState('');
  const [editing,setEditing]=useState<any>(null),[review,setReview]=useState<any>(null),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[section,setSection]=useState('workflows'),[queueView,setQueueView]=useState('mine'),[queueOffset,setQueueOffset]=useState(0),[showHistory,setShowHistory]=useState(false),[historyOffset,setHistoryOffset]=useState(0);
  const options=useQuery<any>({queryKey:['/api/lifecycle/options']}),templates=useQuery<any[]>({queryKey:['/api/lifecycle/templates'],enabled:!!options.data?.canManage}),list=useQuery<any[]>({queryKey:['/api/lifecycle']}),detail=useQuery<any>({queryKey:[`/api/lifecycle/${selected}`],enabled:!!selected});
  const queue=useQuery<any>({queryKey:['/api/lifecycle/tasks/queue',{view:queueView,offset:queueOffset}]}),history=useQuery<any[]>({queryKey:[`/api/lifecycle/${selected}/history`,{offset:historyOffset}],enabled:!!selected&&showHistory});
  const action=useAction(()=>{setEditing(null);setReview(null);setNote('');setConfirmed(false);});
  const record=detail.data?.record, docs=useQuery<any[]>({queryKey:[`/api/employees/${record?.employeeId}/documents`],enabled:!!record&&!!detail.data?.canDocuments&&editing?.kind==='document'});
  const open=(id:number)=>{setSelected(id);setEditing(null);setReview(null);setNote('');setConfirmed(false);setShowHistory(false);setHistoryOffset(0);setSection('workflows');};
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Onboarding and offboarding</h1><p>Assign work, collect evidence and review completion.</p></div><QueryError error={options.error||list.error}/>
    <nav aria-label="Checklist sections" className="flex flex-wrap gap-2"><Button variant={section==='workflows'?'default':'outline'} onClick={()=>setSection('workflows')}>Workflows and tasks</Button>{options.data?.canManage&&<><Button variant={section==='templates'?'default':'outline'} onClick={()=>setSection('templates')}>Checklist templates</Button><Button variant={section==='rules'?'default':'outline'} onClick={()=>setSection('rules')}>Approval rules</Button></>}</nav>
    {section==='templates'&&<><QueryError error={templates.error}/><LifecycleTemplates templates={templates.data||[]} canEdit={!!options.data?.canTemplates}/></>}
    {section==='rules'&&<LifecycleReviewPolicy canEdit={!!options.data?.canPolicy}/>}
    {section==='workflows'&&<>
      <Section title="Task inbox"><Field label="Task queue"><select className={fieldClass} value={queueView} onChange={e=>{setQueueView(e.target.value);setQueueOffset(0);}}><option value="mine">My open tasks</option>{options.data?.canReview&&<><option value="review">Awaiting my independent review</option><option value="overdue">Overdue reviews</option></>}</select></Field><QueryError error={queue.error}/>{queue.isLoading?<p>Loading tasks…</p>:<Table headers={['Employee','Task','Owner','Task due','Review','Action']} rows={(queue.data?.items||[]).map((r:any)=>[r.employeeName,r.task.title,r.ownerName,r.task.dueDate,`${r.task.reviewState.replaceAll('_',' ')}${r.task.reviewDueDate?` · due ${r.task.reviewDueDate}`:''}`,<Button variant="outline" onClick={()=>open(r.task.caseId)}>Open task</Button>])}/>}<Button variant="outline" disabled={!queueOffset} onClick={()=>setQueueOffset(queueOffset-50)}>Previous tasks</Button> <Button variant="outline" disabled={!queue.data?.hasMore} onClick={()=>setQueueOffset(queueOffset+50)}>Next tasks</Button></Section>
      {options.data?.canManage&&<details className="rounded border p-4"><summary className="cursor-pointer font-semibold">Start a workflow</summary><form className="space-y-3 pt-4" onSubmit={e=>{e.preventDefault();const template=templates.data?.find(t=>t.id===Number(templateId));action.mutate({url:'/api/lifecycle',body:{employeeId:Number(employeeId),templateId:Number(templateId),templateVersion:template?.version,ownerId:Number(ownerId),startDate,reason:startReason}});}}><QueryError error={templates.error}/><div className="grid gap-4 md:grid-cols-2"><Field label="Employee"><select className={fieldClass} required value={employeeId} onChange={e=>setEmployee(e.target.value)}><option value="">Select employee</option>{options.data.employees.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Checklist template"><select className={fieldClass} required value={templateId} onChange={e=>setTemplate(e.target.value)}><option value="">Select template</option>{templates.data?.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.kind} · v{t.version}</option>)}</select></Field><Field label="Joining or last employment date"><input className={fieldClass} required type="date" value={startDate} onChange={e=>setDate(e.target.value)}/></Field><Field label="Initial task owner"><select className={fieldClass} required value={ownerId} onChange={e=>setOwner(e.target.value)}><option value="">Select owner</option>{options.data.owners.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></div><Field label="Reason for starting"><input className={fieldClass} required minLength={5} maxLength={2000} value={startReason} onChange={e=>setStartReason(e.target.value)}/></Field><Button disabled={action.isPending}>Start workflow</Button></form></details>}
      <Section title="Workflows">{list.isLoading?<p>Loading workflows…</p>:<Table headers={['Employee','Type','Date','Required tasks complete','Status','Action']} rows={(list.data||[]).map(r=>[r.name,r.record.kind,r.record.startDate,`${r.completed} / ${r.required}`,r.record.status,<Button variant="outline" onClick={()=>open(r.record.id)}>Open checklist</Button>])}/>}</Section>
      {selected&&<Section title="Checklist"><QueryError error={detail.error}/>{detail.isLoading&&<p>Loading checklist…</p>}{record&&<>
        <p>{detail.data.name} · {record.kind} · {record.status}{record.templateSnapshot?` · Template v${record.templateSnapshot.version||1}`:''}{record.reviewPolicySnapshot?` · Review policy v${record.reviewPolicySnapshot.version}`:''}</p>
        {Array.isArray(detail.data.induction)&&<InductionChecklist record={record} pending={detail.data.induction} canManage={detail.data.canManage}/>}
        {record.kind==='onboarding'&&<EmployeeCompensation employeeId={record.employeeId}/>}
        {detail.data.compensation&&<p className="rounded border p-3 text-sm">{detail.data.compensation.recorded?`Salary and benefits breakdown recorded for joining date · effective ${detail.data.compensation.effectiveFrom} · version ${detail.data.compensation.version}`:'Salary and benefits breakdown is required for the joining date before onboarding can be completed. Ask HR to record it in Salary and benefits.'}</p>}
        <Table headers={['Task','Owner / due','Requirement','Status / review','Evidence','Actions']} rows={detail.data.tasks.map((t:any)=>[t.title,<>{t.ownerName}<br/>{t.dueDate}</>,<>{t.required?'Required':'Optional'}{t.reviewRequired&&<p>Independent review</p>}{t.documentType&&<p>Document: {t.documentType}</p>}</>,<>{t.status}<p>{t.reviewState.replaceAll('_',' ')}</p>{t.reviewDueDate&&<p>Review due {t.reviewDueDate}</p>}{t.reviewNote&&<p>Review note: {t.reviewNote}</p>}</>,<>{t.evidence||'—'}{t.documentEvidence&&<p>{t.documentEvidence.documentType} · v{t.documentEvidence.version} · expires {t.documentEvidence.expiryDate}</p>}</>,record.status==='in_progress'?<div className="flex flex-wrap gap-2">{t.canComplete&&<Button variant="outline" onClick={()=>{setReview(null);setEditing({...t,caseVersion:record.version,status:'pending',evidence:t.evidence||'',assetTag:t.assetTag||'',documentId:t.documentId||''});}}>Update task</Button>}{t.reviewState==='pending'&&t.canReview&&<Button onClick={()=>{setEditing(null);setReview({...t,caseVersion:record.version});setNote('');}}>Review submission</Button>}</div>:null])}/>
        {editing&&<form className="space-y-3 rounded border p-4" onSubmit={e=>{e.preventDefault();action.mutate({url:`/api/lifecycle/${selected}/tasks/${editing.id}`,method:'PATCH',body:{version:editing.caseVersion,status:editing.status,evidence:editing.evidence,...(editing.kind==='document'?{documentId:editing.documentId?Number(editing.documentId):null}:{}),...(editing.kind==='asset_return'?{assetTag:editing.assetTag}:{}),...(detail.data.canManage?{ownerId:Number(editing.ownerId),dueDate:editing.dueDate}:{})}});}}>
          <h3 className="font-semibold">Update: {editing.title}</h3><p>{editing.reviewState==='pending'?'The pending submission must be withdrawn before its evidence or ownership can change.':editing.reviewRequired?'The assigned owner submits evidence. A different HR reviewer approves or returns it.':'Record completion evidence or update the task.'}</p>
          <div className="grid gap-3 md:grid-cols-3"><Field label="Task action"><select className={fieldClass} value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value})}><option value="pending">{editing.reviewState==='pending'?'Withdraw submission / reopen':'Save as pending / reopen'}</option>{editing.reviewState!=='pending'&&editing.completedAt===null&&(!editing.reviewRequired||editing.canSubmit)&&<option value="completed">{editing.reviewRequired?'Submit for review':'Complete task'}</option>}</select></Field>{detail.data.canManage&&<><Field label="Task owner"><select className={fieldClass} required value={editing.ownerId} onChange={e=>setEditing({...editing,ownerId:e.target.value})}>{options.data?.owners.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field><Field label="Task due date"><input className={fieldClass} required type="date" value={editing.dueDate} onChange={e=>setEditing({...editing,dueDate:e.target.value})}/></Field></>}</div>
          <Field label="Evidence or update reason"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={editing.evidence} onChange={e=>setEditing({...editing,evidence:e.target.value})}/></Field>
          {editing.kind==='document'&&<><QueryError error={docs.error}/>{detail.data.canDocuments?<><Field label="Collected employee document"><select className={fieldClass} value={editing.documentId} required={editing.status==='completed'} onChange={e=>setEditing({...editing,documentId:e.target.value})}><option value="">Select uploaded document</option>{docs.data?.map(d=><option key={d.id} value={d.id}>{d.documentType} · {d.documentNumber}</option>)}</select></Field><a className="text-primary underline" href="/documents">Upload or review employee documents</a></>:<p>Ask HR to attach the appropriate employee document. Only valid, current evidence can be submitted.</p>}</>}
          {editing.kind==='asset_return'&&<Field label="Returned asset identifier"><input className={fieldClass} maxLength={150} required={editing.status==='completed'} value={editing.assetTag} onChange={e=>setEditing({...editing,assetTag:e.target.value})}/></Field>}<Button disabled={action.isPending}>Save task</Button> <Button variant="outline" type="button" onClick={()=>setEditing(null)}>Close task editor</Button>
        </form>}
        {review&&<form className="space-y-3 rounded border p-4" onSubmit={e=>{e.preventDefault();action.mutate({url:`/api/lifecycle/${selected}/tasks/${review.id}/review`,body:{version:review.caseVersion,decision:'approve',reason:note}});}}><h3 className="font-semibold">Review: {review.title}</h3><p>{review.evidence}</p><Field label="Review decision reason"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field><Button disabled={action.isPending}>Approve task</Button> <Button type="button" variant="outline" disabled={action.isPending||note.trim().length<5} onClick={()=>action.mutate({url:`/api/lifecycle/${selected}/tasks/${review.id}/review`,body:{version:review.caseVersion,decision:'return',reason:note}})}>Return for correction</Button> <Button type="button" variant="outline" onClick={()=>setReview(null)}>Close review</Button></form>}
        {detail.data.canManage&&record.status==='in_progress'&&!review&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();action.mutate({url:`/api/lifecycle/${selected}/complete`,body:{version:record.version,reason:note,confirmed}});}}><Field label="Workflow decision note"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field>{detail.data.canFinish&&<><label className="block"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> {record.kind==='offboarding'?'Complete the exit checklist, mark the employee inactive and revoke their account sessions.':'I confirm the required onboarding work is complete.'}</label><Button disabled={action.isPending}>Complete {record.kind}</Button></>} <Button type="button" variant="outline" disabled={action.isPending||note.trim().length<5} onClick={()=>action.mutate({url:`/api/lifecycle/${selected}/cancel`,body:{version:record.version,reason:note}})}>Cancel workflow</Button></form>}
        <Button variant="outline" onClick={()=>setShowHistory(!showHistory)}>Workflow history</Button>{showHistory&&<><QueryError error={history.error}/><Table headers={['Record','Version','State','Reason','When']} rows={(history.data||[]).map(h=>[h.snapshot.title||record.kind,h.version,`${h.snapshot.status}${h.snapshot.reviewState?` · ${h.snapshot.reviewState}`:''}`,h.reason,new Date(h.created_at).toLocaleString()])}/><Button variant="outline" disabled={!historyOffset} onClick={()=>setHistoryOffset(historyOffset-25)}>Newer history</Button> <Button variant="outline" disabled={history.data?.length!==25} onClick={()=>setHistoryOffset(historyOffset+25)}>Older history</Button></>}
      </>}</Section>}
    </>}
  </div>;
}
function InductionChecklist({record,pending,canManage}:{record:{id:number;version:number;status:string};pending:{id:number;title:string;status:string;progress:number;dueDate:string|null}[];canManage:boolean}){
  const [reason,setReason]=useState('');const action=useAction(()=>setReason(''));
  return <div className="space-y-3 rounded border p-4"><h3 className="font-semibold">Required induction & training</h3><p className="text-sm text-muted-foreground">Published induction courses are assigned when onboarding starts. Complete the required lessons, quizzes and any completion review before closing this workflow.</p>{pending.length?<Table headers={['Course','Progress','Status','Due','']} rows={pending.map(item=>[item.title,`${item.progress}%`,item.status.replaceAll('_',' '),item.dueDate||'No deadline',<a className="text-primary underline" href={`/learning?enrollment=${item.id}`}>Open training record</a>])}/>:<p className="text-sm">No outstanding required induction assignments.</p>}{canManage&&record.status==='in_progress'&&<details><summary className="cursor-pointer text-sm font-medium">Assign newly published required induction courses</summary><form className="space-y-3 pt-3" onSubmit={event=>{event.preventDefault();action.mutate({url:`/api/lifecycle/${record.id}/induction`,body:{version:record.version,reason}});}}><p className="text-sm text-muted-foreground">Use this for workflows started before a required course was published. Existing open assignments and valid completions are retained.</p><Field label="Reason for updating induction assignments"><input className={fieldClass} required minLength={5} maxLength={2000} value={reason} onChange={event=>setReason(event.target.value)}/></Field><Button disabled={action.isPending}>Assign required induction</Button></form></details>}</div>;
}
