import { useEffect, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Building2, CalendarDays, ChevronRight, GitBranch, MapPin, Network, Pencil, Plus, RefreshCw, Search, Users, History, Layers3, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Field, fieldClass } from '@/components/hr/Operations';
import { OrgChartCanvas, chartStructure } from '@/components/hr/OrgChartCanvas';
import { OrgChartEditor, type ChartDraft } from '@/components/hr/OrgChartEditor';
import { apiJson } from '@/lib/queryClient';
import { kindLabels, type WorkforceHome, type TeamSummary } from '@shared/workforce';
import type { ChartPerson, OrgChartView, OrgPerson } from '@shared/org-chart';

const today=(timezone='Asia/Qatar')=>new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const initialScope=()=>new URLSearchParams(window.location.search).get('teamId')||'';

export default function OrgCharts(){
  const cache=useQueryClient();
  const [scope,setScope]=useState(initialScope),[date,setDate]=useState(()=>today()),[teamSearch,setTeamSearch]=useState(''),[kind,setKind]=useState('all');
  const [draft,setDraft]=useState<ChartDraft|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [teamForm,setTeamForm]=useState<{team:TeamSummary|null}|null>(null);
  const home=useQuery<WorkforceHome>({queryKey:['/api/workforce/teams']});
  const directory=useQuery<{people:OrgPerson[]}>({queryKey:['/api/org-charts/company'],enabled:!!home.data?.isAdmin});
  useEffect(()=>{if(home.data&&!scope)setScope(home.data.isAdmin?'company':String(home.data.teams[0]?.id||''));},[home.data,scope]);
  const team=home.data?.teams.find(t=>String(t.id)===scope),isCompany=scope==='company';
  const validDate=/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(Date.parse(date))&&new Date(date).toISOString().slice(0,10)===date;
  const chart=useQuery<OrgChartView>({queryKey:[`/api/org-charts/teams/${scope}`,{date}],enabled:!!team&&validDate});
  const people=directory.data?.people||[];
  const nodes=useMemo<ChartPerson[]>(()=>isCompany?(directory.data?.people||[]).map(p=>({...p,employeeId:p.id,parentEmployeeId:p.reportingManagerId,role:p.position})):chart.data?.nodes||[],[isCompany,directory.data,chart.data]);
  const graph=useMemo(()=>chartStructure(nodes),[nodes]);
  const canSee=isCompany?!!home.data?.isAdmin:!!team;
  const chartError=isCompany?directory.error:chart.error,loading=isCompany?directory.isLoading:chart.isLoading;
  const departments=new Set(nodes.map(n=>n.department).filter(Boolean)).size;
  const save=useMutation({mutationFn:({teamId,draft:body}:{teamId:string;draft:ChartDraft})=>apiJson(`/api/org-charts/teams/${teamId}`,{method:'POST',body:{...body,effectiveTo:body.effectiveTo||null}}),onSuccess:async(_,variables)=>{await cache.invalidateQueries({queryKey:[`/api/org-charts/teams/${variables.teamId}`]});setDate(variables.draft.effectiveFrom);setDraft(null);setError('');setNotice('Hierarchy revision saved. Showing its effective start date.');},onError:(e:Error)=>setError(e.message)});
  function chooseScope(value:string){setScope(value);setDraft(null);setError('');setNotice('');const selected=(cache.getQueryData<WorkforceHome>(['/api/workforce/teams'])||home.data)?.teams.find(t=>String(t.id)===value);setDate(today(selected?.timezone));const url=new URL(window.location.href);if(value==='company')url.searchParams.delete('teamId');else url.searchParams.set('teamId',value);window.history.replaceState(null,'',url.pathname+url.search);}
  function beginEdit(){if(!chart.data||!validDate)return;setDraft({version:chart.data.version,effectiveFrom:date,effectiveTo:chart.data.effectiveTo||'',nodes:chart.data.nodes.map(({employeeId,parentEmployeeId,role})=>({employeeId,parentEmployeeId,role})),reason:''});setError('');setNotice('');}
  const filteredTeams=home.data?.teams.filter(t=>(kind==='all'||t.kind===kind)&&`${t.name} ${t.siteName}`.toLowerCase().includes(teamSearch.toLowerCase()))||[];
  const refresh=()=>{home.refetch();if(isCompany)directory.refetch();else if(team&&validDate)chart.refetch();};
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-4"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Network className="h-7 w-7"/></span><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">People & reporting</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Organization charts</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">See who leads each team, follow reporting lines, and plan your next team structure.</p></div></div>{home.data?.isAdmin&&<Button disabled={!!draft} onClick={()=>setTeamForm({team:null})}><Plus className="mr-2 h-4 w-4"/>Create team</Button>}</header>
    {home.isLoading?<div role="status" className="rounded-2xl border p-8">Loading your teams...</div>:home.error?<div role="alert" className="rounded-2xl border p-6"><p>Unable to load your team access.</p><Button className="mt-3" variant="outline" onClick={()=>home.refetch()}>Try again</Button></div>:<div className="grid items-start gap-5 xl:grid-cols-[250px_minmax(0,1fr)]">
      <aside className="space-y-4 rounded-2xl border bg-card p-4 xl:sticky xl:top-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Your charts</h2><Badge variant="secondary">{(home.data?.teams.length||0)+(home.data?.isAdmin?1:0)}</Badge></div><fieldset disabled={!!draft} className="space-y-3">{home.data?.isAdmin&&<button type="button" aria-current={isCompany?'page':undefined} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${isCompany?'border-primary/30 bg-primary/10 text-primary':'hover:bg-muted/50'}`} onClick={()=>chooseScope('company')}><Building2 className="h-5 w-5 shrink-0"/><span><span className="block text-sm font-semibold">Company overview</span><span className="text-xs text-muted-foreground">Current reporting structure</span></span></button>}<div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" aria-label="Find a team or site" placeholder="Find team or site" value={teamSearch} onChange={e=>setTeamSearch(e.target.value)}/></div><select className={fieldClass} aria-label="Filter team type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All team types</option>{Object.entries(kindLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><div className="grid max-h-72 gap-2 overflow-auto sm:grid-cols-2 xl:max-h-[520px] xl:grid-cols-1">{filteredTeams.map(t=><button type="button" key={t.id} aria-current={String(t.id)===scope?'page':undefined} className={`flex items-start gap-3 rounded-xl border p-3 text-left ${String(t.id)===scope?'border-primary/30 bg-primary/10':'border-transparent hover:bg-muted/50'}`} onClick={()=>chooseScope(String(t.id))}><span className="mt-0.5 rounded-lg bg-muted p-2"><GitBranch className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-medium">{t.name}</span><span className="mt-1 block text-xs text-muted-foreground">{kindLabels[t.kind]}</span><span className="mt-1 block truncate text-xs text-muted-foreground" title={t.siteName}>{t.siteName}</span></span>{String(t.id)===scope&&<ChevronRight className="mt-2 h-4 w-4 shrink-0 text-primary"/>}</button>)}</div>{!filteredTeams.length&&<p className="py-3 text-sm text-muted-foreground">{teamSearch||kind!=='all'?'No teams match your filters.':'No operational teams available.'}</p>}</fieldset>{draft&&<p className="text-xs text-muted-foreground">Save or cancel your hierarchy changes to switch charts.</p>}</aside>
      <main className="min-w-0 space-y-5">
        {notice&&<p role="status" className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm text-emerald-700 dark:text-emerald-300">{notice}</p>}
        {!canSee?<div className="rounded-2xl border border-dashed p-10 text-center"><Network className="mx-auto mb-4 h-10 w-10 text-muted-foreground"/><h2 className="font-semibold">Choose an available chart</h2><p className="mt-2 text-sm text-muted-foreground">Select a company or team chart from your list. HR manages team membership and access.</p></div>:<>
          <section className="overflow-hidden rounded-2xl border bg-card"><div className="flex flex-wrap items-start justify-between gap-4 bg-gradient-to-br from-primary/10 via-primary/5 to-transparent p-5 sm:p-6"><div className="min-w-0"><Badge variant="outline">{isCompany?'Company':kindLabels[team!.kind]}</Badge><h2 className="mt-3 break-words text-2xl font-semibold">{isCompany?'Company reporting structure':team?.name}</h2><p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground">{isCompany?<><Users className="h-4 w-4"/>Active employees and their reporting managers</>:<><MapPin className="h-4 w-4 shrink-0"/>{team?.siteName} · {team?.timezone}</>}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!!draft||loading} onClick={refresh}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>{!isCompany&&home.data?.isAdmin&&<Button size="sm" variant="outline" disabled={!!draft} onClick={()=>setTeamForm({team:team!})}><Pencil className="mr-2 h-4 w-4"/>Team details</Button>}{!isCompany&&chart.data?.canEdit&&!chartError&&!draft&&<Button size="sm" disabled={!validDate||directory.isLoading||!!directory.error} onClick={beginEdit}><GitBranch className="mr-2 h-4 w-4"/>{chart.data.revision?'Edit hierarchy':'Build hierarchy'}</Button>}</div></div>
            <div className="flex flex-wrap items-end justify-between gap-4 border-t px-5 py-4 sm:px-6">{isCompany?<Link className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:underline" href="/employees">Manage reporting managers<ArrowUpRight className="h-4 w-4"/></Link>:<><div className="flex flex-wrap items-end gap-3"><Field label="Chart date"><Input type="date" aria-label="Chart date in team time zone" value={date} disabled={!!draft} onChange={e=>{setDate(e.target.value);setNotice('');}}/></Field><Button variant="ghost" size="sm" disabled={!!draft} onClick={()=>setDate(today(team?.timezone))}><CalendarDays className="mr-2 h-4 w-4"/>Today</Button>{chart.data?.revision&&!chartError&&validDate&&<span className="pb-2 text-xs text-muted-foreground">Revision {chart.data.revision} · {chart.data.effectiveFrom} to {chart.data.effectiveTo||'ongoing'}</span>}</div><Link href={`/workforce?teamId=${scope}`} className="inline-flex items-center gap-2 pb-2 text-sm font-medium text-primary hover:underline">Manage team roster<ArrowUpRight className="h-4 w-4"/></Link></>}</div>
          </section>
          {!isCompany&&!validDate?<p role="alert" className="rounded-xl border p-5 text-sm text-destructive">Choose a valid date to view this team’s hierarchy.</p>:loading?<div role="status" className="rounded-2xl border p-10 text-muted-foreground">Loading hierarchy...</div>:chartError?<div role="alert" className="rounded-2xl border p-6"><h3 className="font-medium">This chart could not be loaded</h3><p className="mt-2 text-sm text-muted-foreground">Check your team access and selected date, then try again.</p><Button className="mt-3" variant="outline" onClick={refresh}>Try again</Button></div>:<>
            {!draft&&<div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'People in chart',value:nodes.length,icon:Users},{label:'Top-level positions',value:graph.roots.length,icon:Network},{label:'Reporting levels',value:graph.levels,icon:Layers3},{label:'Departments',value:departments,icon:Building2}].map(m=><div key={m.label} className="rounded-xl border bg-card p-4"><div className="flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{m.label}</p><m.icon className="h-4 w-4 text-primary"/></div><p className="mt-2 text-2xl font-semibold tabular-nums">{m.value}</p></div>)}</div>}
            {directory.error&&!isCompany&&home.data?.isAdmin&&<p role="alert" className="rounded-lg border p-3 text-sm text-destructive">The employee directory could not be loaded. <button type="button" className="underline" onClick={()=>directory.refetch()}>Reload employees</button> to edit this hierarchy.</p>}
            {draft?<OrgChartEditor initial={draft} people={people} savedPeople={nodes} pending={save.isPending} error={error} onSave={value=>save.mutate({teamId:scope,draft:value})} onCancel={()=>{setDraft(null);setError('');}}/>:nodes.length?<OrgChartCanvas key={`${scope}-${date}-${chart.data?.revision||0}`} nodes={nodes}/>:<div className="rounded-2xl border border-dashed bg-card p-10 text-center"><Network className="mx-auto mb-4 h-12 w-12 text-primary/60"/><h3 className="text-lg font-semibold">{isCompany?'No active employees to display':'Build a clear team structure'}</h3><p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">{isCompany?'Add active employees and their reporting managers in Employee Database.':'No hierarchy is saved for this date. Start with the team head, add staff, and connect each person to their reporting manager.'}</p>{chart.data?.canEdit&&!isCompany&&<Button className="mt-5" disabled={directory.isLoading||!!directory.error} onClick={beginEdit}><Plus className="mr-2 h-4 w-4"/>Build hierarchy</Button>}</div>}
            {!isCompany&&<p className="flex items-start gap-2 rounded-xl bg-muted/40 p-4 text-xs leading-relaxed text-muted-foreground"><GitBranch className="mt-0.5 h-4 w-4 shrink-0"/>This chart describes the team’s reporting structure. Roster membership and permissions are managed in Workforce; leave approvers are selected in HR Rules.</p>}
            {!isCompany&&!!chart.data?.history.length&&!draft&&<details className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer text-sm font-semibold"><History className="mr-2 inline h-4 w-4"/>Revision history · {chart.data.history.length}</summary><div className="mt-4 divide-y">{chart.data.history.map(r=><div key={r.version} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0"><p className="text-sm font-medium">Revision {r.version}{r.version===chart.data?.revision&&<Badge variant="secondary" className="ml-2">Shown</Badge>}</p><p className="mt-1 text-xs text-muted-foreground">{r.effectiveFrom} to {r.effectiveTo||'ongoing'}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{r.reason}</p></div><Button size="sm" variant="outline" onClick={()=>setDate(r.effectiveFrom)}>View effective date</Button></div>)}</div><p className="mt-3 text-xs text-muted-foreground">The newest applicable revision is shown when effective dates overlap.</p></details>}
          </>}
        </>}
      </main>
    </div>}
    {teamForm&&home.data&&<TeamForm key={teamForm.team?.id||'new'} team={teamForm.team} sites={home.data.sites} close={()=>setTeamForm(null)} saved={async row=>{await cache.invalidateQueries({queryKey:['/api/workforce/teams']});await cache.invalidateQueries({queryKey:[`/api/org-charts/teams/${row.id}`]});chooseScope(String(row.id));setTeamForm(null);setNotice(teamForm.team?'Team details saved.':'Team created. Build its hierarchy to get started.');}}/>}
  </div>;
}
function TeamForm({team,sites,close,saved}:{team:TeamSummary|null;sites:WorkforceHome['sites'];close:()=>void;saved:(row:{id:number})=>Promise<void>}){
  const [name,setName]=useState(team?.name||''),[kind,setKind]=useState(team?.kind||'event'),[siteId,setSiteId]=useState(team?String(team.siteId):'');
  const mutation=useMutation({mutationFn:()=>apiJson<{id:number}>(team?`/api/org-charts/teams/${team.id}/details`:'/api/workforce/teams',{method:'POST',body:team?{previous:{name:team.name,kind:team.kind,siteId:team.siteId},updated:{name,kind,siteId:Number(siteId)}}:{name,kind,siteId:Number(siteId)}}),onSuccess:saved});
  return <Dialog open onOpenChange={open=>{if(!open&&!mutation.isPending)close();}}><DialogContent><DialogHeader><DialogTitle>{team?'Edit team details':'Create operational team'}</DialogTitle><DialogDescription>{team?'Update the team name, type and work site.':'Create an event, FEC, mall activation or head office team.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();mutation.mutate();}}><fieldset disabled={mutation.isPending} className="space-y-4"><Field label="Team name"><Input autoFocus required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Team type"><select className={fieldClass} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{Object.entries(kindLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field><Field label="Work site"><select className={fieldClass} required value={siteId} onChange={e=>setSiteId(e.target.value)}><option value="">Choose a site</option>{sites.map(s=><option key={s.id} value={s.id}>{s.name} · {s.timezone}</option>)}</select></Field>{!sites.length&&<p className="text-sm text-muted-foreground">Create a work site in Workforce before adding a team.</p>}<Link href="/workforce" className="inline-flex items-center gap-1 text-sm text-primary hover:underline">Manage work sites<ArrowUpRight className="h-4 w-4"/></Link>{mutation.error&&<p role="alert" className="text-sm text-destructive">{mutation.error.message}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit" disabled={!siteId}>{mutation.isPending?'Saving...':team?'Save details':'Create team'}</Button></div></fieldset></form></DialogContent></Dialog>;
}
