import {useEffect,useState} from 'react';
import {Link} from 'wouter';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {apiJson} from '@/lib/queryClient';
import {kindLabels,type WorkforceHome} from '@shared/workforce';
import {orgChartInput,type ChartPerson,type OrgChartView,type OrgNode,type OrgPerson} from '@shared/org-chart';
const field='w-full rounded border bg-background p-2 text-sm';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function Branch({node,childrenByParent,search,path=[]}:{node:ChartPerson;childrenByParent:Map<number,ChartPerson[]>;search:string;path?:number[]}){
 const [collapsed,setCollapsed]=useState(false);const children=childrenByParent.get(node.employeeId)||[];
 if(path.includes(node.employeeId)||path.length>=20)return <li className="p-3 text-destructive">Check reporting lines for {node.name}.</li>;
 const match=search&&`${node.name} ${node.role} ${node.department}`.toLowerCase().includes(search.toLowerCase());
 return <li className="my-3"><article className={`max-w-md rounded-lg border bg-card p-4 shadow-sm ${match?'ring-2 ring-primary':''}`}><p className="text-xs font-semibold uppercase tracking-wide text-primary">{node.role}</p><h3 className="mt-1 font-semibold">{node.name}</h3><p className="text-sm text-muted-foreground">{node.department}{node.position!==node.role?` · ${node.position}`:''}</p>{children.length>0&&<Button type="button" size="sm" variant="ghost" className="mt-2" aria-expanded={!collapsed} onClick={()=>setCollapsed(!collapsed)}>{collapsed?'Show':'Hide'} {children.length} direct report{children.length===1?'':'s'}</Button>}</article>{!collapsed&&children.length>0&&<ul className="ml-5 border-l-2 border-primary/20 pl-5">{children.map(child=><Branch key={child.employeeId} node={child} childrenByParent={childrenByParent} search={search} path={[...path,node.employeeId]}/>)}</ul>}</li>;
}
function Chart({nodes,search}:{nodes:ChartPerson[];search:string}){
 const ids=new Set(nodes.map(n=>n.employeeId)),children=new Map<number,ChartPerson[]>(),roots:ChartPerson[]=[];
 for(const n of nodes){if(n.parentEmployeeId===null||!ids.has(n.parentEmployeeId))roots.push(n);else children.set(n.parentEmployeeId,[...(children.get(n.parentEmployeeId)||[]),n]);}
 // Keep corrupt legacy company relationships visible rather than dropping a cyclic component.
 const reached=new Set<number>();const visit=(id:number)=>{if(reached.has(id))return;reached.add(id);for(const child of children.get(id)||[])visit(child.employeeId);};roots.forEach(r=>visit(r.employeeId));
 const disconnected=nodes.filter(n=>!reached.has(n.employeeId));
 return <><ul aria-label="Organization hierarchy" className="grid items-start gap-6 lg:grid-cols-2">{roots.map(root=><Branch key={root.employeeId} node={root} childrenByParent={children} search={search}/>)}</ul>{disconnected.length>0&&<div role="alert" className="rounded border border-destructive p-4">These employees have circular reporting lines. Correct them in Employee Database: {disconnected.map(n=>n.name).join(', ')}.</div>}</>;
}
export default function OrgCharts(){
 const cache=useQueryClient(),[scope,setScope]=useState(()=>new URLSearchParams(window.location.search).get('teamId')||''),[date,setDate]=useState(today),[search,setSearch]=useState('');
 const home=useQuery<WorkforceHome>({queryKey:['/api/workforce/teams']});
 const directory=useQuery<{people:OrgPerson[]}>({queryKey:['/api/org-charts/company'],enabled:!!home.data?.isAdmin});
 useEffect(()=>{if(home.data&&!scope)setScope(home.data.isAdmin?'company':String(home.data.teams[0]?.id||''));},[home.data,scope]);
 const team=home.data?.teams.find(t=>String(t.id)===scope);
 const chart=useQuery<OrgChartView>({queryKey:[`/api/org-charts/teams/${scope}`,{date}],enabled:!!team&&/^\d{4}-\d{2}-\d{2}$/.test(date)});
 const [draft,setDraft]=useState<{version:number;effectiveFrom:string;effectiveTo:string;nodes:OrgNode[];reason:string}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [editingTeam,setEditingTeam]=useState<WorkforceHome['teams'][number]|null>(null);
 const [personId,setPersonId]=useState(''),[newTeam,setNewTeam]=useState(false),[teamName,setTeamName]=useState(''),[teamKind,setTeamKind]=useState('event'),[siteId,setSiteId]=useState('');
 const people=directory.data?.people||[];
 const save=useMutation({mutationFn:(body:unknown)=>apiJson(`/api/org-charts/teams/${scope}`,{method:'POST',body}),onSuccess:()=>{setDraft(null);setError('');setNotice('Hierarchy revision saved.');cache.invalidateQueries({queryKey:[`/api/org-charts/teams/${scope}`]});},onError:(e:Error)=>setError(e.message)});
 const create=useMutation({mutationFn:()=>apiJson<{id:number}>(editingTeam?"/api/org-charts/teams/"+editingTeam.id+"/details":'/api/workforce/teams',{method:'POST',body:editingTeam?{previous:{name:editingTeam.name,kind:editingTeam.kind,siteId:editingTeam.siteId},updated:{name:teamName,kind:teamKind,siteId:Number(siteId)}}:{name:teamName,kind:teamKind,siteId:Number(siteId)}}),onSuccess:async row=>{await cache.invalidateQueries({queryKey:['/api/workforce/teams']});setScope(String(row.id));setNewTeam(false);setTeamName('');setNotice(editingTeam?'Team details saved.':'Team created. Add its hierarchy below.');setEditingTeam(null);setError('');},onError:(e:Error)=>setError(e.message)});
 const nodes:ChartPerson[]=scope==='company'?people.map(p=>({...p,employeeId:p.id,parentEmployeeId:p.reportingManagerId,role:p.position})):chart.data?.nodes||[];
 const setNode=(id:number,change:Partial<OrgNode>)=>setDraft(d=>d&&({...d,nodes:d.nodes.map(n=>n.employeeId===id?{...n,...change}:n)}));
 const label=(id:number)=>people.find(p=>p.id===id)?.name||`Employee ${id}`;
 const chooseScope=(value:string)=>{setScope(value);setDraft(null);setError('');setNotice('');setSearch('');};
 return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">People & reporting</p><h1 className="mt-2 text-3xl font-semibold">Organization charts</h1><p className="mt-2 text-muted-foreground">Company reporting lines and a separate hierarchy for every event, FEC and mall activation.</p></div>{home.data?.isAdmin&&<Button onClick={()=>{setEditingTeam(null);setTeamName('');setNewTeam(!newTeam);setSiteId(String(home.data?.sites[0]?.id||''));}}>{newTeam?'Close team form':'Create operational team'}</Button>}</header>
 {home.isLoading?<p>Loading teams…</p>:home.error?<p role="alert">Unable to load your team access.</p>:<>
 {newTeam&&<form className="grid gap-4 rounded-lg border bg-card p-5 md:grid-cols-2" onSubmit={e=>{e.preventDefault();create.mutate();}}><label>Team / event name<Input required minLength={2} maxLength={120} value={teamName} onChange={e=>setTeamName(e.target.value)}/></label><label>Team type<select className={field} value={teamKind} onChange={e=>setTeamKind(e.target.value)}>{Object.entries(kindLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Work site<select className={field} required value={siteId} onChange={e=>setSiteId(e.target.value)}><option value="">Choose site</option>{home.data?.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="flex items-end gap-3"><Button disabled={create.isPending||!siteId}>{editingTeam?'Save team details':'Create team'}</Button><Link href="/workforce" className="text-sm text-primary">Manage work sites</Link></div></form>}
 {!scope?<p>No teams are available within your access. HR can create teams and assign access in Workforce.</p>:<>
 <div className="grid gap-4 md:grid-cols-3"><label>Chart<select className={field} disabled={!!draft} value={scope} onChange={e=>chooseScope(e.target.value)}>{home.data?.isAdmin&&<option value="company">Company · current reporting lines</option>}{home.data?.teams.map(t=><option key={t.id} value={t.id}>{t.name} · {kindLabels[t.kind]}</option>)}</select></label>{scope!=='company'&&<label>Chart date (team local date)<Input type="date" required value={date} disabled={!!draft} onChange={e=>setDate(e.target.value)}/></label>}<label>Highlight a person or role<Input placeholder="Name, role or department" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 {scope==='company'?<p className="text-sm text-muted-foreground">Current active employees, using their reporting-manager records. <Link className="text-primary underline" href="/employees">Edit company reporting lines in Employee Database</Link>.</p>:<div className="flex flex-wrap items-center justify-between gap-3 rounded border bg-muted/30 p-4"><div><h2 className="font-semibold">{team?.name}</h2><p className="text-sm">{team?.siteName} · {team?.timezone}{chart.data?.revision?` · Revision ${chart.data.revision} · ${chart.data.effectiveFrom} through ${chart.data.effectiveTo||'ongoing'}`:''}</p><p className="mt-1 text-sm text-muted-foreground">Chart roles describe reporting lines. Manage dated roster membership and account permissions in Workforce; select leave approvers in HR Rules.</p></div>{chart.data?.canEdit&&!draft&&<Button onClick={()=>{setDraft({version:chart.data!.version,effectiveFrom:chart.data!.effectiveFrom||date,effectiveTo:chart.data!.effectiveTo||'',nodes:chart.data!.nodes.map(({employeeId,parentEmployeeId,role})=>({employeeId,parentEmployeeId,role})),reason:''});setNotice('');setPersonId('');}}>{chart.data.revision?'Revise hierarchy':'Build hierarchy'}</Button>}{home.data?.isAdmin&&team&&!draft&&<Button variant="outline" onClick={()=>{setEditingTeam(team);setTeamName(team.name);setTeamKind(team.kind);setSiteId(String(team.siteId));setNewTeam(true);}}>Edit team details</Button>}<Link href={`/workforce?teamId=${scope}`} className="text-sm text-primary">Open team roster</Link></div>}
 {(scope==='company'?directory.isLoading:chart.isLoading)?<p>Loading hierarchy…</p>:(scope==='company'?directory.error:chart.error)?<p role="alert">Unable to load this chart. Refresh or check team access and the selected date.</p>:<>
 {draft&&<form className="space-y-4 rounded-lg border bg-card p-5" onSubmit={e=>{e.preventDefault();const parsed=orgChartInput.safeParse({...draft,effectiveTo:draft.effectiveTo||null});if(!parsed.success){setError(parsed.error.issues[0].message);return;}save.mutate(parsed.data);}}><h2 className="text-lg font-semibold">Edit team hierarchy</h2><div className="grid gap-4 md:grid-cols-2"><label>Effective from<Input type="date" required value={draft.effectiveFrom} onChange={e=>setDraft({...draft,effectiveFrom:e.target.value})}/></label><label>Effective through (blank = ongoing)<Input type="date" value={draft.effectiveTo} min={draft.effectiveFrom} onChange={e=>setDraft({...draft,effectiveTo:e.target.value})}/></label></div><div className="flex items-end gap-3"><label className="flex-1">Add employee<select className={field} value={personId} onChange={e=>setPersonId(e.target.value)}><option value="">Choose employee</option>{people.filter(p=>!draft.nodes.some(n=>n.employeeId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name} · {p.position}</option>)}</select></label><Button type="button" variant="outline" disabled={!personId||draft.nodes.length>=500} onClick={()=>{const p=people.find(p=>p.id===Number(personId))!;setDraft({...draft,nodes:[...draft.nodes,{employeeId:p.id,parentEmployeeId:null,role:p.position||'Team member'}]});setPersonId('');}}>Add to chart</Button></div>
 {draft.nodes.map(n=><fieldset key={n.employeeId} className="grid gap-3 rounded border p-3 md:grid-cols-3"><legend className="px-1 font-medium">{label(n.employeeId)}</legend><label>Role in this team<Input required maxLength={100} value={n.role} onChange={e=>setNode(n.employeeId,{role:e.target.value})}/></label><label>Reports to<select className={field} value={n.parentEmployeeId||''} onChange={e=>setNode(n.employeeId,{parentEmployeeId:e.target.value?Number(e.target.value):null})}><option value="">Top level / team head</option>{draft.nodes.filter(p=>p.employeeId!==n.employeeId).map(p=><option key={p.employeeId} value={p.employeeId}>{label(p.employeeId)} · {p.role}</option>)}</select></label><Button className="self-end" type="button" variant="outline" onClick={()=>setDraft({...draft,nodes:draft.nodes.filter(p=>p.employeeId!==n.employeeId).map(p=>p.parentEmployeeId===n.employeeId?{...p,parentEmployeeId:null}:p)})}>Remove from chart</Button></fieldset>)}
 <label className="block">Reason for revision<textarea className={field} required minLength={5} maxLength={2000} value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><p className="text-sm text-muted-foreground">Saving creates a dated revision. The latest saved revision applies where dates overlap. Removing a manager places their direct reports at the top level for you to reassign.</p><div className="flex gap-3"><Button disabled={save.isPending}>Save hierarchy revision</Button><Button type="button" variant="outline" disabled={save.isPending} onClick={()=>{setDraft(null);setError('');}}>Cancel editing</Button></div></form>}
 {!draft&&(nodes.length?<><p className="text-sm text-muted-foreground">{nodes.length} people · expand or collapse each reporting branch</p><Chart key={`${scope}-${date}-${chart.data?.revision||0}`} nodes={nodes} search={search}/></>:<div className="rounded-lg border border-dashed p-8"><h2 className="font-semibold">No hierarchy for this date</h2><p className="mt-2 text-sm text-muted-foreground">{home.data?.isAdmin?'Build a hierarchy, add staff and choose who each person reports to.':'Ask HR to configure the hierarchy and your dated team membership.'}</p></div>)}
 {scope!=='company'&&!!chart.data?.history.length&&<details className="rounded border p-4"><summary className="cursor-pointer font-medium">Revision history</summary><ul className="mt-3 space-y-2 text-sm">{chart.data.history.map(r=><li key={r.version}>Revision {r.version} · {r.effectiveFrom} – {r.effectiveTo||'ongoing'} · {r.reason}</li>)}</ul></details>}
 </>}</>}{error&&<p role="alert" className="text-destructive">{error}</p>}{notice&&<p role="status" className="text-primary">{notice}</p>}</>}
 </div>;
}
