import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, fieldClass, useAction, QueryError, downloadCsv } from '@/components/hr/Operations';
import { useAuth } from '@/contexts/AuthContext';
type Adjustment = {
    label: string;
    kind: 'allowance' | 'deduction';
    amount: string;
    reason: string;
};
export default function PayrollOperations() {
    const { user } = useAuth(), [period, setPeriod] = useState(new Date().toISOString().slice(0, 7)), [employee, setEmployee] = useState(''), [selected, setSelected] = useState<number | null>(null), [note, setNote] = useState(''), [reference, setReference] = useState(''), [confirmed, setConfirmed] = useState(false), [adjustments, setAdjustments] = useState<Adjustment[] | null>(null);
    const [year, month] = period.split('-').map(Number);
    const options = useQuery<any>({ queryKey: ['/api/payroll/options'] }), records = useQuery<any[]>({ queryKey: [`/api/payroll/month/${month}/year/${year}`], enabled: !!year && !!month }), detail = useQuery<any>({ queryKey: [`/api/payroll/${selected}`], enabled: !!selected });
    const action = useAction(() => { setNote(''); setAdjustments(null); setReference(''); setConfirmed(false); });
    const row = detail.data?.record, review = detail.data?.review;
    const act = (actionName: string) => action.mutate({ url: `/api/payroll/${selected}/action`, body: { version: review.version, action: actionName, reason: note } });
    const totals = Object.entries((records.data || []).filter(r => r.status !== 'cancelled').reduce((s: Record<string, number>, r: any) => { const c = r.review?.currency || 'Unspecified'; s[c] = (s[c] || 0) + Number(r.netSalary); return s; }, {}));
    return <div className="space-y-6"><style>{`@media print { body * { visibility: hidden; } #payroll-payslip, #payroll-payslip * { visibility: visible; } #payroll-payslip { position: absolute; left: 0; top: 0; width: 100%; } #payroll-payslip [class~="print:hidden"], #payroll-payslip [class~="print:hidden"] * { display: none !important; } }`}</style><div className="flex flex-wrap justify-between gap-3"><h1 className="text-2xl font-bold">Payroll</h1>{['admin', 'super_admin'].includes(user?.role || '') && <a className="underline text-primary" href="/hr-rules">Configure employee pay rules</a>}</div><Section title="Pay runs"><div className="flex flex-wrap items-end gap-4"><Field label="Payment month"><input className={fieldClass} type="month" value={period} onChange={e => { setPeriod(e.target.value); setSelected(null); }}/></Field>{options.data?.canCreate && <><Field label="Employee"><select className={fieldClass} value={employee} onChange={e => setEmployee(e.target.value)}><option value="">Select employee</option>{options.data.employees.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Button disabled={!employee || action.isPending} onClick={() => action.mutate({ url: '/api/payroll', body: { employeeId: Number(employee), year, month } })}>Generate draft</Button></>}<Button variant="outline" disabled={!records.data?.length} onClick={() => downloadCsv('payroll-' + period + '.csv', [['Employee', 'Currency', 'Period start', 'Period end', 'Basic', 'Net', 'Status', 'Reference'], ...(records.data || []).map(r => [r.employeeName, r.review?.currency, r.review?.periodStart, r.review?.periodEnd, r.basicSalary, r.netSalary, r.status, r.wpsReference])])}>Export reconciliation CSV</Button></div><p className="text-sm text-muted-foreground">The cycle ends before its configured start day in the payment month. Drafts use approved assignment time and dated employee rules. Adjustments require review. Record a reference after completing payment externally.</p><p>{totals.map(([c, v]) => `${c} ${Number(v).toFixed(2)}`).join(' · ') || 'No payroll totals yet'}</p><QueryError error={options.error || records.error}/><Table headers={['Employee', 'Period', 'Currency', 'Net pay', 'Status', 'Payment reference', 'Action']} rows={(records.data || []).map(r => [r.employeeName, r.review ? r.review.periodStart + ' → ' + r.review.periodEnd : 'Legacy record', r.review?.currency || '—', r.netSalary, r.status, r.wpsReference || '—', <Button variant="outline" onClick={() => { setSelected(r.id); setAdjustments(null); }}>View payroll</Button>])}/></Section>
 {selected && <div id="payroll-payslip"><Section title="Payroll detail and payslip"><QueryError error={detail.error}/>{row && <><div className="flex justify-between"><div><h3 className="font-semibold">{review?.policy?.employee?.name || detail.data.employeeName}</h3><p>{review?.periodStart} → {review?.periodEnd} · Due {review?.payDate || '—'} · {row.status}</p></div><Button className="print:hidden" variant="outline" onClick={() => window.print()}>Print payslip</Button></div><Table headers={['Pay item', 'Amount']} rows={[[`Basic salary (${review?.currency || ''})`, row.basicSalary], ...Object.entries(row.allowances).map(([k, v]) => [k, String(v)]), ...Object.entries(row.deductions).map(([k, v]) => ['Deduction: ' + k, '−' + String(v)]), ['Net pay', row.netSalary], ['Payment reference', row.wpsReference || 'Pending']]}/><h3 className="font-medium">Approved time included</h3><Table headers={['Work date', 'Timesheet', 'Regular minutes', 'Overtime minutes', 'Additional pay']} rows={(detail.data.lines || []).map((l: any) => [l.workDate, l.timesheetId, l.regularMinutes, l.overtimeMinutes, l.amount])}/>
 {review && row.status === 'draft' && detail.data.canEdit && <details className="print:hidden"><summary className="cursor-pointer">Allowances, deductions and corrections</summary><form className="space-y-3 mt-4" onSubmit={e => { e.preventDefault(); action.mutate({ url: `/api/payroll/${selected}`, method: 'PATCH', body: { version: review.version, adjustments: adjustments || review.adjustments, reason: note } }); }}>{(adjustments || review.adjustments).map((a: Adjustment, i: number) => <div className="grid gap-2 md:grid-cols-5" key={i}>{(['label', 'amount', 'reason'] as const).map(k => <Field key={k} label={k}><input className={fieldClass} required minLength={k === 'reason' ? 5 : 1} value={a[k]} onChange={e => setAdjustments((adjustments || review.adjustments).map((v: Adjustment, j: number) => j === i ? { ...v, [k]: e.target.value } : v))}/></Field>)}<Field label="Kind"><select className={fieldClass} value={a.kind} onChange={e => setAdjustments((adjustments || review.adjustments).map((v: Adjustment, j: number) => j === i ? { ...v, kind: e.target.value } : v))}><option value="allowance">Allowance</option><option value="deduction">Deduction</option></select></Field><Button type="button" variant="outline" onClick={() => setAdjustments((adjustments || review.adjustments).filter((_: unknown, j: number) => j !== i))}>Remove</Button></div>)}<Button type="button" variant="outline" onClick={() => setAdjustments([...(adjustments || review.adjustments), { label: '', kind: 'allowance', amount: '0.00', reason: '' }])}>Add adjustment</Button><Field label="Change reason"><input className={fieldClass} required minLength={5} value={note} onChange={e => setNote(e.target.value)}/></Field><Button disabled={action.isPending}>Save adjustments</Button></form></details>}
 {review && !['processed', 'cancelled'].includes(row.status) && <div className="space-y-3 print:hidden"><Field label="Submission or review reason"><input className={fieldClass} value={note} onChange={e => setNote(e.target.value)}/></Field><div className="flex flex-wrap gap-3">{row.status === 'draft' && detail.data.canEdit && <><Button disabled={note.trim().length < 5 || action.isPending} onClick={() => act('submit')}>Submit for approval</Button><Button variant="outline" disabled={note.trim().length < 5 || action.isPending} onClick={() => act('cancel')}>Cancel draft</Button></>}{detail.data.canApprove && ['submitted', 'approved'].includes(row.status) && <><Button variant="outline" disabled={note.trim().length < 5 || action.isPending} onClick={() => act('return')}>Return for correction</Button>{row.status === 'submitted' && <Button disabled={note.trim().length < 5 || action.isPending} onClick={() => act('approve')}>Approve payroll</Button>}</>}</div>{row.status === 'approved' && detail.data.canApprove && <form className="space-y-3" onSubmit={e => { e.preventDefault(); action.mutate({ url: `/api/payroll/${selected}/mark-paid`, body: { version: review.version, reference, confirmed } }); }}><Field label="External payment reference"><input className={fieldClass} value={reference} required onChange={e => setReference(e.target.value)}/></Field><label className="block"><input type="checkbox" checked={confirmed} required onChange={e => setConfirmed(e.target.checked)}/> I confirm this payment was completed externally.</label><Button disabled={action.isPending}>Record payment</Button></form>}</div>}
 {detail.data.canEdit && (row.status === 'cancelled' || (!review && row.status === 'pending')) && <form className="space-y-3 print:hidden" onSubmit={e => { e.preventDefault(); action.mutate({ url: `/api/payroll/${selected}/regenerate`, body: { version: review?.version || 0, reason: note } }); }}><p>Regenerate using the current effective rules and approved time. Previous figures remain in review history.</p><Field label="Regeneration reason"><input className={fieldClass} required minLength={5} value={note} onChange={e => setNote(e.target.value)}/></Field><Button disabled={action.isPending}>Regenerate draft</Button></form>}<details className="print:hidden"><summary className="cursor-pointer">Review history</summary><Table headers={['Version', 'Action', 'Reason', 'Recorded']} rows={(review?.history || []).map((h: any) => [h.version, h.action, h.reason, new Date(h.at).toLocaleString()])}/></details></>}</Section></div>}</div>;
}
