import {TimePay} from '@/components/operations/TimePay';
import {Settlements} from '@/components/onboarding/Settlements';
import {PayrollReconciliation} from '@/components/onboarding/PayrollReconciliation';
import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import type {Payroll as PayrollRecord} from '@shared/schema';
import type {ApiEmployee} from '@/lib/api-types';
import {calculatePayroll,csvCell} from '@shared/money';
import {hasPermission} from '@shared/permissions';
import {useAuth} from '@/contexts/AuthContext';
import {apiJson} from '@/lib/queryClient';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {useToast} from '@/hooks/use-toast';
type Row=Omit<PayrollRecord,'createdAt'|'updatedAt'|'processedAt'> & {employeeName:string;processedAt:string|null};
const blank={employeeId:'',basicSalary:'0.00',housing:'0.00',transport:'0.00',otherAllowance:'0.00',deductions:'0.00'};
const money=(value:unknown)=>Number(value||0).toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Payroll(){
 const {user}=useAuth(),{toast}=useToast(),cache=useQueryClient();
 const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[editing,setEditing]=useState<number|null>(null),[paid,setPaid]=useState<Row|null>(null),[reference,setReference]=useState('');
 const [year,month]=period.split('-').map(Number);
 const [calculation,setCalculation]=useState<{netSalary:string;roundingAdjustmentCents:number;version:number}|null>(null);
 const preview=useMutation({mutationFn:(body:unknown)=>apiJson<{netSalary:string;roundingAdjustmentCents:number;version:number}>('/api/payroll/preview',{method:'POST',body}),onSuccess:setCalculation,onError:error=>toast({title:'Unable to preview payroll',description:error.message,variant:'destructive'})});
 const {data:records=[],isLoading,error}=useQuery<Row[]>({queryKey:[`/api/payroll/month/${month}/year/${year}`],enabled:!!month&&!!year});
 const {data:employees=[]}=useQuery<ApiEmployee[]>({queryKey:['/api/employees',{limit:1000}]});
 const canCreate=!!user&&hasPermission(user.role,'payroll_management','create'),canUpdate=!!user&&hasPermission(user.role,'payroll_management','update'),canApprove=!!user&&hasPermission(user.role,'payroll_management','approve');
 const mutation=useMutation({mutationFn:({url,body,method='POST'}:{url:string;body:unknown;method?:string})=>apiJson(url,{method,body}),onSuccess:()=>{cache.invalidateQueries({queryKey:[`/api/payroll/month/${month}/year/${year}`]});cache.invalidateQueries({queryKey:['/api/payroll/reconciliation']});setOpen(false);setPaid(null);toast({title:'Payroll saved'});},onError:error=>toast({title:'Unable to save payroll',description:error.message,variant:'destructive'})});
 const original=records.find(row=>row.id===editing);
 const extraAllowances=Object.fromEntries(Object.entries((original?.allowances||{}) as Record<string,string|number>).filter(([key])=>!['housing','transport','other'].includes(key)));
 const originalDeductions=(original?.deductions||{}) as Record<string,string|number>;
 const payload=()=>({employeeId:Number(form.employeeId),month,year,basicSalary:form.basicSalary,allowances:{...extraAllowances,housing:form.housing,transport:form.transport,other:form.otherAllowance},deductions:original&&Number(form.deductions)===Object.values(originalDeductions).reduce<number>((sum,value)=>sum+Number(value),0)?originalDeductions:{other:form.deductions}});
 const edit=(row:Row)=>{const allowance=row.allowances as Record<string,string|number>;setCalculation(null);setEditing(row.id);setForm({employeeId:String(row.employeeId),basicSalary:String(row.basicSalary),housing:String(allowance.housing||0),transport:String(allowance.transport||0),otherAllowance:String(allowance.other||0),deductions:String(Object.values(row.deductions as Record<string,string|number>).reduce<number>((sum,value)=>sum+Number(value),0))});setOpen(true);};
 const download=()=>{const lines=[['Employee','Month','Year','Basic salary QAR','Net salary QAR','Status','Payment reference','Rounding adjustment QAR','Rule version'],...records.map(row=>[row.employeeName,row.month,row.year,row.basicSalary,row.netSalary,row.status,row.wpsReference,(row.roundingAdjustmentCents/100).toFixed(2),row.calculationSnapshot?.version||'baseline'])];const url=URL.createObjectURL(new Blob([lines.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`payroll-${period}.csv`;link.click();URL.revokeObjectURL(url);};
 return <Card><CardHeader><CardTitle>Payroll</CardTitle></CardHeader><CardContent className="space-y-5">
  <PayrollReconciliation month={month} year={year}/><Settlements/><TimePay key={period} records={records} canUpdate={canUpdate}/>
  <div className="flex flex-wrap gap-3"><label>Pay period<Input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label>{canCreate&&<Button onClick={()=>{setCalculation(null);setEditing(null);setForm(blank);setOpen(true);}}>Create payroll draft</Button>}<Button variant="outline" disabled={!records.length} onClick={download}>Export CSV</Button><Button variant="outline" onClick={()=>window.print()}>Print</Button></div>
  <p className="text-sm text-muted-foreground">Bank submission is not connected. Record a payment reference only after payment has been completed outside this application.</p>
  <p className="text-xl">Total net salary: QAR {money(records.reduce((sum,row)=>sum+Number(row.netSalary),0))}</p>
  {isLoading?<p>Loading payroll…</p>:error?<p role="alert">Unable to load payroll.</p>:<div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Employee','Basic salary','Net salary','Status','Payment reference','Actions'].map(text=><th className="p-3 text-left" key={text}>{text}</th>)}</tr></thead><tbody>{records.map(row=><tr className="border-t" key={row.id}><td className="p-3">{row.employeeName}</td><td className="p-3">QAR {money(row.basicSalary)}</td><td className="p-3">QAR {money(row.netSalary)}{row.roundingAdjustmentCents!==0&&<p className="text-xs">Rounding: {row.roundingAdjustmentCents>0?'+':''}{(row.roundingAdjustmentCents/100).toFixed(2)}</p>}<p className="text-xs text-muted-foreground">Rules: {row.calculationSnapshot?.version?`v${row.calculationSnapshot.version}`:'baseline'}</p></td><td className="p-3">{row.status}</td><td className="p-3">{row.wpsReference || '—'}</td><td className="p-3 space-x-2">{canUpdate&&row.status==='pending'&&<Button variant="outline" onClick={()=>edit(row)}>Edit draft</Button>}{canApprove&&row.status==='pending'&&<Button onClick={()=>{setPaid(row);setReference('');}}>Record payment</Button>}</td></tr>)}</tbody></table>{records.length===0&&<p>No payroll records for this period.</p>}</div>}
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing?'Edit payroll draft':'Create payroll draft'} — {period}</DialogTitle></DialogHeader><form className="space-y-3" onChange={()=>setCalculation(null)} onSubmit={e=>{e.preventDefault();try{calculatePayroll(payload().basicSalary,payload().allowances,payload().deductions);mutation.mutate({url:editing?`/api/payroll/${editing}`:'/api/payroll',method:editing?'PATCH':'POST',body:payload()});}catch(error){toast({title:'Check amounts',description:error instanceof Error?error.message:'Invalid amount',variant:'destructive'});}}}>
   <label>Employee<select required disabled={!!editing} className="block w-full border rounded p-2" value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName} ({employee.employeeId})</option>)}</select></label>
   {(['basicSalary','housing','transport','otherAllowance','deductions'] as const).map(key=><label className="block" key={key}>{({basicSalary:'Basic salary',housing:'Housing allowance',transport:'Transport allowance',otherAllowance:'Other allowance',deductions:'Total deductions'})[key]} (QAR)<Input required type="number" min="0" step="0.01" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<div className="flex gap-2"><Button type="button" variant="outline" disabled={preview.isPending||!form.employeeId} onClick={()=>preview.mutate({...payload(),id:editing})}>Preview net salary</Button><Button disabled={mutation.isPending}>Save draft</Button></div>{calculation&&<p className="text-sm">Calculated net: QAR {calculation.netSalary} · rounding adjustment: QAR {(calculation.roundingAdjustmentCents/100).toFixed(2)} · rules {calculation.version?`v${calculation.version}`:'baseline'}</p>}
  </form></DialogContent></Dialog>
  <Dialog open={!!paid} onOpenChange={value=>{if(!value)setPaid(null);}}><DialogContent><DialogHeader><DialogTitle>Record completed payment</DialogTitle></DialogHeader><p>{paid?.employeeName} — QAR {money(paid?.netSalary)}</p><form className="space-y-4" onSubmit={e=>{e.preventDefault();mutation.mutate({url:`/api/payroll/${paid!.id}/mark-paid`,body:{reference}});}}><label>Bank or payment reference<Input required value={reference} onChange={e=>setReference(e.target.value)}/></label><Button disabled={mutation.isPending}>Mark as paid</Button></form></DialogContent></Dialog>
 </CardContent></Card>;
}
