import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Panel,Field,Paging,LoadState,selectStyle} from '@/components/lifecycle/Common';
import {useServiceSave} from '@/components/lifecycle/EmployeeServices';

type Kind='probation'|'transfers'|'incidents';
const states={probation:['open','submitted','confirmed','follow_up','cancelled'],transfers:['submitted','approved','rejected','cancelled','applied'],incidents:['open','in_progress','resolved','closed']};
const label=(s:string)=>s.replaceAll('_',' ');
const titles={probation:'Probation reviews',transfers:'Employee transfers',incidents:'Operational incidents'};
const descriptions={probation:'Record objectives, collect a manager review, and publish an independent HR decision. Employees can respond to their published decision.',transfers:'Propose department, position, location and reporting manager changes. Approved transfers take effect when HR applies them on or after the effective date.',incidents:'Track equipment, service, attendance and site issues through corrective action and independent closure. Use HR Helpdesk for confidential grievances or medical information. Updates here are shared with the reporter, assigned handler and HR.'};
export function Probation(){return <PeopleOperations kind="probation"/>;}
export function Transfers(){return <PeopleOperations kind="transfers"/>;}
export function Incidents(){return <PeopleOperations kind="incidents"/>;}
function PeopleOperations({kind}:{kind:Kind}){
 const config=useQuery<any>({queryKey:['/api/people-operations/config']}),[page,setPage]=useState(1),[status,setStatus]=useState('');
 const q=useQuery<any>({queryKey:[`/api/people-operations/${kind}`,{page,status}]});
 return <div><h1 className="text-2xl font-bold">{titles[kind]}</h1><p className="text-muted-foreground">{descriptions[kind]}</p>{config.error&&<p role="alert">Unable to load workflow permissions.</p>}
 {config.data?.canConfigure&&<Policy key={config.data.policy.version} policy={config.data.policy}/>}
 {(config.data?.canManage||kind==='incidents')&&<Panel title={kind==='probation'?'Open a probation review':kind==='transfers'?'Propose a transfer':'Report an operational incident'}>{kind==='incidents'?<IncidentForm/>:<EmployeeForm kind={kind}/>}</Panel>}
 <Panel title={config.data?.canManage?'HR work queue':'My records and assigned work'}><Field label="Status"><select className={selectStyle} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{states[kind].map(s=><option value={s} key={s}>{label(s)}</option>)}</select></Field><LoadState query={q}/>{q.data?.items.map((r:any)=><Record key={kind+':'+r.id+':'+r.version} kind={kind} row={r} manage={!!config.data?.canManage}/>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel></div>;
}
function History({kind,id,policy=false}:{kind?:Kind;id?:number;policy?:boolean}){
 const [open,setOpen]=useState(false),q=useQuery<any[]>({queryKey:[policy?'/api/people-operations/policy-history':`/api/people-operations/${kind}/${id}/history`],enabled:open});
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary className="cursor-pointer">{policy?'Policy history':'Record history'}</summary>{q.isLoading&&<p>Loading history…</p>}{q.error&&<p role="alert">Unable to load history.</p>}{q.data?.map(r=><details className="rounded border p-2" key={r.version}><summary>v{r.version} · {r.reason}</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(r.snapshot,null,2)}</pre></details>)}</details>;
}
function Policy({policy:p}:{policy:any}){
 const [rules,setRules]=useState(p.rules),[reason,setReason]=useState(''),save=useServiceSave();
 return <Panel title="Admin workflow rules"><details><summary className="cursor-pointer">Edit rules · version {p.version}</summary><p className="my-2 text-sm">Rules are saved with each new case. Existing cases keep their original limits and deadlines. Extension limits start at zero; HR must set the allowed limits before opening a case that may need an extension. Incident targets count elapsed hours from reporting.</p><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'people-operations/policy',body:{version:p.version,rules,reason}});}}>{[['maxExtensionDays','Maximum days per probation extension',365],['maxExtensions','Maximum extensions per review',10]].map(([key,title,max])=><Field key={String(key)} label={String(title)}><Input type="number" required min={0} max={Number(max)} value={rules[key]} onChange={e=>setRules({...rules,[key]:Number(e.target.value)})}/></Field>)}{['low','medium','high'].map(s=><Field key={s} label={`${label(s)} severity resolution target (hours)`}><Input type="number" required min={1} max={8760} value={rules.incidentHours[s]} onChange={e=>setRules({...rules,incidentHours:{...rules.incidentHours,[s]:Number(e.target.value)}})}/></Field>)}<Field label="Policy change reason"><Textarea required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Save new policy version</Button></form></details><History policy/></Panel>;
}
function EmployeePicker({title,onSelect}:{title:string;onSelect:(p:any)=>void}){
 const [search,setSearch]=useState(''),[selected,setSelected]=useState(''),q=useQuery<any[]>({queryKey:['/api/people-operations/people',{q:search}],enabled:search.trim().length>=2});
 return <div className="space-y-2"><Field label={`Find ${title}`}><Input placeholder="Name or employee number" value={search} onChange={e=>{setSearch(e.target.value);setSelected('');onSelect(null);}}/></Field>{q.error&&<p role="alert">Unable to search employees.</p>}<Field label={title}><select className={selectStyle} required value={selected} onChange={e=>{setSelected(e.target.value);onSelect(q.data?.find(p=>String(p.id)===e.target.value)||null);}}><option value="">Choose employee</option>{q.data?.map(p=><option key={p.id} value={p.id}>{p.name} · {p.employee_id}</option>)}</select></Field></div>;
}
function Reviewer({employeeId,value,onChange}:{employeeId:number;value:string;onChange:(id:string)=>void}){
 const q=useQuery<any[]>({queryKey:['/api/people-operations/reviewers',{employeeId}],enabled:!!employeeId});
 return <Field label="Independent reviewer (HR or current reporting manager)">{q.error&&<p role="alert">Unable to load reviewers.</p>}<select className={selectStyle} required value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose reviewer</option>{q.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>;
}
function EmployeeForm({kind}:{kind:'probation'|'transfers'}){
 const [person,setPerson]=useState<any>(null),[reviewer,setReviewer]=useState(''),[reason,setReason]=useState(''),[objectives,setObjectives]=useState(''),[start,setStart]=useState(''),[due,setDue]=useState(''),[effective,setEffective]=useState('');
 const [target,setTarget]=useState({department:'',position:'',location:'',reportingManagerId:null as number|null}),[managerMode,setManagerMode]=useState('keep'),save=useServiceSave();
 return <form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();if(!person)return;save.mutate({path:'people-operations/'+kind,body:kind==='probation'?{employeeId:person.id,reviewerId:Number(reviewer),startDate:start,dueDate:due,objectives,reason}:{employeeId:person.id,employeeVersion:person.record_version,target,effectiveDate:effective,reason}},{onSuccess:()=>{setReason('');}});}}><EmployeePicker title="Employee" onSelect={p=>{setPerson(p);setReviewer('');setManagerMode('keep');setTarget({department:p?.department||'',position:p?.position||'',location:p?.location||'',reportingManagerId:p?.reporting_manager_id??null});}}/>
 {kind==='probation'?<><Reviewer employeeId={person?.id||0} value={reviewer} onChange={setReviewer}/><Field label="Review period start"><Input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Review due date"><Input type="date" required min={start} value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="Objectives and expected evidence"><Textarea required minLength={5} maxLength={2000} value={objectives} onChange={e=>setObjectives(e.target.value)}/></Field></>:<><Field label="Effective date"><Input type="date" required value={effective} onChange={e=>setEffective(e.target.value)}/></Field>{(['department','position','location'] as const).map(key=><Field key={key} label={'New '+key}><Input required minLength={2} maxLength={200} value={target[key]} onChange={e=>setTarget({...target,[key]:e.target.value})}/></Field>)}<Field label="Reporting manager change"><select className={selectStyle} value={managerMode} onChange={e=>{setManagerMode(e.target.value);setTarget({...target,reportingManagerId:e.target.value==='keep'?person?.reporting_manager_id??null:null});}}><option value="keep">Keep current manager</option><option value="clear">Clear manager</option><option value="choose">Choose another manager</option></select></Field>{managerMode==='choose'&&<EmployeePicker title="New reporting manager" onSelect={p=>setTarget({...target,reportingManagerId:p?.id??null})}/>}<p className="text-sm md:col-span-2">To change a submitted proposal, cancel it and create a replacement with the current employee details. HR applies approved transfers manually when due.</p></>}
 <Field label="Reason"><Textarea required minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending||!person||(kind==='transfers'&&managerMode==='choose'&&!target.reportingManagerId)}>{kind==='probation'?'Open review':'Submit transfer for approval'}</Button></form>;
}
function IncidentForm(){
 const [form,setForm]=useState({teamId:'',title:'',location:'',occurredAt:'',category:'site_operations',severity:'medium',description:''}),save=useServiceSave(),teams=useQuery<any[]>({queryKey:['/api/people-operations/teams']});
 return <form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'people-operations/incidents',body:{...form,teamId:form.teamId?Number(form.teamId):null,occurredAt:new Date(form.occurredAt+':00+03:00').toISOString()}},{onSuccess:()=>setForm({...form,title:'',description:''})});}}><Field label="Team / activation (optional)"><select className={selectStyle} value={form.teamId} onChange={e=>setForm({...form,teamId:e.target.value})}><option value="">General / office incident</option>{teams.data?.map(t=><option key={t.id} value={t.id}>{t.name} · {label(t.kind)}</option>)}</select>{teams.error&&<p role="alert">Unable to load teams.</p>}</Field>{[['title','Incident title'],['location','Location']].map(([key,title])=><Field key={key} label={title}><Input required minLength={2} maxLength={200} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<Field label="Occurred at (Qatar time)"><Input type="datetime-local" required value={form.occurredAt} onChange={e=>setForm({...form,occurredAt:e.target.value})}/></Field><Field label="Category"><select className={selectStyle} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['equipment','service','attendance','site_operations','other'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></Field><Field label="Severity"><select className={selectStyle} value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{['low','medium','high'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="What happened and immediate action taken"><Textarea required minLength={5} maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Button disabled={save.isPending}>Report incident</Button></form>;
}
function Record({kind,row:r,manage}:{kind:Kind;row:any;manage:boolean}){
 const [reason,setReason]=useState(''),[recommendation,setRecommendation]=useState('confirm'),[due,setDue]=useState(''),[reviewer,setReviewer]=useState(''),[handler,setHandler]=useState(''),[corrective,setCorrective]=useState(r.corrective_action||''),save=useServiceSave();
 const handlers=useQuery<any[]>({queryKey:['/api/people-operations/handlers',r.team_id?{teamId:r.team_id}:{}],enabled:kind==='incidents'&&manage&&['open','in_progress'].includes(r.status)});
 const act=(action:string,extra:any={})=>save.mutate({path:`people-operations/${kind}/${r.id}/actions`,body:{version:r.version,action,reason,...extra}});
 const button=(action:string,title:string,extra:any={},disabled=false)=><Button key={action} variant="outline" disabled={save.isPending||reason.trim().length<5||disabled} onClick={()=>act(action,extra)}>{title}</Button>;
 const active=kind==='probation'?['open','submitted'].includes(r.status):kind==='transfers'?['submitted','approved'].includes(r.status):true;
 return <article className="space-y-3 rounded border p-4"><h3 className="font-semibold">{kind==='incidents'?r.title:r.employee_name} · {label(r.status)}</h3>
 {kind==='probation'&&<><p>{r.start_date} to {r.due_date} · Extensions {r.extension_count} · Policy v{r.policy_snapshot.version}</p><p>Objectives: {r.objectives}</p>{r.review_evidence&&<p>Reviewer recommends {label(r.recommendation)}: {r.review_evidence}</p>}{r.decision_reason&&<p>HR decision / instructions: {r.decision_reason}</p>}{r.acknowledged_at&&<p>Employee acknowledged receipt: {r.employee_response}</p>}</>}
 {kind==='transfers'&&<><p>Effective {r.effective_date}{r.applied_at?' · Applied '+new Date(r.applied_at).toLocaleString():r.status==='approved'?' · Awaiting HR application':''}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Field</th><th>Current at proposal</th><th>Proposed</th></tr></thead><tbody>{['department','position','location','reportingManagerId'].map(k=><tr key={k}><td>{k==='reportingManagerId'?'Manager employee ID':label(k)}</td><td>{r.from_snapshot[k]??'Unassigned'}</td><td>{r.to_snapshot[k]??'Unassigned'}</td></tr>)}</tbody></table></div><p>{r.proposal_reason}</p><p>{r.decision_reason}</p></>}
 {kind==='incidents'&&<><p>{r.team_name||'General / office'} · {r.location} · {label(r.category)} · {r.severity}</p><p>Occurred {new Date(r.occurred_at).toLocaleString('en-GB',{timeZone:'Asia/Qatar'})} Qatar · Target {new Date(r.due_at).toLocaleString('en-GB',{timeZone:'Asia/Qatar'})} Qatar{!['resolved','closed'].includes(r.status)&&Date.parse(r.due_at)<Date.now()?' · Overdue':''}</p><p>{r.description}</p>{r.corrective_action&&<p>Corrective action: {r.corrective_action}</p>}{r.resolution&&<p>Resolution: {r.resolution}</p>}</>}
 {((kind==='probation'&&(active&&(manage||r.isReviewer)||r.isMine&&!r.acknowledged_at))||(kind==='transfers'&&active&&manage)||(kind==='incidents'&&(manage||r.isHandler)))&&<Field label={kind==='probation'&&r.isMine?'Employee response (acknowledges receipt, not agreement)':'Evidence / decision reason (required for actions)'}><Textarea minLength={5} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></Field>}
 {kind==='probation'&&<>{r.isReviewer&&r.status==='open'&&<><Field label="Reviewer recommendation"><select className={selectStyle} value={recommendation} onChange={e=>setRecommendation(e.target.value)}>{['confirm','extend','follow_up'].map(v=><option value={v} key={v}>{label(v)}</option>)}</select></Field>{button('review','Submit review evidence',{recommendation})}</>}{r.canDecide&&r.status==='submitted'&&<div className="space-y-3"><div className="flex flex-wrap gap-2">{button('confirm','Confirm probation completion')}{button('follow_up','Publish HR follow-up decision')}{button('return','Return to reviewer')}</div>{r.policy_snapshot.rules.maxExtensions>r.extension_count&&r.policy_snapshot.rules.maxExtensionDays>0&&<><Field label={`Extended due date (maximum ${r.policy_snapshot.rules.maxExtensionDays} additional days)`}><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field>{button('extend','Extend review period',{dueDate:due},!due)}</>}</div>}{manage&&!r.isMine&&active&&<details><summary>Reassign or cancel review</summary><Reviewer employeeId={r.employee_id} value={reviewer} onChange={setReviewer}/><div className="mt-2 flex gap-2">{button('reassign','Reassign and reset review',{reviewerId:Number(reviewer)},!reviewer)}{button('cancel','Cancel review')}</div></details>}{r.isMine&&!r.acknowledged_at&&['confirmed','follow_up'].includes(r.status)&&button('acknowledge','Acknowledge decision receipt')}</>}
 {kind==='transfers'&&<div className="flex flex-wrap gap-2">{r.canApprove&&r.status==='submitted'&&<>{button('approve','Approve transfer')}{button('reject','Reject transfer')}</>}{r.canApply&&r.status==='approved'&&button('apply','Apply approved transfer')}{manage&&!r.isMine&&active&&button('cancel','Cancel transfer')}</div>}
 {kind==='incidents'&&<>{manage&&['open','in_progress'].includes(r.status)&&<details><summary>Assign handler / update corrective action</summary>{handlers.error&&<p role="alert">Unable to load handlers.</p>}<Field label="Handler"><select className={selectStyle} value={handler} onChange={e=>setHandler(e.target.value)}><option value="">Choose HR manager or team scheduling lead</option>{handlers.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Required corrective action"><Textarea value={corrective} onChange={e=>setCorrective(e.target.value)} minLength={5} maxLength={2000}/></Field>{button('assign','Assign corrective action',{handlerId:Number(handler),correctiveAction:corrective},!handler||corrective.trim().length<5)}</details>}<div className="flex flex-wrap gap-2">{r.isHandler&&r.status==='in_progress'&&button('resolve','Record resolution')}{r.canClose&&r.status==='resolved'&&button('close','Verify and close')}{manage&&['resolved','closed'].includes(r.status)&&button('reopen','Reopen incident')}</div></>}
 {(kind==='incidents'||manage||(kind==='probation'&&r.isReviewer))&&<History kind={kind} id={r.id}/>}</article>;
}
