import {HelpDisclosure} from '@/components/ux/WorkspaceUI';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DistributionCard} from '@/components/ux/WorkspaceUI';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Section,Table,QueryError} from '@/components/hr/Operations';
import {Input,Note,Pager,Toggle,text,number,useSave} from '@/components/hr/EmployeeServiceUI';
import type {OperationalReminderConfig,OperationalReminderPolicy} from '@shared/reminders';

const base='/api/reminder-rules';
const kinds:Record<string,string>={document_expiry:'Document expiry',training_completion:'Training deadlines',handbook_due:'Handbook acknowledgements',equipment_due:'Equipment returns',approval_reminder:'Approval queues'};
type Runtime={last_started_at:string|null;last_finished_at:string|null;policy_version:number;enabled:boolean;notifications_created:number;summary:Record<string,number>};
const time=(date:string|null)=>date?new Date(date).toLocaleString():'Not run yet';
export default function ReminderRules(){
  const query=useQuery<{policy:OperationalReminderPolicy;runtime:Runtime|null;recent:{kind:string;count:number;last_created_at:string}[]}>({queryKey:[base]}),[page,setPage]=useState(1);
  const history=useQuery<{items:{id:number;version:number;config:OperationalReminderConfig;created_by:number;reason:string;created_at:string}[];total:number}>({queryKey:[base+'/history',{offset:(page-1)*25}]});
  const save=useSave();
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold">Reminder rules</h1><p className="mt-1 text-muted-foreground">Configure in-app reminders for employee deadlines and actionable approval queues.</p></header><QueryError error={query.error}/>{query.isLoading&&<p>Loading reminder rules…</p>}
    <Tabs defaultValue="delivery"><TabsList aria-label="Reminder workspace"><TabsTrigger value="delivery">Delivery overview</TabsTrigger><TabsTrigger value="rules">Reminder rules</TabsTrigger><TabsTrigger value="history">Change history</TabsTrigger></TabsList>{query.data&&<><TabsContent value="rules" forceMount className="data-[state=inactive]:hidden"><Section title={`Operational reminder rules · Version ${query.data.policy.version}`}><form key={query.data.policy.version} className="space-y-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const config:OperationalReminderConfig={enabled:f.has('enabled'),timezone:text(f,'timezone'),notifyDocuments:f.has('notifyDocuments'),documentDays:number(f,'documentDays'),notifyTraining:f.has('notifyTraining'),trainingDays:number(f,'trainingDays'),notifyHandbooks:f.has('notifyHandbooks'),handbookDays:number(f,'handbookDays'),notifyEquipment:f.has('notifyEquipment'),equipmentDays:number(f,'equipmentDays'),notifyApprovals:f.has('notifyApprovals'),includeOverdue:f.has('includeOverdue'),repeatHours:number(f,'repeatHours'),maxPerRun:number(f,'maxPerRun')};save.mutate({url:base,body:{version:query.data!.policy.version,config,reason:text(f,'reason')}});}}>
      <Toggle label="Enable operational reminders" name="enabled" checked={query.data.policy.config.enabled}/><div className="grid gap-4 sm:grid-cols-2"><ReminderCategory title="Employee document expiry" toggle="notifyDocuments" name="documentDays" enabled={query.data.policy.config.notifyDocuments} days={query.data.policy.config.documentDays}/><ReminderCategory title="Training completion deadlines" toggle="notifyTraining" name="trainingDays" enabled={query.data.policy.config.notifyTraining} days={query.data.policy.config.trainingDays}/><ReminderCategory title="Handbook acknowledgement deadlines" toggle="notifyHandbooks" name="handbookDays" enabled={query.data.policy.config.notifyHandbooks} days={query.data.policy.config.handbookDays}/><ReminderCategory title="Equipment return deadlines" toggle="notifyEquipment" name="equipmentDays" enabled={query.data.policy.config.notifyEquipment} days={query.data.policy.config.equipmentDays}/></div>
      <div className="space-y-3"><Toggle label="Notify reviewers about their actionable approval queue" name="notifyApprovals" checked={query.data.policy.config.notifyApprovals}/><Toggle label="Continue reminders after a deadline is overdue" name="includeOverdue" checked={query.data.policy.config.includeOverdue}/></div><div className="grid gap-3 md:grid-cols-3"><Input label="Reminder time zone" name="timezone" required defaultValue={query.data.policy.config.timezone}/><Input label="Minimum hours before repeating a reminder" name="repeatHours" type="number" min={6} max={720} required defaultValue={query.data.policy.config.repeatHours}/><Input label="Maximum in-app reminders per scheduled run" name="maxPerRun" type="number" min={50} max={5000} required defaultValue={query.data.policy.config.maxPerRun}/></div>
      <HelpDisclosure title="Delivery rules"><p className="text-sm text-muted-foreground">Rules take effect on the next scheduled run. The application checks while the hosting service is awake. Reminders go to active, approved accounts; employee deadlines go to their linked account. Approval reminders respect the current reviewer and data access. Archived documents are excluded.</p></HelpDisclosure><Note label="Reason for changing reminder rules"/><Button disabled={save.isPending}>Save reminder rules</Button>
    </form></Section></TabsContent><TabsContent value="delivery"><Section title="Reminder delivery status"><div className="grid gap-3 sm:grid-cols-2 text-sm"><p>Last started: {time(query.data.runtime?.last_started_at||null)}</p><p>Last completed: {time(query.data.runtime?.last_finished_at||null)}</p><p>Rules used by last run: Version {query.data.runtime?.policy_version||0}</p><p>Reminders created by last run: {query.data.runtime?.notifications_created||0}</p></div><DistributionCard title="Last seven days" items={query.data.recent.map(r=>({label:kinds[r.kind]||r.kind,value:r.count}))}/><h3 className="font-medium text-sm">Delivery details</h3><Table headers={['Reminder','Created','Latest delivery']} rows={query.data.recent.map(r=>[kinds[r.kind]||r.kind,r.count,time(r.last_created_at)])}/><Button variant="outline" onClick={()=>void query.refetch()}>Refresh status</Button></Section></TabsContent></>}
    <TabsContent value="history"><Section title="Reminder policy history"><QueryError error={history.error}/>{history.isLoading&&<p>Loading policy history…</p>}{history.data?.items.map(h=><details key={h.id} className="rounded border p-4 text-sm"><summary className="cursor-pointer font-medium">Version {h.version} · {time(h.created_at)} · User #{h.created_by}</summary><p className="mt-3 whitespace-pre-wrap">{h.reason}</p><p className="mt-2 text-muted-foreground">{h.config.enabled?'Enabled':'Disabled'} · {h.config.timezone} · Repeat after {h.config.repeatHours} hours · Maximum {h.config.maxPerRun} per run</p><Table headers={['Reminder','Enabled','Lead days']} rows={[[kinds.document_expiry,h.config.notifyDocuments?'Yes':'No',h.config.documentDays],[kinds.training_completion,h.config.notifyTraining?'Yes':'No',h.config.trainingDays],[kinds.handbook_due,h.config.notifyHandbooks?'Yes':'No',h.config.handbookDays],[kinds.equipment_due,h.config.notifyEquipment?'Yes':'No',h.config.equipmentDays],[kinds.approval_reminder,h.config.notifyApprovals?'Yes':'No','Actionable queue']]}/><p>Overdue reminders: {h.config.includeOverdue?'Enabled':'Disabled'}</p></details>)}<Pager page={page} total={history.data?.total||0} onChange={setPage}/></Section></TabsContent></Tabs>
  </div>;
}
function ReminderCategory({title,toggle,name,enabled,days}:{title:string;toggle:string;name:string;enabled:boolean;days:number}){
  return <div className="rounded border p-4 space-y-3"><Toggle label={title} name={toggle} checked={enabled}/><Input label="Start reminding this many days before the deadline" name={name} type="number" min={0} max={365} defaultValue={days} required/></div>;
}
