import {useState,useEffect} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {OperationsReports} from '@/components/lifecycle/OperationsCenter';
import {apiJson,apiRequest} from '@/lib/queryClient';
import {reportLabels,type ReportKind,type ReportRun} from '@shared/reporting';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
const pretty=(key:string)=>key.replaceAll('_',' ');
const selectClass='block w-full border rounded p-2 bg-background';

export default function Reports(){
 const client=useQueryClient(),[kind,setKind]=useState<ReportKind>('headcount'),[department,setDepartment]=useState(''),[from,setFrom]=useState(`${new Date().getFullYear()}-01-01`),[to,setTo]=useState(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[siteId,setSiteId]=useState(''),[teamId,setTeamId]=useState(''),[page,setPage]=useState(1),[run,setRun]=useState<ReportRun|null>(null),[requestKey,setRequestKey]=useState(crypto.randomUUID());
 const catalog=useQuery<{kinds:{kind:ReportKind;label:string}[];canEditPolicy:boolean}>({queryKey:['/api/reporting/catalog']});
 const history=useQuery<{items:Omit<ReportRun,'snapshot'>[];hasMore:boolean}>({queryKey:['/api/reporting/runs',{page}]});
 const workforce=useQuery<{sites:{id:number;name:string}[];teams:{id:number;name:string;siteId:number}[]}>({queryKey:['/api/workforce/home'],enabled:kind==='workforce'&&catalog.data?.kinds.some(k=>k.kind==='workforce')});
 useEffect(()=>{if(catalog.data?.kinds.length&&!catalog.data.kinds.some(k=>k.kind===kind)){setKind(catalog.data.kinds[0].kind);setRequestKey(crypto.randomUUID());}},[catalog.data,kind]);
 const dated=['turnover','leave','workforce'].includes(kind);
 const generate=useMutation({mutationFn:()=>apiJson<ReportRun>('/api/reporting/runs','POST',{kind,requestKey,filters:{...(kind!=='workforce'?{department:department.trim()}:{}),...(dated?{from,to}:{}),...(kind==='workforce'&&siteId?{siteId:Number(siteId)}:{}),...(kind==='workforce'&&teamId?{teamId:Number(teamId)}:{})}}),onSuccess:async saved=>{setRun(saved);setRequestKey(crypto.randomUUID());setPage(1);await client.invalidateQueries({queryKey:['/api/reporting/runs']});}});
 const open=useMutation({mutationFn:(id:number)=>apiJson<ReportRun>(`/api/reporting/runs/${id}`),onSuccess:setRun});
 const download=useMutation({mutationFn:async()=>{if(!run)return;const response=await apiRequest(`/api/reporting/runs/${run.id}.csv`),url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`hr-report-${run.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
 const changed=()=>{setRequestKey(crypto.randomUUID());generate.reset();};
 return <div className="space-y-6"><Card><CardHeader><CardTitle>Saved HR reports</CardTitle><p className="text-sm text-muted-foreground">Generate a private snapshot, review its definition, then download the same saved figures.</p></CardHeader><CardContent>
 {catalog.error&&<p role="alert">{catalog.error.message}</p>}{catalog.isPending&&<p role="status">Loading report types…</p>}
 <form className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" onSubmit={e=>{e.preventDefault();generate.mutate();}}>
 <div><Label htmlFor="report-type">Report</Label><select className={selectClass} id="report-type" value={kind} disabled={generate.isPending} onChange={e=>{setKind(e.target.value as ReportKind);changed();}}>{catalog.data?.kinds.map(r=><option key={r.kind} value={r.kind}>{r.label}</option>)}</select></div>
 {kind!=='workforce'&&<div><Label htmlFor="report-department">Department (exact name, optional)</Label><Input id="report-department" value={department} onChange={e=>{setDepartment(e.target.value);changed();}} disabled={generate.isPending}/></div>}
 {dated&&<><div><Label htmlFor="report-from">From</Label><Input id="report-from" type="date" value={from} onChange={e=>{setFrom(e.target.value);changed();}} disabled={generate.isPending} required/></div><div><Label htmlFor="report-to">To (inclusive)</Label><Input id="report-to" type="date" min={from} value={to} onChange={e=>{setTo(e.target.value);changed();}} disabled={generate.isPending} required/></div></>}
 {kind==='workforce'&&<><div><Label htmlFor="report-site">Site</Label><select id="report-site" className={selectClass} value={siteId} disabled={generate.isPending} onChange={e=>{setSiteId(e.target.value);setTeamId('');changed();}}><option value="">All sites</option>{workforce.data?.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><Label htmlFor="report-team">Team</Label><select id="report-team" className={selectClass} value={teamId} disabled={generate.isPending} onChange={e=>{setTeamId(e.target.value);changed();}}><option value="">All teams</option>{workforce.data?.teams.filter(t=>!siteId||t.siteId===Number(siteId)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div></>}
 <div className="self-end"><Button disabled={generate.isPending||!catalog.data?.kinds.some(k=>k.kind===kind)}>{generate.isPending?'Generating…':'Generate snapshot'}</Button></div></form>{generate.error&&<p className="mt-3" role="alert">{generate.error.message}</p>}
 </CardContent></Card>
 {run&&<Card><CardHeader><CardTitle>{run.snapshot.title} · Run {run.id}</CardTitle><p className="text-sm">Generated {new Date(run.snapshot.generatedAt).toLocaleString()} · As of {run.snapshot.asOf} (Qatar)</p></CardHeader><CardContent className="space-y-4"><p>{run.snapshot.definition}</p><p className="text-sm">Filters: {Object.entries(run.snapshot.filters).filter(([,v])=>v!=='').map(([k,v])=>`${pretty(k)}: ${v}`).join(' · ')||'All records'}</p><div className="flex flex-wrap gap-4">{Object.entries(run.snapshot.summary).map(([key,value])=><div className="border p-3 rounded" key={key}><p className="text-sm capitalize">{pretty(key)}</p><strong>{value??'—'}</strong></div>)}</div>{Object.keys(run.snapshot.policy).length>0&&<p className="text-sm">Saved policy: {Object.entries(run.snapshot.policy).map(([k,v])=>`${pretty(k)}: ${v}`).join(' · ')}</p>}{run.snapshot.notes.map(note=><p className="text-sm text-muted-foreground" key={note}>{note}</p>)}<Button onClick={()=>download.mutate()} disabled={download.isPending}>Download saved CSV</Button>{download.error&&<p role="alert">{download.error.message}</p>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{run.snapshot.columns.map(c=><th className="p-2 text-left capitalize whitespace-nowrap" key={c.key}>{c.label}</th>)}</tr></thead><tbody>{run.snapshot.rows.map((row,i)=><tr className="border-t" key={i}>{run.snapshot.columns.map(c=><td className="p-2" key={c.key}>{row[c.key]??'—'}</td>)}</tr>)}</tbody></table></div>{run.snapshot.rows.length===0&&<p>No records match these filters.</p>}</CardContent></Card>}
 <Card><CardHeader><CardTitle>Your saved runs</CardTitle></CardHeader><CardContent className="space-y-3">{history.isPending&&<p role="status">Loading history…</p>}{history.error&&<p role="alert">{history.error.message}</p>}{open.error&&<p role="alert">{open.error.message}</p>}{history.data?.items.length===0&&<p>No saved reports yet.</p>}{history.data?.items.map(r=><div className="flex flex-wrap items-center justify-between gap-2 border-b py-2" key={r.id}><span>#{r.id} {reportLabels[r.report_type]} · {new Date(r.created_at).toLocaleString()}</span><Button variant="outline" disabled={open.isPending} onClick={()=>open.mutate(r.id)}>Open run {r.id}</Button></div>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous runs</Button><Button variant="outline" disabled={!history.data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next runs</Button></div></CardContent></Card>
 {catalog.data?.canEditPolicy&&<ReportingPolicy/>}<OperationsReports/>
 </div>;
}
function ReportingPolicy(){
 const client=useQueryClient(),[denominator,setDenominator]=useState(''),[reason,setReason]=useState(''),[page,setPage]=useState(1);
 const policy=useQuery<{version:number;turnover_denominator:string}>({queryKey:['/api/reporting/policy']});
 const history=useQuery<{items:any[];hasMore:boolean}>({queryKey:['/api/reporting/policy/history',{page}]});
 const save=useMutation({mutationFn:()=>apiJson('/api/reporting/policy','POST',{version:policy.data?.version,turnoverDenominator:denominator||policy.data?.turnover_denominator,reason}),onSuccess:async()=>{setReason('');setDenominator('');await Promise.all([client.invalidateQueries({queryKey:['/api/reporting/policy']}),client.invalidateQueries({queryKey:['/api/reporting/policy/history']})]);}});
 return <Card><CardHeader><CardTitle>Reporting policy</CardTitle></CardHeader><CardContent className="space-y-4"><p>Administrator changes apply to future snapshots. Document warning days are managed in Company Settings; leave reports use saved booking calculations.</p>{policy.error&&<p role="alert">{policy.error.message}</p>}<form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate();}}><Label htmlFor="turnover-denominator">Turnover denominator · version {policy.data?.version??'…'}</Label><select id="turnover-denominator" className={selectClass} value={denominator||policy.data?.turnover_denominator||''} onChange={e=>setDenominator(e.target.value)}><option value="average_endpoints">Average of opening and closing headcount</option><option value="opening">Opening headcount</option></select><Label htmlFor="report-policy-reason">Reason for policy change</Label><Input id="report-policy-reason" minLength={5} required value={reason} onChange={e=>setReason(e.target.value)}/><Button disabled={!policy.data||save.isPending||reason.trim().length<5}>Save reporting policy</Button>{save.error&&<p role="alert">{save.error.message}</p>}{save.isSuccess&&<p role="status">Policy saved.</p>}</form><details><summary>Policy history</summary>{history.error&&<p role="alert">{history.error.message}</p>}{history.data?.items.map(r=><p className="py-2" key={r.version}>Version {r.version} · {pretty(r.snapshot.turnover_denominator)} · {r.reason} · {new Date(r.created_at).toLocaleString()}</p>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous policy history</Button><Button variant="outline" disabled={!history.data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next policy history</Button></div></details></CardContent></Card>;
}
