import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Field, Section, Table, QueryError, fieldClass, useAction } from '@/components/hr/Operations';

const blankPolicy={documentType:'*',version:0,enabled:false,anchor:'expiry',retentionDays:0,reviewDays:7,reason:''};
export default function Retention(){
 const [tab,setTab]=useState('documents'),[view,setView]=useState('eligible'),[q,setQ]=useState(''),[offset,setOffset]=useState(0),[status,setStatus]=useState('pending'),[requestOffset,setRequestOffset]=useState(0),[holdOffset,setHoldOffset]=useState(0),[holdStatus,setHoldStatus]=useState('active');
 const [policy,setPolicy]=useState<any>(null),[dialog,setDialog]=useState<any>(null),[note,setNote]=useState(''),[employeeId,setEmployee]=useState(''),[history,setHistory]=useState<any>(null),[historyOffset,setHistoryOffset]=useState(0);
 const options=useQuery<any>({queryKey:['/api/retention/options']}),policies=useQuery<any[]>({queryKey:['/api/retention/policies'],enabled:!!options.data});
 const documents=useQuery<any>({queryKey:['/api/retention/documents',{view,q,offset}],enabled:!!options.data&&tab==='documents'}),requests=useQuery<any>({queryKey:['/api/retention/requests',{status,offset:requestOffset}],enabled:!!options.data&&tab==='requests'}),holds=useQuery<any>({queryKey:['/api/retention/holds',{active:holdStatus,offset:holdOffset}],enabled:!!options.data&&tab==='holds'});
 const trail=useQuery<any>({queryKey:[`/api/retention/history/${history?.kind}/${history?.id}`,{offset:historyOffset}],enabled:!!history});
 const action=useAction(()=>{setDialog(null);setNote('');setPolicy(null);});
 const open=(kind:string,row:any)=>{setDialog({kind,row});setNote('');};
 const showHistory=(kind:string,id:number)=>{setHistory({kind,id});setHistoryOffset(0);};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Record retention</h1><p className="text-muted-foreground">Manage retention periods, preservation holds and independently reviewed archive decisions.</p></div><QueryError error={options.error}/>
 {options.isLoading&&<p>Loading retention access…</p>}{options.data&&<>
 <nav aria-label="Retention sections" className="flex flex-wrap gap-2">{[['documents','Document queue'],['requests','Review requests'],['holds','Preservation holds'],['rules','Retention rules']].map(([id,label])=><Button key={id} variant={tab===id?'default':'outline'} onClick={()=>setTab(id)}>{label}</Button>)}</nav>
 {tab==='documents'&&<Section title="Documents"><div className="grid gap-4 md:grid-cols-2"><Field label="Queue"><select className={fieldClass} value={view} onChange={e=>{setView(e.target.value);setOffset(0);}}><option value="eligible">Eligible for archiving</option><option value="archived">Archived documents</option><option value="held">Documents on hold</option><option value="all">All scoped documents</option></select></Field><Field label="Employee or document type"><input className={fieldClass} value={q} maxLength={100} onChange={e=>{setQ(e.target.value);setOffset(0);}}/></Field></div>
 <p className="text-sm text-muted-foreground">An enabled rule determines when a document becomes eligible. Exact document-type rules take precedence over the default (*). Archived files remain available through existing access controls; restoration is required before replacement or use as checklist evidence.</p><QueryError error={documents.error}/>
 {documents.isLoading?<p>Loading documents…</p>:<Table headers={['Employee / document','Retention date','State','Action']} rows={(documents.data?.items||[]).map((r:any)=>[<>{r.employee_name}<p>{r.document_type} · #{r.id}</p></>,r.retain_until||'No applicable retention date',<>{r.archived?'Archived':'Active'}{r.held&&<p>Preservation hold</p>}{r.pending_renewal&&<p>Renewal pending</p>}{r.pending_request&&<p>Retention review pending</p>}</>,<div className="flex flex-wrap gap-2">{!r.pending_request&&(r.eligible||r.archived)&&<Button variant="outline" onClick={()=>open(r.archived?'restore':'archive',r)}>Request {r.archived?'restoration':'archive'}</Button>}<Button variant="outline" onClick={()=>open('hold',r)}>Add hold</Button><a className="text-primary underline" href={`/api/documents/${r.id}/download`} target="_blank" rel="noreferrer">Download</a></div>])}/>}
 <Button variant="outline" disabled={!offset} onClick={()=>setOffset(offset-50)}>Previous documents</Button> <Button variant="outline" disabled={!documents.data?.hasMore} onClick={()=>setOffset(offset+50)}>Next documents</Button></Section>}
 {tab==='requests'&&<Section title="Review requests"><Field label="Request status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setRequestOffset(0);}}>{['pending','approved','rejected','withdrawn','all'].map(v=><option key={v} value={v}>{v}</option>)}</select></Field><QueryError error={requests.error}/>
 {requests.isLoading?<p>Loading requests…</p>:<Table headers={['Employee / document','Request','Status / due','Action']} rows={(requests.data?.items||[]).map((r:any)=>[<>{r.employee_name}<p>{r.document_type}</p></>,<>{r.action}<p>{r.reason}</p></>,<>{r.status}<p>{String(r.review_due_date).slice(0,10)}{r.overdue?' · overdue':''}</p>{r.decision_reason&&<p>{r.decision_reason}</p>}</>,<div className="flex flex-wrap gap-2">{r.canReview&&<Button onClick={()=>open('review',r)}>Review</Button>}{r.canWithdraw&&<Button variant="outline" onClick={()=>open('withdraw',r)}>Withdraw</Button>}<Button variant="outline" onClick={()=>showHistory('retention_request',r.id)}>History</Button></div>])}/>}
 <Button variant="outline" disabled={!requestOffset} onClick={()=>setRequestOffset(requestOffset-50)}>Previous requests</Button> <Button variant="outline" disabled={!requests.data?.hasMore} onClick={()=>setRequestOffset(requestOffset+50)}>Next requests</Button></Section>}
 {tab==='holds'&&<Section title="Preservation holds"><p>A hold prevents archiving until explicitly released. Add an employee hold to cover all their documents, including later uploads.</p><div className="flex flex-wrap gap-3"><Field label="Employee for new hold"><select className={fieldClass} value={employeeId} onChange={e=>setEmployee(e.target.value)}><option value="">Choose employee</option>{options.data.employees.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Button disabled={!employeeId} onClick={()=>open('hold',{employee_id:Number(employeeId),employee_name:options.data.employees.find((r:any)=>r.id===Number(employeeId))?.name,id:null})}>Hold employee documents</Button><Field label="Hold status"><select className={fieldClass} value={holdStatus} onChange={e=>{setHoldStatus(e.target.value);setHoldOffset(0);}}><option value="active">Active</option><option value="released">Released</option><option value="all">All</option></select></Field></div><QueryError error={holds.error}/>
 <Table headers={['Employee / scope','Reason','State','Action']} rows={(holds.data?.items||[]).map((r:any)=>[<>{r.employee_name}<p>{r.document_id?`${r.document_type} · #${r.document_id}`:'All employee documents'}</p></>,<>{r.reason}{r.release_reason&&<p>Released: {r.release_reason}</p>}</>,r.active?'Active':'Released',<div className="flex gap-2">{r.active&&<Button variant="outline" onClick={()=>open('release',r)}>Release hold</Button>}<Button variant="outline" onClick={()=>showHistory('retention_hold',r.id)}>History</Button></div>])}/><Button variant="outline" disabled={!holdOffset} onClick={()=>setHoldOffset(holdOffset-50)}>Previous holds</Button> <Button variant="outline" disabled={!holds.data?.hasMore} onClick={()=>setHoldOffset(holdOffset+50)}>Next holds</Button></Section>}
 {tab==='rules'&&<Section title="Admin retention rules"><p>Set periods according to your organisation’s approved record policy. No retention rule is enabled automatically. Permanent deletion is not performed by this workflow.</p><QueryError error={policies.error}/><Table headers={['Document type','Anchor','Retain for','Review within','Status','Action']} rows={(policies.data||[]).map((p:any)=>[p.document_type==='*'?'Default (*)':p.document_type,p.anchor.replaceAll('_',' '),`${p.retention_days} days`,`${p.review_days} days`,`${p.enabled?'Enabled':'Disabled'} · v${p.version}`,options.data.canEditPolicy?<div className="flex gap-2"><Button variant="outline" onClick={()=>setPolicy({documentType:p.document_type,version:p.version,enabled:p.enabled,anchor:p.anchor,retentionDays:p.retention_days,reviewDays:p.review_days,reason:''})}>Edit</Button><Button variant="outline" onClick={()=>showHistory('retention_policy',p.id)}>History</Button></div>:null])}/>
 {options.data.canEditPolicy&&<Button variant="outline" onClick={()=>setPolicy({...blankPolicy})}>Add rule</Button>}{policy&&<form className="space-y-4 border rounded p-4" onSubmit={e=>{e.preventDefault();action.mutate({url:'/api/retention/policies',body:policy});}}><div className="grid gap-3 md:grid-cols-2"><Field label="Exact document type (* for default)"><input className={fieldClass} required maxLength={100} disabled={policy.version>0} value={policy.documentType} onChange={e=>setPolicy({...policy,documentType:e.target.value})}/></Field><Field label="Count from"><select className={fieldClass} value={policy.anchor} onChange={e=>setPolicy({...policy,anchor:e.target.value})}><option value="expiry">Document expiry date</option><option value="employment_end">Employment termination date (inactive employees)</option></select></Field><Field label="Retention days"><input className={fieldClass} type="number" required min={0} max={36500} value={policy.retentionDays} onChange={e=>setPolicy({...policy,retentionDays:Number(e.target.value)})}/></Field><Field label="Review due within days"><input className={fieldClass} type="number" required min={1} max={365} value={policy.reviewDays} onChange={e=>setPolicy({...policy,reviewDays:Number(e.target.value)})}/></Field></div><label className="block"><input type="checkbox" checked={policy.enabled} onChange={e=>setPolicy({...policy,enabled:e.target.checked})}/> Enable rule</label><Field label="Reason for this rule"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={policy.reason} onChange={e=>setPolicy({...policy,reason:e.target.value})}/></Field><Button disabled={action.isPending}>Save rule</Button> <Button type="button" variant="outline" onClick={()=>setPolicy(null)}>Cancel</Button></form>}</Section>}
 {dialog&&<Section title={dialog.kind==='review'?'Review retention request':`${dialog.kind.replaceAll('_',' ')} · ${dialog.row.employee_name}`}><form className="space-y-3" onSubmit={e=>{e.preventDefault();const d=dialog,r=d.row;action.mutate(d.kind==='hold'?{url:'/api/retention/holds',body:{employeeId:r.employee_id,documentId:r.id,reason:note}}:d.kind==='release'?{url:`/api/retention/holds/${r.id}/release`,body:{version:r.version,reason:note}}:d.kind==='review'||d.kind==='withdraw'?{url:`/api/retention/requests/${r.id}/decision`,body:{version:r.version,decision:d.kind==='review'?'approve':'withdraw',reason:note}}:{url:'/api/retention/requests',body:{documentId:r.id,action:d.kind,reason:note}});}}>
 <p>{dialog.row.document_type||'All employee documents'}{dialog.kind==='review'?` · ${dialog.row.action}`:''}</p>{dialog.kind==='review'&&<p>{dialog.row.reason}</p>}<Field label="Decision or request reason"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field><Button disabled={action.isPending}>{dialog.kind==='review'?'Approve request':'Save'}</Button> {dialog.kind==='review'&&<Button type="button" variant="outline" disabled={action.isPending||note.trim().length<5} onClick={()=>action.mutate({url:`/api/retention/requests/${dialog.row.id}/decision`,body:{version:dialog.row.version,decision:'reject',reason:note}})}>Reject request</Button>} <Button type="button" variant="outline" onClick={()=>setDialog(null)}>Close</Button></form></Section>}
 {history&&<Section title="Record history"><QueryError error={trail.error}/><Table headers={['Version','State','Reason','Recorded']} rows={(trail.data?.items||[]).map((r:any)=>[r.version,r.snapshot.status??(r.snapshot.active!==undefined?(r.snapshot.active?'Active':'Released'):(r.snapshot.enabled?'Enabled':'Disabled')),r.reason,new Date(r.created_at).toLocaleString()])}/><Button variant="outline" disabled={!historyOffset} onClick={()=>setHistoryOffset(historyOffset-25)}>Newer</Button> <Button variant="outline" disabled={!trail.data?.hasMore} onClick={()=>setHistoryOffset(historyOffset+25)}>Older</Button> <Button variant="outline" onClick={()=>setHistory(null)}>Close history</Button></Section>}
 </>}</div>;
}
