import {useEffect,useState} from 'react';
import {Link} from 'wouter';
import {useMutation,useQuery} from '@tanstack/react-query';
import {Users,RefreshCw,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {apiJson,queryClient} from '@/lib/queryClient';
import type {WorkforceHome} from '@shared/workforce';
import type {TeamOverview as Overview} from '@shared/assignmentReviews';
const selectClass='w-full rounded-md border border-input bg-background px-3 py-2 text-sm';
const stamp=(v:string,zone:string)=>new Date(v).toLocaleString([],{timeZone:zone,dateStyle:'medium',timeStyle:'short'});
export default function TeamOverview(){
  const home=useQuery<WorkforceHome>({queryKey:['/api/workforce/teams']}),leaveQueue=useQuery<any[]>({queryKey:['/api/leaves/pending']}),[teamId,setTeamId]=useState('');
  const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const valid=!!from&&!!to&&to>=from&&Date.parse(to)-Date.parse(from)<90*86400000;
  useEffect(()=>{if(home.data&&!home.data.teams.some(t=>String(t.id)===teamId))setTeamId(String(home.data.teams[0]?.id||''));},[home.data,teamId]);
  const query=useQuery<Overview>({queryKey:['/api/team-overview',{teamId,from:from+'T00:00:00Z',to:to?new Date(Date.parse(to)+86400000).toISOString():''}],enabled:!!teamId&&valid,refetchInterval:30000});
  const tasks=useQuery<any[]>({queryKey:['/api/team-tasks',{teamId}],enabled:!!teamId}),owners=useQuery<any[]>({queryKey:['/api/team-tasks/owners',{teamId}],enabled:!!teamId});
  const [taskTitle,setTaskTitle]=useState(''),[taskDueDate,setTaskDueDate]=useState(''),[taskOwner,setTaskOwner]=useState('');
  const createTask=useMutation({mutationFn:()=>apiJson('/api/team-tasks',{method:'POST',data:{teamId:Number(teamId),title:taskTitle,dueDate:taskDueDate||null,ownerUserId:taskOwner?Number(taskOwner):null}}),onSuccess:()=>{setTaskTitle('');setTaskDueDate('');setTaskOwner('');queryClient.invalidateQueries({queryKey:['/api/team-tasks']});}});
  const updateTask=useMutation({mutationFn:({id,...body}:{id:number;status?:string;ownerUserId?:number|null})=>apiJson(`/api/team-tasks/${id}`,{method:'PATCH',data:body}),onSuccess:()=>queryClient.invalidateQueries({queryKey:['/api/team-tasks']})});
  const data=query.data,zone=data?.team.timezone||'UTC';
  const approvalItems=[
    ...(data?.time?.items||[]).map(item=>({key:`time-${item.id}`,kind:'Timesheet',label:`${item.employeeName} · ${item.role}`,meta:`${Math.floor(item.workedMinutes/60)}h ${item.workedMinutes%60}m`,href:`/timesheets/${item.id}`})),
    ...(leaveQueue.data||[]).slice(0,10).map((leave:any)=>({key:`leave-${leave.id}`,kind:'Leave',label:`${leave.employee?.firstName||'Employee'} ${leave.employee?.lastName||''}`.trim(),meta:`${leave.startDate} → ${leave.endDate}`,href:`/leave?leaveId=${leave.id}`})),
    ...(data?.reviews?.missingItems||[]).map(item=>({key:`review-${item.assignmentId}`,kind:'Review',label:`${item.employeeName} · ${item.role}`,meta:stamp(item.startAt,zone),href:`/assignment-reviews?assignmentId=${item.assignmentId}`})),
  ].slice(0,12);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">People & operations</p><h1 className="mt-2 text-3xl font-semibold">Team overview</h1><p className="mt-2 text-muted-foreground">See what needs attention across staffing, time approvals and assignment reviews.</p></div><Button variant="outline" onClick={()=>{home.refetch();if(teamId&&valid)query.refetch();}}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
    {home.error?<p role="alert">Unable to load team access.</p>:home.isLoading?<p>Loading teams…</p>:!home.data?.teams.length?<Card><CardContent className="py-10"><Users className="mb-3 h-8 w-8 text-primary"/><h2 className="font-semibold">No team access assigned</h2><p className="mt-2 text-muted-foreground">HR can grant dated access in Workforce. Your own records remain in Timesheets and Assignment reviews.</p><Link href="/workforce" className="mt-4 inline-block text-primary">Open Workforce</Link></CardContent></Card>:<>
      <div className="grid gap-3 md:grid-cols-[2fr_1fr_1fr]"><label className="grid gap-1.5 text-sm font-medium">Team<select className={selectClass} value={teamId} onChange={e=>setTeamId(e.target.value)}>{home.data.teams.map(t=><option key={t.id} value={t.id}>{t.name} · {t.siteName}</option>)}</select></label><label className="grid gap-1.5 text-sm font-medium">Work date from (UTC)<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="grid gap-1.5 text-sm font-medium">Through (UTC)<Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>
      {!valid?<p role="alert">Choose a date range of up to 90 days.</p>:query.isLoading?<p>Loading team overview…</p>:query.error?<p role="alert">This team is unavailable or your access has expired. Refresh access.</p>:data&&<>
        <Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><CardTitle>Staffing now and over the next 14 days</CardTitle><Link href={`/workforce?teamId=${teamId}`} className="inline-flex items-center text-sm text-primary">Manage roster<ArrowRight className="ml-2 h-4 w-4"/></Link></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['Live & upcoming shifts',data.staffing.shifts],['Accepted / required',`${data.staffing.accepted} / ${data.staffing.required}`],['Unfilled places',data.staffing.unfilled],['Offers awaiting reply',data.staffing.pendingOffers]].map(([label,value])=><div key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>)}</div><p className="text-sm text-muted-foreground">Coverage uses accepted assignments through {stamp(data.staffingThrough,zone)}. Offers do not reserve places. This staffing window is independent of the historical date filter.</p>{data.staffing.gaps.length>0&&<div className="divide-y border-t">{data.staffing.gaps.map(s=><div className="flex flex-wrap justify-between gap-2 py-3 text-sm" key={s.id}><span>{s.role} · {stamp(s.startAt,zone)}</span><span className="font-medium">{s.unfilled} place{s.unfilled===1?'':'s'} unfilled</span></div>)}</div>}</CardContent></Card>
        <div className="grid items-start gap-5 xl:grid-cols-3"><Card><CardHeader><CardTitle>Time awaiting approval</CardTitle></CardHeader><CardContent>{data.time?<><p className="text-3xl font-semibold">{data.time.pending}</p><p className="mt-2 text-sm text-muted-foreground">Submitted timesheets in the selected work dates, covered by your review permission.</p><div className="mt-3 divide-y">{data.time.items.map(t=><Link key={t.id} href={`/timesheets/${t.id}`} className="flex flex-wrap justify-between gap-2 py-3 text-sm text-primary"><span>{t.employeeName} · {t.role}</span><span>{Math.floor(t.workedMinutes/60)}h {t.workedMinutes%60}m</span></Link>)}</div>{data.time.pending>10&&<Link href="/timesheets" className="text-sm text-primary">View all timesheets</Link>}</>:<p className="text-sm text-muted-foreground">A separate Review timesheets grant is required to see this queue.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Leave awaiting approval</CardTitle></CardHeader><CardContent>{leaveQueue.error?<p className="text-sm text-muted-foreground">Leave approval access is not assigned.</p>:leaveQueue.isLoading?<p>Loading leave requests…</p>:<><p className="text-3xl font-semibold">{leaveQueue.data?.length||0}</p><p className="mt-2 text-sm text-muted-foreground">Pending requests within your current team or HR scope.</p><div className="mt-3 divide-y">{(leaveQueue.data||[]).slice(0,5).map((leave:any)=><Link key={leave.id} href={`/leave?leaveId=${leave.id}`} className="block py-3 text-sm text-primary">{leave.employee?.firstName} {leave.employee?.lastName}<span className="mt-1 block text-xs text-muted-foreground">{leave.startDate} → {leave.endDate} · {leave.leaveType?.name||leave.leaveType}</span></Link>)}</div>{(leaveQueue.data?.length||0)>5&&<Link href="/leave" className="text-sm text-primary">View all leave requests</Link>}</>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Assignments missing a review</CardTitle></CardHeader><CardContent>{data.reviews?<><p className="text-3xl font-semibold">{data.reviews.missing}</p><p className="mt-2 text-sm text-muted-foreground">Completed assignments with approved time and no review in the selected work dates.</p><div className="mt-3 divide-y">{data.reviews.missingItems.map(a=><Link key={a.assignmentId} href={`/assignment-reviews?assignmentId=${a.assignmentId}`} className="block py-3 text-sm text-primary">{a.employeeName} · {a.role}<span className="mt-1 block text-xs text-muted-foreground">{stamp(a.startAt,zone)}</span></Link>)}</div>{data.reviews.missing>10&&<Link href="/assignment-reviews" className="text-sm text-primary">View all review assignments</Link>}</>:<p className="text-sm text-muted-foreground">A separate Review performance grant is required to see this queue.</p>}</CardContent></Card></div>
        <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Unified approval queue</CardTitle><p className="mt-1 text-sm font-normal text-muted-foreground">One queue for time, leave and assignment actions in this team and date range.</p></div><div className="text-sm text-muted-foreground">{approvalItems.length} shown</div></div></CardHeader><CardContent>{!approvalItems.length?<p className="py-4 text-sm text-muted-foreground">Nothing is waiting for your action.</p>:<div className="divide-y rounded-md border">{approvalItems.map(item=><Link key={item.key} href={item.href} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm hover:bg-muted/40"><span><span className="mr-3 inline-flex rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">{item.kind}</span>{item.label}</span><span className="text-muted-foreground">{item.meta}</span></Link>)}</div>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Absence coverage</CardTitle><p className="text-sm font-normal text-muted-foreground">Approved leave overlapping accepted shifts in the next 14 days.</p></CardHeader><CardContent>{!data.staffing.absences.length?<p className="py-4 text-sm text-muted-foreground">No approved absences overlap upcoming accepted shifts.</p>:<div className="divide-y rounded-md border">{data.staffing.absences.map(absence=><Link key={`${absence.leaveId}-${absence.shiftId}`} href={`/workforce?teamId=${teamId}`} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm hover:bg-muted/40"><span><span className="mr-3 inline-flex rounded-full bg-amber-500/10 px-2 py-0.5 text-xs font-medium text-amber-700">{absence.leaveType}</span>{absence.employeeName} · {absence.role}</span><span className="text-muted-foreground">{absence.startDate} → {absence.endDate}</span></Link>)}</div>}{data.staffing.absences.length>=50&&<p className="mt-3 text-xs text-muted-foreground">Showing the first 50 overlapping assignments.</p>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Team tasks and ownership</CardTitle><p className="text-sm font-normal text-muted-foreground">Assign follow-ups from this dashboard and track their status.</p></CardHeader><CardContent className="space-y-4"><form className="grid gap-3 md:grid-cols-[2fr_1fr_1fr_auto]" onSubmit={e=>{e.preventDefault();if(taskTitle.trim())createTask.mutate();}}><Input placeholder="Task title" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} required/><select className={selectClass} value={taskOwner} onChange={e=>setTaskOwner(e.target.value)}><option value="">Assign owner…</option>{(owners.data||[]).map(owner=><option key={owner.id} value={owner.id}>{owner.name} · {owner.role}</option>)}</select><Input type="date" value={taskDueDate} onChange={e=>setTaskDueDate(e.target.value)} aria-label="Due date"/><Button disabled={createTask.isPending}>Add task</Button></form>{tasks.isLoading?<p className="text-sm text-muted-foreground">Loading tasks…</p>:!tasks.data?.length?<p className="text-sm text-muted-foreground">No follow-up tasks for this team.</p>:<div className="divide-y rounded-md border">{tasks.data.map(task=><div key={task.id} className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 text-sm"><span><span className="font-medium">{task.title}</span><span className="ml-3 text-xs text-muted-foreground">{task.ownerName?`Owner: ${task.ownerName}`:'Unassigned'}{task.dueDate?` · Due ${task.dueDate}`:''}</span></span><div className="flex items-center gap-2"><select className="rounded border bg-background px-2 py-1 text-xs" value={task.status} onChange={e=>updateTask.mutate({id:task.id,status:e.target.value})}><option value="open">Open</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select>{task.ownerUserId?null:<Button size="sm" variant="outline" onClick={()=>updateTask.mutate({id:task.id,ownerUserId:owners.data?.[0]?.id||null})}>Assign</Button>}</div></div>)}</div>}</CardContent></Card>
        {data.reviews&&<Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><CardTitle>Performance trends</CardTitle><Link href="/assignment-reviews" className="text-sm text-primary">Open assignment reviews</Link></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{[['Included reviews',data.reviews.included],['Awaiting response',data.reviews.awaitingResponse],['Disputed',data.reviews.disputed],['Withdrawn',data.reviews.withdrawn],['Time approval changed',data.reviews.unverified]].map(([label,value])=><div key={label}><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><p className="text-sm text-muted-foreground">Descriptive averages out of 5 for current, undisputed reviews with approved time. N/A ratings, disputed/withdrawn reviews and records whose time approval changed are excluded. Counts are shown per criterion. Role-specific skills stay on individual reviews because expectations vary by role.</p>{!data.reviews.trend.length?<p className="py-5 text-muted-foreground">No eligible ratings for these work dates yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Monthly ratings under rubric version 1, grouped by work date in UTC</caption><thead><tr className="border-b text-left"><th className="p-3">Work month (UTC)</th><th className="p-3">Reviews</th><th className="p-3">Punctuality</th><th className="p-3">Service</th><th className="p-3">Teamwork</th></tr></thead><tbody>{data.reviews.trend.map(t=><tr key={t.month} className="border-b"><td className="p-3">{t.month}</td><td className="p-3">{t.reviews}</td>{(['punctuality','service','teamwork'] as const).map(k=><td key={k} className="p-3">{t[k]===null?'No ratings':`${t[k]!.toFixed(2)} (${t[`${k}Count`]} ratings)`}</td>)}</tr>)}</tbody></table></div>}</CardContent></Card>}
      </>}
    </>}
  </div>;
}
