import {calculateTime,defaultCalculationRules} from '@shared/calculation-rules';
import TimesheetAttendanceReview from '@/components/hr/TimesheetAttendanceReview';
import {useState,type ReactNode,type FormEvent} from 'react';
import {Link,useLocation,useRoute} from 'wouter';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {ArrowLeft,Clock3,Plus,RefreshCw,LockKeyhole} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardHeader,CardContent,CardTitle} from '@/components/ui/card';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {apiJson} from '@/lib/queryClient';
import {siteTimeToIso} from '@shared/workforce';
import {timesheetLabels,timesheetStatuses,type TimeAssignment,type TimesheetConfig,type TimesheetList,type TimesheetDetail,type TimesheetRow,type PayrollTimeOption} from '@shared/timesheets';

const selectClass='w-full rounded-md border border-input bg-background px-3 py-2 text-sm';
const duration=(minutes:number)=>`${Math.floor(minutes/60)}h ${minutes%60}m`;
const stamp=(value:string,zone:string)=>new Date(value).toLocaleString([],{timeZone:zone,dateStyle:'medium',timeStyle:'short'});
function wall(value:string,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>;}
function useTimeMutation(){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({url,body,method='POST'}:{url:string;body:unknown;method?:string})=>apiJson<{id:number;version:number}>(url,{method,body}),
  onSuccess:async()=>{await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/timesheets')});},onError:async(error)=>{toast({title:'Unable to save',description:error.message,variant:'destructive'});if(error.message.startsWith('409:'))await cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith('/api/timesheets')});}});}
export default function Timesheets(){
  const [,params]=useRoute('/timesheets/:id'),id=params?Number(params.id):null;
  const config=useQuery<TimesheetConfig>({queryKey:['/api/timesheets/config']}),[view,setView]=useState('mine'),[status,setStatus]=useState(''),[page,setPage]=useState(1),[create,setCreate]=useState(false);
  const [from,setFrom]=useState(()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10)),[to,setTo]=useState(()=>new Date().toISOString().slice(0,10));
  const valid=!!from&&!!to&&to>=from&&Date.parse(to)-Date.parse(from)<90*86400000;
  const range={from:from?from+'T00:00:00.000Z':'',to:to?new Date(Date.parse(to)+86400000).toISOString():''};
  const list=useQuery<TimesheetList>({queryKey:['/api/timesheets/',{...range,view,status,page}],enabled:!id&&valid,refetchInterval:30000});
  if(config.isLoading)return <p>Loading timesheets…</p>;
  if(config.error||!config.data)return <p role="alert">Unable to load timesheets. Please refresh.</p>;
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Workforce time</p><h1 className="mt-2 text-3xl font-semibold">Timesheets</h1><p className="mt-2 text-muted-foreground">Report completed work, review hours and track payroll inclusion.</p></div><Button onClick={()=>setCreate(true)} disabled={!valid}><Plus className="mr-2 h-4 w-4"/>Report time</Button></div>
    {id?<SheetPanel id={id} key={id}/>:<><div className="grid items-end gap-3 md:grid-cols-2 xl:grid-cols-5"><Field label="View"><select className={selectClass} value={view} onChange={e=>{setView(e.target.value);setPage(1);}}><option value="mine">My timesheets</option>{config.data.canReview&&<option value="review">Team review</option>}{config.data.canPayrollRead&&<option value="payroll">Payroll approved time</option>}</select></Field><Field label="Status"><select className={selectClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{timesheetStatuses.filter(s=>view==='mine'||(view==='review'?s!=='draft':['approved','payroll_locked'].includes(s))).map(s=><option key={s} value={s}>{timesheetLabels[s]}</option>)}</select></Field><Field label="Shift start from (UTC)"><Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></Field><Field label="Through (UTC)"><Input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></Field><Button variant="outline" onClick={()=>list.refetch()} disabled={!valid}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
      {!valid?<p role="alert">Choose a date range of up to 90 days.</p>:list.isLoading?<p>Loading timesheets…</p>:list.error?<p role="alert">Unable to load timesheets. Please refresh.</p>:<Card><CardContent className="py-2">{!list.data?.items.length?<div className="py-10"><Clock3 className="mb-3 h-8 w-8 text-primary"/><h2 className="font-semibold">No timesheets in this view</h2><p className="mt-2 text-muted-foreground">Report time for a completed, accepted assignment or adjust the filters.</p></div>:<div className="divide-y">{list.data.items.map(row=><Link key={row.id} href={`/timesheets/${row.id}`} className="block rounded-md py-4 hover:bg-muted/40"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{row.employeeName} · {row.role}</p><p className="mt-1 text-sm text-muted-foreground">{row.teamName} · {row.siteName}</p></div><Badge className="self-start" variant={row.status==='returned'?'destructive':'secondary'}>{timesheetLabels[row.status]}</Badge></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-sm"><p>{stamp(row.actualStartAt,row.timezone)} · {row.timezone}</p><p>Worked {duration(row.workedMinutes)}{row.payableMinutes!==null&&` · Payable ${duration(row.payableMinutes)}`}</p></div></Link>)}</div>}</CardContent></Card>}
      {valid&&list.data&&<div className="flex flex-wrap items-center justify-between gap-3 text-sm"><p>{list.data.total} timesheets · Page {page}</p><div className="flex gap-2"><Button variant="outline" disabled={page===1||list.isFetching} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={page*25>=list.data.total||list.isFetching} onClick={()=>setPage(page+1)}>Next</Button></div></div>}
    </>}
    <NewTimesheet open={create} close={()=>setCreate(false)} range={range}/>
  </div>;
}
function ActualForm({assignment,sheet,close,done}:{assignment:TimeAssignment;sheet?:TimesheetRow;close?:()=>void;done:(id:number)=>void}){
  const [start,setStart]=useState(sheet?wall(sheet.actualStartAt,sheet.timezone):''),[end,setEnd]=useState(sheet?wall(sheet.actualEndAt,sheet.timezone):''),[breaks,setBreaks]=useState(String(sheet?.breakMinutes??0)),[note,setNote]=useState(sheet?.employeeNote||''),[confirmed,setConfirmed]=useState(false);
  const mutation=useTimeMutation(),{toast}=useToast();
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const submit=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='submit';
    try{const actuals={actualStartAt:siteTimeToIso(start,assignment.timezone),actualEndAt:siteTimeToIso(end,assignment.timezone),breakMinutes:Number(breaks),employeeNote:note};
      if(submit&&!confirmed)throw new Error('Confirm that these are your actual hours before submitting');
      const saved=await mutation.mutateAsync({url:sheet?`/api/timesheets/${sheet.id}`:'/api/timesheets/',method:sheet?'PATCH':'POST',body:sheet?{...actuals,version:sheet.version}:{...actuals,assignmentId:assignment.assignmentId}});
      if(submit)try{await mutation.mutateAsync({url:`/api/timesheets/${saved.id}/submit`,body:{version:saved.version}});}catch(error){done(saved.id);throw error;}
      toast({title:submit?'Time submitted for review':'Draft saved'});done(saved.id);
    }catch(error){if(!(error instanceof Error&&/^\d{3}:/.test(error.message)))toast({title:'Check reported time',description:(error as Error).message,variant:'destructive'});}}
  return <form className="space-y-4" onSubmit={save}><div className="rounded-md bg-muted p-3 text-sm"><p className="font-medium">{assignment.role} · {assignment.teamName}</p><p className="mt-1">Scheduled: {stamp(assignment.startAt,assignment.timezone)} → {stamp(assignment.endAt,assignment.timezone)}</p><p className="mt-1">Enter actual times in {assignment.timezone}. Scheduled break: {assignment.plannedBreakMinutes} minutes.</p></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Actual start"><Input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/></Field><Field label="Actual finish"><Input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} required/></Field></div><Field label="Total break minutes"><Input type="number" min={0} max={1439} step={1} value={breaks} onChange={e=>setBreaks(e.target.value)} required/></Field><Field label="Work notes (optional)"><Textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="Explain overtime, late arrival or other changes."/></Field><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these are my actual completed hours and breaks.</label><div className="flex flex-wrap gap-2">{close&&<Button type="button" variant="outline" onClick={close} disabled={mutation.isPending}>Close</Button>}<Button type="submit" value="draft" variant="outline" disabled={mutation.isPending}>Save draft</Button><Button type="submit" value="submit" disabled={mutation.isPending||!confirmed}>{mutation.isPending?'Saving…':'Submit for review'}</Button></div></form>;
}
function NewTimesheet({open,close,range}:{open:boolean;close:()=>void;range:{from:string;to:string}}){
  const [,navigate]=useLocation(),[page,setPage]=useState(1),[selected,setSelected]=useState<TimeAssignment|null>(null);
  const available=useQuery<{items:TimeAssignment[];hasMore:boolean}>({queryKey:['/api/timesheets/assignments',{...range,page}],enabled:open&&!selected});
  return <Dialog open={open} onOpenChange={v=>{if(!v){close();setSelected(null);setPage(1);}}}><DialogContent className="max-h-[90vh] overflow-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Report completed work</DialogTitle><DialogDescription>Choose an accepted assignment within the date filter. Each assignment has one timesheet.</DialogDescription></DialogHeader>{selected?<ActualForm assignment={selected} close={()=>setSelected(null)} done={id=>{setSelected(null);close();navigate(`/timesheets/${id}`);}}/>:<div className="space-y-3">{available.isLoading?<p>Loading assignments…</p>:available.error?<p role="alert">Unable to load assignments.</p>:!available.data?.items.length?<p>No completed assignments without a timesheet in this date range.</p>:available.data.items.map(a=><button key={a.assignmentId} className="block w-full rounded-md border p-4 text-left hover:bg-muted" onClick={()=>setSelected(a)}><p className="font-medium">{a.role} · {a.teamName}</p><p className="mt-1 text-sm text-muted-foreground">{stamp(a.startAt,a.timezone)} · {a.siteName}</p></button>)}<div className="flex gap-2"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button variant="outline" disabled={!available.data?.hasMore} onClick={()=>setPage(page+1)}>More assignments</Button></div></div>}</DialogContent></Dialog>;
}
function SheetPanel({id}:{id:number}){
  const query=useQuery<TimesheetDetail>({queryKey:[`/api/timesheets/${id}`]});
  if(query.isLoading)return <p>Loading timesheet…</p>;
  if(query.error||!query.data)return <div role="alert"><p>This timesheet is unavailable or outside your current access.</p><Link href="/timesheets" className="text-primary">Back to timesheets</Link></div>;
  const {sheet:row,capabilities:access,history}=query.data;
  return <div className="space-y-5"><Link href="/timesheets" className="inline-flex items-center text-sm text-primary"><ArrowLeft className="mr-2 h-4 w-4"/>Back to timesheets</Link><Card><CardContent className="pt-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-muted-foreground">Timesheet #{row.id} · Version {row.version}</p><h2 className="mt-2 text-2xl font-semibold">{row.employeeName} · {row.role}</h2><p className="mt-2 text-muted-foreground">{row.teamName} · {row.siteName} · {row.timezone}</p></div><Badge className="self-start">{timesheetLabels[row.status]}</Badge></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-sm text-muted-foreground">Reported actual time</p><p className="mt-1 font-medium">{stamp(row.actualStartAt,row.timezone)} → {stamp(row.actualEndAt,row.timezone)}</p></div><div><p className="text-sm text-muted-foreground">Worked / breaks</p><p className="mt-1 font-medium">{duration(row.workedMinutes)} / {row.breakMinutes}m</p></div><div><p className="text-sm text-muted-foreground">Approved payable time</p><p className="mt-1 font-medium">{row.payableMinutes===null?'Awaiting approval':duration(row.payableMinutes)}</p>{row.policyReference&&<p className="mt-1 text-sm">Policy: {row.policyReference}</p>}</div></div>{row.employeeNote&&<p className="mt-4 whitespace-pre-wrap break-words text-sm">Work notes: {row.employeeNote}</p>}{row.reviewNote&&<p className="mt-4 rounded-md bg-muted p-3 text-sm">Review: {row.reviewNote}</p>}{row.payrollId&&<p className="mt-4 flex items-center gap-2 text-sm"><LockKeyhole className="h-4 w-4"/>Linked to payroll #{row.payrollId}. This record is locked.</p>}</CardContent></Card>
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]"><div className="space-y-5">{access.edit&&<Card><CardHeader><CardTitle>{row.status==='returned'?'Correct reported time':'Reported hours'}</CardTitle></CardHeader><CardContent><ActualForm assignment={row} sheet={row} done={()=>query.refetch()}/></CardContent></Card>}{access.review&&<><TimesheetAttendanceReview row={row}/><ReviewPanel row={row}/></>} {access.reopen&&<ReopenPanel row={row}/>} {access.payrollLock&&<PayrollPanel row={row}/>}
      {!access.edit&&<p className="text-sm text-muted-foreground">For a correction, <Link href="/helpdesk" className="text-primary underline">contact HR through the helpdesk</Link>. Approved records require an HR return before editing; payroll-linked records require a separate adjustment.</p>}
    </div><Card><CardHeader><CardTitle>Revision history</CardTitle></CardHeader><CardContent className="space-y-4">{!history.length&&<p className="text-sm text-muted-foreground">Earlier drafts are available to the employee and authorized HR or team reviewers.</p>}{history.map(h=><details key={h.id} className="rounded-md border p-3"><summary className="cursor-pointer text-sm font-medium">v{h.version} · {h.action} · {h.actorName}</summary><p className="mt-2 text-xs text-muted-foreground">{stamp(h.createdAt,row.timezone)}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm">{h.reason}</p><p className="mt-2 text-sm">{stamp(h.snapshot.actualStartAt,row.timezone)} → {stamp(h.snapshot.actualEndAt,row.timezone)}</p><p className="mt-1 text-sm">Worked {duration(h.snapshot.workedMinutes)} · Breaks {h.snapshot.breakMinutes}m{h.snapshot.payableMinutes!==null&&` · Payable ${duration(h.snapshot.payableMinutes)}`}</p>{h.snapshot.policyReference&&<p className="mt-1 text-sm">Policy: {h.snapshot.policyReference}</p>}{h.snapshot.employeeNote&&<p className="mt-2 whitespace-pre-wrap break-words text-sm">{h.snapshot.employeeNote}</p>}</details>)}</CardContent></Card></div>
  </div>;
}
function ReviewPanel({row}:{row:TimesheetRow}){
  const rule=row.calculationSnapshot?.rules.timesheets||defaultCalculationRules.timesheets,calculated=rule.payableMethod==='calculated';
  const suggestion=calculateTime(row.workedMinutes+row.breakMinutes,row.breakMinutes,rule).calculatedMinutes;
  const [decision,setDecision]=useState('approved'),[minutes,setMinutes]=useState(String(calculated?suggestion:Math.min(row.workedMinutes+row.breakMinutes,suggestion))),[policy,setPolicy]=useState(row.calculationSnapshot?.version?`Calculation rules v${row.calculationSnapshot.version}`:''),[reason,setReason]=useState('');const mutation=useTimeMutation();
  return <Card><CardHeader><CardTitle>Review reported time</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/timesheets/${row.id}/review`,body:{version:row.version,decision,reason,...(decision==='approved'?{payableMinutes:calculated?suggestion:Number(minutes),policyReference:calculated?`Calculation rules v${row.calculationSnapshot?.version||0}`:policy}:{})}});}catch{}}}><Field label="Decision"><select className={selectClass} value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Approve payable time</option><option value="returned">Return to employee for correction</option></select></Field>{decision==='approved'&&<><Field label="Payable minutes"><Input type="number" min={0} max={calculated?1440:row.workedMinutes+row.breakMinutes} readOnly={calculated} step={1} value={calculated?suggestion:minutes} onChange={e=>setMinutes(e.target.value)} required/></Field><Field label="Policy or agreement reference"><Input readOnly={calculated} value={calculated?`Calculation rules v${row.calculationSnapshot?.version||0}`:policy} onChange={e=>setPolicy(e.target.value)} minLength={3} maxLength={120} placeholder="Company policy or agreed paid-break rule" required/></Field><p className="text-sm text-muted-foreground">{calculated?`Payable time follows the saved calculation rules: ${suggestion} minutes.`:`Suggested payable time: ${suggestion} minutes. Confirm minutes under the applicable agreement, including paid breaks.`} Overtime rates and payment amounts are handled in payroll.</p></>}<Field label="Reason visible to employee"><Textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} required/></Field><Button type="submit" disabled={mutation.isPending}>Save review</Button></form></CardContent></Card>;
}
function ReopenPanel({row}:{row:TimesheetRow}){const [reason,setReason]=useState('');const mutation=useTimeMutation();return <Card><CardHeader><CardTitle>Request correction</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/timesheets/${row.id}/reopen`,body:{version:row.version,reason}});}catch{}}}><p className="text-sm text-muted-foreground">Returning this timesheet removes its current approval. The earlier approved hours remain in revision history.</p><Field label="Correction reason"><Textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={2000} required/></Field><Button variant="outline" disabled={mutation.isPending}>Return approved time</Button></form></CardContent></Card>;}
function PayrollPanel({row}:{row:TimesheetRow}){const query=useQuery<PayrollTimeOption[]>({queryKey:[`/api/timesheets/${row.id}/payroll-options`]}),[payrollId,setPayrollId]=useState(''),[confirmed,setConfirmed]=useState(false),mutation=useTimeMutation();return <Card><CardHeader><CardTitle>Confirm payroll inclusion</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={async e=>{e.preventDefault();try{await mutation.mutateAsync({url:`/api/timesheets/${row.id}/payroll-lock`,body:{version:row.version,payrollId:Number(payrollId),confirmed}});}catch{}}}><p className="text-sm text-muted-foreground">Select the processed payroll that already includes these approved hours. Linking locks the timesheet; it does not calculate pay or send money.</p>{query.error?<p role="alert">Unable to load payroll records.</p>:<Field label="Processed payroll"><select className={selectClass} value={payrollId} onChange={e=>setPayrollId(e.target.value)} required><option value="">Choose payroll…</option>{query.data?.map(p=><option key={p.id} value={p.id}>#{p.id} · {p.month}/{p.year} · {p.reference||'No reference'}</option>)}</select></Field>}{query.data?.length===0&&<p className="text-sm">No processed payroll for this employee yet.</p>}<label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>I verified that this payroll includes the approved payable time.</label><Button disabled={mutation.isPending||!confirmed||!payrollId}>Link and lock timesheet</Button></form></CardContent></Card>;}
