import {Router} from 'express';
import {z} from 'zod';
import {sql,eq} from 'drizzle-orm';
import {db} from '../db';
import {employees,employeeLifecycleEvents} from '@shared/schema';
import {civilDate} from '@shared/calculation-rules';
import {authenticate} from '../middleware/auth';
import {OnboardingError} from '../services/onboarding-workflow';
import {blockingExits,exitTemplateSchema} from '../services/employmentContinuity';
import {recordId as id,decisionReason as reason,shortText,isAdmin,managesRecords,requireManager,requireAdmin,recordHandler as handle,recordHistory as history,qatarToday} from '../services/workplaceRecords';
const router=Router();router.use(authenticate);router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
const fail=(status:number,message:string):never=>{throw new OnboardingError(status,message);};
const pageOf=(req:any)=>z.coerce.number().int().min(1).max(10000).default(1).parse(req.query.page);
async function policy(tx:any){const r=await tx.execute(sql`SELECT * FROM employment_watch_policies ORDER BY version DESC LIMIT 1`);return r.rows[0]||{id:0,version:0,watch_days:30};}
async function employee(tx:any,employeeId:number,req:any){const r=await tx.execute(sql`SELECT id,user_id,employee_id,first_name,last_name,type,status,joining_date,contract_end_date,termination_date,record_version FROM employees WHERE id=${employeeId} FOR UPDATE`);const e=r.rows[0] as any;if(!e)fail(404,'Employee not found');if(e.user_id===req.user.userId)fail(403,'Another HR manager must handle your employment record');return e;}
function renewable(e:any){if(!['active','on_leave'].includes(e.status)||e.termination_date||!e.contract_end_date)fail(400,'Renewals require a current employee with an existing contract end date and no recorded termination');}
router.get('/config',handle(async(req,res)=>res.json({canManage:managesRecords(req),canConfigure:isAdmin(req),policy:await policy(db)})));
router.post('/policy',handle(async(req,res)=>{requireAdmin(req);const input=z.object({version:z.number().int().min(0),watchDays:z.number().int().min(1).max(365),reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{await tx.execute(sql`LOCK TABLE employment_watch_policies IN SHARE ROW EXCLUSIVE MODE`);const old=await policy(tx);if(old.version!==input.version)fail(409,'Policy changed; reload');const r=await tx.execute(sql`INSERT INTO employment_watch_policies(version,watch_days,created_by) VALUES (${old.version+1},${input.watchDays},${req.user.userId}) RETURNING *`);await history(tx,req,'employment_watch_policy',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.get('/policy-history',handle(async(req,res)=>{requireAdmin(req);const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind='employment_watch_policy' ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
router.get('/people',handle(async(req,res)=>{requireManager(req);const q=z.string().trim().min(2).max(100).parse(req.query.q);const r=await db.execute(sql`SELECT id,employee_id,first_name||' '||last_name AS name,type,status,joining_date,contract_end_date,record_version FROM employees WHERE status IN ('active','on_leave') AND strpos(lower(first_name||' '||last_name||' '||employee_id),lower(${q}))>0 ORDER BY id LIMIT 25`);res.json(r.rows);}));
router.get('/expiring',handle(async(req,res)=>{requireManager(req);const page=pageOf(req),p=await policy(db);const r=await db.execute(sql`SELECT e.id,e.employee_id,e.first_name||' '||e.last_name AS name,e.type,e.contract_end_date,e.record_version,(e.contract_end_date-${qatarToday()}::date)::int AS days_remaining,(SELECT r.status FROM contract_renewals r WHERE r.employee_id=e.id AND r.status IN ('submitted','approved')) AS renewal_status FROM employees e WHERE e.status IN ('active','on_leave') AND e.termination_date IS NULL AND e.contract_end_date<=${qatarToday()}::date+${p.watch_days}::int ORDER BY e.contract_end_date,e.id LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows,watchDays:p.watch_days});}));
router.get('/exit-templates',handle(async(req,res)=>{requireManager(req);const r=await db.execute(sql`SELECT * FROM exit_checklist_templates ORDER BY enabled DESC,name,id LIMIT 25 OFFSET ${(pageOf(req)-1)*25}`);res.json({items:r.rows});}));
router.post('/exit-templates',handle(async(req,res)=>{requireAdmin(req);const input=exitTemplateSchema.extend({reason}).parse(req.body);const saved=await db.transaction(async tx=>{const r=await tx.execute(sql`INSERT INTO exit_checklist_templates(name,employee_types,enabled,tasks,created_by,updated_by) VALUES (${input.name},${JSON.stringify(input.employeeTypes)}::jsonb,${input.enabled},${JSON.stringify(input.tasks)}::jsonb,${req.user.userId},${req.user.userId}) RETURNING *`);await history(tx,req,'exit_template',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.post('/exit-templates/:id',handle(async(req,res)=>{requireAdmin(req);const templateId=id.parse(Number(req.params.id)),input=exitTemplateSchema.extend({version:id,reason}).parse(req.body);const saved=await db.transaction(async tx=>{const rows=await tx.execute(sql`SELECT * FROM exit_checklist_templates WHERE id=${templateId} FOR UPDATE`);const old=rows.rows[0] as any;if(!old)fail(404,'Template not found');if(old.version!==input.version)fail(409,'Template changed; reload');const r=await tx.execute(sql`UPDATE exit_checklist_templates SET name=${input.name},employee_types=${JSON.stringify(input.employeeTypes)}::jsonb,enabled=${input.enabled},tasks=${JSON.stringify(input.tasks)}::jsonb,version=version+1,updated_by=${req.user.userId} WHERE id=${templateId} RETURNING *`);await history(tx,req,'exit_template',r.rows[0],input.reason);return r.rows[0];});res.json(saved);}));
router.get('/clearance-exits/:employeeId',handle(async(req,res)=>{requireManager(req);const employeeId=id.parse(Number(req.params.employeeId));res.json(await blockingExits(db,employeeId,qatarToday()));}));
const kindSchema=z.enum(['renewals','clearances']);
const tables={renewals:'contract_renewals',clearances:'return_work_clearances'};
const historyKinds={renewals:'contract_renewal',clearances:'return_work_clearance'};
router.get('/:kind',handle(async(req,res)=>{const kind=kindSchema.parse(req.params.kind),page=pageOf(req),status=z.string().max(30).default('').parse(req.query.status);if(kind==='clearances')requireManager(req);const r=await db.execute(sql`SELECT r.*,e.first_name||' '||e.last_name AS employee_name,e.user_id AS employee_user_id FROM ${sql.raw(tables[kind])} r JOIN employees e ON e.id=r.employee_id WHERE ${managesRecords(req)?sql`true`:sql`e.user_id=${req.user.userId} AND r.status IN ('approved','applied')`} AND (${status}='' OR r.status=${status}) ORDER BY r.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows.map((r:any)=>({...r,canManage:managesRecords(req)&&r.employee_user_id!==req.user.userId,canReview:managesRecords(req)&&r.employee_user_id!==req.user.userId&&r.created_by!==req.user.userId}))});}));
router.get('/:kind/:id/history',handle(async(req,res)=>{requireManager(req);const kind=z.enum(['renewals','clearances','exit-templates']).parse(req.params.kind),recordId=id.parse(Number(req.params.id));const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind=${kind==='exit-templates'?'exit_template':historyKinds[kind]} AND record_id=${recordId} ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
router.post('/renewals',handle(async(req,res)=>{requireManager(req);const input=z.object({employeeId:id,employeeVersion:id,newEndDate:civilDate,effectiveDate:civilDate,agreementReference:shortText,reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{const e=await employee(tx,input.employeeId,req);renewable(e);if(e.record_version!==input.employeeVersion)fail(409,'Employee changed; select the employee again');if(input.newEndDate<=e.contract_end_date||input.newEndDate<qatarToday()||input.effectiveDate<e.joining_date||input.effectiveDate>input.newEndDate)fail(400,'Choose a later contract end date and an effective date between joining and the new end date');const exits=await tx.execute(sql`SELECT id FROM offboarding_cases WHERE employee_id=${e.id} AND status='open'`);if(exits.rows.length)fail(409,'Resolve the open exit case before proposing a renewal');const r=await tx.execute(sql`INSERT INTO contract_renewals(employee_id,employee_version,previous_end_date,new_end_date,effective_date,agreement_reference,proposal_reason,created_by) VALUES (${e.id},${e.record_version},${e.contract_end_date},${input.newEndDate},${input.effectiveDate},${input.agreementReference},${input.reason},${req.user.userId}) RETURNING *`);await history(tx,req,'contract_renewal',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.post('/renewals/:id/actions',handle(async(req,res)=>{requireManager(req);const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['approve','reject','cancel','apply']),reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT employee_id FROM contract_renewals WHERE id=${recordId}`);if(!lookup.rows.length)fail(404,'Renewal not found');const e=await employee(tx,Number(lookup.rows[0].employee_id),req);const rows=await tx.execute(sql`SELECT * FROM contract_renewals WHERE id=${recordId} FOR UPDATE`),old=rows.rows[0] as any;if(old.version!==input.version)fail(409,'Renewal changed; reload');if(!['submitted','approved'].includes(old.status))fail(409,'Renewal is finalized');
 let r;
 if(input.action==='cancel'){r=await tx.execute(sql`UPDATE contract_renewals SET status='cancelled',decision_reason=${input.reason},version=version+1 WHERE id=${recordId} RETURNING *`);}
 else{
  if(input.action==='apply'&&old.status!=='approved'||input.action!=='apply'&&old.status!=='submitted')fail(409,'Renewal is not ready for this action');
  if(input.action!=='apply'&&old.created_by===req.user.userId)fail(403,'An independent HR manager must decide the renewal');
  if(input.action!=='reject'){
   renewable(e);if(e.record_version!==old.employee_version||e.contract_end_date!==old.previous_end_date)fail(409,'Employee changed since proposal; cancel and submit a new renewal');
   const exits=await tx.execute(sql`SELECT id FROM offboarding_cases WHERE employee_id=${e.id} AND status='open'`);if(exits.rows.length)fail(409,'Resolve the open exit case first');
   if(old.new_end_date<qatarToday())fail(400,'Proposed contract has already expired; submit a new renewal');
  }
  if(input.action==='apply'){
   if(old.effective_date>qatarToday())fail(400,'Apply on or after the effective date');
   await tx.update(employees).set({contractEndDate:old.new_end_date,updatedAt:new Date()}).where(eq(employees.id,e.id));
   await tx.insert(employeeLifecycleEvents).values({employeeId:e.id,eventType:'contract_renewal',effectiveDate:old.effective_date,reason:input.reason,metadata:{renewalId:recordId,previousEndDate:old.previous_end_date,newEndDate:old.new_end_date,agreementReference:old.agreement_reference},createdBy:req.user.userId});
   r=await tx.execute(sql`UPDATE contract_renewals SET status='applied',applied_by=${req.user.userId},applied_at=now(),decision_reason=${input.reason},version=version+1 WHERE id=${recordId} RETURNING *`);
  }else r=await tx.execute(sql`UPDATE contract_renewals SET status=${input.action==='approve'?'approved':'rejected'},approved_by=${input.action==='approve'?req.user.userId:null},approved_at=${input.action==='approve'?sql`now()`:sql`NULL`},decision_reason=${input.reason},version=version+1 WHERE id=${recordId} RETURNING *`);
 }
 await history(tx,req,'contract_renewal',r.rows[0],input.reason);return r.rows[0];});res.json(saved);}));

async function clearanceContext(tx:any,e:any,returnDate:string){
 if(e.status!=='active'||e.termination_date||e.joining_date>returnDate||returnDate>qatarToday()||(e.contract_end_date&&e.contract_end_date<qatarToday()))fail(400,'Verify an active current employment record and a return date on or before today first');
 const exits=await blockingExits(tx,e.id,qatarToday());if(exits.some(o=>o.status==='open'))fail(409,'Complete or cancel the open exit case first');if(!exits.length)fail(409,'No completed exit case needs clearance');
 if(exits.some(o=>!o.completed_date||o.completed_date>returnDate))fail(400,'Return date cannot precede completed exit clearance');
 const custody=await tx.execute(sql`SELECT id FROM equipment_custody WHERE employee_id=${e.id} AND status<>'closed'`);if(custody.rows.length)fail(409,'Resolve existing equipment custody before return-to-work clearance');
 return exits.map(o=>({id:o.id,version:o.version,completedAt:o.completed_at}));
}
router.post('/clearances',handle(async(req,res)=>{requireManager(req);const input=z.object({employeeId:id,employeeVersion:id,returnDate:civilDate,reference:shortText,reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{const e=await employee(tx,input.employeeId,req);if(e.record_version!==input.employeeVersion)fail(409,'Employee changed; select the employee again');const exits=await clearanceContext(tx,e,input.returnDate);const ids=exits.map(o=>o.id);const r=await tx.execute(sql`INSERT INTO return_work_clearances(employee_id,employee_version,return_date,exit_ids,exit_snapshot,reference,proposal_reason,created_by) VALUES (${e.id},${e.record_version},${input.returnDate},ARRAY[${sql.join(ids.map(v=>sql`${v}`),sql`, `)}]::integer[],${JSON.stringify(exits)}::jsonb,${input.reference},${input.reason},${req.user.userId}) RETURNING *`);await history(tx,req,'return_work_clearance',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.post('/clearances/:id/actions',handle(async(req,res)=>{requireManager(req);const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['approve','reject','cancel','revoke']),reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT employee_id FROM return_work_clearances WHERE id=${recordId}`);if(!lookup.rows.length)fail(404,'Clearance not found');const e=await employee(tx,Number(lookup.rows[0].employee_id),req);const rows=await tx.execute(sql`SELECT * FROM return_work_clearances WHERE id=${recordId} FOR UPDATE`),old=rows.rows[0] as any;if(old.version!==input.version)fail(409,'Clearance changed; reload');if(input.action==='revoke'?old.status!=='approved':old.status!=='submitted')fail(409,'Clearance is not ready for this action');if(['approve','reject'].includes(input.action)&&old.created_by===req.user.userId)fail(403,'An independent HR manager must review this clearance');
 if(input.action==='approve'){if(e.record_version!==old.employee_version)fail(409,'Employee changed; cancel and submit a new clearance');const exits=await clearanceContext(tx,e,old.return_date);if(JSON.stringify(exits.map(o=>[o.id,o.version]))!==JSON.stringify(old.exit_snapshot.map((o:any)=>[o.id,o.version])))fail(409,'Exit cases changed; submit a fresh clearance');}
 const status={approve:'approved',reject:'rejected',cancel:'cancelled',revoke:'revoked'}[input.action];const r=await tx.execute(sql`UPDATE return_work_clearances SET status=${status},approved_by=${input.action==='approve'?req.user.userId:old.approved_by},approved_at=${input.action==='approve'?sql`now()`:old.approved_at},decision_reason=${input.reason},version=version+1 WHERE id=${recordId} RETURNING *`);await history(tx,req,'return_work_clearance',r.rows[0],input.reason);return r.rows[0];});res.json(saved);}));
export default router;
