import {Router} from 'express';
import {z} from 'zod';
import {and,eq,sql} from 'drizzle-orm';
import {db} from '../db';
import {employees,activityLogs} from '@shared/schema';
import {authenticate} from '../middleware/auth';
import {employeeScope} from '../services/access';
import {hasPermission,getAccessScope} from '@shared/permissions';
import {civilDate} from '@shared/calculation-rules';
import {OnboardingError} from '../services/onboarding-workflow';
const router=Router();router.use(authenticate);router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
const id=z.number().int().positive(),kind=z.enum(['expense','benefit']),reason=z.string().trim().min(5).max(2000),money=z.number().int().min(1).max(100000000);
const rules=z.object({perRequestCents:money,annualCapCents:money,employeeTypes:z.array(z.enum(['permanent','temporary','contract'])).min(1).max(3)}).strict();
const admin=(req:any)=>['admin','super_admin'].includes(req.user.role);
const moduleFor=(k:string)=>k==='expense'?'payroll_management' as const:'benefits_perks' as const;
function reviewer(req:any,k:string){const module=moduleFor(k);return hasPermission(req.user.role,module,'update')&&['all','department'].includes(getAccessScope(req.user.role,module));}
function scope(req:any,k:string){return sql`((${k==='expense'||hasPermission(req.user.role,'benefits_perks','read')} AND ${employees.userId}=${req.user.userId}) OR (${reviewer(req,k)} AND ${employeeScope(req.user,moduleFor(k))}))`;}
function handler(fn:(req:any,res:any)=>Promise<any>){return async(req:any,res:any)=>{try{await fn(req,res);}catch(e:any){const code=e.code||e.cause?.code;res.status(e instanceof OnboardingError?e.status:e instanceof z.ZodError?400:code==='23505'?409:500).json({message:e instanceof OnboardingError?e.message:e instanceof z.ZodError?e.issues.map((i:any)=>i.message).join('; '):code==='23505'?'Reference already used; reload the existing request':'Unable to complete employee service action'});}};}
async function audit(tx:any,req:any,type:string,row:any,why:string){await tx.execute(sql`INSERT INTO lifecycle_history(kind,record_id,version,snapshot,actor_id,reason) VALUES (${type},${row.id},${row.version},${JSON.stringify(row)}::jsonb,${req.user.userId},${why})`);await tx.insert(activityLogs).values({userId:req.user.userId,action:'update',entityType:type,entityId:row.id,details:'Saved version '+row.version});}
router.get('/policies',handler(async(req,res)=>{const k=kind.parse(req.query.kind);if(k==='benefit'&&!hasPermission(req.user.role,'benefits_perks','read'))throw new OnboardingError(403,'Benefits access required');const r=await db.execute(sql`SELECT * FROM (SELECT DISTINCT ON(name) * FROM employee_service_policies WHERE kind=${k} ORDER BY name,version DESC) p WHERE enabled OR ${admin(req)} ORDER BY name`);res.json({items:r.rows,canConfigure:admin(req)});}));
router.post('/policies',handler(async(req,res)=>{
 if(!admin(req))throw new OnboardingError(403,'An Admin or Super Admin configures service policies');const input=z.object({kind,name:z.string().trim().min(2).max(100),expectedVersion:z.number().int().min(0),enabled:z.boolean(),rules,reason}).strict().parse(req.body);if(input.rules.annualCapCents<input.rules.perRequestCents)throw new OnboardingError(400,'Annual cap cannot be below the request cap');
 const saved=await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(293001)`);const latest=await tx.execute(sql`SELECT version FROM employee_service_policies WHERE kind=${input.kind} AND name=${input.name} ORDER BY version DESC LIMIT 1`);if(Number(latest.rows[0]?.version||0)!==input.expectedVersion)throw new OnboardingError(409,'Policy changed; reload');
 const r=await tx.execute(sql`INSERT INTO employee_service_policies(kind,name,version,enabled,rules,created_by,reason) VALUES (${input.kind},${input.name},${input.expectedVersion+1},${input.enabled},${JSON.stringify(input.rules)}::jsonb,${req.user.userId},${input.reason}) RETURNING *`);await audit(tx,req,'service_policy',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);
}));
router.get('/requests',handler(async(req,res)=>{const k=kind.parse(req.query.kind),page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT r.*,p.name AS policy_name,p.rules AS policy_rules,employees.first_name || ' ' || employees.last_name AS employee_name,employees.user_id AS owner_user_id FROM employee_service_requests r JOIN employees ON employees.id=r.employee_id JOIN employee_service_policies p ON p.id=r.policy_id WHERE r.kind=${k} AND ${scope(req,k)} ORDER BY r.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows.map((r:any)=>({...r,canReview:reviewer(req,k)&&r.owner_user_id!==req.user.userId&&r.created_by!==req.user.userId&&r.status==='submitted',canWithdraw:r.owner_user_id===req.user.userId&&r.status==='submitted',canPay:k==='expense'&&reviewer(req,k)&&r.owner_user_id!==req.user.userId&&r.status==='approved',canEnd:k==='benefit'&&reviewer(req,k)&&r.owner_user_id!==req.user.userId&&r.status==='approved'}))});}));
router.post('/requests',handler(async(req,res)=>{
 const input=z.object({kind,policyId:id,title:z.string().trim().min(3).max(200),amountCents:money,serviceDate:civilDate,endDate:civilDate.nullable(),evidence:reason,reference:z.string().trim().min(5).max(100)}).strict().parse(req.body);
 if(input.kind==='benefit'&&(!hasPermission(req.user.role,'benefits_perks','read')||!(hasPermission(req.user.role,'benefits_perks','create')||hasPermission(req.user.role,'benefits_perks','update'))))throw new OnboardingError(403,'Benefits enrollment access required');
 const saved=await db.transaction(async tx=>{const [e]=await tx.select().from(employees).where(eq(employees.userId,req.user.userId)).for('update');if(!e||e.status!=='active')throw new OnboardingError(403,'An active linked employee record is required');
 const policies=await tx.execute(sql`SELECT * FROM employee_service_policies WHERE id=${input.policyId}`);const policy=policies.rows[0] as any;if(!policy||policy.kind!==input.kind)throw new OnboardingError(400,'Choose a policy for this request');const latest=await tx.execute(sql`SELECT id,enabled FROM employee_service_policies WHERE kind=${input.kind} AND name=${policy.name} ORDER BY version DESC LIMIT 1`);if(latest.rows[0].id!==policy.id||!latest.rows[0].enabled)throw new OnboardingError(409,'Select the current enabled policy');
 const r=rules.parse(policy.rules);if(!r.employeeTypes.includes(e.type)||input.amountCents>r.perRequestCents)throw new OnboardingError(400,'This request exceeds the policy or your employment type is not eligible');
 const today=new Date().toISOString().slice(0,10);if(input.serviceDate<e.joiningDate||(input.kind==='expense'&&(input.serviceDate>today||input.endDate))||(input.kind==='benefit'&&(!input.endDate||input.endDate<input.serviceDate||input.endDate.slice(0,4)!==input.serviceDate.slice(0,4))))throw new OnboardingError(400,'Check the service dates; benefits must remain within one calendar year');
 const year=Number(input.serviceDate.slice(0,4));const used=await tx.execute(sql`SELECT coalesce(sum(r.amount_cents),0)::bigint AS cents FROM employee_service_requests r JOIN employee_service_policies p ON p.id=r.policy_id WHERE r.employee_id=${e.id} AND r.kind=${input.kind} AND p.name=${policy.name} AND extract(year FROM r.service_date)=${year} AND r.status NOT IN ('rejected','withdrawn')`);if(Number(used.rows[0].cents)+input.amountCents>r.annualCapCents)throw new OnboardingError(409,'This request exceeds the annual policy cap including pending requests');
 if(input.kind==='benefit'){const overlap=await tx.execute(sql`SELECT r.id FROM employee_service_requests r JOIN employee_service_policies p ON p.id=r.policy_id WHERE r.employee_id=${e.id} AND p.kind='benefit' AND p.name=${policy.name} AND r.status IN ('submitted','approved') AND r.service_date<=${input.endDate} AND r.end_date>=${input.serviceDate} LIMIT 1`);if(overlap.rows.length)throw new OnboardingError(409,'This benefit already covers part of the requested period');}
 const result=await tx.execute(sql`INSERT INTO employee_service_requests(kind,employee_id,policy_id,title,amount_cents,service_date,end_date,evidence,reference,created_by) VALUES (${input.kind},${e.id},${policy.id},${input.title},${input.amountCents},${input.serviceDate},${input.endDate},${input.evidence},${input.reference},${req.user.userId}) RETURNING *`);await audit(tx,req,'service_request',result.rows[0],'Submitted with supporting reference');return result.rows[0];});res.status(201).json(saved);
}));
router.post('/requests/:id/actions',handler(async(req,res)=>{
 const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['approve','reject','withdraw','pay','end']),reason,paymentReference:z.string().trim().min(5).max(150).optional()}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT employee_id FROM employee_service_requests WHERE id=${recordId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Request not found');const [owner]=await tx.select().from(employees).where(eq(employees.id,Number(lookup.rows[0].employee_id))).for('update');const rows=await tx.execute(sql`SELECT r.* FROM employee_service_requests r JOIN employees ON employees.id=r.employee_id WHERE r.id=${recordId} FOR UPDATE OF r`);const row=rows.rows[0] as any;
 const accessible=await tx.select({id:employees.id}).from(employees).where(and(eq(employees.id,owner.id),scope(req,row.kind)));if(!accessible.length)throw new OnboardingError(404,'Request not found');if(row.version!==input.version)throw new OnboardingError(409,'Request changed; reload');let status='',decider=row.decided_by;
 if(input.action==='withdraw'){if(owner.userId!==req.user.userId||row.status!=='submitted')throw new OnboardingError(403,'Only the employee may withdraw a pending request');status='withdrawn';}
 else{if(!reviewer(req,row.kind)||owner.userId===req.user.userId||row.created_by===req.user.userId)throw new OnboardingError(403,'An independent authorized reviewer is required');
 if(input.action==='pay'){if(row.kind!=='expense'||row.status!=='approved'||!input.paymentReference)throw new OnboardingError(409,'Approve the expense and provide an external payment reference first');status='paid';}
 else if(input.action==='end'){if(row.kind!=='benefit'||row.status!=='approved')throw new OnboardingError(409,'Only approved benefits can be ended');status='ended';}
 else{if(row.status!=='submitted')throw new OnboardingError(409,'Only pending requests can be decided');if(input.action==='approve'&&owner.status!=='active')throw new OnboardingError(409,'Employee is no longer active');status=input.action==='approve'?'approved':'rejected';decider=req.user.userId;}}
 const r=await tx.execute(sql`UPDATE employee_service_requests SET status=${status},decided_by=${decider},payment_reference=${input.action==='pay'?input.paymentReference:row.payment_reference},version=version+1 WHERE id=${recordId} RETURNING *`);await audit(tx,req,'service_request',r.rows[0],input.reason);return r.rows[0];});res.json(saved);
}));
router.get('/requests/:id/history',handler(async(req,res)=>{const recordId=id.parse(Number(req.params.id));const rows=await db.execute(sql`SELECT kind,employee_id FROM employee_service_requests WHERE id=${recordId}`);if(!rows.rows.length)throw new OnboardingError(404,'Request not found');const row=rows.rows[0];const e=await db.select({id:employees.id}).from(employees).where(and(eq(employees.id,Number(row.employee_id)),scope(req,String(row.kind))));if(!e.length)throw new OnboardingError(404,'Request not found');const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind='service_request' AND record_id=${recordId} ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
export default router;
