import {Router} from 'express';
import {randomBytes,createHash} from 'node:crypto';
import {z} from 'zod';
import {sql} from 'drizzle-orm';
import {rateLimit} from 'express-rate-limit';
import {db} from '../db';
import {activityLogs} from '@shared/schema';
import {authenticate} from '../middleware/auth';
import {OnboardingError} from '../services/onboarding-workflow';
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
function handler(fn:(req:any,res:any,next:any)=>Promise<any>){return async(req:any,res:any,next:any)=>{try{await fn(req,res,next);}catch(e:any){res.status(e instanceof OnboardingError?e.status:e instanceof z.ZodError?400:(e.code||e.cause?.code)==='23505'?409:500).json({message:e instanceof OnboardingError?e.message:e instanceof z.ZodError?'Check EOS request fields':'Unable to process EOS request'});}};}
export const eosAdmin=Router();eosAdmin.use(authenticate);eosAdmin.use((req,res,next)=>{res.set('Cache-Control','no-store');if(!['admin','super_admin'].includes(req.user!.role))return res.status(403).json({message:'Administrator access required'});next();});
eosAdmin.get('/',handler(async(_req,res)=>{const keys=await db.execute(sql`SELECT k.id,k.name,k.team_id,t.name AS team_name,k.expires_at,k.revoked_at FROM eos_service_keys k JOIN workforce_teams t ON t.id=k.team_id ORDER BY k.id DESC LIMIT 100`);const teams=await db.execute(sql`SELECT id,name FROM workforce_teams ORDER BY name LIMIT 500`);res.json({items:keys.rows,teams:teams.rows});}));
eosAdmin.post('/',handler(async(req,res)=>{const input=z.object({name:z.string().trim().min(3).max(100),teamId:z.number().int().positive(),expiresAt:z.string().datetime()}).strict().parse(req.body);if(Date.parse(input.expiresAt)<=Date.now()||Date.parse(input.expiresAt)>Date.now()+365*86400000)throw new OnboardingError(400,'Key expiry must be within the next 365 days');const secret='eos_'+randomBytes(32).toString('hex');const row=await db.transaction(async tx=>{const team=await tx.execute(sql`SELECT id FROM workforce_teams WHERE id=${input.teamId}`);if(!team.rows.length)throw new OnboardingError(404,'Team not found');const r=await tx.execute(sql`INSERT INTO eos_service_keys(name,team_id,key_hash,expires_at,created_by) VALUES (${input.name},${input.teamId},${hash(secret)},${input.expiresAt},${req.user.userId}) RETURNING id,name,team_id,expires_at`);await tx.insert(activityLogs).values({userId:req.user.userId,action:'create',entityType:'eos_key',entityId:Number(r.rows[0].id),details:'Team-scoped EOS credential created'});return r.rows[0];});res.status(201).json({...row,secret});}));
eosAdmin.post('/:id/revoke',handler(async(req,res)=>{const id=z.coerce.number().int().positive().parse(req.params.id);await db.transaction(async tx=>{const r=await tx.execute(sql`UPDATE eos_service_keys SET revoked_at=coalesce(revoked_at,now()) WHERE id=${id} RETURNING id`);if(!r.rows.length)throw new OnboardingError(404,'Key not found');await tx.insert(activityLogs).values({userId:req.user.userId,action:'update',entityType:'eos_key',entityId:id,details:'EOS credential revoked'});});res.json({revoked:true});}));
export const eosApi=Router();eosApi.use(rateLimit({windowMs:60000,limit:120,standardHeaders:'draft-7',legacyHeaders:false}));
eosApi.use(handler(async(req,res,next)=>{res.set('Cache-Control','no-store');const auth=String(req.headers.authorization||'');if(!/^Bearer eos_[a-f0-9]{64}$/.test(auth))throw new OnboardingError(401,'Valid EOS service credential required');const r=await db.execute(sql`SELECT k.id,k.team_id FROM eos_service_keys k JOIN users u ON u.id=k.created_by WHERE k.key_hash=${hash(auth.slice(7))} AND k.revoked_at IS NULL AND k.expires_at>now() AND u.is_active=true AND u.approval_status='approved' AND u.role IN ('admin','super_admin')`);if(!r.rows.length)throw new OnboardingError(401,'EOS credential expired or revoked');res.locals.eos=r.rows[0];next();}));
eosApi.get('/assignments',handler(async(req,res)=>{const cursor=z.coerce.number().int().min(0).default(0).parse(req.query.after);const team=res.locals.eos.team_id;const r=await db.execute(sql`SELECT a.id AS "assignmentId",a.employee_id AS "employeeId",a.shift_id AS "shiftId",a.status,s.start_at AS "startAt",s.end_at AS "endAt",s.role FROM workforce_assignments a JOIN workforce_shifts s ON s.id=a.shift_id WHERE s.team_id=${team} AND a.id>${cursor} ORDER BY a.id LIMIT 101`);const more=r.rows.length>100,items=r.rows.slice(0,100);res.json({items,nextCursor:more?items[items.length-1].assignmentId:null});}));
eosApi.get('/changes',handler(async(req,res)=>{const cursor=z.coerce.number().int().min(0).default(0).parse(req.query.after);const r=await db.execute(sql`SELECT id,payload,created_at AS "createdAt" FROM eos_assignment_events WHERE team_id=${res.locals.eos.team_id} AND id>${cursor} ORDER BY id LIMIT 100`);res.json({items:r.rows,nextCursor:r.rows.length?r.rows[r.rows.length-1].id:cursor});}));
eosApi.post('/activations',handler(async(req,res)=>{
 const input=z.object({externalId:z.string().trim().min(1).max(100),label:z.string().trim().min(2).max(200)}).strict().parse(req.body),requestKey=z.string().min(16).max(128).parse(req.headers['idempotency-key']),bodyHash=hash(JSON.stringify(input)),key=res.locals.eos;
 const result=await db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM eos_service_keys WHERE id=${key.id} FOR UPDATE`);const prior=await tx.execute(sql`SELECT body_hash,response FROM eos_requests WHERE key_id=${key.id} AND request_key=${requestKey}`);if(prior.rows.length){if(prior.rows[0].body_hash!==bodyHash)throw new OnboardingError(409,'Idempotency key was used with different content');return prior.rows[0].response;}
 const r=await tx.execute(sql`INSERT INTO eos_activation_links(team_id,external_id,label) VALUES (${key.team_id},${input.externalId},${input.label}) ON CONFLICT(team_id,external_id) DO NOTHING RETURNING id,team_id AS "teamId",external_id AS "externalId",label`);let response=r.rows[0];if(!response){const old=await tx.execute(sql`SELECT id,team_id AS "teamId",external_id AS "externalId",label FROM eos_activation_links WHERE team_id=${key.team_id} AND external_id=${input.externalId}`);response=old.rows[0];if(response.label!==input.label)throw new OnboardingError(409,'External activation already has a different label');}
 await tx.execute(sql`INSERT INTO eos_requests(key_id,request_key,body_hash,response) VALUES (${key.id},${requestKey},${bodyHash},${JSON.stringify(response)}::jsonb)`);return response;});res.status(201).json(result);
}));
