import {Router} from 'express';
import {z} from 'zod';
import {sql} from 'drizzle-orm';
import {db} from '../db';
import {authenticate} from '../middleware/auth';
import {civilDate} from '@shared/calculation-rules';
import {OnboardingError} from '../services/onboarding-workflow';
import {blockingExits} from '../services/employmentContinuity';
import {recordId as id,shortText,decisionReason as reason,isAdmin,managesRecords,requireManager,requireAdmin,recordHandler as handle,recordHistory as history,qatarToday} from '../services/workplaceRecords';
const router=Router();router.use(authenticate);router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
router.get('/config',handle(async(req,res)=>res.json({canManage:managesRecords(req),canConfigure:isAdmin(req)})));
router.get('/people',handle(async(req,res)=>{requireManager(req);const q=z.string().trim().min(2).max(100).parse(req.query.q);const r=await db.execute(sql`SELECT id,employee_id,first_name||' '||last_name AS name FROM employees WHERE status='active' AND strpos(lower(first_name||' '||last_name||' '||employee_id),lower(${q}))>0 ORDER BY id LIMIT 25`);res.json(r.rows);}));
router.get('/assets',handle(async(req,res)=>{requireManager(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page),q=z.string().trim().max(100).default('').parse(req.query.q);const r=await db.execute(sql`SELECT a.*,EXISTS(SELECT 1 FROM equipment_custody c WHERE c.asset_id=a.id AND c.status<>'closed') AS assigned FROM equipment_assets a WHERE strpos(lower(a.asset_tag||' '||a.name),lower(${q}))>0 ORDER BY a.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows});}));
const assetFields=z.object({assetTag:shortText,name:shortText,category:shortText,serialNumber:z.string().trim().max(200),location:shortText,reason}).strict();
router.post('/assets',handle(async(req,res)=>{requireAdmin(req);const input=assetFields.parse(req.body);const saved=await db.transaction(async tx=>{const r=await tx.execute(sql`INSERT INTO equipment_assets(asset_tag,name,category,serial_number,location,created_by) VALUES (${input.assetTag.toUpperCase()},${input.name},${input.category},${input.serialNumber},${input.location},${req.user.userId}) RETURNING *`);await history(tx,req,'equipment_asset',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.post('/assets/:id',handle(async(req,res)=>{requireAdmin(req);const assetId=id.parse(Number(req.params.id)),input=assetFields.extend({version:id,status:z.enum(['available','maintenance','retired','lost'])}).parse(req.body);const saved=await db.transaction(async tx=>{
 const rows=await tx.execute(sql`SELECT * FROM equipment_assets WHERE id=${assetId} FOR UPDATE`),old=rows.rows[0] as any;if(!old)throw new OnboardingError(404,'Asset not found');if(old.version!==input.version)throw new OnboardingError(409,'Asset changed; reload');
 const custody=await tx.execute(sql`SELECT id FROM equipment_custody WHERE asset_id=${assetId} AND status<>'closed'`);if(custody.rows.length)throw new OnboardingError(409,'Resolve active custody before editing this asset');
 const r=await tx.execute(sql`UPDATE equipment_assets SET asset_tag=${input.assetTag.toUpperCase()},name=${input.name},category=${input.category},serial_number=${input.serialNumber},location=${input.location},status=${input.status},version=version+1 WHERE id=${assetId} RETURNING *`);await history(tx,req,'equipment_asset',r.rows[0],input.reason);return r.rows[0];});res.json(saved);
}));
router.get('/custody',handle(async(req,res)=>{const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const view=z.enum(['mine','all']).default('mine').parse(req.query.view);if(view==='all')requireManager(req);const r=await db.execute(sql`SELECT c.*,e.first_name||' '||e.last_name AS employee_name,e.user_id AS employee_user_id FROM equipment_custody c JOIN employees e ON e.id=c.employee_id WHERE ${view==='all'?sql`true`:sql`e.user_id=${req.user.userId}`} ORDER BY (c.status<>'closed') DESC,c.due_date,c.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows.map((r:any)=>({...r,canClose:managesRecords(req)&&r.employee_user_id!==req.user.userId,isMine:r.employee_user_id===req.user.userId})),canManage:managesRecords(req)});}));
router.post('/custody',handle(async(req,res)=>{requireManager(req);const input=z.object({assetId:id,assetVersion:id,employeeId:id,issuedDate:civilDate,dueDate:civilDate,reason}).strict().parse(req.body);if(input.issuedDate>qatarToday()||input.dueDate<input.issuedDate)throw new OnboardingError(400,'Check issue and return dates');
 const saved=await db.transaction(async tx=>{
 const people=await tx.execute(sql`SELECT * FROM employees WHERE id=${input.employeeId} FOR UPDATE`),employee=people.rows[0] as any;if(!employee||employee.status!=='active'||employee.joining_date>input.issuedDate)throw new OnboardingError(400,'Choose an active employee whose employment has started');if(employee.user_id===req.user.userId)throw new OnboardingError(403,'Another HR manager must issue equipment to you');
 const exits=await blockingExits(tx,input.employeeId,input.issuedDate);if(exits.length)throw new OnboardingError(409,'Resolve open exits or approve return-to-work clearance for completed exits before issuing equipment');
 const rows=await tx.execute(sql`SELECT * FROM equipment_assets WHERE id=${input.assetId} FOR UPDATE`),asset=rows.rows[0] as any;if(!asset||asset.version!==input.assetVersion||asset.status!=='available')throw new OnboardingError(409,'Choose a current available asset');
 const r=await tx.execute(sql`INSERT INTO equipment_custody(asset_id,employee_id,asset_snapshot,issued_date,due_date,issued_by,issue_evidence) VALUES (${input.assetId},${input.employeeId},${JSON.stringify(asset)}::jsonb,${input.issuedDate},${input.dueDate},${req.user.userId},${input.reason}) RETURNING *`);await history(tx,req,'equipment_custody',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);
}));
router.post('/custody/:id/actions',handle(async(req,res)=>{const custodyId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['receipt','request_return','close']),reason,returnedDate:civilDate.optional(),disposition:z.enum(['available','maintenance','lost']).optional()}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{
 const lookup=await tx.execute(sql`SELECT employee_id,asset_id FROM equipment_custody WHERE id=${custodyId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Custody not found');const person=await tx.execute(sql`SELECT user_id FROM employees WHERE id=${lookup.rows[0].employee_id} FOR UPDATE`);const mine=person.rows[0]?.user_id===req.user.userId;
 if(input.action==='close'){requireManager(req);if(mine)throw new OnboardingError(403,'Another HR manager must inspect your equipment return');}else if(!mine)throw new OnboardingError(404,'Custody not found');
 await tx.execute(sql`SELECT id FROM equipment_assets WHERE id=${lookup.rows[0].asset_id} FOR UPDATE`);const rows=await tx.execute(sql`SELECT * FROM equipment_custody WHERE id=${custodyId} FOR UPDATE`),old=rows.rows[0] as any;if(old.version!==input.version||old.status==='closed')throw new OnboardingError(409,'Custody changed or is closed; reload');
 let result;if(input.action==='receipt'){if(old.receipt_at)throw new OnboardingError(409,'Receipt already acknowledged');result=await tx.execute(sql`UPDATE equipment_custody SET receipt_at=now(),employee_note=${input.reason},version=version+1 WHERE id=${custodyId} RETURNING *`);}else if(input.action==='request_return'){if(old.status==='return_requested')throw new OnboardingError(409,'Return already requested');result=await tx.execute(sql`UPDATE equipment_custody SET status='return_requested',employee_note=${input.reason},version=version+1 WHERE id=${custodyId} RETURNING *`);}else{
 if(!input.disposition||!input.returnedDate||input.returnedDate<old.issued_date||input.returnedDate>qatarToday())throw new OnboardingError(400,'Record disposition and a valid inspection date');
 result=await tx.execute(sql`UPDATE equipment_custody SET status='closed',returned_date=${input.returnedDate},disposition=${input.disposition},return_evidence=${input.reason},closed_by=${req.user.userId},version=version+1 WHERE id=${custodyId} RETURNING *`);
 const asset=await tx.execute(sql`UPDATE equipment_assets SET status=${input.disposition},version=version+1 WHERE id=${old.asset_id} RETURNING *`);await history(tx,req,'equipment_asset',asset.rows[0],input.reason);
 }await history(tx,req,'equipment_custody',result.rows[0],input.reason);return result.rows[0];});res.json(saved);
}));
router.get('/history/:kind/:id',handle(async(req,res)=>{const kind=z.enum(['equipment_asset','equipment_custody']).parse(req.params.kind),recordId=id.parse(Number(req.params.id));if(!managesRecords(req)){if(kind==='equipment_asset')throw new OnboardingError(403,'HR access required');const r=await db.execute(sql`SELECT c.id FROM equipment_custody c JOIN employees e ON e.id=c.employee_id WHERE c.id=${recordId} AND e.user_id=${req.user.userId}`);if(!r.rows.length)throw new OnboardingError(404,'Custody not found');}const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind=${kind} AND record_id=${recordId} ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
export default router;
