import {Router} from 'express';
import {z} from 'zod';
import {sql} from 'drizzle-orm';
import {db} from '../db';
import {authenticate} from '../middleware/auth';
import {civilDate} from '@shared/calculation-rules';
import {OnboardingError} from '../services/onboarding-workflow';
import {activityLogs} from '@shared/schema';
import {recordId as id,shortText,decisionReason as reason,isAdmin,managesRecords,requireManager,requireAdmin,recordHandler as handle,recordHistory as history,qatarToday} from '../services/workplaceRecords';
const router=Router();router.use(authenticate);router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
const fields=z.object({title:shortText,body:z.string().trim().min(20).max(50000),employeeTypes:z.array(z.enum(['permanent','temporary','contract'])).min(1).max(3).refine(a=>new Set(a).size===a.length),department:z.string().trim().max(200),dueDate:civilDate,reason}).strict();
router.get('/config',handle(async(req,res)=>res.json({canManage:managesRecords(req),canConfigure:isAdmin(req)})));
router.get('/policies',handle(async(req,res)=>{requireManager(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT * FROM handbook_policies ORDER BY id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows});}));
router.post('/policies',handle(async(req,res)=>{requireAdmin(req);const input=fields.parse(req.body);const saved=await db.transaction(async tx=>{const r=await tx.execute(sql`INSERT INTO handbook_policies(title,body,employee_types,department,due_date,created_by) VALUES (${input.title},${input.body},${JSON.stringify(input.employeeTypes)}::jsonb,${input.department},${input.dueDate},${req.user.userId}) RETURNING *`);await history(tx,req,'handbook_policy',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(saved);}));
router.post('/policies/:id',handle(async(req,res)=>{requireAdmin(req);const policyId=id.parse(Number(req.params.id)),input=fields.extend({version:id}).parse(req.body);const saved=await db.transaction(async tx=>{const rows=await tx.execute(sql`SELECT * FROM handbook_policies WHERE id=${policyId} FOR UPDATE`),old=rows.rows[0] as any;if(!old)throw new OnboardingError(404,'Policy not found');if(old.version!==input.version||old.status!=='draft')throw new OnboardingError(409,'Only the current draft can be edited');const r=await tx.execute(sql`UPDATE handbook_policies SET title=${input.title},body=${input.body},employee_types=${JSON.stringify(input.employeeTypes)}::jsonb,department=${input.department},due_date=${input.dueDate},version=version+1 WHERE id=${policyId} RETURNING *`);await history(tx,req,'handbook_policy',r.rows[0],input.reason);return r.rows[0];});res.json(saved);}));
async function assignPolicy(tx:any,row:any){
 const eligible=sql`e.status='active' AND e.joining_date<=${qatarToday()}::date AND ${JSON.stringify(row.employee_types)}::jsonb ? e.type::text AND (${row.department}='' OR e.department=${row.department})`;
 const count=await tx.execute(sql`SELECT count(*)::int AS n FROM employees e WHERE ${eligible}`);if(Number(count.rows[0].n)>10000)throw new OnboardingError(400,'Narrow the policy audience to a department before assignment');
 const assigned=await tx.execute(sql`INSERT INTO handbook_assignments(policy_id,policy_version,employee_id,due_date) SELECT ${row.id},${row.version},e.id,${row.due_date}::date FROM employees e WHERE ${eligible} ON CONFLICT DO NOTHING RETURNING id`);return assigned.rows.length;
}
router.post('/policies/:id/actions',handle(async(req,res)=>{requireAdmin(req);const policyId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['publish','revise','withdraw','assign']),reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{
 const rows=await tx.execute(sql`SELECT * FROM handbook_policies WHERE id=${policyId} FOR UPDATE`),old=rows.rows[0] as any;if(!old)throw new OnboardingError(404,'Policy not found');if(old.version!==input.version)throw new OnboardingError(409,'Policy changed; reload');
 if(input.action==='assign'){if(old.status!=='published'||old.due_date<qatarToday())throw new OnboardingError(409,'Publish a current policy with an upcoming deadline');const assigned=await assignPolicy(tx,old);await tx.insert(activityLogs).values({userId:req.user.userId,action:'update',entityType:'handbook_policy',entityId:policyId,details:`Assigned current publication to ${assigned} additional employees`});return {...old,assigned};}
 const allowed:Record<string,string[]>={draft:['publish','withdraw'],published:['revise','withdraw'],withdrawn:['revise']};if(!allowed[old.status]?.includes(input.action))throw new OnboardingError(409,'This policy action is unavailable');if(input.action==='publish'&&old.due_date<qatarToday())throw new OnboardingError(400,'Set a current or future acknowledgement deadline');
 const status=input.action==='publish'?'published':input.action==='revise'?'draft':'withdrawn';const r=await tx.execute(sql`UPDATE handbook_policies SET status=${status},version=version+1 WHERE id=${policyId} RETURNING *`),row=r.rows[0] as any;await history(tx,req,'handbook_policy',row,input.reason);
 if(['publish','withdraw'].includes(input.action))await tx.execute(sql`UPDATE handbook_assignments SET status='withdrawn' WHERE policy_id=${policyId} AND acknowledged_at IS NULL AND status='active'`);
 const assigned=input.action==='publish'?await assignPolicy(tx,row):0;return {...row,assigned};});res.json(saved);
}));
router.get('/mine',handle(async(req,res)=>{const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT a.*,h.snapshot->>'title' AS title,h.snapshot->>'body' AS body FROM handbook_assignments a JOIN employees e ON e.id=a.employee_id JOIN lifecycle_history h ON h.kind='handbook_policy' AND h.record_id=a.policy_id AND h.version=a.policy_version WHERE e.user_id=${req.user.userId} ORDER BY (a.status='active' AND a.acknowledged_at IS NULL) DESC,a.due_date,a.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows});}));
router.post('/acknowledgements/:id',handle(async(req,res)=>{const assignmentId=id.parse(Number(req.params.id));z.object({confirmed:z.literal(true)}).strict().parse(req.body);const saved=await db.transaction(async tx=>{
 const lookup=await tx.execute(sql`SELECT policy_id FROM handbook_assignments WHERE id=${assignmentId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Acknowledgement not found');await tx.execute(sql`SELECT id FROM handbook_policies WHERE id=${lookup.rows[0].policy_id} FOR UPDATE`);
 const rows=await tx.execute(sql`SELECT a.*,e.user_id,e.status AS employee_status FROM handbook_assignments a JOIN employees e ON e.id=a.employee_id WHERE a.id=${assignmentId} FOR UPDATE OF a`),row=rows.rows[0] as any;if(row.user_id!==req.user.userId||row.employee_status!=='active')throw new OnboardingError(404,'Acknowledgement not found');if(row.acknowledged_at)return row;if(row.status!=='active')throw new OnboardingError(409,'This policy assignment has been withdrawn');
 const r=await tx.execute(sql`UPDATE handbook_assignments SET acknowledged_at=now(),acknowledged_by=${req.user.userId} WHERE id=${assignmentId} RETURNING *`);await tx.insert(activityLogs).values({userId:req.user.userId,action:'update',entityType:'handbook_acknowledgement',entityId:assignmentId,details:`Acknowledged policy ${row.policy_id} publication ${row.policy_version}`});return r.rows[0];});res.json(saved);
}));
router.get('/policies/:id/recipients',handle(async(req,res)=>{requireManager(req);const policyId=id.parse(Number(req.params.id)),page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT a.*,e.first_name||' '||e.last_name AS employee_name,e.employee_id AS employee_number FROM handbook_assignments a JOIN employees e ON e.id=a.employee_id WHERE a.policy_id=${policyId} ORDER BY a.policy_version DESC,a.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows});}));
router.get('/policies/:id/history',handle(async(req,res)=>{requireManager(req);const policyId=id.parse(Number(req.params.id));const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind='handbook_policy' AND record_id=${policyId} ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
export default router;
