import express from "express";
import notificationService from "../services/notifications";
import { authenticate, authorize } from "../middleware/auth";
import { requireCommunicationAccess } from '../middleware/communicationsAccess';
import {runOperationalReminders} from '../services/operational-reminders';

const router = express.Router();
router.use(authenticate, requireCommunicationAccess);
router.post('/', authenticate, (_req,res)=>res.status(410).json({message:'Publish an announcement through the internal Communication Hub. Operational notifications are generated by HR workflows.'}));

// Get notifications for the current user
router.get("/", authenticate, async (req, res) => {
  try {
    const userId = req.user!.userId;
    const notifications = await notificationService.getUserNotifications(userId);
    return res.json(notifications);
  } catch (error) {
    console.error("Error fetching notifications:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

// Mark a notification as read
router.patch("/:id/mark-delivered", authenticate, async (req, res) => {
  try {
    const userId = req.user!.userId;
    const notificationId = parseInt(req.params.id);
    
    if (isNaN(notificationId)) {
      return res.status(400).json({ error: "Invalid notification ID" });
    }

    const success = await notificationService.markNotificationDelivered(notificationId,userId);
    
    if (!success) {
      return res.status(404).json({ error: "Notification not found" });
    }

    return res.json({ success: true });
  } catch (error) {
    console.error("Error marking notification as delivered:", error);
    return res.status(500).json({ error: "Internal server error" });
  }
});

router.post('/reminders/run', authenticate, authorize(['admin','super_admin','hr','hr_director']), async (_req,res)=>{
  try{return res.json(await runOperationalReminders());}
  catch(error){return res.status(500).json({message:error instanceof Error?error.message:'Unable to run reminders'});}
});

export default router;
