import {Router} from 'express';
import {z} from 'zod';
import {eq,and,sql} from 'drizzle-orm';
import {db} from '../db';
import {employees,activityLogs} from '@shared/schema';
import {authenticate} from '../middleware/auth';
import {hasPermission,getAccessScope} from '@shared/permissions';
import {employeeScope} from '../services/access';
import {civilDate} from '@shared/calculation-rules';
import {OnboardingError,changeOnboardingTask} from '../services/onboarding-workflow';
const router=Router();router.use(authenticate);router.use((_req,res,next)=>{res.set('Cache-Control','no-store');next();});
const id=z.number().int().positive(),reason=z.string().trim().min(5).max(2000),text=z.string().trim().min(2).max(200);
const isAdmin=(req:any)=>['admin','super_admin'].includes(req.user.role);
function hr(req:any,write=false){if(!hasPermission(req.user.role,'recruitment_onboarding',write?'update':'read')||getAccessScope(req.user.role,'recruitment_onboarding')!=='all')throw new OnboardingError(403,'Organization-wide recruitment access required');}
const approval=(req:any)=>hasPermission(req.user.role,'recruitment_onboarding','approve');
function handler(fn:(req:any,res:any)=>Promise<any>){return async(req:any,res:any)=>{try{await fn(req,res);}catch(e:any){res.status(e instanceof OnboardingError?e.status:e instanceof z.ZodError?400:(e.code||e.cause?.code)==='23505'?409:500).json({message:e instanceof OnboardingError?e.message:e instanceof z.ZodError?e.issues.map((i:any)=>i.message).join('; '):'Unable to save workflow; reload and try again'});}};}
async function history(tx:any,req:any,kind:string,row:any,why:string){await tx.execute(sql`INSERT INTO lifecycle_history(kind,record_id,version,snapshot,actor_id,reason) VALUES (${kind},${row.id},${row.version},${JSON.stringify(row)}::jsonb,${req.user.userId},${why})`);await tx.insert(activityLogs).values({userId:req.user.userId,action:'update',entityType:kind,entityId:row.id,details:'Workflow version '+row.version});}
router.get('/requisitions',handler(async(req,res)=>{hr(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT r.*,e.user_id AS requester_user_id,EXISTS(SELECT 1 FROM requisition_editors x WHERE x.requisition_id=r.id AND x.user_id=${req.user.userId}) AS is_editor FROM job_requisitions r JOIN employees e ON e.id=r.requested_by ORDER BY r.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows.map((r:any)=>({...r,canApprove:approval(req)&&r.requester_user_id!==req.user.userId&&!r.is_editor})),canEdit:hasPermission(req.user.role,'recruitment_onboarding','update')});}));
router.post('/requisitions/:id/actions',handler(async(req,res)=>{
 hr(req,true);const recordId=id.parse(Number(req.params.id));const input=z.object({version:id,action:z.enum(['edit','submit','approve','return','open','hold','close','cancel']),reason,fields:z.object({jobTitle:text,department:text,location:text,numberOfVacancies:z.number().int().min(1).max(10000),jobDescription:z.string().trim().min(5).max(10000)}).strict().optional()}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{const rows=await tx.execute(sql`SELECT * FROM job_requisitions WHERE id=${recordId} FOR UPDATE`);const r=rows.rows[0] as any;if(!r)throw new OnboardingError(404,'Requisition not found');if(r.version!==input.version)throw new OnboardingError(409,'Requisition changed; reload');const [requester]=await tx.select().from(employees).where(eq(employees.id,r.requested_by));let status=r.status,approver=r.approved_by,approvedAt=r.approved_at;
 if(input.action==='edit'){if(status!=='draft'||!input.fields)throw new OnboardingError(409,'Only a draft can be edited');const f=input.fields;const result=await tx.execute(sql`UPDATE job_requisitions SET job_title=${f.jobTitle},department=${f.department},location=${f.location},number_of_vacancies=${f.numberOfVacancies},job_description=${f.jobDescription},updated_at=now() WHERE id=${recordId} RETURNING *`);await tx.execute(sql`INSERT INTO requisition_editors(requisition_id,user_id) VALUES (${recordId},${req.user.userId}) ON CONFLICT DO NOTHING`);await history(tx,req,'requisition',result.rows[0],input.reason);return result.rows[0];}
 const transitions:Record<string,string[]>={draft:['submit','cancel'],pending_approval:['approve','return','cancel'],approved:['open','cancel'],open:['hold','close','cancel'],on_hold:['open','close','cancel']};if(!transitions[status]?.includes(input.action))throw new OnboardingError(409,'This requisition transition is not available');
 if(['approve','return'].includes(input.action)){const editors=await tx.execute(sql`SELECT 1 FROM requisition_editors WHERE requisition_id=${recordId} AND user_id=${req.user.userId}`);if(!approval(req)||requester.userId===req.user.userId||editors.rows.length)throw new OnboardingError(403,'Independent recruitment approval is required');if(input.action==='approve'){const [owner]=await tx.select().from(employees).where(eq(employees.userId,req.user.userId));if(!owner||owner.status!=='active')throw new OnboardingError(400,'Approver requires an active linked employee');approver=owner.id;approvedAt=new Date();}}
 if(['close','cancel'].includes(input.action)){const offers=await tx.execute(sql`SELECT o.id FROM job_offers o JOIN job_applications a ON a.id=o.application_id WHERE a.requisition_id=${recordId} AND (o.status IN ('draft','pending_approval','pending') OR (o.status='accepted' AND NOT EXISTS(SELECT 1 FROM recruitment_handoffs h WHERE h.offer_id=o.id))) LIMIT 1`);if(offers.rows.length)throw new OnboardingError(409,'Resolve pending offers and accepted-offer handoffs first');}
 status=({submit:'pending_approval',approve:'approved',return:'draft',open:'open',hold:'on_hold',close:'closed',cancel:'cancelled'} as any)[input.action];const result=await tx.execute(sql`UPDATE job_requisitions SET status=${status},approved_by=${approver},approved_at=${approvedAt},updated_at=now() WHERE id=${recordId} RETURNING *`);await history(tx,req,'requisition',result.rows[0],input.reason);return result.rows[0];});res.json(saved);
}));
router.get('/offers',handler(async(req,res)=>{hr(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const rows=await db.execute(sql`SELECT o.*,c.full_name_en AS candidate_name,j.job_title,e.user_id AS creator_user_id,EXISTS(SELECT 1 FROM offer_editors x WHERE x.offer_id=o.id AND x.user_id=${req.user.userId}) AS is_editor,EXISTS(SELECT 1 FROM recruitment_handoffs h WHERE h.offer_id=o.id) AS handed_off FROM job_offers o JOIN employees e ON e.id=o.created_by JOIN job_applications a ON a.id=o.application_id JOIN candidates c ON c.id=a.candidate_id JOIN job_requisitions j ON j.id=a.requisition_id ORDER BY o.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:rows.rows.map((r:any)=>({...r,canApprove:approval(req)&&r.creator_user_id!==req.user.userId&&!r.is_editor})),canEdit:hasPermission(req.user.role,'recruitment_onboarding','update')});}));
router.post('/offers/:id/actions',handler(async(req,res)=>{
 hr(req,true);const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['submit','approve','return','accept','decline','expire','withdraw','revise']),reason,acceptanceDate:civilDate.optional()}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT a.requisition_id FROM job_offers o JOIN job_applications a ON a.id=o.application_id WHERE o.id=${recordId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Offer not found');const jobs=await tx.execute(sql`SELECT * FROM job_requisitions WHERE id=${lookup.rows[0].requisition_id} FOR UPDATE`);const job=jobs.rows[0] as any;
 const rows=await tx.execute(sql`SELECT * FROM job_offers WHERE id=${recordId} FOR UPDATE`),r=rows.rows[0] as any;if(r.version!==input.version)throw new OnboardingError(409,'Offer changed; reload');const link=await tx.execute(sql`SELECT 1 FROM recruitment_handoffs WHERE offer_id=${recordId}`);if(link.rows.length)throw new OnboardingError(409,'A handed-off offer is final');
 const actions:Record<string,string[]>={draft:['submit','withdraw'],pending_approval:['approve','return','withdraw'],pending:['accept','decline','expire','withdraw','revise']};if(!actions[r.status]?.includes(input.action))throw new OnboardingError(409,'This offer action is unavailable');let status='',approvedBy=r.approved_by_user,acceptance=null;const today=new Date().toISOString().slice(0,10);
 if(['submit','approve','accept'].includes(input.action)&&job.status!=='open')throw new OnboardingError(409,'The requisition must be open');
 if(['approve','return'].includes(input.action)){const [creator]=await tx.select().from(employees).where(eq(employees.id,r.created_by));const editors=await tx.execute(sql`SELECT 1 FROM offer_editors WHERE offer_id=${recordId} AND user_id=${req.user.userId}`);if(!approval(req)||creator.userId===req.user.userId||editors.rows.length)throw new OnboardingError(403,'An independent recruitment approver is required');if(input.action==='approve'){if(r.expiry_date<today)throw new OnboardingError(409,'This draft has expired; withdraw it and prepare a replacement');approvedBy=req.user.userId;}}
 if(input.action==='accept'){if(!r.approved_by_user)throw new OnboardingError(409,'Legacy offer needs independent approval before acceptance; withdraw and create a controlled offer');if(!input.acceptanceDate||input.acceptanceDate<r.offer_date||input.acceptanceDate>r.expiry_date||input.acceptanceDate>today)throw new OnboardingError(400,'Record an acceptance date within the offer period');const accepted=await tx.execute(sql`SELECT count(*)::int AS n FROM job_offers o JOIN job_applications a ON a.id=o.application_id WHERE a.requisition_id=${job.id} AND o.status='accepted'`);if(Number(accepted.rows[0].n)>=job.number_of_vacancies)throw new OnboardingError(409,'Accepted offers already fill this requisition');acceptance=input.acceptanceDate;}
 if(input.action==='revise'){await tx.execute(sql`INSERT INTO lifecycle_history(kind,record_id,version,snapshot,actor_id,reason) VALUES ('offer',${r.id},${r.version},${JSON.stringify(r)}::jsonb,${req.user.userId},'Issued terms before revision') ON CONFLICT DO NOTHING`);await tx.execute(sql`INSERT INTO offer_editors(offer_id,user_id) VALUES (${recordId},${req.user.userId}) ON CONFLICT DO NOTHING`);approvedBy=null;}
 if(input.action==='expire'&&r.expiry_date>=today)throw new OnboardingError(409,'Offer has not expired');status=({submit:'pending_approval',approve:'pending',return:'draft',accept:'accepted',decline:'declined',expire:'expired',withdraw:'withdrawn',revise:'draft'} as any)[input.action];
 const result=await tx.execute(sql`UPDATE job_offers SET status=${status},approved_by_user=${approvedBy},offer_letter=CASE WHEN ${input.action}='revise' THEN NULL ELSE offer_letter END,acceptance_date=${acceptance},decline_reason=${['decline','withdraw'].includes(input.action)?input.reason:null},updated_at=now() WHERE id=${recordId} RETURNING *`);await history(tx,req,'offer',result.rows[0],input.reason);return result.rows[0];});res.json(saved);
}));
router.get('/requirements',handler(async(req,res)=>{hr(req);const r=await db.execute(sql`SELECT c.id,c.name,t.id AS template_id,coalesce(t.version,0) AS version,coalesce(t.document_types,'[]'::jsonb) AS document_types FROM onboarding_checklists c LEFT JOIN LATERAL(SELECT * FROM onboarding_requirement_templates WHERE checklist_id=c.id ORDER BY version DESC LIMIT 1)t ON true ORDER BY c.id DESC LIMIT 100`);res.json({items:r.rows,canEdit:isAdmin(req)});}));
router.post('/requirements/:id',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrators configure required documents');const checklistId=id.parse(Number(req.params.id)),input=z.object({version:z.number().int().min(0),documentTypes:z.array(text).max(30).refine(a=>new Set(a).size===a.length,'Document types must be unique'),reason}).strict().parse(req.body);
 const result=await db.transaction(async tx=>{const c=await tx.execute(sql`SELECT id FROM onboarding_checklists WHERE id=${checklistId} FOR UPDATE`);if(!c.rows.length)throw new OnboardingError(404,'Checklist not found');const latest=await tx.execute(sql`SELECT version FROM onboarding_requirement_templates WHERE checklist_id=${checklistId} ORDER BY version DESC LIMIT 1`);if(Number(latest.rows[0]?.version||0)!==input.version)throw new OnboardingError(409,'Requirements changed; reload');const r=await tx.execute(sql`INSERT INTO onboarding_requirement_templates(checklist_id,version,document_types,created_by,reason) VALUES (${checklistId},${input.version+1},${JSON.stringify(input.documentTypes)}::jsonb,${req.user.userId},${input.reason}) RETURNING *`);await history(tx,req,'requirement_template',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(result);
}));
router.get('/courses',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrator catalogue access required');const r=await db.execute(sql`SELECT id,title,description,provider,active,version FROM training_courses ORDER BY id DESC LIMIT 100`);res.json(r.rows);}));
router.post('/courses/:id',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrators maintain courses');const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,title:text,description:z.string().trim().min(5).max(5000),provider:text,active:z.boolean(),reason}).strict().parse(req.body);const saved=await db.transaction(async tx=>{const old=await tx.execute(sql`SELECT version FROM training_courses WHERE id=${recordId} FOR UPDATE`);if(!old.rows.length)throw new OnboardingError(404,'Course not found');if(old.rows[0].version!==input.version)throw new OnboardingError(409,'Course changed; reload');const r=await tx.execute(sql`UPDATE training_courses SET title=${input.title},description=${input.description},provider=${input.provider},active=${input.active},updated_at=now() WHERE id=${recordId} RETURNING *`);await history(tx,req,'course',r.rows[0],input.reason);return r.rows[0];});res.json(saved);}));
router.post('/assessments/:id/reassign',handler(async(req,res)=>{
 if(!['admin','super_admin','hr_director','hr'].includes(req.user.role))throw new OnboardingError(403,'HR manages reviewer reassignment');const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,reviewerId:id,reason}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT cycle_id FROM cycle_assessments WHERE id=${recordId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Review not found');const cycles=await tx.execute(sql`SELECT status FROM review_cycles WHERE id=${lookup.rows[0].cycle_id} FOR UPDATE`);const rows=await tx.execute(sql`SELECT * FROM cycle_assessments WHERE id=${recordId} FOR UPDATE`);const r=rows.rows[0] as any;if(r.version!==input.version||r.status==='published'||cycles.rows[0].status!=='open')throw new OnboardingError(409,'Only an unpublished review in an open cycle can be reassigned');
 const [subject]=await tx.select().from(employees).where(and(eq(employees.id,r.employee_id),employeeScope(req.user,'performance_management','update')));if(!subject)throw new OnboardingError(404,'Employee not found');if(subject.userId===req.user.userId||input.reviewerId===subject.id||input.reviewerId===r.reviewer_id)throw new OnboardingError(403,'Choose another independent reviewer');
 const reviewers=await tx.execute(sql`SELECT e.id,e.user_id,u.role,u.department FROM employees e JOIN users u ON u.id=e.user_id WHERE e.id=${input.reviewerId} AND e.status='active' AND u.is_active=true AND u.approval_status='approved'`);const reviewer=reviewers.rows[0] as any;if(!reviewer)throw new OnboardingError(400,'Reviewer needs an active linked account');const [allowed]=await tx.select({id:employees.id}).from(employees).where(and(eq(employees.id,subject.id),employeeScope({userId:reviewer.user_id,role:reviewer.role,department:reviewer.department} as any,'performance_management','update')));if(!allowed)throw new OnboardingError(403,'Reviewer cannot manage this employee');
 const result=await tx.execute(sql`UPDATE cycle_assessments SET reviewer_id=${input.reviewerId},status='draft',ratings='[]'::jsonb,score=NULL,development_plan='',version=version+1 WHERE id=${recordId} RETURNING *`);await history(tx,req,'assessment',result.rows[0],input.reason);return result.rows[0];});res.json(saved);
}));
router.get('/history/:kind/:id',handler(async(req,res)=>{const kind=z.enum(['requisition','offer','requirement_template','course','interview','onboarding_task']).parse(req.params.kind),recordId=id.parse(Number(req.params.id));if(kind==='course'){if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');}else hr(req);const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind=${kind} AND (${kind} <> 'requirement_template' AND record_id=${recordId} OR ${kind} = 'requirement_template' AND record_id IN (SELECT id FROM onboarding_requirement_templates WHERE checklist_id=(SELECT checklist_id FROM onboarding_requirement_templates WHERE id=${recordId}))) ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));
const offerTerms=z.object({version:id,offerDate:civilDate,expiryDate:civilDate,startDate:civilDate.nullable(),salary:z.number().int().positive().max(100000000),benefits:z.string().trim().max(5000),reason}).strict();
router.post('/offers/:id/terms',handler(async(req,res)=>{
 hr(req,true);const recordId=id.parse(Number(req.params.id)),input=offerTerms.parse(req.body);
 if(input.expiryDate<input.offerDate||(input.startDate&&input.startDate<input.offerDate))throw new OnboardingError(400,'Check offer dates');
 const saved=await db.transaction(async tx=>{const rows=await tx.execute(sql`SELECT * FROM job_offers WHERE id=${recordId} FOR UPDATE`),row=rows.rows[0] as any;
 if(!row)throw new OnboardingError(404,'Offer not found');if(row.version!==input.version||row.status!=='draft')throw new OnboardingError(409,'Only the current draft can be edited');
 const r=await tx.execute(sql`UPDATE job_offers SET offer_date=${input.offerDate},expiry_date=${input.expiryDate},start_date=${input.startDate},salary=${input.salary},benefits=${JSON.stringify(input.benefits)}::json,approved_by_user=NULL,offer_letter=NULL,updated_at=now() WHERE id=${recordId} RETURNING *`);
 await tx.execute(sql`INSERT INTO offer_editors(offer_id,user_id) VALUES (${recordId},${req.user.userId}) ON CONFLICT DO NOTHING`);await history(tx,req,'offer',r.rows[0],input.reason);return r.rows[0];});res.json(saved);
}));
router.get('/waiver-policy',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');const r=await db.execute(sql`SELECT * FROM onboarding_waiver_policies ORDER BY version DESC LIMIT 1`);res.json(r.rows[0]||{version:0,document_types:[]});}));
router.post('/waiver-policy',handler(async(req,res)=>{
 if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');const input=z.object({version:z.number().int().min(0),documentTypes:z.array(text).max(30).refine(a=>new Set(a).size===a.length,'Use unique document types'),reason}).strict().parse(req.body);
 const result=await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(73101)`);const old=await tx.execute(sql`SELECT version FROM onboarding_waiver_policies ORDER BY version DESC LIMIT 1`);if(Number(old.rows[0]?.version||0)!==input.version)throw new OnboardingError(409,'Policy changed; reload');const r=await tx.execute(sql`INSERT INTO onboarding_waiver_policies(version,document_types,created_by,reason) VALUES (${input.version+1},${JSON.stringify(input.documentTypes)}::jsonb,${req.user.userId},${input.reason}) RETURNING *`);await history(tx,req,'waiver_policy',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(result);
}));
router.post('/documents/:id/waiver',handler(async(req,res)=>{
 if(!isAdmin(req))throw new OnboardingError(403,'An administrator must decide document waivers');const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['waive','revoke']),reason}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{const lookup=await tx.execute(sql`SELECT onboarding_id FROM onboarding_document_checks WHERE id=${recordId}`);if(!lookup.rows.length)throw new OnboardingError(404,'Requirement not found');const parents=await tx.execute(sql`SELECT o.*,e.user_id FROM employee_onboarding o JOIN employees e ON e.id=o.employee_id WHERE o.id=${lookup.rows[0].onboarding_id} FOR UPDATE OF o`);const parent=parents.rows[0] as any;
 if(parent.status!=='in_progress')throw new OnboardingError(409,'Only active onboarding can change requirements');if(parent.user_id===req.user.userId)throw new OnboardingError(403,'Another administrator must decide your waiver');
 const rows=await tx.execute(sql`SELECT * FROM onboarding_document_checks WHERE id=${recordId} FOR UPDATE`),row=rows.rows[0] as any;if(row.version!==input.version)throw new OnboardingError(409,'Requirement changed; reload');let policyId=null;
 if(input.action==='waive'){if(row.status!=='required')throw new OnboardingError(409,'Only an unverified required document can be waived');await tx.execute(sql`SELECT pg_advisory_xact_lock(73101)`);const policies=await tx.execute(sql`SELECT * FROM onboarding_waiver_policies ORDER BY version DESC LIMIT 1`),policy=policies.rows[0] as any;if(!policy?.document_types.includes(row.document_type))throw new OnboardingError(409,'This document type is not eligible under the current waiver policy');policyId=policy.id;}else if(row.status!=='waived')throw new OnboardingError(409,'There is no active waiver');
 const r=await tx.execute(sql`UPDATE onboarding_document_checks SET status=${input.action==='waive'?'waived':'required'},waiver_policy_id=${policyId},verified_by=${input.action==='waive'?req.user.userId:null},document_id=NULL,document_updated_at=NULL,version=version+1 WHERE id=${recordId} RETURNING *`);await history(tx,req,'document',r.rows[0],input.reason);return r.rows[0];});res.json(saved);
}));
router.get('/my-tasks',handler(async(req,res)=>{const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT t.id,t.version,t.status,t.comments,t.review_required,t.review_state,t.assignee_id,t.due_date,c.task_name,o.status AS onboarding_status FROM onboarding_tasks t JOIN employees e ON e.id=t.assignee_id JOIN checklist_tasks c ON c.id=t.task_id JOIN employee_onboarding o ON o.id=t.onboarding_id WHERE e.user_id=${req.user.userId} AND e.status='active' ORDER BY t.due_date,t.id LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows});}));
router.post('/my-tasks/:id',handler(async(req,res)=>{const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,status:z.enum(['in_progress','completed']),comments:z.string().trim().min(5).max(5000)}).strict().parse(req.body);const r=await db.execute(sql`SELECT t.assignee_id,t.due_date FROM onboarding_tasks t JOIN employees e ON e.id=t.assignee_id WHERE t.id=${recordId} AND e.user_id=${req.user.userId} AND e.status='active'`);if(!r.rows.length)throw new OnboardingError(404,'Assigned task not found');const row=r.rows[0];res.json(await changeOnboardingTask(recordId,{expectedVersion:input.version,status:input.status,comments:input.comments,assigneeId:row.assignee_id,dueDate:row.due_date},req.user.userId,true));}));

const scheduleFields=z.object({applicationId:id,interviewerId:id,startsAt:z.string().datetime({offset:true}),durationMinutes:z.number().int().min(15).max(480),interviewType:z.enum(['phone','video','in-person']),interviewRound:z.enum(['first','second','final','technical','hr']),reason}).strict();
async function schedule(tx:any,req:any,input:z.infer<typeof scheduleFields>,recordId?:number,version?:number){
 // Scheduling is low volume; one transaction lock also covers conflicts across applications.
 await tx.execute(sql`SELECT pg_advisory_xact_lock(73102)`);
 if(recordId){const r=await tx.execute(sql`SELECT * FROM interviews WHERE id=${recordId} FOR UPDATE`),old=r.rows[0] as any;if(!old)throw new OnboardingError(404,'Interview not found');if(old.version!==version||old.status!=='scheduled'||old.application_id!==input.applicationId)throw new OnboardingError(409,'Only the current scheduled interview can be rescheduled');}
 const app=await tx.execute(sql`SELECT a.candidate_id,a.status,j.status AS job_status FROM job_applications a JOIN job_requisitions j ON j.id=a.requisition_id WHERE a.id=${input.applicationId} FOR SHARE OF a,j`);const a=app.rows[0] as any;if(!a||a.status!=='interview'||a.job_status!=='open')throw new OnboardingError(409,'Select an interview-stage application with an open requisition');
 const owner=await tx.execute(sql`SELECT id FROM employees WHERE id=${input.interviewerId} AND status='active' FOR UPDATE`);if(!owner.rows.length)throw new OnboardingError(400,'Choose an active interviewer');
 const start=new Date(input.startsAt),end=new Date(start.getTime()+input.durationMinutes*60000);if(start.getTime()<=Date.now())throw new OnboardingError(400,'Schedule a future interview');
 const employment=await tx.execute(sql`SELECT id FROM employees WHERE id=${input.interviewerId} AND joining_date<=(${start.toISOString()}::timestamptz AT TIME ZONE 'Asia/Qatar')::date AND (contract_end_date IS NULL OR contract_end_date>= ((${end.toISOString()}::timestamptz-interval '1 millisecond') AT TIME ZONE 'Asia/Qatar')::date) AND (termination_date IS NULL OR termination_date> ((${end.toISOString()}::timestamptz-interval '1 millisecond') AT TIME ZONE 'Asia/Qatar')::date)`);if(!employment.rows.length)throw new OnboardingError(409,'Interviewer employment dates must cover the interview');
 const leave=await tx.execute(sql`SELECT id FROM leaves WHERE employee_id=${input.interviewerId} AND status='approved' AND start_date<=((${end.toISOString()}::timestamptz-interval '1 millisecond') AT TIME ZONE 'Asia/Qatar')::date AND end_date>=(${start.toISOString()}::timestamptz AT TIME ZONE 'Asia/Qatar')::date LIMIT 1`);if(leave.rows.length)throw new OnboardingError(409,'Interviewer has approved leave during this booking');
 const work=await tx.execute(sql`SELECT a.id FROM workforce_assignments a JOIN workforce_shifts s ON s.id=a.shift_id WHERE a.employee_id=${input.interviewerId} AND a.status='accepted' AND s.cancelled_at IS NULL AND s.start_at<${end.toISOString()}::timestamptz AND s.end_at>${start.toISOString()}::timestamptz LIMIT 1`);if(work.rows.length)throw new OnboardingError(409,'Interviewer has an accepted workforce shift during this booking');
 const legacy=await tx.execute(sql`SELECT id FROM shift_schedules WHERE employee_id=${input.interviewerId} AND start_time<${end.toISOString()}::timestamptz AND end_time>${start.toISOString()}::timestamptz UNION ALL SELECT id FROM event_staff_assignments WHERE employee_id=${input.interviewerId} AND status NOT IN ('declined','cancelled','no_show') AND start_time<${end.toISOString()}::timestamptz AND end_time>${start.toISOString()}::timestamptz LIMIT 1`);if(legacy.rows.length)throw new OnboardingError(409,'Interviewer has a conflicting attendance or event schedule');
 const conflict=await tx.execute(sql`SELECT i.id FROM interviews i JOIN job_applications a ON a.id=i.application_id WHERE i.status='scheduled' AND i.id<>${recordId||0} AND (i.interviewer_id=${input.interviewerId} OR a.candidate_id=${a.candidate_id}) AND i.interview_date<${end.toISOString()}::timestamptz AT TIME ZONE 'UTC' AND i.interview_date+i.duration_minutes*interval '1 minute'>${start.toISOString()}::timestamptz AT TIME ZONE 'UTC' LIMIT 1`);if(conflict.rows.length)throw new OnboardingError(409,'The candidate or interviewer already has an overlapping interview');
 const r=recordId?await tx.execute(sql`UPDATE interviews SET interviewer_id=${input.interviewerId},interview_date=${start.toISOString()}::timestamptz AT TIME ZONE 'UTC',duration_minutes=${input.durationMinutes},interview_type=${input.interviewType},interview_round=${input.interviewRound},updated_at=now() WHERE id=${recordId} RETURNING *`):await tx.execute(sql`INSERT INTO interviews(application_id,interviewer_id,interview_date,duration_minutes,interview_type,interview_round,status) VALUES (${input.applicationId},${input.interviewerId},${start.toISOString()}::timestamptz AT TIME ZONE 'UTC',${input.durationMinutes},${input.interviewType},${input.interviewRound},'scheduled') RETURNING *`);await history(tx,req,'interview',r.rows[0],input.reason);return r.rows[0];
}
router.get('/interview-options',handler(async(req,res)=>{hr(req);const q=z.string().trim().max(100).default('').parse(req.query.q);const applications=await db.execute(sql`SELECT a.id,c.full_name_en AS name,j.job_title FROM job_applications a JOIN candidates c ON c.id=a.candidate_id JOIN job_requisitions j ON j.id=a.requisition_id WHERE a.status='interview' AND j.status='open' AND strpos(lower(c.full_name_en||' '||j.job_title),lower(${q}))>0 ORDER BY a.id DESC LIMIT 100`);const people=await db.execute(sql`SELECT id,first_name||' '||last_name AS name FROM employees WHERE status='active' AND strpos(lower(first_name||' '||last_name),lower(${q}))>0 ORDER BY id LIMIT 100`);res.json({applications:applications.rows,people:people.rows});}));
router.get('/interviews',handler(async(req,res)=>{hr(req);const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT i.*,to_char(i.interview_date,'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS starts_at,c.full_name_en AS candidate_name,e.first_name||' '||e.last_name AS interviewer_name FROM interviews i JOIN employees e ON e.id=i.interviewer_id JOIN job_applications a ON a.id=i.application_id JOIN candidates c ON c.id=a.candidate_id ORDER BY i.interview_date DESC,i.id DESC LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows,canEdit:hasPermission(req.user.role,'recruitment_onboarding','update')});}));
router.post('/interviews',handler(async(req,res)=>{hr(req,true);const input=scheduleFields.parse(req.body);res.status(201).json(await db.transaction(tx=>schedule(tx,req,input)));}));
router.post('/interviews/:id/reschedule',handler(async(req,res)=>{hr(req,true);const recordId=id.parse(Number(req.params.id)),{version,...input}=scheduleFields.extend({version:id}).parse(req.body);res.json(await db.transaction(tx=>schedule(tx,req,input,recordId,version)));}));
router.post('/interviews/:id/decision',handler(async(req,res)=>{
 hr(req,true);const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['completed','cancelled','no-show']),rating:z.number().int().min(1).max(5).optional(),recommendation:z.enum(['hire','reject','hold']).optional(),reason}).strict().parse(req.body);
 const saved=await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(73102)`);const r=await tx.execute(sql`SELECT *,interview_date<=CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AS started FROM interviews WHERE id=${recordId} FOR UPDATE`),row=r.rows[0] as any;if(!row)throw new OnboardingError(404,'Interview not found');if(row.version!==input.version||row.status!=='scheduled')throw new OnboardingError(409,'This interview is no longer awaiting a decision');if(input.action!=='cancelled'&&!row.started)throw new OnboardingError(409,'Wait until the interview has started');if(input.action==='completed'&&(!input.rating||!input.recommendation))throw new OnboardingError(400,'Completion requires a rating and recommendation');const result=await tx.execute(sql`UPDATE interviews SET status=${input.action},rating=${input.action==='completed'?input.rating:null},recommendation=${input.action==='completed'?input.recommendation:null},feedback=${input.reason},updated_at=now() WHERE id=${recordId} RETURNING *`);await history(tx,req,'interview',result.rows[0],input.reason);return result.rows[0];});res.json(saved);
}));

router.get('/task-review-policy',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');const r=await db.execute(sql`SELECT * FROM onboarding_review_policies ORDER BY version DESC LIMIT 1`);res.json(r.rows[0]||{version:0,owner_groups:[]});}));
router.post('/task-review-policy',handler(async(req,res)=>{
 if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');const input=z.object({version:z.number().int().min(0),ownerGroups:z.array(z.enum(['hr','manager','it','new_hire'])).max(4).refine(a=>new Set(a).size===a.length,'Use unique groups'),reason}).strict().parse(req.body);
 const result=await db.transaction(async tx=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(73103)`);const old=await tx.execute(sql`SELECT version FROM onboarding_review_policies ORDER BY version DESC LIMIT 1`);if(Number(old.rows[0]?.version||0)!==input.version)throw new OnboardingError(409,'Policy changed; reload');const r=await tx.execute(sql`INSERT INTO onboarding_review_policies(version,owner_groups,created_by,reason) VALUES (${input.version+1},${JSON.stringify(input.ownerGroups)}::jsonb,${req.user.userId},${input.reason}) RETURNING *`);await history(tx,req,'task_review_policy',r.rows[0],input.reason);return r.rows[0];});res.status(201).json(result);
}));
router.get('/task-reviews',handler(async(req,res)=>{hr(req);const includeCompleted=z.enum(['false','true']).default('false').parse(req.query.includeCompleted)==='true';const page=z.coerce.number().int().min(1).default(1).parse(req.query.page);const r=await db.execute(sql`SELECT t.*,o.status AS onboarding_status,c.task_name,e.first_name||' '||e.last_name AS employee_name,owner.first_name||' '||owner.last_name AS owner_name,e.user_id AS subject_user_id,owner.user_id AS owner_user_id FROM onboarding_tasks t JOIN employee_onboarding o ON o.id=t.onboarding_id JOIN employees e ON e.id=o.employee_id JOIN checklist_tasks c ON c.id=t.task_id LEFT JOIN employees owner ON owner.id=t.assignee_id WHERE t.review_required=true AND (o.status='in_progress' OR ${includeCompleted}) ORDER BY (t.review_state='pending') DESC,t.due_date,t.id LIMIT 25 OFFSET ${(page-1)*25}`);res.json({items:r.rows.map((r:any)=>({...r,canReview:r.onboarding_status==='in_progress'&&hasPermission(req.user.role,'recruitment_onboarding','approve')&&r.submitted_by!==req.user.userId&&r.subject_user_id!==req.user.userId&&r.owner_user_id!==req.user.userId})),canEdit:hasPermission(req.user.role,'recruitment_onboarding','update')});}));
router.post('/task-reviews/:id',handler(async(req,res)=>{hr(req,true);if(!approval(req))throw new OnboardingError(403,'Recruitment approval permission required');const recordId=id.parse(Number(req.params.id)),input=z.object({version:id,action:z.enum(['approve','return']),reason}).strict().parse(req.body);const rows=await db.execute(sql`SELECT assignee_id,due_date FROM onboarding_tasks WHERE id=${recordId}`);if(!rows.rows.length)throw new OnboardingError(404,'Task not found');const r=rows.rows[0];res.json(await changeOnboardingTask(recordId,{expectedVersion:input.version,status:input.action==='approve'?'completed':'in_progress',comments:input.reason,assigneeId:r.assignee_id,dueDate:r.due_date},req.user.userId,false,input.action));}));
router.get('/policy-history/:kind',handler(async(req,res)=>{if(!isAdmin(req))throw new OnboardingError(403,'Administrator access required');const kind=z.enum(['task_review_policy','waiver_policy']).parse(req.params.kind);const r=await db.execute(sql`SELECT version,reason,created_at,snapshot FROM lifecycle_history WHERE kind=${kind} ORDER BY version DESC LIMIT 100`);res.json(r.rows);}));

export default router;
