import {useDeferredValue,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'wouter';
import {Fingerprint,ScanFace,ScanLine,ContactRound,Monitor,DoorOpen,Plug,MapPin,Plus,Search,Settings2,History,Trash2,Network,FileDown,Cloud,Users,ShieldCheck,CheckCircle2,ArrowRight,RefreshCw,type LucideIcon} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,QueryError,Section,Table,fieldClass} from '@/components/hr/Operations';
import {AttendanceLocationManagement,type AttendanceLocationContext} from '@/components/hr/AttendanceLocations';
import {MetricCard} from '@/components/ux/ModuleVisuals';
import {AnimatedIcon} from '@/components/ux/ExperienceUI';
import {apiJson} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {devicePresets,applyDevicePreset,deviceKinds,deviceKindLabels,connectionMethods,connectionMethodLabels,profileStatuses,profileStatusLabels,emptyDevice,deviceDefinition,deviceSetupIssues,type DeviceDefinition,type DeviceContext,type DeviceProfile,type DeviceRevision,type DevicePreset} from '@shared/device-connections';

const base='/api/settings/devices';
const icons:Record<DeviceDefinition['kind'],LucideIcon>={fingerprint:Fingerprint,face:ScanFace,multi_biometric:ScanFace,card_reader:ContactRound,qr_scanner:ScanLine,kiosk:Monitor,access_terminal:DoorOpen,other:Plug};
const methodIcons:Record<DeviceDefinition['method'],LucideIcon>={local_bridge:Network,local_api:Network,vendor_cloud:Cloud,file_export:FileDown};
type Person={id:number;name:string;staffId:string;status:string};

export default function DeviceConnections(){
  const [tab,setTab]=useState(()=>{const value=new URLSearchParams(window.location.search).get('tab');return value&&['devices','presets','geofencing','guide'].includes(value)?value:'presets';});
  const [search,setSearch]=useState(''),[kind,setKind]=useState('all'),[site,setSite]=useState('all'),[status,setStatus]=useState('current');
  const [editing,setEditing]=useState<{profile:DeviceProfile|null;preset?:DevicePreset}|null>(null),[history,setHistory]=useState<DeviceProfile|null>(null);
  const cache=useQueryClient(),devices=useQuery<DeviceContext>({queryKey:[base]}),location=useQuery<AttendanceLocationContext>({queryKey:['/api/attendance/location/context']});
  const fences=useQuery<{id:number;config:{enabled:boolean;startsOn:string|null;endsOn:string|null}}[]>({queryKey:['/api/attendance/location/locations'],enabled:!!location.data?.canManage});
  const data=devices.data,current=data?.devices.filter(d=>d.config.status!=='archived')||[],complete=current.filter(d=>!deviceSetupIssues(d.config).length).length;
  const rows=(data?.devices||[]).filter(d=>(status==='all'||status==='current'&&d.config.status!=='archived'||d.config.status===status)&&(kind==='all'||d.config.kind===kind)&&(site==='all'||String(d.config.siteId??'unassigned')===site)&&`${d.config.name} ${d.config.brand} ${d.config.model} ${d.config.serial}`.toLowerCase().includes(search.toLowerCase()));
  const refresh=()=>cache.invalidateQueries({queryKey:[base]});
  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label="Device profiles" value={devices.isLoading?'…':devices.error?'—':current.length} icon={Fingerprint}/><MetricCard label="Setup details complete" value={devices.isLoading?'…':devices.error?'—':complete} detail="Live connector still required" icon={CheckCircle2}/><MetricCard label="Saved boundaries" value={fences.isLoading?'…':fences.error?'—':fences.data?.length??'—'} icon={MapPin}/><MetricCard label="GPS enforcement" value={location.isLoading?'…':location.error?'—':location.data?.policy.config.required?'On':'Off'} icon={ShieldCheck} tone={location.data?.policy.config.required?'positive':'attention'}/></div>
    <QueryError error={devices.error||location.error||fences.error}/>{devices.error&&<Button variant="outline" onClick={()=>devices.refetch()}>Reload device settings</Button>}
    <Tabs value={tab} onValueChange={setTab} className="min-w-0"><TabsList aria-label="Devices and attendance connections"><TabsTrigger value="presets">Setup presets ({devicePresets.length})</TabsTrigger><TabsTrigger value="devices">My devices</TabsTrigger><TabsTrigger value="geofencing">Geofencing</TabsTrigger><TabsTrigger value="guide">Connection guide</TabsTrigger></TabsList>
      <TabsContent value="presets" className="space-y-5 pt-3"><PresetLibrary disabled={!data||data.devices.length>=data.limit} choose={preset=>setEditing({profile:null,preset})}/></TabsContent>
      <TabsContent value="devices" className="space-y-5 pt-3">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Your device directory</h2><p className="mt-1 text-sm text-muted-foreground">Terminals, scanners and kiosks across your sites.</p></div><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Refresh device profiles" disabled={devices.isFetching} onClick={()=>void refresh()}><RefreshCw className="h-4 w-4"/></Button><Button disabled={!data||data.devices.length>=data.limit} onClick={()=>setEditing({profile:null})}><Plus className="mr-2 h-4 w-4"/>Add device</Button></div></div>
        <div className="flex flex-wrap items-center gap-3 rounded-2xl border border-primary/15 bg-primary/5 p-4"><Plug className="h-5 w-5 shrink-0 text-primary"/><p className="min-w-0 flex-1 text-sm"><strong>Device sync needs a connector.</strong> Save setup details here; no hardware is connected yet.</p><Button variant="ghost" size="sm" onClick={()=>setTab('guide')}>View setup steps<ArrowRight className="ml-2 h-4 w-4"/></Button></div>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Search device profiles" className="pl-9" type="search" value={search} placeholder="Device, model or serial…" onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter device type" className={fieldClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All device types</option>{deviceKinds.map(value=><option key={value} value={value}>{deviceKindLabels[value]}</option>)}</select><select aria-label="Filter work site" className={fieldClass} value={site} onChange={e=>setSite(e.target.value)}><option value="all">All work sites</option><option value="unassigned">Site not assigned</option>{data?.sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><select aria-label="Filter profile status" className={fieldClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="current">Current profiles</option><option value="all">Including archived</option>{profileStatuses.map(value=><option key={value} value={value}>{profileStatusLabels[value]}</option>)}</select></div>
        {devices.isLoading?<p role="status" className="p-8 text-center">Loading device profiles…</p>:!devices.error&&!rows.length?<div className="rounded-2xl border border-dashed bg-card px-6 py-12 text-center"><div className="mx-auto mb-4 flex w-fit gap-4 rounded-2xl bg-primary/5 p-5 text-primary"><Fingerprint/><ScanFace/><ScanLine/></div><h3 className="font-semibold">{data?.devices.length?'No devices match these filters':'Add your first attendance device'}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">{data?.devices.length?'Change the type, site or search to find a device.':'Choose its type, assign a workplace and map employee IDs.'}</p>{!data?.devices.length&&<Button className="mt-5" disabled={!data} onClick={()=>setEditing({profile:null})}><Plus className="mr-2 h-4 w-4"/>Register a device</Button>}</div>:<div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{rows.map(row=>{const c=row.config,Icon=icons[c.kind],MethodIcon=methodIcons[c.method],issues=deviceSetupIssues(c);return <article key={row.id} className="module-card flex min-w-0 flex-col gap-4 rounded-2xl border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="rounded-2xl bg-primary/10 p-3 text-primary"><AnimatedIcon icon={Icon}/></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{profileStatusLabels[c.status]}</span></div><div className="min-w-0"><h3 className="break-words text-lg font-semibold">{c.name}</h3><p className="mt-1 text-sm text-muted-foreground">{deviceKindLabels[c.kind]}</p><p className="mt-1 break-words text-xs text-muted-foreground">{[c.brand,c.model].filter(Boolean).join(' · ')||'Manufacturer and model needed'}</p></div><div className="space-y-2 text-sm"><p className="flex gap-2"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/>{data?.sites.find(s=>s.id===c.siteId)?.name||'Work site not assigned'}</p><p className="flex gap-2"><MethodIcon className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground"/>{connectionMethodLabels[c.method]}</p><p className="flex gap-2"><Users className="h-4 w-4 shrink-0 text-muted-foreground"/>{c.mappings.length} staff IDs mapped</p></div><div className="mt-auto rounded-xl bg-muted/60 px-3 py-2 text-xs">{issues.length?`${issues.length} setup details missing`:'Setup details complete'} · Connector required</div><div className="flex flex-wrap gap-2"><Button variant="outline" className="flex-1" onClick={()=>setEditing({profile:row})}><Settings2 className="mr-2 h-4 w-4"/>Manage</Button><Button variant="ghost" aria-label={`View history for ${c.name}`} onClick={()=>setHistory(row)}><History className="mr-2 h-4 w-4"/>History</Button></div></article>;})}</div>}
      </TabsContent>
      <TabsContent value="geofencing" className="space-y-4 pt-3"><div className="flex flex-wrap items-center gap-3 rounded-2xl border bg-card p-4"><MapPin className="h-5 w-5 text-primary"/><p className="flex-1 text-sm">Manage office, mall, FEC and event boundaries, GPS accuracy and attendance approvals.</p><Button asChild variant="outline" size="sm"><Link href="/settings/teams">Manage work sites</Link></Button></div><AttendanceLocationManagement/></TabsContent>
      <TabsContent value="guide" className="space-y-4 pt-3"><ConnectionGuide onDevices={()=>setTab('devices')} onGeofence={()=>setTab('geofencing')}/></TabsContent>
    </Tabs>
    {editing&&data&&<DeviceEditor key={editing.profile?editing.profile.id+':'+editing.profile.version:editing.preset?.id||'new'} profile={editing.profile} initialPreset={editing.preset} context={data} close={()=>setEditing(null)} saved={()=>{setEditing(null);setTab('devices');void refresh();}}/>}
    {history&&<DeviceHistory profile={history} close={()=>setHistory(null)}/>}
  </div>;
}

function PresetLibrary({disabled,choose}:{disabled:boolean;choose:(preset:DevicePreset)=>void}){
  const [filter,setFilter]=useState('all');
  const presets=devicePresets.filter(p=>filter==='all'||(filter==='vendor'?!!p.brand:!p.brand));
  return <><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Choose a starting point</h2><p className="mt-1 max-w-xl text-sm text-muted-foreground">Four manufacturer families and six generic profiles. You can choose the exact hardware later.</p></div><select className={fieldClass+' sm:w-auto'} aria-label="Filter setup presets" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All presets</option><option value="vendor">Manufacturer families</option><option value="generic">Generic profiles</option></select></div><p className="rounded-xl border border-primary/15 bg-primary/5 px-4 py-3 text-sm">Presets prepare connection settings. Model compatibility and a live connector still need to be confirmed.</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{presets.map(p=>{const Icon=icons[p.kind];return <article key={p.id} className="module-card flex min-w-0 flex-col gap-4 rounded-2xl border bg-card p-5"><div className="flex items-center justify-between gap-2"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><AnimatedIcon icon={Icon}/></span><span className="rounded-full bg-muted px-2.5 py-1 text-xs">{p.brand?'Manufacturer':'Generic'}</span></div><div><h3 className="font-semibold">{p.name}</h3><p className="mt-2 text-sm text-muted-foreground">{p.description}</p></div><div className="mt-auto space-y-3"><p className="text-xs text-muted-foreground">{connectionMethodLabels[p.method]}</p><Button variant="outline" className="w-full" disabled={disabled} onClick={()=>choose(p)}>Use this preset<ArrowRight className="ml-2 h-4 w-4"/></Button>{p.documentation&&<a className="block text-center text-xs text-primary underline" href={p.documentation} target="_blank" rel="noreferrer">Manufacturer integration guide</a>}</div></article>;})}</div></>;
}

function DeviceEditor({profile,initialPreset,context,close,saved}:{profile:DeviceProfile|null;initialPreset?:DevicePreset;context:DeviceContext;close:()=>void;saved:()=>void}){
  const [config,setConfig]=useState(()=>{const value=structuredClone({...emptyDevice(context.timezone),...profile?.config});return initialPreset?applyDevicePreset(value,initialPreset):value;}),[tab,setTab]=useState('details'),[reason,setReason]=useState(''),[error,setError]=useState('');
  const [people,setPeople]=useState<DeviceProfile['employeeNames']>(()=>({...profile?.employeeNames})),{toast}=useToast();
  const save=useMutation({mutationFn:()=>apiJson(profile?`${base}/${profile.id}`:base,{method:profile?'PUT':'POST',body:{version:profile?.version||0,config,reason}}),onSuccess:()=>{toast({title:'Device profile saved',description:'Connection details are saved. Live device sync still needs a connector.'});saved();}});
  function update<K extends keyof DeviceDefinition>(key:K,value:DeviceDefinition[K]){setConfig(current=>({...current,[key]:value}));}
  const issues=deviceSetupIssues(config),preset=devicePresets.find(p=>p.id===config.presetId);
  return <Dialog open onOpenChange={open=>{if(!open&&!save.isPending)close();}}><DialogContent className="max-h-[90dvh] max-w-4xl overflow-y-auto [&>*]:min-w-0"><DialogHeader><DialogTitle>{profile?'Manage device':'Register device'}</DialogTitle><DialogDescription>Save the device profile and staff IDs. Credentials and biometric templates stay outside this form.</DialogDescription></DialogHeader>
    <form className="min-w-0 space-y-4" onSubmit={e=>{e.preventDefault();setError('');const parsed=deviceDefinition.safeParse(config);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join('; '));return;}save.mutate();}}><fieldset disabled={save.isPending} className="min-w-0 space-y-4">
      <Tabs value={tab} onValueChange={setTab} className="min-w-0"><TabsList aria-label="Device configuration"><TabsTrigger value="details">Device details</TabsTrigger><TabsTrigger value="connection">Connection</TabsTrigger><TabsTrigger value="staff">Staff IDs ({config.mappings.length})</TabsTrigger></TabsList>
        <TabsContent value="details" className="space-y-4 pt-2"><Field label="Setup preset"><select className={fieldClass} value={config.presetId} onChange={e=>{const selected=devicePresets.find(p=>p.id===e.target.value);setConfig(current=>selected?applyDevicePreset(current,selected):{...current,presetId:'custom'});}}><option value="custom">Custom device</option>{devicePresets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>{preset&&<p className="rounded-xl bg-primary/5 p-3 text-sm text-muted-foreground">{preset.requirements}{preset.documentation&&<> <a className="font-medium text-primary underline" href={preset.documentation} target="_blank" rel="noreferrer">Manufacturer documentation</a></>}</p>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Device name"><input className={fieldClass} required minLength={2} maxLength={120} value={config.name} placeholder="e.g. Head Office entrance" onChange={e=>update('name',e.target.value)}/></Field><Field label="Device type"><select className={fieldClass} value={config.kind} onChange={e=>update('kind',e.target.value as DeviceDefinition['kind'])}>{deviceKinds.map(value=><option key={value} value={value}>{deviceKindLabels[value]}</option>)}</select></Field><Field label="Manufacturer"><input className={fieldClass} maxLength={100} value={config.brand} onChange={e=>update('brand',e.target.value)}/></Field><Field label="Model"><input className={fieldClass} maxLength={100} value={config.model} onChange={e=>update('model',e.target.value)}/></Field><Field label="Serial / asset ID"><input className={fieldClass} maxLength={120} value={config.serial} onChange={e=>update('serial',e.target.value)}/></Field><Field label="Work site"><select className={fieldClass} value={config.siteId??''} onChange={e=>{const s=context.sites.find(s=>s.id===Number(e.target.value));setConfig(c=>({...c,siteId:s?.id??null,timezone:s?.timezone||c.timezone}));}}><option value="">Assign later</option>{context.sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></Field><Field label="Device timezone"><input className={fieldClass} maxLength={80} required value={config.timezone} placeholder="Asia/Qatar" onChange={e=>update('timezone',e.target.value)}/></Field><Field label="Profile status"><select className={fieldClass} value={config.status} onChange={e=>update('status',e.target.value as DeviceDefinition['status'])}>{profileStatuses.map(value=><option key={value} value={value}>{profileStatusLabels[value]}</option>)}</select></Field></div><p className="text-xs text-muted-foreground">A site can serve multiple FEC, mall or event teams. Archiving preserves this profile and its history.</p><Field label="Installation notes"><textarea className={fieldClass} rows={3} maxLength={1500} value={config.notes} onChange={e=>update('notes',e.target.value)} placeholder="Placement, installer or maintenance details. No passwords."/></Field></TabsContent>
        <TabsContent value="connection" className="space-y-4 pt-2"><Field label="Planned connection method"><select className={fieldClass} value={config.method} onChange={e=>setConfig(c=>({...c,method:e.target.value as DeviceDefinition['method'],host:'',port:null,cloudUrl:''}))}>{connectionMethods.map(value=><option key={value} value={value}>{connectionMethodLabels[value]}</option>)}</select></Field>
          {config.method==='local_bridge'&&<><p className="text-sm text-muted-foreground">Record the device address used by your on-site bridge. This server does not scan or connect to your private network.</p><div className="grid gap-4 sm:grid-cols-[1fr_10rem]"><Field label="Local device / server host"><input className={fieldClass} maxLength={253} value={config.host} placeholder="IP or hostname only" onChange={e=>update('host',e.target.value)}/></Field><Field label="Device port"><input className={fieldClass} type="number" min={1} max={65535} value={config.port??''} onChange={e=>update('port',e.target.value===''?null:Number(e.target.value))}/></Field></div></>}
          {['vendor_cloud','local_api'].includes(config.method)&&<><p className="text-sm text-muted-foreground">Record the API base URL supplied by your installer. A compatible API connector is required before syncing.</p><Field label="API base URL"><input className={fieldClass} type="url" maxLength={500} value={config.cloudUrl} placeholder="https://…" onChange={e=>update('cloudUrl',e.target.value)}/></Field></>}
          {config.method==='file_export'&&<p className="rounded-xl bg-muted p-4 text-sm">Record a device that exports attendance files. Its export format must be mapped before device-file import can be enabled. Saving this profile does not import attendance.</p>}
          <Field label="Protocol / integration interface"><input className={fieldClass} maxLength={120} value={config.protocol} placeholder="Confirm with the selected model’s documentation" onChange={e=>update('protocol',e.target.value)}/></Field><Field label="Credential reference (optional)"><input className={fieldClass} maxLength={160} autoComplete="off" value={config.credentialReference} placeholder="Vault item name or IT reference — no actual secret" onChange={e=>update('credentialReference',e.target.value)}/></Field><div className="rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><strong>Connection status: connector required</strong><p className="mt-1 text-muted-foreground">Saving a host or URL does not verify connectivity. No device password, API token, fingerprint or face image is collected here.</p></div>
        </TabsContent>
        <TabsContent value="staff" className="space-y-4 pt-2"><StaffMappings config={config} people={people} update={mappings=>update('mappings',mappings)} remember={p=>setPeople(current=>({...current,[p.id]:{name:p.name,staffId:p.staffId,status:p.status}}))}/></TabsContent>
      </Tabs>
      <details className="rounded-xl bg-muted/60 p-3 text-sm"><summary className="cursor-pointer font-medium">{issues.length?`${issues.length} setup details still needed`:'Setup details complete'} · live connector required</summary>{issues.length>0&&<ul className="mt-2 list-disc space-y-1 pl-5">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}</details>
      <Field label="Reason for this change"><textarea className={fieldClass} rows={2} minLength={5} maxLength={1000} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><QueryError error={save.error}/>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap gap-2"><Button disabled={save.isPending||reason.trim().length<5}>{save.isPending?'Saving…':'Save device profile'}</Button><Button variant="outline" type="button" onClick={close}>Cancel</Button></div>
    </fieldset></form>
  </DialogContent></Dialog>;
}

function StaffMappings({config,people,update,remember}:{config:DeviceDefinition;people:DeviceProfile['employeeNames'];update:(mappings:DeviceDefinition['mappings'])=>void;remember:(person:Person)=>void}){
  const [search,setSearch]=useState(''),[person,setPerson]=useState<Person|null>(null),[code,setCode]=useState(''),[error,setError]=useState(''),[filter,setFilter]=useState('');
  const deferred=useDeferredValue(search.trim()),query=useQuery<Person[]>({queryKey:[base+'/employees',{q:deferred}],enabled:deferred.length>=2});
  function add(){setError('');const value=code.trim();if(!person||!value)return;if(config.mappings.some(m=>m.deviceUserId.toLowerCase()===value.toLowerCase()||m.employeeId===person.id)){setError('This device user ID or employee is already mapped.');return;}remember(person);update([...config.mappings,{deviceUserId:value,employeeId:person.id}]);setPerson(null);setSearch('');setCode('');}
  const shown=config.mappings.filter(m=>`${m.deviceUserId} ${people[m.employeeId]?.name||''} ${people[m.employeeId]?.staffId||''}`.toLowerCase().includes(filter.toLowerCase()));
  return <><p className="text-sm text-muted-foreground">Match each machine user ID to the correct employee. Store IDs only; biometric enrolment remains on the device.</p><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Field label="Find an employee"><input className={fieldClass} value={search} maxLength={100} placeholder="Type a name or staff ID (2+ characters)" onChange={e=>{setSearch(e.target.value);setPerson(null);}}/></Field>{person?<div className="rounded-lg bg-primary/5 p-3 text-sm">{person.name} · {person.staffId}</div>:deferred.length>=2&&<div className="max-h-44 overflow-auto rounded-xl border">{query.isFetching?<p role="status" className="p-3 text-sm">Finding employees…</p>:query.data?.map(p=><button type="button" key={p.id} className="block w-full border-b px-3 py-2 text-left text-sm hover:bg-muted focus-visible:bg-muted" onClick={()=>setPerson(p)}>{p.name}<span className="block text-xs text-muted-foreground">{p.staffId}</span></button>)}{!query.isFetching&&query.data?.length===0&&<p className="p-3 text-sm">No matching active employees.</p>}</div>}<QueryError error={query.error}/></div><div className="space-y-3"><Field label="User ID on device"><input className={fieldClass} value={code} maxLength={80} autoComplete="off" onChange={e=>setCode(e.target.value)}/></Field><Button type="button" variant="outline" disabled={!person||!code.trim()||config.mappings.length>=500} onClick={add}><Plus className="mr-2 h-4 w-4"/>Add mapping</Button></div></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Input aria-label="Search mapped staff" placeholder="Find a saved mapping…" value={filter} onChange={e=>setFilter(e.target.value)}/><Table pageSize={8} headers={['Device ID','Employee','Status','Action']} rows={shown.map(m=>[m.deviceUserId,<div>{people[m.employeeId]?.name||`Employee #${m.employeeId}`}<p className="text-xs text-muted-foreground">{people[m.employeeId]?.staffId}</p></div>,people[m.employeeId]?.status||'Missing employee',<Button type="button" variant="ghost" size="icon" aria-label={`Remove device ID ${m.deviceUserId}`} onClick={()=>update(config.mappings.filter(item=>item.deviceUserId!==m.deviceUserId))}><Trash2 className="h-4 w-4"/></Button>])}/><p className="text-xs text-muted-foreground">Mappings are saved with the device profile. Removing a mapping here does not change employee records.</p></>;
}

function DeviceHistory({profile,close}:{profile:DeviceProfile;close:()=>void}){
  const query=useQuery<DeviceRevision[]>({queryKey:[`${base}/${profile.id}/history`]});
  return <Dialog open onOpenChange={value=>{if(!value)close();}}><DialogContent className="max-h-[90dvh] max-w-3xl overflow-y-auto [&>*]:min-w-0"><DialogHeader><DialogTitle>History · {profile.config.name}</DialogTitle><DialogDescription>The latest 30 saved revisions. Every save also creates an activity record.</DialogDescription></DialogHeader><QueryError error={query.error}/>{query.isLoading?<p role="status">Loading revisions…</p>:<div className="space-y-3">{query.data?.map(row=><details key={row.version} className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">Version {row.version} · {new Date(row.at).toLocaleString()} · {profileStatusLabels[row.config.status]}</summary><div className="mt-3 space-y-2 text-sm"><p>{row.reason}</p><p className="text-muted-foreground">Saved by user #{row.actorId} · {row.config.name} · {deviceKindLabels[row.config.kind]} · {row.config.mappings.length} staff IDs</p><p className="text-muted-foreground">{connectionMethodLabels[row.config.method]} · {row.config.timezone}</p><p className="break-all text-muted-foreground">{row.config.host||row.config.cloudUrl||'No network endpoint'}{row.config.port?`:${row.config.port}`:''}</p></div></details>)}</div>}</DialogContent></Dialog>;
}

function ConnectionGuide({onDevices,onGeofence}:{onDevices:()=>void;onGeofence:()=>void}){
  return <><div className="grid gap-4 md:grid-cols-3">{[{icon:Fingerprint,title:'1. Register the hardware',text:'Add its manufacturer, model, serial and workplace.'},{icon:Users,title:'2. Match staff IDs',text:'Map machine user IDs to existing employee records.'},{icon:Plug,title:'3. Configure a connector',text:'Use the manufacturer’s supported protocol and confirm its attendance format.'}].map(item=><Section key={item.title} title={item.title}><AnimatedIcon icon={item.icon} className="h-7 w-7 text-primary"/><p className="text-sm text-muted-foreground">{item.text}</p></Section>)}</div><Section title="Available now"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-3 rounded-xl bg-muted/50 p-4"><h3 className="flex items-center gap-2 font-medium"><MapPin className="h-4 w-4"/>Mobile GPS & geofencing</h3><p className="text-sm text-muted-foreground">Actual workplace boundaries, dates, GPS accuracy and attendance review rules.</p><Button variant="outline" onClick={onGeofence}>Manage geofencing</Button></div><div className="space-y-3 rounded-xl bg-muted/50 p-4"><h3 className="flex items-center gap-2 font-medium"><Settings2 className="h-4 w-4"/>Device setup directory</h3><p className="text-sm text-muted-foreground">Saved device profiles, site assignments, connection references and staff mappings.</p><Button variant="outline" onClick={onDevices}>Manage devices</Button></div></div></Section><Section title="Before live device sync"><p className="text-sm text-muted-foreground">The application does not yet include a vendor connector, device-file importer, hardware heartbeat or biometric enrolment. A device listed here is a saved configuration, not a verified connection.</p><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border p-4 text-sm"><strong>Provide to your installer</strong><ul className="mt-2 list-disc space-y-1 pl-5 text-muted-foreground"><li>Manufacturer, exact model and firmware</li><li>Supported API / export documentation</li><li>Site network and timezone</li><li>One sample attendance file or event format</li></ul></div><div className="rounded-xl border p-4 text-sm"><strong>Attendance review stays in place</strong><p className="mt-2 text-muted-foreground">Device setup does not change attendance, payroll, supervisor approvals or existing GPS enforcement. A future connector must preserve those controls.</p><Button asChild variant="link" className="mt-2 h-auto px-0"><Link href="/attendance">Open attendance</Link></Button></div></div></Section></>;
}
