import {useState,type ReactNode} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export {Field,selectStyle} from '@/components/operations/Common';
export function useSave(){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>apiJson<any>('/api/lifecycle/'+path,{method:'POST',body}),onSuccess:async()=>{await cache.invalidateQueries({predicate:q=>['/api/workflow-controls','/api/interviews','/api/lifecycle','/api/job-','/api/onboarding','/api/employee-onboarding','/api/performance'].some(p=>String(q.queryKey[0]).startsWith(p))});toast({title:'Saved'});},onError:(e:Error)=>toast({title:'Unable to save',description:e.message,variant:'destructive'})});}
export function Panel({title,children}:{title:string;children:ReactNode}){return <section className="my-5 space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">{title}</h2>{children}</section>;}
export function Person({module,label,value,onChange}:{module:'performance_management'|'training_development';label:string;value:number;onChange:(id:number)=>void}){const [q,setQ]=useState('');const result=useQuery<any[]>({queryKey:['/api/lifecycle/people',{module,q}],enabled:q.trim().length>=2});return <div className="space-y-2"><label className="grid gap-1 text-sm">Find {label}<Input value={q} placeholder="Name or employee number" onChange={e=>{setQ(e.target.value);onChange(0);}}/></label>{result.error&&<p role="alert">Unable to search employees.</p>}<label className="grid gap-1 text-sm">{label}<select required className="rounded border bg-background p-2" value={value||''} onChange={e=>onChange(Number(e.target.value))}><option value="">Select employee</option>{result.data?.map(e=><option key={e.id} value={e.id}>{e.name} · {e.employee_id}</option>)}</select></label></div>;}
export function History({kind,id}:{kind:string;id:number}){const [open,setOpen]=useState(false);const result=useQuery<any[]>({queryKey:[`/api/lifecycle/history/${kind}/${id}`],enabled:open});return <div><Button variant="ghost" size="sm" onClick={()=>setOpen(!open)}>History</Button>{open&&<div className="space-y-2 text-sm">{result.isLoading&&<p>Loading history…</p>}{result.error&&<p role="alert">History is unavailable for your account.</p>}{result.data?.length===0&&<p>No workflow history recorded yet.</p>}{result.data?.map(r=><details key={r.version} className="rounded border p-2"><summary>Version {r.version} · {new Date(r.created_at).toLocaleString()} · {r.reason}</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(r.snapshot,null,2)}</pre></details>)}</div>}</div>;}
export function Paging({page,setPage,count}:{page:number;setPage:(n:number)=>void;count:number}){return <div className="flex items-center gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page}</span><Button variant="outline" disabled={count<25} onClick={()=>setPage(page+1)}>Next</Button></div>;}
export function LoadState({query}:{query:{isLoading:boolean;error:unknown;data?:{items:any[]}}}){return query.isLoading?<p>Loading…</p>:query.error?<p role="alert">Unable to load this workflow. Check your access or retry.</p>:query.data?.items.length===0?<p className="text-sm text-muted-foreground">No records yet.</p>:null;}
