import {ReassignReview} from './WorkflowControls';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Field,Panel,Person,History,Paging,LoadState,useSave,selectStyle} from './Common';
export function Cycles(){
 const [page,setPage]=useState(1),[cyclePage,setCyclePage]=useState(1),[title,setTitle]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[due,setDue]=useState(''),[reason,setReason]=useState('');
 const [ratingMax,setRatingMax]=useState(5),[scoreDecimals,setScoreDecimals]=useState(2);
 const [criteria,setCriteria]=useState([{title:'',weight:100}]),[employeeId,setEmployeeId]=useState(0),[reviewerId,setReviewerId]=useState(0),[cycleId,setCycleId]=useState('');
 const cycles=useQuery<any>({queryKey:['/api/lifecycle/cycles',{page:cyclePage}]}),reviews=useQuery<any>({queryKey:['/api/lifecycle/assessments',{page}]}),save=useSave();
 return <Panel title="Review cycles and development plans"><p className="text-sm text-muted-foreground">Administrators configure rating scales, weights and rounding for each cycle. The assigned reviewer submits evidence; independent HR publishes the review before the employee can read and acknowledge it. Scores do not change pay.</p><LoadState query={cycles}/>
 {cycles.data?.canCreate&&<details><summary className="cursor-pointer">Configure a cycle</summary><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:'cycles',body:{title,startDate:start,endDate:end,dueDate:due,reason,rubric:criteria,ratingMax,scoreDecimals}});}}><Field label="Cycle name"><Input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><div className="grid gap-3 md:grid-cols-3"><Field label="Period starts"><Input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Period ends"><Input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Reviews due"><Input type="date" required value={due} onChange={e=>setDue(e.target.value)}/></Field></div><Field label="Maximum rating"><select className={selectStyle} value={ratingMax} onChange={e=>setRatingMax(Number(e.target.value))}><option value={5}>5 points</option><option value={10}>10 points</option></select></Field><Field label="Score decimal places"><select className={selectStyle} value={scoreDecimals} onChange={e=>setScoreDecimals(Number(e.target.value))}>{[0,1,2].map(n=><option key={n}>{n}</option>)}</select></Field><p>Criteria and weights (total 100%). A saved cycle preserves its rubric.</p>{criteria.map((r,i)=><div className="flex items-end gap-2" key={i}><Field label="Criterion"><Input required value={r.title} onChange={e=>setCriteria(criteria.map((v,j)=>j===i?{...v,title:e.target.value}:v))}/></Field><Field label="Weight %"><Input type="number" required min={1} max={100} value={r.weight} onChange={e=>setCriteria(criteria.map((v,j)=>j===i?{...v,weight:Number(e.target.value)}:v))}/></Field><Button type="button" variant="outline" disabled={criteria.length===1} onClick={()=>setCriteria(criteria.filter((_,j)=>j!==i))}>Remove</Button></div>)}<Button type="button" variant="outline" disabled={criteria.length>=20} onClick={()=>setCriteria([...criteria,{title:'',weight:1}])}>Add criterion</Button><Field label="Configuration reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Create cycle</Button></form></details>}
 {cycles.data?.items.map((c:any)=><Cycle key={c.id+':'+c.version} row={c} canClose={cycles.data.canCreate}/>)}<Paging page={cyclePage} setPage={setCyclePage} count={cycles.data?.items.length||0}/>
 {reviews.data?.canAssign&&<details><summary className="cursor-pointer">Assign a review</summary><form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'assessments',body:{cycleId:Number(cycleId),employeeId,reviewerId,reason}});}}><Field label="Open cycle"><select required className={selectStyle} value={cycleId} onChange={e=>setCycleId(e.target.value)}><option value="">Choose cycle</option>{cycles.data?.items.filter((c:any)=>c.status==='open').map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Person module="performance_management" label="employee" value={employeeId} onChange={setEmployeeId}/><Person module="performance_management" label="reviewer" value={reviewerId} onChange={setReviewerId}/><Field label="Assignment reason"><Input minLength={5} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Assign review</Button></form></details>}
 <h3 className="font-semibold">Assigned reviews</h3><LoadState query={reviews}/>{reviews.data?.items.map((r:any)=><Assessment key={r.id+':'+r.version} row={r}/>)}<Paging page={page} setPage={setPage} count={reviews.data?.items.length||0}/></Panel>;
}
function Cycle({row:c,canClose}:{row:any;canClose:boolean}){const [reason,setReason]=useState(''),save=useSave();return <article className="rounded border p-3"><strong>{c.title}</strong><p>{c.start_date} to {c.end_date} · Due {c.due_date} · {c.status}</p><p className="text-sm">{c.rubric.map((r:any)=>`${r.title} (${r.weight}%)`).join(' · ')}</p>{canClose&&c.status==='open'&&<details><summary>Close cycle</summary><form className="flex gap-2" onSubmit={e=>{e.preventDefault();save.mutate({path:`cycles/${c.id}/close`,body:{version:c.version,reason}});}}><Input aria-label="Closure reason" required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Closure reason"/><Button disabled={save.isPending}>Close</Button></form></details>}{canClose&&<History kind="cycle" id={c.id}/>}</article>;}
function Assessment({row:r}:{row:any}){const [ratings,setRatings]=useState<any[]>(r.ratings.length?r.ratings:r.rubric.map(()=>({score:'',evidence:''}))),[plan,setPlan]=useState(r.development_plan),[reason,setReason]=useState(''),save=useSave();const act=(action:string)=>save.mutate({path:`assessments/${r.id}/actions`,body:{version:r.version,action,reason,...(action==='submit'?{ratings,developmentPlan:plan}:{})}});return <article className="space-y-3 rounded border p-4"><h3 className="font-semibold">{r.employee_name} · {r.cycle_title}</h3><p>{r.status}{r.score!==null&&` · ${r.score}/${r.rating_max}`}{r.acknowledged_at&&' · Acknowledged'}</p>{r.canEdit?<form className="space-y-3" onSubmit={e=>{e.preventDefault();act('submit');}}>{r.rubric.map((c:any,i:number)=><div key={i} className="grid gap-2 md:grid-cols-2"><Field label={`${c.title} · ${c.weight}% · Score (1–${r.rating_max})`}><Input required type="number" min={1} max={r.rating_max} value={ratings[i].score} onChange={e=>setRatings(ratings.map((v,j)=>j===i?{...v,score:Number(e.target.value)}:v))}/></Field><Field label="Evidence"><Textarea required minLength={5} value={ratings[i].evidence} onChange={e=>setRatings(ratings.map((v,j)=>j===i?{...v,evidence:e.target.value}:v))}/></Field></div>)}<Field label="Development plan with objectives, support and target dates"><Textarea required minLength={5} value={plan} onChange={e=>setPlan(e.target.value)}/></Field><Field label="Submission reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Submit for HR review</Button></form>:<div>{r.ratings.map((v:any,i:number)=><p key={i} className="text-sm">{r.rubric[i].title}: {v.score}/{r.rating_max} · {v.evidence}</p>)}{r.development_plan&&<p className="whitespace-pre-wrap">Development plan: {r.development_plan}</p>}</div>}
 {(r.canPublish||r.canAcknowledge)&&<div className="space-y-2"><Field label="Review / acknowledgement note"><Input minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{r.canPublish&&<><Button disabled={save.isPending||reason.trim().length<5} onClick={()=>act('publish')}>Publish to employee</Button> <Button variant="outline" disabled={save.isPending||reason.trim().length<5} onClick={()=>act('return')}>Return to reviewer</Button></>}{r.canAcknowledge&&<Button disabled={save.isPending||reason.trim().length<5} onClick={()=>act('acknowledge')}>Acknowledge receipt</Button>}</div>}<ReassignReview row={r}/><History kind="assessment" id={r.id}/></article>;}
