import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Panel,Field,Paging,LoadState,selectStyle} from './Common';
const cents=(value:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(value))throw new Error('Enter a QAR amount with at most two decimal places');const [whole,decimal='']=value.split('.');return Number(whole)*100+Number(decimal.padEnd(2,'0'));};
export const qar=(n:number)=>(n/100).toFixed(2)+' QAR';
export function useServiceSave(){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({path,body}:{path:string;body:any})=>apiJson<any>('/api/'+path,{method:'POST',body}),onSuccess:async()=>{await cache.invalidateQueries({predicate:q=>['/api/employment-continuity','/api/people-operations','/api/employees','/api/employee-records','/api/equipment','/api/handbook','/api/offboarding','/api/workflow-controls','/api/interviews','/api/lifecycle','/api/job-','/api/onboarding','/api/employee-onboarding','/api/employee-services','/api/operations-center','/api/eos-keys','/api/helpdesk'].some(p=>String(q.queryKey[0]).startsWith(p))});toast({title:'Saved'});},onError:(e:Error)=>toast({title:'Unable to save',description:e.message,variant:'destructive'})});}
export default function EmployeeServices({kind}:{kind:'expense'|'benefit'}){
 const [page,setPage]=useState(1),[policyId,setPolicyId]=useState(''),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[end,setEnd]=useState(''),[evidence,setEvidence]=useState(''),[reference,setReference]=useState(''),[error,setError]=useState('');
 const policies=useQuery<any>({queryKey:['/api/employee-services/policies',{kind}]}),requests=useQuery<any>({queryKey:['/api/employee-services/requests',{kind,page}]}),save=useServiceSave();
 return <div><h1 className="text-2xl font-bold">{kind==='expense'?'Expense reimbursement':'Benefits enrollment'}</h1><p className="text-muted-foreground">{kind==='expense'?'Submit a verified receipt reference and amount for independent review. Recording payment does not make a bank transfer.':'Request an eligible benefit for a defined period. Entitlement values do not automatically change payroll.'}</p><Panel title="Available policies"><LoadState query={policies}/>{policies.data?.items.map((p:any)=><div key={p.id} className="rounded border p-3"><strong>{p.name}</strong><p>Version {p.version} · {p.enabled?'Enabled':'Disabled'} · Per request {qar(p.rules.perRequestCents)} · Annual cap {qar(p.rules.annualCapCents)}</p><p>Eligible types: {p.rules.employeeTypes.join(', ')}</p></div>)}{policies.data?.canConfigure&&<Policy kind={kind} items={policies.data.items}/>}</Panel>
 <Panel title="Submit a request"><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();try{setError('');save.mutate({path:'employee-services/requests',body:{kind,policyId:Number(policyId),title,amountCents:cents(amount),serviceDate:date,endDate:kind==='benefit'?end:null,evidence,reference}},{onSuccess:()=>{setTitle('');setAmount('');setReference('');setEvidence('');}});}catch(e){setError((e as Error).message);}}}><Field label="Policy"><select required className={selectStyle} value={policyId} onChange={e=>setPolicyId(e.target.value)}><option value="">Choose policy</option>{policies.data?.items.filter((p:any)=>p.enabled).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Request title"><Input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Amount / entitlement value (QAR)"><Input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label={kind==='expense'?'Expense date':'Benefit start date'}><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field>{kind==='benefit'&&<Field label="Benefit end date (same calendar year)"><Input type="date" required value={end} onChange={e=>setEnd(e.target.value)}/></Field>}<Field label="Unique receipt or request reference"><Input required minLength={5} value={reference} onChange={e=>setReference(e.target.value)}/></Field><Field label="Evidence and purpose"><Textarea required minLength={5} value={evidence} onChange={e=>setEvidence(e.target.value)}/></Field>{error&&<p role="alert">{error}</p>}<Button disabled={save.isPending}>Submit for review</Button></form></Panel>
 <Panel title="Requests and decisions"><LoadState query={requests}/>{requests.data?.items.map((r:any)=><Request key={r.id+':'+r.version} row={r}/>)}<Paging page={page} setPage={setPage} count={requests.data?.items.length||0}/></Panel></div>;
}
function Policy({kind,items}:{kind:string;items:any[]}){const [selected,setSelected]=useState(''),[name,setName]=useState(''),[per,setPer]=useState(''),[annual,setAnnual]=useState(''),[types,setTypes]=useState<string[]>([]),[enabled,setEnabled]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(''),save=useServiceSave();return <details><summary className="cursor-pointer">Configure policies (Admin)</summary><form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();try{setError('');save.mutate({path:'employee-services/policies',body:{kind,name,expectedVersion:items.find(p=>String(p.id)===selected)?.version||0,enabled,rules:{perRequestCents:cents(per),annualCapCents:cents(annual),employeeTypes:types},reason}},{onSuccess:r=>setSelected(String(r.id))});}catch(e){setError((e as Error).message);}}}><Field label="New policy or existing policy"><select className={selectStyle} value={selected} onChange={e=>{setSelected(e.target.value);const p=items.find(p=>String(p.id)===e.target.value);setName(p?.name||'');setPer(p?String(p.rules.perRequestCents/100):'');setAnnual(p?String(p.rules.annualCapCents/100):'');setTypes(p?.rules.employeeTypes||[]);setEnabled(p?.enabled||false);}}><option value="">New policy</option>{items.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Policy name"><Input required disabled={!!selected} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Maximum per request (QAR)"><Input required value={per} onChange={e=>setPer(e.target.value)}/></Field><Field label="Annual cap per employee (QAR)"><Input required value={annual} onChange={e=>setAnnual(e.target.value)}/></Field><div>{['permanent','temporary','contract'].map(t=><label key={t} className="mr-4 inline-flex gap-2"><input type="checkbox" checked={types.includes(t)} onChange={e=>setTypes(e.target.checked?[...types,t]:types.filter(v=>v!==t))}/>{t}</label>)}</div><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enable new requests</label><Field label="Policy reason"><Input minLength={5} required value={reason} onChange={e=>setReason(e.target.value)}/></Field>{error&&<p role="alert">{error}</p>}<Button disabled={save.isPending}>Publish policy version</Button></form></details>;}
function Request({row:r}:{row:any}){const [reason,setReason]=useState(''),[payment,setPayment]=useState(''),[show,setShow]=useState(false),save=useServiceSave();const history=useQuery<any[]>({queryKey:[`/api/employee-services/requests/${r.id}/history`],enabled:show});const act=(action:string)=>save.mutate({path:`employee-services/requests/${r.id}/actions`,body:{version:r.version,action,reason,...(action==='pay'?{paymentReference:payment}:{})}});return <article className="space-y-2 rounded border p-4"><h3 className="font-semibold">{r.employee_name} · {r.title} · {qar(r.amount_cents)}</h3><p>{r.policy_name} · {r.service_date}{r.end_date&&` to ${r.end_date}`} · {r.status}</p><p className="text-sm">Reference: {r.reference} · {r.evidence}</p>{r.payment_reference&&<p>External payment: {r.payment_reference}</p>}{(r.canReview||r.canWithdraw||r.canPay||r.canEnd)&&<><Field label="Decision reason"><Input minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{r.canPay&&<Field label="Completed external payment reference"><Input value={payment} onChange={e=>setPayment(e.target.value)}/></Field>}<div className="flex flex-wrap gap-2">{[[r.canReview,'approve','Approve'],[r.canReview,'reject','Reject'],[r.canWithdraw,'withdraw','Withdraw'],[r.canPay,'pay','Record paid'],[r.canEnd,'end','End benefit']].filter(v=>v[0]).map(v=><Button key={String(v[1])} disabled={save.isPending||reason.trim().length<5||(v[1]==='pay'&&payment.trim().length<5)} onClick={()=>act(String(v[1]))}>{v[2]}</Button>)}</div></>}<Button variant="ghost" onClick={()=>setShow(!show)}>Decision history</Button>{show&&<div>{history.error&&<p role="alert">Unable to load history.</p>}{history.data?.map(h=><p key={h.version}>v{h.version} · {h.snapshot.status} · {h.reason}</p>)}</div>}</article>;}
