import {PolicyHistory} from './OnboardingReviews';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useAuth} from '@/contexts/AuthContext';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Field,Panel,Paging,LoadState,selectStyle} from './Common';
import {useServiceSave} from './EmployeeServices';
export function OfferTerms({row:r}:{row:any}){
 const [offerDate,setOfferDate]=useState(r.offer_date),[expiryDate,setExpiryDate]=useState(r.expiry_date),[startDate,setStartDate]=useState(r.start_date||''),[salary,setSalary]=useState(r.salary),[benefits,setBenefits]=useState(typeof r.benefits==='string'?r.benefits:JSON.stringify(r.benefits||'')),[reason,setReason]=useState(''),save=useServiceSave();
 return <details><summary>Edit draft terms</summary><p>Term changes require independent approval and clear the old offer-letter reference. Salary is recorded in whole QAR.</p><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:`workflow-controls/offers/${r.id}/terms`,body:{version:r.version,offerDate,expiryDate,startDate:startDate||null,salary,benefits,reason}});}}>{[['Offer date',offerDate,setOfferDate],['Expiry date',expiryDate,setExpiryDate],['Start date',startDate,setStartDate]].map(([label,value,set]:any)=><Field key={label} label={label}><Input type="date" required={label!=='Start date'} value={value} onChange={e=>set(e.target.value)}/></Field>)}<Field label="Salary (QAR)"><Input required type="number" min={1} step={1} value={salary} onChange={e=>setSalary(Number(e.target.value))}/></Field><Field label="Benefits and terms"><Textarea value={benefits} onChange={e=>setBenefits(e.target.value)}/></Field><Field label="Change reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Save draft terms</Button></form></details>;
}
export function WaiverPolicy(){const {user}=useAuth(),allowed=['admin','super_admin'].includes(user?.role||''),q=useQuery<any>({queryKey:['/api/workflow-controls/waiver-policy'],enabled:allowed});return allowed?<Panel title="Document waiver policy"><p>No document type is eligible by default. List only types your organization permits administrators to waive. Existing recorded waivers retain their policy version.</p>{q.error&&<p role="alert">Unable to load waiver policy.</p>}{q.data&&<PolicyForm key={q.data.version} row={q.data}/>}<PolicyHistory kind="waiver_policy"/></Panel>:null;}
function PolicyForm({row:r}:{row:any}){const [types,setTypes]=useState(r.document_types.join('\n')),[reason,setReason]=useState(''),save=useServiceSave();return <form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'workflow-controls/waiver-policy',body:{version:r.version,documentTypes:types.split('\n').map((s:string)=>s.trim()).filter(Boolean),reason}});}}><Field label="Eligible document types, one per line"><Textarea value={types} onChange={e=>setTypes(e.target.value)}/></Field><Field label="Policy reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Publish policy v{r.version+1}</Button></form>;}
export function DocumentWaiver({row:r}:{row:any}){const {user}=useAuth(),[reason,setReason]=useState(''),save=useServiceSave();if(!['admin','super_admin'].includes(user?.role||'')||r.onboarding_status!=='in_progress'||!['required','waived'].includes(r.status))return null;return <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();save.mutate({path:`workflow-controls/documents/${r.id}/waiver`,body:{version:r.version,action:r.status==='waived'?'revoke':'waive',reason}});}}><Field label="Waiver decision reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending} variant="outline">{r.status==='waived'?'Revoke waiver':'Waive under policy'}</Button></form>;}
export function MyOnboardingTasks(){const [page,setPage]=useState(1),q=useQuery<any>({queryKey:['/api/workflow-controls/my-tasks',{page}]});return <Panel title="My onboarding tasks"><p>Update tasks assigned to you. Ask HR to change an owner, due date, or completed task.</p><LoadState query={q}/>{q.data?.items.map((r:any)=><OwnTask key={r.id+':'+r.version} row={r}/>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel>;}
function OwnTask({row:r}:{row:any}){const [status,setStatus]=useState('in_progress'),[comments,setComments]=useState(''),save=useServiceSave();return <article className="space-y-2 rounded border p-3"><strong>{r.task_name}</strong><p>{r.status} · Due {r.due_date}{r.review_required?` · Review: ${r.review_state}`:''}</p><p>{r.comments}</p>{r.status!=='completed'&&r.review_state!=='pending'&&r.onboarding_status==='in_progress'&&<form className="grid gap-3 md:grid-cols-3" onSubmit={e=>{e.preventDefault();save.mutate({path:`workflow-controls/my-tasks/${r.id}`,body:{version:r.version,status,comments}});}}><Field label="Progress"><select className={selectStyle} value={status} onChange={e=>setStatus(e.target.value)}><option value="in_progress">In progress</option><option value="completed">{r.review_required?'Submit for HR review':'Completed'}</option></select></Field><Field label="Work completed / evidence"><Textarea required minLength={5} value={comments} onChange={e=>setComments(e.target.value)}/></Field><Button disabled={save.isPending}>Save progress</Button></form>}</article>;}
export function InterviewScheduling(){const [page,setPage]=useState(1),q=useQuery<any>({queryKey:['/api/workflow-controls/interviews',{page}]});return <div id="interview-scheduling"><Panel title="Interview scheduling"><p>Book and reschedule interviews with candidate and interviewer conflict checks. Approved leave and recorded workforce, attendance and event schedules also block overlapping bookings. Enter dates and times in Qatar time (UTC+03:00). Existing appointments without a duration use 60 minutes.</p>{q.data?.canEdit&&<details><summary>Schedule interview</summary><ScheduleForm/></details>}<LoadState query={q}/>{q.data?.items.map((r:any)=><Interview key={r.id+':'+r.version} row={r} canEdit={q.data.canEdit}/>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel></div>;}
function ScheduleForm({row:r}:{row?:any}){
 const [applicationId,setApplication]=useState(r?.application_id||0),[interviewerId,setInterviewer]=useState(r?.interviewer_id||0),[start,setStart]=useState(r?new Date(new Date(r.starts_at).getTime()+3*3600000).toISOString().slice(0,16):''),[duration,setDuration]=useState(r?.duration_minutes||60),[type,setType]=useState(r?.interview_type||'video'),[round,setRound]=useState(r?.interview_round||'first'),[reason,setReason]=useState(''),[search,setSearch]=useState(''),save=useServiceSave();const options=useQuery<any>({queryKey:['/api/workflow-controls/interview-options',{q:search}]});
 return <form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:r?`workflow-controls/interviews/${r.id}/reschedule`:'workflow-controls/interviews',body:{...(r?{version:r.version}:{}),applicationId,interviewerId,startsAt:start+':00+03:00',durationMinutes:duration,interviewType:type,interviewRound:round,reason}});}}><Field label="Find candidate or interviewer (up to 100 matches)"><Input value={search} onChange={e=>setSearch(e.target.value)}/></Field>{options.error&&<p role="alert">Unable to load booking options.</p>}<Field label="Application"><select className={selectStyle} required disabled={!!r} value={applicationId||''} onChange={e=>setApplication(Number(e.target.value))}><option value="">Choose application</option>{r&&<option value={r.application_id}>{r.candidate_name}</option>}{!r&&options.data?.applications.map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.job_title}</option>)}</select></Field><Field label="Interviewer"><select className={selectStyle} required value={interviewerId||''} onChange={e=>setInterviewer(Number(e.target.value))}><option value="">Choose interviewer</option>{!!interviewerId&&!options.data?.people.some((p:any)=>p.id===interviewerId)&&<option value={interviewerId}>{r?.interviewer_name||'Selected interviewer'}</option>}{options.data?.people.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Start (Qatar time)"><Input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Duration (minutes)"><Input type="number" required min={15} max={480} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></Field><Field label="Format"><select className={selectStyle} value={type} onChange={e=>setType(e.target.value)}>{['phone','video','in-person'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Round"><select className={selectStyle} value={round} onChange={e=>setRound(e.target.value)}>{['first','second','final','technical','hr'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Scheduling reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>{r?'Reschedule':'Book interview'}</Button></form>;
}
function Interview({row:r,canEdit}:{row:any;canEdit:boolean}){const [action,setAction]=useState('completed'),[rating,setRating]=useState(3),[recommendation,setRecommendation]=useState('hold'),[reason,setReason]=useState(''),save=useServiceSave();const h=useQuery<any[]>({queryKey:[`/api/workflow-controls/history/interview/${r.id}`]});return <article className="space-y-2 rounded border p-3"><strong>{r.candidate_name} · {r.interviewer_name}</strong><p>{new Date(r.starts_at).toLocaleString('en-GB',{timeZone:'Asia/Qatar'})} Qatar · {r.duration_minutes} minutes · {r.status}</p>{canEdit&&r.status==='scheduled'&&<><details><summary>Reschedule</summary><ScheduleForm row={r}/></details><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:`workflow-controls/interviews/${r.id}/decision`,body:{version:r.version,action,reason,...(action==='completed'?{rating,recommendation}:{})}});}}><Field label="Outcome"><select className={selectStyle} value={action} onChange={e=>setAction(e.target.value)}>{['completed','cancelled','no-show'].map(v=><option key={v}>{v}</option>)}</select></Field>{action==='completed'&&<><Field label="Rating (1–5)"><Input type="number" min={1} max={5} required value={rating} onChange={e=>setRating(Number(e.target.value))}/></Field><Field label="Recommendation"><select className={selectStyle} value={recommendation} onChange={e=>setRecommendation(e.target.value)}>{['hire','reject','hold'].map(v=><option key={v}>{v}</option>)}</select></Field></>}<Field label="Feedback / decision reason"><Textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Record outcome</Button></form></>}<details><summary>Interview history</summary>{h.error&&<p>Unable to load history.</p>}{h.data?.map(v=><p key={v.version}>v{v.version} · {v.snapshot.status} · {v.reason}</p>)}</details></article>;}
