import {CourseMaintenance} from './WorkflowControls';
import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
import {Field,Panel,Person,History,Paging,LoadState,useSave,selectStyle} from './Common';
export default function Learning(){
 const [page,setPage]=useState(1),[coursePage,setCoursePage]=useState(1),[employeeId,setEmployeeId]=useState(0),[courseId,setCourseId]=useState(''),[due,setDue]=useState(''),[reason,setReason]=useState('');
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[provider,setProvider]=useState('');
 const records=useQuery<any>({queryKey:['/api/lifecycle/learning',{page}]}),courses=useQuery<any>({queryKey:['/api/lifecycle/courses',{page:coursePage}]}),save=useSave();
 return <div><h1 className="text-2xl font-bold">Training and development</h1><p className="text-muted-foreground">Assign courses, submit completion evidence and track independently verified certificates. These records do not automatically grant workforce qualifications.</p>
 <Panel title="Course catalogue"><LoadState query={courses}/>{courses.data?.items.map((c:any)=><article key={c.id} className="rounded border p-3"><strong>{c.title}</strong><p>{c.provider} · {c.active?'Active':'Inactive'}</p><p className="text-sm">{c.description}</p></article>)}<Paging page={coursePage} setPage={setCoursePage} count={courses.data?.items.length||0}/>
 {courses.data?.canCreate&&<details><summary className="cursor-pointer">Add a course</summary><form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'courses',body:{title,description,provider,reason:'Course added to internal catalogue'}},{onSuccess:()=>{setTitle('');setDescription('');setProvider('');}});}}><Field label="Course title"><Input required value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Provider"><Input required value={provider} onChange={e=>setProvider(e.target.value)}/></Field><Field label="Description"><Textarea required minLength={5} value={description} onChange={e=>setDescription(e.target.value)}/></Field><Button disabled={save.isPending}>Add course</Button></form></details>}</Panel>
 {records.data?.canAssign&&<Panel title="Assign training"><form className="grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:'learning',body:{employeeId,courseId:Number(courseId),dueDate:due,reason}});}}><Person module="training_development" label="employee" value={employeeId} onChange={setEmployeeId}/><Field label="Course from the displayed catalogue page"><select required className={selectStyle} value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Select course</option>{courses.data?.items.filter((c:any)=>c.active).map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field><Field label="Due date"><Input type="date" required value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="Assignment reason"><Input minLength={5} required value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Assign</Button></form></Panel>}
 <CourseMaintenance/><Panel title="Learning records"><LoadState query={records}/>{records.data?.items.map((r:any)=><Record key={r.id+':'+r.version} row={r}/>)}<Paging page={page} setPage={setPage} count={records.data?.items.length||0}/></Panel></div>;
}
function Record({row:r}:{row:any}){const [action,setAction]=useState(r.canSubmit?'submit':r.canVerify?'verify':'withdraw'),[evidence,setEvidence]=useState(r.evidence),[completion,setCompletion]=useState(''),[expiry,setExpiry]=useState(''),[reason,setReason]=useState(''),save=useSave();return <article className="space-y-3 rounded border p-4"><h3 className="font-semibold">{r.employee_name} · {r.course_title}</h3><p className="text-sm">{r.status} · Due {r.due_date}{r.completion_date&&` · Completed ${r.completion_date}`}{r.expiry_date&&` · Certificate expires ${r.expiry_date}${r.expiry_date<new Date().toISOString().slice(0,10)?' (expired)':''}`}</p>{r.evidence&&<p className="whitespace-pre-wrap text-sm">Evidence: {r.evidence}</p>}
 {(r.canSubmit||r.canVerify||r.canWithdraw)&&<details><summary className="cursor-pointer">Update training</summary><form className="mt-3 grid gap-3 md:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate({path:`learning/${r.id}/actions`,body:{version:r.version,action,reason,...(['submit','verify'].includes(action)?{evidence}:{}),...(action==='verify'?{completionDate:completion,expiryDate:expiry||null}:{})}});}}><Field label="Action"><select className={selectStyle} value={action} onChange={e=>setAction(e.target.value)}>{r.canSubmit&&<option value="submit">Submit completion evidence</option>}{r.canVerify&&<option value="verify">Verify completed training</option>}{r.canVerify&&r.status==='submitted'&&<option value="return">Return for more evidence</option>}{r.canWithdraw&&<option value="withdraw">Withdraw assignment</option>}</select></Field><Field label="Reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{['submit','verify'].includes(action)&&<Field label="Completion evidence / certificate reference"><Textarea required minLength={5} value={evidence} onChange={e=>setEvidence(e.target.value)}/></Field>}{action==='verify'&&<><Field label="Completion date"><Input type="date" required value={completion} onChange={e=>setCompletion(e.target.value)}/></Field><Field label="Certificate expiry (optional)"><Input type="date" value={expiry} onChange={e=>setExpiry(e.target.value)}/></Field></>}<Button disabled={save.isPending}>Save training action</Button></form></details>}<History kind="learning" id={r.id}/></article>;}
