import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {useAuth} from '@/contexts/AuthContext';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Field,Panel,Paging,LoadState} from './Common';
import {useServiceSave} from './EmployeeServices';
export function PolicyHistory({kind}:{kind:'task_review_policy'|'waiver_policy'}){const [open,setOpen]=useState(false),q=useQuery<any[]>({queryKey:[`/api/workflow-controls/policy-history/${kind}`],enabled:open});return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Policy history</summary>{q.error&&<p role="alert">History unavailable.</p>}{q.data?.map(r=><p key={r.version}>v{r.version} · {(r.snapshot.owner_groups||r.snapshot.document_types).join(', ')||'None'} · {r.reason}</p>)}</details>;}
export function OnboardingReviewPolicy(){const {user}=useAuth(),allowed=['admin','super_admin'].includes(user?.role||''),q=useQuery<any>({queryKey:['/api/workflow-controls/task-review-policy'],enabled:allowed});return allowed?<Panel title="Onboarding review policy"><p>Choose task owner groups that need independent HR approval after the owner submits evidence. This applies to new onboarding cases; existing tasks retain their saved policy.</p>{q.error&&<p role="alert">Unable to load policy.</p>}{q.data&&<PolicyForm key={q.data.version} row={q.data}/>}<PolicyHistory kind="task_review_policy"/></Panel>:null;}
function PolicyForm({row:r}:{row:any}){const [groups,setGroups]=useState<string[]>(r.owner_groups),[reason,setReason]=useState(''),save=useServiceSave();return <form className="space-y-3" onSubmit={e=>{e.preventDefault();save.mutate({path:'workflow-controls/task-review-policy',body:{version:r.version,ownerGroups:groups,reason}});}}><div className="flex flex-wrap gap-4">{[['new_hire','New hire'],['hr','HR'],['manager','Manager'],['it','IT']].map(([value,label])=><label key={value}><input type="checkbox" checked={groups.includes(value)} onChange={e=>setGroups(e.target.checked?[...groups,value]:groups.filter(v=>v!==value))}/> {label}</label>)}</div><Field label="Policy change reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending}>Publish policy v{r.version+1}</Button></form>;}
export function OnboardingReviewQueue(){const [page,setPage]=useState(1),[includeCompleted,setIncludeCompleted]=useState(false),q=useQuery<any>({queryKey:['/api/workflow-controls/task-reviews',{page,includeCompleted:String(includeCompleted)}]});return <Panel title="Onboarding task reviews"><p>Review submitted evidence before completing the task. The owner, submitter and employee being onboarded cannot approve their own work. Returned tasks remain open for correction.</p><label><input type="checkbox" checked={includeCompleted} onChange={e=>{setIncludeCompleted(e.target.checked);setPage(1);}}/> Include completed and cancelled onboarding history</label><LoadState query={q}/>{q.data?.items.map((r:any)=><Review key={r.id+':'+r.version} row={r} canEdit={q.data.canEdit}/>)}<Paging page={page} setPage={setPage} count={q.data?.items.length||0}/></Panel>;}
function Review({row:r,canEdit}:{row:any;canEdit:boolean}){const [reason,setReason]=useState(''),[open,setOpen]=useState(false),save=useServiceSave(),q=useQuery<any[]>({queryKey:[`/api/workflow-controls/history/onboarding_task/${r.id}`],enabled:open});return <article className="space-y-3 rounded border p-3"><strong>{r.employee_name} · {r.task_name}</strong><p>Owner: {r.owner_name||'Unassigned'} · Due {r.due_date} · {r.review_state}</p><p className="whitespace-pre-wrap">{r.comments||'No evidence submitted yet.'}</p>{canEdit&&r.canReview&&r.review_state==='pending'&&<form className="flex flex-wrap gap-2" onSubmit={e=>e.preventDefault()}><Field label="Review decision reason"><Input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{['approve','return'].map(action=><Button key={action} disabled={save.isPending||reason.trim().length<5} variant={action==='return'?'outline':'default'} onClick={()=>save.mutate({path:`workflow-controls/task-reviews/${r.id}`,body:{version:r.version,action,reason}})}>{action==='approve'?'Approve and complete':'Return to owner'}</Button>)}</form>}<details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Task history</summary>{q.error&&<p role="alert">History unavailable.</p>}{q.data?.map(h=><div className="my-2 rounded border p-2" key={h.version}><p>v{h.version} · {h.snapshot.reviewState} · {h.reason}</p><p className="whitespace-pre-wrap">{h.snapshot.comments}</p></div>)}</details></article>;}
