import { useState } from 'react';
import { ArrowRight, CheckCircle2, Clock3, Inbox, ListChecks, Search, UserPlus, AlertCircle, CalendarDays, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Field, QueryError, fieldClass } from '@/components/hr/Operations';

export const words=(value:string)=>value.replaceAll('_',' ');
export function LifecycleStatus({value}:{value:string}){return <Badge variant="outline" className={value==='completed'||value==='approved'?'border-emerald-500/25 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300':value==='returned'||value==='cancelled'?'border-amber-500/25 bg-amber-500/10 text-amber-700 dark:text-amber-300':'bg-muted/50'}>{words(value)}</Badge>;}
export function TaskProgress({done,total}:{done:number;total:number}){const percent=total?Math.min(100,Math.round(done/total*100)):0;return <div className="min-w-28"><div className="mb-2 flex items-center justify-between gap-3 text-xs"><span>{done} / {total} required tasks</span>{total>0&&<span className="font-semibold">{percent}%</span>}</div><div role="progressbar" aria-label="Required checklist tasks complete" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all motion-reduce:transition-none" style={{width:`${percent}%`}}/></div></div>;}
type Row={record:{id:number;kind:string;startDate:string;status:string};name:string;required:number;completed:number;overdue:number;pendingReviews:number};
export function LifecycleWorkspace({rows,loading,error,queue,queueLoading,queueError,queueView,setQueueView,queueOffset,setQueueOffset,canManage,canReview,businessDate,open,start}:{rows:Row[];loading:boolean;error:unknown;queue:any;queueLoading:boolean;queueError:unknown;queueView:string;setQueueView:(v:string)=>void;queueOffset:number;setQueueOffset:(v:number)=>void;canManage:boolean;canReview:boolean;businessDate:string;open:(id:number,taskId?:number)=>void;start:()=>void}) {
  const [kind,setKind]=useState('onboarding'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[view,setView]=useState('workflows');
  const typed=rows.filter(r=>kind==='all'||r.record.kind===kind),filtered=typed.filter(r=>(status==='all'||r.record.status===status)&&r.name.toLowerCase().includes(search.toLowerCase()));
  const shown=filtered.slice((page-1)*12,page*12),active=typed.filter(r=>r.record.status==='in_progress');
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><Button variant={view==='workflows'?'default':'outline'} onClick={()=>setView('workflows')}><Users className="mr-2 h-4 w-4"/>Employee workflows</Button><Button variant={view==='tasks'?'default':'outline'} onClick={()=>setView('tasks')}><Inbox className="mr-2 h-4 w-4"/>Task inbox</Button></div>{canManage&&<Button onClick={start}><UserPlus className="mr-2 h-4 w-4"/>Start workflow</Button>}</div>
    {view==='workflows'?<>
      <div className="flex flex-wrap gap-2">{['onboarding','offboarding','all'].map(value=><Button size="sm" key={value} variant={kind===value?'secondary':'ghost'} aria-pressed={kind===value} onClick={()=>{setKind(value);setPage(1);}}>{value==='all'?'All workflows':value==='onboarding'?'Joining employees':'Leaving employees'}</Button>)}</div>
      {loading?<p role="status" className="rounded-xl border p-6">Loading employee workflows…</p>:error?<div className="rounded-xl border p-5"><QueryError error={error}/></div>:<>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{label:'In progress',value:active.length,icon:Clock3},{label:'Overdue tasks',value:active.reduce((n,r)=>n+r.overdue,0),icon:AlertCircle},{label:'Awaiting task review',value:active.reduce((n,r)=>n+r.pendingReviews,0),icon:ListChecks},{label:'Completed workflows',value:typed.filter(r=>r.record.status==='completed').length,icon:CheckCircle2}].map(m=><div key={m.label} className="rounded-2xl border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{m.label}</p><m.icon className="h-4 w-4 text-primary"/></div><p className="mt-3 text-3xl font-semibold tabular-nums">{m.value}</p></div>)}</div>
        <p className="text-xs text-muted-foreground">Overview for {kind==='all'?'all workflow types':kind} within your access{rows.length>=500?' · Latest 500 workflows loaded':''}. Task progress is separate from training and final clearance.</p>
        <section className="space-y-4 rounded-2xl border bg-card p-4 sm:p-5"><div className="flex flex-wrap items-end gap-3"><div className="min-w-48 flex-1"><Field label="Find employee"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input aria-label="Find employee workflow" className="pl-9" value={search} maxLength={100} placeholder="Search employee name" onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div></Field></div><Field label="Workflow status"><select className={fieldClass} value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="all">All statuses</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field>{(search||status!=='all')&&<Button variant="ghost" onClick={()=>{setSearch('');setStatus('all');setPage(1);}}>Clear filters</Button>}</div>
          {shown.length?<div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{shown.map(r=><article key={r.record.id} className="flex flex-col rounded-xl border p-4 transition-colors hover:border-primary/40"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-sm font-semibold text-primary">{r.name.split(/\s+/).slice(0,2).map(n=>n[0]).join('')}</span><div><h3 className="font-semibold">{r.name}</h3><p className="mt-1 text-xs text-muted-foreground">{r.record.kind==='onboarding'?'Onboarding':'Offboarding'} · #{r.record.id}</p></div></div><LifecycleStatus value={r.record.status}/></div><p className="my-4 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="h-4 w-4"/>{r.record.kind==='onboarding'?'Joining date':'Last employment date'}: {r.record.startDate}</p><TaskProgress done={r.completed} total={r.required}/><div className="mt-4 flex min-h-6 flex-wrap gap-2">{r.record.status==='in_progress'&&r.overdue>0&&<Badge variant="outline" className="text-destructive">{r.overdue} overdue</Badge>}{r.record.status==='in_progress'&&r.pendingReviews>0&&<Badge variant="secondary">{r.pendingReviews} awaiting review</Badge>}</div><Button variant="outline" className="mt-4 w-full justify-between" onClick={()=>open(r.record.id)}>Open checklist<ArrowRight className="h-4 w-4"/></Button></article>)}</div>:<div className="py-10 text-center"><ListChecks className="mx-auto mb-3 h-10 w-10 text-muted-foreground"/><h3 className="font-semibold">No matching workflows</h3><p className="mt-2 text-sm text-muted-foreground">{search||status!=='all'?'Try another name or status.':canManage?'Start a workflow using a saved checklist template.':'Your workflows will appear here when assigned.'}</p></div>}
          <div className="flex flex-wrap items-center justify-between gap-3 text-sm"><p>{filtered.length} workflows · Page {page} of {Math.max(1,Math.ceil(filtered.length/12))}</p><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><Button size="sm" variant="outline" disabled={page*12>=filtered.length} onClick={()=>setPage(page+1)}>Next</Button></div></div>
        </section>
      </>}
    </>:<section className="rounded-2xl border bg-card p-5 space-y-4"><div><h2 className="font-semibold">Your task inbox</h2><p className="mt-1 text-sm text-muted-foreground">Assigned work and independent reviews across onboarding and offboarding.</p></div><Field label="Task queue"><select className={fieldClass} value={queueView} onChange={e=>{setQueueView(e.target.value);setQueueOffset(0);}}><option value="mine">My open tasks</option>{canReview&&<><option value="review">Awaiting my independent review</option><option value="overdue">Overdue reviews</option></>}</select></Field><QueryError error={queueError}/>{queueLoading?<p role="status">Loading tasks…</p>:!queueError&&(queue?.items?.length?<div className="divide-y">{queue.items.map((r:any)=><article key={r.task.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="text-xs font-medium text-muted-foreground">{r.employeeName} · {words(r.kind)}</p><h3 className="mt-1 font-semibold">{r.task.title}</h3><p className="mt-2 text-xs text-muted-foreground">Owner: {r.ownerName} · Due {r.task.dueDate}{r.task.reviewDueDate?` · Review due ${r.task.reviewDueDate}`:''}</p><div className="mt-2 flex gap-2"><LifecycleStatus value={r.task.reviewState==='pending'?'awaiting_review':r.task.reviewState==='returned'?'returned':'pending'}/>{r.task.dueDate<businessDate&&<Badge variant="outline" className="text-destructive">Task overdue</Badge>}</div></div><Button variant="outline" onClick={()=>open(r.task.caseId,r.task.id)}>Open task<ArrowRight className="ml-2 h-4 w-4"/></Button></article>)}</div>:<div className="py-8 text-center"><CheckCircle2 className="mx-auto mb-3 h-9 w-9 text-emerald-500"/><h3 className="font-medium">No tasks in this queue</h3><p className="mt-2 text-sm text-muted-foreground">Choose another queue or return to employee workflows.</p></div>)}<div className="flex gap-2"><Button variant="outline" disabled={!queueOffset} onClick={()=>setQueueOffset(queueOffset-50)}>Previous tasks</Button><Button variant="outline" disabled={!queue?.hasMore} onClick={()=>setQueueOffset(queueOffset+50)}>Next tasks</Button></div></section>}
  </div>;
}

export function LifecycleReadiness({detail,onSection}:{detail:any;onSection:(section:string)=>void}){
  const r=detail.readiness;if(!r)return <p className="text-sm text-muted-foreground">You can see your assigned tasks. HR reviews the complete workflow before closing it.</p>;
  const checks:{name:string;count:number;section?:string;href?:string}[]=[{name:'Required checklist tasks',count:r.requiredPending,section:'tasks'},{name:'Independent reviews',count:r.pendingReviews,section:'tasks'},...(detail.record.kind==='onboarding'?[{name:'Required training',count:r.inductionPending,section:'training'},{name:'Handbook acknowledgements',count:r.handbookPending,href:'/handbook'},{name:'Salary and benefits recorded',count:r.compensationMissing?1:0,section:detail.canCompensation?'compensation':undefined}]:[{name:'Equipment clearance',count:r.equipmentOpen,href:'/equipment'},{name:'Last employment date reached',count:r.futureExit?1:0}])];
  return <div className="rounded-xl border p-4"><h3 className="mb-3 text-sm font-semibold">Completion requirements</h3><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{checks.map(c=><div key={c.name} className={`flex items-start gap-2 rounded-lg p-3 ${c.count?'bg-amber-500/5':'bg-emerald-500/5'}`}>{c.count?<Clock3 className="mt-0.5 h-4 w-4 shrink-0 text-amber-600"/>:<CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>}<div><p className="text-xs font-medium">{c.name}</p><p className="mt-1 text-xs text-muted-foreground">{c.count?c.name==='Salary and benefits recorded'?'Required':c.name==='Last employment date reached'?'Not yet':`${c.count} outstanding`:'Clear'}</p>{c.count>0&&c.section&&<button type="button" className="mt-2 text-xs font-medium text-primary underline" onClick={()=>onSection(c.section!)}>Open section</button>}{c.count>0&&c.href&&<a className="mt-2 inline-block text-xs font-medium text-primary underline" href={c.href}>Open records</a>}</div></div>)}</div><p className="mt-3 text-xs text-muted-foreground">Document validity and final eligibility are checked again when HR completes the workflow.</p></div>;
}
