import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Button} from '@/components/ui/button';
import {Field,Section,Table,fieldClass,useAction,QueryError} from '@/components/hr/Operations';
import {taskKinds, type LifecycleTaskDefinition} from '@shared/lifecycle';

const blankTask=():LifecycleTaskDefinition=>({title:'',kind:'general',required:true,offsetDays:0,reviewRequired:false,documentType:''});
export function LifecycleTemplates({templates,canEdit}:{templates:any[];canEdit:boolean}){
  const [edit,setEdit]=useState<any>(null),[history,setHistory]=useState<number|null>(null),[offset,setOffset]=useState(0);
  const versions=useQuery<any[]>({queryKey:[`/api/lifecycle/templates/${history}/history`,{offset}],enabled:!!history});
  const action=useAction(()=>setEdit(null));
  const setTask=(i:number,patch:Partial<LifecycleTaskDefinition>)=>setEdit({...edit,tasks:edit.tasks.map((t:any,j:number)=>i===j?{...t,...patch}:t)});
  return <Section title="Checklist templates"><p>Each workflow keeps the template version used when it started. Revisions and archiving affect future workflows.</p>
    <Table headers={['Template','Type','Version','Availability','Actions']} rows={templates.map(t=>[t.name,t.kind,t.version,t.active?'Active':'Archived',<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{setHistory(t.id);setOffset(0);}}>Version history</Button>{canEdit&&<Button variant="outline" onClick={()=>setEdit({...t,reason:'',tasks:t.tasks.map((d:any)=>({...blankTask(),...d}))})}>Revise template</Button>}</div>])}/>
    {canEdit&&<Button variant="outline" onClick={()=>setEdit({name:'',kind:'onboarding',active:true,tasks:[blankTask()],reason:''})}>New template</Button>}
    {history&&<div className="space-y-3 border rounded p-4"><h3 className="font-semibold">Template version history</h3><QueryError error={versions.error}/>{versions.isLoading?<p>Loading versions…</p>:<Table headers={['Version','Reason','Saved checklist']} rows={(versions.data||[]).map(v=>[v.version,v.reason,<details><summary>{v.snapshot.name} · {v.snapshot.active?'Active':'Archived'}</summary><ul className="list-disc pl-5">{v.snapshot.tasks.map((t:any,i:number)=><li key={i}>{t.title} · {t.kind} · {t.required?'Required':'Optional'} · {t.offsetDays} days · {t.reviewRequired?'Independent review':'Company review rules'}{t.documentType?` · ${t.documentType}`:''}</li>)}</ul></details>])}/>}<Button variant="outline" disabled={!offset} onClick={()=>setOffset(offset-25)}>Newer versions</Button> <Button variant="outline" disabled={versions.data?.length!==25} onClick={()=>setOffset(offset+25)}>Older versions</Button></div>}
    {edit&&<form className="space-y-4 border rounded p-4" onSubmit={e=>{e.preventDefault();action.mutate({url:edit.id?`/api/lifecycle/templates/${edit.id}`:'/api/lifecycle/templates',method:edit.id?'PATCH':'POST',body:{name:edit.name,kind:edit.kind,tasks:edit.tasks,reason:edit.reason,...(edit.id?{version:edit.version,active:edit.active}:{})}});}}>
      <h3 className="font-semibold">{edit.id?`Revise version ${edit.version}`:'Create a checklist'}</h3><div className="grid gap-3 md:grid-cols-2"><Field label="Template name"><input className={fieldClass} required maxLength={150} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="Workflow type"><select className={fieldClass} disabled={!!edit.id} value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value})}><option value="onboarding">Onboarding</option><option value="offboarding">Offboarding</option></select></Field></div>
      {edit.id&&<label className="block"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Available for new workflows</label>}
      {edit.tasks.map((t:LifecycleTaskDefinition,i:number)=><fieldset key={i} className="border rounded p-3 space-y-3"><legend className="px-1">Task {i+1}</legend><div className="grid gap-3 md:grid-cols-3"><Field label="Task title"><input className={fieldClass} required maxLength={200} value={t.title} onChange={e=>setTask(i,{title:e.target.value})}/></Field><Field label="Evidence type"><select className={fieldClass} value={t.kind} onChange={e=>setTask(i,{kind:e.target.value as any,documentType:''})}><option value="general">General</option><option value="document">Document collection</option><option value="asset_return">Asset return</option></select></Field><Field label="Calendar days from workflow date"><input className={fieldClass} required type="number" min={-90} max={365} value={t.offsetDays} onChange={e=>setTask(i,{offsetDays:Number(e.target.value)})}/></Field></div>
        {t.kind==='document'&&<Field label="Required document type (exact name; blank accepts any)"><input className={fieldClass} maxLength={100} value={t.documentType} onChange={e=>setTask(i,{documentType:e.target.value})}/></Field>}
        <div className="flex flex-wrap gap-4"><label><input type="checkbox" checked={t.required} onChange={e=>setTask(i,{required:e.target.checked})}/> Required for completion</label><label><input type="checkbox" checked={t.reviewRequired} onChange={e=>setTask(i,{reviewRequired:e.target.checked})}/> Require independent review</label><Button type="button" variant="outline" disabled={edit.tasks.length===1} onClick={()=>setEdit({...edit,tasks:edit.tasks.filter((_:any,j:number)=>j!==i)})}>Remove task</Button></div>
      </fieldset>)}
      <p className="text-sm text-muted-foreground">Administrator rules may require review even when a task's checkbox is cleared.</p><Button type="button" variant="outline" disabled={edit.tasks.length>=100} onClick={()=>setEdit({...edit,tasks:[...edit.tasks,blankTask()]})}>Add task</Button><Field label="Reason for template change"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={edit.reason} onChange={e=>setEdit({...edit,reason:e.target.value})}/></Field><Button disabled={action.isPending}>Save template version</Button> <Button type="button" variant="outline" onClick={()=>setEdit(null)}>Close editor</Button>
    </form>}
  </Section>;
}
export function LifecycleReviewPolicy({canEdit}:{canEdit:boolean}){
  const policy=useQuery<any>({queryKey:['/api/lifecycle/review-policy']}),[edit,setEdit]=useState<any>(null),[history,setHistory]=useState(false),[offset,setOffset]=useState(0);
  const versions=useQuery<any[]>({queryKey:['/api/lifecycle/review-policy/history',{offset}],enabled:history}),action=useAction(()=>setEdit(null));
  return <Section title="Checklist approval rules"><QueryError error={policy.error}/><p>Rules apply to new onboarding and offboarding workflows. Existing tasks keep their original review requirement and target.</p>{policy.data&&<><p>Version {policy.data.version} · Review required for: {policy.data.taskKinds.join(', ')||'Only tasks selected in their template'} · Review target: {policy.data.reviewDays} calendar days after submission.</p>{canEdit&&<Button variant="outline" onClick={()=>setEdit({...policy.data,reason:''})}>Edit approval rules</Button>}</>}
    {edit&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();action.mutate({url:'/api/lifecycle/review-policy',body:edit});}}><fieldset><legend className="font-medium">Always require independent review</legend>{taskKinds.map(kind=><label key={kind} className="block"><input type="checkbox" checked={edit.taskKinds.includes(kind)} onChange={e=>setEdit({...edit,taskKinds:e.target.checked?[...edit.taskKinds,kind]:edit.taskKinds.filter((v:string)=>v!==kind)})}/> {kind.replace('_',' ')}</label>)}</fieldset><Field label="Review target in calendar days"><input className={fieldClass} required type="number" min={1} max={365} value={edit.reviewDays} onChange={e=>setEdit({...edit,reviewDays:Number(e.target.value)})}/></Field><Field label="Reason for rule change"><textarea className={fieldClass} required minLength={5} maxLength={2000} value={edit.reason} onChange={e=>setEdit({...edit,reason:e.target.value})}/></Field><Button disabled={action.isPending}>Save approval rules</Button> <Button type="button" variant="outline" onClick={()=>setEdit(null)}>Cancel edit</Button></form>}
    <Button variant="outline" onClick={()=>setHistory(!history)}>Rule history</Button>{history&&<><QueryError error={versions.error}/><Table headers={['Version','Required types','Days','Reason']} rows={(versions.data||[]).map(v=>[v.version,v.task_kinds.join(', ')||'Template selection only',v.review_days,v.reason])}/><Button variant="outline" disabled={!offset} onClick={()=>setOffset(offset-25)}>Newer rules</Button> <Button variant="outline" disabled={versions.data?.length!==25} onClick={()=>setOffset(offset+25)}>Older rules</Button></>}
  </Section>;
}
