import {useId,useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Link} from 'wouter';
import {Download,FileText,Printer,Landmark,Settings2,RefreshCw,CheckCheck,AlertCircle,Search,ChevronDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Field,Section,Table,QueryError,fieldClass} from '@/components/hr/Operations';
import {MetricCard,StatusPill} from '@/components/ux/ModuleVisuals';
import {apiJson,apiRequest} from '@/lib/queryClient';
import {useToast} from '@/hooks/use-toast';
import {deductionReasons,paymentTypes,exportKinds,exportKindLabels,employeeIssues,recordIssues,type ExportFilter,type PayrollExportPreview,type PayrollExportRow,type WpsRecord,type WpsEmployee,type WpsSettings} from '@shared/payroll-exports';
import {moneyCents,moneyText} from '@shared/money';

const base='/api/payroll/exports';
export default function PayrollExports({period,setPeriod,initialId}:{period:string;setPeriod:(value:string)=>void;initialId?:number}){
  const [exportExpanded,setExportExpanded]=useState(false),actionsId=useId();
  const [kind,setKind]=useState<ExportFilter['kind']>('all'),[teamId,setTeam]=useState(''),[siteId,setSite]=useState('');
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Set<number>>(()=>new Set(initialId?[initialId]:[])),[editing,setEditing]=useState<PayrollExportRow|null>(null);
  const [confirm,setConfirm]=useState(false),[confirmed,setConfirmed]=useState(false),[reexport,setReexport]=useState(false),[reason,setReason]=useState('');
  const [year,month]=period.split('-').map(Number),cache=useQueryClient(),{toast}=useToast();
  const filter:ExportFilter={year,month,kind,...(teamId?{teamId:Number(teamId)}:{}),...(siteId?{siteId:Number(siteId)}:{})};
  const query=useQuery<PayrollExportPreview>({queryKey:[base+'/preview',filter],enabled:!!year&&!!month,refetchOnWindowFocus:false});
  const data=query.data,rows=data?.rows||[],shown=rows.filter(r=>(status==='all'||r.status===status)&&`${r.name} ${r.employeeRef} ${r.department}`.toLowerCase().includes(search.toLowerCase())),chosen=rows.filter(r=>selected.has(r.id));
  const selectable=shown.filter(r=>r.status!=='cancelled'),ready=selectable.filter(r=>r.wps&&!r.wps.issues.length&&!r.wps.lastExport);
  const issues=chosen.filter(r=>r.wps?.issues.length),repeat=chosen.some(r=>r.wps?.lastExport);
  const totals=chosen.reduce((values,row)=>{const currency=row.currency||'Unspecified';values.set(currency,(values.get(currency)||0)+moneyCents(row.net));return values;},new Map<string,number>());
  const sites=[...new Map((data?.teams||[]).filter(team=>kind==='all'||team.kind===kind).map(team=>[team.siteId,{id:team.siteId,name:team.siteName}])).values()];
  const refresh=()=>cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith(base)});
  const download=useMutation({mutationFn:async({format,popup}:{format:'payslips'|'csv'|'wps';popup?:Window|null})=>{
    if(popup===null)throw new Error('Allow pop-ups to print or save payslips as PDF.');
    try{
      const response=await apiRequest(base+'/download',{method:'POST',body:{filter,records:chosen.map(r=>({id:r.id,fingerprint:r.fingerprint})),format,settingsVersion:data?.settingsVersion,confirmed,allowReexport:reexport,reason}});
      const filename=response.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]||`payroll-${period}.${format==='payslips'?'html':'csv'}`;
      if(popup){popup.opener=null;popup.document.write(await response.text());popup.document.close();popup.focus();popup.print();}
      else {const url=URL.createObjectURL(await response.blob()),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
      return {format,filename};
    }catch(error){popup?.close();throw error;}
  },onSuccess:({format,filename})=>{toast({title:format==='wps'?'WPS file prepared':'Payslip export prepared',description:filename});if(format==='wps'){setConfirm(false);setSelected(new Set());void refresh();}}});
  function resetSelection(){setSelected(new Set());download.reset();}
  const busy=download.isPending||query.isFetching;
  return <div className="space-y-5">
    <Section title="Payslips & WPS exports"><div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-2xl text-sm text-muted-foreground">Choose a payment month and team, select employees, then export their saved payroll.</p>{data?.canConfigure&&<Button variant="outline" asChild><Link href="/settings/wps"><Settings2 className="mr-2 h-4 w-4"/>WPS settings</Link></Button>}</div>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Payment month"><input className={fieldClass} type="month" value={period} onChange={e=>{if(e.target.value){resetSelection();setPeriod(e.target.value);}}}/></Field><Field label="Employee group"><select className={fieldClass} value={kind} onChange={e=>{setKind(e.target.value as ExportFilter['kind']);setTeam('');setSite('');resetSelection();}}>{exportKinds.map(value=><option value={value} key={value}>{exportKindLabels[value]}</option>)}</select></Field><Field label="Mall / FEC / event team"><select className={fieldClass} value={teamId} onChange={e=>{setTeam(e.target.value);resetSelection();}}><option value="">All matching teams</option>{data?.teams.filter(t=>(kind==='all'||t.kind===kind)&&(!siteId||t.siteId===Number(siteId))).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Work site"><select className={fieldClass} value={siteId} onChange={e=>{setSite(e.target.value);setTeam('');resetSelection();}}><option value="">All matching sites</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name}</option>)}</select></Field></div>
      <p className="text-xs text-muted-foreground">Teams match membership during the saved salary period. Head Office also includes employees on the office calendar. Each selected employee's complete payslip is exported once; this is not a salary split between locations.</p>
    </Section>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard label="Matching payroll" value={query.isLoading?'…':query.error?'—':rows.length} icon={FileText}/><MetricCard label="Selected" value={chosen.length} icon={CheckCheck}/>{data?.canWps&&<MetricCard label="WPS ready · not exported" value={data.settingsIssues.length?'Setup needed':ready.length} icon={Landmark} tone="positive"/>}{[...totals].map(([currency,cents])=><MetricCard key={currency} label={`Selected net · ${currency}`} value={Number(moneyText(cents)).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}/>)}</div>
    <QueryError error={query.error||download.error}/>{query.error&&<Button variant="outline" onClick={()=>query.refetch()}>Retry</Button>}
    {data?.canWps&&data.settingsIssues.length>0&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-100"><p className="flex items-center gap-2 font-semibold"><AlertCircle className="h-4 w-4"/>Company WPS setup needed</p><ul className="mt-2 list-disc space-y-1 pl-5">{data.settingsIssues.map(issue=><li key={issue}>{issue}</li>)}</ul>{data.canConfigure?<Link href="/settings/wps" className="mt-3 inline-block font-medium underline">Complete WPS settings</Link>:<p className="mt-2">Ask an administrator to complete the payer settings.</p>}</div>}
    <Section title="Select employees"><div className="flex flex-wrap items-end gap-3"><div className="min-w-0 w-full sm:flex-1 sm:w-auto"><Field label="Find employee"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder="Name, staff ID or department" value={search} onChange={e=>setSearch(e.target.value)}/></div></Field></div><Field label="Payroll status"><select className={fieldClass} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{[...new Set(rows.map(r=>r.status))].map(value=><option key={value} value={value}>{value==='processed'?'Paid':value}</option>)}</select></Field><Button variant="outline" disabled={query.isFetching} onClick={()=>{download.reset();void refresh();}}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
      <div className="flex flex-wrap items-center gap-2"><Button variant="outline" size="sm" disabled={!selectable.length||busy} onClick={()=>setSelected(new Set(selectable.slice(0,500).map(r=>r.id)))}>Select matching ({Math.min(selectable.length,500)})</Button>{data?.canWps&&<Button variant="outline" size="sm" disabled={!ready.length||busy||!!data.settingsIssues.length} onClick={()=>setSelected(new Set(ready.slice(0,500).map(r=>r.id)))}>Select WPS ready</Button>}<Button variant="ghost" size="sm" disabled={!chosen.length||busy} onClick={resetSelection}>Clear selection</Button><span className="text-xs text-muted-foreground">Up to 500 payslips per export · {chosen.length} selected across search results</span></div>
      {query.isLoading?<p role="status">Loading payroll for export…</p>:<Table pageSize={12} headers={['Select','Employee','Team / site','Net pay','Status',...(data?.canWps?['WPS readiness']:[]),'Action']} rows={shown.map(row=>[
        <input type="checkbox" aria-label={`Select payroll for ${row.name}`} checked={selected.has(row.id)} disabled={busy||row.status==='cancelled'||!selected.has(row.id)&&chosen.length>=500} onChange={e=>setSelected(current=>{const next=new Set(current);e.target.checked?next.add(row.id):next.delete(row.id);return next;})}/>,
        <div><p className="font-medium">{row.name}</p><p className="text-xs text-muted-foreground">{row.employeeRef} · {row.department}</p></div>,row.groups.map(g=>g.name).join(' · ')||(row.headOffice?'Head Office':'Unassigned'),`${row.currency||'—'} ${row.net}`,<StatusPill value={row.status==='processed'?'paid':row.status}/>,
        ...(data?.canWps?[<div className="text-xs">{row.wps?.issues.length?<span className="text-amber-700 dark:text-amber-300">{row.wps.issues.length} items to review</span>:<span className="text-emerald-700 dark:text-emerald-300">Employee details ready</span>}{row.wps?.lastExport&&<p className="mt-1">Previously exported {new Date(row.wps.lastExport.at).toLocaleDateString()}</p>}</div>]:[]),
        data?.canWps?<Button variant="outline" size="sm" onClick={()=>setEditing(row)}>WPS details</Button>:<span className="text-xs text-muted-foreground">Select to export</span>,
      ])}/>}
      {!query.isLoading&&!query.error&&!rows.length&&<p className="rounded-xl bg-muted p-4 text-sm">No saved payroll matches this month and group. Generate payroll in Pay runs, or choose another payment month.</p>}
    </Section>
    <div className="sticky bottom-20 z-10 space-y-3 rounded-2xl border bg-card/95 p-4 shadow-lg backdrop-blur md:bottom-3"><Button variant="ghost" className="w-full justify-between md:hidden" aria-expanded={exportExpanded} aria-controls={actionsId} onClick={()=>setExportExpanded(value=>!value)}>{chosen.length} selected · Export options<ChevronDown className={`h-4 w-4 transition-transform ${exportExpanded?'rotate-180':''}`}/></Button><div id={actionsId} className={exportExpanded?'space-y-3':'hidden space-y-3 md:block'}><div className="flex flex-wrap gap-2"><Button disabled={!chosen.length||busy} onClick={()=>download.mutate({format:'payslips',popup:window.open('','_blank')})}><Printer className="mr-2 h-4 w-4"/>Print / Save PDF</Button><Button variant="outline" disabled={!chosen.length||busy} onClick={()=>download.mutate({format:'payslips'})}><FileText className="mr-2 h-4 w-4"/>Download payslips</Button><Button variant="outline" disabled={!chosen.length||busy} onClick={()=>download.mutate({format:'csv'})}><Download className="mr-2 h-4 w-4"/>Payroll CSV</Button>{data?.canWps&&<Button variant="outline" disabled={!chosen.length||busy||!!data.settingsIssues.length||!!issues.length} onClick={()=>{setConfirmed(false);setReexport(false);setReason('');download.reset();setConfirm(true);}}><Landmark className="mr-2 h-4 w-4"/>Export WPS SIF</Button>}</div><p className="text-xs text-muted-foreground">Payslips download as a printable HTML document. Save as PDF uses your browser. WPS export creates a bank-upload file; it does not transfer money or mark payroll paid.{!!issues.length&&` ${issues.length} selected records need WPS corrections.`}</p></div></div>
    {editing?.wps&&data?.settings&&<WpsDetails key={editing.id+':'+editing.fingerprint} row={editing} settings={data.settings} close={()=>setEditing(null)} saved={()=>{setEditing(null);void refresh();}}/>}
    <Dialog open={confirm} onOpenChange={value=>{if(!download.isPending)setConfirm(value);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Export Qatar WPS file</DialogTitle><DialogDescription>Review this selection before preparing a SIF v1 file for your bank.</DialogDescription></DialogHeader><div className="space-y-4"><div className="rounded-xl bg-muted p-4"><p className="font-semibold">{chosen.length} employees · {period}</p>{[...totals].map(([currency,cents])=><p key={currency}>{currency} {moneyText(cents)}</p>)}<p className="mt-2 text-xs">Employer: {data?.settings?.employerEid} · Payer bank: {data?.settings?.payerBank}</p></div><label className="flex gap-3 text-sm"><input className="mt-1" type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I have reviewed the selected employees, approved amounts, identity details and bank accounts.</span></label>{repeat&&<><label className="flex gap-3 text-sm"><input className="mt-1" type="checkbox" checked={reexport} onChange={e=>setReexport(e.target.checked)}/><span>Some payroll was already exported. I have checked whether the earlier file was submitted to the bank and need another export.</span></label><Field label="Reason for re-export"><textarea className={fieldClass} minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field></>}<QueryError error={download.error}/><Button disabled={!confirmed||download.isPending||repeat&&(!reexport||reason.trim().length<5)} onClick={()=>download.mutate({format:'wps'})}>{download.isPending?'Preparing…':'Download WPS file'}</Button></div></DialogContent></Dialog>
  </div>;
}

function WpsDetails({row,settings,close,saved}:{row:PayrollExportRow;settings:WpsSettings;close:()=>void;saved:()=>void}){
  const wps=row.wps!,[person,setPerson]=useState<WpsEmployee>(wps.employee),[pay,setPay]=useState<WpsRecord>(wps.record),[note,setNote]=useState('');
  const save=useMutation({mutationFn:(kind:'employee'|'record')=>apiJson(`${base}/${kind==='employee'?'employees/'+row.employeeId:'records/'+row.id}`,{method:'PUT',body:kind==='employee'?{version:wps.employeeVersion,employee:person,reason:note}:{version:wps.recordVersion,record:pay,fingerprint:row.fingerprint,reason:note}}),onSuccess:saved});
  const identityIssues=employeeIssues(person,settings),payIssues=recordIssuesSafe(pay,row.net);
  return <Dialog open onOpenChange={value=>{if(!value&&!save.isPending)close();}}><DialogContent className="max-h-[90dvh] max-w-3xl overflow-y-auto [&>*]:min-w-0"><DialogHeader><DialogTitle>WPS details · {row.name}</DialogTitle><DialogDescription>Bank details apply to this employee. Salary details apply only to payroll #{row.id}; saved net pay remains {row.currency} {row.net}.</DialogDescription></DialogHeader>
    <Tabs defaultValue="employee" className="min-w-0"><TabsList><TabsTrigger value="employee">Employee & bank</TabsTrigger><TabsTrigger value="record">Salary details</TabsTrigger><TabsTrigger value="issues">Readiness ({wps.issues.length})</TabsTrigger></TabsList>
      <TabsContent value="employee"><form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate('employee');}}><fieldset disabled={save.isPending} className="space-y-4"><Field label="Name as on QID / visa"><input className={fieldClass} value={person.name} maxLength={70} onChange={e=>setPerson({...person,name:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Employee QID"><input className={fieldClass} value={person.qid} maxLength={11} inputMode="numeric" onChange={e=>setPerson({...person,qid:e.target.value,visaId:e.target.value?'':person.visaId})}/></Field><Field label="Visa ID (when there is no QID)"><input className={fieldClass} value={person.visaId} maxLength={12} onChange={e=>setPerson({...person,visaId:e.target.value,qid:e.target.value?'':person.qid})}/></Field><Field label="Employee bank short code"><input className={fieldClass} maxLength={4} value={person.bank} onChange={e=>setPerson({...person,bank:e.target.value.toUpperCase()})}/></Field><Field label="Employee IBAN / same-bank account"><input className={fieldClass} autoComplete="off" maxLength={40} value={person.account} onChange={e=>setPerson({...person,account:e.target.value.replace(/\s/g,'').toUpperCase()})}/></Field></div><IssueList issues={identityIssues}/><p className="text-xs text-muted-foreground">These are dedicated WPS payment details. Changes here do not rewrite the employee's general profile.</p><Field label="Reason for bank or identity change"><textarea className={fieldClass} value={note} minLength={5} maxLength={1000} required onChange={e=>setNote(e.target.value)}/></Field><QueryError error={save.error}/><Button disabled={save.isPending||note.trim().length<5}>Save employee WPS details</Button></fieldset></form></TabsContent>
      <TabsContent value="record"><form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate('record');}}><fieldset disabled={save.isPending} className="space-y-4"><IssueList issues={wps.warnings}/><div className="grid gap-4 sm:grid-cols-2">{([['basic','Contractual basic salary (QAR)'],['extraIncome','Extra income (QAR)'],['deductions','Total deductions (QAR)'],['extraHours','Overtime hours']] as const).map(([key,label])=><Field key={key} label={label}><input className={fieldClass} value={pay[key]} inputMode="decimal" required onChange={e=>setPay({...pay,[key]:e.target.value})}/></Field>)}<Field label="Working days (optional)"><input className={fieldClass} type="number" min={0} max={999} step={1} value={pay.workingDays??''} onChange={e=>setPay({...pay,workingDays:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label="Deduction reason"><select className={fieldClass} value={pay.deductionReason} onChange={e=>setPay({...pay,deductionReason:e.target.value as WpsRecord['deductionReason']})}><option value="">Choose if deductions apply</option>{Object.entries(deductionReasons).map(([key,label])=><option key={key} value={key}>{key} · {label}</option>)}</select></Field><Field label="Payment type"><select className={fieldClass} value={pay.paymentType} onChange={e=>setPay({...pay,paymentType:e.target.value as WpsRecord['paymentType']})}>{paymentTypes.map(type=><option key={type}>{type}</option>)}</select></Field></div><Field label="WPS notes / comments"><textarea className={fieldClass} value={pay.notes} maxLength={300} onChange={e=>setPay({...pay,notes:e.target.value})}/></Field><IssueList issues={payIssues}/><p className="rounded-xl bg-muted p-3 text-sm">Basic + extra income − deductions must equal the approved net amount: <strong>{row.currency} {row.net}</strong>. Payroll amounts and approval status are unchanged.</p><Field label="Reason for reviewing these WPS figures"><textarea className={fieldClass} value={note} minLength={5} maxLength={1000} required onChange={e=>setNote(e.target.value)}/></Field><QueryError error={save.error}/><Button disabled={save.isPending||note.trim().length<5||!!payIssues.length}>Save WPS salary details</Button></fieldset></form></TabsContent>
      <TabsContent value="issues"><IssueList issues={wps.issues}/>{!wps.issues.length&&<p className="p-4 text-sm text-emerald-700 dark:text-emerald-300">Employee and payroll details are ready. Company settings and the final selection are checked again before download.</p>}{wps.lastExport&&<p className="mt-3 break-all text-xs text-muted-foreground">Last export: {wps.lastExport.filename} · {new Date(wps.lastExport.at).toLocaleString()}</p>}</TabsContent>
    </Tabs></DialogContent></Dialog>;
}
function IssueList({issues}:{issues:string[]}){return issues.length?<ul className="list-disc space-y-1 rounded-xl bg-amber-50 p-4 pl-8 text-sm text-amber-950 dark:bg-amber-950/30 dark:text-amber-100">{issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:null;}
function recordIssuesSafe(pay:WpsRecord,net:string){try{return recordIssues(pay,net);}catch{return ['Enter valid monetary amounts with no more than two decimal places.'];}}
