import {useState} from 'react';
import {Link} from 'wouter';
import {LayoutGrid,Search,ArrowUpRight} from 'lucide-react';
import {usePageAccess} from '@/hooks/usePageAccess';
import {pageLabel} from '@shared/navigation';
import {ModuleIcon} from './ModuleVisuals';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const descriptions:Record<string,string>={
 '/':'Your overview and next actions','/account':'Your profile and sign-in settings','/communications':'Messages, announcements and channels','/helpdesk':'Raise a question and track HR support','/employees':'Find people and manage employee records','/org-charts':'Company and operational reporting lines','/recruitment':'Vacancies, candidates, interviews and offers','/onboarding':'Joining and leaving checklists','/employment':'Contracts and service history','/team-overview':'Staffing, approvals and team follow-ups','/workforce':'Teams, venues, rosters and shift offers','/event-staff':'Event staffing and assignments','/attendance':'Clock-in records and attendance review','/timesheets':'Worked hours and time approvals','/leave':'Balances, requests and the leave calendar','/payroll':'Pay runs, review and payslips','/benefits':'Entitlements and benefit requests','/expenses':'Claims, receipts and reimbursement','/documents':'Employee documents and renewal tracking','/hr-letters':'Request, prepare and issue HR letters','/equipment':'Assigned items and return tracking','/handbook':'Policies and acknowledgements','/learning':'Courses, training and qualifications','/performance':'Goals, reviews and development','/assignment-reviews':'Feedback on completed assignments','/reports':'Build reports and revisit saved results','/retention':'Record retention and review decisions','/bulk-import':'Validate and import employee records','/user-management':'Accounts, roles and access controls','/hr-rules':'Attendance, leave and salary policies','/operations-setup':'Prepare staff access and operational coverage','/reminder-rules':'Configure scheduled reminders','/settings':'All HR policies, leave, payroll, training, accounts, branding and services'};
export default function ModuleLauncher(){
 const [open,setOpen]=useState(false),[search,setSearch]=useState('');const {user,pages}=usePageAccess();
 const visible=pages.filter(p=>`${pageLabel(p,user!.role)} ${p.section} ${descriptions[p.href]||''}`.toLowerCase().includes(search.toLowerCase()));
 return <Dialog open={open} onOpenChange={value=>{setOpen(value);if(!value)setSearch('');}}><Button variant="outline" size="sm" aria-label="Browse modules" onClick={()=>setOpen(true)}><LayoutGrid className="h-4 w-4"/><span className="hidden sm:inline">Modules</span></Button><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>What would you like to do?</DialogTitle><DialogDescription>Choose a workspace available to your account.</DialogDescription></DialogHeader><label className="flex items-center gap-3 rounded-xl border px-3 py-2"><Search aria-hidden="true" className="h-4 w-4 text-muted-foreground"/><span className="sr-only">Search workspaces</span><input autoFocus type="search" placeholder="Search people, leave, payroll…" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 bg-transparent py-1 text-sm outline-none"/></label><div className="max-h-[58dvh] overflow-y-auto pr-1 space-y-5">{[...new Set(visible.map(p=>p.section))].map(section=><section key={section}><h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{section}</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{visible.filter(p=>p.section===section).map(p=><Link key={p.href} data-section={p.section} href={p.href} onClick={()=>{setOpen(false);setSearch('');}} className="module-card-link group flex items-start gap-3 rounded-xl border p-4 hover:border-primary/40 hover:bg-primary/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="section-icon"><ModuleIcon name={p.icon}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{pageLabel(p,user!.role)}</span><span className="mt-1 block text-xs leading-relaxed text-muted-foreground">{descriptions[p.href]}</span></span><ArrowUpRight aria-hidden="true" className="h-3 w-3 shrink-0 text-muted-foreground"/></Link>)}</div></section>)}{!visible.length&&<p role="status" className="py-8 text-center text-sm text-muted-foreground">No available workspaces match your search.</p>}</div></DialogContent></Dialog>;
}
