import {useState,type ReactNode} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'wouter';
import {apiJson} from '@/lib/queryClient';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useToast} from '@/hooks/use-toast';
import {siteTimeToIso,type ShiftView} from '@shared/workforce';
const selectClass='w-full rounded-md border bg-background p-2 text-sm';
const day=(offset:number)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
const stamp=(v:string,zone:string)=>new Date(v).toLocaleString([],{timeZone:zone,dateStyle:'medium',timeStyle:'short'});
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1 text-sm">{label}{children}</label>;}
function useOperation(){const cache=useQueryClient(),{toast}=useToast();return useMutation({mutationFn:({url,body,method='POST'}:{url:string;body:unknown;method?:string})=>apiJson<any>(url,{method,body}),onSuccess:async()=>{await cache.invalidateQueries({predicate:q=>['/api/workforce/','/api/team-overview','/api/leaves','/api/timesheets','/api/assignment-reviews'].some(prefix=>String(q.queryKey[0]).startsWith(prefix))});toast({title:'Saved'});},onError:(e:Error)=>toast({title:'Unable to save',description:e.message,variant:'destructive'})});}
function Pager({page,setPage,more}:{page:number;setPage:(n:number)=>void;more:boolean}){return <div className="flex items-center gap-3 pt-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(page-1)}>Previous</Button><span className="text-sm">Page {page}</span><Button variant="outline" disabled={!more} onClick={()=>setPage(page+1)}>Next</Button></div>;}
export function Availability(){
 const zone=Intl.DateTimeFormat().resolvedOptions().timeZone,[from,setFrom]=useState(day(0)),[start,setStart]=useState(''),[end,setEnd]=useState(''),[kind,setKind]=useState('available'),[error,setError]=useState('');
 const range={from:from+'T00:00:00Z',to:new Date(Date.parse(from)+30*86400000).toISOString()};
 const rows=useQuery<{id:number;start_at:string;end_at:string;kind:string;cancelled_at:string|null}[]>({queryKey:['/api/workforce/availability',range]}),op=useOperation();
 return <Card><CardHeader><CardTitle>My availability</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Times use {zone}. Unavailability blocks new offers and acceptance. For an accepted shift, arrange coverage with your scheduler first. Availability does not guarantee an assignment.</p><form className="grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();setError('');let body;try{body={startAt:siteTimeToIso(start,zone),endAt:siteTimeToIso(end,zone),kind};}catch(err){setError((err as Error).message);return;}try{await op.mutateAsync({url:'/api/workforce/availability',body});setStart('');setEnd('');}catch{}}}><Field label="Availability"><select className={selectClass} value={kind} onChange={e=>setKind(e.target.value)}><option value="available">Available</option><option value="unavailable">Unavailable</option></select></Field><div/><Field label="Start"><Input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="End"><Input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Button disabled={op.isPending}>Declare availability</Button>{error&&<p role="alert">{error}</p>}</form><Field label="30-day history starting (UTC)"><Input type="date" value={from} onChange={e=>{if(e.target.value)setFrom(e.target.value);}}/></Field>{rows.isLoading?<p>Loading availability…</p>:rows.error?<p role="alert">Unable to load availability.</p>:<>{!rows.data?.length&&<p>No declarations in this window.</p>}{rows.data?.map(a=><div key={a.id} className="flex flex-wrap justify-between gap-2 border-t py-3 text-sm"><span>{a.kind} · {stamp(a.start_at,zone)} → {stamp(a.end_at,zone)}{a.cancelled_at?' · Cancelled':''}</span>{!a.cancelled_at&&new Date(a.end_at)>new Date()&&<Button variant="outline" size="sm" disabled={op.isPending} onClick={()=>op.mutate({url:`/api/workforce/availability/${a.id}/cancel`,body:{}})}>Cancel declaration</Button>}</div>)}{rows.data?.length===200&&<p>Showing the first 200 declarations. Adjust the start date for later records.</p>}</>}</CardContent></Card>;
}
function wall(v:string,zone:string){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(v)).map(p=>[p.type,p.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
export function ShiftOperations({shift,zone}:{shift:ShiftView;zone:string}){
 const [open,setOpen]=useState(false),[page,setPage]=useState(1),[original,setOriginal]=useState(''),[person,setPerson]=useState(''),[reason,setReason]=useState(''),[revision,setRevision]=useState(false),[history,setHistory]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({role:shift.role,station:shift.station||'',headcount:String(shift.headcount),breakMinutes:String(shift.breakMinutes),startAt:wall(shift.startAt,zone),endAt:wall(shift.endAt,zone)});
 const op=useOperation(),active=!shift.cancelledAt&&new Date(shift.startAt)>new Date();
 const candidates=useQuery<{items:{id:number;name:string;eligible:boolean;reason:string|null;declaredAvailable:boolean}[]}>({queryKey:[`/api/workforce/shifts/${shift.id}/candidates`,{page}],enabled:open&&active});
 const snapshots=useQuery<{version:number;reason:string;created_at:string;snapshot:{replacementShiftId?:number}}[]>({queryKey:[`/api/workforce/shifts/${shift.id}/history`],enabled:history});
 return <div className="mt-4 space-y-3 border-t pt-4"><div className="flex flex-wrap gap-2">{active&&<><Button variant="outline" onClick={()=>setOpen(!open)}>Candidates & replacements</Button><Button variant="outline" onClick={()=>setRevision(true)}>Revise shift</Button></>}<Button variant="ghost" onClick={()=>setHistory(!history)}>Revision history</Button></div>
 {history&&(snapshots.isLoading?<p>Loading history…</p>:snapshots.error?<p role="alert">Unable to load history.</p>:<div className="text-sm">{!snapshots.data?.length&&<p>No revisions to this shift.{shift.supersedesId?` Replaces shift #${shift.supersedesId}.`:''}</p>}{snapshots.data?.map(h=><p key={h.version}>Version {h.version} · {h.reason} · {stamp(h.created_at,zone)}{h.snapshot.replacementShiftId?` · New shift #${h.snapshot.replacementShiftId}`:''}</p>)}</div>)}
 {open&&active&&<div className="space-y-3"><p className="text-sm text-muted-foreground">Eligibility includes membership, employment, skills, leave, availability and conflicting accepted work. It is checked again when an offer is accepted.</p>{candidates.isLoading?<p>Checking candidates…</p>:candidates.error?<p role="alert">Candidates are unavailable. Your scheduling access may have changed.</p>:<><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await op.mutateAsync({url:original?`/api/workforce/assignments/${original}/replace`:`/api/workforce/shifts/${shift.id}/offers`,body:original?{employeeId:Number(person),reason}:{employeeId:Number(person)}});setPerson('');setOriginal('');setReason('');}catch{}}}><Field label="New offer or replacement"><select className={selectClass} value={original} onChange={e=>setOriginal(e.target.value)}><option value="">Offer an open place</option>{shift.assignments.filter(a=>['offered','accepted','cancelled'].includes(a.status)).map(a=><option key={a.id} value={a.id}>Replace {a.name} · {a.status}</option>)}</select></Field><Field label="Eligible candidate on this page"><select className={selectClass} required value={person} onChange={e=>setPerson(e.target.value)}><option value="">Select employee…</option>{candidates.data?.items.filter(p=>p.eligible).map(p=><option key={p.id} value={p.id}>{p.name}{p.declaredAvailable?' · Declared available':''}</option>)}</select></Field>{original&&<><Field label="Replacement reason (visible to original employee)"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field><p className="text-sm">This cancels the original assignment immediately and offers the shift to the replacement. Coverage is confirmed only after acceptance.</p></>}<Button disabled={op.isPending||!person}>{original?'Cancel original & offer replacement':'Send offer'}</Button></form><div className="divide-y text-sm">{candidates.data?.items.map(p=><p key={p.id} className="py-2">{p.name} · {p.eligible?(p.declaredAvailable?'Eligible · Declared available':'Eligible · No full availability declaration'):p.reason}</p>)}{!candidates.data?.items.length&&<p>No members on this page.</p>}</div><Pager page={page} setPage={n=>{setPage(n);setPerson('');}} more={candidates.data?.items.length===25}/></>}</div>}
 <Dialog open={revision} onOpenChange={v=>{if(!op.isPending)setRevision(v);}}><DialogContent className="max-h-[90vh] overflow-auto"><DialogHeader><DialogTitle>Revise shift #{shift.id}</DialogTitle><DialogDescription>Times use {zone}. The old shift and responses remain in history. All active assignments are cancelled; send new offers afterwards. Required skills stay the same.</DialogDescription></DialogHeader><form className="space-y-3" onSubmit={async e=>{e.preventDefault();setError('');let body;try{body={version:shift.version,reason,shift:{...form,headcount:Number(form.headcount),breakMinutes:Number(form.breakMinutes),startAt:siteTimeToIso(form.startAt,zone),endAt:siteTimeToIso(form.endAt,zone),requiredSkills:shift.requiredSkills}};}catch(err){setError((err as Error).message);return;}try{await op.mutateAsync({url:`/api/workforce/shifts/${shift.id}/revise`,body});setRevision(false);}catch{}}}>{(['role','station','headcount','breakMinutes','startAt','endAt'] as const).map(k=><Field key={k} label={{role:'Role',station:'Station',headcount:'People needed',breakMinutes:'Break minutes',startAt:'Start',endAt:'End'}[k]}><Input required={k!=='station'} type={k.endsWith('At')?'datetime-local':['headcount','breakMinutes'].includes(k)?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}<Field label="Reason"><Input required minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></Field>{error&&<p role="alert">{error}</p>}<Button disabled={op.isPending}>Cancel old assignments & create revised shift</Button></form></DialogContent></Dialog></div>;
}
type CoverageRow={id:number;role:string;startAt:string;unfilled:number;warnings:{assignmentId:number;name:string;status:string;issue:string}[]};
export function Coverage({teamId,range,zone}:{teamId:string;range:{from:string;to:string};zone:string}){
 const [page,setPage]=useState(1);const q=useQuery<{items:CoverageRow[];hasMore:boolean}>({queryKey:[`/api/workforce/teams/${teamId}/coverage`,{...range,page}],refetchInterval:30000});
 return <Card><CardHeader><CardTitle>Coverage & absence alerts</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Future shifts in the selected roster window. Pending absences need a decision; they do not automatically cancel work.</p>{q.isLoading?<p>Loading coverage…</p>:q.error?<p role="alert">Coverage requires scheduling access for this team.</p>:<>{q.data?.items.filter(s=>s.unfilled||s.warnings.length).map(s=><div key={s.id} className="border-t pt-3 text-sm"><a className="font-medium text-primary" href={`#shift-${s.id}`}>{s.role} · {stamp(s.startAt,zone)} · {s.unfilled} unfilled</a>{s.warnings.map(w=><p key={w.assignmentId}>{w.name} · {w.issue} · {w.status}</p>)}</div>)}{!q.data?.items.some(s=>s.unfilled||s.warnings.length)&&<p>No coverage alerts on this page.</p>}<Pager page={page} setPage={setPage} more={!!q.data?.hasMore}/></>}</CardContent></Card>;
}
type Inbox={time:{id:number;employeeName:string;role:string;startAt:string}[];performance:{id:number;employeeName:string;role:string;startAt:string}[];leave:{id:number;employeeName:string;startDate:string;endDate:string}[];grants:{id:number;permission:string;endAt:string}[];hasMore:boolean};
export function ApprovalInbox({teamId,zone}:{teamId:string;zone:string}){
 const [from,setFrom]=useState(day(-30)),[to,setTo]=useState(day(30)),[page,setPage]=useState(1),[decision,setDecision]=useState<{id:number;name:string;status:string}|null>(null),op=useOperation();
 const valid=!!from&&!!to&&to>=from&&Date.parse(to)-Date.parse(from)<90*86400000;
 const q=useQuery<Inbox>({queryKey:[`/api/workforce/teams/${teamId}/approvals`,{from:from+'T00:00:00Z',to:to?new Date(Date.parse(to)+86400000).toISOString():'',page}],enabled:valid,refetchInterval:30000});
 return <Card><CardHeader><CardTitle>Team approval inbox</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">Only actionable records in this team and your current permission scope. Timesheet and performance grants are separate; leave uses your HR approval permissions. Up to 25 records per lane per page.</p><div className="flex flex-wrap gap-3"><Field label="From (UTC)"><Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></Field><Field label="Through (UTC)"><Input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></Field></div>{!valid?<p role="alert">Choose up to 90 days.</p>:q.isLoading?<p>Loading approvals…</p>:q.error?<p role="alert">Unable to load team approvals. Refresh your access.</p>:q.data&&<><div className="grid gap-5 lg:grid-cols-3"><section><h3 className="font-medium">Timesheets ({q.data.time.length})</h3>{q.data.time.map(t=><Link key={t.id} className="block border-t py-3 text-sm text-primary" href={`/timesheets/${t.id}`}>{t.employeeName} · {t.role} · {stamp(t.startAt,zone)}</Link>)}{!q.data.time.length&&<p className="text-sm">No actionable timesheets on this page.</p>}</section><section><h3 className="font-medium">Leave ({q.data.leave.length})</h3>{q.data.leave.map(l=><div key={l.id} className="space-y-2 border-t py-3 text-sm"><p>{l.employeeName} · {l.startDate} → {l.endDate}</p><div className="flex gap-2"><Button size="sm" disabled={op.isPending} onClick={()=>setDecision({id:l.id,name:l.employeeName,status:'approved'})}>Approve</Button><Button variant="outline" size="sm" disabled={op.isPending} onClick={()=>setDecision({id:l.id,name:l.employeeName,status:'rejected'})}>Reject</Button></div></div>)}{!q.data.leave.length&&<p className="text-sm">No actionable leave on this page.</p>}</section><section><h3 className="font-medium">Performance ({q.data.performance.length})</h3>{q.data.performance.map(t=><Link key={t.id} className="block border-t py-3 text-sm text-primary" href={`/assignment-reviews?assignmentId=${t.id}`}>{t.employeeName} · {t.role} · {stamp(t.startAt,zone)}</Link>)}{!q.data.performance.length&&<p className="text-sm">No actionable performance reviews on this page.</p>}</section></div>{q.data.grants.length>0&&<div className="text-xs text-muted-foreground">Your dated team access:{q.data.grants.map(g=><p key={g.id}>{g.permission.replaceAll('_',' ')} · Expires {stamp(g.endAt,zone)}</p>)}</div>}<Pager page={page} setPage={setPage} more={q.data.hasMore}/></>}
 <Dialog open={!!decision} onOpenChange={v=>{if(!v&&!op.isPending)setDecision(null);}}><DialogContent><DialogHeader><DialogTitle>{decision?.status==='approved'?'Approve':'Reject'} leave</DialogTitle><DialogDescription>Confirm the leave decision for {decision?.name}. Approval checks the employee's balance and accepted shift conflicts again.</DialogDescription></DialogHeader><Button disabled={op.isPending} onClick={async()=>{if(!decision)return;try{await op.mutateAsync({url:`/api/leaves/${decision.id}/status`,method:'PATCH',body:{status:decision.status}});setDecision(null);}catch{}}}>Confirm decision</Button></DialogContent></Dialog></CardContent></Card>;
}
