// Fixed interface text only. Employee names, notes and supplied values stay intact.
export const employeeArabic:Record<string,string>={
 'permanent':'دائم','event':'فعاليات','active':'نشط','inactive':'غير نشط','male':'ذكر','female':'أنثى','single':'أعزب','married':'متزوج','divorced':'مطلق','widowed':'أرمل',
 'Notes':'ملاحظات','Saving…':'جارٍ الحفظ…',
 'Employment':'العمل','Personal & emergency':'البيانات الشخصية والطوارئ','Banking':'البيانات المصرفية','Lifecycle':'دورة الخدمة','Activity':'النشاط',
 'Employment details':'بيانات العمل','Employee ID':'الرقم الوظيفي','Type':'النوع','Event staff eligible':'مؤهل للعمل في الفعاليات','Work schedule':'جدول العمل','Management office':'المكتب الإداري','Assigned shifts':'الورديات المعيّنة','Not assigned':'غير معيّن',
 'Department':'القسم','Position':'المسمى الوظيفي','Location':'الموقع','Work location':'موقع العمل','Joining date':'تاريخ الالتحاق','Work email':'البريد الإلكتروني للعمل','Work phone':'هاتف العمل','Primary manager':'المدير المباشر','Secondary manager':'المدير الثاني','Manager details outside your directory access':'بيانات المدير خارج نطاق صلاحيتك في دليل الموظفين',
 'Contract end':'نهاية العقد','Category':'الفئة','Cost center':'مركز التكلفة','Job grade':'الدرجة الوظيفية','Probation (months)':'فترة التجربة (بالأشهر)','Notice (days)':'مدة الإخطار (بالأيام)',
 'Personal details':'البيانات الشخصية','Arabic name':'الاسم بالعربية','Date of birth':'تاريخ الميلاد','Gender':'الجنس','Nationality':'الجنسية','QID / identification':'البطاقة الشخصية / إثبات الهوية','Marital status':'الحالة الاجتماعية','Religion':'الديانة','Blood group':'فصيلة الدم','Mobile':'الهاتف المحمول','Secondary contact':'وسيلة اتصال إضافية','Personal email':'البريد الإلكتروني الشخصي','Residential address':'عنوان السكن','Home country address':'العنوان في البلد الأم',
 'Emergency contact':'جهة الاتصال في حالات الطوارئ','Name':'الاسم','Number':'الرقم','Relationship':'صلة القرابة','Bank details':'البيانات المصرفية','Bank':'البنك','Account name':'اسم الحساب','IBAN':'رقم الحساب المصرفي الدولي','SWIFT code':'رمز سويفت','Branch':'الفرع',
 'Not recorded':'غير مسجل','Yes':'نعم','No':'لا','Loading employee…':'جارٍ تحميل بيانات الموظف…','Employee unavailable, or you no longer have access.':'الموظف غير متاح أو لم تعد لديك صلاحية الوصول.','Back to employees':'العودة إلى الموظفين','← Back to employees':'العودة إلى الموظفين','Retry':'إعادة المحاولة','Reload profile':'إعادة تحميل الملف','Edit Employee':'تعديل بيانات الموظف','Office schedule:':'جدول المكتب:',
 'FEC, mall activation and event team assignments are managed in Workforce Operations.':'تُدار مهام فرق مراكز الترفيه العائلي وفعاليات المراكز التجارية والفعاليات ضمن عمليات القوى العاملة.',
 'Employee documents':'مستندات الموظف','Add Document':'إضافة مستند','Loading documents…':'جارٍ تحميل المستندات…','Unable to load documents.':'تعذر تحميل المستندات.','No documents recorded for this employee.':'لا توجد مستندات مسجلة لهذا الموظف.','Document':'المستند','Expires':'تاريخ الانتهاء','File':'الملف','Open document':'فتح المستند','No file attached':'لا يوجد ملف مرفق',
 'Events preserve an employment history. Update department, position and contract details using Edit Employee. Termination deactivates the employee and linked account immediately. Reactivation restores employment; an administrator must restore account access in User Management.':'تحفظ الأحداث السجل الوظيفي. حدّث القسم والمسمى الوظيفي وبيانات العقد عبر تعديل بيانات الموظف. يؤدي إنهاء الخدمة إلى تعطيل الموظف والحساب المرتبط فورًا. تعيد إعادة التفعيل حالة العمل؛ ويجب أن يعيد المسؤول صلاحية الحساب من إدارة المستخدمين.',
 'Record lifecycle event':'تسجيل حدث وظيفي','Event type':'نوع الحدث','Lifecycle event recorded':'تم تسجيل الحدث الوظيفي','Unable to record lifecycle event':'تعذر تسجيل الحدث الوظيفي','Record event':'تسجيل الحدث','Lifecycle history':'سجل الأحداث الوظيفية','Loading lifecycle history…':'جارٍ تحميل السجل الوظيفي…','Unable to load lifecycle history.':'تعذر تحميل السجل الوظيفي.','No lifecycle events recorded yet.':'لم تُسجل أحداث وظيفية بعد.','Recorded by':'سجّله','System':'النظام','Record history':'سجل التغييرات','Loading history…':'جارٍ تحميل السجل…','Unable to load history.':'تعذر تحميل السجل.','No recorded changes yet.':'لم تُسجل تغييرات بعد.','Page':'الصفحة',
 'hire':'التعيين','transfer':'النقل','promotion':'الترقية','probation started':'بدء فترة التجربة','probation completed':'إكمال فترة التجربة','contract renewal':'تجديد العقد','termination':'إنهاء الخدمة','reactivation':'إعادة التفعيل','correction':'التصحيح',
 'Pending employee corrections':'تصحيحات الموظفين المعلّقة','Unable to load HR correction queue.':'تعذر تحميل قائمة التصحيحات لدى الموارد البشرية.','Review profile':'مراجعة الملف','No pending requests.':'لا توجد طلبات معلّقة.','Correction saved':'تم حفظ التصحيح','Unable to save correction':'تعذر حفظ التصحيح','Correction requests are available to the employee and authorized HR reviewers.':'تتوفر طلبات التصحيح للموظف ولمراجعي الموارد البشرية المخوّلين.','Loading correction requests…':'جارٍ تحميل طلبات التصحيح…','Employee correction requests':'طلبات تصحيح بيانات الموظف',
 'Contact, address and emergency details require HR approval before the employee record changes.':'تتطلب بيانات الاتصال والعنوان والطوارئ موافقة الموارد البشرية قبل تغيير سجل الموظف.','Field to correct':'الحقل المطلوب تصحيحه','Proposed value':'القيمة المقترحة','Request reason':'سبب الطلب','Request correction':'طلب تصحيح','Request:':'الطلب:','Decision:':'القرار:','Not set':'غير محدد','Decision or withdrawal reason':'سبب القرار أو السحب','Approve correction':'الموافقة على التصحيح','Reject correction':'رفض التصحيح','Withdraw request':'سحب الطلب','Mobile number':'رقم الهاتف المحمول','Emergency contact name':'اسم جهة الاتصال للطوارئ','Emergency contact number':'رقم الاتصال للطوارئ','pending':'قيد المراجعة','approved':'موافق عليه','rejected':'مرفوض','withdrawn':'مسحوب',
};
