import {compensationArabic} from './compensation-localization';
export type Language='en'|'ar';
export const arabic:Record<string,string>={
 ...compensationArabic,
 'Enter your credentials to access your account':'أدخل بيانات تسجيل الدخول للوصول إلى حسابك','Enter your username or email':'أدخل اسم المستخدم أو البريد الإلكتروني','Enter your password':'أدخل كلمة المرور','Hide password':'إخفاء كلمة المرور','Show password':'إظهار كلمة المرور','Enter a code if you enabled multifactor authentication.':'أدخل الرمز إذا فعّلت المصادقة متعددة العوامل.','Signing in...':'جارٍ تسجيل الدخول…','Accounts are created by your administrator. Contact HR for access.':'ينشئ المسؤول الحسابات. تواصل مع الموارد البشرية للحصول على صلاحية الدخول.','Forgot password?':'هل نسيت كلمة المرور؟','All rights reserved.':'جميع الحقوق محفوظة.','Username or email is required':'اسم المستخدم أو البريد الإلكتروني مطلوب','Password must be at least 6 characters':'يجب أن تتكون كلمة المرور من ستة أحرف على الأقل','Modules':'الأقسام','Browse modules':'استعراض الأقسام','What would you like to do?':'ماذا تريد أن تفعل؟','Choose a workspace available to your account.':'اختر مساحة عمل متاحة لحسابك.','Search workspaces':'البحث في مساحات العمل','Search people, leave, payroll…':'ابحث عن الموظفين أو الإجازات أو الرواتب…','No available workspaces match your search.':'لا توجد مساحات عمل متاحة تطابق بحثك.',
 'Workspace':'مساحة العمل','People':'الموظفون','Work & time':'العمل والوقت','Pay & benefits':'الأجور والمزايا','HR services':'خدمات الموارد البشرية','Development':'التطوير','Insights':'التحليلات','Administration':'الإدارة',
 'Dashboard':'لوحة المعلومات','My account':'حسابي','My Account':'حسابي','Communication Hub':'مركز التواصل','HR Helpdesk':'مكتب دعم الموارد البشرية','Privacy requests':'طلبات الخصوصية','Employee Database':'قاعدة بيانات الموظفين','Organization charts':'الهيكل التنظيمي','Recruitment':'التوظيف','Onboarding & offboarding':'إجراءات الانضمام والمغادرة','End of Service':'نهاية الخدمة','Employment history':'السجل الوظيفي','Team overview':'نظرة عامة على الفريق','Workforce':'القوى العاملة','Event Staff':'موظفو الفعاليات','Attendance':'الحضور','Timesheets':'سجلات ساعات العمل','Leave':'الإجازات','Payroll':'الرواتب','Benefits & entitlements':'المزايا والاستحقاقات','Expenses':'المصروفات','Documents':'المستندات','HR Letter Centre':'مركز خطابات الموارد البشرية','Contracts':'العقود','Equipment & returns':'العهد والإرجاع','Employee handbook':'دليل الموظف','Learning & training':'التعلم والتدريب','Performance':'الأداء','Assignment reviews':'تقييم المهام','Reports & analytics':'التقارير والتحليلات','Record retention':'الاحتفاظ بالسجلات','Record Retention':'الاحتفاظ بالسجلات','Bulk Import':'الاستيراد الجماعي','HR Rules & Settings':'قواعد وإعدادات الموارد البشرية',
 'Home':'الرئيسية','Team':'الفريق','Time':'الوقت','Help':'المساعدة','Explore':'استكشاف','Close':'إغلاق','Find a module':'البحث عن قسم','Find anything…':'ابحث هنا…','Quick navigation':'التنقل السريع','Main navigation':'القائمة الرئيسية','Workspace navigation':'التنقل في مساحة العمل','Open navigation':'فتح القائمة','Close navigation':'إغلاق القائمة','Close navigation backdrop':'إغلاق خلفية القائمة','Close menu':'إغلاق القائمة','Log out':'تسجيل الخروج','Skip to content':'الانتقال إلى المحتوى','No accessible modules match your search.':'لا توجد أقسام متاحة تطابق بحثك.','Open account menu':'فتح قائمة الحساب',
 'Username or email':'اسم المستخدم أو البريد الإلكتروني','Password':'كلمة المرور','Sign In':'تسجيل الدخول','Authenticator or recovery code':'رمز المصادقة أو الاسترداد','Current password':'كلمة المرور الحالية','Six-digit authenticator code':'رمز المصادقة المكوّن من ستة أرقام','Current authenticator or unused recovery code':'رمز المصادقة الحالي أو رمز استرداد غير مستخدم','Multifactor authentication':'المصادقة متعددة العوامل',
 'Previous':'السابق','Next':'التالي','Actions':'الإجراءات','Employee':'الموظف','Request type':'نوع الطلب','Requested information and outcome':'المعلومات والنتيجة المطلوبة','Response and evidence reference':'الرد ومرجع الإثبات','Submit a request':'تقديم طلب','Request history':'سجل الطلبات','Payroll and leave reconciliation':'مطابقة الرواتب والإجازات','Calculation':'الحساب','Notice':'الإخطار','Policy review history':'سجل مراجعة السياسة','Propose rules for independent review':'اقتراح قواعد للمراجعة المستقلة','Effective date':'تاريخ السريان','Reason for change':'سبب التغيير','Gratuity days per service year':'أيام المكافأة عن كل سنة خدمة','Minimum qualifying years':'الحد الأدنى لسنوات الاستحقاق','Monthly wage divisor':'مقسوم الأجر الشهري','Service-year method':'طريقة حساب سنوات الخدمة','Service threshold (months)':'مدة الخدمة الفاصلة بالأشهر','Notice before threshold (months)':'مدة الإخطار قبل المدة الفاصلة بالأشهر','Notice after threshold (months)':'مدة الإخطار بعد المدة الفاصلة بالأشهر',
 'Payroll ID':'رقم سجل الراتب','Period':'الفترة','Status':'الحالة','Net':'الصافي','Payment reference':'مرجع الدفع','Leave type':'نوع الإجازة','Year':'السنة','Posted days':'الأيام المسجلة','Reserved days':'الأيام المحجوزة','Available days':'الأيام المتاحة','Reviewed available days':'الأيام المتاحة عند المراجعة',
};
export const translate=(language:Language,text:string)=>language==='ar'?(arabic[text]||text):text;
export const languageLocale=(language:Language)=>language==='ar'?'ar-QA':'en-QA';
