import type {ContractDocument,ContractSignature} from '@shared/contracts';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function printableContract(row:{reference:string;status:string;document:ContractDocument;signature:ContractSignature|null;content_hash:string|null}){
  const d=row.document,s=row.signature,bilingual=d.languageMode==='en-ar',a=d.arabic;
  const block=(title:string,body:string,titleAr='',bodyAr='')=>`<section class="pair"><div lang="en" dir="ltr"><h2>${escape(title)}</h2><p>${escape(body)}</p></div>${bilingual?`<div lang="ar" dir="rtl"><h2>${escape(titleAr)}</h2><p>${escape(bodyAr||'لم يُستكمل بعد')}</p></div>`:''}</section>`;
  const drawing=s?.strokes.length?`<svg viewBox="0 0 600 180" role="img" aria-label="Employee signature">${s.strokes.map(line=>`<polyline fill="none" stroke="#17142b" stroke-width="2.5" stroke-linecap="round" points="${line.map(([x,y])=>`${(x*600).toFixed(2)},${(y*180).toFixed(2)}`).join(' ')}"/>`).join('')}</svg>`:'';
  const statusAr:Record<string,string>={draft:'مسودة',sent:'بانتظار التوقيع',signed:'موقّع',declined:'مرفوض',withdrawn:'مسحوب'};
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escape(row.reference)}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#efedf6;font:14px/1.8 Arial,Tahoma,sans-serif;color:#201e30}main{max-width:1060px;margin:25px auto;padding:36px;background:white;border:1px solid #ded9ec;border-radius:18px}header{border-bottom:3px solid #7750c7;padding-bottom:20px}h1{font-size:24px;line-height:1.5}h2{font-size:15px;margin:0 0 8px}p{white-space:pre-wrap;overflow-wrap:anywhere;orphans:3;widows:3}.pair{display:grid;grid-template-columns:${bilingual?'minmax(0,1fr) minmax(0,1fr)':'minmax(0,1fr)'};gap:28px;padding:20px 0;border-bottom:1px solid #eee}.pair>div{min-width:0}.pair [dir=rtl]{text-align:right}.meta,footer{font-size:11px;color:#625b76}.status{display:inline-block;border-radius:8px;padding:5px 12px;background:#eee7ff;font-weight:bold;text-transform:uppercase}svg{width:100%;max-width:480px;height:auto}.signature{margin-top:30px}.signature>strong{display:block}footer{border-top:1px solid #ddd;margin-top:24px;padding-top:15px;overflow-wrap:anywhere}.toolbar{text-align:center;padding:12px;background:#262039;color:white}@media(max-width:650px){main{padding:20px;margin:10px}.pair{grid-template-columns:1fr;gap:16px}.pair [dir=rtl]{border-top:1px dashed #ddd;padding-top:16px}}@media print{body{background:white}main{border:0;border-radius:0;padding:0;margin:0;max-width:none}.toolbar{display:none}.pair{grid-template-columns:${bilingual?'minmax(0,1fr) minmax(0,1fr)':'minmax(0,1fr)'};gap:22px}.pair [dir=rtl]{border:0;padding-top:0}h2{break-after:avoid}.signature{break-inside:avoid}@page{size:A4;margin:15mm}}
  </style></head><body><div class="toolbar">Print / Save as PDF${bilingual?' · <span lang="ar" dir="rtl">طباعة / حفظ بصيغة PDF</span>':''}</div><main><header><div class="status">${escape(row.status)}${bilingual?' · '+escape(statusAr[row.status]):''}</div><div class="pair"><div lang="en"><h1>${escape(d.title)}</h1><strong>${escape(d.companyName)}</strong><p class="meta">${escape(d.companyAddress)}</p></div>${bilingual?`<div lang="ar" dir="rtl"><h1>${escape(a?.title)}</h1><strong>${escape(d.companyNameAr)}</strong><p class="meta">${escape(d.companyAddressAr)}</p></div>`:''}</div><p class="meta">${escape(row.reference)} · ${escape(d.employeeReference)}</p></header>
  ${block('Employee',d.employeeName,'الموظف',d.employeeNameAr)}
  ${block('Appointment',`${d.position}\n${d.department}\n${d.location}\nStart: ${d.startDate}${d.endDate?'\nEnd: '+d.endDate:'\nNo end date specified'}`,'بيانات التعيين',`${a?.position||''}\n${a?.department||''}\n${a?.location||''}\nتاريخ البدء: \u2066${d.startDate}\u2069${d.endDate?'\nتاريخ الانتهاء: \u2066'+d.endDate+'\u2069':'\nلم يُحدَّد تاريخ انتهاء'}`)}
  ${block('Working arrangements',d.schedule,'ترتيبات العمل',a?.schedule)}${block('Compensation and allowances',d.compensation,'الأجر والبدلات',a?.compensation)}
  ${d.clauses.map((c,i)=>block(`${i+1}. ${c.title}`,c.body,`${i+1}. ${c.titleAr||''}`,c.bodyAr)).join('')}
  <div class="signature">${block('Employee agreement',s?s.statement:'Employee signature has not been recorded.','موافقة الموظف',s?s.statementAr||'لم يُسجَّل نص موافقة بالعربية لهذه النسخة.':'لم يُسجَّل توقيع الموظف بعد.')}${s?`${drawing}<strong dir="auto">${escape(s.name)}</strong><p class="meta">Employee account / حساب الموظف #${s.userId} · ${escape(s.recordedAt)}</p>`:''}</div>
  <footer>Contract content SHA-256: ${escape(row.content_hash||'Draft — not sent for signature')}<p>Signature evidence is recorded in E3 HR. This copy does not include a certificate-based digital signature.</p>${bilingual?'<p lang="ar" dir="rtl">تُحفظ أدلة التوقيع في نظام E3 HR. لا تتضمن هذه النسخة توقيعاً رقمياً قائماً على شهادة رقمية.</p>':''}</footer></main></body></html>`;
}
