import {csvCell,moneyCents,moneyText} from '@shared/money';
import {totalMoney,type ExportFilter,type PayrollExportRow,type WpsSettings} from '@shared/payroll-exports';
import type {CompanySettings} from '@shared/settings';

const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const stamp=(date:Date)=>{
  const parts=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(p=>[p.type,p.value]));
  return {date:parts.year+parts.month+parts.day,time:parts.hour+parts.minute};
};
export function sifFile(settings:WpsSettings,rows:PayrollExportRow[],filter:ExportFilter,created=new Date()){
  const at=stamp(created),salaryMonth=`${filter.year}${String(filter.month).padStart(2,'0')}`;
  const cell=(value:unknown)=>'"'+String(value??'').replaceAll('"','""')+'"';
  const lines:unknown[][]=[
    ['Employer EID','File Creation Date','File Creation Time','Payer EID','Payer QID','Payer Bank Short Name','Payer IBAN','Salary Year and Month','Total Salaries','Total Records','SIF Version'],
    [settings.employerEid,at.date,at.time,settings.payerEid,settings.payerQid,settings.payerBank,settings.payerIban,salaryMonth,totalMoney(rows),rows.length,'1'],
    ['Record Sequence','Employee QID','Employee Visa ID','Employee Name','Employee Bank Short Name','Employee Account','Salary Frequency','Number of Working days','Net Salary','Basic Salary','Extra hours','Extra income','Deductions','Payment Type','Notes / Comments','Housing Allowance','Food Allowance','Transportation Allowance','Over Time Allowance','Deduction Reason Code','Extra Field 1','Extra Field 2'],
    ...rows.map((row,index)=>{const wps=row.wps!,person=wps.employee,pay=wps.record;return [String(index+1).padStart(6,'0'),person.qid,person.visaId,person.name,person.bank,person.account,'M',pay.workingDays??'',row.net,pay.basic,pay.extraHours,pay.extraIncome,pay.deductions,pay.paymentType,pay.notes,wps.breakdown.housing,wps.breakdown.food,wps.breakdown.transport,wps.breakdown.overtime,pay.deductionReason,'',''];}),
  ];
  return {filename:`SIF_${settings.employerEid}_${settings.payerBank}_${at.date}_${at.time}.csv`,content:lines.map(line=>line.map(cell).join(',')).join('\r\n')+'\r\n'};
}
export function payrollCsv(rows:PayrollExportRow[]){
  const columns=['Payroll ID','Employee ID','Employee','Department','Team(s)','Currency','Period start','Period end','Pay date','Basic','Allowance total','Deduction total','Rounding adjustment','Net','Status','Payment reference'];
  const sum=(items:Record<string,string>)=>moneyText(Object.values(items).reduce((total,value)=>total+moneyCents(value),0));
  const signed=(cents:number)=>(cents<0?'-':'')+moneyText(Math.abs(cents));
  return [columns,...rows.map(r=>[r.id,r.employeeRef,r.name,r.department,r.groups.map(g=>g.name).join('; ')|| (r.headOffice?'Head Office':'Unassigned'),r.currency||'Unspecified',r.periodStart,r.periodEnd,r.payDate,r.basic,sum(r.allowances),sum(r.deductions),signed(r.roundingCents),r.net,r.status,r.paymentReference])].map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n';
}
export function payslipDocument(company:CompanySettings,rows:PayrollExportRow[],filter:ExportFilter){
  const period=`${filter.year}-${String(filter.month).padStart(2,'0')}`;
  const amount=(value:string,currency:string|null)=>`${escape(currency||'Currency unspecified')} ${escape(Number(value).toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}))}`;
  const table=(title:string,items:[string,string][],currency:string|null)=>`<section class="items"><h2>${escape(title)}</h2><table><thead><tr><th>Pay item</th><th>Amount</th></tr></thead><tbody>${items.map(([label,value])=>`<tr><td>${escape(label)}</td><td>${amount(value,currency)}</td></tr>`).join('')}</tbody></table></section>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Payslips ${escape(period)}</title><style>
    *{box-sizing:border-box}body{margin:0;background:#f1f3f8;color:#202339;font:14px/1.5 Arial,sans-serif}header.toolbar{padding:20px;text-align:center;background:#22243a;color:white}.toolbar p{margin:5px 0;font-size:13px}.slip{max-width:850px;margin:24px auto;padding:42px;background:white;border:1px solid #dfe2ed;border-radius:16px}.top{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid #6d4fc5;padding-bottom:22px}.company{font-size:21px;font-weight:700}.subtle{color:#667085;font-size:12px}.badge{display:inline-block;padding:5px 10px;border-radius:7px;background:#f0ebfc;color:#503b91;font-size:12px;font-weight:bold}.employee{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px;padding:24px 0}.employee h1{font-size:23px;margin:0}.employee p{margin:3px 0}.items{margin:18px 0}.items h2{font-size:14px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{text-align:left;padding:9px 10px;border-bottom:1px solid #e9eaf2;overflow-wrap:anywhere}th{background:#f5f4fa;font-size:12px}td:last-child,th:last-child{text-align:right;width:38%}.net{display:flex;justify-content:space-between;gap:20px;margin-top:24px;padding:20px;background:#eff8f3;color:#164b36;border-radius:10px;font-size:20px;font-weight:bold}.foot{margin-top:24px;border-top:1px solid #ddd;padding-top:12px;font-size:11px;color:#667085}.draft{padding:10px;background:#fff4d6;color:#755014;font-weight:bold}.meta{overflow-wrap:anywhere}@media(max-width:600px){.slip{margin:10px;padding:22px}.top,.employee{display:block}.employee>div{margin:12px 0}.net{font-size:17px}}@page{size:A4;margin:14mm}@media print{body{background:white;font-size:11px}.toolbar{display:none}.slip{margin:0;max-width:none;padding:0;border:0;border-radius:0;break-after:page}.slip:last-child{break-after:auto}.top{break-inside:avoid}.employee,.net,.foot,tr{break-inside:avoid}thead{display:table-header-group}th{background:#eee!important}.net{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
    </style></head><body><header class="toolbar"><strong>${rows.length} payslip${rows.length===1?'':'s'} · ${escape(period)}</strong><p>Use your browser's Print command (Ctrl+P / Cmd+P), then choose Save as PDF or your printer.</p><p>Each employee starts on a separate page. Confidential payroll information.</p></header>${rows.map(row=>{
      const paid=['processed','paid'].includes(row.status),approved=row.status==='approved',status=paid?'Payment recorded':approved?'Approved for payment':'Draft / not for payment';
      const earningItems:[string,string][]=[['Basic salary',row.basic],...Object.entries(row.allowances)];
      const deductionItems=Object.entries(row.deductions);
      if(row.roundingCents>0)earningItems.push(['Rounding adjustment',moneyText(row.roundingCents)]);
      if(row.roundingCents<0)deductionItems.push(['Rounding adjustment',moneyText(-row.roundingCents)]);
      return `<article class="slip"><div class="top"><div><div class="company">${escape(company.companyName)}</div><div class="subtle">${escape(company.companyAddress)}</div><div class="subtle">${escape(company.companyEmail)} ${escape(company.companyPhone)}</div></div><div><strong>PAYSLIP</strong><p class="subtle">${escape(period)} · #${row.id}</p><span class="badge">${escape(status)}</span></div></div>${!paid&&!approved?'<p class="draft">DRAFT — NOT FOR PAYMENT</p>':''}<div class="employee"><div><h1>${escape(row.name)}</h1><p>${escape(row.employeeRef)} · ${escape(row.position)}</p><p class="subtle">${escape(row.department)}</p></div><div class="meta"><p><strong>Salary period:</strong> ${escape(row.periodStart||'Not recorded')} – ${escape(row.periodEnd||'Not recorded')}</p><p><strong>Pay date:</strong> ${escape(row.payDate||'Not recorded')}</p><p><strong>Team:</strong> ${escape(row.groups.map(g=>g.name).join(' · ')||(row.headOffice?'Head Office':'Unassigned'))}</p></div></div>${table('Earnings',earningItems,row.currency)}${table('Deductions',deductionItems.length?deductionItems:[['No deductions','0.00']],row.currency)}<div class="net"><span>Net pay</span><span>${amount(row.net,row.currency)}</span></div><div class="foot"><p><strong>Payment reference:</strong> ${escape(row.paymentReference||(paid?'Not recorded':'Not paid / not recorded'))}</p><p>Amounts reproduce saved payroll #${row.id}. ${paid?'External payment has been recorded.':'This payslip is not proof of a completed bank transfer.'}</p></div></article>`;
    }).join('')}</body></html>`;
}
