import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Monitor, Smartphone, RefreshCw, LogOut } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { useAuth } from '@/contexts/AuthContext';
import { apiJson } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';

type Session = { id: number; ipAddress: string | null; userAgent: string | null; issuedAt: string; lastUsed: string; expiresAt: string; isCurrent: boolean };
const date = (value: string) => new Date(value).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
function device(agent: string | null) { const ua = agent || ''; const browser = /Edg\//.test(ua) ? 'Edge' : /Firefox\//.test(ua) ? 'Firefox' : /Chrome\//.test(ua) ? 'Chrome' : /Safari\//.test(ua) ? 'Safari' : 'Browser'; const os = /Android/.test(ua) ? 'Android' : /iPhone|iPad/.test(ua) ? 'iOS' : /Windows/.test(ua) ? 'Windows' : /Macintosh/.test(ua) ? 'macOS' : /Linux/.test(ua) ? 'Linux' : 'Unknown device'; return `${browser} · ${os}`; }
export default function AccountSessions() {
  const { user, refreshToken } = useAuth(), { toast } = useToast();
  const [target, setTarget] = useState<Session | null>(null);
  const query = useQuery<{ sessions: Session[] }>({ queryKey: [`/api/auth/sessions/${user?.userId}`], enabled: !!user, refetchInterval: 60000, refetchIntervalInBackground: false });
  const revoke = useMutation({ mutationFn: (id: number) => apiJson(`/api/auth/revoke-session/${id}`, { method: 'POST', body: {} }), onSuccess: async () => { setTarget(null); toast({ title: 'Session ended' }); await refreshToken(); void query.refetch(); } });
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="max-w-lg text-sm text-muted-foreground">Review browsers currently signed in to your account. End a session you no longer use.</p><Button variant="outline" size="sm" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>{query.error ? <p role="alert" className="rounded-xl border p-4 text-sm">Sessions could not be loaded. Refresh to try again.</p> : query.isLoading ? <p role="status" className="text-sm text-muted-foreground">Loading sessions…</p> : <div className="space-y-3">{query.data?.sessions.map(session => { const Mobile = /Android|iPhone|iPad/.test(session.userAgent || '') ? Smartphone : Monitor; return <div key={session.id} className="flex flex-wrap items-start gap-3 rounded-xl border p-4"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Mobile className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-semibold">{device(session.userAgent)}</h3>{session.isCurrent && <span className="rounded-full bg-primary/10 px-2 py-1 text-[10px] font-semibold text-primary">This browser</span>}</div><dl className="mt-2 space-y-1 text-xs text-muted-foreground"><div><dt className="inline">Last active: </dt><dd className="inline">{date(session.lastUsed)}</dd></div><div><dt className="inline">Session expires: </dt><dd className="inline">{date(session.expiresAt)}</dd></div><div><dt className="inline">IP address: </dt><dd className="inline break-all">{session.ipAddress || 'Not recorded'}</dd></div></dl></div>{!session.isCurrent && <Button size="sm" variant="outline" disabled={revoke.isPending} onClick={() => { revoke.reset(); setTarget(session); }}><LogOut className="mr-2 h-3.5 w-3.5"/>End session</Button>}</div>; })}{!query.data?.sessions.length && <p className="rounded-xl bg-muted/40 p-4 text-sm text-muted-foreground">No active sessions returned. Refresh to update this list.</p>}</div>}<Dialog open={!!target} onOpenChange={open => { if (!open && !revoke.isPending) setTarget(null); }}><DialogContent><DialogHeader><DialogTitle>End this session?</DialogTitle><DialogDescription>{target ? device(target.userAgent) : 'This browser'} will need to sign in again. Unsaved work in that session may be lost.</DialogDescription></DialogHeader>{revoke.error && <p role="alert" className="text-sm text-destructive">{revoke.error.message}</p>}<DialogFooter><Button variant="outline" disabled={revoke.isPending} onClick={() => setTarget(null)}>Keep session</Button><Button disabled={revoke.isPending || !target} onClick={() => target && revoke.mutate(target.id)}>{revoke.isPending ? 'Ending…' : 'End session'}</Button></DialogFooter></DialogContent></Dialog></div>;
}
