import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {defaultAnalyticsPolicy} from '@shared/reporting';
import {Button} from '@/components/ui/button';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {Pages,reportsApi} from './ReportLibrary';
export default function ReportPolicy(){
 const cache=useQueryClient(),[draft,setDraft]=useState<any>(null),[reason,setReason]=useState(''),[page,setPage]=useState(1);
 const policy=useQuery<any>({queryKey:[reportsApi+'/policy']}),history=useQuery<{items:any[];hasMore:boolean}>({queryKey:[reportsApi+'/policy/history',{page}]});
 const value=draft||policy.data,config=value?.config||defaultAnalyticsPolicy;
 const change=(key:string,v:unknown)=>setDraft({...value,config:{...config,[key]:v}});
 const save=useMutation({mutationFn:()=>apiJson(reportsApi+'/policy','POST',{version:value.version,turnoverDenominator:value.turnover_denominator,config,reason}),onSuccess:()=>{setDraft(null);setReason('');cache.invalidateQueries({queryKey:[reportsApi+'/policy']});cache.invalidateQueries({queryKey:[reportsApi+'/policy/history']});cache.invalidateQueries({queryKey:[reportsApi+'/catalog']});}});
 return <Section title="Reporting rules · Admin / Super Admin"><p className="text-sm text-muted-foreground">Changes apply to future reports. Every snapshot preserves its calculation policy and source definition. Saved attendance, leave and payroll calculations are reported as recorded; edit those source rules in HR Rules & Settings.</p><QueryError error={policy.error||save.error}/>{policy.isPending&&<p>Loading policy…</p>}{value&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><p className="text-sm">Editing policy version {value.version}</p><div className="grid gap-4 md:grid-cols-2"><Field label="Turnover denominator"><select className={fieldClass} value={value.turnover_denominator} onChange={e=>setDraft({...value,turnover_denominator:e.target.value})}><option value="average_endpoints">Average opening / closing headcount</option><option value="opening">Opening headcount</option></select></Field><Field label="Maximum saved rows (100–5,000)"><input className={fieldClass} type="number" required min={100} max={5000} step={1} value={config.maxRows} onChange={e=>change('maxRows',Number(e.target.value))}/></Field><Field label="Minimum published reviews before showing an average (1–50)"><input className={fieldClass} type="number" required min={1} max={50} step={1} value={config.minimumPerformanceSample} onChange={e=>change('minimumPerformanceSample',Number(e.target.value))}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={config.schedulesEnabled} onChange={e=>change('schedulesEnabled',e.target.checked)}/>Enable scheduled reporting</label></div><Field label="Reason for policy change"><textarea className={fieldClass} required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></Field><Button disabled={save.isPending||reason.trim().length<5}>Save reporting rules</Button>{save.isSuccess&&<p role="status">Reporting rules saved.</p>}{draft&&<Button type="button" variant="ghost" onClick={()=>{setDraft(null);setReason('');policy.refetch();}}>Discard draft and reload</Button>}</form>}<details className="space-y-3"><summary className="cursor-pointer font-medium">Policy change history</summary><QueryError error={history.error}/>{history.data?.items.length===0&&<p className="text-sm">Default rules are active; no policy changes yet.</p>}{history.data?.items.map(row=><div className="rounded border p-3 text-sm" key={row.version}><p className="font-medium">Version {row.version} · {new Date(row.created_at).toLocaleString()}</p><p>{row.reason}</p><pre className="mt-2 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify({turnoverDenominator:row.snapshot.turnover_denominator,config:row.snapshot.config||defaultAnalyticsPolicy},null,2)}</pre></div>)}<Pages page={page} setPage={setPage} more={history.data?.hasMore}/></details></Section>;
}
