import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {apiJson} from '@/lib/queryClient';
import {reportLabels,type ReportKind,type SavedReportInput} from '@shared/reporting';
import {Button} from '@/components/ui/button';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {pretty} from './ReportViewer';
export const reportsApi='/api/reporting/snapshots';
type Page={items:any[];hasMore:boolean};
export function Pages({page,setPage,more}:{page:number;setPage:(page:number)=>void;more?:boolean}){return <div className="flex items-center gap-3"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous page</Button><span className="text-sm">Page {page}</span><Button size="sm" variant="outline" disabled={!more} onClick={()=>setPage(page+1)}>Next page</Button></div>;}
const filters=(d:any)=>Object.entries(d.filters||{}).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>`${pretty(k)}: ${v}`).join(' · ')||'All authorized records';
export function ReportHistory({kinds,onOpen}:{kinds:ReportKind[];onOpen:(id:number)=>void}){
 const [page,setPage]=useState(1),[kind,setKind]=useState(''),[q,setQ]=useState(''),[draft,setDraft]=useState('');
 const list=useQuery<Page>({queryKey:[reportsApi+'/runs',{page,kind,q}]});
 return <Section title="Your saved report runs"><p className="text-sm text-muted-foreground">Immutable results, including scheduled runs. Only you can open these reports, while your current permissions still cover their source records.</p><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();setQ(draft);setPage(1);}}><Field label="Report type"><select className={fieldClass} value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="">All report types</option>{kinds.map(k=><option key={k} value={k}>{reportLabels[k]}</option>)}</select></Field><Field label="Search saved filters"><input className={fieldClass} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={100}/></Field><Button variant="outline">Search runs</Button></form><QueryError error={list.error}/>{list.isPending&&<p role="status">Loading runs…</p>}{list.data?.items.length===0&&<p>No saved runs match your search.</p>}<div className="divide-y">{list.data?.items.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-medium">#{row.id} · {reportLabels[row.report_type as ReportKind]}</p><p className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString()} · {filters(row)}</p></div><Button variant="outline" size="sm" onClick={()=>onOpen(row.id)}>Open run {row.id}</Button></div>)}</div><Pages page={page} setPage={setPage} more={list.data?.hasMore}/></Section>;
}
export function ReportViews({current,onLoad,kinds}:{current:SavedReportInput;onLoad:(d:SavedReportInput)=>void;kinds:ReportKind[]}){
 const cache=useQueryClient(),[page,setPage]=useState(1),[editing,setEditing]=useState<any>(null),[name,setName]=useState(''),[reason,setReason]=useState(''),[archive,setArchive]=useState(false),[replace,setReplace]=useState(false);
 const list=useQuery<Page>({queryKey:[reportsApi+'/views',{page}]});
 const save=useMutation({mutationFn:()=>apiJson(reportsApi+`/views/${editing.id}${archive?'/archive':''}`,archive?'POST':'PATCH',archive?{version:editing.version,reason}:{version:editing.version,reason,definition:{...(replace?current:editing.definition),name}}),onSuccess:()=>{setEditing(null);setReason('');cache.invalidateQueries({queryKey:[reportsApi+'/views']});}});
 return <Section title="Your saved views"><p className="text-sm text-muted-foreground">Views save filters, comparisons and column choices. Loading a view prepares the builder; generate a new snapshot to refresh its figures.</p><QueryError error={list.error||save.error}/>{list.isPending&&<p>Loading views…</p>}{list.data?.items.length===0&&<p>No saved views yet. Save one from the report builder.</p>}<div className="divide-y">{list.data?.items.map(row=><div key={row.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-medium">{row.definition.name}</p><p className="text-sm">{reportLabels[row.definition.kind as ReportKind]}</p><p className="text-xs text-muted-foreground">{filters(row.definition)} · Version {row.version}</p></div><div className="flex gap-2"><Button size="sm" disabled={!kinds.includes(row.definition.kind)} onClick={()=>onLoad(row.definition)}>Load view</Button><Button size="sm" variant="outline" onClick={()=>{setEditing(row);setName(row.definition.name);setReason('');setArchive(false);setReplace(false);save.reset();}}>Manage view</Button></div></div>)}</div>{editing&&<form className="space-y-3 rounded-lg border bg-muted/20 p-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><h3 className="font-medium">Manage {editing.definition.name}</h3><Field label="View name"><input required minLength={3} maxLength={120} className={fieldClass} value={name} onChange={e=>setName(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={replace} disabled={archive} onChange={e=>setReplace(e.target.checked)}/>Replace filters and columns with the current builder: {reportLabels[current.kind]}</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={archive} onChange={e=>setArchive(e.target.checked)}/>Archive this view (saved runs remain available)</label><Field label="Reason for change"><input required minLength={5} maxLength={1000} className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="flex gap-2"><Button disabled={save.isPending}>{archive?'Archive view':'Save view changes'}</Button><Button type="button" variant="ghost" onClick={()=>setEditing(null)}>Cancel</Button></div></form>}<Pages page={page} setPage={setPage} more={list.data?.hasMore}/></Section>;
}
export function ReportSchedules({current,onOpen,enabled}:{current:SavedReportInput;onOpen:(id:number)=>void;enabled:boolean}){
 const cache=useQueryClient(),[page,setPage]=useState(1),[editor,setEditor]=useState<any>(null),[name,setName]=useState(''),[cadence,setCadence]=useState('monthly'),[hour,setHour]=useState(8),[active,setActive]=useState(true),[reason,setReason]=useState(''),[replace,setReplace]=useState(false),[history,setHistory]=useState<number|null>(null),[historyPage,setHistoryPage]=useState(1);
 const list=useQuery<Page>({queryKey:[reportsApi+'/schedules',{page}]}),runs=useQuery<Page>({queryKey:[reportsApi+`/schedules/${history}/history`,{page:historyPage}],enabled:history!==null});
 const save=useMutation({mutationFn:()=>{const d=editor.id&&!replace?editor.definition:current,definition={name,kind:d.kind,filters:d.filters,cadence,hour,enabled:active,reason};return apiJson(reportsApi+'/schedules'+(editor.id?'/'+editor.id:''),editor.id?'PATCH':'POST',editor.id?{version:editor.version,definition}:definition);},onSuccess:()=>{setEditor(null);cache.invalidateQueries({queryKey:[reportsApi+'/schedules']});}});
 const run=useMutation({mutationFn:()=>apiJson<{created:number;failed:number;skipped:boolean}>(reportsApi+'/schedules/run-due','POST',{}),onSuccess:()=>{cache.invalidateQueries({queryKey:[reportsApi+'/schedules']});cache.invalidateQueries({queryKey:[reportsApi+'/runs']});if(history)cache.invalidateQueries({queryKey:[reportsApi+`/schedules/${history}/history`]});}});
 const edit=(row:any)=>{setEditor(row);setName(row.definition?.name||current.name);setCadence(row.definition?.cadence||'monthly');setHour(row.definition?.hour??8);setActive(row.enabled??true);setReason('');setReplace(false);save.reset();};
 return <Section title="Scheduled reports"><p className="text-sm text-muted-foreground">Reports are saved privately in this app. Daily uses yesterday, weekly uses the last completed Sunday–Saturday, and monthly uses the last completed calendar month. Current-record reports capture records when the job runs. All schedules use Qatar time.</p><p className="text-sm text-muted-foreground">The existing server checks periodically while awake. Free hosting may delay a run; after waking it captures the latest completed period without backfilling missed periods. No email or paid scheduler is required.</p>{!enabled&&<p role="status" className="rounded border p-3">An administrator has paused all scheduled report generation.</p>}<div className="flex flex-wrap gap-2"><Button onClick={()=>edit({})}>Schedule current builder</Button><Button variant="outline" disabled={run.isPending||!enabled} onClick={()=>run.mutate()}>Run my due schedules</Button></div>{run.data&&<p role="status">{run.data.skipped?'Scheduler is paused or busy.':`${run.data.created} reports created; ${run.data.failed} failed. Completed periods are not repeated. Retries wait at least 30 minutes.`}</p>}<QueryError error={list.error||save.error||run.error}/>
 {editor&&<form className="space-y-3 rounded-lg border bg-muted/20 p-4" onSubmit={e=>{e.preventDefault();save.mutate();}}><h3 className="font-medium">{editor.id?'Edit schedule':'Create schedule'}</h3><p className="text-sm">{reportLabels[(editor.id&&!replace?editor.definition.kind:current.kind) as ReportKind]} · {filters(editor.id&&!replace?editor.definition:current)}. Date filters are replaced with each completed period; comparisons are not scheduled.</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Schedule name"><input required minLength={3} maxLength={120} className={fieldClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Frequency"><select className={fieldClass} value={cadence} onChange={e=>setCadence(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></Field><Field label="Earliest hour (Qatar)"><input type="number" required min={0} max={23} step={1} className={fieldClass} value={hour} onChange={e=>setHour(Number(e.target.value))}/></Field></div>{editor.id&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/>Replace report and filters with the current builder</label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Schedule enabled</label><Field label="Reason for creating or changing the schedule"><input required minLength={5} maxLength={1000} className={fieldClass} value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className="flex gap-2"><Button disabled={save.isPending}>Save schedule</Button><Button type="button" variant="ghost" onClick={()=>setEditor(null)}>Cancel</Button></div></form>}
 {list.isPending&&<p>Loading schedules…</p>}{list.data?.items.length===0&&<p>No schedules yet.</p>}<div className="divide-y">{list.data?.items.map(row=><div key={row.id} className="space-y-2 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{row.definition.name} · {row.enabled?'Enabled':'Paused'}</p><p className="text-sm">{reportLabels[row.definition.kind as ReportKind]} · {pretty(row.definition.cadence)} after {String(row.definition.hour).padStart(2,'0')}:00 Qatar</p><p className="text-xs text-muted-foreground">{filters(row.definition)} · Last checked: {row.last_attempt_at?new Date(row.last_attempt_at).toLocaleString():'Not yet'}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>edit(row)}>Edit / pause</Button><Button size="sm" variant="outline" onClick={()=>{setHistory(row.id);setHistoryPage(1);}}>Run history</Button>{row.last_run_id&&<Button size="sm" onClick={()=>onOpen(row.last_run_id)}>Latest report</Button>}</div></div>{row.last_error&&<p role="alert" className="text-sm text-destructive">{row.last_error}</p>}</div>)}</div><Pages page={page} setPage={setPage} more={list.data?.hasMore}/>{history&&<div className="space-y-3 rounded border p-4"><h3 className="font-medium">Schedule #{history} · Run history</h3><QueryError error={runs.error}/>{runs.isPending&&<p>Loading scheduled runs…</p>}{runs.data?.items.length===0&&<p>No attempts recorded yet.</p>}{runs.data?.items.map(r=><div className="flex flex-wrap justify-between gap-2 border-b pb-2 text-sm" key={r.id}><div>{r.period_key} · {r.status} · {new Date(r.created_at).toLocaleString()}{r.error&&<p className="text-destructive">{r.error}</p>}</div>{r.report_run_id&&<Button size="sm" variant="outline" onClick={()=>onOpen(r.report_run_id)}>Open report</Button>}</div>)}<Pages page={historyPage} setPage={setHistoryPage} more={runs.data?.hasMore}/><Button variant="ghost" size="sm" onClick={()=>setHistory(null)}>Close schedule history</Button></div>}</Section>;
}
