import {useMemo,useState} from 'react';
import {useMutation} from '@tanstack/react-query';
import {BarChart,Bar,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {Download,Printer,Table2,ChartColumn} from 'lucide-react';
import {apiJson,apiRequest} from '@/lib/queryClient';
import {Button} from '@/components/ui/button';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import type {ReportRun,ReportSnapshot} from '@shared/reporting';
export const pretty=(key:string)=>key.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
export const display=(value:unknown)=>value==null?'—':typeof value==='number'?value.toLocaleString(undefined,{maximumFractionDigits:2}):String(value);
const chosenColumns=(s:ReportSnapshot,chosen:string[])=>{const selected=s.columns.filter(c=>!chosen.length||chosen.includes(c.key));return selected.length?selected:s.columns;};
const policyEntries=(policy:Record<string,unknown>):[string,unknown][]=>Object.entries(policy).flatMap(([key,value]):[string,unknown][]=>value&&typeof value==='object'?policyEntries(value as Record<string,unknown>):[[pretty(key),typeof value==='boolean'?value?'Enabled':'Disabled':typeof value==='string'?pretty(value):value]]);
const metric=(key:string,rows:ReportSnapshot['rows'])=>!['announcement_id'].includes(key)&&rows.some(r=>typeof r[key]==='number'||/^(basic_amount|net_amount|allowance_amount|deduction_amount|amount)$/.test(key));
const html=(v:unknown)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function printSection(s:ReportSnapshot,chosen:string[]){
 const columns=chosenColumns(s,chosen);
 return `<h1>${html(s.title)}</h1><p>${html(s.definition)}</p><p>Generated ${html(s.generatedAt)} · As of ${html(s.asOf)} (Qatar) · ${html(s.scopeLabel||'Authorized source records')}</p><p>Filters: ${html(JSON.stringify(s.filters))}</p><p>${Object.entries(s.summary).map(([k,v])=>html(pretty(k))+': '+html(display(v))).join(' · ')}</p>${s.notes.map(n=>'<p>'+html(n)+'</p>').join('')}<p>Saved policy: ${html(JSON.stringify(s.policy))}</p><p>All ${s.rows.length} saved rows. Selected columns; on-screen search and pagination do not limit this export.</p><table><thead><tr>${columns.map(c=>'<th>'+html(pretty(c.label))+'</th>').join('')}</tr></thead><tbody>${s.rows.map(r=>'<tr>'+columns.map(c=>'<td>'+html(display(r[c.key]))+'</td>').join('')+'</tr>').join('')}</tbody></table>`;
}
export default function ReportViewer({run,chosen,onColumns}:{run:ReportRun;chosen:string[];onColumns:(keys:string[])=>void}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(1),[sort,setSort]=useState<{key:string;desc:boolean}|null>(null),[measure,setMeasure]=useState(''),[group,setGroup]=useState(''),[compare,setCompare]=useState(false);
 const snapshot=compare&&run.snapshot.comparison?run.snapshot.comparison:run.snapshot;
 const columns=chosenColumns(snapshot,chosen);
 const rows=useMemo(()=>{const filtered=snapshot.rows.filter(row=>columns.some(c=>String(row[c.key]??'').toLowerCase().includes(search.toLowerCase())));if(sort)filtered.sort((a,b)=>{const av=a[sort.key],bv=b[sort.key];if(av==null)return bv==null?0:1;if(bv==null)return -1;const numeric=metric(sort.key,filtered),order=numeric?Number(av)-Number(bv):String(av).localeCompare(String(bv),undefined,{numeric:true});return sort.desc?-order:order;});return filtered;},[snapshot,search,sort,chosen]);
 const pages=Math.max(1,Math.ceil(rows.length/25)),shownPage=Math.min(page,pages);
 const metrics=snapshot.columns.filter(c=>metric(c.key,snapshot.rows)),selectedMetric=metrics.some(c=>c.key===measure)?measure:metrics[0]?.key;
 const groupKey=snapshot.kind==='performance'?'cycle':snapshot.kind==='payroll'?'currency':['expenses','benefits'].includes(snapshot.kind)?'unit':null;
 const groups=groupKey?Array.from(new Set(rows.map(r=>String(r[groupKey]??'Unspecified')))):[];
 const selectedGroup=groups.includes(group)?group:groups[0];
 const chartRows=rows.filter(r=>(!groupKey||String(r[groupKey]??'Unspecified')===selectedGroup)&&r[selectedMetric]!=null).slice(0,20).map(r=>({label:snapshot.columns.filter(c=>!metric(c.key,snapshot.rows)&&!['announcement_id','acknowledgement_required'].includes(c.key)).map(c=>r[c.key]).filter(v=>v!=null&&v!=='').join(' / '),value:Number(r[selectedMetric])}));
 const download=useMutation({mutationFn:async()=>{const response=await apiRequest(`/api/reporting/snapshots/runs/${run.id}.csv`),url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=`hr-report-${run.id}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
 const print=useMutation({mutationFn:async(popup:Window|null)=>{if(!popup)throw new Error('Allow pop-ups to print or save this report as PDF.');try{const fresh=await apiJson<ReportRun>(`/api/reporting/snapshots/runs/${run.id}`);popup.opener=null;popup.document.write('<!doctype html><html><head><title>HR report '+fresh.id+'</title><style>body{font:11px Arial,sans-serif;color:#172b36;margin:24px}h1{font-size:20px}table{border-collapse:collapse;width:100%;margin-top:16px}th,td{border:1px solid #ccd4d9;padding:5px;text-align:left;overflow-wrap:anywhere}thead{display:table-header-group}tr{break-inside:avoid}section+section{break-before:page}@page{size:landscape;margin:12mm}</style></head><body><section>'+printSection(fresh.snapshot,chosen)+'</section>'+(fresh.snapshot.comparison?'<section>'+printSection(fresh.snapshot.comparison,chosen)+'</section>':'')+'</body></html>');popup.document.close();popup.focus();popup.print();}catch(e){popup.close();throw e;}}});
 return <Section title={`${run.snapshot.title} · Run #${run.id}`}><div className="flex flex-wrap justify-between gap-3"><div className="text-sm text-muted-foreground"><p>{run.snapshot.scopeLabel} · Generated {new Date(run.created_at).toLocaleString()}</p><p>As of {snapshot.asOf} (Qatar) · {Object.entries(snapshot.filters).filter(([,v])=>v!=='').map(([k,v])=>`${pretty(k)}: ${v}`).join(' · ')||'All authorized records'}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>download.mutate()} disabled={download.isPending}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button variant="outline" size="sm" onClick={()=>print.mutate(window.open('','_blank'))} disabled={print.isPending}><Printer className="mr-2 h-4 w-4"/>Print / PDF</Button></div></div>
 <QueryError error={download.error||print.error}/><p className="text-sm">{snapshot.definition}</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(run.snapshot.summary).map(([key,value])=>{const previous=run.snapshot.comparison?.summary[key],delta=typeof value==='number'&&typeof previous==='number'?value-previous:null;return <div key={key} className="rounded-lg border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">{pretty(key)}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{display(value)}{key.endsWith('_percent')&&value!=null?'%':''}</p>{run.snapshot.comparison&&<p className="mt-1 text-xs text-muted-foreground">Previous: {display(previous)}{delta!=null?` · ${delta>0?'+':''}${display(delta)}${key.endsWith('_percent')?' pts':''}`:''}</p>}</div>;})}</div>
 {run.snapshot.comparison&&<div className="flex flex-wrap items-center gap-3"><Button variant={compare?'outline':'default'} size="sm" onClick={()=>{setCompare(false);setPage(1);}}>Selected period</Button><Button variant={compare?'default':'outline'} size="sm" onClick={()=>{setCompare(true);setPage(1);}}>Previous period</Button><span className="text-xs text-muted-foreground">Cards compare both periods; charts and rows show {compare?'previous':'selected'} period.</span></div>}
 <details className="rounded border p-3 text-sm"><summary className="cursor-pointer font-medium">Definitions, exclusions and saved rules</summary><ul className="my-3 list-disc space-y-1 pl-5">{snapshot.notes.map(n=><li key={n}>{n}</li>)}</ul><dl className="grid gap-2 sm:grid-cols-2">{policyEntries(snapshot.policy).map(([key,value],i)=><div key={i}><dt className="text-muted-foreground">{key}</dt><dd>{display(value)}</dd></div>)}</dl></details>
 <div className="grid items-end gap-3 sm:grid-cols-3"><Field label="Search saved rows"><input className={fieldClass} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Department, status, course…"/></Field>{metrics.length>0&&<Field label="Chart measure"><select className={fieldClass} value={selectedMetric||''} onChange={e=>setMeasure(e.target.value)}>{metrics.map(c=><option key={c.key} value={c.key}>{pretty(c.label)}</option>)}</select></Field>}{groupKey&&groups.length>0&&<Field label={`Chart ${pretty(groupKey)} (kept separate)`}><select className={fieldClass} value={selectedGroup} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g}>{g}</option>)}</select></Field>}</div>
 {chartRows.length>0&&<div className="rounded-lg border p-4"><h3 className="mb-3 flex items-center gap-2 text-sm font-medium"><ChartColumn className="h-4 w-4"/>{pretty(selectedMetric)}{groupKey?` · ${selectedGroup}`:''}</h3><div style={{height:Math.max(220,chartRows.length*34)}} role="img" aria-label={`${pretty(selectedMetric)} chart. Exact figures in the accessible table below.`}><ResponsiveContainer width="100%" height="100%"><BarChart data={chartRows} layout="vertical" margin={{left:10,right:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="label" width={150} tick={{fontSize:10}} tickFormatter={v=>String(v).length>27?String(v).slice(0,26)+'…':v}/><Tooltip formatter={(v:any)=>[display(v),pretty(selectedMetric)]}/><Bar dataKey="value" fill="#0e7490" radius={[0,4,4,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><p className="mt-2 text-xs text-muted-foreground">First {chartRows.length} matching nonblank rows in table order. Each bar is one saved group; no cross-currency or cross-cycle aggregation.</p></div>}
 <details className="text-sm"><summary className="cursor-pointer font-medium">Choose table / PDF columns</summary><div className="mt-2 flex flex-wrap gap-3">{snapshot.columns.map(c=><label key={c.key} className="flex items-center gap-2"><input type="checkbox" checked={columns.some(v=>v.key===c.key)} disabled={columns.length===1&&columns[0].key===c.key} onChange={e=>onColumns(e.target.checked?[...columns.map(v=>v.key),c.key]:columns.filter(v=>v.key!==c.key).map(v=>v.key))}/>{pretty(c.label)}</label>)}</div><Button className="mt-2" size="sm" variant="ghost" onClick={()=>onColumns([])}>Show all columns</Button></details>
 <div className="overflow-auto rounded border"><table className="w-full text-sm"><caption className="p-3 text-left"><Table2 className="mr-2 inline h-4 w-4"/>{rows.length} matching of {snapshot.rows.length} saved rows · Page {shownPage} of {pages}</caption><thead className="bg-muted/50"><tr>{columns.map(c=><th scope="col" className="whitespace-nowrap p-3 text-left" key={c.key} aria-sort={sort?.key===c.key?sort.desc?'descending':'ascending':'none'}><button type="button" className="text-left underline-offset-4 hover:underline" onClick={()=>{setSort({key:c.key,desc:sort?.key===c.key?!sort.desc:false});setPage(1);}}>{pretty(c.label)} {sort?.key===c.key?sort.desc?'↓':'↑':'↕'}</button></th>)}</tr></thead><tbody>{rows.slice((shownPage-1)*25,shownPage*25).map((r,i)=><tr key={i} className="border-t">{columns.map(c=><td className="p-3 align-top tabular-nums" key={c.key}>{display(r[c.key])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-6 text-center text-muted-foreground">No records match {search?'this search':'these report filters'}.</p>}</div><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">CSV includes every saved row and column. PDF includes every saved row and your selected columns. Both include comparisons.</p><div className="flex gap-2"><Button variant="outline" size="sm" disabled={shownPage<=1} onClick={()=>setPage(shownPage-1)}>Previous rows</Button><Button variant="outline" size="sm" disabled={shownPage>=pages} onClick={()=>setPage(shownPage+1)}>Next rows</Button></div></div></Section>;
}
