import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Copy,FileStack,Plus,ArrowLeft,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Field,Section,QueryError,fieldClass} from '@/components/hr/Operations';
import {apiJson} from '@/lib/queryClient';
import {blankContent,blankDraft,contentOf,templateSchema,templateIssues,type ContractTemplate,type TemplateSummary,type ContractClause} from '@shared/contracts';
import {ContentFields,ClauseEditor,DocumentPreview} from './ContractComposer';

const base='/api/contracts';
export default function TemplateLibrary({onUse}:{onUse?:(template:ContractTemplate)=>void}){
  const [search,setSearch]=useState(''),[q,setQ]=useState(''),[page,setPage]=useState(1);
  const [editor,setEditor]=useState<{id?:number;copy?:boolean}|null>(null);
  const list=useQuery<{items:TemplateSummary[];hasMore:boolean}>({queryKey:[base+'/templates',{q,page}]});
  const selected=useQuery<ContractTemplate>({queryKey:[base+'/templates/'+editor?.id],enabled:!!editor?.id});
  const choose=useMutation({mutationFn:(id:number)=>apiJson<ContractTemplate>(base+'/templates/'+id),onSuccess:template=>onUse?.(template)});
  if(editor)return <div className="space-y-4"><Button variant="ghost" onClick={()=>setEditor(null)}><ArrowLeft className="mr-2 h-4 w-4"/>All templates</Button><QueryError error={selected.error}/>{editor.id&&selected.isLoading?<p role="status">Opening template…</p>:(!editor.id||selected.data)&&<TemplateEditor key={`${editor.id||'new'}-${editor.copy||false}-${selected.data?.version||0}`} source={editor.id?selected.data:undefined} copy={editor.copy} close={()=>setEditor(null)}/>}</div>;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Contract templates</h2><p className="mt-1 text-sm text-muted-foreground">Reusable English–Arabic contracts. Every copy can be tailored.</p></div><Button onClick={()=>setEditor({})}><Plus className="mr-2 h-4 w-4"/>Create template</Button></div>
    <form className="flex gap-2" onSubmit={e=>{e.preventDefault();setQ(search);setPage(1);}}><input className={fieldClass} aria-label="Search templates" placeholder="Search template or category" maxLength={100} value={search} onChange={e=>setSearch(e.target.value)}/><Button variant="outline">Search</Button></form>
    <QueryError error={list.error||choose.error}/>{list.isLoading&&<p role="status">Loading templates…</p>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.data?.items.map(row=><article className="flex flex-col gap-4 rounded-2xl border bg-card p-5" key={row.id}><div className="flex justify-between gap-3"><span className="rounded-xl bg-primary/10 p-3 text-primary"><FileStack className="h-6 w-6"/></span><Badge variant={row.active?'secondary':'outline'}>{row.active?'Available':'Archived'}</Badge></div><div><h3 className="font-semibold">{row.name}</h3><p className="mt-2 text-xs text-muted-foreground">{row.category} · {row.clause_count} terms · v{row.version}</p></div><p className="flex-1 text-sm text-muted-foreground">{row.description}</p><div className="flex flex-wrap gap-2">{onUse&&<Button size="sm" disabled={!row.active||choose.isPending} onClick={()=>choose.mutate(row.id)}>Use template</Button>}<Button size="sm" variant="outline" onClick={()=>setEditor({id:row.id})}>Edit</Button><Button size="sm" variant="ghost" onClick={()=>setEditor({id:row.id,copy:true})}><Copy className="mr-2 h-4 w-4"/>Duplicate</Button></div></article>)}</div>
    {list.data&&!list.data.items.length&&<p className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">No templates match. Create one or change your search.</p>}
    {(page>1||list.data?.hasMore)&&<div className="flex items-center gap-3"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</Button><span className="text-sm">Page {page}</span><Button variant="outline" disabled={!list.data?.hasMore} onClick={()=>setPage(p=>p+1)}>Next</Button></div>}
    <p className="text-xs text-muted-foreground">Starter templates are editable starting points. HR reviews the final wording in both languages before sending.</p>
  </div>;
}
function TemplateEditor({source,copy,close}:{source?:ContractTemplate;copy?:boolean;close:()=>void}){
  const [name,setName]=useState(source?(copy?'Copy of '+source.name:source.name):''),[category,setCategory]=useState(source?.category||'Employment'),[description,setDescription]=useState(source?.description||'');
  const [active,setActive]=useState(source?.active??true),[document,setDocument]=useState(()=>source?contentOf(source.document):blankContent());
  const [tab,setTab]=useState('details'),[error,setError]=useState(''),[submissionKey]=useState(()=>crypto.randomUUID());
  const library=useQuery<ContractClause[]>({queryKey:[base+'/clauses']});
  const cache=useQueryClient();
  const save=useMutation({mutationFn:(input:unknown)=>apiJson(base+'/templates'+(source&&!copy?'/'+source.id:''),{method:source&&!copy?'PATCH':'POST',body:input}),onSuccess:()=>{void cache.invalidateQueries({predicate:q=>String(q.queryKey[0]).startsWith(base)});close();}});
  const submit=()=>{const parsed=templateSchema.safeParse({name,category,description,active,document});if(!parsed.success){setError(parsed.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; '));return;}const issues=templateIssues(parsed.data);if(issues.length){setError(issues.join(' '));return;}setError('');save.mutate({...parsed.data,...(source&&!copy?{version:source.version}:{submissionKey})});};
  return <div className="space-y-5"><Section title={source&&!copy?'Edit contract template':'Create contract template'}><p className="text-sm text-muted-foreground">Employee names and dates are filled on each contract. Template changes apply to future copies.</p><fieldset disabled={save.isPending} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Template name"><input className={fieldClass} value={name} maxLength={160} onChange={e=>setName(e.target.value)}/></Field><Field label="Category"><input className={fieldClass} value={category} maxLength={80} onChange={e=>setCategory(e.target.value)}/></Field></div><Field label="Description"><textarea className={fieldClass} rows={2} maxLength={600} value={description} onChange={e=>setDescription(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Available for new contracts</label></fieldset></Section>
    <fieldset disabled={save.isPending} className="min-w-0"><Tabs value={tab} onValueChange={setTab}><TabsList className="flex h-auto flex-wrap justify-start"><TabsTrigger value="details">1 · Details</TabsTrigger><TabsTrigger value="terms">2 · Terms</TabsTrigger><TabsTrigger value="preview">3 · Preview</TabsTrigger></TabsList><TabsContent value="details"><Section title="Default contract content"><p className="text-sm text-muted-foreground">Leave employee-specific fields blank for HR to complete on each copy.</p><ContentFields value={document} onChange={setDocument}/></Section></TabsContent><TabsContent value="terms"><Section title="Template terms"><details className="rounded-xl bg-muted/50 p-3 text-xs"><summary className="cursor-pointer font-medium">Reusable employee fields</summary><p className="mt-2 break-words">{'English: {{employee_name}}, {{position}}, {{department}}, {{location}}'}</p><p className="mt-2 break-words">{'Arabic: {{employee_name_ar}}, {{position_ar}}, {{department_ar}}, {{location_ar}}'}</p></details><QueryError error={library.error}/><ClauseEditor clauses={document.clauses} onChange={clauses=>setDocument(d=>({...d,clauses}))} library={library.data}/></Section></TabsContent><TabsContent value="preview"><DocumentPreview template document={{...blankDraft(),...document,companyName:'Company from Settings',companyAddress:'',employeeName:'',employeeReference:''}}/></TabsContent></Tabs></fieldset>
    {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<QueryError error={save.error}/><div className="sticky bottom-20 flex flex-wrap justify-end gap-3 rounded-xl border bg-card p-4 shadow-lg md:bottom-4"><Button variant="ghost" disabled={save.isPending} onClick={close}>Cancel</Button><Button disabled={save.isPending} onClick={submit}><Save className="mr-2 h-4 w-4"/>{save.isPending?'Saving…':'Save template'}</Button></div>
  </div>;
}
